### ISSUE TITLE
Extending C++ classes in Python

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#1002]
Hello Pybind11 developers,

I trying to extend Pybind11 bound class in Python (inject new method to the bound C++ classes in Python, functionality similar to: http://www.boost.org/doc/libs/1_64_0/libs/python/doc/html/tutorial/tutorial/techniques.html#tutorial.techniques.extending_wrapped_objects_in_pyt) And so far it looks like there is no additional C++ flags/code needed to enable this. Obviously simple extension on Python side will work for object created in Python but for objects created in C++ Boost require some extra code. Could you please confirm that Pybind11 classes does not need any extra tweaks to make this happened? Please find minimal example below.

Thanks,

```C++
#include <pybind11/pybind11.h>
#include <iostream>

struct Value {
	int a, b;
};

Value create_value() { return Value(); }

namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

	pybind11::class_<Value> cl(m, "Value");
	cl.def(pybind11::init<>());
	cl.def_readwrite("a", &Value::a);
	cl.def_readwrite("b", &Value::b);

	m.def("create_value", &create_value);

    return m.ptr();
}
```

```Python
from example import *

Value.__str__ = lambda s: "Value({}, {})".format(s.a, s.b)
Value.foo = lambda s: s.a+s.b

print( 'Value create in Python: {} {}'.format( Value(), Value().foo() ) )
print( 'Value create in C++: {} {}'.format( create_value(), create_value().foo() ) )
```

**Comment by dean0x7d** [comment]
> Obviously simple extension on Python side will work for object created in Python but for objects created in C++ Boost require some extra code. Could you please confirm that Pybind11 classes does not need any extra tweaks to make this happened?

As far as I remember this works exactly the same in Boost.Python as your example above. Because the type object is mutated directly, the changes will affect instances created both in Python and from C++.

**Comment by lyskov** [comment]
Great, thank you for checking on this @dean0x7d !
