### ISSUE TITLE
Build and install Pythons are not sanity checked against each other

### ISSUE THREAD

**Issue by mathstuf** [pybind/pybind11#1008]
## Issue description

When building Pybind11, it finds a certain Python. It then refinds Python when used from an install tree. However, there is no sanity check that they Pythons are compatible with each other. It can be built against 2.7, but then find 3.5 at install time. An error should be raised if the major (and probably minor) version numbers do not match.

**Comment by mathstuf** [comment]
Cc: @johnkit

**Comment by jagerman** [comment]
What issue would there be with a 2.7 build followed by a 3.5 build cause?  Given that an installation is just installing headers (which can be used with any supported python version), it doesn't seem like a major problem to have such a mismatch.

**Comment by mathstuf** [comment]
Oh, embed is also just an interface library. Sorry about that; I thought it was a real library.
