### ISSUE TITLE
Enum class doesn't show in the correct namespace/submodule in help of methods that uses them

### ISSUE THREAD

**Issue by patrikhuber** [pybind/pybind11#1017]
Hi!

This might be a user error, but I think this looks like a bug to me.

MWE:

```
namespace ns {
    struct Pet {
        enum class Enum { val1, val2 };
    };
}

namespace f {
    void func(ns::Pet::Enum en) { return; }
}

PYBIND11_MODULE(mod, m) {
    py::class_<ns::Pet> pet(m, "Pet");

    pet.def(py::init<ns::Pet>());

    py::enum_<ns::Pet::Enum>(pet, "Enum")
        .value("Dog", ns::Pet::Enum::val1)
        .value("Cat", ns::Pet::Enum::val2)
        .export_values(); // with and without this line - it's the same result

    m.def("func", &f::func);
}
```

The enum is correctly usable as `mod.Pet.Enum`, however, the documentation for `func` is wrong (`help(mod.func)`):

> FUNCTIONS
    func(...) method of builtins.PyCapsule instance
        func(arg0: mod.Enum) -> None

where this should show mod.Pet.Enum.

**Comment by YannickJadoul** [comment]
I've also noticed this before, but I think it's a Python 2 thing.
Can you have a look and for example try nesting classes in pure Python code, as a test? Something like
```Python
class A(object):
    class B(object):
         class C(object):
              pass
```
As far as I remember (and just tested), this gives the same problem when calling `help` on one of these classes?

Interestingly, Python 3 does seem to handle this correctly.

**Comment by patrikhuber** [comment]
@YannickJadoul I am compiling with Python-3.6 though (Win64).

**Comment by YannickJadoul** [comment]
Ah, I haven't actually tried a pybind11 module on Python 3 with that amount of nesting, though (it's just the pure python example that gives the same, wrong result on Python 2 but a different, correct one on Python 3).
So maybe that's then indeed a minor pybind bug.

**Comment by patrikhuber** [comment]
I can confirm that this is fixed in the latest pybind11. I just found #1166 (that issue got opened 3 months after this one, and it looked like exactly the same problem), and it was probably the fixes there that fixed this too.
