### ISSUE TITLE
pybind11.get_include returns wrong path

### ISSUE THREAD

**Issue by garth-wells** [pybind/pybind11#1024]
`pybind11.get_include()` does not return where the pybind11 headers are actually installed. It returns where pip would have installed by default.

To reproduce:
```
pip3 install --install-option="--prefix=/tmp/pyb" .
```
and then run
```
export PYTHONPATH=/tmp/pyb/lib/python3.5/site-packages/
python3 -c "import pybind11; print(pybind11.get_include()); print(pybind11.get_include(True))"
```

**Comment by dean0x7d** [comment]
What output do you expect? AFAIK, independent of any pip options, the headers are always installed in the Python include dir (where Python's headers are) or in `$HOME/.local/include`, and that's exactly what `pybind11.get_include()` and `pybind11.get_include(True)` report.

**Comment by garth-wells** [comment]
I didn't realise that pip doesn't respect `--prefix`. I was expecting behaviour along the lines of how NumPy installs headers.

Related, `python setup.py install` doesn't install the headers. Maybe an error should be raised, or a warning that pip should be be used to install.
