### ISSUE TITLE
Addition to Upgrade Guide for v2.2

### ISSUE THREAD

**Issue by henryiii** [pybind/pybind11#1048]
In upgrading a codebase to v2.2, I've noticed that pybind now cares about l-value references matching in constructors. So this used to work:

```cpp
#include <pybind11/pybind11.h>
namespace py = pybind11;

struct Test {
    Test(int &i) {};
};

PYBIND11_PLUGIN(sample) {
    py::module m("sample", "");
    py::class_<Test>(m,"Test")
        .def(py::init<int>());
    return m.ptr();
}
```

But now gives an error unless changed to this:
```cpp
        .def(py::init<int&>());
```

Which is much better, but should be mentioned in the upgrade guide to save others time figuring out the new build failure with a slightly cryptic error message.

PS: `PYBIND11_MODULE` and `python -m pybind11 --includes` are both nice for quick examples like this, I actually used the latter to make the include line that I used after switching back to 2.1 in my venv.

**Comment by dean0x7d** [comment]
Interesting, I didn't know that this compiled with the previous version. It's definitely good that it doesn't anymore. Have you noticed anything else, or is it just non-const lvalue references?

**Comment by henryiii** [comment]
I think just that. I only had that mistake a few times, and playing with other combinations in the above code seems to behave correctly except for const or non-const lvalue references. `&&` doesn't work at all in 2.1, but that's expected, if I remember the release notes correctly. Const seems to be handled correctly if there's a mis-match.
