### ISSUE TITLE
STL vector caster doesn't work with temporaries in v2.2.0

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#1051]
Line 162 in `stl.h` should be `auto const &` instead of `auto &` in order to work with temporaries (such as bit vector references), I believe.

**Comment by dean0x7d** [comment]
Should be fixed in #1053. The fix uses `auto &&` to still allow forwarding for more efficient casting of rvalues.

**Comment by pschella** [comment]
Thanks!
