### ISSUE TITLE
Pickle support type matching problem

### ISSUE THREAD

**Issue by hkaiser** [pybind/pybind11#1061]
pybind V2.2.0, still happening on top of master:

Adding bindings for pickle support like this:
```
struct foo {};

py::class_<foo>(foo, "foo")
    .def(py::pickle(
        [](foo const& d) -> std::string { return std::string("foo"); },
        [](std::string const& str) -> foo { return foo{}; }
    ));
```
produces a compilation error:

    The type returned by `__getstate__` must be the same as the argument accepted by `__setstate__`

even if it should work just fine.

**Comment by dean0x7d** [comment]
Thanks for reporting! Should be fixed in #1064.
