### ISSUE TITLE
What is the difference between PYBIND11_MODULE and PYBIND11_PLUGIN ?

### ISSUE THREAD

**Issue by NaniBird** [pybind/pybind11#1066]
Hi,
I see online a lot of people using each interchangeably.
Thank you.

**Comment by dean0x7d** [comment]
`PYBIND11_MODULE` is new in v2.2, [as explained in the docs](http://pybind11.readthedocs.io/en/latest/upgrade.html#v2-2).

For quick questions like this, please post in the [Gitter chat room](https://gitter.im/pybind/Lobby).
