### ISSUE TITLE
Constructor signature matching fail.

### ISSUE THREAD

**Issue by JendaPlhak** [pybind/pybind11#1070]
## Issue description

Hi, after release of version 2.2 I have encountered problem with binding constructor of vector. 

What I would like to do is bind vector's constructor which constructs vector of n elements with given value. Instead it matches initializer list constructor and the below Python code prints 2, as it constructs vector of two elements (10, 2) instead of vector of 10 elements equal to 2. 

Minimal example is following:

```
#include <vector>
#include <pybind11/pybind11.h>

namespace py = pybind11;

PYBIND11_MAKE_OPAQUE(std::vector<uint32_t>);

PYBIND11_MODULE(_test, m) {
    using Container = std::vector<uint32_t>;
    using T = typename Container::value_type;

    py::class_<Container, std::shared_ptr<Container>>(m, "VectorUint32")
    .def(py::init<Container::size_type, const T&>())
    .def("__len__", &Container::size);
}
```
```
from test import _test

if __name__ == '__main__':
    vec = _test.VectorUint32(10, 2)
    print(len(vec))
```

On Ubuntu 16.04 with gcc version 7.1.0 or 6.3 the compiler produces warning which is fine, but I still have no idea how to make it work properly.

```
In file included from /usr/local/include/python3.6/pybind11/pybind11.h:46:0,
                 from test.cpp:2:
/usr/local/include/python3.6/pybind11/detail/init.h: In instantiation of ‘pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...)::<lambda(pybind11::detail::value_and_holder&, Args ...)> [with Class = pybind11::class_<std::vector<unsigned int>, std::shared_ptr<std::vector<unsigned int, std::allocator<unsigned int> > > >; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {long unsigned int, const unsigned int&}]’:
/usr/local/include/python3.6/pybind11/detail/init.h:163:29:   required from ‘struct pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<std::vector<unsigned int>, std::shared_ptr<std::vector<unsigned int, std::allocator<unsigned int> > > >; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {long unsigned int, const unsigned int&}]::<lambda(struct pybind11::detail::value_and_holder&, long unsigned int, const unsigned int&)>’
/usr/local/include/python3.6/pybind11/detail/init.h:163:9:   required from ‘static void pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<std::vector<unsigned int>, std::shared_ptr<std::vector<unsigned int, std::allocator<unsigned int> > > >; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {long unsigned int, const unsigned int&}]’
/usr/local/include/python3.6/pybind11/pybind11.h:1096:9:   required from ‘pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const pybind11::detail::initimpl::constructor<Args ...>&, const Extra& ...) [with Args = {long unsigned int, const unsigned int&}; Extra = {}; type_ = std::vector<unsigned int>; options = {std::shared_ptr<std::vector<unsigned int, std::allocator<unsigned int> > >}]’
test.cpp:13:52:   required from here
/usr/local/include/python3.6/pybind11/detail/init.h:164:31: warning: narrowing conversion of ‘std::forward<long unsigned int>(args#0)’ from ‘long unsigned int’ to ‘unsigned int’ inside { } [-Wnarrowing]
             v_h.value_ptr() = new Cpp<Class>{std::forward<Args>(args)...};
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/python3.6/pybind11/detail/init.h:164:31: warning: narrowing conversion of ‘std::forward<long unsigned int>(args#0)’ from ‘long unsigned int’ to ‘unsigned int’ inside { } [-Wnarrowing]```

**Comment by YannickJadoul** [comment]
I think this has got to do with the fact that this construction has recently been changed to work with brace-initialization instead of 'ordinary' parentheses to call the constructor (cfr. #1015). Since vector also accepts an `initializer_list`, this one get preferred (even though a `long unsigned int` needs to get converted to an `unsigned int` in order to match the vector's type).
In other words, when looking at the [`std::vector` constructor) documentation](http://en.cppreference.com/w/cpp/container/vector/vector), (8) is called instead of (2).

Quick solution: replace `py::init<...>()` by `py::init([](Container::size_type s, const T &t) { return Container(s, t); })`, choosing explicitely for `()` instead of `{}` for the constructor.

On the other hand, this feels rather unintuitive on pybind11's part...

**Comment by JendaPlhak** [comment]
Yes, that was my guess too. The way I see it explicit constructor should take precedence before initializer_list. The question is, why is it not so? And will it be fixed or are there some deeper reasons for this behaviour?

**Comment by YannickJadoul** [comment]
As far as I know, #1015 was a rather recent change, allowing for easy construction of POD structs/classes. Also, this issue was brought up, it seems, but a note was made in the docs: http://pybind11.readthedocs.io/en/stable/advanced/classes.html#brace-initialization

**Comment by YannickJadoul** [comment]
This now seems to compile and work in 2.5.
