### ISSUE TITLE
Intersection of overloads and std::function<>

### ISSUE THREAD

**Issue by jcelerier** [pybind/pybind11#1085]
I'd like to have multiple overloads that take different kinds of functions in parameters:

      .def(
          "add_callback",
          [](foo& addr, std::function<void(int)> clbk) { ... })
      .def(
         "add_callback",
          (foo& addr, std::function<void(foo&, int)> clbk) { ... })

But the following python code fails:

    def fun_callback(foo, val):
      print(...)

    my_foo.add_callback(fun_callback)
          
with:

    TypeError: fun_callback() missing 1 required positional argument: 'val'

The first overload works, and renaming the second overload to another function name (for instance add_callback2) works too. 

Is there a way around this ?

**Comment by henryiii** [comment]
Quick note: you must be compiling in C++14, or at least with a C++14 supporting compiler, in order for the compiler to be able to tell the difference between differing signatures in `std::function`. This might be related.

**Comment by YannickJadoul** [comment]
Wouldn't the problem be that a Python function cannot 'match a typed overload', in general, because of Python's duck-typing?

**Comment by jcelerier** [comment]
> Quick note: you must be compiling in C++14, or at least with a C++14 supporting compiler,

yep, I am (using g++ 7.2).

> Wouldn't the problem be that a Python function cannot 'match a typed overload', in general, because of Python's duck-typing?

hmm... yes, that would make sense. If I understand correctly, there is a single "function" type from Python's side ?

**Comment by YannickJadoul** [comment]
> hmm... yes, that would make sense. If I understand correctly, there is a single "function" type from Python's side ?

I think so. Or not even, actually. There's just 'things that can be called' (i.e., I'm guessing you could perfectly pass an object with the `__call__` method implemented). Either way, these things typically only get caught once they are used, in Python.

On the other hand, doesn't Python allow some kind of introspection, either? But then I don't know if pybind uses that.

**Comment by YannickJadoul** [comment]
> On the other hand, doesn't Python allow some kind of introspection, either? But then I don't know if pybind uses that.

Answer: nope, looking at `functional.h`.
```C++
        if (!isinstance<function>(src))
            return false;

// ...

        value = [func](Args... args) -> Return {
            gil_scoped_acquire acq;
            object retval(func(std::forward<Args>(args)...));
            /* Visual studio 2015 parser issue: need parentheses around this expression */
            return (retval.template cast<Return>());
        };
```

**Comment by jcelerier** [comment]
okay, I guess I'll just give my function another name ! thanks
