### ISSUE TITLE
Can't pass None to pybind11::slice

### ISSUE THREAD

**Issue by jbarlow83** [pybind/pybind11#1095]
## Issue description

The definition of `pybind11:slice` does not allow one to create a slice object where one of start, stop, step are None, since the only constructor requires all three be of type ``ssize_t``.

From https://github.com/pybind/pybind11/blob/master/include/pybind11/pytypes.h#L1062:

```c++
    slice(ssize_t start_, ssize_t stop_, ssize_t step_) {
        int_ start(start_), stop(stop_), step(step_);
        m_ptr = PySlice_New(start.ptr(), stop.ptr(), step.ptr());
        if (!m_ptr) pybind11_fail("Could not allocate slice object!");
    }
```

Slicing notation places uses None whenever the index is variable, e.g. `somelist[:]` means `slice(None, None, None)`. 

Specifically one cannot create a slice that asks for all elements of a list reversed without constructing a slice that has `stop=None`.

```python
>>> l = [1,2,3,4,5]
>>> l[::-1]  # Requires start=None, stop=None, step=-1
[5,4,3,2,1]
>>> l[5:0:-1]
[5,4,3,2]  # stop=0 terminates the list *before* the 0th element
>>> l[5:-1:-1]
[] # stop=-1 terminates the list before the final element
```

Of course PySlice_New can be called but the pybind API is quite nice :).

**Comment by henryiii** [comment]
Could this be done with a pointer constructor? `slice(ssize_t* start_, ssize_t* stop_, ssize_t* step_)` where `nullptr` is `None`? Or a C++17 optional interface might be nice.

**Comment by jbarlow83** [comment]
The case where I ran into this was trying to create a C++ class whose Python bindings would give it list like semantics.

Suppose I have this. Existing class Thing, for which I've written a helper that uses its API to get items out of the Thing in py::list. I did it that way so I can use the implementation to implement `__getitem__` and `reverse`.

```c++

py::list getItemList(Thing &t, py::slice slice)
{
     size_t start, stop, step, slicelength;
     if (!slice.compute(t.count(), &start, &stop, &step, &slicelength))
        throw py::error_already_set();
     py::list result;
     for (size_t i = 0; i < slicelength; ++i) {
        Item item = t.getItem(start);
        result.append(item);
        start += step;
     }
     return result;
}

py::class_<Thing>(...)
    .def("__getitem__",
            [](Thing &t, py::slice slice) {
                getItemList(t, slice);
            }
    )
    .def("reverse", 
            [](Thing &t) {
                py::slice ordinary_indices(0, t.count(), 1);                
                py::int_ step(-1);
                PyObject *raw_slice = PySlice_New(Py_None, Py_None, step.ptr());
                py::slice reversed_slice = py::reinterpret_steal<py::slice>(raw_slice);
                py::list reversed = getItemList(t, reversed_slice);
                setItemsFromIterable(t, ordinary_indices, reversed);
            }
    );
```

**Comment by yxlao** [comment]
Casting to CPython's `PySliceObject*` works for me. Also, you may use `py::detail::PyNone_Check` to check if a `PyObject` is None. It looks like this:

```cpp
tensor.def("__getitem__", [](const Tensor& tensor, py::slice key) {
    const PySliceObject* slice_key =
            reinterpret_cast<const PySliceObject*>(key.ptr());
    std::cout << "start is None: "
                << py::detail::PyNone_Check(slice_key->start) << std::endl;
    std::cout << "step is None: "
                << py::detail::PyNone_Check(slice_key->step) << std::endl;
    std::cout << "stop is None: "
                << py::detail::PyNone_Check(slice_key->stop) << std::endl;
    // ...
});
```
