### ISSUE TITLE
Is here a str object leaked ?

### ISSUE THREAD

**Issue by complyue** [pybind/pybind11#1102]
I just started using pybind, and new to C++11 (but experienced with old school C++), to my current understanding to the semantics, the returned `str` object from `pybind11::str(format)` at this line:
https://github.com/pybind/pybind11/blob/0aef6422a349e498410c4a06b9decc04addd8c25/include/pybind11/numpy.h#L426
should be *moved* to `object args` at this line:
https://github.com/pybind/pybind11/blob/0aef6422a349e498410c4a06b9decc04addd8c25/include/pybind11/numpy.h#L443

And if so, given `args.release()` is called here, I suspect the intermediate `str` object should keep its refcnt==1 after both function returned.

Am I wrong?
Sorry I'm not familiar enough with pybind or Py C-API to code verify this.

**Comment by jagerman** [comment]
Good find!  `PyArray_DescrConverter` indeed just borrows the object reference rather than stealing it.  I suspect the `release()` was copy and pasted from one of the other numpy API invocations that do steal a reference to the argument.

Fixed in c6a57c10
