### ISSUE TITLE
PYBIND11_PLUGIN macro replacement

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#1115]
Dear Pybind11 developers,

I read the upgrade guide http://pybind11.readthedocs.io/en/master/upgrade.html#deprecation-of-the-pybind11-plugin-macro  and it state that `PYBIND11_PLUGIN` is now deprecated in favor of `PYBIND11_MODULE`.

This new macro however manually creating module object and this makes it use in my project (https://github.com/RosettaCommons/binder) problematic since i need to be able to create root module object dynamically. So wonder: will it possible to either provide an alternative to `PYBIND11_PLUGIN` macro that does not create module object or provide an alternative to macro that do so?

Thanks,

**Comment by henryiii** [comment]
For something as specialized as binder, couldn't you just make your own copy of the `#define` manually and change what you need, thereby directly using the internals of pybind11? In fact, I assume you could just copy the `PYBIND_PLUGIN` macro to `BINDER_PLUGIN` and remove the `PYBIND11_DEPRECATED` line. What those two macros do is pretty simple, so I don't think it's likely to change in a way that would affect Binder.

Just my 2¢ suggestion.

https://github.com/pybind/pybind11/blob/d81d11a61caa6fdfdceb10cd272aef776fa7254f/include/pybind11/detail/common.h#L225-L251

**Comment by lyskov** [comment]
Well, while i certainly can do this, the problem is that that way i (and everyone else who need this functionality) will need to maintain such macros which could be challenging for ppl who know little about inner machinery of Pybind11 and how modules are setup...

**Comment by jagerman** [comment]
Macro expansion is something that in general we want t oavoid--the macro contents are treated like `detail`-namespace code and could change between versions.

Undeprecating `PYBIND11_PLUGIN` is a potential option, but I wonder if something better can't be done.

For example, looking at `context.cpp`, I think you could change it to PYBIND11_MODULE, change your `std::map<std::string, std::shared_ptr<py::module>>` to just a `std::map<std::string, py::module>`, and then stash `modules[""] = m;`.

(`py::module` is already just a Python object wrapper, which means Python already has its shared object semantics around the object--i.e. the module won't be destroyed as long as a `py::module` exists, and copies are essentially already shared-pointer-like instances).

**Comment by lyskov** [comment]
Aha, awesome - i did not know that py::module is already shared-pointer-like object - thank you for sharing this @jagerman ! That will definitely makes things easier. I will close this issue for now then.
