### ISSUE TITLE
how to cast from user-defined type

### ISSUE THREAD

**Issue by drubin6** [pybind/pybind11#1119]
I am trying to cast between a user-defined type and py::object, but clearly I'm doing it wrong. You can imagine that `foo` is a Python callback function and the program is a unit test of a C++ library component.

```C++
#include <pybind11/embed.h>
#include <pybind11/pybind11.h>

struct Acknowledgment {};  // empty

void foo(pybind11::object arg)
{
    (void)arg.cast<Acknowledgment>();  // throw on error
}

int main()
{
    pybind11::scoped_interpreter guard;

    Acknowledgment acknowledgment;
    foo(pybind11::cast(acknowledgment));  // <--- cast error here
    return 0;
}
```

**Comment by YannickJadoul** [comment]
Well, where have you defined how that object should be converted to Python? Do you have a `pybind11::class_<Acknowledgement>(...)` binding being constructed, somewhere?

**Comment by drubin6** [comment]
That's the thing. I'm not sure how to define "how that object should be converted."  IIUC `py::class_<T>` is the API by which you define the Python interface to C++ types. In this case, I have some library function (`foo`) that needs to call a Python function with an `Acknowledgment`. Should that library component depend on the  header in which `py::class_<Acknowledgment>` is defined? That presents some issues because the caller of `foo` is implemented in a component (.h/.cpp pair) that defines a type that is also exposed to Python through the `py::class_<T>` API, so there would be a circular dependency between these two components.

**Comment by YannickJadoul** [comment]
I don't completely understand the details of your use case, but if you need to call a Python function with an `Acknowledgment` object, that function should have access to a Python `Acknowledgment` type.

Let's maybe make this more concrete:
Suppose you have
```
def foo(ack):
   print type(ack)
   return 42
```
and you call that function as before
```
// Import the Python module so we can call foo...
Acknowledgment acknowledgment;
foo(pybind11::cast(acknowledgment));
```

What would you expect that thing to print? The moment you call `pybind11::cast` that object 'lives in the Python interpreter' and needs to have a Python type, etc. Constructing `py::class_<Acknowledgment>(module, "PythonAcknowledgment")` before does that: it does not just 'define the Python interface', but creates a new Python class type `PythonAcknowledgment` and registers the mapping between the C++ `Acknowledgment` and Python `PythonAcknowledgment`.

**Comment by drubin6** [comment]
Okay, I added this line between the definitions of `Acknowledgment` and `foo`, but the program still crashes:
```
PYBIND11_MODULE(xxx, m) { pybind11::class_<Acknowledgment>(m, "Acknowledgment").def(pybind11::init<>()); }
```

**Comment by YannickJadoul** [comment]
Errors or throws a casting exception?

The `class_` constructor executes certain pieces of code to add the class to the Python module and register the conversion, so you need to have this `class_` constructed before you can use the conversion. So the exact way of solving this depends on your further architecture:
- If you want to have a separate Python module that's imported by different other modules that need to use the `Acknowledgment` type, then indeed, you probably want to use `PYBIND11_MODULE`. But, since this creates a Python extension module, this needs to be compiled separately to a `.pyd`/`.so` shared library (in a separate compilation unit, etc.). After that, you should be able to use `py::import` to import this Python library and use the types.
- But what you're currently showing, you just want to have that type conversion, so just put `pybind11::module m("xxx"); pybind11::class_<Acknowledgment>(m, "Acknowledgment").def(pybind11::init<>());` at the start of your `main` function. (But I don't know the overall structure of your project, why you actually need to pass through Python, what other parts of the project need to access these type conversions, etc, etc)

**Comment by YannickJadoul** [comment]
But what's the actual point of casting to a Python type? Do you basically want an oblique type that just passes from C++ to C++ through Python but is never accessed by any Python code, or is there something more to it?

**Comment by jagerman** [comment]
cpp_function is an intermediate class that you almost never should deal with directly; instead you want to attach your function to the module with `m.def([](...) { ... });`.

I suggest taking a read through the documentation which covers this in a fair bit of detail.

**Comment by drubin6** [comment]
Okay! It's starting to come together for me. Thank you. But you're right, I need to consider the overall architecture. Indeed, my actual program is described by your first bullet point. I have a `PYBIND11_MODULE` that exposes `Acknowledgment` and some other class called `Messenger`. This binding is implemented in a `plugin` component. `Messenger`, implemented in the `messenger` component, exposes a method, `sendMessage()`, that takes a Python callback having the signature `Callable[Union[str, Acknowledgment], None]`. You can call it with either a string (message) or an acknowledgment, and implementations will test the argument appropriately. This component header `plugin.h` is like this:
```C++
PYBIND11_MODULE(xxx, m1) {
    pybind11::module m2("tx", m1);

    pybind11::class_<Acknowledgment>(m2, "Acknowledgment")
        .def(pybind11::init<>());

    pybind11::class_<Messenger>(m2, "Messenger")
        .def(pybind11::init<>())
        .def("send_message", &Messenger::sendMessage,
                pybind11::arg("message"), pybind11::arg("callback"));
}
```

In Python, I can write something like
```Python
from typing import Union
import xxx.tx

def callback(arg: Union[str, xxx.tx.Acknowledgment]): -> None:
    # ...

xxx.tx.Messenger messenger
messenger.send_message("hello", callback)
```

The C++ implementation of `Messenger.sendMessage()` takes the callback as `stl::function<void(pybind11::object)>`. What I am trying to model in my `main` program is a **unit test driver** for the `messenger` component. What I understood from this discussion is that the the definition of the Python `Acknowledgment` type has to be visible to the `messenger` component.  However, IIUIC, I cannot define the Python `Acknowledgment` type twice. I also cannot create a circular reference between the `messenger` and `plugin` components. It seems that, additionally, I cannot "open the `xxx` namespace" twice by writing `PYBIND11_MODULE(xxx, m1)` in two different components.

I appreciate that the circular reference constraint and component terminology may be unfamiliar, but if you follow me so far and have additional suggestions, they would be well received.

**Comment by YannickJadoul** [comment]
I am of course familiar with circular references, but I am failing to see where exactly in your problem it would be :-)

As far as I see, the Python module (with `callback`) clearly depends on the binary Python extension made with pybind11 (with `Acknowledgment` and `Messenger`). And a test suite would of course depend on these two modules, too. But why would anything depends on this main/test module?

As far as I know, you don't need to define the `Acknowledgment` type again in the latter main/test code. Just importing the pybind11 module should be enough, because it shares its bindings if I am correct (if both parts are compiled with the same version of pybind11, that is!). So, if you `pybind11::import` this module, doesn't that solve the problem?

Also, maybe you should have a look at the structure of the pybind11 unit tests. There's quite a lot of them, so it might inspire you on how to do this?

**Comment by drubin6** [comment]
This is how I imagine the components:

* acknowledgement.{h,cpp} ~ define `Acknowledgement`
* messenger.{h,cpp} ~ define `Messenger` / include `acknowledgment`
* plugin.{h,cpp} ~ define PYBIND11_MODULE / include `acknowledgment` and `messenger`

In order for `Messenger::sendMessage()` to call the callback with `Acknowledgment`, it needs to also include `plugin.h`, so there is a circular reference.

**Comment by jagerman** [comment]
The cleanest approach here would be to make acknowledgment and messenger purely c++. Then plugin uses pybind to provide the Python wrapper around the c++ objects and functions.

**Comment by jagerman** [comment]
You can even build them into separate `.so`s with the plugin linking against the c++ library.

**Comment by drubin6** [comment]
I buy that but I don't quite see how to connect the Python callback to the `Messenger` implementation using that approach. Can you elaborate with some pseudo-code?

**Comment by YannickJadoul** [comment]
> In order for `Messenger::sendMessage()` to call the callback with `Acknowledgment`, it needs to also include `plugin.h`, so there is a circular reference.

Why exactly is that? If I understand well, `plugin.cpp` is only exposing the Python interface? So why can't you just pass the callback gotten through that interface as an `std::function` to the `Messenger` class?

**Comment by drubin6** [comment]
Maybe I'm mistaken, but it seems that the `PYBIND11_MODULE` binding has to be declared in the `plugin.h` header file, which other components include in order to see the definitions of the various `cast` operations. This would lead to an implementation like this (untested), which breaks the circular reference:

```C++
// messenger.h

    void sendMessage(const std::string& message,
                     const std::function<void(std::variant<std::string, Acknowledgment>)>& callback);
        // Send the specified 'message' and invoke the specified 'callback' with the response
        // where response can be a string or an 'Acknowledgment'.
```
and something like
```C++
    pybind11::class_<Messenger>(m2, "Messenger")
        .def(
            "send_message",
            [](Messenger&         messenger,
               const std::string& message,
               pybind11::object   callback) {
                auto cbwrapper =
                    [callback](
                        const std::variant<std::string, Acknowledgment>& arg) {
                        try {
                            callback(
                                pybind11::cast(std::get<Acknowledgment>(arg)));
                        }
                        catch (const std::bad_variant_access&) {
                            callback(std::get<std::string>(arg));
                        }
                    }

                    messenger.sendMessage(message, cbwrapper);
            });

```

**Comment by YannickJadoul** [comment]
No, I think you are mistaken there: `PYBIND11_MODULE` is just the entrance point when a module is imported in Python, creating new types and registering with them with pybind. But, as I said before, on the C++ level, this is just a function. There are no extra declarations you could include in other compilation units! So I once again think there is no need at all for `plugin.h`.

On another note: have you looked at all the functionality that is already present? As the documentation shows, there already is the built-in possibility of having a function that accepts `std::function`: http://pybind11.readthedocs.io/en/master/advanced/cast/functional.html. pybind11 is a quite versatile library, so I think spending half an hour or an hour on reading the basic documentation would help you quite a lot in understanding the possibilities and principles of pybind11.

**Comment by drubin6** [comment]
I will have to play around with the code a bit. I still don't understand how you can put the `PYBIND11_MODULE` definition in the .cpp file and still have everything work. If that were the case, my original code should work if I simply link against an object file with the `PYBIND11_MODULE` definition.

I did read the documentation and I appreciate the correspondence between Python functions and `std::function`. One sticking point I ran into is when a Python callback is bound to another thread. In this case, it is necessary to hold the GIL when destroying the callback object so that Python can correctly decrement the reference count. I found it necessary to store and manipulate `pybind11::object` to get the correct semantics. I don't think it is possible to get the correct semantics relative to the GIL if you allow the binding layer to translate the Python function to an `std::function`.

**Comment by YannickJadoul** [comment]
> If that were the case, my original code should work if I simply link against an object file with the PYBIND11_MODULE definition.

No, because the module initialization code (inside the `PYBIND11_MODULE` body) never gets executed. There's a difference between linking to an object file with a function and actually calling that function.

I can't really comment on the threading part since I haven't done anything with that functionality yet. But the main point is that you should be able to keep that conversion between python and c++ inside of `plugin.cpp`, no? (although maybe partly manually, because of the threading you mention)

**Comment by drubin6** [comment]
> No, because the module initialization code (inside the PYBIND11_MODULE body) never gets executed. 

I'm confused. How would the module initialization get executed in a C++ test driver? By calling `module::import()`?

**Comment by jagerman** [comment]
If embedding, there is a special macro that lets you provide a module inside a binary with a `main` that embeds the interpreter (see https://pybind11.readthedocs.io/en/stable/advanced/embedding.html#adding-embedded-modules)

**Comment by bstaletic** [comment]
This looks resolved.
