### ISSUE TITLE
docstring trimming and signature insertion

### ISSUE THREAD

**Issue by SylvainCorlay** [pybind/pybind11#112]
Just entering this for the record. I guess it is ok to close it if out of scope.

- docstring processing tools generally trim uniform amounts of indentation from the docstring, corresponding to the minimum indentation of all non-empty lines except the first one. See [PEP 257](https://www.python.org/dev/peps/pep-0257/#handling-docstring-indentation).
- C++11 supports multi-lines string literals with custom delimiters like
    ```
    R"mydelimiter(
        Cool Extension Module
        =====================
    )mydelimiter"
    ```
which are a really good fit for docstrings in pybind11.

- pybind11 inserts the signature at the first line of the docstring of functions and methods as it is customary for C extension modules, which cannot be inspected.

    `Signature : (x : array[float], y : array[float], z : array[float]) -> object`

Hence, if we don't indent the first line in the user provided docstrings, we end-up with a minimum common indentation of 0, which breaks the trimming.

Therefore, users willing to indent their C++ string litterals passed as docstrings should be careful to also indent the first line because of this insertion (and not do `R"(mydelimiter(Beginning of the docstring`).

*or*

pybind, which does *some* processing of the docstring (by inserting the signature) could trim it itself before inserting the signature.

**Comment by wjakob** [comment]
trimming the docstring in pybind11 seems quite reasonable to me!

**Comment by SylvainCorlay** [comment]
Thanks, I am not sure this does it. The example code from the PEP does:

```python
def trim(docstring):
    if not docstring:
        return ''
    # Convert tabs to spaces (following the normal Python rules)
    # and split into a list of lines:
    lines = docstring.expandtabs().splitlines()
    # Determine minimum indentation (first line doesn't count):
    indent = sys.maxint
    for line in lines[1:]:
        stripped = line.lstrip()
        if stripped:
            indent = min(indent, len(line) - len(stripped))
    # Remove indentation (first line is special):
    trimmed = [lines[0].strip()]
    if indent < sys.maxint:
        for line in lines[1:]:
            trimmed.append(line[indent:].rstrip())
    # Strip off trailing and leading blank lines:
    while trimmed and not trimmed[-1]:
        trimmed.pop()
    while trimmed and not trimmed[0]:
        trimmed.pop(0)
    # Return a single string:
    return '\n'.join(trimmed)
```

If I understand what you did correctly, you trim the entire docstring as a complete line.

**Comment by wjakob** [comment]
Aha, I see! That will be quite painful to do in C++ though :(

**Comment by SylvainCorlay** [comment]
I guess that it would be ok to revert that. It could probably land in the documentation though...

**Comment by SylvainCorlay** [comment]
cc @jmabille

**Comment by wjakob** [comment]
I'm not 100% sure what to add to the docs here -- do you have a suggestion? Or can this be closed?

**Comment by SylvainCorlay** [comment]
The crux of it is
- If you use C++11 string literals for your docstrings:
    - be careful to not indent your C++ code with actual tabulations because these will be part of the string and cause sphinx parsing to fail. Spaces are fine because sphinx trims the minimal indentation of the docstring.
   -  For normal Python docstrings, the first line is excluded from the minimal indentation computation so that you can write docstrings starting with `"""The beginning of the docstring`. In pybind11, since we also insert the signature, we must be careful to space-indent the one-line summary too.

**Comment by wjakob** [comment]
Ok, that makes sense. I assume that by tabulations, you mean the TAB character?

**Comment by SylvainCorlay** [comment]
That is right.

**Comment by SylvainCorlay** [comment]
An action point on pybind11 side would be to replace tabulations of the docstrings with 4 spaces...

**Comment by wjakob** [comment]
I would accept a PR for the TAB issue if it is simple and does not unduly increase the size of the resulting binary. Due to the nature of tab alignment, it is harder to do than just replacing all tabs by four spaces though.

**Comment by r-owen** [comment]
It might suffice to replace leading tabs with 4 spaces and ignore embedded tabs. That is simple.
