### ISSUE TITLE
Simple way to map C++ exceptions to existing Python exceptions

### ISSUE THREAD

**Issue by lahwaacz** [pybind/pybind11#1125]
The [documentation](http://pybind11.readthedocs.io/en/master/advanced/exceptions.html#registering-custom-translators) shows a simple way to map C++ exceptions to _new_ Python exceptions, however it does not show similar solution to map C++ exceptions to _existing_ Python exceptions. This should be simpler since it is not necessary to create the Python exception, but as far as I can tell the only solution to do this is to write custom exception translator. I'm interested mainly in the standard Python exceptions `AssertionError` and `NotImplementedError`.

**Comment by jagerman** [comment]
Take a look at the example in the documentation for `OtherException`; it shows what you want (if you drop the `MyCustomException` part of the code):

```C++
py::register_exception_translator([](std::exception_ptr p) {
    try {
        if (p) std::rethrow_exception(p);
    } catch (const OtherException &e) {
        PyErr_SetString(PyExc_RuntimeError, e.what());
    }
});
```
in your case, you'll want one catch for the C++ type that becomes `AssertionError` (using `PyExc_AssertionError`) and another to catch and set `PyExc_NotImplementedError`.  (The full list of built-in exceptions is at https://docs.python.org/3/c-api/exceptions.html#standard-exceptions).

**Comment by lahwaacz** [comment]
Thank you, I will do that. Would it be feasible to implement a function overload in pybind11 to allow writing just `py::register_exception<CppExp>(module, PyExc_AssertionError);`?

**Comment by jagerman** [comment]
Feel free to submit a PR.  It wouldn't need the `module` argument: it would be basically like the current `register_exception` but without the `scope` and `name` arguments, and using `PyErr_SetString` instead of the `ex(w.what())`.

It might also be useful to name it `translate_exception` or something along those lines.

**Comment by bstaletic** [comment]
One can write `py::register_exception<CppExp>(module, "Name", PyExc_AssertionError);` which creates a new exception called `Name` that inherits from `AssertionError`. I feel this is good enough.
