### ISSUE TITLE
Can't bind a pure virtual interface class

### ISSUE THREAD

**Issue by neutralid** [pybind/pybind11#1126]
I'm trying to convert some existing code to be python bound and running into problems with pure virtual "interface" classes used as bases.
Basically, I want to be able to construct my implementation of the Service interface class in Python (create a ServiceImpl instance) and pass the pointer to another python-bound method that takes a pointer to the interface class as an argument (void doSomethingWithService(Service*)).

Unfortunately, no matter what I've tried, compilation fails 
error: cannot declare field ‘pybind11::detail::instance<ServiceImpl,Service>::holder’ to be of abstract type ‘Service’
note:   because the following virtual functions are pure within ‘Service’:

I've read the documentation about virtual functions, but most of the work involving trampoline classes seem to be just for extending classes in Python, which is not a use case here (and to be blunt, that looks like a lot of effort just to allow a derived class to be python bound -- I will have to add the solution to many, many files). I'm hoping there is a much simpler way that I'm missing. The base class doesn't need to be constructable or anything, I really just need python to be able to do the type conversions since all of our other functions expect "interface" pointers (at least, the docs led me to believe Python could automatically upcast if relationships were specified correctly)

Finally, I apologize since this isn't exactly a bug, and possibly could be solved through the chat, but unfortunately company firewalls bla bla bla. Thanks in advance for any help!

`class Service {
Service() {}
virtual void DoSomething() = 0;
}

class ServiceImpl : public Service {
ServiceImpl() {}
void DoSomething() { printf("something!"); }
}

PYBIND11_PLUGIN(test) {
  py::module m("test");
//  py::class_<Service>(m, "Service")
  py::class_<ServiceImpl, Service>(m, "ServiceImpl")
    .def(py::init<>());
  return m.ptr();
}`

**Comment by jagerman** [comment]
> `py::class_<ServiceImpl, Service>(m, "ServiceImpl")`

The first template argument always has to be the C++ class (`Service`); the alias/trampoline class (which is where you provide a class implementing all the virtual functions with `PYBIND11_OVERLOAD_...` macros to bounce the calls to Python) has to come afterwards, i.e.:

`py::class_<Service, ServiceImpl>(m, "Service")`

**Comment by jagerman** [comment]
To elaborate a little, you always have to have a concrete (non-abstract) C++ type to be able to create an object on the C++ side.  The trampoline class, `ServiceImpl`, is just such a class: it's the "glue" needed to be able to instantiate a C++ instance; such an instance can then be passed to something expecting a `Service *` (this is just a casting to a base class).

**Comment by neutralid** [comment]
It turns out the latest version of pybind11 worked fine with the code as it was. We were able to push for the upgrade from 1.xx and everything now seems fine. Closing issue.
