### ISSUE TITLE
PyPy 5.9.0 segfault under multiple inheritance

### ISSUE THREAD

**Issue by jagerman** [pybind/pybind11#1130]
The test suite segfaults under PyPy 5.9.0, in particular when using multiple inheritance of both a Python and C++ class with the Python class first.  It seems in such a case our custom `tp_new` (in `pybind11_object`) doesn't get called, so the instance doesn't get allocated or initialized.

I'm creating this issue to document/track it; more details are at the upstream bug report: https://bitbucket.org/pypy/pypy/issues/2674/cpyext-tp_new-not-called-in-some-multiple

**Comment by bstaletic** [comment]
We've dropped support for PyPy 5.9.0 and we now have CI for PyPy.
