### ISSUE TITLE
Crashes when Numpy isn't installed

### ISSUE THREAD

**Issue by Speierers** [pybind/pybind11#1137]
## Issue description

Python is crashing when trying to import a python library made with Pybind11 because the C++ code was setting some Numpy flags and Numpy was actually not installed on my machine: 

```
py::module m_parent = py::module::import("my_framework");
m.attr("float_dtype") = py::dtype("f");
```

I guess Pybind11 should throw an exception rather than segfaulting in this case.

## Reproducible example code

Run the code above on a machine where Numpy isn't installed.

**Comment by dcnieho** [comment]
I have what may be a related issue. When running a pyd that exports a py::array_t, python will crash randomly during script execution when the python script does not import numpy. and with randomly, i mean really at any random point of execution of the C++. Symptoms are like a buffer overwrite.
This is on Windows 10 with pybind 2.3.4, up to date MSVC (16.4.1), and Python 3.6.6. Occurs only for x64 release builds, not for x86 release build, or debug builds for both platforms...
Random as it is, the issue never occurs when adding `import numpy` to my python script, and almost every run when i don't import that

**Comment by bstaletic** [comment]
Without a reproducible example, there's not much to be done here. As far as I can tell, pybind correctly throws `ModuleNotFoundError`.
