### ISSUE TITLE
Python report wrong type for class from hierarchy when most derived classes is not bound

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#1140]
Dear Pybind11 developers, i noticed that in situation when hierarchy of classes if partially bound (case when most derived classes is not bound) types reported in Python seems wrong. 

For example when dealing with derived classes the base class type of hierarchy will be reported while the most derived type seems like a better (most useful) answer. Could this fixed?

Use case for this will be situation when Python bindings provided for some base library levels while objects created come from extra library level when new, derived classes is created for already bound classes.

Thanks,

```C++
#include <pybind11/pybind11.h>

struct A
{
	virtual ~A() {}

	virtual void foo() {}
};

struct B : public A
{
	void foo() override {}

	virtual void bar() {}
};


struct C : public B
{
	void foo() override {}

	void bar() override {}
};


A * get() { return new C(); }

namespace py = pybind11;

PYBIND11_MODULE(example, m)
{
	py::class_<A> (m, "A")
        .def(py::init<>())
		.def("foo", &A::foo)
		;

	py::class_<B, A> (m, "B")
        .def(py::init<>())
		.def("foo", &B::foo)
		.def("bar", &B::bar)
		;

	m.def("get", &get);
}
```

Python code, notice that `b` is reported as an instance of `A` instead of `B` and therefore `bar` member function is not there.
```Python
> from example import *; b = get(); type(b), dir(b)
(example.A,
 ['__class__',
  '__delattr__',
  '__doc__',
  '__format__',
  '__getattribute__',
  '__hash__',
  '__init__',
  '__module__',
  '__new__',
  '__reduce__',
  '__reduce_ex__',
  '__repr__',
  '__setattr__',
  '__sizeof__',
  '__str__',
  '__subclasshook__',
  'foo'])
```

**Comment by wjakob** [comment]
Hi Sergey,

this is a know limitation of pybind11. The trouble is that ``typeid(*ptr)`` (which pybind11 uses internally to determine the type of the return value) returns the typeid of ``C``, which is not known to pybind11. The fact that ``B`` is a parent of ``C`` is also not known at runtime because there is no way of traversing ``typeid`` hierarchies. So it's basically a limitation of C++ itself that manifests itself in pybind11.

Best,
WEnzel

**Comment by lyskov** [comment]
Ah, I see. - thank you for explaining this Wenzel!

**Comment by lyskov** [comment]
Out of curiosity: so how Pybind11 fallback to determent that type of return object is `A`? Or does do this simply by using function return type?

**Comment by wjakob** [comment]
The function return type :)
