### ISSUE TITLE
Using python C API with pybind11

### ISSUE THREAD

**Issue by neutralid** [pybind/pybind11#1141]
We have some old code that worked directly with Python.h and the python C API. Lots of methods pass around PyObjects, which are probably pretty close to py::object in terms of implementation. If I attempt to bind a function which returns a PyObject, I get type errors since it doesn't know what PyObject is.
I can create a dummy class binding to stop these errors, but then python just treats the returned value as a generic object.

<example.PyObject object at 0x7f92b4157fb8>

It appears that py::object makes some use of PyObject under the hood, but it's unclear if there's an easy way to cast/convert to the former. Can anyone provide guidance?

**Comment by neutralid** [comment]
I apparently was on the verge of a breakthrough just needed to keep chugging along. For future people like me, py::object does indeed wrap a PyObject*, so all we had to do in our bindings was define a lambda to properly get a pointer/convert a PyObject to a py::object.

.def("setValue", [](myClass& c, py::object o){ c.setValue(o.ptr()); })
.def("getValue", [](const myClass& c){ return py::reinterpret_steal<py::object>(c.getValue());

**Comment by jagerman** [comment]
Just a note on this to elaborate a bit:

One of the big deficiencies in the Python C API is that you can't tell whether a returned `PyObject *` is a borrowed or stolen reference (except by reading the documentation).  Pybind tries to correct this by having `py::object`, which manages an `inc_ref()` on creation and a `dec_ref()` on destruction.

When you need to work with borrowed or stolen references you can use `auto o = py::reinterpret_steal<py::object>(pyobject_ptr);` or `auto o = py::reinterpret_borrow<py::object>(pyobject_ptr);` to steal or borrow a reference, respectively.  Borrowing is often the right thing, but some C API functions (particularly ones that create new objects) return new references that need to be stolen to get the reference counts right.

**Comment by artiit** [comment]
Hi, @jagerman , My code is something like bellow:
```
PyObject* GetRet(Ret* ret) {
  npy_intp shape[1];
  shape[0] = 1024;
  PyArray_Descr* descr = PyArray_DescrFromType(NPY_OBJECT);
  PyObject* obj = PyArray_Empty(1, shape, descr, 0);
  PyArrayObject* np_array = reinterpret_cast<PyArrayObject*>(obj);
  PyObject** out = reinterpret_cast<PyObject**>(PyArray_DATA(np_array));
  for (int i = 0; i < ret->size(); ++i) {
      out[i] = PyBytes_FromStringAndSize(ret[i]->data(), ret[i]->size());
    }
  return obj;
}
```
In this case, should I use steal instead of borrow and what return policy should I take?
I found that the return::policy does not matter cause both reference and take_ownership just worked well. But, it seems that different strategies(steal or borrow) have an impact on the time of function execution, steal is shorter than borrow by a few ms. I think this is related to reference count.

Any suggestions will be appreciate.

Thanks.
