### ISSUE TITLE
Compilation failure when binding type const char*

### ISSUE THREAD

**Issue by trelau** [pybind/pybind11#1143]
## Issue description

Compilation failure when trying to compile the sample below (MSVC 2015 Windows 10 64-bit). This is a small replication of a C++ library that I am trying to wrap but cannot modify.

## Reproducible example code

```c++
#include <pybind11\pybind11.h>
#include <pybind11\iostream.h>

namespace py = pybind11;

typedef const char* TheString;

void TheMethod(TheString& theString) {
	std::cout << theString;
};



PYBIND11_MODULE(pymod2, mod) {

	mod.def("TheMethod", (void (*) (TheString&)) &TheMethod);
	
}
```
Results in:

`C2664	'void (TheString &)': cannot convert argument 1 from 'char *' to 'TheString &'`

Possibly related to https://github.com/pybind/pybind11/issues/1116

**Comment by bstaletic** [comment]
`TheString&` is a non-const l-value reference and a type that gets passed to `TheMethod()` is an r-value. That is not how C++ works. Instead use `const TheString&` and it will compile fine.
