### ISSUE TITLE
Visual Studio 2015 can't catch breakpoint.

### ISSUE THREAD

**Issue by ghost** [pybind/pybind11#1147]
I built a python module using pybind11 v2.2.1 and Visual Studio 2015, targeting python 2.7. The module runs correctly inside python command line. Now I want to debug it. I have built the module under Debug mode in Visual Studio 2015 and make sure it is the debugged version that is loaded. In VS, I attached python process and set the breakpoint properly, but the breakpoint cannot be caught after I executed the function to be debugged in python CLI. It is expected that the breakpoint can be caught but the code just run as if there is no debugger. The debugging feature of Visual Studio 2015 works when I am debugging regular C++ application. I did not change any config in Debug mode (actually I don't know how to change at all). The remote debugger worked once when I tested pybind11 using a very small test code. But now I am developing a large project so it is impossible to provide the code. So, how can I troubleshoot the problem or, if you have related experience, how can I find the problem and fix it? Thank you.

Environment:
Visual Studio 2015 Update 3
Windows 7
Python 2.7.13
All 64-bit for the above
pybind11 v2.2.1

**Comment by YannickJadoul** [comment]
I don't think we can help a lot here. We don't have any frequent Windows-using maintainers, and in +2.5 years, no one else came with an answer, either.
This is not pybind11-specific, but is related to debugging any Python C extension with Visual Studio. So I suggest Googling a bit for it. E.g.: https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2019

For more questions like this, do please pass by [Gitter](https://gitter.im/pybind/Lobby), and there might be more people to help you out step by step.
