### ISSUE TITLE
overload_cast<> failure using G++/Intel C++

### ISSUE THREAD

**Issue by f-koehler** [pybind/pybind11#1149]
## Issue description
I have some problems using the `overload_cast<>` function where code compiles fine using Clang but fails for Gcc/Intel. In this scenario the overload of a template class member function is based on constness.
Even after consulting the documentation, especially [this section](http://pybind11.readthedocs.io/en/stable/classes.html#overloaded-methods), I still don't see what the problem might be.

## Minimal Failing Example
The following code compiles using `Clang 6.0.0` but fails for `gcc 5.4.1` and `icpc 17.0.4`. I made sure that the `-std=c++14` is set and also tried to enforce the C++14 features of pybind11 using `PYBIND11_CPP_STANDARD`.
```C++
#include <pybind11/pybind11.h>
namespace py = pybind11;

template <typename T>
class TemplateClass {
private:
    T t;

public:
    TemplateClass() : t(1.) {}

    auto&       foo() { return t; }
    const auto& foo() const { return t; }
    auto&       bar(T& a) { return a; }
    const auto& bar(T& a) const { return a; }
};


PYBIND11_MODULE(SomeModule, m) {
    py::class_<TemplateClass<double>>(m, "TemplateClass")
        .def("bar", py::overload_cast<double&>(&TemplateClass<double>::bar))
        .def("foo", py::overload_cast<>(&TemplateClass<double>::foo));
}
```
With `g++` I get the following error:
```
error: no match for call to ‘(const pybind11::detail::overload_cast_impl<double&>) (<unresolved overloaded function type>)’
         .def("bar", py::overload_cast<double&>(&TemplateClass<double>::bar))
```
The `unresolved overloaded function type` portion indicates that the compile does not know which overloaded function to use and indeed the compiler error vanishes when removing one of the overloads for each function. How do I indicate which overload the compiler should use?
Compilation also fails if I try to export the const versions using `py::const_`.

What am I missing here?

**Comment by f-koehler** [comment]
Very strange, if I do not use `auto` for the return types but write `T` explicitly it compiles fine. But why is Clang able to deduce the types correctly? I tested also the latest Gcc 7 which also fails.

**Comment by jagerman** [comment]
This feels like a gcc bug related to `auto` return types to me.  It doesn't appear to be specific to `py::overload_cast`: gcc won't even accept a regular member function cast there:

```C++
template <typename T>
class C {
    T x;
public:
    auto &f() { return x; }
    const auto &f() const { return x; }
};

int main() {
    (void) (double & (C<double>::*)()) &C<double>::f;
}
```
fails to compile under g++, works under clang.

I've no idea of how one could work around the issue.

**Comment by f-koehler** [comment]
I can verify the failure of raw casts. I did not write about this, because I assumed I messed them up. Currently I am working around by not using `auto`. If I find the time I will try to report this to the GCC devs.

I will close my issue as it is not related to pybind11.

**Comment by adriendelsalle** [comment]
It looks like it's still the case today with `gcc version 10.3.0`, any news about this @f-koehler ?

**Comment by adriendelsalle** [comment]
I found [this pointer](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96647), looks like it's in the pipeline
