### ISSUE TITLE
pip 10 will break pybind11

### ISSUE THREAD

**Issue by phdowling** [pybind/pybind11#1174]
See: https://github.com/pypa/pip/issues/3696#issuecomment-342701372

It seems that the usage `pip.locations.distutils_scheme('pybind11')['headers']` will no longer be supported in the upcoming pip upgrade (and in fact, is discouraged even in the current version of pip).

**Comment by wjakob** [comment]
That's quite concerning -- thank you for letting us know. A proposed fix is in #1190.
