### ISSUE TITLE
Default arguments for a function

### ISSUE THREAD

**Issue by chinmoykulkarni** [pybind/pybind11#1175]
How to pass a default argument
I have a class Foo. I want to pass its object to a function bar

     void bar(string abc, Foo foo = {})

I want to call bar with both parameters if defined or else just abc. I have written functionality to handle {} in my definition. How do you wrap this in pybind11
This is what I currently have (Obviously does not work)

     v.def("bar",&bar,py::arg("foo") = {})

**Comment by wjakob** [comment]
```
 v.def("bar",&bar,py::arg("foo") = Foo{})
```

``Foo`` must be registered before that binding declaration so that pybind11 knows how to convert it.

**Comment by chinmoykulkarni** [comment]
I have the Class foo declared as follows
py::class_<Foo>(v,'Foo');

After I implemented your method I am facing the following and a few more errors
 error: static assertion failed: The number of named arguments does not match the function signature
         static_assert(detail::expected_num_args<Extra...>(sizeof...(Args)),

**Comment by wjakob** [comment]
It's all in the error message: If you add one ``py::arg`` declaration, you have to provide `them for all arguments (not necessarily with default values).

**Comment by chinmoykulkarni** [comment]
Got it. Thanks!

**Comment by chinmoykulkarni** [comment]
Hi,
I have to pass in static variable to my default argument
in CPP

    void bar(string abc, Foo foo = Baz::var1)

Where, Class Baz has static const variable "var1" of type Foo.

I currently have tried these

    .def("bar",&bar,py::arg("abc"),py::arg("foo") = Foo Baz.var1)
    .def("bar",&bar,py::arg("abc"),py::arg("foo") = Foo Baz::var1)
