### ISSUE TITLE
PYBIND11_TYPE_CASTER() behaviour changes between C++11 and C++14/17

### ISSUE THREAD

**Issue by bluescarni** [pybind/pybind11#1180]
The following code works as expected when pybind11 is being compile with C++11:

```c++
template <int N>
struct test {};

namespace pybind11
{
namespace detail
{
template <int N>
struct type_caster<test<N>> {
public:
    PYBIND11_TYPE_CASTER(test<N>, _(("test[" + std::to_string(N) + "]").c_str()));
    // etc. etc.
};
}}
```

However, this same code compiled with C++14 and later breaks because, with C++14 and later, only compile-time string operations are allowed inside the body of the ``_()`` call (or at least that's my understanding while skimming the code).

Would it be possible to have runtime string manipulation capabilities in C++14/17 as well?

**Comment by aldanor** [comment]
In your case, `N` is compile-time, so you can do

```cpp
_("test[") + _<N>() + _("]")
```

at compile-time.

**Comment by bluescarni** [comment]
Thanks, didn't know that! Is this going to work in C++11 as well? I'll try it later tonight.

**Comment by jagerman** [comment]
> going to work in C++11 as well?

Yup.

You can also get a ternary (if-else) on a compile-time condition with: `_<CONDITION>("if true", "if false")`.  For example: `_<std::is_integral<T>::value>("int", "float"))` is used by the numeric value caster.

**Comment by bluescarni** [comment]
Awesome, it's working as intended. I am closing the report.

Thanks a lot for the help!
