### ISSUE TITLE
Using find_package does not work

### ISSUE THREAD

**Issue by Baljak** [pybind/pybind11#1185]
In our CMake based project, using either 2.2.1 or the last master doesn't work with find_package (on Windows). On the other way, add_subdirectory works properly, but we don't include external libraries in our projects so we are bound to use find_package. The following error is raised:

```
CMake Error at PyTest/CMakeLists.txt:5 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
```

I tried to set pybind11_DIR to my local pybind11 repository or to the tools subdirectory but neither works. The only way I found to get it to work properly was to cmake pybind11 separately, build its INSTALL project to get an "installed" version of pybind11 directory and set pybind11_DIR to point to its share\cmake\pybind11 subdirectory. Is this the only way?

**Comment by Baljak** [comment]
Nevermind, I will use add_subdirectory instead.

**Comment by harryhan618** [comment]
> Nevermind, I will use add_subdirectory instead.

But you can't put the `pybind11` directory as a subdirectory for every cpp extension for python. 
There must be a way to use `find_package`. Do you know how to make it work other than `set(pybind11_DIR "/path/to/pybind11")`?
