### ISSUE TITLE
Indicating that a function takes keyword-only arguments

### ISSUE THREAD

**Issue by anntzer** [pybind/pybind11#1194]
## Issue description

I was told on gitter that pybind11 currently does not support creating functions that takes keyword-only arguments.  It would be appreciated if it did.

As far as I can tell, support for keyword-only arguments is directly implemented in PyArg_ParseTupleAndKeywords by the "$" specifier (https://docs.python.org/3/c-api/arg.html#other-objects) (which requires keyword-only arguments to have a default; I guess it's fine to have whatever limitations the Python C-API currently has).

On pybind11's side, I guess this can be provided as something like `py::kwonly("foo")` / `"foo"_kwo` where one would have expected `py::arg("foo")` / `"foo"_a`; or with some marker object separating kwonly arguments from non-kwonly ones, similar to `*` on Py3.

## Reproducible example code

N/A

**Comment by jagerman** [comment]
Give #1196 a try.  I went with the second suggestion (using a marker object) as it seemed a bit nicer as an interface (and neatly avoids the issue of what happens when you specify a `py::kwonly` before a `py::arg`).

**Comment by anntzer** [comment]
Thank you for the quick reply!
#1196 appears to work based on some very simple testing; also supports compulsory keyword-only arguments (so matching Python's behavior, which is good).
It would also be nice if the reported signatures (either in the docstring, or in the TypeError when non matching arguments are passed) included the `*` (as Python would display the signature).  Otherwise, I can get error messages like
```
File "<string>", line 1, in <module>
TypeError: f(): incompatible function arguments. The following argument types are supported:
    1. (x: int, y: int=1) -> int

Invoked with: 1, 2
```
(where f actually had signature `(x: int, *, y: int = 1)`) which can be a bit confusing.

**Comment by anntzer** [comment]
Actually, another Py3 behavior that may be nice to have is keyword-only arguments after `*args` (i.e., `def f(*args, kwo=42):`); as a side note, https://www.python.org/dev/peps/pep-3102/ suggests that this is actually where the `, *,` syntax came from.

Right now this doesn't work with pybind11 (`py::args` must come at the end of the argument list (possibly before py::kwargs)), but in general it may be worth trying to come up with a syntax that consistently handles both `def f(pos_or_kw, *, kwo)` and `def f(pos_or_kw, *args, kwo):` (for example, but not necessarily, by making removing the constraint that py::args must come last, and making py::args_kw_only optionally match a py::args if one is present).
