### ISSUE TITLE
Documentation contains nothing about downloading and installation

### ISSUE THREAD

**Issue by defjaf** [pybind/pybind11#1203]
The [current documentation](http://pybind11.readthedocs.io/en/latest/) contains absolutely nothing about where to download and how to install the software. It's not that hard to trace things back here to GitHub, but a more explicit pointer would be a good idea! (For those of us on  macOS a comment that [it's available](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pybind11.rb) via [homebrew](https://brew.sh) might also be appropriate.

**Comment by liwt31** [comment]
Agreed. It surprised me that the "First steps" in the documentation is not about downloading and installation...

**Comment by bstaletic** [comment]
If you click the "Read the Docs" bar in the lower left corner there will be an "on GitHub" section with a link to the repo.
