### ISSUE TITLE
Documentation outdated for numpy example

### ISSUE THREAD

**Issue by chhenning** [pybind/pybind11#1205]
On the [page](http://pybind11.readthedocs.io/en/master/advanced/pycpp/numpy.html) I believe the example for initializing a Matrix with a numpy array is using the outdated "__init__" notation. Look for the "/* Bind MatrixXd (or some other Eigen type) to Python */" comment to find the code.

When I run the code I'm greeted with the following warning:

    FutureWarning: pybind11-bound class 'chh.Matrix' is using an old-style placement-new '__init__' which has been deprecated. See the upgrade guide in pybind11's docs. This message is only visible when compiled in debug mode.

**Comment by YannickJadoul** [comment]
Thanks for reporting, @chhenning!
