### ISSUE TITLE
Using pybind with existing CMake structure

### ISSUE THREAD

**Issue by JohnV7** [pybind/pybind11#1217]
## Issue description

I'm trying to use pybind with an existinc cmake structure. I modified the existing CMakeLists.txt file adding 
`add_subdirectory(src/pybind11)`
`pybind11_add_module(mycode src/mycode.cpp)`
`target_link_libraries(mycode  PRIVATE ${MYCODE_LIBRARIES})`

This compiles succesfully and generates mycode.so, but when trying to import it via python I get following error:
`import mycode`
> ImportError: ./mycode.so: undefined symbol: PyInstanceMethod_Type

Any ideas what the problem may be?

**Comment by Xfel** [comment]
This might come from a python version mismatch between the version used to compile and the version used to run.

**Comment by henryiii** [comment]
Should be fixed by #2370 and related changes.

**Comment by me21** [comment]
I have this issue with my setup.
I crosscompile on Windows for Beaglebone Black Linux ARM machine and I get this error when I try to import the .so file on the target.
