### ISSUE TITLE
Python callable returning a bool will be always ``true`` in C++

### ISSUE THREAD

**Issue by elemakil** [pybind/pybind11#122]
A callable defined in python that returns a `bool` and that is passed into the `C++` code will return always true. Minimal example:

```c++
#include <pybind11/pybind11.h>
#include <pybind11/functional.h>

namespace py = pybind11;

#include <iostream>
#include <functional>

void forward(std::function<bool(int)> fn){
    std::cout << "21 -> " << fn(21) << std::endl;
    std::cout << "42 -> " << fn(42) << std::endl;
    std::cout << "84 -> " << fn(84) << std::endl;
}

PYBIND11_PLUGIN(bindings) {
    py::module m("bindings", "My C++ bindings.");
    m.def("forward", forward);
    return m.ptr();
}
```

Python session

```python
>>> import bindings
>>> def foo(n):
...     return n>= 42
... 
>>> bindings.forward(foo)
21 -> 1
42 -> 1
84 -> 1
```

**Comment by bennybp** [comment]
Your example is working as expected for me with Intel and two different version of GCC. Which compiler/python version are you using?

**Comment by wjakob** [comment]
I think this is an old bug -- are you sure you're using the latest version of pybind11?

**Comment by elemakil** [comment]
Hah, sorry completely forgot to add that information.

I'm on MacOS ```10.11.3```:

```
─[~]$ which clang++
/usr/bin/clang++
─[~]$ clang++ --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```
Using the (most recent) pybind11 tag ```v1.2```.

**Comment by wjakob** [comment]
The most recent one is in 'master' -- can you try that?

**Comment by elemakil** [comment]
Yep, this does work. I'm closing the issue, sorry for the noise. 

Is ```master``` expected be be stable? Meaning, should I just follow ```master``` instead of going with the tags?

**Comment by wjakob** [comment]
Master is the development branch. So far my approach was to sync up 'stable' whenever there is a new release, which is perhaps a bit too infrequent. The last release still has this bug.
