### ISSUE TITLE
Missing file pybind11Targets.cmake?

### ISSUE THREAD

**Issue by joakim-hove** [pybind/pybind11#1221]
## Issue description

I am trying compile a small example using cmake and `find_package( )`, but the cmake module `pybind11Config.cmake` seems to refer to a non existing file `pybind11Targets.cmake`. My `CMakeLists.txt` looks like:

```cmake
project( sunbeam )
find_package(pybind11 REQUIRED)
message(STATUS "Found pybind11 v${pybind11_VERSION}: ${pybind11_INCLUDE_DIR}")
```

And the output I get is:

```txt
[joaho@lt-lx899886 build]$ cmake3 ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Failed
-- Performing Test HAS_CPP11_FLAG
-- Performing Test HAS_CPP11_FLAG - Success
CMake Error at /usr/local/share/cmake/pybind11/pybind11Config.cmake:108 (include):
  include could not find load file:

    /usr/local/share/cmake/pybind11/pybind11Targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


CMake Error at /usr/local/share/cmake/pybind11/pybind11Config.cmake:111 (set_property):
  set_property could not find TARGET pybind11::pybind11.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


CMake Error at /usr/local/share/cmake/pybind11/pybind11Config.cmake:112 (set_property):
  set_property could not find TARGET pybind11::embed.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


CMake Error at /usr/local/share/cmake/pybind11/pybind11Config.cmake:117 (set_property):
  set_property could not find TARGET pybind11::pybind11.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


CMake Error at /usr/local/share/cmake/pybind11/pybind11Config.cmake:119 (get_property):
  get_property could not find TARGET pybind11::pybind11.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


CMake Error at /usr/local/share/cmake/pybind11/pybind11Config.cmake:120 (get_property):
  get_property could not find TARGET pybind11::module.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


-- Found pybind11 v2.3.dev0: /usr/local/include

```

I have previously installed the master version of `pybind11` in `/usr/local` using the following command sequence:
```bash
git clone git@github.com:pybind/pybind11
mkdir pybind11/build ; cd pybind11/build
cmake .. 
make install
```
I am using cmake version 3.6.3 on Redhat Linux.

**Comment by joakim-hove** [comment]
Ping - would be very grateful if someone could take a brief look at this. If it is indeed a bug I am happy to (try) make a fix.

**Comment by jagerman** [comment]
Try rebuilding/installing with `cmake .. -DPYBIND11_INSTALL=1`.  (Off the top of my head, I don't remember why we need that flag—perhaps we should at least try to make `make install` fail, or else stop requiring the option).

**Comment by joakim-hove** [comment]
> Try rebuilding/installing with cmake .. -DPYBIND11_INSTALL=1.

Thank you for responding.

I am slightly embarrassed to say that why I removed my hacks/workarounds from December and tried again everything just worked - with a plain `make install`; so my problems must have been some other cmake related problem. Sorry about the noise.

**Comment by jagerman** [comment]
No problem, happy to hear you got it working.

**Comment by Akshay-9416** [comment]
Hi I am facing the same issue and make install hasn't solved it for me. below is the link to the issue i have posted in stackoverflow 
can someone please look at the issue and please let me know how to solve it.
https://stackoverflow.com/questions/64680891/set-property-could-not-find-target-pybind11pybind11-perhaps-it-has-not-yet-be

**Comment by YannickJadoul** [comment]
@Akshay-9416 

First of all, this is a 3 year old issue, so it's probably better to pass by Gitter (or open a new issue) and just refer to this.
Second of all, you are doing a lot of weird, manual things in your CMake and `src/pybind11_catkin/scripts/find_pybind11`, so it's no wonder things will go wrong if you then manually include random parts of pybind11's CMake framework (i.e., `tools/pybind11Tools.cmake`). Please refer to the docs (https://pybind11.readthedocs.io/en/stable/compiling.html#building-with-cmake) where @henryiii has done a great effort to nicely describe how to correctly use pybind11 in a CMake build system in your project (through a local cloned directory with `add_subdirectory` or through an installed version with `find_package`). Please follow this guide before blaming pybind11.

**Comment by henryiii** [comment]
I believe the issue is here: #2642

**Comment by henryiii** [comment]
Also, please use git instead of Google Drive for programming! Learning git is totally worth it!

**Comment by YannickJadoul** [comment]
> I believe the issue is here: #2642

Well, even better. Then #2642 should have just referred to this issue.
