### ISSUE TITLE
numpy arrays scalar

### ISSUE THREAD

**Issue by fbriol** [pybind/pybind11#1224]
Hello I need different functions taking as arguments a value of « numpy arrays scalar » type.

It is possible to write prototypes like this:

    PYBIND11_MODULE(np_scalar, m) {
        m.def("overloaded", [](py::array_t<double>) {
            return "double";
        });
        m.def("overloaded", [](py::array_t<std::int8_t>) {
            return "int8";
        });
        m.def("overloaded", [](py::array_t<std::int16_t>) {
            return "int16";
        });
    }

However, this method does not allow to intercept scalars, for example:

    >>> import np_scalar
    >>> np_scalar.overloaded(numpy.array([1], dtype='int8'))
    'int8'
    >>> np_scalar.overloaded(numpy.int8(1))
    'double'

How do we intercept numpy arrays scalar?

Thank you very much for your help.

**Comment by chhenning** [comment]
I'm not an expert but can you do:
```
m.def("overloaded", [](py::array a)
{
    auto buf = a.request();
    auto fmt = buf.format;

    if (fmt == "int32")
    {
        return "int32";
    }
    else if (fmt == "float64")
    {
        return "float64";
    }
    else
    {
        return "unknown";
    }
});
```

**Comment by fbriol** [comment]
This doesn't work because this prototype only accepts array, not scalar.

    m.def("overloaded", [](py::array a)
    {
        auto buf = a.request();
        auto fmt = buf.format;

        if (fmt == "i")
        {
            return "int32";
        }
        else if (fmt == "h")
        {
            return "int16";
        }
        else
        {
            return "unknown";
        }
    });

    >>> import np_scalar
    >>> np_scalar.overloaded(numpy.array([1], dtype="int32"))
    'int32'
    >>> np_scalar.overloaded(numpy.int32(1))
    .../...
    TypeError: overloaded(): incompatible function arguments. The following argument types are 
    supported:
        1. (arg0: array) -> str

**Comment by vanossj** [comment]
I was just doing a similar thing. It *should* work with `py::buffer` instead of `py::array`
However numpy doesn't expose the buffer info of scalers correctly, numpy/numpy#10265, it always reports them as byte arrays.

```c++
m.def("overloaded", [](py::buffer a)
{
    auto buf = a.request();
    if (buf.ndim == 0)
    {
        return "scaler of type " + buf.format;
    }
    else
    {
        return "ndarray of type " + buf.format;
    }
});
```

```python
>>> import np_scalar
>>> np_scalar.overloaded(numpy.array([1], dtype="int32"))
'ndarray of type i'
>>> np_scalar.overloaded(numpy.int32(1))
'ndarray of type B'
```

**Comment by eacousineau** [comment]
@fbriol If you're still monitoring this issue, can you take a gander at the solutions (/ workarounds) in these two issues?

https://github.com/pybind/pybind11/issues/1776
https://github.com/pybind/pybind11/issues/1785

Both were for leveraging NumPy to gain access to "off the beaten path" floats, like `float128` and `float16`. One of the workarounds I posted was making a `npy_scalar_caster` - however, that's only useful if you want to capture a specific type, and it *could* shadow (or error out) if you try and use it with already supported types like `float` or `double`:
https://github.com/eacousineau/repro/blob/5e6acf6/python/pybind11/custom_tests/test_numpy_issue1785.cc#L21-L47
