### ISSUE TITLE
why pybind11 is slower than cython

### ISSUE THREAD

**Issue by zhuoqiang** [pybind/pybind11#1227]
simple benchmark for the example `add()` function

```py
In [1]: import example
In [2]: %timeit example.add(1000, 2000)
606 ns ± 33.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

release buidl (using `cmake -DCMAKE_BUILD_TYPE=Release ..` ) improves the speed:

```py
In [1]: import example
In [2]: %timeit example.add(1000, 2000)
469 ns ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

however, comparing with cython it still not fast enough:

```py
In [10]: %reload_ext cython
In [11]:
    ...: %%cython
    ...: cpdef int cython_add(int a, int b):
    ...:     return a + b
    ...:
In [12]: %timeit cython_add(1000, 2000)
114 ns ± 5.48 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

pybind11 is 4X times slower than cython.

Why that happened? Is there anything to do to improve the performance here?

**Comment by aldanor** [comment]
IIRC, due to all the argument conversion and casting logic in pybind11, Cython will normally be somewhat faster on microbenchmarks which is to be expected.

// Make sure you compile both with the same compiler flags though for the results to be any meaningful.

**Comment by daly88** [comment]
it allocate a std::vector.reserve to store the function argument for each call, which will do malloc/new memory allocation, but it's meaningless
