### ISSUE TITLE
C++ exceptions not converted to Python exceptions when extension built with setuptools

### ISSUE THREAD

**Issue by xoltar** [pybind/pybind11#123]
Hi Folks,

Not sure if this is a pybind11 bug, maybe it's a distutils bug, or just something I'm doing wrong.

I'm on mac os x, El Capitan. I have an extension built with pybind11 (pybind11 is really nice, by the way). When I use a cmake-based build based on the sample in the pybind11 docs, the extension works fine.

However, I want to package the extension for use with pip, so I need setup.py to work (right?). When I use setup.py to build, it compiles and even runs, but whenever an exception is thrown (like index error, or stop iteration), the process terminates after catching it.

I have no idea what would make this happen, do you?

At the moment I'm stuck with telling people to download and build from source, rather than using pip install, which is a shame. 

Any ideas?

Thanks,
Bryn

**Comment by wjakob** [comment]
Note that installing pybind11 via pip just installs the header files, so I suppose some of the compilations options invoked by ``setup.py`` must be different.

There is an official recipe for making packages: https://github.com/pybind/pbtest -- does it work with that?

**Comment by xoltar** [comment]
That definitely helps, I must have missed that in the docs.

However, even though it has pybind11 as a dependency, it doesn't seem to automatically locate the pybind11 header files. What's the canonical way to find them, so I can add them to the include_dirs member of the Extension?

Thanks for your help!

**Comment by wjakob** [comment]
That sounds strange to me, I think it should.

CC @SylvainCorlay @jmabille

**Comment by xoltar** [comment]
I uninstalled pybind11-1.3 (which I think I installed from source according to the readme when I was just getting this started) and pip installed, which gave me 1.2, but there was an error message in the install about not being able to find a file it expected. So pip uninstall pybind11 and pip install pybind11 again seems to have gotten me a clean installation, and now, indeed, the setup.py from pbtest does find the headers, does build, and does give me the right behavior with exceptions. Thanks so much for your assistance!

**Comment by SylvainCorlay** [comment]
> However, even though it has pybind11 as a dependency, it doesn't seem to automatically locate the pybind11 header files. What's the canonical way to find them, so I can add them to the include_dirs member of the Extension?

@xoltar [pbtest](https://github.com/pybind/pbtest) is a good start to create a pip-installable module that depends on pybind11.

If the pybind11 package is installed correctly, its header files should have been copied in a subdirectory called `pybind11` of your python include directory, where Python.h is for example.

*Note that `pip install pybind11` will indeed place these headers correctly but not `python setup.py install` because of a limitation of setuptools. (pip runs the setup.py script but with a certain flag called `--single-version-externally-managed`)*

To locate the headers in your extension module, you need to specify the directory as the main headers directory of python, that is `'include'`

```python
ext_modules = [
    Extension(
        'pbtest',
        [the list of your cpp files],
        include_dirs=['include'],
        language='c++',
    ),
]
```

**Comment by wjakob** [comment]
> Note that pip install pybind11 will indeed place these headers correctly but not python setup.py install because of a limitation of setuptools. (pip runs the setup.py script but with a certain flag called --single-version-externally-managed)

@SylvainCorlay: That could be a good sentence to add to the ``README.md`` of pbtest.

**Comment by xoltar** [comment]
> Note that pip install pybind11 will indeed place these headers correctly but not python setup.py install because of a limitation of setuptools. (pip runs the setup.py script but with a certain flag called --single-version-externally-managed)

Yes, I think this is the problem I saw, thanks.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay: That could be a good sentence to add to the README.md of pbtest.

:+1: will do

**Comment by xoltar** [comment]
I would also recommend adding a link to pbtest in the pybind11 readme, as well as a statement on installation (i.e., that you don't need to, pip will take care of it). I cloned and ran setup.py install, which was the beginning of my troubles. :-)
