### ISSUE TITLE
contains

### ISSUE THREAD

**Issue by RiccardoRossi** [pybind/pybind11#1235]
Make sure you've completed the following steps before submitting your issue -- thank you!

1. Check if your question has already been answered in the [FAQ](http://pybind11.readthedocs.io/en/latest/faq.html) section.
2. Make sure you've read the [documentation](http://pybind11.readthedocs.io/en/latest/). Your issue may be addressed there.
3. If those resources didn't help and you only have a short question (not a bug report), consider asking in the [Gitter chat room](https://gitter.im/pybind/Lobby).
4. If you have a genuine bug report or a more complex question which is not answered in the previous items (or not suitable for chat), please fill in the details below.
5. Include a self-contained and minimal piece of code that reproduces the problem. If that's not possible, try to make the description as clear as possible.

*After reading, remove this checklist and the template text in parentheses below.*

## Issue description

(Provide a short description, state the expected behavior and what actually happens.)

## Reproducible example code

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete C++ and Python snippets that can be easily compiled and run to diagnose the issue.)

**Comment by EricCousineau-TRI** [comment]
Might you be able to update your issue description? (Or close this one if it was a mistake?)

If you're posting to say that we should pybind-ify being able check `if x in y`, then I completely agree with you.

**Comment by RiccardoRossi** [comment]
dear Eric,
i did not realize i opened an empty issue. closing
