### ISSUE TITLE
nullptr as default argument

### ISSUE THREAD

**Issue by jmabille** [pybind/pybind11#124]
Not sure this is an issue, but I didn't find in the doc how to specify a nullptr default argument for a function. The following code will throw an exception when importing the module in Python:

```c++
module.def("my_function", &my_function, py::arg("ptr1"), py::arg("ptr2") = nullptr);
```

**Comment by wjakob** [comment]
Maybe it works when you cast nullptr to a pointer type (of the type in question?)

**Comment by jmabille** [comment]
Well done, that solves the problem.
Thanks!

**Comment by jmabille** [comment]
Seems I've close the issue too soon. The compilation is fine, however Python complains about incompatible functions arguments if I don't provide the default argument or if I pass None. That looks similar to #107

**Comment by wjakob** [comment]
weird.. I can look at it if you could provide a small snippet (It's hard to squeeze in the time to support this project, and this makes my life much easier)

**Comment by jmabille** [comment]
Ok I made further tests, actually it works with raw pointers, but not with shared_ptr. Here is a code snippet to reproduce the issue:

```c++
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <pybind11/stl.h>
#include <pybind11/numpy_array.h>
#include <iostream>

PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

namespace py = pybind11;

class Wrapper
{

public:

    Wrapper(double value) : m_value(value) {}

    double get_value() const { return m_value; }

private:

    double m_value;
};

void test_wrapper(std::shared_ptr<Wrapper> w1, std::shared_ptr<Wrapper> w2 = nullptr)
{
    std::cout << w1->get_value() << std::endl;
    if (w2)
    {
        std::cout << w2->get_value() << std::endl;
    }
}

PYBIND11_PLUGIN(dev_pybind)
{
	py::module m("dev_pybind", "pybind testing plugin");

    py::class_<Wrapper, std::shared_ptr<Wrapper>>(m, "Wrapper")
        .def(py::init<double>())
        .def("get_value", &Wrapper::get_value);

    m.def("test_wrapper", &test_wrapper, py::arg("w1"), py::arg("w2") = std::shared_ptr<Wrapper>(nullptr));

	return m.ptr();
}
```

In python:
```python
import dev_pybind as dp
w1 = dp.Wrapper(1.0)
dp.test_wrapper(w1)
```
