### ISSUE TITLE
numpy array wrappers providing STL compliant interface

### ISSUE THREAD

**Issue by jmabille** [pybind/pybind11#125]
Hi Wenzel,

I am currently developing a python extension module that does heavy manipulations on numpy arrays. Moreover, since this module can also be used by other C++ modules that have no relation with Python, the code must be generic enough to work with both numpy arrays and STL containers. For that, I've developed a wrapper around pybind11::array_t that provides a STL compliant interface (it currently works for 1D arrays only, but this will be enhanced in the future)

I think this code could be of interest for other people, but it should be in a dedicated module depending on pybind11 in order to have a good segregation of duty.

Moreover, since performance is critical, I want to avoid many calls to the Python C API, and that would require a few changes in pybind11 (one of these changes would be to store the Py_buffer inside the buffer_info as a shared_ptr instead of a raw pointer).

So my questions:
- I foresee that this would probably be a rather large amout of code. Would you consider this functionality to be in scope for pybind project ?
- At which point would it make sense for it to be in a different repo for the  pybind organization ?
- If not, would you be ok with the few changes in pybind11 mentioned earlier to enable me to have my wrappers working in a separate project ?

**Comment by jmabille** [comment]
cc @SylvainCorlay

**Comment by wjakob** [comment]
Sorry for the delay in answering to some of your PRs/tickets. I am currently in deadline mode but will try to get back to you next week.

**Comment by wjakob** [comment]
Hi Johan,

is this code available in a repository somewhere? I'd be curious to see it.

I'm not that excited about the ``shared_ptr`` change -- maybe the right thing would be to rethink ``buffer`` or ``array`` itself. But for that it would be useful to know why the shared pointers were needed.

Best,
Wenzel

**Comment by jmabille** [comment]
Hi Wenzel,

You can see the code [here](https://github.com/jmabille/pybind11/blob/numpy_array/include/pybind11/numpy_array.h) (Sorry for the formatting, I have to fix that).

The code is not totally semantically correct (especially for the resize functions) but it gives an idea on how things could work. I've added a quick implementation of wrappers on 2-dimensional arrays that satisfies my need, however a more generic implementation should be provided (as soon as I have the time to do it), providing a interface similar to boost.multiarray. Strided iterators (similar to the ones I implemented for pybind11 vectorize functionality) should also be provided.

The  need of the shared_ptr change may not be obvious in the current implementation since I only store the buffer and its size, however for N-dimensional arrays, we can't store a copy of a buffer_info object, that would  lead to a double call to PyBuffer_Release in the buffer_info destructor. Without any change in buffer_info, we'd have to store a copy of every member of buffer_info in the wrapper (except the view), and I guess you would agree it is not the right thing to do.

So somehow the buffer_info copies need to remember they share a common view and the shared_ptr seems a natural solution. Now I agree it may not be the best solution, it is just the most obvious one to avoid refactoring the buffer_info and array classes.

Johan

**Comment by wjakob** [comment]
Hello Johan,

I finally got to take a look at your class. I think it's potentially quite useful to some users, but it's a bit beyond the scope of the (intentionally) bare-bones interface to NumPy in pybind11. I think it makes more sense to release this code as a pybind11 extension in a separate repository. I'll close this ticket since there IMHO not an action item for this library. If you'd like me to link to your code at some point or create a project in the pybind project, then I'd be happy to do that.

Best,
Wenzel

**Comment by rhl-** [comment]
Hi, I think this is very useful. I thought the idea of this library was to make interaction with python seamless. Requiring users to rewrite something as obvious as a wrapper around a numpy array object seems against the mantra of "seamless integration."

**Comment by wjakob** [comment]
Note that there is already a wrapper around a numpy array that basically provides all important information about it. I'm not against extending that, it's just that the referenced project was much to heavy IMHO. The focus of this library is on seamless integration with a tiny footprint (otherwise, you can always go to Boost.Python and Boost.NumPy which have more features in any case...)
