### ISSUE TITLE
Calling Python from C++ [question]

### ISSUE THREAD

**Issue by royalstream** [pybind/pybind11#126]
Is there a way to use this library to call Python from C++? (as opposed to creating a python module from C++ code)
The *About This Project* section says *"and vice versa"* but the documentation focuses solely on exposing C++ to Python and there are no results if I search for **Py_Initialize** in the source code which could mean I'm out of luck.
That said, maybe it's still posible to do it with some additional code here and there.
If C++ callbacks are supported I would suspect the plumbing is ready for it.

**Comment by bennybp** [comment]
Yes it possible (depending on what you mean by 'call python'). It's just a bit buried - see example9. You get a python module using `pybind11::module::import()`, and then using it. For example, I do

    pybind11::module mod_sys = pybind11::module::import("sys");

where I can then change the system path for importing other module by changing `mod_sys.attr("path")`, etc. Basically, you use it like any other pybind11 module or object.

**Comment by wjakob** [comment]
You'll have to set up the python interpreter yourself with manual Python API calls. Once that is done, you can use the library as-is.

**Comment by royalstream** [comment]
Excellent, that's what I suspected but I'm relatively new to the Python C API so I wasn't sure.
