### ISSUE TITLE
Solving tight-binding Hamiltonian with spin-orbit coupling using pybinding

### ISSUE THREAD

**Issue by Leostorm10** [pybind/pybind11#1263]
Make sure you've completed the following steps before submitting your issue -- thank you!

1. Check if your question has already been answered in the [FAQ](http://pybind11.readthedocs.io/en/latest/faq.html) section.
2. Make sure you've read the [documentation](http://pybind11.readthedocs.io/en/latest/). Your issue may be addressed there.
3. If those resources didn't help and you only have a short question (not a bug report), consider asking in the [Gitter chat room](https://gitter.im/pybind/Lobby).
4. If you have a genuine bug report or a more complex question which is not answered in the previous items (or not suitable for chat), please fill in the details below.
5. Include a self-contained and minimal piece of code that reproduces the problem. If that's not possible, try to make the description as clear as possible.

*After reading, remove this checklist and the template text in parentheses below.*

## Issue description

(Provide a short description, state the expected behavior and what actually happens.)

## Reproducible example code

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete C++ and Python snippets that can be easily compiled and run to diagnose the issue.)

Hi,   
  I looked into the documentation of pybinding and nowhere mentioned about using spin-orbit coupling uses. I would like to know if spin-orbit copling can be solved using pybinding for example Kane-mele model and plot the eigenstates in real space.

Thanks,

**Comment by Leostorm10** [comment]
Hi,

Is it possible to solve tight-binding Hamiltonian with spin-orbit coupling in pybinding. I cannot find any such example. Also, if it is possible to plot eigenstates of Hamiltonian in real space.

Thanks,

**Comment by JoelStienlet** [comment]
Hello!
there is a confusion with this library: https://github.com/dean0x7d/pybinding
pybind11 is a library to export C++ functions to python, no calculations done here!

**Comment by wjakob** [comment]
Puzzle solved -- I was also starting to get curious about the relation of pybind11 and spin-orbit couplings :).

**Comment by Leostorm10** [comment]
Ok, many thanks for your reply.
