### ISSUE TITLE
Crash on pure virtual overload

### ISSUE THREAD

**Issue by dlunch** [pybind/pybind11#127]
PYBIND11_OVERLOAD_PURE crashes when i tried to call python overloaded function from C++ code. pybind11 crashes on following line:
`pybind11::str caller = pybind11::handle(frame->f_code->co_name).str();`
the value of frame was null. 
I suspect there isn't a python frame because i use pybind11 as python embedding library for my application. 

Thanks.

**Comment by wjakob** [comment]
Is it possible that you did not initialize Python correctly? Or is this simply the first entry point to the Python side? In that case it is probably better to use pybind11::call()

**Comment by dlunch** [comment]
It's first entry point to the python side. How can I get python side overloaded function?

**Comment by wjakob** [comment]
Did you try the function I just mentioned?

**Comment by dlunch** [comment]
I have to get python side function before i can call(). I'm trying to call python class's overloaded method. I can't find any method to get function object of python descendent class's method.

**Comment by wjakob** [comment]
I fear you are on your on with regards to that.. This sort of thing was not meant to be done via PYBIND11_OVERLOAD_PURE, and it's not something that was generally considered while writing the API.

The best approach is probably to figure out how to do it with raw Python C-API and then convert it into pybind11, adding functions that may not be present now.

**Comment by dlunch** [comment]
OK, I'll try it. Thanks.
