### ISSUE TITLE
Structured dtype field ordering now handled differently in NumPy 1.14.0

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#1274]
This works on NumPy 1.13:

```cpp
struct Foo { int x; int y; };
PYBIND11_NUMPY_DTYPE(Foo, y, x);
```

but on 1.14 it now throws:

```python
ImportError: NumPy: invalid buffer descriptor!
```

I guess the reason is this:

> Second, assignment between structured arrays will now occur "by position"
instead of "by field name". The Nth field of the destination will be set to the
Nth field of the source regardless of field name, unlike in numpy versions 1.6
to 1.13 in which fields in the destination array were set to the
identically-named field in the source array or to 0 if the source did not have
a field.

> Correspondingly, the order of fields in a structured dtypes now matters when
computing dtype equality.

```python
# 1.13
>>> d1 = np.dtype({'names': ['x', 'y'], 'formats': ['i4', 'i4'], 'offsets': [0, 8]})
>>> d2 = np.dtype({'names': ['y', 'x'], 'formats': ['i4', 'i4'], 'offsets': [8, 0]})
>>> d1 == d2
True
```

```python
# 1.14
>>> d1 = np.dtype({'names': ['x', 'y'], 'formats': ['i4', 'i4'], 'offsets': [0, 8]})
>>> d2 = np.dtype({'names': ['y', 'x'], 'formats': ['i4', 'i4'], 'offsets': [8, 0]})
>>> d1 == d2
False
```

**Comment by wjakob** [comment]
Closed by #1837.
