### ISSUE TITLE
Migration from Boost.Python

### ISSUE THREAD

**Issue by polyvertex** [pybind/pybind11#128]
I'm considering migrating from Boost.Python to pybind11 for a C++ application that embeds Python3 (Windows platform). Main reason is I would like to get rid of this huge Boost dependency.

The project is nothing fancy in regards to the inter-language connection: exposed C++ classes, heavy use of std::shared_ptr, tied lifetime of C++-Python objects. Exception-protected at inter-language boundaries. Casting of shared_ptr objects, strings, vector, list and map containers. No custodian_and_ward'ish policy.

While it seems pybind11 "just works" (tm) and that my use case seems to fit perfectly on paper, it is unclear to me whether it can be considered *stable* enough for such a migration. Would you advise me wait a bit or to start digging?

**Comment by wjakob** [comment]
It should work, but it's really your call...
