### ISSUE TITLE
Template test functions on double and DataVector

### ISSUE THREAD

**Issue by osheamonn** [pybind/pybind11#1285]
## Issue description

Test functions for pointwise functions should be templated on both double and DataVector and make_with_value used in the CHECK statement. This should also remove the need for `check_tensor_doubles_equals...` function.

**Comment by jagerman** [comment]
Was this issue filed on the wrong project?  It doesn't seem to have anything to do with pybind11 itself.

Closing.

**Comment by osheamonn** [comment]
Yes I opened the wrong tab, my apologies!
