### ISSUE TITLE
How to create a NumPy scalar in C++?

### ISSUE THREAD

**Issue by mgeier** [pybind/pybind11#1288]
Currently I'm using `py::float_`, which corresponds to a C++ `double` and a `numpy.float64`.

Is there a way to create other NumPy scalar values, like e.g. `numpy.float32`?

I've looked in `numpy.h` but I didn't find anything that sounded like it could do that ...

**Comment by EricCousineau-TRI** [comment]
A simple way would be to do something like:
```
py::module np = py::module::import("numpy");
py::print(np.attr("float32")(10.2));
```

There's also `py::dtype::of<T>()`, which gives you the `PyArray_Desc` object, and you can query the `type` object to then get the class:
```
py::object float32 = py::dtype::of<float>().attr("type");
py::print(float32(10.2));
```

[Example source](https://github.com/EricCousineau-TRI/repro/blob/eb14d3afd3eb0cd4186b5799a94b4e31b0d711bc/python/pybind11/dtype_stuff/test_issue_1288.cc)

**Comment by mgeier** [comment]
Thanks a lot @EricCousineau-TRI, that works perfectly!

I'm currently needing the second option, because I'm starting from a C++ type, but it's good to know that it's also possible to get a scalar type given its string representation.
