### ISSUE TITLE
Pybind11 doesn't provide an equivalent to Boost.Python's "name" property of enum_ objects

### ISSUE THREAD

**Issue by bstaletic** [pybind/pybind11#1290]
## Issue description

Boost.Python provides a `name` property for its python objects. It's (probably) the most useful for `enum_` objects, which is my use case.

I know there is a `__members__` dictionary, which I'm currently using and which is equivalent of Boost.Python's `names` dictionary. However this means I have to iterate over the dictionary for every `enum_` I happen to instantiate. It would be much more efficient if I could just read the value stored in some attribute.

That said, I'm bundling just the pybind11 headers in my project, so I tried to modify the `pybind11::enum_::value()` on my own.

```c++
    enum_& value(char const* name, Type value, const char *doc = nullptr) {
        auto v = pybind11::cast(value, return_value_policy::copy);
        this->attr(name) = v;
        m_entries[pybind11::str(name)] = std::make_pair(v, doc);
        // Added by me:
        this->def_property_readonly("name",  [name](const Type &value){return str(name);});
        // End of my modifications
        return *this;
}
```

But this resulted in [this binding](https://github.com/bstaletic/ycmd/blob/pybind11_rfc/cpp/ycm/ycm_core.cpp#L134-L145) always evaluating `name` to `UNKNOWN` as `UNKNOWN` is the last enumeration value declared.

## Reproducible example code

```c++
#include <pybind11/pybind11.h>

using namespace pybind11;

enum class A { B };

PYBIND_MODULE(module_name, m) {
    enum_<A>(m, "A").value("B", A::B);
}
```

Interactive python session:
```
>>> import module_name
>>> module_name.A.B.name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ycm_core.DiagnosticKind' object has no attribute 'name'
```

For reference, Boost.Python:
```c++
#include <boost/python.hpp>

using namespace boost::python;

BOOST_PYTHON_MODULE(module_name) {
    enum_<A>("A").value("B", A::B);
}
```

The same session for Boost.Python:
```
>>> import module_name
>>> module_name.A.B.name
'B'
```

**Comment by bstaletic** [comment]
I've also tried implementing `__inverted_members__`, which is just `__members__`, but with keys and values inverted. This allowed me to just have a dictionary look up instead of iterating over the whole dictionary.

Still, not as convenient as a dedicated attribute.

**Comment by bstaletic** [comment]
Since this was implemented, I'll close the feature request.

**Comment by jagerman** [comment]
> Since this was implemented, I'll close the feature request.

For future reference (in case you didn't already know this): Sticking "Fixes #xyz" somewhere in the PR description will make github do that automatically upon merging.
