### ISSUE TITLE
Transfer Class Ownership to C++ on Construct

### ISSUE THREAD

**Issue by bgoodman44** [pybind/pybind11#1297]
I'm having an issue where a python class, which is derived from a c++ using pybind11, is being immediately destructed (garbage collected).  I would like C++ to take ownership of the dynamically allocated object, but I can't seem to make that happen.  I've tried keep_alive, passing shared_ptr<> as py::class_ template argument, and py::return_value_policy... nothing is working.  I suspect this is just user error.

This is a simplification of the real issue I'm having with a much larger code base that is architected similarly.  Changing the architecture is not an option, so making this example work is critical for me.

I have two c++ classes that I have created python interfaces for using pybind11.  Class A and B  both have virtual methods, so they have corresponding trampoline classes to support inheritance.  The user calls the B::Run() function which results in a dynamically allocated (via new) A object to be created.  When I create specializations of these two classes in python, as shown below.... Segmentation fault because the B::aBase is destroyed immediately after B::Run being called.

Any Ideas how to fix this?  Thanks in advance!

```
class A
{
public:
    A(){};
    virtual ~A()
    {
        std::cout << "In A::~A()\n";
    };

    virtual char* SayHello()
    {
        char* x = "\n\nHello from Class A\n\n";
        return x;
    }
};

class ATramploline : public A
{
public:
    using A::A;
    char* SayHello() override
    {
        PYBIND11_OVERLOAD( char*,A,SayHello,);
    }
};


class B
{
public:
    B()
    {
        std::cout << "In Class B Constructor\n";
    }

    void Run()
    {
        aBase = AllocateAnAClass();
        std::cout << aBase->SayHello();
    }

    virtual ~B()
    {
        fprintf(stderr,"About to delete aBase");
        delete aBase;
    }

    A* aBase;

    virtual A* AllocateAnAClass()
    {
        return new A;
    }
};

class BTramploline : public B
{
public:
    using B::B;
    A* AllocateAnAClass() override
    {
        PYBIND11_OVERLOAD( A*,B,AllocateAnAClass,);
    }
};

PYBIND11_MODULE(TestModule,m)
{
    py::class_<A,ATramploline>(m,"A")
        .def(py::init<>(),py::return_value_policy::reference_internal)
        .def("SayHello",&A::SayHello);

    py::class_<B,BTramploline>(m,"B")
        .def(py::init<>())
        .def("Run",&B::Run)
        .def("AllocateAnAClass",&B::AllocateAnAClass,py::return_value_policy::reference_internal);
}

```
```
#!/usr/bin/python3

from TestModule import A,B
class MyA(A):
    def __init__(self):
        super().__init__()
        print("Done with MyA Constructor")

    def SayHello(self):
        return '\n\nHello from Class MyA\n\n'

class MyB(B):
    def __init__(self):
        super().__init__()
        print("Done With MyB Constructor")
    def AllocateAnAClass(self):
        print("In MyB::AllocateAnAClass!!!")
        return MyA()

#x = B()
#x.Run()

y = MyB()
y.Run()

print("done with test script\n")
```

**Comment by uwydoc** [comment]
i think you have to change the return type of `AllocateAnAClass` from `A *` to `pybind11::object`, and keep that returned object as a member of class B, to keep the object from being gc-ed. according to my limited knowledge with pybind11, the owership transfer just cannot happened that magically.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bgoodman44** [comment]
If I set up MyB::AllocateAnAClass to be:

```
def AllocateAnAClass(self):
        print("In MyB::AllocateAnAClass!!!")
        self._dummy = MyA()
        return self._dummy
```
It works... until the "B" base class destructs the object that it is supposed to own.  For this trivial example, its simple enough to change the memory managment structure.... but for the MUCH larger codebase I'm dealing with, it is not.  I need python to maintain NO ownership over the object.  This seems like a fairly trivial and commonly required capability.

Thank you for your response, but can this really be the only solution?  It seems completely impractical for larger projects to create python copies and change the return type from a base class pointer to a py::object.  SWIG handled this without an issue....but SWIG is a major PITA for debugging (etc), which is why I landed on pybind11.

I thought this is EXACTLY what py::return_value_policy is supposed to do? py::init<> is essentially just producing a call of "new A;" 

What am I missing here?

**Comment by jagerman** [comment]
If `A` objects are never used independently in Python, you can bind them with:
```
py::class_<MyClass, std::unique_ptr<MyClass, py::nodelete>>(...)
```
to tell pybind to never delete them when the Python wrapper gets garbage collected.  It's trivially easy to cause a memory leak (just construct an `A` without giving it to a `B`--including, for example, an exception occuring (even if caught) between initialization and handing it off to the B), but it looks like what you're looking for.

**Comment by jagerman** [comment]
As for `return_value_policy`: `py::init<>` is just a shortcut for declaring an `__init__`, which doesn't *have* a return value to apply a policy to.  For `.def("AllocateAnAClass", ...)` it's not going to help: when a pointer is returned that pybind already knows about (which will happen in this case -- because the returned object is already wrapped in another pybind-managed object) we just incref the other object.

One other point, in passing: `super().__init__()` is likely to get you into trouble if you have multiple inheritance happening (in particular, multiple inheritance from Python of multiple wrapped C++ base classes).  This is unfortunately, but Python's MRO is fundamentally incompatible with C++: there's no simple way to work around it to force the MRO into a C++-compatible base class initialization chain.  You're definitely safer sticking to `Base.__init__(self)`.  (Though if you don't have multiple inheritance you don't need to worry, but something to be aware of).

**Comment by bgoodman44** [comment]
Thanks jagerman!  This is EXACTLY what I needed.  Also, thanks for the note on super()...didn't realize that could be an issue.
