### ISSUE TITLE
Setting __file__ in eval_file

### ISSUE THREAD

**Issue by jeandet** [pybind/pybind11#1300]
Hi,
I wonder if it wouldn't make sense to set __file__ global variable by default inside pybind11::eval_file executed scripts might want to use it.
A kind of recurring pattern in python is:
```
import os
script_path = os.path.realpath(__file__)
```

**Comment by EricCousineau-TRI** [comment]
Seconded. Nominally, if you try and use `trace` in a file executed via `py::eval_file` without having set `__file__`, you won't see any commands for that file. An example usage (albeit a hacky motivation - for debugging in CLion):
[Python code](https://github.com/EricCousineau-TRI/pybind11/blob/a6df0a26735d390ae6e2097bf94f8ad64a5c6b53/tests/test_numpy_dtype_user.py#L161-L163)
[C++ code](https://github.com/EricCousineau-TRI/pybind11/blob/a6df0a26735d390ae6e2097bf94f8ad64a5c6b53/tests/test_numpy_dtype_user.cpp#L246-L248)
