### ISSUE TITLE
Invoking a C function with std::initializer_list argument

### ISSUE THREAD

**Issue by ffreckle** [pybind/pybind11#1302]
I cannot figure out how to invoke a C function with an std::initializer_list argument from Python.  I posted this question first on Stackoverflow then in the Gitter chat room. I also looked around for a relevant test case and could not find one.   Perhaps this is not supported?   The C function is:
```
#include <iostream>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
using namespace std;
namespace py = pybind11;
void list_ints(const std::initializer_list<int> &il) {
        std::cout << "Got to list_ints ..." << std::endl;
	for (const auto &elem : il)
		std::cout << to_string(elem) << " ";
	std::cout << std::endl;
};
PYBIND11_MODULE(initializer, m) {
    // This does not match anything
    m.def("list_ints", &list_ints);
    // This matches a list argument and invokes the function, then BOOM.
    m.def("list_ints", (void (*) (const std::vector<int>&)) &list_ints);
}
```
The python code to invoke this function is:
```
from initializer import list_ints
l = [1,2]
# Call succeeds but function Seg Faults!
list_ints(l)
print(l)
```
The function only succeeds with the addition of the second m.def() above.  Using only `m.def("list_ints", &list_ints)` results in a TypeError: list_ints(): incompatible function arguments whether I'm passing *args or a single list.  With the second binding in place, the output is:
```
Got to list_ints ...
1 2 0 -1073741824 0 0 259188368 ...
```
and then BOOM.  It iterates off the end of the initializer list.  I'm running on MacOS/llvm, --std=c++14, Python 3.4.  I can call this same function in C with `list_ints({1,2,3,4,5})` and it works as expected.

**Comment by jagerman** [comment]
It's not supported and, I believe, not *possible* to support: an initializer list is a deliberately opaque type designed to only be constructible by the C++ compiler but *not* by C++ code--and that means that it just isn't possible for us to accept it.

See the answer to https://stackoverflow.com/questions/29314156/c11-is-it-possible-to-construct-an-stdinitializer-list for some more details.

As for your binding code, you're basically `reintepret_cast`ing your function into a function that takes a different type.  Pybind constructs a `std::vector<int>` then passes this along as the function argument, but the function thinks it's getting a `std::initializer_list`--and then Bad Things happen.  It's basically doing `auto &il = reintepret_cast<std::initializer_list<int> &>(v)` for the argument, where `v` is a `std::vector<int>`.

**Comment by ffreckle** [comment]
@jagerman Got it.  Thanks for the response and link.

**Comment by kidnapping78** [comment]
Look here for more https://stackdev.space/questions/can-you-please-explain-the-meaning-of-this-list-of-initializers
