### ISSUE TITLE
Multiple inheritance with user defined holder type

### ISSUE THREAD

**Issue by terraform123** [pybind/pybind11#1306]
## Issue description

In a multiple inheritance scenario, the implicit up-cast from derived type to base type does not work when using a user defined smart pointer (i.e. holder) type of a derived class.

In case of using std::shared_ptr, or when inheriting only from one base class, the issue is not present.

The example works in C++, but does not work in python. Implicit cast definition in the python wrapping code does not help (declare it for C->A and C->B). Can not declare implicit cast between holder types.

## C++ code
```c++
template< typename T >
class MyHolder
{
public:
    explicit MyHolder( T* ptr = nullptr ) : ptr_( ptr ) {}
    template< typename U > MyHolder( MyHolder< U > ptr ) : ptr_( dynamic_cast< T* >( ptr.get() ) ) {}
    T* get() { return ptr_; }
    T* operator-> () const { return ptr_; }
private:
    T* ptr_;
};


class A
{
public:
    virtual ~A() = default;
    virtual void foo() = 0;
};

class B
{
public:
    virtual ~B() = default;
    virtual void bar() = 0;
};

class C : public A, public B
{
public:
    C() = default;
    virtual void foo() override
    {
        std::cout << "foo" << std::endl;
    }
    virtual void bar() override
    {
        std::cout << "bar" << std::endl;
    }
};

void testA( MyHolder< A > ptr )
{
    ptr->foo();
}

void testB( MyHolder< B > ptr )
{
    ptr->bar();
}
```
## Wrapping code
```c++
PYBIND11_DECLARE_HOLDER_TYPE( T, MyHolder< T >, true );

PYBIND11_MODULE( test, m )
{
    pybind11::class_< A, MyHolder< A > >( m, "A" )
        .def( "foo", &A::foo );

    pybind11::class_< B, MyHolder< B > >( m, "B" )
        .def( "bar", &B::bar );

    pybind11::class_< C, MyHolder< C >, A, B >( m, "C" )
        .def( pybind11::init<>() );

    m.def( "testA", &testA );
    m.def( "testB", &testB );
}
```
## C++ test code
```c++
int main()
{
    auto c = std::unique_ptr< C >( new C() );
    auto ptr = MyHolder< C >( c.get() );
    testA( ptr );
    testB( ptr );
    return 0;
}
```
Output:
```
foo
bar
```
## python test code
```python
c = test.C()
test.testA( c )
test.testB( c )
```
Output:
```
TypeError: testA(): incompatible function arguments. The following argument types are supported:
    1. (arg0: test.A) -> None

Invoked with: <test.C object at 0x...>
```

**Comment by jagerman** [comment]
The issue here is that when multiple inheritance is involved we rely on a constructor compatible with `std::shared_ptr`'s aliasing constructor ([constructor (8) here](http://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr)), which lets us create a holder containing a recast pointer (i.e. an `A *`) that keeps the original `C *` alive (and, if it ends up being the last object, destroys the `C *` rather than the `A *`).

If you add:
```
    MyHolder( const MyHolder &other, T* ptr ) : ptr_(ptr) {}
```
the example will work.  (Your example holder doesn't do any actual memory management, of course; in reality it would need to support the sort of aliasing described above).

**Comment by terraform123** [comment]
Thanks a lot for the explanation. I figured as much that I am missing some shared_ptr goodness, but could not figure out what.

**Comment by kliegeois** [comment]
I am facing the exact same issue. Is there any other extra requirements in term of constructors of the holder class now?
By the way, I might be wrong but I think that this constructor requirement is not listed in the documentation, that might be useful to include some comments about this.

**Comment by kliegeois** [comment]
I am facing the exact same issue. Is there any other extra requirements in term of constructors of the holder class now?
By the way, I might be wrong but I think that this constructor requirement is not listed in the documentation, that might be useful to include some comments about this.
