### ISSUE TITLE
Segmentation fault: 11 when trying to make std::string opaque

### ISSUE THREAD

**Issue by Pulsar18** [pybind/pybind11#1311]
When I am trying to use `PYBIND11_MAKE_OPAQUE(std::string);` the code compiles but as soon as I want to import it into python i get a "Segmentation fault: 11". Is it not possible to make a std::string opaque in analogy to `PYBIND11_MAKE_OPAQUE(std::vector<int>);`?

**Comment by NaniBird** [comment]
How did you solve this ?
