### ISSUE TITLE
simple test file - cmake, setup.py, no symbols exported (but can import module in python)

### ISSUE THREAD

**Issue by gminorcoles** [pybind/pybind11#1313]
HI,
  I have a project that I am trying to wrap with pybind11 on ubuntu 16.04. I am using cmake 3.5.x,  python 2.7, anaconda distribution. 

I have copied the example setup.py, and modified it to use cmake for the build. This seems to work. 

My project structure is intended to be a pybind cpp file which called a function called fwa_logile. The pybind stubb cpp file links a library with all the important functonality. This libarary is a depednency in cmake. It builds and runs when I do the executable target. 

When I run the fwa_python target, it all seems to work, including the setup.py stuff. I can import the module in python, but then when I try to call "test_fwa" is say module has no attribute test_fwa. 

I ran "nm -D fwa_python.so"
 on my .so file, and it seems that anything matching "test_fwa" is indeed not defined. But the object file does have that function defined. 

Here is the output of setup.py install. Can anyone help me troubleshoot this? 

running install
running bdist_egg
running egg_info
writing requirements to fwa.egg-info/requires.txt
writing fwa.egg-info/PKG-INFO
writing top-level names to fwa.egg-info/top_level.txt
writing dependency_links to fwa.egg-info/dependency_links.txt
reading manifest file 'fwa.egg-info/SOURCES.txt'
writing manifest file 'fwa.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
-- Found PythonInterp: /home/QIM/george/miniconda2/bin/python (found suitable version "2.7.12", minimum required is "2.7") 
-- Found PythonInterp: /home/QIM/george/miniconda2/bin/python (found version "2.7.12") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/QIM/george/src/lab/george/tsapi/build/temp.linux-x86_64-2.7
[ 97%] Built target tsalib
Scanning dependencies of target fwa_python
[ 98%] Building CXX object fwa_python/CMakeFiles/fwa_python.dir/fwa_python.cpp.o
[100%] Linking CXX shared module ../../lib.linux-x86_64-2.7/fwa_python.so
/usr/bin/c++  -fPIC -fpermissive -O3 -DNDEBUG  -shared  -o ../../lib.linux-x86_64-2.7/fwa_python.so CMakeFiles/fwa_python.dir/fwa_python.cpp.o -flto ../tsalib/libtsalib.a -lpthread -ldl -lquickfix 
[100%] Built target fwa_python
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/fwa_python.so -> build/bdist.linux-x86_64/egg
creating stub loader for fwa_python.so
byte-compiling build/bdist.linux-x86_64/egg/fwa_python.py to fwa_python.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying fwa.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fwa.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fwa.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fwa.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fwa.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying fwa.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/fwa-0.1.5-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing fwa-0.1.5-py2.7-linux-x86_64.egg
removing '/home/QIM/george/miniconda2/lib/python2.7/site-packages/fwa-0.1.5-py2.7-linux-x86_64.egg' (and everything under it)
creating /home/QIM/george/miniconda2/lib/python2.7/site-packages/fwa-0.1.5-py2.7-linux-x86_64.egg
Extracting fwa-0.1.5-py2.7-linux-x86_64.egg to /home/QIM/george/miniconda2/lib/python2.7/site-packages
fwa 0.1.5 is already the active version in easy-install.pth

Installed /home/QIM/george/miniconda2/lib/python2.7/site-packages/fwa-0.1.5-py2.7-linux-x86_64.egg
Processing dependencies for fwa==0.1.5
Searching for pybind11==2.2.2
Best match: pybind11 2.2.2
Adding pybind11 2.2.2 to easy-install.pth file

Using /home/QIM/george/miniconda2/lib/python2.7/site-packages
Finished processing dependencies for fwa==0.1.5

**Comment by jagerman** [comment]
What is in your `fwa_python.cpp` file?  This is a guess, but it sounds, from your description, like you're missing the module definition/binding code.  See [Creating bindings for a simple function](http://pybind11.readthedocs.io/en/stable/basics.html#creating-bindings-for-a-simple-function) in the docs.

**Comment by gminorcoles** [comment]
I have the module definition macro there just like the examples. I cannot access any project files right now I am only on My phone.

**Comment by henryiii** [comment]
I don't think there's enough here to go on. Please reopen if there's still an issue!
