### ISSUE TITLE
Replace sscanf by sscanf_s on Windows?

### ISSUE THREAD

**Issue by anntzer** [pybind/pybind11#1314]
## Issue description

PYBIND11_PLUGIN currently uses sscanf to parse the output of Py_GetVersion().  On MSVC, the use of sscanf triggers a warning:
> warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

Obviously 1) the warning is spurious (the literal format used is totally safe) and 2) the programmer could, indeed, set _CRT_SECURE_NO_WARNINGS; but still, perhaps pybind11 could just use sscanf_s there?

## Reproducible example code

N/A

**Comment by jagerman** [comment]
I'm testing a fix (linked above via commit message reference) for this by just building and checking for the major/minor version string prefix we expect (rather than doing any string-to-integer conversion at all).
