### ISSUE TITLE
keep_alive with lists and other destruction dependancies

### ISSUE THREAD

**Issue by blapid** [pybind/pybind11#1315]
## Issue description
Hi, I've been using pybind11 successfully for a number of projects lately, but I'm having an issue with my current project and would appreciate some feedback from the more experienced users or devs.

Basically, I have a 3rd party C++ library, the issue with it's API can be summed down to this (full example file in a gist linked below):
```c++
struct B;
struct A {
	A() {};
	~A() {
		printf("~A()\n");
		if (!b_list.empty()) {
			printf("b_list not empty!\n");
		}
	};
	void register_b(B *b) {
		b_list.push_back(b);
	};
	void unregister_b(B *b) {
		auto removed = std::remove(b_list.begin(), b_list.end(), b);
		b_list.erase(removed, b_list.end());
	};
	std::list<B *> b_list;
};

struct B {
	B(A& a) : m_a(a) {
		m_a.register_b(this);
	};
	~B() {
		printf("~B()\n");
		m_a.unregister_b(this);
	};
	A& m_a;
};
```

Which means the user is supposed to make sure that A is destructed after all B's created with that A are destructed. I know the API can be much better, but being 3rd party I don't have much choice in the matter.

I tried using pybind11 to create a module for this interface:
```c++
PYBIND11_MODULE(example, m) {
	py::class_<B>(m, "B");
	py::class_<A>(m, "A")
		.def(py::init<>())
		.def("get_b_list", [](A& _this) ->  std::list<B> {
			std::list<B> b_list
			// Note: Actual enumeration code omitted, 
			// 	I just create some items to demonstrate the issue.
			b_list.push_back({_this});
			b_list.push_back({_this});
			return b_list;
		}, py::return_value_policy::move);
}
```

And use it with a simple test script:
```python
import example
a = example.A()
b1 = a.get_b_list()
print b1
```

This attempt does not work because I don't convey the dependancies to python, and so A may be destructed before all of the B's and I get the print message in A's destructor (which is an assert in the actual library).

After going through the docs, I saw the `keep_alive` option and thought I should add it to `get_b_list` defs: `py::return_value_policy::move, py::keep_alive<0, 1>());` (we want A to be destroyed only after the list, and therefore after its items, are destructed)

This leads to the following error: `RuntimeError: Could not allocate weak reference!`. Which makes sense because python doesn't support weakrefs to lists :(

This leaves me with three options:
1. There's a better way to do this which is already integrated into pybind11 but I haven't figured it out yet.
2. lists+weakrefs makes sense as a feature request for pybind11. I went down that rabbit hole for a couple of hours and got somewhere, but it's *really* hacky.
3. Wrap the API in a way that preserves the destruction condition in C++.

I ended going with 3, I don't want to clutter this post with more code so please find it here: https://gist.github.com/blapid/69cba9f58abf38ecb84a0d3c1a241fef .

I post this issue with two goals:
1. If I missed anything, and option 1 is correct, I'd love to hear about the correct approach.
2. If anyone else is having this issue, I hope my API wrapping idea may be useful for them as well.

Cheers!
## Reproducible example code
https://gist.github.com/blapid/26d82fad2ae59744cbebe6bfa0235270

**Comment by jagerman** [comment]
If your `std::list` was actually a `std::vector` then I think `pybind11/stl_bind.h`'s `bind_vector` would be the answer.  Without binding the container, all you get (via `stl.h`) is copying of the returned list contents into a native Python list, which doesn't seem like what you want.

The problem is that we don't actually *have* a `bind_list` in `stl_bind.h`, but I think that that (hypothetical) feature is pretty much exactly what you're looking for.  The good news is that it would probably be fairly easy to implement using some of the existing `bind_vector` code, but with SFINAE checks for the various definitions that rely on `operator[]` (like `__getitem__`/`__setitem__`/`__delitem__`).  It might also need some tweaks to allow for non-copyable element types (e.g. your `B` elements in the example), and to only call `reserve()` if the container has such a method.

(It might also make sense to mimic (some of) the [`deque`](https://docs.python.org/3/library/collections.html#collections.deque) interface since a `std::list` is far closer to a Python `deque` than a Python `list`.)

And in case it wasn't obvious, I'm hinting that a PR implementing this would be very welcome. :)

**Comment by blapid** [comment]
Thanks for the reply @jagerman  :) In hindsight, I haven't mentioned that I've tried with both vector and list and got similar results :(
See https://gist.github.com/blapid/26d82fad2ae59744cbebe6bfa0235270
Compiling and running the test.py file yields the issue as well - either A is getting destructed before B's and sometimes causes a segfault or "cannot allocate weakref" (if using `keep_alive`).

If I'm not missing anything, I think my difficulty isn't with the container binding, but with enforcing the destruction dependancies - hence my attempt to use `keep_alive`. Unfortunately `keep_alive<0,1>` and python lists don't seem to work together.

**Comment by jagerman** [comment]
Right, but `keep_alive` *does* work with `bind_vector` and I think will do what you want.

**Comment by jagerman** [comment]
Here's with a `bind_vector` (I had to change `B` slightly to make it copy assignable--by storing a `A*` rather than `A&`):
```
$ python3 -c 'from i1315 import *; print("hi"); z = A().get_b_list(); print("bye")'
hi
~B()
~B()
~B()
~A()
bye
~B()
~B()
```
and here's the output with `keep_alive<0, 1>()` added to the definition:
```
hi
~B()
~B()
~B()
bye
~B()
~B()
~A()
```

**Comment by blapid** [comment]
Yeah I just tried it myself too. Thats awesome, thanks!
Out of curiosity, is there a way to use `bind_vector` if B was not copy assignable?

**Comment by jagerman** [comment]
IIRC, `std::vector` itself requires copy assignability.  A hypothetical `bind_list` wouldn't.

**Comment by jagerman** [comment]
I think the way to think about this would be that `bind_list` would be the base implementation for a `list`, then `bind_vector` would use all of that plus add the extra things (like indexing) that a vector gives you.

**Comment by blapid** [comment]
I see. The requirement is indeed from `std::vector` but it depends on how you use it (it fails on the definition of insert, up until then it's fine).

I'll definitely look into `bind_list`, will do my best to get a PR going.

Thank's for the help! :)
