### ISSUE TITLE
Is there documentation that lists all the APIs?

### ISSUE THREAD

**Issue by xchern** [pybind/pybind11#1332]
After trying binding my fluid simulator to python with pybind11, I find that the library is convenient. But actually the documentation is not adequate enough, some useful methods are not in the documentation, which make it painful to write coding. For example, the `bool contains(const char *key) const` of `pybind11::dict` and the constructors of `pybind11::array::ShapeContainer`.

Googling a lot but find nothing, finally I had to read the code to get these APIs. Thank the God for the well organized code, which makes code reading much easier.

So I wonder, if there exists a official API doc which lists all the methods for classes?

**Comment by jagerman** [comment]
Some of the API (generated from the doxygen-formatted comments in the code) is available at: https://pybind11.readthedocs.io/en/stable/reference.html but as the warning at the top says:

"Please be advised that the reference documentation discussing pybind11 internals is currently incomplete. Please refer to the previous sections and the pybind11 header files for the nitty gritty details."

**Comment by xiaosong0911** [comment]
Oh, so reading the code is just the proper way. Sorry for my carelessness...

Thanks for your help!

**Comment by YannickJadoul** [comment]
Seems to be resolved, so closing.
