### ISSUE TITLE
How to turn py::kwargs item.second to an expected type

### ISSUE THREAD

**Issue by xsh6528** [pybind/pybind11#1341]
I want to do something similar to

```
bool switch;
for (auto item : kwargs) {
if (item.first == "switch") {
  switch = item.second;
}
```
Now, it gives
```
error: assigning to 'bool' from incompatible type 'pybind11::handle'
```

**Comment by jagerman** [comment]
`item.first` and `item.second` are generic Python objects (wrapped in `py::handle` wrappers); you need to cast it to the desired C++ type:

```C++
    switch = py::cast<bool>(item.second);
```
See http://pybind11.readthedocs.io/en/stable/advanced/pycpp/object.html#casting-back-and-forth
and http://pybind11.readthedocs.io/en/stable/advanced/cast/index.html

Also I might suggest asking these types of questions on the [gitter channel](https://gitter.im/pybind/Lobby) -- it's a more appropriately place (the issue tracker here is really meant for reporting bugs), but also you'll tend to get a faster response for questions like this there than asking here.
