### ISSUE TITLE
Pybind11 causes clang 3.3 and clang 3.4 to segfault

### ISSUE THREAD

**Issue by bstaletic** [pybind/pybind11#1349]
## Issue description

As it stands now, compiling with clang 3.4 (assuming the same goes for clang 3.3) makes clang segfault. To work around this, Valloric/ycmd#925 had to drop support for clang 3.3 and clang 3.4.

Looking at [the current `ycm_core.cpp`](https://github.com/bstaletic/ycmd/blob/pybind11_rfc/cpp/ycm/ycm_core.cpp) and [the last year's segfaults](https://travis-ci.org/bstaletic/ycmd/jobs/268804565) ([today's segfaults](https://travis-ci.org/bstaletic/ycmd/jobs/362463412) don't look much different to me), @jagerman thought it had something to do with the static variable used in exception binding and told me to try the following in `pybind11.h`. 

```c++
NAMESPACE_BEGIN(detail)
template <typename CppException>
exception<CppException> &get_exception_object() {
    static exception<CppException> ex;
    return ex;
}
NAMESPACE_END(detail)

/**
 * Registers a Python exception in `m` of the given `name` and installs an exception translator to
 * translate the C++ exception to the created Python exception using the exceptions what() method.
 * This is intended for simple exception translations; for more complex translation, register the
 * exception object and translator directly.
 */
template <typename CppException>
exception<CppException> &register_exception(handle scope,
                                            const char *name,
                                            PyObject *base = PyExc_Exception) {
    auto &ex = detail::get_exception_object<CppException>();
    ex = exception<CppException>(scope, name, base);
    register_exception_translator([](std::exception_ptr p) {
        if (!p) return;
        try {
            std::rethrow_exception(p);
        } catch (const CppException &e) {
            detail::get_exception_object<CppException>()(e.what());
        }
    });
    return ex;
}
```

This did solve the segmentation fault (at least on clang 3.4), but is now causing [compilation errors](https://travis-ci.org/bstaletic/ycmd/jobs/362466751).

## Reproducible example code

Unfortunately, I can't make this minimal. Something, somewhere in ycmd libclang completer bindings is making clang 3.3 segfault, but I am willing to run tests on travis.

Since travis only supports clang 3.4, I'll try to package clang 3.3 for my distro so that we can test it. I still can't promise I'll manage to get clang 3.3 ready for testing. I will be using https://github.com/bstaletic/ycmd/tree/pybind11_segfault to test whatever we come up with.

**Comment by jagerman** [comment]
Add: `exception() = default;` to the 'class exception' just above that code; that should fix the compilation error.

If this solves the problem I'll clean up the patch to `#ifdef` this approach for clang < 3.5.

**Comment by jagerman** [comment]
The issue here is almost certainly https://bugs.llvm.org/show_bug.cgi?id=19052, indeed present in 3.4 and fixed in 3.5.

**Comment by bstaletic** [comment]
Yup, that fixed it.
https://travis-ci.org/bstaletic/ycmd/builds/362630239

Thanks for looking into this.

**Comment by bstaletic** [comment]
For completeness, here's the diff that fixed it:

```diff
diff --git a/cpp/pybind11/pybind11/pybind11.h b/cpp/pybind11/pybind11/pybind11.h
index 977045d6..c685e06c 100644
--- a/cpp/pybind11/pybind11/pybind11.h
+++ b/cpp/pybind11/pybind11/pybind11.h
@@ -1650,6 +1650,7 @@ void register_exception_translator(ExceptionTranslator&& translator) {
 template <typename type>
 class exception : public object {
 public:
+    exception() = default;
     exception(handle scope, const char *name, PyObject *base = PyExc_Exception) {
         std::string full_name = scope.attr("__name__").cast<std::string>() +
                                 std::string(".") + name;
@@ -1666,6 +1667,14 @@ public:
     }
 };

+NAMESPACE_BEGIN(detail)
+template <typename CppException>
+exception<CppException> &get_exception_object() {
+    static exception<CppException> ex;
+    return ex;
+}
+NAMESPACE_END(detail)
+
 /**
  * Registers a Python exception in `m` of the given `name` and installs an exception translator to
  * translate the C++ exception to the created Python exception using the exceptions what() method.
@@ -1676,13 +1685,14 @@ template <typename CppException>
 exception<CppException> &register_exception(handle scope,
                                             const char *name,
                                             PyObject *base = PyExc_Exception) {
-    static exception<CppException> ex(scope, name, base);
+    auto &ex = detail::get_exception_object<CppException>();
+    ex = exception<CppException>(scope, name, base);
     register_exception_translator([](std::exception_ptr p) {
         if (!p) return;
         try {
             std::rethrow_exception(p);
         } catch (const CppException &e) {
-            ex(e.what());
+            detail::get_exception_object<CppException>()(e.what());
         }
     });
     return ex;
```

**Comment by jagerman** [comment]
I cleaned it up a bit for PR #1350; once that passes the CI tests I'll merge.
