### ISSUE TITLE
Better examples for args and kwargs

### ISSUE THREAD

**Issue by ghost** [pybind/pybind11#1357]
I would love to see good examples on how to parse the args and kwargs arguments in the documentation.

Thank you!

**Comment by yeganer** [comment]
Have you had a look at  [tests/test_kwargs_and_defaults.cpp ](https://github.com/pybind/pybind11/blob/master/tests/test_kwargs_and_defaults.cpp)?
`py::args` and `py::kwargs` are essentially just lists and dictionaries. That means you would use them the same way as you would use a list/dictionary.

**Comment by bstaletic** [comment]
No further discussion. Closing.
