### ISSUE TITLE
const char* isn't handled properly

### ISSUE THREAD

**Issue by benEnsta** [pybind/pybind11#137]
Hi, thank you very much for your great work with this library.

Since the version e206564ebf3cc2970181084813fa2bbe227cbfd5, const char* type does not seem to be handled properly.

```c++
#include <iostream>
#include <pybind11/pybind11.h>
namespace py = pybind11;

void print_cchar(const char* msg){
	std::cout << msg << std::endl;
}

PYBIND11_PLUGIN(testChar)
{
  py::module m("testChar");
  m.def("print_cchar", &print_cchar);
  return m.ptr();
}
```
Nothing is displayed with 
```python
> import testChar
> testChar.print_cchar("test")
> 
```

**Comment by wjakob** [comment]
that's an awful regression, thanks for the report.

**Comment by benEnsta** [comment]
As fast as usual, thank you !
