### ISSUE TITLE
How to wrap void functions which take double* 

### ISSUE THREAD

**Issue by fbartolic** [pybind/pybind11#1378]
Hello, I have C++ code with several C-style functions which look like this: 

`void some_function(double* array, int array_size) { do something with array } `

What's the easiest way to  wrap these functions? I thought about casting the Python list/numpy array directly to a an array in C++ allocated with `new double[array_size]` an then calling `some_function` but I'm
not sure how to do that.

**Comment by jagerman** [comment]
The easiest approach is probably to bind an intermediate wrapper taking a `std::vector` and passing its data to the real function:
```C++
#include <pybind11/stl.h>
// ...
    m.def("some_function", [](std::vector<double> array) { return some_function(array.data(), array.size()); });
```

**Comment by fbartolic** [comment]
Thank you so much!
