### ISSUE TITLE
Implicit conversion from Null when inside a vector

### ISSUE THREAD

**Issue by afryt** [pybind/pybind11#1382]
Can't make an implicit conversion from None (py::none or py::object) to my class work.
It is the same issue as https://github.com/pybind/pybind11/issues/642 but I'd like to provide a non-obscure use case.

In the interface I'm writing I'd like to provide a constructor from a Python list. The elements of the list can be double, string and None (ideally). The constructor being exposed is this one: 
`A::A(const vector<B>& l)`
I expose it using
```
py::class_<A> m(module, "A");
m.def(py::init<vector<B>>&>())
```
I'd like to call this using:
```
A([None, 1.0, "string"])
```
I registered implicit conversion from `double` and `string` to `B` and it flies, that is I can create object `A` using `A([1.0, 'string'])`. This works because `B` has implicit conversions:
`B.def(py::init<double>()).def(py::init<std::string>()).def(py::init<>());`
and a list of `py::implicitly_convertible<double, B>()...`. 

Question: How to I add implicit conversion from Python None to use B() when in a list?

**Comment by tboyce021** [comment]
I'm running into this same issue with a map. Did you ever figure out a workaround?

**Comment by afryt** [comment]
No, unfortunately I haven't. If you come up with something please share.

**Comment by bstaletic** [comment]
```c++
b_class.def("__init__" [](py::object o) {
    if (o.is_none()) return B{};
    else throw py::type_error("boom");
});
```

If this doesn't solve it, feel free to reopen the issue.

**Comment by YannickJadoul** [comment]
Or `#include <stl.h>` + `std::optional<...>`.

**Comment by crisluengo** [comment]
Consider the following example code (paraphrased, might have typos):

```cpp
#include "pydip.h"

class A {
public:
   int value = 0;
   A() = default;
   A(int v) : value(v) {};
}

int X(A const&) {
   return A.value;
}

PYBIND11_MODULE(mymodule, m) {
   auto a = py::class_<A>(m, "A");
   a(py::init<>());
   //a(py::init([](py::none const&) { return A{}; }));  // I had tried this one too
   a("__init__", [](py::object const& o) {
      if (o.is_none()) {
         return A{};
      }
      throw py::type_error("boom");
   });
   py::implicitly_convertible<py::none, A>();
   a(py::init<int>());
   py::implicitly_convertible<int, A>();

   m.def("X", X);
}
```

I can now do in Python:
```python
a = A(None)
a = A(1)
X(a)
X(1)
```
But I cannot do
```python
X(None)
```

However, if I edit `pybind11/cast.h`, at the top of `bool load_impl(handle src, bool convert)`, where it says:
```cpp
        if (src.is_none()) {
            // Defer accepting None to other overloads (if we aren't in convert mode):
            if (!convert) return false;
            value = nullptr;
            return true;
        }
```
If I remove the `value = nullptr; return true;` lines, then the above all works correctly.

I have not found any downsides to doing so. This means that the custom converter function gets a `py::none` object as input, it can choose to reject that or accept that. Any conversion function already tests what the type of the input object is, so this should not affect any existing code.

---

In real life, the above example is for an image class where the default-constructed image has no pixels, and is used to signal "I don't need this input" to specific functions.
