### ISSUE TITLE
BSD License issue

### ISSUE THREAD

**Issue by sclarkson** [pybind/pybind11#1386]
Using a BSD style license for a header-only template library is somewhat dubious as it creates a bit of a trap for end-users. In particular, the clause below means that any code shipped that is built using pybind11 must include a copy of the pybind11 license.
https://github.com/pybind/pybind11/blob/f5f66189620b7575f3124c66e3b3c8d0d03caf25/LICENSE#L9-L11

If this is your intent, then please ignore this. However, https://github.com/pybind/pybind11/issues/28 suggests that may not be intentional.

The [zlib License](https://www.zlib.net/zlib_license.html) or the [Boost Software License](https://www.boost.org/LICENSE_1_0.txt) are much more end-user friendly for header-only template libraries, as they do not have the copyright requirement on binary distributions.

(I'm very open to being corrected about my interpretation of the BSD license as it applies to header-only template libraries)

**Comment by jagerman** [comment]
I don't see the interpretation that way; a binary built using pybind isn't a distribution of pybind itself, but merely a dependent project.  The only case I can see that clause really entering is if you wanted to modify pybind and redistribute, say, a compiled version of the test suite.

**Comment by wjakob** [comment]
Hi,

@sclarkson: I do think you interpreted the license text correctly. In many commercial applications without source code, there is some kind of about dialog that has lots of statements of BSD-licensed components for exactly this reason. Our use of this license is intentional, and I would consider it a shame if there was no acknowledgement at all (it's so little to ask for that I don't think it's unreasonable).

Wenzel

**Comment by sclarkson** [comment]
@jagerman It doesn't specify that the binary distribution has to be in whole, and therefore I believe a partial distribution still applies. If that were the case, anyone could pull parts out of open-source projects and put them into proprietary software.

@wjakob Thank you for clarifying. However, this doesn't just apply to commercial projects, but open-source ones as well. If we agree on the interpretation, then distributing a binary release of the open-source project without the pybind11 license is a violation. As such, probably everyone on PyPI who uses pybind11 is in violation of your license.
