### ISSUE TITLE
Permissiveness in converting floating point <-> integers

### ISSUE THREAD

**Issue by bennybp** [pybind/pybind11#139]
Pybind11 seems to perform conversion between floating point and integer types.

    #include <pybind11/pybind11.h>
    #include <iostream>

    void MyFunction(int i) { std::cout << " integer: " << i << "\n"; }
    void MyFunction(double d) { std::cout << " double: " << d << "\n"; }

    PYBIND11_PLUGIN(example) {
        pybind11::module m("example", "pybind example plugin");
        m.def("MyFunction", static_cast<void(*)(int)>(MyFunction));
        m.def("MyFunction", static_cast<void(*)(double)>(MyFunction));
        return m.ptr();
    }

For example, the integer version of MyFunction will truncate a python float, and the double version will expand a python int. When overloaded, the version of MyFunction called is always whichever was exported first.

This comes from cpython helpfully doing the conversion (ie, in `PyLong_AsLong`) rather than checking the type.

I would think floating point -> integer would be disallowed, since it would almost always truncate. The other direction is possibly ok, although there is risk of loss of precision with large integers (and overloads wouldn't work). The checks are pretty easy to insert, but I was curious of your thoughts of what should be allowed and what shouldn't.

**Comment by wjakob** [comment]
Hi,

that's a good point. It is even more complicated since other types can also have a __float__ or __int__ member that performs a conversion.

I think that for such tricky cases, the best workaround is to create a wrapper function that takes a ``pybind11::object`` and then dispatches to the right function based on that. Does that make sense?

**Comment by bennybp** [comment]
Yes, that makes sense. Generally, though, I wasn't sure if you intended for the conversions from float to integers to take place at all unless explicitly cast. I can sort of go either way in that debate.

**Comment by wjakob** [comment]
closing this ticket since there isn't a clear issue to be fixed on the pybind11 side.
