### ISSUE TITLE
Where could I find the docs introducing how to manipulate python dict in c++ ?

### ISSUE THREAD

**Issue by CoinCheung** [pybind/pybind11#1398]
Sorry for disturbing, I find pybind11 very helpful and would like to use it to extend my python program with c++. However, after going through the docs here: http://pybind11.readthedocs.io/en/stable/advanced/cast/index.html
I did not see the instructions nor examples of how could I manipulate python dict or list object in C++. I mean I would like to pass a python list or dict object to a function implementetd by c++, but I do not know how could the c++ program manipulate the passed python objects args. Would you show me the attributes of the args and how to manipulate them?

**Comment by bstaletic** [comment]
It's on this page: https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html

In short, you can either treat them as `std::map`s (stl.h) or have a special type for the python side (stl_bind.h).

**Comment by jagerman** [comment]
A third option: you can bind a function that takes a (C++) `py::list` or `py::dict` argument: those are thin wrappers around the native Python types that provide C++ operators/methods that makes them work very similarly to the Python interface for lists/dicts.  For example:

```C++
m.def("set_x", [](py::dict d) { d["x"] = 1; });
```

Python:
```
d = {"a": 1};
mymod.set_x(d);
# d now contains {"a": 1, "x": 1}
```

If you're just trying to translate a Python code into C++ stl types, either `stl.h` or `stl_bind.h` will perform that conversion for you (which one to use depends on your specific needs).

**Comment by CoinCheung** [comment]
@jagerman Thanks greatly for your instructions. Surely I need to let C++ work as python extensions rather than translate python and C++ code into each other. Therefore, the task of manipulating and accessing the objects or types from one to the other language is important for me. 

I sort of understand the option you provided now. To confirm my understanding, could I access the python containers and objects in C++ freely as I do that in python simply with a prefix ```py::``` ? Or does it only works for the variable fileds but not the methods fields, for example I could find the number of one element in a python list like this:
```
 >>>  li = list(range(9))
 >>> print(li.count(2))
```
could I do that in C++ if I have a ```py::list``` object like this ?
```
  py::list pli;
  pli.count(3);
```

**Comment by bstaletic** [comment]
This will work:

```c++
py::list pli;
pli.attr("count")(3);
```

**Comment by CoinCheung** [comment]
Thanks, how could I create a list with values? for example, in python I could do this: 
```
a = [1,2,3]
```
how could I do it in c++ with pybind11 please?

**Comment by bstaletic** [comment]
You've got two options:
```
py::list a(3); // preallocate 3 "empty" slots - value will be None (py::none)
a[0] = 1;
a[1] = 2;
a[2] = 3;
/* Alternatively */
py::list a;
a.append(1);
a.append(2);
a.append(3);
```

I haven't checked, there might be a `py::list::extend` too. Also `int`s might need to be explicitly passed to `py::int_` constructor.

**Comment by CoinCheung** [comment]
Thanks very much. How could I write `for k, v in dict.items()` in c++ with the great pybind11 please ?

**Comment by vryy** [comment]
Hello

Is is possible to use std::size_t as key of py::dict ? Of all the examples I saw uses only string. In fact, it does not compile with key std::size_t

**Comment by bstaletic** [comment]
>     for k, v in dict.items()

    for(auto&& [k, v] : dict)

> Is it possible to use std::size_t as key of py::dict ? Of all the examples I saw uses only string. In fact, it does not compile with key std::size_t

There's no automatic conversion between `size_t` and `py::int_`. Since `py::dict` is a python type, you need to pass `int_`.
