### ISSUE TITLE
Docs about numpy C++ interface not standard compliant

### ISSUE THREAD

**Issue by HDembinski** [pybind/pybind11#1400]
pybind11 is fantastic and getting better and better. Great work!

## Issue description

I would like to report an issue in the docs of the numpy C++ interface that were a pain to track down, because it produces a compiler error that is not helpful at all and does not point to the correct solution. It would be nice if the docs could be updated.

On the page http://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html
in the section "Direct access", there is an example which calls the templated method `unchecked` on the templated class `array_t`:
```
m.def("sum_3d", [](py::array_t<double> x) {
    auto r = x.unchecked<3>(); // x must have ndim = 3; can be non-writeable
    double sum = 0;
    for (ssize_t i = 0; i < r.shape(0); i++)
        for (ssize_t j = 0; j < r.shape(1); j++)
            for (ssize_t k = 0; k < r.shape(2); k++)
                sum += r(i, j, k);
    return sum;
});
```
This code fails on Apple LLVM version 9.1.0 (clang-902.0.39.1), and apparently it is not standard compliant because the `template` keyword is missing the call to a templated method. See https://stackoverflow.com/questions/610245/where-and-why-do-i-have-to-put-the-template-and-typename-keywords. Because it is not standard compliant, the original code may work on some compilers, but not on others.

The correct example is (and this should be  updated in the docs, please):
```
m.def("sum_3d", [](py::array_t<double> x) {
    auto r = x.template unchecked<3>(); // x must have ndim = 3; can be non-writeable
    double sum = 0;
    for (ssize_t i = 0; i < r.shape(0); i++)
        for (ssize_t j = 0; j < r.shape(1); j++)
            for (ssize_t k = 0; k < r.shape(2); k++)
                sum += r(i, j, k);
    return sum;
});
```

**Comment by bstaletic** [comment]
> it is not standard compliant

The `template` keyword here isn't needed, because `x` is an instance of a complete type that doesn't depend on any template parameters.

See here: https://godbolt.org/z/zrr8zY

> This code fails on Apple LLVM version 9.1.0 (clang-902.0.39.1)

That would be a bug in AppleClang.

@YannickJadoul I'll leave it up to you whether this should be closed. Adding an unnecessary and fairly obscure keyword just to appease AppleClang doesn't seem to be worth the confusion of other users.

**Comment by YannickJadoul** [comment]
Cleaning this up and going over old issues, it's +2 years years later. I'd hope this is fixed in compilers, by now.
If not, and this is still a problem (@HDembinski?) we could of course still change it in the docs, but hopefully it's not necessary anymore?
