### ISSUE TITLE
Lack of virtual destructor causes crashing unit tests on XCode 9.3

### ISSUE THREAD

**Issue by BrunoFiligree** [pybind/pybind11#1401]
We were testing pybind11 to see if we could use it. The first thing we did was build the tests and it crashed with an illegal instruction. This was on...
  - OSX 10.13.4
  - vanilla python 3.6.3
  - clang 9.1.0. (XCode 9.3)

However it passed using clang 9.0.0 (Xcode 9.1) on the same machine.

We spent sometime debugging it and it turns out it's a problem with the unit test "test_virtual_functions".  The crash is in the middle of calling the destructor of the abstract base class `ExampleVirt`. This does does _not_ have a virtual destructor. However, the bindings are provided for a derived class `PyExampleVirt`. When we made `ExampleVirt::~ExampleVirt` virtual the crash went away. 

There is probably some compiler interaction going on with how you are doing the bindings. Either way, having an ABC without a virtual destructor usually causes all sorts of issues, though I'm not sure how that works with how you've implemented bindings.

**Comment by jagerman** [comment]
That definitely looks like a bug in the test suite: it should indeed be virtual.  I've pushed e763f04 to master to fix it.

**Comment by BrunoFiligree** [comment]
Great. Happy to help.
