### ISSUE TITLE
return const reference to a class member variable

### ISSUE THREAD

**Issue by fkloosterman** [pybind/pybind11#141]
I ran into some issues trying to bind a method that returns a const reference to a class member variable. 

With this pybind wrapper:

```C++
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

class B {};

class A {
public:
    A( const B & b ) : b_(b) {}
    
    const B & b() const { return b_; }
    
protected:
    B b_;
};

namespace py = pybind11;

PYBIND11_PLUGIN(test) {

    py::module m("test", "Test");
    
    py::class_<B>(m, "B")
        .def(py::init<>());
    
    py::class_<A>(m, "A")
        .def(py::init<const B&>(), py::arg("b"))
        .def_property_readonly("b", &A::b);
    
    return m.ptr();
    
}
```
the following python test indicates that method b returns the object it is called on, rather than the contained object b:

```python
import test
b = test.B()
a = test.A(b)
print(a.b)
print(a.b==a)
```
prints: `<test.A at 0x7fee3ad55c70>` and `True`

Any ideas why this is happening?

**Comment by wjakob** [comment]
You need
```
        .def_property_readonly(
            "b", py::cpp_function(&A::b, py::return_value_policy::reference_internal));
```

**Comment by wjakob** [comment]
Never mind -- I changed the interface a bit (84ec78feeb47a8e14aae326251757b981dd74c97) so that your original syntax will now also work. This was more confusing than it should have been.
