### ISSUE TITLE
Problems with transitive link dependencies

### ISSUE THREAD

**Issue by bjfar** [pybind/pybind11#1419]
I am having some link problems with pybind11. I am wrapping a small piece of code, which links to a C API shared library that I build with cmake in a separate project. This external library has its own dependencies, which in principle should be found in the INTERFACE_LINK_LIBRARIES property that is filled by FindPackage.

To be explicit, my CMakeLists.txt file looks like this:

```
find_package(ScannerBitCAPI REQUIRED)
get_target_property(LIBS ScannerBitCAPI INTERFACE_LINK_LIBRARIES)
message("Libs: ${LIBS}")

# We will use pybind11 to create the Python extension module
add_subdirectory("${PROJECT_SOURCE_DIR}/lib/pybind11-2.1.1")

# Generate Python module
pybind11_add_module(pyscannerbit "${PROJECT_SOURCE_DIR}/src/pyScannerBit.cpp")
target_link_libraries(pyscannerbit PUBLIC ScannerBitCAPI)
```

Everything builds fine, but when I try to import the python module I get unresolved symbols that indicate that the transitive link dependencies are not propagating properly. For example I get

```
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from sb import Scan, HDF5
  File "/home/farmer/repos/gambit/copy4/contrib/pyscannerbit/sb.py", line 12, in <module>
    import pyscannerbit
ImportError: /home/farmer/repos/gambit/copy4/lib/libUtils.so: undefined symbol: recursive_mkdir
```

where this symbol can be found in the library libmkpath.so:

```
> nm /home/farmer/repos/gambit/copy4/lib/libmkpath.so
 ...CUT...
0000000000000830 T recursive_mkdir
...CUT...
```

which seems to be correctly listed under the LIBS that I extract (just for debugging purposes) from INTERFACE_LINK_LIBRARIES:

```
Libs: /home/farmer/repos/gambit/copy4/contrib/yaml-cpp-0.5.3/libyaml-cpp.a;/home/farmer/repos/gambit/copy4/lib/libPrinters.so;/home/farmer/repos/gambit/copy4/lib/libmkpath.so;/home/farmer/repos/gambit/copy4/lib/libfjcore.so;/home/farmer/repos/gambit/copy4/lib/libLogs.so;/home/farmer/repos/gambit/copy4/lib/libUtils.so;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;/usr/lib/openmpi/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libgsl.so;/usr/lib/x86_64-linux-gnu/libgslcblas.so;/usr/lib/x86_64-linux-gnu/libm.so;/home/farmer/anaconda3/envs/gambit/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/home/farmer/anaconda3/envs/gambit/lib/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
```

Do you have any idea what my problem might be? INTERFACE_LINK_LIBRARIES seems to be filled correctly, so I want to blame pybind11 for not linking them into the final python extension module, but it is of course possible that I have done something stupid or wrong here :). If it helps, I am building and exporting the cmake config info for the other project using the method described here: https://stackoverflow.com/questions/33462209/making-cmake-library-accessible-by-other-cmake-packages-automatically/33568871#33568871.

**Comment by bjfar** [comment]
Hmm, it seems that I can solve it by pre-loading these libraries with the LD_PRELOAD environment variable. Which I guess makes sense. So maybe this is more a problem of the LD_LIBRARY_PATH or rpaths or something.

**Comment by loriab** [comment]
`ldd -v pyscannerbit.so` to see if the symbol-containing lib is actually linked and looking at the `link.txt` file w/i the cmake build dir may help diagnosis.

**Comment by bstaletic** [comment]
If the cmake generator is "Unix Makefiles" then one can pass `VERBOSE=1` as a `make` argument and have it output the command it is executing.

**Comment by loriab** [comment]
Your analysis seems sound, but cmake can do funny things. (1) any chance libmkpath is specified before the symbols that need it? (2) you could try linking pb11 as and ordinary lib `target_link_libraries(yourlib PUBLIC pybind11::module)`, rather than the `pybind11_add_module`. (3) play with lib order in `link.txt` (overwritten every time cmake configuration runs) until it works, then try to convince cmake to generate that `link.txt`.

**Comment by cecabert** [comment]
@bjfar Did you managed to make it work ? 
I have similar use case with the same issue. I managed to link with my external shared library by adding `-Wl, --no-as-needed <MyLib> -Wl,--as-needed` to the `target_link_libraries(...)` command. With that all the required libraries are showing up in the output of `ldd MyLib.so`.
Unfortunately even with proper linking, when importing the module I still got `undefined symbol XXX`

**Comment by bjfar** [comment]
Nope, never solved this. I'm not even sure I have understood how to correctly export my shared library with cmake. This whole process is very complicated and poorly documented (I mean the cmake stuff moreso than pybind11).

**Comment by YannickJadoul** [comment]
@henryiii, do you have any insight into this? Or should we just assume that the new CMake system is better and that newer versions of CMake should work, and close this?

**Comment by henryiii** [comment]
I think this is an order issue, and it's not really CMake or pybind11 related - if you list your sources in the wrong order, you can get issues with linking. The solution would be to reorder, or to make multiple targets and explicitly specify the dependencies.

Please reopen if there's still something we can help with (or if you have a specific problem that we can help debug).
