### ISSUE TITLE
equivalent of boost::python::iterator?

### ISSUE THREAD

**Issue by rhl-** [pybind/pybind11#142]
Is there one? I can't find it in the documentation or examples...

**Comment by wjakob** [comment]
There isn't at the moment. A PR which implements this feature would be welcomed.

**Comment by rhl-** [comment]
Hi, this was somewhat unfortunate. I actually went to boost.python because they have this object. Then, I was amazed at how difficult it is to pass python objects to C++ objects in boost.python. pybind11 has made this *much* simpler. 

I have now switched my little project back to pybind11. I appreciate this much more. I have taken a look at the code for boost::python::iterator, it is certainly nontrivial. 

Well I enjoy writing templated c++, I simply don't know enough to be able to produce such a feature at this time. Having it however, would allow me, it seems, to write bindings for most of my library.

**Comment by wjakob** [comment]
It's not a priority for me, and I don't currently have cycles to work on this. I marked the issue with "help wanted".
