### ISSUE TITLE
Accessing a  map ( a member variable in a C++ class) as a dictionary in  Python using def_readonly

### ISSUE THREAD

**Issue by ishan193** [pybind/pybind11#1420]
Hi,
I want to access the map in which I am storing a big tensor of dynamic size mostly (10000x3x10) as a dictionary in python. For that I created a class and use the read_only property to access the map. But this is making the data loading very slow because it is copying the whole data to perform this STL conversion.
Can you suggest some ideas to access this map just by reference and avoid copying?

**Comment by bstaletic** [comment]
No further discussion, so I'll assume that `stl_bind.h`/`py::bind_map` was the answer.
