### ISSUE TITLE
Odd Conversion Error from 'unsigned __int64' to 'unsigned __int64 *'

### ISSUE THREAD

**Issue by phil-zxx** [pybind/pybind11#1422]
Let me outline all the steps I've taken:
1. Downloaded https://github.com/pybind/pybind11/archive/v2.2.3.zip and 
extracted it to C:\pybind11-2.2.3\

2. As per http://pybind11.readthedocs.io/en/latest/basics.html#windows I create a folder **build**, i.e. **C:\pybind11-2.2.3\build** and then run **cmake -A x64 ..** in there (since my Python is 64 bit).
![image](https://user-images.githubusercontent.com/32247590/41042824-83053f5e-699a-11e8-949e-9b07ce381e4b.png)
![image](https://user-images.githubusercontent.com/32247590/41042877-a234df1a-699a-11e8-93e4-3d35bcb07eb2.png)

3. Now I run **cmake --build . --config Release --target check** but get a lot of conversion errors:
`vector(2326): error C2446: '<': no conversion from 'unsigned __int64' to 'unsigned __int64 *'`
Here a screenshot
![image](https://user-images.githubusercontent.com/32247590/41043028-ec001dda-699a-11e8-8645-74af1585e31a.png)
Similarly, when building from the VS solution **pybind11.sln** directly:
![image](https://user-images.githubusercontent.com/32247590/41043335-a5340668-699b-11e8-8598-0dc157c0cb2c.png)

---

I am using **cmake** as per https://cmake.org/files/v3.11/cmake-3.11.3-win64-x64.zip
and **Visual Studio 2017 Professional**. I've searched stackexchange & google for this sort of error but cannot find anything. Has anybody an idea what the root cause of this is? Am I missing any packages/libraries or else (like specific build parameters)?

**Comment by YannickJadoul** [comment]
This issue is 2 years old, pybind11 is now at v2.5.0, the `vector<bool>` code seems to still be there in the tests, and I don't know of any current build issues on the CI services.

Is this still an issue? If so, please reopen.
