### ISSUE TITLE
Cannot import embedded module

### ISSUE THREAD

**Issue by TheGreatMonkey** [pybind/pybind11#1433]
I'm working on a c++ project that will be using python for script execution.

I've created a function and a binding using PYBIND11_EMBEDDED_MODULE.

for the sake of an example lets say I've used the sample:
int add(int i, int j) {
	return i + j;
}
PYBIND11_EMBEDDED_MODULE(fast_calc, m) {
    // `m` is a `py::module` which is used to bind functions and classes
    m.def("add", [](int i, int j) {
        return i + j;
    });
}

I then try to call the function:

py::exec(R"(
    Import fast_calc
    fast_calc.add(1,2)
)");

the call fails at "Import fast_calc" with an error: "Unhandled exception at <memory location> in <application> Microsoft C++ exception: pybind11::error_alread_set at memory location <another memory location>

NOTE that the above binding works if I call it using c++ calls like:
py::module fast_calc = py::module::import("fast_calc");
py::object result = fast_calc.attr("add")(1, 2);
int n = result.cast<int>();

**Comment by TheGreatMonkey** [comment]
Somehow I retyped the bindings and they started working.

**Comment by k12Sergey** [comment]
Hi! I've got absolutely the same problem. How did you do that? I possibly try everything i can imagine.
