### ISSUE TITLE
pickling of pybind11 wrapped c++ objects ...

### ISSUE THREAD

**Issue by jkhoogland** [pybind/pybind11#144]
Hi

I could not find anything related pickling of pybind11 wrapped objects in python.
From looking at [boost.python](http://www.boost.org/doc/libs/1_60_0/libs/python/doc/html/reference/topics/pickle_support.html) it is possible.

Have you given it any thought yet ? 
Thanks
Jiri

**Comment by wjakob** [comment]
Pickling is not part of pybind11 at the moment. PRs that implement this feature (especially very compact ones :)) are welcomed.
