### ISSUE TITLE
pybind11 uses deprecated PyThread_set_key_value API

### ISSUE THREAD

**Issue by jbarlow83** [pybind/pybind11#1444]
## Issue description

As of Python 3.7, the PyThread_* API was deprecated and superceded by the Thread Specific Storage API.

Details from Python documentation:
* https://docs.python.org/3/c-api/init.html#thread-specific-storage-tss-api
* https://www.python.org/dev/peps/pep-0539/

Compiling against Python 3.7 will produce numerous deprecation warnings for every file that includes pybind11 headers. Despite this, everything seems to be working okay. 

To suppress the warnings, pybind11 should select the new API on Python 3.7.

**Comment by jbarlow83** [comment]
Closed by #1454

**Comment by jonatanolofsson** [comment]
Could we get a new release with this in?
