### ISSUE TITLE
No transpose option for Eigen arguments/return values

### ISSUE THREAD

**Issue by woodychow** [pybind/pybind11#1445]
Background:
To store a block of vertices, it is usual to use a Nx3 matrix in row major in numpy and a 3xN matrix in column major in C++ (Eigen). These 2 matrices are the same thing in memory, but pybind11 will automatically transpose in memory my Nx3 row major matrix in numpy to a Nx3 column matrix. I would like to keep my vertices in column major in C++

One way to implement this no transpose option for return value is to add additional enum value to `return_value_policy`. However, since `return_value_policy` values are not flags, if I am not mistaken, a `_notranspose` version for each enum is need.

For arguments, I can just add a notranspose option to `arg`

My questions are
* Am I missing something? Is there an easy way to do this?
* If no, would such a contribution be welcomed? I need this for my project, so I think I will implement this anyways.

**Comment by jagerman** [comment]
The simplest way to do this is probably to wrap code via a numpy transpose (which returns a view that simply references the original array's data with swapped strides/dimensions).  E.g. when returning from C++:

```C++
m.def("returns_matrix", []() {
    auto ret = py::cast(returns_matrix(), return_value_policy::move);
    return ret.attr("transpose")();
});
```

and, when going the other way:

```C++
using MyMatrixType = Eigen::Matrix<double, 3, Eigen::Dynamic>;
m.def("takes_matrix", [](py::array a) {
    takes_matrix(py::cast<MyMatrixType>(a.attr("transpose")());
});
```

(Assuming the `takes_matrix` function here takes an `Eigen::Ref` this would also avoid copying the data.)

**Comment by woodychow** [comment]
Thank you very much. I already hacked pybind11 to do this, but using numpy transpose is much easier and cleaner!

**Comment by bonfus** [comment]
@woodychow do you still have your implementation of the No transpose option?
I have a similar case as the one you describe and adding all those transpose operations adds a lot of code bloat.
