### ISSUE TITLE
Implicit cast of struct to dict

### ISSUE THREAD

**Issue by molpopgen** [pybind/pybind11#145]
Hi,

First--apologies if this is the wrong place to post a query.  I couldn't find a mailing list related to this project.

I'd like to be able to have C++ structs automatically cast to dictionaries in Python.  This is one of the "killer features" of Cython, IMO.

I've been messing around with trying to create a "foo_caster" struct, modeled after the objects in pbyind11/stl.h, with a manual "cast" function written for type foo, and a call to PYBIND11_TYPE_CASTER finishing up the object.

While my attempts compile, nothing of use is happening at run-time.

Is what I'm trying to accomplish possible?  If so, could we get an example program or a hint added to the documentation?

Thanks.

**Comment by wjakob** [comment]
Doing this automatically is not going to be possible because C++ type reflection is not yet part of the standard. You could, however, implement casters for *specific* data structures that occur in your codebase. Yo'll have to look at the other casters in ``cast.h`` -- this is kind of beyond the scope of this library, so you're own your own if you choose to do that.

**Comment by molpopgen** [comment]
I've been looking at those examples, and it is not clear what the minimum requirements are.  For example, the caster for std::string calls PYBIND11_TYPE_CASTER at the end, others do not.  Likewise, calls to name() are in some casters but not others, etc.

 Basically, it seems much easier to add an as_dict() function to the various types in the modules, and leave the conversion up to the user at run-time.

**Comment by brandonmpetty** [comment]
I am interested in this too.  Has anything changed in 5 years?

**Comment by YannickJadoul** [comment]
@brandonmpetty, unless you know something we don't and can query the members of a struct in C++ (without C++23/C++26 reflection), then I don't see what would have changed. (Also, this is reviving a 5 years old thread; asking on Gitter would have been easier/better/less necromancy.)

**Comment by brandonmpetty** [comment]
@YannickJadoul, apologies for the necromancy.  I was specifically wondering if you were able to work around the need for reflection.  For example, when I create an Enum I have to spell out every detail... so obviously no reflection is at play there.  I was wondering if something like that had been added yet for exposing specific structs as dicts.

I am very new to Python and Pybind, so you'll have to forgive me for being over zealous.  I am droping the idea of having Pybind do it all for me and am creating a thin shim layer for better exposing my library.  From what I have been reading, I may have to do that for performance reasons as it does a lot of array manipulation.

Thank you, and sorry for the interruption.  But something to thinking about... don't lock yourself into thinking reflection is the only way to solve this problem.

**Comment by YannickJadoul** [comment]
Ah, like that. The closest that's built-in, is a direct mapping between a C++ and Python type, and using `def_readwrite`, as demonstrated in the docs.

To map to a dict, no, there isn't. It's something you could do yourself, though, using `py::cast`, etc.
