### ISSUE TITLE
Defining enum with mutiple identical values should cause an error

### ISSUE THREAD

**Issue by cysiek** [pybind/pybind11#1451]
It's quite easy to make the following mistake:

```
enum SimpleEnum
    {
        ONE, TWO, THREE
    };

    PYBIND11_MODULE(MyPythonModule, module)
    {
        py::enum_<SimpleEnum>(module, "SimpleEnum")
        .value("ONE", SimpleEnum::ONE)          //NOTE: all value function calls are called with the same first parameter value
        .value("ONE", SimpleEnum::TWO)
        .value("ONE", SimpleEnum::THREE)
        .export_values();
}
```

This code compiles fine without any error/warning. When the module is loaded in Python, you can access only first value of SimpleEnum - "ONE". Would it be possible to make this code throw an error or at least warning at compile time (or eventually during loading python module) ?

Other information:
Pybind version: 2.2.3, Win 10 x64, Visual Studio 2015 x64, Python: Anaconda Python 3.6.5

**Comment by jagerman** [comment]
Should be a simple enough check if you want to submit a PR (and turn your original post into a test case):
```C++
    pybind11::str pyname(name);
    if (m_entries.contains(pyname))
        throw value_error("...");
    // ... (current code)
```

**Comment by cysiek** [comment]
I've created a pull request - https://github.com/pybind/pybind11/pull/1453
Please note that it's my first PR to open source project, so some "obvious" things might be wrong ;) Feel free to give me any feedback.

**Comment by cysiek** [comment]
I've fixed formatting issues, but still travis fails for XCode 9 C++ ( [https://travis-ci.org/pybind/pybind11/builds/404210394](url) ). For me it looks a bit like configuration issue, @jagerman @bstaletic could you have a look at it?

**Comment by bstaletic** [comment]
PR merged. Closing.
