### ISSUE TITLE
set_property can not be used on an ALIAS target

### ISSUE THREAD

**Issue by live-lively** [pybind/pybind11#1456]
when I compile open3d using pybind as dependence in ubuntu16.04LTS, it occurs:
--------------------------------------------------------------------------------------------------------
CMake Error at /usr/local/share/cmake/pybind11/pybind11Targets.cmake:50 (set_target_properties):
   set_target_properties can not be used on an ALIAS target.
 Call Stack (most recent call first):
   /usr/local/share/cmake/pybind11/pybind11Config.cmake:108 (include)
   External/CMakeLists.txt:3 (find_package)

 CMake Error at /usr/local/share/cmake/pybind11/pybind11Targets.cmake:57 (set_target_properties):
   set_target_properties can not be used on an ALIAS target.
 Call Stack (most recent call first):
   /usr/local/share/cmake/pybind11/pybind11Config.cmake:108 (include)
   External/CMakeLists.txt:3 (find_package)

 CMake Error at /usr/local/share/cmake/pybind11/pybind11Targets.cmake:65 (set_target_properties):
   set_target_properties can not be used on an ALIAS target.
 Call Stack (most recent call first):
   /usr/local/share/cmake/pybind11/pybind11Config.cmake:108 (include)
   External/CMakeLists.txt:3 (find_package)

 CMake Error at /usr/local/share/cmake/pybind11/pybind11Config.cmake:111 (set_property):
   set_property can not be used on an ALIAS target.
 Call Stack (most recent call first):
   External/CMakeLists.txt:3 (find_package)

**Comment by sromberg** [comment]
Same when compiling open3d with pybind on macOS 10.14. Does anyone have an idea how to solve that?

**Comment by shoKagami** [comment]
I also faced this bug. But it was fixed by comment out the 3rd line of Open3D/src/External/CMakeList.txt.
as https://github.com/IntelVCL/Open3D/issues/420#issuecomment-401233737 .

**Comment by henryiii** [comment]
Looks like it was fixed upstream. If it does persist, #2370 would likely fix it as well.
