### ISSUE TITLE
Differences between declaring property and function?

### ISSUE THREAD

**Issue by wolfv** [pybind/pybind11#146]
Declaring a custom iterator function as property doesn't work (ie. I am getting a segmentation fault). 

Not sure if this is intended or not. However, as function it works perfect.

        .def_property_readonly("test", [](py::object s) { 
            return PySequenceIterator<Polygon_2::Edge_const_iterator>(
                s.cast<const Polygon_2 &>().edges_begin(), 
                s.cast<const Polygon_2 &>().edges_end(), 
            s);
        })
        .def("edges", [](py::object s) { 
            return PySequenceIterator<Polygon_2::Edge_const_iterator>(
                s.cast<const Polygon_2 &>().edges_begin(), 
                s.cast<const Polygon_2 &>().edges_end(), 
            s);
        })

**Comment by wjakob** [comment]
Thanks for your report — unfortunately, it is not in a form that convenient for me. I’m a researcher at a university and just support this project in my free time, hence resources are very limited. If you’d like me to take a look at this issue, please submit a self-contained and minimal piece of code that reproduces the problem (in other words: no external dependencies, isolate the function(s) that cause breakage, submit matched C++ and Python snippets).

**Comment by wolfv** [comment]
Hi, sorry. The code below is hopefully better.

```
typedef std::vector<int> vint;

class A {
public:
    vint a = {1,2,3,4,5,6,7};
    vint::iterator a_begin() {
        return a.begin();
    }
    vint::iterator a_end() {
        return a.end();
    }
};

namespace {
    // Special iterator data structure for python
    template <typename T>
    struct PySequenceIterator {
        PySequenceIterator(const T & begin, const T & end, py::object ref) : begin(begin), end(end), ref(ref) {}
        py::object next() {
            if (begin == end)
                throw py::stop_iteration();
            return py::cast(*(begin++));
        }

        int len() {
            return std::distance(begin, end);
        }

        py::object getitem(int i) {
            return py::cast(begin[i]);
        }

        T begin;
        T end;
        py::object ref; // keep a reference
        size_t index = 0;
    };
};

void init_test(py::module &m) {
    py::module sub = m.def_submodule("isolatedtest", "isolatedtest");
    py::class_<A>(sub, "A")
        .def(py::init<>())
        .def("ints", [](py::object s) { 
            return PySequenceIterator<vint::iterator>(
                s.cast<A &>().a_begin(),
                s.cast<A &>().a_end(), 
                s); 
        })
        .def_property_readonly("ints_property", [](py::object s) { 
            return PySequenceIterator<vint::iterator>(
                s.cast<A &>().a_begin(),
                s.cast<A &>().a_end(), 
                s); 
        })
    ;

    typedef PySequenceIterator<vint::iterator> PyIntIterator;

    py::class_<PyIntIterator>(sub, "IntIterator")
        .def("__iter__", [](PyIntIterator &it) -> PyIntIterator& { return it; })
        .def("__len__", &PyIntIterator::len)
        .def("__next__", &PyIntIterator::next);
}
```

**Comment by wjakob** [comment]
Ok, getting a better idea now. Does it work if you specify a py::return_value_policy::copy at the end of your def_property_readonly declaration? Note that this will require a current version of pybind11.

**Comment by wolfv** [comment]
yes! cool! thanks a lot.

**Comment by wjakob** [comment]
I changed the default parameters for properties so that your original example would also have worked. (see the latest commit)
