### ISSUE TITLE
unsigned char * (array) bounded as an unsigned char

### ISSUE THREAD

**Issue by ofirDubi** [pybind/pybind11#1460]
Hi, 

Im trying to expend the a cpp function that receives an unsigned char pointer (which i will use as an array) as an argument:
```c
 void igl::opengl::glfw::test_pybind(const unsigned char * in_data){
	printf("got the data: %p", in_data);
}
```
 When i bind the function and call it from python using a list:
```python 
igl.glfw.test_pybind([1,2,3])
```
I get the following error:
```
TypeError: test_pybind(): incompatible function arguments. The following argument types are supported:
    1. (in_data: int) -> bool
```
I also noticed that if i call the function with  a number between 0 and 255 (the values of an unsigned char) the function executes. When i use a larger/negative number, the code fails with the same error as above. This brought me to the conclusion that the function is expecting an unsigned char for some reason.

My binding code is:

```python

void python_export_igl_glfw(py::module &m)
{

  py::module me = m.def_submodule(
    "glfw", "GLFW Mesh viewer");

me.def("test_pybind", []
(
const unsigned char * in_data
){
return igl::opengl::glfw::test_pybind(in_data);
}, __doc_igl_opengl_glfw_test_pybind,
py::arg("in_data"));

}
```

**Comment by jagerman** [comment]
It's an explicit design choice not to support C-style pointers-are-arrays semantics because there is really no way for pybind to know whether a pointer argument is just a pointer or a C-style array.  To work around it you'll need an intermediate step such as going through a `std::vector`:

```
m.def("f", [](std::vector<unsigned char> in) {
    return func_expecting_char_ptr(in.data());
});
```
(you may also want a `in.push_back(0)` before the call if the function expects 0-terminated data).

**Comment by ofirDubi** [comment]
Hmm, I get your point.
 My workaround was wrapping the function with another function that receives `std::string` as a parameter. Then I converted it to unsigned char * array and passed it to my original function.
But your solution is nicer :p
