### ISSUE TITLE
unchecked_mutable_reference element access methods should be const

### ISSUE THREAD

**Issue by MoritzMaxeiner** [pybind/pybind11#1468]
## Issue description

The methods provided by `unchecked_mutable_reference` are not marked as `const`:
https://github.com/pybind/pybind11/blob/5ef1af138dc3ef94c05274ae554e70d64cd589bf/include/pybind11/numpy.h#L389
https://github.com/pybind/pybind11/blob/5ef1af138dc3ef94c05274ae554e70d64cd589bf/include/pybind11/numpy.h#L400
https://github.com/pybind/pybind11/blob/5ef1af138dc3ef94c05274ae554e70d64cd589bf/include/pybind11/numpy.h#L403
As `const`-ness is not transitive in C++, these three should all be marked as `const` (while they allow modifying the returned data, they themselved do not mutate the `unchecked_mutable_reference` object).

## Reproducible example code

```
#include <iostream>
#include <pybind11/numpy.h>

void foo(pybind11::detail::unchecked_mutable_reference<float, 1> const& x)
{
    // Assuming x has at least one element for brevity
    std::cout << x[0] << std::endl;
}
```

will fail to compile (even though it should) because `x` been passed as a constant reference (which is a common use case to avoid copies).

## Corrective action

Change the methods quoted above to:

`template <typename... Ix> T& operator()(Ix... index) const {`

`T &operator[](ssize_t index) const { return operator()(index); } `

`template <typename... Ix> T *mutable_data(Ix... ix) const { return &operator()(ssize_t(ix)...); }`

**Comment by bstaletic** [comment]
While these member functions don't directly mutate the buffer, but in C++11 and newer, `const` implies thread safe in the most literal sense of the word. On top of that `vector::operator[](size_t) const` returns a `const_reference`, not `reference`.

Those two seem like two good reasons why these member functions should not be `const` even if they don't directly mutate `*this`.

**Comment by MoritzMaxeiner** [comment]
>  but in C++11 and newer, `const` implies thread safe in the most literal sense of the word

That's only true for the C++ standard library, not for C++ in general, AFAIU. Regardless, providing member access would not (by itself) introduce a data race, so I'm not sure I understand your argument here.

> On top of that vector::operator[](size_t) const returns a const_reference, not reference.

If you want to follow the C++ standard library here, then the corrective action would change to providing three additional methods marked as const with the return types also marked as const:

```
template <typename... Ix> T const& operator()(Ix... index) const {

T const& operator[](ssize_t index) const { return operator()(index); }

template <typename... Ix> T const* mutable_data(Ix... ix) const { return &operator()(ssize_t(ix)...); }
```

**Comment by bstaletic** [comment]
> That's only true for the C++ standard library, not for C++ in general, AFAIU.

Actually, it's part of the core language.

> Regardless, providing member access would not (by itself) introduce a data race, so I'm not sure I understand your argument here.

I'm saying that if those were `const` then you would be well within you contract to take `unchecked_mutable_reference`, "spread" it across threads, write through the pointer and not expect data races. That's not what we can promise here.

> If you want to follow the C++ standard library here, then the corrective action would change to providing three additional methods marked as const with the return types also marked as const:

I've considered that, but `pybind11/numpy.h` also has `unchecked_reference`, which seems to serve that purpose.

> passed as a constant reference

Right. These reference proxy types are too big to be passed by value. I have two questions.

1. If you're passing `unchecked_mutable_reference`, why not pass it by non-const reference?
2. If you don't need mutability, as `const&` would imply, why not pass around `unchecked_reference`?

**Comment by MoritzMaxeiner** [comment]
> Actually, it's part of the core language.

Please reference the location in the C++ standard for this claim.

> I'm saying that if those were const then you would be well within you contract to take unchecked_mutable_reference, "spread" it across threads, write through the pointer and not expect data races. That's not what we can promise here.

Since `const` is not transitive in C++, you could indeed share a `const unchecked_mutable_reference` between threads and mutate what it references. But you can also, at present, share a non-const `unchecked_mutable_reference` between threads and mutate what it references. It's not necessary to promise a transitive property `const` inherently doesn't have, imho.

> I've considered that, but pybind11/numpy.h also has unchecked_reference, which seems to serve that purpose.

It's quite normal to get an `unchecked_mutable_reference` in your python binding code once and then pass it on the template code that you're also calling from non-python-binding code, so if you're arguing to follow the C++ standard library design paradigm w.r.t. const, applying it consistently would allow simplifying API consumers.


>     1. If you're passing `unchecked_mutable_reference`, why not pass it by non-const reference?

The same reason I wouldn't pass a non-const reference of `std::vector` from (templated) code that needs to mutate the content into other (templated) code that doesn't: const correctness:

```
#include <vector>

template<typename R>
void inspect_range(R const& r)
{
    // This mutation will cause compilation failure
    if (std::size(r) == 2) {
        std::swap(r[0], r[std::size(r) - 1]);
    }
}

template<typename R>
void transform_range(R&& r)
{
    inspect_range(r);
    // Just an example for content mutation
    if (std::size(r) == 2) {
        std::swap(r[0], r[std::size(r) - 1]);
    }
}

int main(int argc, char** argv)
{
    std::vector<int> v;
    transform_range(v);
}
```

> If you don't need mutability, as const& would imply, why not pass around unchecked_reference?

In my case it's correct I don't need it, but since const isn't transitive, that's not implied. The ability to mutate a reference itself has no relation to the ability to mutate its contents (purely from a language standpoint), though. Anyway, the reason I don't want to pass around an `unchecked_reference` is shown by the above code example. I cannot pass an unchecked reference into `transform_range`, since I *do* need to mutate the content there, but I don't want to pass that mutability on to `inspect_range` to get compilation const correctness guarantees.

**Comment by bstaletic** [comment]
> > Actually, it's part of the core language.
> 
> Please reference the location in the C++ standard for this claim.

https://stackoverflow.com/questions/14127379/does-const-mean-thread-safe-in-c11/14127380#14127380

That SO references the standard.


>     template<typename R>
>     void inspect_range(R const& r)
>     {
>         // This mutation will cause compilation failure
>         if (std::size(r) == 2) {
>             std::swap(r[0], r[std::size(r) - 1]);
>         }
>     }


Now I'm really confused. When you take `R const&` and try to mutate it, isn't it just like doing the following:

```c++
int i = 4;
int const& r = i;
r += 3;
```

The above also fails to compile.

**Comment by bstaletic** [comment]
Moreover, that `inspect_range` fails to compile for any sequence container in the standard library too.

https://godbolt.org/z/Y4KMW8

**Comment by MoritzMaxeiner** [comment]
> That SO references the standard.

That SO (as well as the referenced parts of the C++ standard) *explicitly* states that *only* the *Standard Library* expects `const` objects to be threads safe. It *does not* make any claim as to `const` meaning thread safe in the *Standard Language*, which is what you've been claiming. Please provide a reference for *the latter*.

> Now I'm really confused.

Why? It is *supposed* to fail to compile, that is the guarantee of *const correctness* and the purpose of the example: Demonstrate *why* I want mutable access to an object in templated function A (`transform_range`), that calls a templated function B (`inspect_range`) with the latter having only `const` access. **To ensure the compiler enforces *const correctness* in function B.**

The real world scenario would be more like this:

```
#include <vector>
#include <utility>
#include <iostream>

template<typename R>
void inspect_range(R const& r)
{
    // I'm aware that I could also use `for (decltype(auto) x : r) {`, but that would impose
    // either the requirement that R provides `begin` and `end` members, or that `std::begin` and `std::end`
    // have been specialized for R.
    for (std::size_t i = 0; i < std::size(r); ++i) {
        // Imagine a check here that tests whether r[i]
        // is a valid value (by some defintion of valid).
        std::cerr << r[i] << std::endl;
    }
}

template<typename R>
void transform_range(R&& r)
{
    inspect_range(std::forward<R>(r));
    if (std::size(r) == 2) {
        std::swap(r[0], r[std::size(r) - 1]);
    }
}

int main(int argc, char** argv)
{
        std::vector<int> v;
        transform_range(v);
}
```

This compiles fine with std::vector (and I would assume any other containers/ranges in std::, but I haven't tested them all), but *it's going to fail to compile in `inspect_range` with `unchecked_mutable_reference`, because `unchecked_mutable_reference` does not have the appropriate `const` operator(s).

**Comment by MoritzMaxeiner** [comment]
If it helps, imagine `transform_range` receiving *untrusted user input* from the network as a request in `r` (with potentially malicious data injected), and - for performance reasons - it's supposed to reuse that same memory for its response if feasible (maybe `r` has been preallocated to some sufficient size similar to `std::vector::reserve`).

However, before you allow that request to be processed further and have the response written back into `r` (still in `transform_range`), you *need* to first validate the request, to ensure it *doesn't* contain malicious data. That's what you then call `inspect_range` for, which might throw an exception (or instead of `void` return `bool` to indicate validation status) if the input data is invalid; and since `inspect_range` *never* needs write access to `r`, it *should* only get `const` access to it.

**Comment by YannickJadoul** [comment]
@MoritzMaxeiner, I've been discussing this yesterday evening and today with @bstaletic. I do think the first reaction was a bit too fast; personally, I think I was too quick and overlooked that these were methods on `unchecked_mutable_reference` and not on `array`. Sorry for that, and dismissing the issue too soon (we're trying to clean up some issues and get the number down, so that's how ;-) ).

But anyway, on topic, two things:

1. The more I think about it, the more the fact that `unchecked_mutable_reference` doesn't have `const T &operator[](ssize_t index) const` seems wrong indeed. `unchecked_reference` does, and it's the base class (so given a `const unchecked_mutable_reference &r`, `const unchecked_reference& s = r;` would suddenly allow to call these methods).
The issue seems to be a lack of `using ConstBase::operator[]`; the solution to add such a line, in order to add these to the overload resolution?

2. `const T &operator[](ssize_t index)` is still a different matter. I understand where this is coming from (e.g., `T * const` also allows to change the actual object pointed to). We've been looking for a few examples, but these seem inconclusive as well:
    -  The proxy object in a `vector<bool>` doesn't allow assigning to a `const &` proxy: https://godbolt.org/z/Korqc1
    -  `std::iterator` and `std::span` do allow to assign to a `const &` to a non-const version of the class: https://godbolt.org/z/j76q1a & https://godbolt.org/z/vKxshj

    So the question is: how close to a pointer or `std::span` would/should the semantics of `unchecked_reference` and `unchecked_mutable_reference` be? I've got some sympathy to your suggestion, but I'm not entirely convinced yet.

**Comment by bstaletic** [comment]
Okat, let's reopen this. From where I stand, `const T& operator[](ssize_t) const` (and friends) makes sense and was probably an oversight. However, I don't think `T& operator[](ssize_t) const` is a good idea.

**Comment by MoritzMaxeiner** [comment]
> Sorry for that, and dismissing the issue too soon (we're trying to clean up some issues and get the number down, so that's how ;-) ).

No problem :)

>     1. The issue seems to be a lack of `using ConstBase::operator[]`; the solution to add such a line, in order to add these to the overload resolution?

Yes, adding these two lines as `public` in `unchecked_mutable_reference` solves the issue for me:

```
    using ConstBase::operator();
    using ConstBase::operator[];
```

I've taken a look again at the `mutable_data` member function and I retract my statement regarding that one, since I don't think it makes sense to have a method named mutable return something const, so please disregard my earlier statements regarding this one.



>     2. So the question is: how close to a pointer or `std::span` would/should the semantics of `unchecked_reference` and `unchecked_mutable_reference` be?

The only difference here that I can see would be that `std::vector` *owns* the referenced data, while neither `std::iterator` and `std::span` do (the same way a pointer or a reference don't own the referenced data); `unchecked_mutable_reference` doesn't own the data, either, afaiu.

Personally, I'm happy with only the above two `using` lines being added as that covers all my use cases. If that's done, I have no need for `T &operator[](ssize_t index) const`.

From a policy point of view I would think "const objects (or references/pointers to them) shall not allow mutation of data they own" (but allow mutation of data they don't own - provided the references/pointers to said data lack `const` attribution) to be a sensible one. Applied to `unchecked_mutable_reference`, that would mean adding `T &operator[](ssize_t index) const` and `template <typename... Ix> T& operator()(Ix... index) const`.

Whatever policy you decide on is not as important as documenting it and then applying it consistently, though (so API consumers know what to expect).

**Comment by YannickJadoul** [comment]
@henryiii, any thoughts?

**Comment by YannickJadoul** [comment]
PR in #2514
