### ISSUE TITLE
variadic templates and parameter forwarding in factory method

### ISSUE THREAD

**Issue by wanchaol** [pybind/pybind11#1469]
Say that I want to use variadic templates and parameter forwarding in factory method

```c++
class service {
private:
    service() = default;
    service( const service & o ) = default;
    service( std::vector<config_setting> c );
public:
    template<typename ... T>
    static shared_ptr<service> create( T&& ... all ) {
        return shared_ptr<service>( new service( std::forward<T>(all)... ) );
    }
```

How could I bind the constructor to the factory method?

I am doing something like:
```c++
py::class_<service, std::shared_ptr<service>>(m, "service")
.def(py::init(&service:create));
```

But it seems that I could not succesfully compile with error:

```
 cannot convert ‘& service::create’ (type ‘<unresolved overloaded function type>’) to type ‘std::vector<config_setting >&&’
```

Does anyone know how we could support case like this?

**Comment by GreyDireWolf** [comment]
+1. I'm dealing with same issue but as far as I understand pybind11 doesn't support templates(you need to make wrapper for each type)

**Comment by hjzh4** [comment]
+1.

**Comment by YannickJadoul** [comment]
> +1. I'm dealing with same issue but as far as I understand pybind11 doesn't support templates(you need to make wrapper for each type)

What @glitzflitz said. A function/method template is not yet a function/method. pybind11 (actually just C++) needs concrete types to know which C++ code needs to be generated, and how to convert them from Python. Can't fix.
