### ISSUE TITLE
Binding for template class with copy-like constructor

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#147]
Hi, i noticed that attempt to bind a templated class that have copy-like constructor defined lead to a compilation error. Please find the minimal code example and compilation error log below.

Thanks,

```C++
#include <pybind11/pybind11.h>

template< typename T >
class A
{
public:
	A() {}

	A(T const &  ) {}  // commenting out this line will resolve the error

	//explicit A(A const & ) = default;
};

void foo_t(A<bool>) {}

namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

	m.def("foo_t", (void (*)(class A<bool>)) &foo_t, "doc", pybind11::arg("")); // error

    return m.ptr();
}
```

```
In file included from .../pybind11/include/pybind11/pybind11.h:30:
In file included from .../pybind11/include/pybind11/attr.h:13:
.../pybind11/include/pybind11/cast.h:508:18: error: ambiguous conversion for C-style cast from 'pybind11::detail::type_caster<A<bool>, void>' to 'A<bool>'
        return f((Tuple) std::get<Index>(value)...);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../pybind11/include/pybind11/cast.h:498:9: note: in instantiation of function template specialization 'pybind11::detail::type_caster<std::tuple<A<bool> >, void>::call<void, void (*)(A<bool>), 0>' requested here
        call<ReturnValue>(std::forward<Func>(f), typename make_index_sequence<sizeof...(Tuple)>::type());
        ^
.../pybind11/include/pybind11/pybind11.h:70:31: note: in instantiation of function template specialization 'pybind11::detail::type_caster<std::tuple<A<bool> >, void>::call<void, void (*)(A<bool>)>' requested here
                args.template call<Return>((Return (*) (Args...)) rec->data),
                              ^
/pybind11/include/pybind11/pybind11.h:488:22: note: in instantiation of function template specialization 'pybind11::cpp_function::cpp_function<void, A<bool> , pybind11::name, pybind11::sibling, pybind11::scope, char [4], pybind11::arg>' requested here
        cpp_function func(std::forward<Func>(f), name(name_),
                     ^
by-value.cpp:23:4: note: in instantiation of function template specialization 'pybind11::module::def<void (*)(A<bool>), char [4], pybind11::arg>' requested here
        m.def("foo_t", (void (*)(class A<bool>)) &foo_t, "doc", pybind11::arg("")); // error
          ^
by-value.cpp:4:7: note: candidate is the implicit copy constructor
class A
      ^
by-value.cpp:9:2: note: candidate constructor
        A(T const &  ) {}  // commenting out this line will resolve the error
        ^
1 error generated.
```

**Comment by wjakob** [comment]
That is an issue where it's hard to do much. Clearly, "A" will need to be copied in your example. But the custom constructor causes the default copy constructor to be deleted, which means that pybind11 cannot access it anymore.

**Comment by lyskov** [comment]
ok... but if problem with copy constructor then why does uncommenting line with ```explicit A(A const & ) = default;``` does not help?

**Comment by wjakob** [comment]
Does it work without the ``explicit``?

**Comment by lyskov** [comment]
nope

**Comment by lyskov** [comment]
And to just clarify: commenting out line ```A(T const &  ) {}``` remove the error no matter if other constructors is present or not. And from the error it looks like compiler getting confused this constructor with  copy-constructor which does not make sense to me...

**Comment by bennybp** [comment]
It's not related to templates, but actually is related to any class with a constructor that takes `bool`. (ie, remove the template and it still won't compile, change it to take an `int` and it will).

After a little digging, it looks like it's because C++ will implicitly cast a pointer to a `bool`, and the type_caster classes have some not-explicit `operator type*()` conversions. (adding explicit to the one in cast.h line 217 did the trick for me, but there may others).

**Comment by wjakob** [comment]
@bennybp Making the type_caster casting operations explicit will route the casting operation to the (incorrect) implicit operator. The code will compile in this case, but it's not the desired behavior.

I committed a workaround with some template logic that selects the right operator in all cases, which avoids the error.

**Comment by lyskov** [comment]
Awesome, thank you for fixing this!
