### ISSUE TITLE
bind_vector calls len on iterable

### ISSUE THREAD

**Issue by mika-fischer** [pybind/pybind11#1474]
## Issue description
The following code in `stl_bind.h`
```cpp
    cl.def(init([](iterable it) {
        auto v = std::unique_ptr<Vector>(new Vector());
        v->reserve(len(it));
        for (handle h : it)
           v->push_back(h.cast<T>());
        return v.release();
    }));
```
is inconsistent, because an iterable does not necessarily have `__len__` defined. Either that should be checked, or an overload for `sequence` should be provided.

**Comment by bstaletic** [comment]
This could be solved by changing `v->reserve(hasattr(it, "__len__") ? len(it) : 0)` or maybe it should use `len_hint` from #1496.

**Comment by mika-fischer** [comment]
This was fixed in https://github.com/pybind/pybind11/commit/22859bb8fc1a7f106182e142dcb8b5aed6a7a879
