### ISSUE TITLE
Workaround for binding void* type

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#148]
Hi, i am working on workaround that will allow binding of void* type in Python (so Python code could hold void* as-value and use it later as function argument etc) The code below appear to be working and do the trick. However it seems that attempt to compile this code should really produce an error (by attempt to cast 'VoidPointer' to 'void *' and vice versa). So i am curious: how/why exactly this code is able to compile? And i also submitting this as an issue in case this is actually a bug.

Thanks,

```c++
#include <pybind11/pybind11.h>
#include <iostream>

struct VoidPointer
{
	void *p;
	//explicit operator void*() const { return p; }  // apper to be not needed...
};


void * foo_null_0() { return nullptr; }
void * foo_null_1() { return (void*)1; }
void * foo_null_2() { return (void*)2; }
void foo_null(void *p) { std::cout << p << std::endl; }

namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

	pybind11::class_<VoidPointer> cl(m, "VoidPointer");
	cl.def(pybind11::init<>());

	m.def("foo_null_0", (VoidPointer (*)()) &foo_null_0, "doc");
	m.def("foo_null_1", (VoidPointer (*)()) &foo_null_1, "doc");
	m.def("foo_null_2", (VoidPointer (*)()) &foo_null_2, "doc");

	m.def("foo_null", (void (*)(VoidPointer)) &foo_null, "doc", pybind11::arg(""));

    return m.ptr();
}
```

**Comment by wjakob** [comment]
Hi Sergey,

not sure I get the issue -- using casts like
```
(VoidPointer (*)()) 
```
you change the type of the function (so pybind11 doesn't even know that ``void*`` pointers are involved). 
Or am I missing something?
-Wenzel

**Comment by lyskov** [comment]
Ah, i see... - yes, you absolutely right that way pybind11 does not even know that functions is of wrong types - never mind then.

Thank you for checking on this!
