### ISSUE TITLE
Two Eigen Matrix outputs of one function

### ISSUE THREAD

**Issue by AlessandroFasse** [pybind/pybind11#1480]
Hello everybody,

I am more very new to pybind and have the following question. 

I am currently working with the 3d geometry library libigl which provides very nice 3d functions. In this library all data a encoded as two Eigen::Matrices, that is, one for the vertices of a 3D Mesh and another one contains the faces ( triangles) of the mesh. There is for example a libigl function that takes  a set of vertices and faces and computes new vertices and faces. Is there a way two return both at the same time? So in python can I do something as

new_vertices, new_faces = ownpybind.update_mesh(vertices, faces)

where the underlying function in C++ should look like this:

void update_mesh(MatrixXd vertices, MatrixXi faces){
    MatrixXd new_vertices;
    MatrixXi new_faces;
    igl::update_mesh(vertices, faces, new_vertices, new_faces);
    py::return(new_vertices, new_faces);
}

I would really appreciate your help!

Best, 
Alessandro

**Comment by yesint** [comment]
Just return a tuple:

```
.def("update_mesh",[](const MatrixXd& vertices, const MatrixXi& faces){
 MatrixXd new_vertices;
 MatrixXi new_faces;
 igl::update_mesh(vertices, faces, new_vertices, new_faces);
 return py::make_tuple(new_vertices,new_faces);
})
```
Btw, passing matrices by value is very very bad idea! Consider using Eigen::Ref or templated function as described in Eigen documentation.

**Comment by YannickJadoul** [comment]
Answered by @yesint (thanks, @yesint!).
