### ISSUE TITLE
Return of a read file

### ISSUE THREAD

**Issue by AlessandroFasse** [pybind/pybind11#1482]
Hey everybody, 
currently I am working on a way to use libigl in order to make some computations on meshes. 
Libigl has a method in order to use a already opened file via 

bool igl::readSTL(
      FILE * stl_file, 
      std::vector<std::vector<TypeV> > & V,
      std::vector<std::vector<TypeF> > & F,
      std::vector<std::vector<TypeN> > & N)
{

My goal is now to write a method that gets a string and returns to python the read file. I have:

FILE * read_binary(std::string &filename){
        FILE * opened_file;
        opened_file = fopen(filename.c_str(), "r");
        fclose(opened_file);
        return opened_file;
}

However, if I run the code I get the following error:

TypeError: Unable to convert function return value to a Python type! The signature was
	(arg0: str) -> _IO_FILE

Is there a way to move an openend file with pybind11 between C++ and Python?

**Comment by YannickJadoul** [comment]
No answer after @bstaletic correctly said we need more details to help. Closing.
