### ISSUE TITLE
Is it possible to translate caffe python api from Boost.Python to pybind11

### ISSUE THREAD

**Issue by fireae** [pybind/pybind11#1484]
I am now facing some problems.

 bp::class_<Blob<Dtype>, shared_ptr<Blob<Dtype> >, boost::noncopyable>(
    "Blob", bp::no_init)
    .add_property("shape",
        bp::make_function(
            static_cast<const vector<int>& (Blob<Dtype>::*)() const>(
                &Blob<Dtype>::shape),
            bp::return_value_policy<bp::copy_const_reference>()))
    .add_property("num",      &Blob<Dtype>::num)
    .add_property("channels", &Blob<Dtype>::channels)
    .add_property("height",   &Blob<Dtype>::height)
    .add_property("width",    &Blob<Dtype>::width)
    .add_property("count",    static_cast<int (Blob<Dtype>::*)() const>(
        &Blob<Dtype>::count))
    .def("reshape",           bp::raw_function(&Blob_Reshape))
#ifdef USE_CUDA
    .add_property("_gpu_data_ptr",
        reinterpret_cast<uintptr_t (Blob<Dtype>::*)()>(
          &Blob<Dtype>::mutable_gpu_data))
    .add_property("_gpu_diff_ptr",
        reinterpret_cast<uintptr_t (Blob<Dtype>::*)()>(
          &Blob<Dtype>::mutable_gpu_diff))
#endif
    .add_property("data",     bp::make_function(&Blob<Dtype>::mutable_cpu_data,
          NdarrayCallPolicies()))
    .add_property("diff",     bp::make_function(&Blob<Dtype>::mutable_cpu_diff,
          NdarrayCallPolicies()));
  BP_REGISTER_SHARED_PTR_TO_PYTHON(Blob<Dtype>);

  bp::class_<Layer<Dtype>, shared_ptr<PythonLayer<Dtype> >,
    boost::noncopyable>("Layer", bp::init<const LayerParameter&>())
    .add_property("blobs", bp::make_function(&Layer<Dtype>::blobs,
          bp::return_internal_reference<>()))
    .def("setup", &Layer<Dtype>::LayerSetUp)
    .def("reshape", &Layer<Dtype>::Reshape)
    .add_property("type", bp::make_function(&Layer<Dtype>::type));
  BP_REGISTER_SHARED_PTR_TO_PYTHON(Layer<Dtype>);

Blob -> numpy 
Layer is a abstract class, and support python layer

**Comment by bmerry** [comment]
I don't think you should expect the pybind developers to port your code for you. You will be more likely to get help if you indicate where you're having trouble, what you've tried so far and what errors you're getting as a result.

Also, please edit your question to put your code in triple backticks so that it doesn't get mangled by the formatter (see https://guides.github.com/features/mastering-markdown/).

**Comment by fireae** [comment]
@bmerry, thank you
