### ISSUE TITLE
py::bind_vector doesn't support negative index

### ISSUE THREAD

**Issue by liuzqt** [pybind/pybind11#1489]
I have a class Point3d of (x,y,z).

according to the [tutorial](http://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html), I try to implement vector of Point3d as some buffer, which can be easily converted to numpy array.
But it doesn't support negative index. How can I customize the __getitem__ method?

here is how I bind vector of Point3d

```
  // Declare opaque binding of vectors
  py::bind_vector<std::vector<Point3d>>(m, "Point3dList", py::buffer_protocol())
      .def_buffer([](std::vector<Point3d> &v) -> py::buffer_info {
        return py::buffer_info(
            (void *) v.data(),
            sizeof(double),
            py::format_descriptor<double>::format(),
            2,
            {(int) v.size(), 3},
            {sizeof(double) * 3, sizeof(double)}
        );
      });
```

And an more general question:
Can I customize it as a `list`, but still get the benefit from rearrange its memory layout defined by buffer_protocol?

**Comment by bstaletic** [comment]
In file `include/pybind11/stl_bind.h` is a class named `vector_accessor` that defines the `__getitem__` member function.

Here's the patch that should work:
```diff
diff --git a/include/pybind11/stl_bind.h b/include/pybind11/stl_bind.h
index 21514e9..039cb4d 100644
--- a/include/pybind11/stl_bind.h
+++ b/include/pybind11/stl_bind.h
@@ -281,6 +281,7 @@ void vector_accessor(enable_if_t<!vector_needs_copy<Vector>::value, Class_> &cl)
         [](Vector &v, SizeType i) -> T & {
             if (i >= v.size())
                 throw index_error();
+            if (i < 0) i = v.size() + i;
             return v[i];
         },
         return_value_policy::reference_internal // ref + keepalive
```

**Comment by liuzqt** [comment]
thanks!
