### ISSUE TITLE
Hints on exporting symbols?

### ISSUE THREAD

**Issue by r-owen** [pybind/pybind11#1497]
I would appreciate some help with fixing problems caused by hidden symbol visibility. We built a large code base for linux and macOS with an older version of pybind11 that uses a separate wrapper file for each class (more or less). We are now having problems when we try to build with pybind11 2.2.3 with symbols hidden (something we never tried before).

The current problem I'm wrestling with is that type_info for a given object is different depending on which module I obtain the type info from. But only on macOS, not linux. I *suspect* this means I have to export the symbol for the class in question from the module where it is wrapped, so other wrappers can see it (if only because it all works fine if I don't hide symbols). Here is the simplest example I have been able to come up with:

pb.h:
```
#ifndef LSST_PB
#define LSST_PB

#include <typeinfo>

class ClassA {
public:
    ClassA(void){};

    std::type_info const& type_a() const { return (typeid(ClassA)); };
};

class ClassB {
public:
    ClassB(void){};

    ~ClassB(void) = default;

    std::type_info const& type_a() const { return (typeid(ClassA)); };
};

#endif
```

a.cc
```
#include "pybind11/pybind11.h"
#include "pb.h"
namespace py = pybind11;

PYBIND11_MODULE(a, mod) {
    py::class_<std::type_info>(mod, "TypeInfo")
            .def("__eq__",
                 [](std::type_info const& self, std::type_info const& other) { return self == other; })
            .def("__ne__",
                 [](std::type_info const& self, std::type_info const& other) { return self != other; })
            .def("name", &std::type_info::name)
            .def("hash_code", &std::type_info::hash_code);

    py::class_<ClassA, std::shared_ptr<ClassA>> cls(mod, "ClassA");
    cls.def(py::init<>());
    cls.def("type_a", &ClassA::type_a, py::return_value_policy::reference);
}
```

b.h
```
#include "pybind11/pybind11.h"
#include "pb.h"
namespace py = pybind11;

PYBIND11_MODULE(b, mod) {
    py::module::import("a");

    py::class_<ClassB, std::shared_ptr<ClassB>> cls(mod, "ClassB");
    cls.def(py::init<>());
    cls.def("type_a", &ClassB::type_a, py::return_value_policy::reference);
}
```

Put these all in a directory "src" and use this CMakeLists.txt:

```
cmake_minimum_required(VERSION 2.8.12)
project(pb)

add_subdirectory(pybind11)
pybind11_add_module(a src/a.cc)
pybind11_add_module(b src/b.cc)
```

It builds just fine (though I've seen situation where `py::module::import("a");` segfaults on import of the module `b` and I'm not sure why -- it's not random, but small changes to the build seem to make this happen).

If I then run Python and create an instance of ClassA and ClassB I see is that the value returned by `type_a()` is different for the two instances: they do not compare equal.

My suspicion is that I have to export the wrapped version of `ClassA` from the module `a` so that the module `b` can see it. I just don't know how to do that. The documentation recommends PYBIND11_EXPORT as part of the class definition, and I have tried that in the definition of `ClassA` but it has no effect. Also our C++ is used as shared libraries by other code, so I don't want to add pybind11-specific code to that; we strongly prefer to isolate the pybind11 wrappers from the C++ code it wraps. Thus a solution that is specific to the wrappers would be most appreciated.

**Comment by r-owen** [comment]
Also, for completeness, here is the test I run to show the problem:
```
import unittest

from a import ClassA
from b import ClassB


class ABTestCase(unittest.TestCase):
    """A test case for PropertyList."""

    def testTypes(self):
        a = ClassA()
        b = ClassB()

        self.assertEqual(a.type_a().name(), b.type_a().name())

        # these two both fail
        self.assertEqual(a.type_a(), b.type_a())
        self.assertEqual(a.type_a().hash_code(), b.type_a().hash_code())


if __name__ == "__main__":
    unittest.main()
```

**Comment by r-owen** [comment]
See also https://jira.lsstcorp.org/browse/DM-15151

**Comment by r-owen** [comment]
Adding `__attribute__((visibility("default")))` to the definition of `ClassA` in pb.h seems to fix the problem:
```
class __attribute__((visibility("default"))) ClassA {
public:
    ClassA(void){};

    std::type_info const& type_a() const { return (typeid(ClassA)); };
};
```

I wonder why `PYBIND11_EXPORT` did not, since I would expect it to do the same thing.

**Comment by bstaletic** [comment]
`PYBIND11_EXPORT` expands to `__attribute__((visibility("default"))` on gcc and clang and to `_declspec(export)` on MSVC. If you're interested if that really happened, take a look at the preprocessed file, by passing `-save-temps` to gcc.

**Comment by bstaletic** [comment]
This seems to be resolved.
