### ISSUE TITLE
Namespace py::class_ member functions

### ISSUE THREAD

**Issue by Tmplt** [pybind/pybind11#1500]
I'm currently improving the Python bindings for a program I'm writing, but I've gotten stuck with the actual implementation, and request help.

My program loads Python plugins that uses callbacks and a logging function, the latter of which is what I'm having trouble with. A function is called in each plugin with a class instance as argument. The current implementation is the following:
```cpp
enum class log_level {
    debug = 1,
    warn = 2,
    error = 3
};

class plugin_handler {
public:
    void log(log_level lvl, const std::string &msg)
    {
        // ...
    }
};

PYBIND11_MODULE(pybindings, m)
{
    py::enum_<log_level>(m, "log_level")
        .value("debug", log_level::debug)
        .value("warn",  log_level::warn)
        .value("error", log_level::error);

    py::class_<plugin_handler>(m, "plugin_handler")
        .def("log", &plugin_handler::log);
}
```
In my plugins, I would then write:
```python
def function(instance):
    instance.log(pybindings.log_level.debug, 'this is a debug log entry')
    instance.log(pybindings.log_level.warn, 'this is a warning log entry')
    instance.log(pybindings.log_level.error, 'this is an error log entry')
```
But I would like to change this into:
```python
def function(instance):
    instance.log.debug('this is a debug log entry')
    instance.log.warn('this is a warning log entry')
    instance.log.error('this is an error log entry')
```
How would I do that?

This could easily be solved by defining a submodule and three log function within it, but these will then not be related to the instance argument. I can't define a submodule in a `py::class_`, so it seems I have to manage this with a `.def()`. A `.def("__getattr__", ...)` would allow for arbitrary attributes, but for `instance.log.error` the key would be `log` instead of `log.error`.

Is there some other way? Is this possible?

Cheers.

**Comment by bstaletic** [comment]
How about making `log` a class that has `debug`, `warn` and `error` as member functions?

**Comment by Tmplt** [comment]
Good idea. Here's an initial working implementation:
```cpp
enum class log_level {
    debug = 1,
    warn = 2,
    error = 3
};

class plugin_handler {
public:
    void log(log_level lvl, const std::string &msg)
    {
        // ...
    }
};

namespace detail {

struct log_wrapper {
public:
    explicit log_wrapper(plugin_handler* instance)
        : ph_(instance)
    {
        assert(ph_ != nullptr);
    }

    void debug(const std::string &msg)
    {
        ph_->log(log_level::debug, msg);
    }
    void warn(const std::string &msg)
    {
        ph_->log(log_level::warn, msg);
    }
    void error(const std::string &msg)
    {
        ph_->log(log_level::err, msg);
    }

private:
    core::plugin_handler* ph_;
};

}

PYBIND11_MODULE(pybindings, m)
{
    py::class_<detail::log_wrapper>(m, "log")
        .def("debug", &detail::log_wrapper::debug)
        .def("warn", &detail::log_wrapper::warn)
        .def("error", &detail::log_wrapper::error);

    py::class_<plugin_handler>(m, "plugin_handler")
        .def("log", &plugin_handler::log)
        .def("__getattr__", [&](plugin_handler &ph, const std::string &key) {
            if (key == "log")
                return detail::log_wrapper(&ph);

            // Is there some exception that pybind11 translates to AttributeError?
            throw std::invalid_argument(std::string("AttributeError: no plugin handler attribute with key '") + key + "'");
        });
}
```
It feels dirty though, what with a new `detail::log_wrapper` instance whenever something is logged. But I don't know if there is some better way to do this.

**Comment by jbarlow83** [comment]
It would be cleaner to define `.def_property_readonly("log", ...)` which returns a `log_wrapper` instance.

But you do have to do it this way, because after Python calls `__getattr__` it expects to get a new object. To Python

```python
instance.log.debug('this is a debug log entry')
```

means

```python
_tmp = instance.__getattr__('log')
_tmp2 = _tmp.__getattr__('debug')
_tmp2.__call__('this is a debug log entry')
```

You could cheat by having the `.log` return self and defining debug, warn and error as class methods. That would support the use of .log as a convention.

Aside: use smart pointers.

**Comment by Tmplt** [comment]
Thank you. This resolves my issue.
