### ISSUE TITLE
Overload char and std::string

### ISSUE THREAD

**Issue by ax3l** [pybind/pybind11#1509]
## Issue description

Overloading a signature for both `char` and `std::string` will always select the `char` overload.
Passed strings will then fail.

Affected pybind11 release: `2.2.3`

## Reproducible example code

Binding code:
```C++
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <iostream>
#include <string>

namespace py = pybind11;

PYBIND11_MODULE(cmake_example, m) {
    m.def("foo", [](char const& value) {
        std::cout << "char!" << std::endl;
    });
    m.def("foo", [](std::string const& value) {
        std::cout << "string!" << std::endl;
    });
/* same with:
    m.def("foo", [](py::str const& value) {
        std::cout << "python string!" << std::endl;
    });
*/
}
```

Runtime:
```python
# Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
# [GCC 7.2.0] on linux
# Type "help", "copyright", "credits" or "license" for more information.
import cmake_example

cmake_example.foo("a")
# char!

cmake_example.foo("ab")
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ValueError: Expected a character, but multi-character string found

cmake_example.foo(b"ab")
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ValueError: Expected a character, but multi-character string found

cmake_example.foo(b"a")
# char!

cmake_example.foo(str("a"))
# char!

cmake_example.foo(str("ab"))
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ValueError: Expected a character, but multi-character string found
```

**Comment by bstaletic** [comment]
As a workaround, I'd take a `const std::string &` in the lambda and have some logic that would decide whether I'm passing the whole string object next or just the `c_str()`.

**Comment by ax3l** [comment]
Thx for the work-around, did exactly that and decided on `string.size()` in my case.

**Comment by earonesty** [comment]
There's no such thing as a "char" in python, so a string of size 1 and a char are the same thing.   If you need a way to distinguish between them you will need to have two functions.

**Comment by bstaletic** [comment]
@earonesty The idea is to distinguish between `char*` and `sd::string`.

**Comment by ax3l** [comment]
Yep, the idea is that if both are overloaded, `std::string` would be the better one to select.
Anyway, changing again the order in-code for he overload probably already solves this, but we might want to do this automatically?

**Comment by bstaletic** [comment]
I'm not sure on which criteria would you pick one over the other. For my project, `std::string` is always preferred, but we don't have `char*` overloads.

**Comment by ax3l** [comment]
hm, I think this issue is invalid. A user chan choose the overload if need be.
