### ISSUE TITLE
Leaks from Address Sanitizer

### ISSUE THREAD

**Issue by mbrucher** [pybind/pybind11#1510]
The issue is related to https://github.com/pytorch/pytorch/issues/5161

It seems that pybind11::cpp_function::initialize_generic (and others) are allocating data that never gets freed before the end of the run, when ASAN is unloaded.

Is it a known issue in pybond11? Boost.Python also has similar issues, so wondering if there shouldn't be a documentation on how to avoid these or valgrind/ASAN blacklist?

**Comment by bstaletic** [comment]
Running Valgrind on a python executable is always troublesome. CPython, while written in C, doesn't use `malloc`, instead it has its own implementation called `PyMalloc`. When you compile your interpreter you can pass `--with-valgrind` and `--without-pymalloc`, yet this is still not enough.

According to Valgrind, python2 leaks a lot more than python3, but has orders of magnitude fewer memory access errors.
It is possible to suppress Valgrind errors and to even generate suppression rules with `--gen-suppressions`, but once I got a clean Valgrind run on my local machine it didn't work on CI builds.
There's [an outdated valgrind suppression file](https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Misc/valgrind-python.supp) in the CPython repository too.

All this said, I think there might be a few issues coming from pybind11, not just CPython. For that part take a look at https://github.com/pybind/pybind11/pull/1454, which touches upon the discussion of ridding pybind11 of (known) leaks.

**Comment by mbrucher** [comment]
These are the issues that ASAN finds on pybind11 code. As Python is not generated with asan, there is no issue with Python code. Only the memory allocated by the pyblind11-wrapped modules and not freed by them.
I don't care currently about valgrind, only ASAN builds (because they are faster and better).

**Comment by micbou** [comment]
Look at the memory leaks. They are all coming from CPython functions (mostly `_PyCFunction_FastCallDict`). I doubt pybind11 can do much about that.

**Comment by bstaletic** [comment]
@mbrucher ASAN begin "better" is debatable. Try running valgrind with `--track-origins=full` or `--track-origins=yes`. It will make valgrind even slower, but it will tell you where an error occured.

**Comment by mbrucher** [comment]
I know both of them quite well ;)

**Comment by mbrucher** [comment]
@micbou perhaps, but I didn't see anything in the documentation about how to solve this issue...

**Comment by bstaletic** [comment]
This seems to be all about leaks (or "leaks") from CPython API. It doesn't look like pybind11 is to blame. Some things you can look into:

- `PYTHONMALLOC`
- Compiling python with `--without-malloc` or with `--with-valgrind`.
- Valgrind suppression files.
