### ISSUE TITLE
__cpp_fold_expressions now defined in MSVC

### ISSUE THREAD

**Issue by sum-catnip** [pybind/pybind11#1515]
## Issue description

__cpp_fold_expressions got defined in the new MSVC version. Pybind will therefore no longer compile with the newest visual studio / VC++ installed. To fix it i changed `#ifdef __cpp_fold_expressions` in common.h:480 to `#if defined(__cpp_fold_expressions) && !defined(_MSC_VER)` this is probably not the best solution but i figured other people could stumble across this problem too.

## Reproducible example code

well just build anything with an up to date visual studio toolset.

**Comment by wjakob** [comment]
Fixed in 'master'.
