### ISSUE TITLE
MSVC 2015 crashes when trying to run a simple example

### ISSUE THREAD

**Issue by roozbehg** [pybind/pybind11#1516]
Hi,

I just started using pybind11. I basically followed the instruction provided in the web site. I'm using MSVC 2015 with Python 3.6 (32bit) to run some basic example. I make all the links to include and libs folders and compiled it. everything worked fine for a simple pyd library creation and I even imported the module into python and tested it. but MSVC crashes every time I start to run (both in debug and release mode) the following piece of code. it compiles with no issue though.

#include <pybind11/embed.h>
namespace py = pybind11;

void main() {
    py::scoped_interpreter guard{}; 
    py::print("Hello, World!"); 
}

I checked the existing issues but unfortunately could not figure out the reason. I'd really appreciate if you can help me?

**Comment by 10se1ucgo** [comment]
Do you have another version of Python installed and in your PATH? I had both Python 3.6 32 & 64 bit installed, and the 64 bit version was in my PATH. However, I was building the example off the 32-bit installation, and what I assume was happening was it loaded the python36.dll from the 64 bit version in my PATH and crashed. Maybe try manually copying python36.dll from the 32 bit installation to your build folder.

**Comment by YannickJadoul** [comment]
No reply to a helpful question/suggestion (and quite a probably explanation of what goes wrong, actually; thanks @10se1ucgo!) +1.5 years. I'm closing this.
