### ISSUE TITLE
How I could return a py::list with values

### ISSUE THREAD

**Issue by CoinCheung** [pybind/pybind11#1528]
I looked through the docs to find a way to let c++ program return a python list, but I was not so luck to find where it is. For example, in the python side, I hope there is a function: 
```
>>> import my_module
>>> my_module.fun([1,2,3])
[2,3,4]
```
In the c++ side, I have a function like this one:
```
py::list fun(py::list& li) {
vector<int> vi(py::len(li));
vi.clear();
for (auto& el : li) vi.push_back(el.cast<int>() + 1);

py::list res;
// How I could fill the content of this py::list object with the values in vi
return res;
}
```
How could I fill the object ```res``` with the values from ```vi```, or could I directly use ```res``` rather than ```vi``` as the container to hold the result ?

**Comment by bstaletic** [comment]
`py::list` has `operator[]` defined, so you can do `res[0] = foo`. There's also `py::list::append()`. You can use `py::list` just like a python list.

**Comment by CoinCheung** [comment]
@bstaletic Thanks, how could I use operator [] to create a dict object like this? 
{1: [1,2,3], "age": 23, "name": "john" } 

I have a c++ function which I find not work: 
```
py::dict get_dict() {
    py::dict res;
    py::list li;
    li.append(1);
    li.append(2);
    li.append(3);
    res["name"] = "john";
    res["age"] = 23;
    res[1] = li; 
    return res;
}
```
this line ```res[1] = li;``` will not work, since number 1 in operator [] is not allowed

**Comment by bstaletic** [comment]
Did you try with a `py::int_(1)` instead of just `1`?

**Comment by CoinCheung** [comment]
Yeah, that works for me, thanks a lot. 
BTW, would you please give me some help on this issue?https://github.com/pybind/cmake_example/issues/15#issue-360632699

**Comment by bstaletic** [comment]
I left a comment there too. Close the issue if it is resolved.

**Comment by CoinCheung** [comment]
OK, Many Thanks
