### ISSUE TITLE
no module when compiling with CMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by Tux1** [pybind/pybind11#1529]
main.cpp :
```
#include <pybind11/pybind11.h>
int main() {
    return 0;
}

PYBIND11_MODULE(exe1, m) {
    m.def("main", &main);
}
```
CMakeLists.txt :
`pybind11_add_module(exe1 main.cpp)`

test.py :
```
try:
    import exe1
except ImportError:
    print('exe1 failed')
else:
    print(exe1)
    print(dir(exe1))
    print(exe1.main())
```

Output :

> <module 'exe1' (namespace)>
> Traceback (most recent call last):
> ['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>   File "/Users/charlesrilhac/CLionProjects/untitled2/test.py", line 12, in <module>
>     print(exe1.main())
> AttributeError: module 'exe1' has no attribute 'main'

and I noticed that the output file is name exe1**d**.cpython-37m.darwin.so with a `d` at the end of the name.

I do something wrong or is it a bug ?
When compiling CMAKE_BUILD_TYPE=Release or nothing, it is going well.

**Comment by Tux1** [comment]
Nobody is facing the same issue ?

**Comment by bstaletic** [comment]
Something tells me this has to do with [symbol visibility](https://pybind11.readthedocs.io/en/stable/advanced/misc.html?highlight=visibility).

Quoting the docs:

> Note that pybind11 code compiled with hidden-by-default symbol visibility (e.g. via the command line flag -fvisibility=hidden on GCC/Clang), which is required proper pybind11 functionality, can interfere with the ability to access types defined in another extension module. Working around this requires manually exporting types that are accessed by multiple extension modules; pybind11 provides a macro to do just this:

This is also why you should have posted how you have compiled the extension module.

> You can name it `main`.

No, you can't, but try it when you fix the symbol visibility.

**Comment by Tux1** [comment]
I think I can :) :
main.cpp :
```
#include <pybind11/pybind11.h>
int main() {
    return 0;
}
PYBIND11_MODULE(exe1, m) {
    m.def("main", &main);
}
```

CMakeLists.txt :
```
set(SOURCE_FILES main.cpp)
pybind11_add_module(exe1 ${SOURCE_FILES})
```

test.py : 
```
import exe1
print(exe1)
print(dir(exe1))
print(exe1.main())
```

output :

> <module 'exe1' from '/Users/me/CLionProjects/untitled/cmake-build-release/exe1/exe1.cpython-37m-darwin.so'>
> ['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'main']
> 0
>

**Comment by bstaletic** [comment]
When I bind `main`  like that I get a segfault. Even if it works for you it is undefined behaviour to directly invoke `main`. At least in C++. In plain old C it is perfectly valid.

Also, what doesn't work? You've just shown `main` being called above.

**Comment by Tux1** [comment]
Because I built the example in Release not in Debug

**Comment by bstaletic** [comment]
As far as symbol visibility is concerned, you need to explicitly expose needed symbols. Pybind11 provides a convenience macro `PYBIND11_EXPORT`.

```c++
class PYBIND11_EXPORT Foo {} // explicitly visible class
```

**Comment by Tux1** [comment]
I think CMake in Release mode strip C++ binary. It might cause the issue no ? Python is not able to recognise anything in the module built ?

**Comment by sdebionne** [comment]
I am not sure about macOS but on Windows a module built in debug should be run with a debug version of Python (`python_d`).

**Comment by henryiii** [comment]
Please reopen if there is still a problem!

**Comment by ChivenZhang** [comment]
I got the same problem. What I have done as below:
* Using vs2019 build .pyd file by pybind11.
* Launch .py file which import the .pyd file in last step.
* Error reported that cannot find module named ...
The wield point is that what done well in release mode compile except debug mode. So I think it's not as the path config result in failed import.

**Comment by kaiware0x** [comment]
I encountered the same issue, but I solved by manually appending `_d` to the name of the built module.

For example: 
extend01.cp312-win_amd64.pyd -> extend01**_d**.cp312-win_amd64.pyd

However, when importing a module, do not add `_d`. 
```py
# Same for Debug and Release.
import extend01
```
