### ISSUE TITLE
Binded function default arguments only evaluated once

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#153]
Hi, i noticed that current version of pybind11 evaluate C++ function default arguments only once during 'binding phase' (Python style) as opposed to do so for every-call as C++ does. While this behavior certainly inline with Python idioms it might be not desirable while dealing with C++ code and might lead to confusing situation when 'same' call from Python and from C++ will lead to different results (example below). Also: some C++ function default might be written in a way that does not allow it to be called before certain init() was called (which is impossible with current implementation).

So, would it be possible to make functions default for binded functions to be evaluated during function call?

Thanks,

```c++
#include <pybind11/pybind11.h>
#include <iostream>

int foo_default()
{
  std::cout << "Default called!!!" << std::endl;
  static int a=0;
  return a++;
}

int foo(int a = foo_default())
{
	return a;
}

namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

	m.def("foo", (int (*)(int)) &foo, "doc", pybind11::arg_t<int>("a", foo_default(), "foo_default()"));

    return m.ptr();
}
```

**Comment by wjakob** [comment]
Hi Sergey,

older versions of pybind11 actually did what you propose. The current scheme (which only evaluates once) lead to a significant simplification of the codebase and a more straightforward way to auto-stringify arguments if no explicit string is provided. So I am not in favor of changing back.

You could probably emulate the behavior you want with a lambda function that takes a dummy default argument (e.g. nullptr or -1) and calls foo_ptr() in that case. This could all be hidden by providing a "foo_default()" string for the default argument as you do now.

Wenzel

**Comment by lyskov** [comment]
Thank you for clarification Wenzel! I see your point, I am guessing that implementation of initialization-for-each-call require C macros, while current implementation is pure C++ code right? I will see if there is a way to generalize lambda function approach.

Best,

**Comment by wjakob** [comment]
Ok, I'm closing this ticket for now since there is no TODO on the pybind11 side. Feel free to open a support ticket if you have issues getting it to work.
