### ISSUE TITLE
Error during class registration should not leave the (incomplete) class in the module

### ISSUE THREAD

**Issue by eudoxos** [pybind/pybind11#1534]
## Issue description

When class registration fails because default argument of its method cannot be converted (type not registered yet), that (incomplete) class object is already in the module. Failure during class registration should not leave that behind; otherwise, registering that class later (when the default argument can be converted already) fails with "object with that name is already defined".

The use case: I am migrating a larger code from boost::python where a number of classes are registered in quasi-random order. Sometimes registration fails because the base class is not registered yet, and this is retried until all classes will have been registered successfully.

If this cannot be fixed directly, please document how to remove the (half-)registered class from pybind11 registry (or something like that ;) this is `boost::python`), besides deleting the name from the module, so that subsequent registration can succeed.

## Reproducible example code

```
#include<iostream>
#include<pybind11/pybind11.h>
namespace py=pybind11;

struct B { int i=-1; };
struct A { int meth(const B& b){ return b.i; } };

// register class A, but catch and report exceptions
void tryRegA(py::module m){
   try{ py::class_<A>(m,"A").def("meth",&A::meth,py::arg("b")=B())	;}
   catch(std::exception& e){ std::cerr<<"Error exposing class A:\n"<<e.what()<<std::endl;}
}

PYBIND11_MODULE(pb11reg, m) {
   // this will fail because of the default argument conversion
   tryRegA(m);
   // now register B for the argument
   py::class_<B>(m,"B");
   // this will fail because A is already registered
   tryRegA(m);
}

```

compile with:

    c++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` pb11reg.cpp -o pb11reg`python3-config --extension-suffix`

and the result:

```
Error exposing class A:
arg(): could not convert default argument 'b: B' in method '<class 'pb11reg.A'>.meth' into a Python object (type not registered yet?)
Error exposing class A:
generic_type: cannot initialize type "A": an object with that name is already defined
```

The second registration of A would suceed had the failed first registration of `A` not left the class behind.

**Comment by bstaletic** [comment]
Why not just take care of the order of registration on the user's end? I'm not aware of any easy way of unregistering a class, assuming that is even possible.

**Comment by eudoxos** [comment]
The unregistration would be an extreme. Much better would be if registration would be done at the end, after everything succeeded. `boost::python` would not register the class unless the wrapper was successfully created completely.

The registration order is just too complicated (about 250 classes) to be maintained by hand, computers are better at that.

**Comment by bstaletic** [comment]
I've taken a look at the pybind11 code. What happens here is that on first invokation of `tryRegA()`, the class registration succeeded. It's the attribute registration that failed, so we're again back to the question - "how to unregister a class that was previously successfully registred?"

You could do something like this:

```c++
void tryRegA(py::module m) {
        // Should succeed on first try and fail on second.
        // Wrap in a try/catch.
        // If there already is a class A in the module, do something 
        // py::class_<A> class_A = m.attr("A");
        py::class_<A> class_A(m, "A");
        // Should fail on first try and succeed on second.
        // Wrap in a try/catch and repeat for every py::class_::def
        class_A.def("meth",&A::meth,py::arg("b")=B());
}
```

**Comment by eudoxos** [comment]
I could do first class registration only (no attributes/methods/...) with the current scheme (retrying in circles) and only then do the rest at once, for all classes. I will get back how that worked.

**Comment by eudoxos** [comment]
Hm, that said, is there a way to retrieve the class_<...> object later? Can I keep it from the first registration and retrieve it later to add those methods? As they are templates (different types), it is hard to store them. Maybe I will have to look at co-routines to do that :/

**Comment by bstaletic** [comment]
You can pass references around. Just be careful about the object life time. Also, I see no reason that `py::class_` part (without `def`) wouldn't work from the start, without invoking any `tryFoo` function, so that would be an easy solution to the life time problem.

**Comment by eudoxos** [comment]
I managed to solve it in a pretty funny way, something along this line. For each class, define class registration which (if it does not throw) returns a lambda function, which will define the class attributes. Those function are called in a loop until all classes will have been registered.

PS the reason why the registration order cannot be maintained is also that the classes are defined in various plugins which might or might not be loaded.

```
std::function<void()> regA(py::module m){
   py::class_<A> class_A(m,"A");
   return [m,class_a]() mutable {
      class_A.def("meth",&A::meth,py::arg("b")=B();
   }
}
PYBIND11_MODULE(mymod,m){
   std::list<std::function<void()>> defs;
   while(True){
      /* loop over all registration functions which did not succeed yet, repeatedly */
      try{
         defs.push_back(regA(m));
         /* success, remove the class registration function from the list to be run again */
      } except(...){ /* do nothing*/ }
   }
   // all classes registered now; define their attributes via those lambdas returned
   for(auto doDef: defs) doDef();
}
```

**Comment by eudoxos** [comment]
Thanks for help. Closing.
