### ISSUE TITLE
multiple inheritance

### ISSUE THREAD

**Issue by fabioramponi** [pybind/pybind11#154]
How can I wrap a c++ class inheriting from more than one class?

e.g.: say I have this c++ code:

```cpp
class A {
public:
   void methodA() {...};
}

class B {
public:
  void methodB() {...};
}

class C: public A, public B {}
class D: public A, public B {}
```
How should I wrap it so that In python I can write something like this?

```python
c_inst = C()
c.methodA()
c.methodB()
d_inst = D()
d.methodA()
d.methodB()
```

**Comment by wjakob** [comment]
Multiple inheritance is not supported by pybind11 -- sorry for the inconvenience.

**Comment by wjakob** [comment]
Closing this -- see also 1e1f3675cdec705de23ffc2d28c8cbc7b9a65343 for the rationale.

**Comment by Vayu** [comment]
It probably worth to mention, that although it is not possible to map relationships, one can still wrap individual classes and their method independently (like example code in this issue which doesn't use and inheritance relationships).

**Comment by pschella** [comment]
Any update on this feature? I heard a patch to enable multiple-inheritance is in the works. But I can't find it or an issue tracking it. We are currently evaluating using pybind11 for a large body of code and it would be good to know if this is expected to work in the near future.

**Comment by wjakob** [comment]
There are various partial patches -- I'll need to sit down at some point and figure out what to do with them. This is a very delicate change, so I won't make any promises as far as timing goes.

**Comment by pschella** [comment]
I understand. Just know that we most likely (I'm not responsible for scheduling) would be willing to help implement this feature.
