### ISSUE TITLE
Failed to import functions defined through embedded interpreter script execution

### ISSUE THREAD

**Issue by pdicerbo** [pybind/pybind11#1541]
Hi there,
I need to define a set of python functions and then call them from my c++ application. Moreover, for some technical reasons this functions cannot be implemented in a "classical" python module and then imported into c++ side (by means of `py::import` statement): they must be dynamically implemented in the c++ code, since the functions implementation depends on some parameters which in turn depend on the configuration. To achieve this, I tried to execute with an embedded interpreter a string containing the functions implementation, then import the global python environment.

## Issue description
Considering the code reported below, after the execution of the `init_script` (which defines the `foo` function) the code simply crashes when I try to retrieve that function. The weird thing is that the function seems to be defined in global environment (the `foo` entry is present when I execute `py::print( py::globals())` on c++ side) after the script execution.

I am compiling in RelWithDebInfo with gcc 8.2.1 on Linux and with Clang 5.0.1 on Windows.

## Reproducible example code
Here the code to reproduce the issue.

```Cpp
#include <iostream>
#include <pybind11/pybind11.h>
#include <pybind11/embed.h>

using namespace std;
namespace py = pybind11;

constexpr char init_script[] = R"__(
def foo( myarg ):
    print("\twithin foo python function with argument:", myarg)
    return 42

if __name__ == "__main__":
    foo("foo method test")    # check foo function definition
)__";


int main()
{
    py::initialize_interpreter();                                               // initialize Python interpreter
    {
        py::object scope = py::module::import("__main__").attr("__dict__");     // import main scope
        py::exec( init_script, scope);                                          // execute python script (which defines "foo" function)
        py::print( py::globals() );                                             // check that foo function is globally defined
        py::object python_method  = py::globals().attr("foo");                  // retrieve foo function: here the code crashes...
        auto ret = python_method("python call test").cast<int>();               // execute python function and retrieve return value
        cout << "from python method retrieved " << ret << endl;                 // print the result
    }
    py::finalize_interpreter();                                                 // finalize Python interpreter
    return 0;
}
```

**Comment by pdicerbo** [comment]
It works!!
I am really sorry for the stupid question, thank you very much for your help :)

**Comment by vanossj** [comment]
No need to be sorry! Sometimes you have to ask questions to learn.
