### ISSUE TITLE
make_tuple fails with py::object argument

### ISSUE THREAD

**Issue by eudoxos** [pybind/pybind11#1543]
## Issue description
```
py::object o;
py::make_tuple(o);
```
fails with `unable to convert argument of type 'object' to Python object`.

This is a nuisance, especially when invoking python callables in c++ via the operator(), where args are packed into tuple -- python objects cannot be passed as arguments this way.

A solution would be to make `py::cast(py::object)` identity function. Is this disallowed for some specific reason?

There is a converter from handle (below), another specialization for py::object should do the job:
```
// pytype -> pytype (calls converting constructor)
template <typename T, detail::enable_if_t<detail::is_pyobject<T>::value, int> = 0>
T cast(const handle &handle) { return T(reinterpret_borrow<object>(handle)); }
```

**Comment by wjakob** [comment]
This sounds like a very sensible addition. I am actually surprised that this does not already exist -- can you add a PR with this change, and a test?

**Comment by kylemacfarlan** [comment]
I ran into this issue today when trying to pass None to a python callback--has there been any progress on it?

**Comment by ngoldbaum** [comment]
I don't think it works with `handle` either? I'm having trouble making a self-contained example, but when I call an `object` with only `handle` instances as arguments, I get:

```
RuntimeError: make_tuple(): unable to convert argument of type 'handle' to Python object
```

**Comment by bstaletic** [comment]
This seems to be working, at least on 2.5.0.

```c++
#include <pybind11/pybind11.h>
#include <pybind11/embed.h>

int main(void)
{
        pybind11::scoped_interpreter g;
        pybind11::object o = pybind11::cast(3);
        pybind11::handle h = pybind11::cast(3);
        auto t = pybind11::make_tuple(o, h);
        pybind11::print(t);
        return 0;
}

(3, 3)
```

If it isn't resolved, feel free to reopen.
