### ISSUE TITLE
PYBIND_OVERLOAD compile error with overloaded class methods and inheritance

### ISSUE THREAD

**Issue by jmikeowen** [pybind/pybind11#1547]
## Issue description

I'm seeing compile errors when using PYBIND_OVERLOAD with overloaded class methods and class inheritance.   The following code runs into trouble trying to provide a trampoline method in the derived class for  an overloaded virtual method in the base:

## Reproducible example code

```
#include "pybind11/pybind11.h"
#include "pybind11/functional.h"
#include "pybind11/operators.h"

namespace py = pybind11;
using namespace pybind11::literals;

#include <iostream>

class A {
public:
  virtual void func()               { std::cout << "A::func()" << std::endl; }
  virtual void func(int x) = 0;
};

class B: public A{
public:
  virtual void func(int x) override { std::cout << "B::func(" << x << ")" << std::endl; }
};

class Atrampoline: public A {
  using A::A;
  virtual void func() override      { PYBIND11_OVERLOAD     (void, A, func,); }
  virtual void func(int x) override { PYBIND11_OVERLOAD_PURE(void, A, func, x); }
};

class Btrampoline: public B {
  using B::B;
  virtual void func() override      { PYBIND11_OVERLOAD     (void, B, func,); }
  virtual void func(int x) override { PYBIND11_OVERLOAD     (void, B, func, x); }
};

PYBIND11_MODULE(test_overload, m) {
  py::class_<A, Atrampoline>(m, "A")
    .def(py::init<>())
    .def("func", (void (A::*)()) &A::func)
    .def("func", (void (A::*)(int)) &A::func)
    ;

  py::class_<B, Btrampoline>(m, "B")
    .def(py::init<>())
    .def("func", (void (B::*)(int)) &B::func)
    ;
}
```

I'm testing with gcc 7.1.0 on a Linux system, which fails to compile the trampoline line for the no argument version of "func" in B (virtual void func() override      { PYBIND11_OVERLOAD     (void, B, func,); }).  The compile errors look like 
```
In file included from testOverloadError.cc:1:0:
testOverloadError.cc: In member function 'virtual void Btrampoline::func()':
/usr/workspace/wsrzd/owen/projects/Spheral/debug-pybind11-toss_3_x86_64_ib/Linux_x86_64/include/pybind11/pybind11.h:1945:33: error: no matching function for call to 'Btrampoline::func()'
     return cname::fn(__VA_ARGS__)
                                 ^
/usr/workspace/wsrzd/owen/projects/Spheral/debug-pybind11-toss_3_x86_64_ib/Linux_x86_64/include/pybind11/pybind11.h:1952:5: note: in expansion of macro 'PYBIND11_OVERLOAD_NAME'
     PYBIND11_OVERLOAD_NAME(ret_type, cname, #fn, fn, __VA_ARGS__)
     ^~~~~~~~~~~~~~~~~~~~~~
testOverloadError.cc:29:39: note: in expansion of macro 'PYBIND11_OVERLOAD'
   virtual void func() override      { PYBIND11_OVERLOAD     (void, B, func,); }
                                       ^~~~~~~~~~~~~~~~~
testOverloadError.cc:18:16: note: candidate: virtual void B::func(int)
   virtual void func(int x) override { std::cout << "B::func(" << x << ")" << std::endl; }
                ^~~~
testOverloadError.cc:18:16: note:   candidate expects 1 argument, 0 provided
In file included from testOverloadError.cc:1:0:
/usr/workspace/wsrzd/owen/projects/Spheral/debug-pybind11-toss_3_x86_64_ib/Linux_x86_64/include/pybind11/pybind11.h:1945:33: error: return-statement with a value, in function returning 'void' [-fpermissive]
     return cname::fn(__VA_ARGS__)
                                 ^
/usr/workspace/wsrzd/owen/projects/Spheral/debug-pybind11-toss_3_x86_64_ib/Linux_x86_64/include/pybind11/pybind11.h:1952:5: note: in expansion of macro 'PYBIND11_OVERLOAD_NAME'
     PYBIND11_OVERLOAD_NAME(ret_type, cname, #fn, fn, __VA_ARGS__)
     ^~~~~~~~~~~~~~~~~~~~~~
testOverloadError.cc:29:39: note: in expansion of macro 'PYBIND11_OVERLOAD'
   virtual void func() override      { PYBIND11_OVERLOAD     (void, B, func,); }
                                       ^~~~~~~~~~~~~~~~~
make: *** [test_overload] Error 1
```

It appears the inherited method A::func() is never considered for matching, so the compilation fails.  If I disambiguate the "func" methods (say by making them "func1" and "func2") everything works as expected.  It also works if I change the overload signature in Btrampoline for func to explicitly use the A class (so change the line to read "PYBIND11_OVERLOAD     (void, A, func,);" in Btrampoline's implementation.

I've been looking through the documentation, tests, and FAQ, but I don't see this particular pattern discussed.  Is this actually an error, or should I be using explicit references to "A" methods in "Btrampoline"?

**Comment by jmikeowen** [comment]
Now that I look at this again I realize this is a problem of function hiding, so I don't think this is a pybind11 problem after all.

**Comment by YannickJadoul** [comment]
> Now that I look at this again I realize this is a problem of function hiding, so I don't think this is a pybind11 problem after all.

I believe you're right. `B::func()` doesn't resolve to `A::func()`, but to `B::func(int)`, which takes a parameter. I think the line `virtual void func() override      { PYBIND11_OVERLOAD     (void, B, func,); }` isn't necessary as long as you don't override `f()` in `B`. Another option is adding `f()` to `B`.

What might still be necessary is `.def("func", (void (B::*)()) &A::func)` if you want the overloads to work on a `B` instance.

**Comment by YannickJadoul** [comment]
> Hi! This is actually the problem I'm fighting through now. I tried to specify 'A' as class to call the func from, yep, it compiles. Doesn't work though - throws me an bad_alloc error. I won't like to change my C++ code. Have you found any solution to this problem yet? Would be super helpful

@vukolka Is this still an issue? If so, please come to [Gitter](https://gitter.im/pybind/Lobby) or give us more information here. It's not really clear from your explanation how your code looks and what goes wrong.
