### ISSUE TITLE
PYBIND11_INTERNALS_ID doesn't take build-type or compiler flags into account

### ISSUE THREAD

**Issue by crest01** [pybind/pybind11#1548]
## Issue description

Two pybind11 - modules with the same PYBIND11_INTERNALS_VERSION aren't necessarily binary compatible, since the build flags aren't included in the PYBIND11_INTERNALS_ID, and at least MSVC subtly changes the memory layout depending on the build type.

I am developing two pybind11-modules at the same time, using cmake and VS2017 to build and debug them. And they need to be built with the same build type, or the internals - struct (created and registered by whichever module is imported first) isn't binary compatible, and the first call to `(*internals_pp)->registered_exception_translators.push_front()` chrashes.

**Comment by bmerry** [comment]
I've run into a related issue: a manylinux1 wheel (hence built with GCC 4.8) and a package built from source on Ubuntu 16.04 (GCC 5.4) with the same pybind11 version seem to have different internals layout. We should probably fold in `__GXX_ABI_VERSION__` and `__GLIBCXX__` as well.

Maybe it's also worth allowing the user to opt out of inter-module sharing entirely, to avoid such problems? Not every module needs to share with others.

**Comment by YannickJadoul** [comment]
Solved in #1549 and #1855?

If not, please reopen!
