### ISSUE TITLE
MSVC: _snprintf not in cstdio anymore

### ISSUE THREAD

**Issue by sum-catnip** [pybind/pybind11#1553]
## Issue description

pyerrors.h defines snprintf as _snprintf (if win32 is defined) because MSVC used to have those prefixes. But when i checked MSVC's cstdio the functions where no longer prefixed so they probably changed that. so any code using snprintf or vsnprintf won't compile anymore because "error C2039: '_snprintf': is not a member of 'std'".

## Reproducible example code

Just include pybind and try to use snprintf or vsnprintf with an up to date vc++ toolset.

**Comment by 10se1ucgo** [comment]
I had this issue too, just a problem with macros not being language constructs. I fixed this easily with a `#define HAVE_SNPRINTF 1` or `add_definitions(-DHAVE_SNPRINTF=1)` in my CMakeLists.txt

**Comment by sum-catnip** [comment]
yes that's what i did too but i don't think ppl should have to figure that out.

**Comment by 10se1ucgo** [comment]
I'd imagine you'd have to take that up with CPython, pyerrors.h does not come from pybind (only included by it, indirectly from including Python.h).

**Comment by sum-catnip** [comment]
ah fuck ur right ^^
