### ISSUE TITLE
const objects should not be mutable in Python

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#156]
A const object returned by a function should not be mutable from Python. Currently this is not the case if the function / method returns a `shared_ptr<const T>`.
Specifically, changing the attribute `.value` should not be allowed on an object returned by `.get_const()` in the following example, but it is.

    #include <pybind11/pybind11.h>
    
    class Test {
    public:
        explicit Test(int v) : value{v} {};
        int value {};
    
        std::shared_ptr<Test const> get_const() {
            static std::shared_ptr<Test const> instance(new Test(1));
            return instance;
        }
    };
    
    namespace py = pybind11;
    
    PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
    
    PYBIND11_PLUGIN(const_test) {
        py::module m("const_test");
    
        py::class_<Test, std::shared_ptr<Test>>(m, "Test")
            .def(py::init<int>())
            .def("get_const", &Test::get_const)
            .def_readwrite("value", &Test::value);
    
        return m.ptr();
    }

**Comment by wjakob** [comment]
Hello Pim,

pybind11 has no support for detecting/preserving the ``const``ness of values (which has no equivalent in Python, so it's actually a quite alien concept to force on Python). It's the sort of thing which is theoretically feasible, but would significantly complicate the library. I decided to draw the line on the side of simplicity in this case.

Best,
Wenzel

**Comment by wjakob** [comment]
See also 1e1f3675cdec705de23ffc2d28c8cbc7b9a65343.

**Comment by pschella** [comment]
Yes, that does seem reasonable.
Thanks!

Pim
