### ISSUE TITLE
Policy override PR clears data from STL container of custom type

### ISSUE THREAD

**Issue by Blistic** [pybind/pybind11#1561]
## Issue description

There seems to be a problem with the simple case of setting values for stl containers with custom data types. The data in the custom data type (```Foo```) is wiped after it is accessed once in Python. As shown in the minimal code below, if the ```bar.list``` line accessing the container is called, the assertion fails. (Tabbing out that line makes the assertion pass).

This issue only appeared in version 2.2.4 and I have traced the problem to PR #1455. In this case removing the [return value policy override](https://github.com/wjakob/pybind11/blob/6d9caf9365a749489bb3043364b6fe750ff06393/include/pybind11/stl.h#L164) fixes the issue (for vectors/lists at least). 

For some reason explicitly adding the copy constructor ```Foo(const Foo& other) = default;``` seems to prevent the issue as well (uncomment in the code below).  Although, I thought this would be generated automatically by the compiler in this case, so I'm not sure why it makes a difference.

Is this truly supposed to be the default behavior of pybind11? It seems like quite a simple use case and the default return value policy is producing strange results.

## Reproducible example code
test_stl.py
```python
from test_stl import Foo, Bar

bar = Bar()
bar.list = [Foo('bar')]
# If the stl container is accessed, the data is cleared. If this line is commented, the assertion passes
bar.list
assert bar.list[0].data == 'bar'
```

test_stl.cpp
```c++
#include <vector>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

struct Foo {
  std::string data;
  //Foo(const Foo& other) = default;
};

struct Bar {
  std::vector<Foo> list;
};

PYBIND11_MODULE(test_stl, m) {
    namespace py = pybind11;

    py::class_<Foo>(m, "Foo")
      .def(py::init<std::string>())
      .def_readwrite("data",&Foo::data);

    py::class_<Bar>(m, "Bar")
      .def(py::init<>())
      .def_readwrite("list",&Bar::list);
}

```

**Comment by wjakob** [comment]
This is now fixed -- apologies that it took me a while to get to this given the seriousness of the regression.
