### ISSUE TITLE
Crash when two pybind11 modules are imported

### ISSUE THREAD

**Issue by ibell** [pybind/pybind11#1562]
I don't think I can replicate this in a simple case, but I have two modules, each that operate just fine when they are the only module imported.  

Builds are inside a conda environment, with visual studio 2015 64-bit as compiler.  One package is this one: https://github.com/usnistgov/CEGO and the other one is an internal C++ library with a pybind11 wrapper.

When they are both imported, like so:
``` python
import PyCEGO
import VLEIsoTracer as vle
```

I get a crash:

![image](https://user-images.githubusercontent.com/1859947/46672000-a070ff80-cbd6-11e8-82fc-9cfbf6d384fe.png)

**Comment by ibell** [comment]
It seems like one library was built with commit 2bde61500d0719c344a238cd11124d0755370f36 and the other one was built with 51d18aa252332e883c61b7cb45ed317146b372ce .  When I sync both to master, there is no import crash.  It seems like a bug that any modules compiled with pybind11 with two different commits result in a crash.

**Comment by YannickJadoul** [comment]
This was improved/fixed in #1012.
Meanwhile, the two commits you mention were not official releases, so you're it's not really a surprise that things don't cooperate well, then.
