### ISSUE TITLE
"__assign__" calls move-constructor instead of copy-constructor

### ISSUE THREAD

**Issue by amastrobera** [pybind/pybind11#1564]
I have a *container class* (vector of something), that I converted in python using pybind11.   

In python, I want to be able to take a *reference of one* of the items in that vector, read or write that item's id, and have the original vector in the container class updated (see the python code). 

I read that pybind11 chooses the best option (move or copy) for me; in fact the compiler demands me to declare the move-operator= and move-constructor. **I try to force pybind11 to use the copy-operator= instead of the move-operator=** but I failed to do that. 

cpp classes
```
// mycppmodule.h
#include <vector>
#include <iostream>
#ifndef _HEAD_
#def _HEAD_
class C {
   C() = default;
   ~C() = default;
   C(C const& cp) { 
      std::cout << "copy constructor" << std::endl; 
      *this = cp;
   } 
   C& operator=(C const& cp) { 
       std::cout << "copy assignment op" << std::endl; 
       if (this != &cp) { mId = cp.mId; } 
      return *this;
    }; 
  //pybind11 wants these 
   C(C&&) { std::cout << "move constructor" << std::endl; } 
   C& operator=(C&&) { std::cout << "move assigment op" << std::endl; }; 

   std::string getId() { return mId; }
   void setId(std::string const& id) { mId = id;}

private:
   std::string mId;
};

class Container {
    std::vector<C>& getCs() {return mCs;}
    std::vector<C> const& getCs() const { return mCs;}
    void addC(C const& c) { mCs.push_back(c);}
private:
    std::vector<C> mCs;
};
#endif //_HEAD_
```

python code. 
```
from mypymodule import C, Container

cont = Container()
c = C()
c.id = "hello"
cont.addC(c) # correctly copy constructor is called :) 
print ("old id  was %s" % cont.cs[0].id) # "hello"

ref = cont.cs[0]  # move assignment is called ! damn
ref.id = "bonjour"

print ("new id  is %s" % cont.cs[0].id) # empty string (it was moved)
print ("the moved id  is here %s" % cont.cs[0].id) # "bonjour"
```

I apply this code to bind it. See that I explicitly tell "__assignment__" to call the copy operator=.

```
#include <mycppmodule.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
namespace py = pybind11;

PYBIND11_MODULE("mypymodule", m) {
    py::class_<C>(m, "C")
        .def(py::init<>())
        .def("__assign__", (C& (C::*) (C const&)) &C::operator=)
        .def_property("id", &C::getId, &C::setId)
    ;
    py::class_<Container>(m, "Container")
        .def(py::init<>())
        .def("addC", &Container::addC)
        .def("cs", (std::vector<C> const& (Container::*)() const) &Container::getCs)
        .def("cs", (std::vector<C>& (Container::*)()) &Container::getCs)
    ;
}
```

I wrote this for you. I apologies in advance for _typos_.

**Comment by amastrobera** [comment]
**update**: I managed to avoid the **move** problem with a simple opaque container. 
```
#include <pybind11/stl_bind.h>

PYBIND11_MAKE_OPAQUE(std::vector<C>);

// inside the PYBIND11_MODULE ... 
{
   py::bind_vector<std::vector<C>>(m, "VectorC");
}
```

Now, each time I take the object from the list like this `newc = cont.cs()[0]` I get a copy out of it. I am happy, but I still want to modify `newc` and have `cont.cs()[0]` updated (as normally python does when you use a list of objects. 

The docs doesn't have much about the opaque containers. **can you tell me how to overload the __getitem__ function of my opaque `VectorC`** ?

**Comment by bstaletic** [comment]
I think you can use `.def("getitem"...)` on the `bind_vector` class.

**Comment by amastrobera** [comment]
> I think you can use `.def("getitem"...)` on the `bind_vector` class.

I thought so too. i did something like that, and it doesn't change the behaviour. the item is still copied, rather than referenced

```
py::bind_vector<std::vector<C>>(m, "VectorC") 
    .def("__getitem__", [](std::vector<C>& v, size_t index) { return &v[index];})
;
```

**Comment by bstaletic** [comment]
`std::cout` and similar don't play well with python's `sys.stdout` and `sys.stderr`, so it's not a wonder why it didn't get called. Take a look at [this](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/utilities.html#capturing-standard-output-from-ostream) or use `py::print`.

**Comment by amastrobera** [comment]
managed with this (i suspected for long time this was it):
c++ 
```
class Container {
    ///stuff 
    std::vector<C>& getCs();
    std::vector<C> const& getCs() const;
};
```
bindings 
```
py::class_<Container>(m, "Container")
     /// stuff
    .def_property("cs", 
                     (VectorC const& (Container::*)() const) &Container::getCs,
                     (VectorC & (Container::*)() ) &Container::getCs ) 
;
```

**Comment by bstaletic** [comment]
I don't think you can bind private properties else, what's the point of them being private?

**Comment by amastrobera** [comment]
> I don't think you can bind private properties else, what's the point of them being private?

I don't like the idea to have to write a const-getter and a non-const getter in c++ just for this binding. 
```
    std::vector<C>& getCs();
    std::vector<C> const& getCs() const;
```
It seems that Scott Meyers [approved](https://stackoverflow.com/questions/856542/elegant-solution-to-duplicate-const-and-non-const-getters) this practice and there is a `std::as_const` in c++17.... So perhaps it is not a problem at all. It does force the design to be this way thought.

**Comment by bstaletic** [comment]
It sounds to me like you actually want that property to be public.
