### ISSUE TITLE
returning un-binded classes of external c++ libraries

### ISSUE THREAD

**Issue by amastrobera** [pybind/pybind11#1565]
I have class that returns an OGR geometry from [gdal](https://www.gdal.org/ogr__geometry_8h.html) library. (Roughly like this)

```
#include <ogr_geometry.h>
#include <memory>

class MyShape{
public:
      MyShape() = default;
      ~MyShape() = default;
      OGRGeometry const& getGeom() const { return *mGeom; }
      void setGeom(std::string const& txt) { mGeom.reset( <createUniquePtrGeomFromText(tx)>); }
private: 
    std::unique_ptr<OGRGeometry, <some_deleter> > mGeom;
};
```
with bindings 
```
py::class_<MyShape>(m, "MyShape") 
   .def(py::init<>())
   .def_property("geom", &MyShape::getGeom, &MyShape::setGeom)
;
```
If I use it in python, python does not know what the ogr_geometry returned value is. 
```
m = MyShape()
m.geom = "POINT (1 1)" # all good
g = m.geom  # expecting the "reference_internal" but TypeError here 
print "g is a %s " % type(g) # never reached, should be "g is a <class 'xxx.OGRPoint'>"
```
TypeError: Unable to convert function return value to a Python type! The signature was (arg0: MyShape) -> OGRGeometry

I know that python has a library that derives exactly from the same c++ one, and it is called [py-gdal](https://pcjericks.github.io/py-gdalogr-cookbook/geometry.html) . 

Is it possible to make my python bindings return an object from this library here ?
```
from osgeo import ogr # the python equivalent, in question, already exists
import mymodule.MyShape

m = MyShape()
m.geom = "POINT (1 1)" 
g = m.geom 
print "g is a %s " % type(g)  # "g is a <'osgeo.ogr.Geometry'>"
```

If not, how do I make the returned value consisten with py-gdal ?

**Comment by amastrobera** [comment]
this does the trick
(bindings file)
```
m.def("makeGeometry",[](std::string const& text) {
    py::object ogr = py::module::import("osgeo").attr("ogr");
    return ogr.attr("<make a shape function from ogr lib>")(text);
});
```

**Comment by jamie-sgro** [comment]
If you don't mind me asking @amastrobera, how did you go about including ogr_geometry.h into your .cpp file?
