### ISSUE TITLE
find_package() not working, cant include the lib.

### ISSUE THREAD

**Issue by Dariusz1989** [pybind/pybind11#1569]
Hey

This is a little "noobish" question but I have been struggling with it for a while now. I'm trying to add pybind11 to my c++ project but I cant get past through cmake setup.

Here are the steps that I did
Download pybind
Extract it to my externalLib/pybind/pybind11 folder
Add environment path helper to find pybind so its something like ${externalLibs}/pybind/pybind11
and then did this cmake as shown below

`
SET(PYBIND_LIB ${externalLibs}/pybind/pybind11)
set(pybind11_DIR ${PYBIND_LIB}/tools)
find_package(pybind11 REQUIRED)
`

And that gives me this error : 

`
CMake Error at CMakeLists.txt:65 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
`

I even tried this
`
find_package(pybind11 REQUIRED PATHS "C:/dev/externalLibs/pybind/pybind11/tools")
`
And he still does not find the stuff?!

What am I doing wrong here?!

**Comment by Dariusz1989** [comment]
I went over the directory again, slower... I found out that the file
pybind11Config.cmake
was in fact named
pybind11Config.cmake.in
so I renamed it, now it goes through but crashes here : 
`
  Parse error.  Expected a command name, got unquoted argument with text
  "@PACKAGE_INIT@".
Call Stack (most recent call first):
  CMakeLists.txt:65 (find_package
`

**Comment by vanossj** [comment]
is `${externalLibs}` in your project? you could use `add_subdirectory(${externalLibs}/pybind/pybind11)` instead of `find_package`

**Comment by chongkong** [comment]
`Findpybind11.cmake.in` and `pybind11Config.cmake.in` are baked into `Findpybind11.cmake` and `pybind11Config.cmake` once you build the project.

``` shell
$ mkdir build
$ cd build
$ cmake ..
$ make check -j 4
```

After then you will find `pybind11Config.cmake` file in `build/` directory. The problem is I don't know what is the right way to add the baked config.cmake to make it available from my project it via `find_package`. I tried to set `pybind11_DIR` or add the path to the `CMAKE_MODULE_PATH`, but it is quite cumbersome.

**Comment by YannickJadoul** [comment]
Thanks for answering, @kabukunz!
