### ISSUE TITLE
TypeError when working with object across modules

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#157]
When a type `MyType` is wrapped in one module and subsequently used as an argument for a function in a different module a TypeError is raised.

Specifically the attached basic test gives the following output:

    In [1]: import amod
    
    In [2]: a=amod.A()
    
    In [3]: mt=amod.MyType()
    
    In [4]: a.test(mt)
    Out[4]: 0L
    
    In [5]: import bmod
    
    In [6]: b=bmod.B()
    
    In [7]: b.test(mt)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-7-7aa8288574de> in <module>()
    ----> 1 b.test(mt)
    
    TypeError: Incompatible function arguments. The following argument types are supported:
        1. (bmod.B, std::__1::shared_ptr<mynamespace::MyType>) -> int

[multitest.tar.gz](https://github.com/pybind/pybind11/files/209354/multitest.tar.gz)

Checking where this exception is created and specifically checking the content of `registered_types_cpp` does indicate the correct type `MyType` is visible from `bmod`.
Which I guess it would have to be for the error message to be printed...
So I am a little confused as to what is going wrong. Possibly / probably something stupid on my part.

**Comment by wjakob** [comment]
Maybe because you forgot
```
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
```
in the other file?

**Comment by wjakob** [comment]
also, you can't have a namespace around the PYBIND11_PLUGIN declaration.

**Comment by pschella** [comment]
I did not put `PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);` in the file indeed, but putting it in doesn't seem to make a difference. Neither does removing of the namespaces in `a.cpp` and `b.cpp`. In all other tests the namespaces seem to work fine actually.

**Comment by wjakob** [comment]
What OS/Compiler + version are you using?

**Comment by wjakob** [comment]
One more thing: PYBIND11_DECLARE_HOLDER_TYPE must be declared at the top level -- I forgot whether you were doing that (i.e. not in a namespace).

**Comment by pschella** [comment]
OSX El Capitan 10.11.4.

Setuptools seems to pick up `g++`.

`$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**Comment by pschella** [comment]
In `a.cpp`:

    #include <pybind11/pybind11.h>
    
    #include "mytype.h"
    
    namespace py = pybind11;
    
    PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
        
    class A {
    };
    
    PYBIND11_PLUGIN(amod) {
        py::module m("amod", "module a");
    
        py::class_<mynamespace::MyType, std::shared_ptr<mynamespace::MyType>>(m, "MyType")
            .def(py::init<>());
    
        py::class_<A>(m, "A")
            .def(py::init<>())
            .def("test", [](A &ds, std::shared_ptr<mynamespace::MyType> &t) { return 0; });
        return m.ptr();
    }
    
and in `b.cpp`:

    #include <pybind11/pybind11.h>
    
    #include "mytype.h"
    
    namespace py = pybind11;
    
    PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
        
    class B {
    };
    
    PYBIND11_PLUGIN(bmod) {
        py::module m("bmod", "module b");
    
        py::class_<B>(m, "B")
            .def(py::init<>())
            .def("test", [](B &ds, std::shared_ptr<mynamespace::MyType> &t) { return 0; });
    
        return m.ptr();
    }

**Comment by wjakob** [comment]
Can't reproduce with your example.
```
% python2.7                                                                                                                                                                          Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import amod
>>> import bmod
>>> amod.A().test(amod.MyType())
0L
>>> bmod.B().test(amod.MyType())
```
This is on OSX 10.11.4. I tried both the current Clang bundled with Xcode (``Apple LLVM version 7.3.0 (clang-703.0.29)``) and GCC (``gcc version 5.3.0 (Homebrew gcc 5.3.0)``).

**Comment by pschella** [comment]
Hmm, that is strange. Did you use my setup.py or are your build settings different?

**Comment by wjakob** [comment]
No I did not use setup.py. It is probably a default symbol visibility issue (setup.py specifies -fvisibility=hidden). What happens when you annotate your custom type with  __attribute__ ((visibility ("default"))) ?

**Comment by wjakob** [comment]
Note: double underscores around "attribute" :)

**Comment by pschella** [comment]
Ok, so that was stupid. The example setuptools script for pybind11 that I got from https://github.com/pybind/pbtest has an explicit `-fvisibility=hidden` in it. If I change that to `-fvisibility=default` it works. No idea why the example includes this tough.

**Comment by wjakob** [comment]
This is really important to get small binaries..

**Comment by pschella** [comment]
Ah, of course. But it is a little confusing given that it inhibits some of the functionality. Perhaps a note in the section about "Partitioning code over multiple extension modules"? Anyway, thanks again for your help! I'm closing this issue now since it seems to be resolved.

**Comment by pschella** [comment]
Actually it only seems to work as long as the wrapped class is not polymorphic. If in the example `MyType` contains a virtual function (even if it's just the destructor) the `TypeError` is back again.

**Comment by wjakob** [comment]
I cannot reproduce your issue (added a virtual method and everything still works nicely on GCC + Clang).

**Comment by wjakob** [comment]
(I added a note to the documentation regarding the visibility flag)

**Comment by pschella** [comment]
Hmm, I don't quite understand this. In the test if I simply change:

    #ifndef MYTYPE_H
    #define MYTYPE_H
    
    #include <string>
    
    class MyType {
    public:
        MyType() = default;
        std::string name{"hello"};
        std::string get_name() const;
        int f();
    };
    
    #endif // MYTYPE_H

to

    #ifndef MYTYPE_H
    #define MYTYPE_H
    
    #include <string>
    
    class MyType {
    public:
        MyType() = default;
        std::string name{"hello"};
        std::string get_name() const;
        virtual int f();
    };
    
    #endif // MYTYPE_H

(i.e. only adding `virtual`). The test:

    import amod
    import bmod
    
    a=amod.A()
    
    mt=amod.MyType()
    
    print "testing A"
    a.test(mt)
    
    b=bmod.B()
    
    print "testing B"
    b.test(mt)

suddenly fails with:

    TypeError: Incompatible function arguments. The following argument types are supported:
        1. (bmod.B, MyType) -> int

where `a.cpp` is:

    #include <pybind11/pybind11.h>    
    #include "mytype.h"
    
    namespace py = pybind11;
    
    PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
        
    class A {
    };
    
    PYBIND11_PLUGIN(amod) {
        py::module m("amod", "module a");
    
        py::class_<MyType, std::shared_ptr<MyType>>(m, "MyType")
            .def(py::init<>());
    
        py::class_<A>(m, "A")
            .def(py::init<>())
            .def("test", [](A &ds, std::shared_ptr<MyType> &t) { return 0; });
        return m.ptr();
    }

and `b.cpp` is

    #include <pybind11/pybind11.h>
    #include "mytype.h"
    
    namespace py = pybind11;
    
    PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
    
    class B {
    };
    
    PYBIND11_PLUGIN(bmod) {
        py::module m("bmod", "module b");
    
        py::class_<B>(m, "B")
            .def(py::init<>())
            .def("test", [](B &ds, std::shared_ptr<MyType> &t) { return 0; });
    
        return m.ptr();
    }

**Comment by wjakob** [comment]
What are the compilation flags?

**Comment by wjakob** [comment]
I can't even compile that:
```
 % g++ bmod.cpp -o bmod.so -std=c++11 -I include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -shared -lpython                                        [INS]
Undefined symbols for architecture x86_64:
  "typeinfo for MyType", referenced from:
      pybind11::detail::type_caster<MyType, void>::type_caster() in bmod-d4229d.o
      l__ZZN8pybind116detail1_I6MyTypeEENS0_5descrEvE5types in bmod-d4229d.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

You have to link some shared library which contains the virtual table for that type, otherwise I don't see how this is supposed to work.

**Comment by pschella** [comment]
In the example I left out the, rather trivial, class definitions.
But the problem was indeed in the linking. Or more specifically in _not_ linking.
Each module was building the source for ``MyType`` separately.
Moving that to a shared library and linking both ``amod`` and ``bmod`` to it solved the problem.

**Comment by wjakob** [comment]
Ok, that's good to hear.
