### ISSUE TITLE
Getting an object C++ type_info

### ISSUE THREAD

**Issue by nbentyNV** [pybind/pybind11#1572]
I'm writing a class which displays a GUI for every element in a `pybind11::dict` object.
In order to correctly display the UI elements, I need to know the underlying C++ type (either `type_info` or `type_index`.

I tried the following:
```c++
            PyObject* pObj = mMap["u8"].ptr(); // u8 is a uint8_t
            PyTypeObject* pType = pObj->ob_type; // pType->tp_name == `int`
            auto pType = pybind11::detail::get_type_info(f->second.ptr()->ob_type);
```
That doesn't work - `pType` is nullptr, which is not what I expected considering `pType` is valid.
Am I doing something wrong or is that a pybind11 issue?

**Comment by YannickJadoul** [comment]
`pybind11::detail::get_type_info` is not part of pybind11's public API. pybind11 doesn't support mapping back from Python types to C++ types (as this is not always possible), and `pybind11::detail::get_type_info` is only meant for internal use for custom types bound through `class_`, so it will not work for `int`.

Even more so: what's the corresponding type to a Python `int`? A C++ `uint8_t` (as you show) or a `int` or a `long` or a `uint32_t` or ... ?

You'll need to figure out a custom solution for yourself; maybe creating your own mapping from Python types to C++ types, or maybe storing the type in each object with a `py::capsule` or so.
