### ISSUE TITLE
FindPythonLibsNew.cmake bug on Windows

### ISSUE THREAD

**Issue by suzuryo3893** [pybind/pybind11#1574]
I found a bug on ``tools/FindPythonLibsNew.cmake``, when I used Windows.
https://github.com/pybind/pybind11/blob/28cb6764fc6f66f5c678466c9af525f1dd6f8cc8/tools/FindPythonLibsNew.cmake#L122-L124 repots error in some cases.

For example, when I tried below on my python according to L77-L88;

```
from distutils import sysconfig as s;import sys;import struct;print('.'.join(str(v) for v in sys.version_info));print(sys.prefix);print(s.get_python_inc(plat_specific=True));print(s.get_python_lib(plat_specific=True));print(s.get_config_var('SO'));print(hasattr(sys, 'gettotalrefcount')+0);print(struct.calcsize('@P'));print(s.get_config_var('LDVERSION') or s.get_config_var('VERSION'));print(s.get_config_var('LIBDIR') or '');print(s.get_config_var('MULTIARCH') or '');
```

it output

```
3.6.5.final.0
C:\(some locations)\Python36\
C:\(some locations)\Python36\include
C:\(some locations)\Python36\Lib\site-packages
.cp36-win_amd64.pyd
0
8
36


```

The second line has a terminal backslash. It makes ``list`` command on CMake failed to purse each line.
As a result, ``PYTHON_PREFIX`` is set to ``C:\(some locations)\Python36C:\(some locations)\Python36\include``, and ``PYTHON_SIZEOF_VOID_P`` is set to 36. So the code reports "Python config failure: Python is 266-bit".

A considerable fixation is to replace backslash to slash before starting REPLACE.

```cmake
# Convert the process output into a list
+ if(WIN32)
+     string(REGEX REPLACE "\\\\" "/" _PYTHON_VALUES ${_PYTHON_VALUES})
+ endif()
string(REGEX REPLACE ";" "\\\\;" _PYTHON_VALUES ${_PYTHON_VALUES})
string(REGEX REPLACE "\n" ";" _PYTHON_VALUES ${_PYTHON_VALUES})
list(GET _PYTHON_VALUES 0 _PYTHON_VERSION_LIST)
```

**Comment by wjakob** [comment]
@suzuryo3893: That sounds like a good solution. Could you create a PR with this change so that the continuous integration servers can verify the change on all platforms?
