### ISSUE TITLE
For Python subclass, forgetting to call C++ superclass `__init__` constructor is painful

### ISSUE THREAD

**Issue by EricCousineau-TRI** [pybind/pybind11#1577]
While it is noted here in the docs:
https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python
it is still sometimes easy to forget. If it were somehow possible, it'd be nice to robustly detect access to unconstructed base classes. (... though it may be a big performance penalty, so I'm fine with this being closed as "Not a Problem")

Example failure case from above:
```python
class Dachschund(Dog):
    def __init__(self, name):
        # Oops!
        self.name = name

    def bark(self):
        return "yap!"

d = Dog("Sir Schnitzel")
d.go(10)  # Nuts!
```

Had run into it when writing [this example](https://github.com/RobotLocomotion/drake/issues/9702#issuecomment-432826511), and then felt dumb once I realized what the problem was.

**Comment by bstaletic** [comment]
Considering that we've merged https://github.com/pybind/pybind11/pull/2152, can we close this now?

**Comment by YannickJadoul** [comment]
I say we can.
