### ISSUE TITLE
Add python code for retrieving the header file path

### ISSUE THREAD

**Issue by wjakob** [pybind/pybind11#158]
[see pbtest PR]

**Comment by wjakob** [comment]
cc @SylvainCorlay

**Comment by SylvainCorlay** [comment]
note: before Python 3.4, pip is not part of the python standard library. If we use `pip.locations`, it should at least be imported locally in the `get_include` function rather than at a module level.

**Comment by SylvainCorlay** [comment]
> Note: before Python 3.4, pip is not part of the python standard library (so we would be making it a dependency of pybind11, unless there is an alternative to pip.locations.distutils_scheme).

Python packaging is such a mess...

**Comment by wjakob** [comment]
Any preferences regarding the syntax/location of the code from your end? I was thinking of adding
```
try:
    from pip import locations, os
    __include_paths__ = [os.path.dirname(
        locations.distutils_scheme('pybind11')['headers'])]
except ImportError:
    __include_paths__ = []
```
to ``pybind11/__version__.py``.

**Comment by SylvainCorlay** [comment]
I was rather hoping we would have something that would not require `pip` at all. I looked at the implementation of `distutils_scheme` and it is quite complex though...

Regarding the case of import error, get_include should return `'include'`.

**Comment by wjakob** [comment]
I had the same reaction to ``distutils_scheme``. Unless there is a better alternative, I'll commit that with your ``'include'`` fix.

**Comment by wjakob** [comment]
Thoughts? Also, would you make it a static variable __include_paths__, or a function get_includes? You have more experience with this kind of packaging stuff and conventions in various libraries, so I'll defer to you :)

**Comment by SylvainCorlay** [comment]
I don't have so much experience. People are familiar with numpy's `get_include`...

The brew-installed python thing that you brought up in https://github.com/pybind/pbtest/pull/6 is not something I could find any documentation on. I will probably open an issue in distutils and simply ask upstream...
