### ISSUE TITLE
type_caster::cast const issue

### ISSUE THREAD

**Issue by soulslicer** [pybind/pybind11#1580]
## Issue description

I am trying to write code to generate a simple C++ object to Python/Numpy caster
```

        static handle cast(const op::Array<float> &m, return_value_policy, handle defval)
        {
            std::string format = format_descriptor<float>::format();

            return array(buffer_info(
                m.getPtr(),     /* Pointer to buffer */
                sizeof(float),       /* Size of one scalar */
                format,         /* Python struct-style format descriptor */
                m.getSize().size(),            /* Number of dimensions */
                m.getSize(),      /* Buffer dimensions */
                m.getStride()         /* Strides (in bytes) for each index */
                )).release();
        }

```

However, when I compile it, it complains that m.getPtr() has to be a const ptr, since the object we pass in from the cast is a const object. 

```
pybind11/pybind11.h:155: error: no matching function for call to ‘pybind11::detail::type_caster<op::Array<float> >::cast(const op::Array<float>&, pybind11::return_value_policy&, pybind11::handle&)’
                 std::move(args_converter).template call<Return, Guard>(cap->f), policy, call.parent);
                                                                                                    ^

```
If i try to make the handle cast input non const, then it complains saying such a callback doesnt exist. 

```
error: passing ‘const op::Array<float>’ as ‘this’ argument of ‘T* op::Array<T>::getPtr() [with T = float]’ discards qualifiers [-fpermissive]
             float* ptr = const_cast<float*>(m.getPtr());
                                                      ^
```

How do we handle this

**Comment by YannickJadoul** [comment]
If this is still an issue, we're going to need some more context. What's the full first error you get? Normally, passing a non-`const` object to a `const` reference, shouldn't be a problem at all. So the first error is probably longer, specifying why it can't match.

The second error is not related to pybind11, bu to this `op::Array<float>` interface. So I cannot say anything about that either.

Please reopen if this is still a problem (or come to [Gitter](https://gitter.im/pybind/Lobby)).
