### ISSUE TITLE
when creating .so file and pybind11::object set as function's args or retval, i get "undefined reference error"

### ISSUE THREAD

**Issue by ZQPei** [pybind/pybind11#1583]
### To be specific and simple, say i have three files :
============================================
---------------
#### human.py
---------------
```python
class Human:
    def __init__(self, name):
        self.name = name
        self.age = 10

    def get_age(self):
        return self.age
```

----------------
#### human.h
----------------
```
#include <pybind11/embed.h>

namespace py=pybind11;

void print_age(py::object human);
```

----------------
#### human.cpp
----------------
```
#include "human.h"

void print_age(py::object human){
    auto res = human.attr("get_age") ();
    py::print("age: ",res);
}

```
--------------
#### test.cpp
--------------
```
#include "human.h"

int main(){
    py::scoped_interpreter guard{};
    py::object jack = py::module::import("human").attr("Human")("Jack");
    print_age(jack);
    return 0;
}
```
=========================================

Now, if i compile human.h human.cpp, test.cpp those three files at the same time, pybind11 works fine.
However, if i first compile human.h human.cpp to libhuman.so with command
```bash
g++ -std=c++11 -fPIC -shared human.cpp -o libhuman.so -I/home/pzq/anaconda3/include/python3.6m 
-L/home/pzq/anaconda3/lib -lpython3.6m
```
and then compile test.cpp as test.o and then link .so file with command
```bash
g++ -std=c++11 test.cpp -o test -I/home/pzq/anaconda3/include/python3.6m -L/home/pzq/anaconda3/lib -L. -lpython3.6m -lhuman
```
or
```bash
g++ -std=c++11 -c test.cpp -o test.o -I/home/pzq/anaconda3/include/python3.6m
g++ test.o -o test -L/home/pzq/anaconda3/lib -L. -lpython3.6m -lhuman
```
,and i got error :
```
test.o: In function `main':
test.cpp:(.text+0x108): undefined reference to `print_age(pybind11::object)'
```

if `py::object` used as retval, i encounted the same problem.
it seems like `pybind11::object` cannot be used as args or retval, is it? Or something else?
Can anybody solve this problem for me, thanks!!!

**Comment by bstaletic** [comment]
> `g++ test.o libhuman.so -o test -L/home/pzq/anaconda3/lib -lpython3.6m`

That's not how you link `test.o` against `libhuman.so`. You're supposed to link it thte same way you linked `libpython3.6m.so` - `-L. -lhuman`.

**Comment by ZQPei** [comment]
> > `g++ test.o libhuman.so -o test -L/home/pzq/anaconda3/lib -lpython3.6m`
> 
> That's not how you link `test.o` against `libhuman.so`. You're supposed to link it thte same way you linked `libpython3.6m.so` - `-L. -lhuman`.

Thanks for your reply! 
In fact, I have tried using `-L. -lhuman`, and it's still not working.
I think you will get the same error if you try to compile them.

**Comment by bstaletic** [comment]
Okay, this was subtle. Change `human.h` to:
```C++
#include <pybind11/embed.h>

namespace py=pybind11;

PYBIND11_EXPORT void print_age(py::object human);
```

This will get you going - the `test` executable will be generated correctly.
To see why `PYBIND11_EXPORT` was needed, search the docs for `PYBIND11_EXPORT` and `-fvisibility=hidden`.

**Comment by bstaletic** [comment]
> So the py::object is default visibility=hidden, is it?

Yes. Basically pybind will make you compile with `-fvisibility=hidden` and then expose only what's necessary.
