### ISSUE TITLE
Windows/Cygwin - Can't use pybind11 - make error

### ISSUE THREAD

**Issue by gr0mph** [pybind/pybind11#1586]
**Hi,**

I want to integrate in a project the practical tool pybind11. My work environment is windows.

I have write a stackoverflow topic about this:
[StackOverflow](https://stackoverflow.com/questions/53115907/windows-cygwin-cant-use-pybind11-make-error)

**Has anyone ever compiled pybind11 with cygwin?**

**thank you very much in advance**

**Comment by YannickJadoul** [comment]
Not clear what's going wrong in the question. The StackOverflow question got answered as well, so I'll consider this solved.

Do reopen and explain what exactly the problem is, if there is still a problem.
