### ISSUE TITLE
type_caster support for std::any

### ISSUE THREAD

**Issue by hkalodner** [pybind/pybind11#1590]
## Issue description

pybind11 provides support for most STL containers including `std::optional` and `std::variant` introduced in c++17. However there is no support for the fully generic `std::any` type which is a fully type-erased holder for any underlying type, essentially a modern void* with ownership semantics.

It would be great if there was some generic mechanism for casting this type. `std::any` does have `type` method which provides access to the `std::type_info` of the underlying type, but I'm not sure if this is enough to provide casting support.

It would be great to know whether this is possible. If not, it might make sense to state this on the STL support page.

Thanks!

**Comment by Xfel** [comment]
`std::any` doesn't give you access to it's contents unless you know the content's exact type. So, the only way to implement the any typecaster would be to add code for all other possible typecasters and select them using a large if-elseif-structure. That's not feasible, since there is no generic way to get all template instantiations of type_caster.

**Comment by YannickJadoul** [comment]
Thanks for answering this, @Xfel!



> It would be great if there was some generic mechanism for casting this type. `std::any` does have `type` method which provides access to the `std::type_info` of the underlying type, but I'm not sure if this is enough to provide casting support.

Maybe that would work for standard `py::class_` registered classes, but it would still have issues with custom casters (e.g. `stl.h` or primitive types), that don't have their `std::type_info` registered in pybind11's internals. So I think @Xfel's suggestion is better.

If anyone feels like trying this out, do open a PR and we can discuss is further.
