### ISSUE TITLE
Potential collision with C++20 `module` keyword

### ISSUE THREAD

**Issue by dalboris** [pybind/pybind11#1593]
Hi everyone,

I just wanted to bring to your attention that the name `module` is likely to become a [keyword](https://en.cppreference.com/w/cpp/keyword) in C++20, which I believe would cause a collision with `pybind11::module`. Maybe you already know this, maybe not, but I thought I'd better write something here just in case.

Here is an interesting discussion from Vulkan facing similar problems: https://github.com/KhronosGroup/Vulkan-Docs/issues/568

Related links:
https://www.reddit.com/r/cpp/comments/4b9qru/what_exactly_is_the_proposed_module_system_how/
https://clang.llvm.org/docs/Modules.html

**Comment by EricCousineau-TRI** [comment]
I guess this may not contribute much, but future proofing the library at least should be simple enough:
```c++
class module_ { ... };

#if !defined(PYBIND11_CPP20)
using module = module;
#endif
```

**Comment by EricCousineau-TRI** [comment]
Thanks! And oops! Corrected.

**Comment by dalboris** [comment]
Closing this (see #1639).
