### ISSUE TITLE
Is it possible to bind Python with Aws-cpp-sdk using Pybind11? 

### ISSUE THREAD

**Issue by NatxoMendez** [pybind/pybind11#1594]
My code binds Python with the S3 module of Aws-cpp-sdk. It compiles, but I keep getting 

> Error in `python3': free(): invalid pointer: 0x00007fb16afe6aa0  

My code is based on an aws sdk c++ [example](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/get_object.cpp).

The error occurs here:

`object_request.WithBucket(bucket_name).WithKey(key_name);`

**Comment by YannickJadoul** [comment]
> My code is based on an aws sdk c++ [example](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/cpp/example_code/s3/get_object.cpp).

I see no pybind11 in your example.

We can't help anything if you don't provide a minimal, compiling example that demonstrates what goes wrong.

Please reopen if this is still an issue. But if it is just a question, please ask on [Gitter](https://gitter.im/pybind/Lobby) first.
