### ISSUE TITLE
FAQ suggestion

### ISSUE THREAD

**Issue by akroizer** [pybind/pybind11#1596]
Hello,
I was struggling with the error “ImportError: dynamic module does not define init function”. The[ FAQ](https://pybind11.readthedocs.io/en/latest/faq.html) suggested it might be a problem in python version so I looked in the direction for a while, however this was not the issue. After digging some more
I found [this](https://stackoverflow.com/questions/45054860/extending-c-to-python-using-pybind11?rq=1) outdated stackoverflow issue that hinted at the right direction - the reason was that the module name specified in PYBIND11_MODULE was different than the shared library I was creating.
I suggest to add this to the FAQ for future reference.

**Comment by wjakob** [comment]
Sure, can you create a PR for the doc change?

**Comment by akroizer** [comment]
Thanks, Done https://github.com/pybind/pybind11/pull/1606
