### ISSUE TITLE
How to specify python compiler/path?

### ISSUE THREAD

**Issue by Dariusz1989** [pybind/pybind11#1597]
Hey

I'm trying to wrap my head around pybind11 more and more lately. 

I was never able to run it via find_package(pybind11) or anything like that, instead I just included the lib in mr project via INCLUDE_DIRECTORIES(pathToPyBindDir) and just call

```
#include <pybind11.h>
#include <include/pybind11/embed.h>

namespace py = pybind11;
```

Seems to work so far. But now I need to specify python. As I don't want to use the default windows one located in program files, but in my custom folder so that when I deploy the app. The python comes with it. More or less.

Can any1 hint out how I can set this up ?

TIA

**Comment by YannickJadoul** [comment]
Try passing `PYTHON_EXECUTABLE` to CMake (or setting it before `add_subdirectory(pybind11)`): https://pybind11.readthedocs.io/en/stable/compiling.html#configuration-variables
