### ISSUE TITLE
static py::object in C++ function may cause Segfault on exit

### ISSUE THREAD

**Issue by lns** [pybind/pybind11#1598]
## Issue description

When we have a `py::object` as a static variable in a C++ function, it seemly causes a Segmentation fault when the python program exits. This happens under Python3 but not under Python2 in my case.

## Reproducible example code

In `example.cpp`:
```c++
#include <pybind11/pybind11.h>

namespace py = pybind11;

py::object last(py::object obj) {
  static py::object stored = obj;
  py::object ret = stored;
  stored = obj;
  return ret;
}

PYBIND11_MODULE(example, m) {
  m.def("last", &last);
}
```
An `example.so` is compiled with
```bash
g++ -std=c++11 -O3 -Wall -shared -fPIC -I/path_of_latest_pybind11/include `python3 -m pybind11 --includes` example.cpp -o example.so
```
with latest pybind11 from github installed. The following python program exits with Segmentation fault, when we pass a python object as the argument of `last()` under python3 (Python 3.4.5 (default, Feb 27 2018, 15:10:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux).
```python
from example import last
a = last( [] )
```
The program exits smoothly under Python2, or we pass a number/string as the argument of `last()` under Python3.  I am not sure about the causes of the problem. Any help will be appreciated. Thanks!

**Comment by bstaletic** [comment]
I'm assuming that it's because at the time your program is about to exit and is cleaning up static data, your interpreter is already gone,  so it's not legal to call `py::object::~object()`. But you're saying it exits smoothly on python2, which is surprising to me.

**Comment by lns** [comment]
Thank you for clarifying this! Do you have suggestions to implement this correctly? It seems that if we can cleaning up static C++ data *before* destroying python interpreter then it will exits safely?

**Comment by anntzer** [comment]
Looks related to https://github.com/pybind/pybind11/issues/1493.

**Comment by uentity** [comment]
@lns why do you ever need static `py::object`?
Answering your question - yes, I think you can safely destroy your objects using Python's `atexit`.

**Comment by lns** [comment]
The static property is not a must but for convenience. I used to store the global information about a customized dynamic data structure in a static `py::object`. Now according to the discussion, having a static `py:object` will cause some troubles, so I am trying to wrap this info instead in a class/singleton (which will be cleaned before python's exit) and so far it works as well (with a few extra lines at the python side). Again, thank you for your constructive comments!
