### ISSUE TITLE
Passing by value

### ISSUE THREAD

**Issue by JendaPlhak** [pybind/pybind11#161]
Assume we have following c++ code -

```
#include <pybind11/pybind11.h>
#include <iostream>


struct Foo {
    std::string a;
};

void show(Foo f) {
    std::cout << f.a << std::endl;
}

namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

    m.def("show", &show, "Prints a");
    py::class_<Foo>(m, "Foo")
    .def_readwrite("a",    &Foo::a);

    return m.ptr();
}
```

And very simple python script where we create Bird structure and want to pass it by value to function show - 

```
import sys
sys.path.append(".")
import example

b = example.Bird
example.show(b)
```

This, to me quite surprisingly, causes following error: 

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    example.show(f)
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (Foo) -> NoneType
```

Why is that so? Am I doing it wrong or passing by value is just not possible? I didn't really found anything about this in the docs :-/

**Comment by JendaPlhak** [comment]
It would be quite alright if I were to pass the argument by reference, but I was unable to accomplish that either.

**Comment by wjakob** [comment]
Huh? There is nothing called ``Bird`` in your example code. Do you mean ``Foo``? Aren't you missing the parentheses, as in ``Foo()``?

**Comment by JendaPlhak** [comment]
Sorry, already edited. I don't think that it is a problem of parenthesis.

**Comment by wjakob** [comment]
Please just try with parentheses...

**Comment by JendaPlhak** [comment]
You mean to do - f = example.Foo() ? That doesn't work since I didn't provide constructor for structure Foo. Is that the problem?

**Comment by wjakob** [comment]
exactly.. please look at the documentation examples before posting here -- my resources for these kinds of support tickets are very limited.

**Comment by JendaPlhak** [comment]
I see. Ok, sorry to bother, I will try harder next time.
