### ISSUE TITLE
ImportError: DLL load failed , When compiled on windows VS2015

### ISSUE THREAD

**Issue by ZQPei** [pybind/pybind11#1613]
I am using pybind11 to do some stuff like converting cv::Mat to numpy.ndarray.
What I have found is this repository [pybind11_opencv_numpy](https://github.com/edmBernard/pybind11_opencv_numpy)
and this repo worked on ubuntu!
When I compile them on windows with Visual Studio 2015, it successed.
But when I tried to call the generated file example.pyd in python, it occurs `ImportError: DLL load failed`.
I just compiled example.cpp ndarray_converter.h ndarray_converter.cpp
and example.cpp is as follows.
```cpp
#include <pybind11/pybind11.h>

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc.hpp>

#include "ndarray_converter.h"

#include <string>
#include <iostream>


namespace py = pybind11;

void show_image(cv::Mat image)
{
    cv::imshow("image_from_Cpp", image);
    cv::waitKey(0);
}

cv::Mat read_image(std::string image_name)
{
    cv::Mat image = cv::imread(image_name, CV_LOAD_IMAGE_COLOR);
    return image;
}

cv::Mat passthru(cv::Mat image)
{
    return image;
}

cv::Mat cloneimg(cv::Mat image)
{
    return image.clone();
}

PYBIND11_MODULE(test, m) 
{
    NDArrayConverter::init_numpy();
    
    m.doc() = "pybind11 opencv example plugin";
    m.def("read_image", &read_image, "A function that read an image", 
        py::arg("image"));

    m.def("show_image", &show_image, "A function that show an image", 
        py::arg("image"));
        
    m.def("passthru", &passthru, "Passthru function", py::arg("image"));
    m.def("clone", &cloneimg, "Clone function", py::arg("image"));

}
```
Is that pybind11 cannot work correctly on windows?
Can somebody help me out?

**Comment by ZQPei** [comment]
solved!

**Comment by cecabert** [comment]
@ZQPei, I run into the same issue, how did you solve it ?

**Comment by ZQPei** [comment]
@cecabert 
You shall add opencv *.dll file path to your environment before compilation!
It may work

**Comment by zchrissirhcz** [comment]
I meet same error message when encapsulating my own face landmark detection library.

I was using opencv 4.4,  VS2017 x64, and opencv vc15 x64's bin directory already in PATH, before opening cmd.exe to call my script, but it complains dll not found.

Later I switch to opencv 3.4.5, adding its vc15 bin directory to PATH, then call my script, it run OK.

Hope this may help people.
