### ISSUE TITLE
py::object::get_type() cpp label for <class 'type'> ?

### ISSUE THREAD

**Issue by ftaralle** [pybind/pybind11#1619]
Hi all,

I would like to write a method that accep only 'python types', the python meta-class.
But i cannot find the proper cpp label for this "thing"

I mean, i would like;
foo(2) -> exception: '2' is not a type
foo(int) -> ok 'int' is a type

cpp side:
```cpp
void foo(const py::object& input) {
    std::cout << input << ", " << input.get_type() << std::endl ;
}
```

python side:
```python
foo(2) # -> <class 'int'>
foo(int) # -> <class 'type'>
```

I know that <class 'int'> corresponds to py::int_
what is the cpp label for <class 'type'>

**Comment by EricCousineau-TRI** [comment]
For things like this, I think I've done the following hacky workaround:
```c++
void foo(py::object input) {
  py::object type = py::eval("type");  // Yuck, but it generally works.
  if (!input.isinstance(type)) {
    py::print("Bad thing.");
  } ...
}
```

Of course, there may be better ways, but this should at least unblock you.
From looking around, you could also do something with:
https://docs.python.org/2/library/inspect.html#inspect.isclass
like:
```c++
if (!py::module::import("inspect").attr("isclass")(input).cast<bool>()) { ... }
```

**Comment by ftaralle** [comment]
``` c++
if (!py::module::import("inspect").attr("isclass")(input).cast<bool>()) { ... }
```

works perfectly. Thank's

**Comment by ftaralle** [comment]
``` c++
if (!py::module::import("inspect").attr("isclass")(input).cast<bool>()) { ... }
```

works perfectly. Thanks

**Comment by eliottparis** [comment]
Following code seems to be a less time consuming solution to do this check: 

```c++
py::object obj;
bool is_type = PyType_CheckExact (obj.ptr ());
```
