### ISSUE TITLE
 dynamic module does not define init function

### ISSUE THREAD

**Issue by rhl-** [pybind/pybind11#162]
All of a sudden I have started seeing this:

`
In [4]: import ctl
ImportError                               Traceback (most recent call last)
<ipython-input-4-efe7da4e3134> in <module>()
----> 1 import ctl

ImportError: dynamic module does not define init function (initctl)`

**Comment by wjakob** [comment]
See the FAQ.

**Comment by rhl-** [comment]
Ah I see! Thanks!!
