### ISSUE TITLE
How to send file stream from python to c++

### ISSUE THREAD

**Issue by baudzhou** [pybind/pybind11#1623]
## Issue description

I tried to send file stream from python to c++ and met some problem. Thanks for help.

## Reproducible example code

**C++**
`
void asr(FILE *finput) {

    const int audio_buf_len = 320; 

    const double per_send_seconds = 0.01; 

    char audio_buf[audio_buf_len];

    while (!feof(finput)) {

        size_t read_cnt = fread(audio_buf, 1, audio_buf_len, finput);

....................

....................

    }

}

PYBIND11_MODULE(baidu_asr, m)

{

    m.doc() = "pybind11 example plugin";

    // expose add function, and add keyword arguments and default arguments

    m.def("asr", &asr, "A function which adds two numbers");

}

`
**python**

`
import asr

with open('16k-0.pcm','r') as f:

        asr.asr(f)
`

**error message**

> TypeError: rec(): incompatible function arguments. The following argument types are supported:
    1. (arg0: _IO_FILE) -> None

**Comment by MisterBianco** [comment]
Did you figure this out? I am working on something similar and just found this.
