### ISSUE TITLE
Passing C++ object into multiprocessing.Queue

### ISSUE THREAD

**Issue by RoboMouse** [pybind/pybind11#163]
Hi! I wanted to have some fun with pybind11 and Python multiprocessing library, however for following minimal example - 

```
#include <pybind11/pybind11.h>

struct Number {
    Number() : number(5) {}
    int number;
};

namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

    py::class_<Number>(m, "Number")
    .def(py::init<>())
    .def(py::init<const Number&>())
    .def_readwrite("number",    &Number::number);

    return m.ptr();
}
```

```
import sys
sys.path.append(".")
import example
import multiprocessing as mp

q = mp.Queue()

x = example.Number()
print(x.number)
q.put(x)
y = q.get()

print(y.number)
```

From which I get very unexpected output - 
`
5
994494424
`
as if after I get my object back from the queue, it is uninitialized. I thought it might be caused by the fact that I originally didn't provide copy constructor, but even providing it didn't help.

**Comment by wjakob** [comment]
According to this, pickling is involved: http://stackoverflow.com/questions/8518935/does-pythons-multiprocessing-connection-serialize. So you need to implement the meta functions for pickling/unpickling (for which there is currently no native mechanism in pybind11, i.e. you're on your own).

**Comment by RoboMouse** [comment]
Would it help to use boost?

**Comment by wjakob** [comment]
Pickling is now supported, see 56062831935fb3f723f241bd82444212494d15b0.
