### ISSUE TITLE
Support for wrapping C++ macros 

### ISSUE THREAD

**Issue by GreyDireWolf** [pybind/pybind11#1632]
Is there any way to wrap macros to call from python? I currently I'm working on generating bindings for logging library which uses glog like maros

**Comment by bstaletic** [comment]
Binding a macro directly is simply impossible. However, you can wrap your macros in a function and bind that.

**Comment by GreyDireWolf** [comment]
@bstaletic I think you are right. I was wondering if there was direct way of wrapping macro using functions in pybind11. So I guess you have to do it manually.
