### ISSUE TITLE
Passing self to a method that expects an abstract parent

### ISSUE THREAD

**Issue by ohm314** [pybind/pybind11#1634]
## Issue description

I hope I can explain this properly: I have a visitor pattern implemented in C++, which has an abstract Visitor class as well as implementations. I'd like to be able to further extend the visitor implementations using python bound visitor child-classes. When I pass however the python child class to the data class that is supposed to accept it, it fails to correctly resolve the type in gives up. I think the example code should explain what I'm trying to do.

Here's the error I get:

```
→ python ../test.py 
Program
Traceback (most recent call last):
  File "../test.py", line 28, in <module>
    main()
  File "../test.py", line 24, in main
    visitor.visit_program(p)
  File "../test.py", line 18, in visit_program
    node.visit_children(self)
TypeError: visit_children(): incompatible function arguments. The following argument types are supported:
    1. (self: example.Program, visitor: ast::Visitor) -> None

Invoked with: <example.TestNode object at 0x7f493acb4ed8>, <__main__.MyTestVisitor object at 0x7f493c09ae08>
```

## Reproducible example code

Here's the C++ code

```c++
#include <pybind11/pybind11.h>
#include <iostream>

namespace py = pybind11;

class TestVisitor;
class TestNode {
public:
    void visit_children(TestVisitor* );
    void accept(TestVisitor* );
};

class TestVisitor {
public:
   virtual void visit(TestNode* node) = 0;
};

class TestVisitorImpl : public TestVisitor {
public:
    virtual void visit(TestNode* node) {
        node->visit_children(this);
    }
};

void TestNode::visit_children(TestVisitor *v) {
    std::cout << "hello from TestNode" << std::endl;
}

void TestNode::accept(TestVisitor* v) {
    v->visit(this);
}

class PyTestVisitorImpl : public TestVisitorImpl {
public:
    using TestVisitorImpl::TestVisitorImpl;
    void visit(TestNode* node) override { PYBIND11_OVERLOAD(void, TestVisitorImpl, visit, node); }
};

class PyTestVisitor : public TestVisitor {
public:
    using TestVisitor::TestVisitor;
    void visit(TestNode* node) override { PYBIND11_OVERLOAD_PURE(void, TestVisitor, visit, node); }
};

PYBIND11_MODULE(example, m) {
    py::class_<TestVisitor, PyTestVisitor>(m, "TestVisitor")
            .def(py::init<>())
            .def("visit", &TestVisitor::visit);
    py::class_<TestVisitorImpl, PyTestVisitorImpl>(m, "TestVisitorImpl")
            .def(py::init<>())
            .def("visit", &TestVisitorImpl::visit);
    py::class_<TestNode>(m, "TestNode")
            .def(py::init<>())
            .def("accept", &TestNode::accept)
            .def("visit_children", &TestNode::visit_children);
}
```
And here is the python code that fails:

```python
import example
from example import TestVisitor, TestVisitorImpl

class MyTestVisitor(TestVisitorImpl):

    def visit(self, node):
        print("python visit")
        #super(MyTestVisitor, self).visit(node) # this works fine but has different semantics
        node.visit_children(self) # <-- this fails

def main():
    v = MyTestVisitor()
    n = example.TestNode()

if __name__ == "__main__":
    main()
```
I tried a number of alternative implementations but no luck so far. I'd really appreciate some help with this.

Thank you!

**Comment by bstaletic** [comment]
Looking at this, I don't see anything wrong, but pybind's `TypeError`s also have an `Invoked with:` line that is always useful for debugging this kind of type errors.

**Comment by skoslowski** [comment]
So, I tried this briefly. If `MyTestVisitor` inherits from `TestVisitor` instead, a call to `v.visit(n)` yields
```
python visit
hello from TestNode
```
It's this what you are expecting?

**Comment by ohm314** [comment]
Did you in the meantime have a chance reproducing this maybe? In the meantime I'm deriving from the base class as @skoslowski suggested above also. Let me know if I can provide you with more information to help.

**Comment by ohm314** [comment]
any update @skoslowski @bstaletic ?

**Comment by YannickJadoul** [comment]
This seems to be working, now that you told pybind11 about the `TestVisitor` class and that it's a base class of `TestVisitorImpl` (and thus also in the hierarchy of `MyTestVisitor`)?

At the very least, I can't reproduce anymore, with the version of the code currently presented above.

**Comment by YannickJadoul** [comment]
(Please reopen if there is still a problem.)
