### ISSUE TITLE
dynamic_attr and methods

### ISSUE THREAD

**Issue by pasbi** [pybind/pybind11#1645]
Using the `dynamic_attr`-tag, I can add a member-variable to a python-class instance from C++ after it has been created (III).
How can I add a member-function to a python-class instance from C++ after it has been created (`I`), (`II`)?

```
#include <pybind11/embed.h>
namespace py = pybind11;
class Foo { };
PYBIND11_EMBEDDED_MODULE(foo, m) { }

int main()
{
  using namespace py::literals;
  py::scoped_interpreter guard {};
  py::object module = py::module::import("foo");

  py::class_<Foo>(module, "Foo", py::dynamic_attr());

  Foo special_foo;
  py::object py_special_foo = py::cast(special_foo);

  // py_special_foo.attr("bar") = []() { return 73; };                        // (I)
  py_special_foo.attr("bar") = [](const py::object& self) { return 73; };     // (II)
  // py_special_foo.attr("bar") = 73;                                         // (III)


  py::exec( "print(special_foo.bar)",
            py::globals(),
            py::dict("special_foo"_a=py_special_foo) );
}
```

I'm aware that there's a [subtle difference](https://stackoverflow.com/a/2982/4248972) between member functions (`I`?)  and bound member methods (`II`?). Actually I only need (`II`), but I'm curious about (`I`) as well.

**Comment by YannickJadoul** [comment]
Have a look at what `py::class_::def` does: you can construct a `py::cpp_function` (and pass `py::method`, probably, maybe?) and assign it to `attr("...")`. I would assume this would work in this case as well?

If not, do please reopen this issue.

**Comment by pasbi** [comment]
Thanks @YannickJadoul , `py::cpp_function` does the trick.
FTR, the following lines add the function `bar` to the class a posteriori:

```
py::cpp_function func_cpp = []() { return 73; };
py_special_foo.attr("bar") = func_cpp;
```
or, if you prefer one line, `static_cast` also works:
```
py_special_foo.attr("bar") = static_cast<py::cpp_function>([]() { return 73; });
```

**Comment by YannickJadoul** [comment]
Great, thanks for confirming!

Don't even go with `static_cast`, btw. Just construct it:

```
py_special_foo.attr("bar") = py::cpp_function([]() { return 73; });
```

And if you really want to do things correctly, and have a "normal" method, do this:

```
py_special_foo.attr("bar") = py::cpp_function([](const Foo &self) { return 73; }, py::is_method(py_special_foo));
```
