### ISSUE TITLE
Acquiring a GIL lock locks the application

### ISSUE THREAD

**Issue by ArdKuijpers** [pybind/pybind11#165]
I am trying to implement Python bindings for a C++ library and like how pybind11 makes life easier. Thanks for that!

But I ran into a few issues regarding threads. Let me try to explain. The library records audio signals and lets clients handle the samples through a callback. The way the callback mechanism is implemented is to attach a Listener to a Controller. When new samples arrive, the Controller informs the (Python) listener by calling a virtual method (let's call it `doit`) to handle the data.

Since the library works with threads, I followed the instructions regarding locking the GIL. But if I call  `pybind11::gil_scoped_acquire`, it locks the application. I'm not sure if this is an error or my mistake (probably the latter ;) ). But I hope someone can help me to point me in the right direction, because it got my stuck for two days now. 

I made a clean example to demonstrate the locking. I simulate an event either by calling  `call_doit` or `call_doit_thread` from Python. `call_doit` will properly call the overloaded method `doit`. It runs on the same thread as Python. When using `call_doit_thread` the module tries to call the overloaded method from a std::thread. Then the module locks at `pybind11::gil_scoped_acquire gil;` (an expression inside the macro PYBIND11_OVERLOAD_PURE).

```cpp
#include <pybind11/pybind11.h>
namespace py = pybind11;

#include <string>
#include <thread>
#include <iostream>

namespace Sandbox {

class ListenerBase
{
public:
	virtual ~ListenerBase() {}
	virtual void doit(std::string caller) = 0;
};

class Controller
{
public:
	Controller(ListenerBase& base) : _base(base) {}
	void call_doit() { internal_call_doit("call_doit"); }
	void call_doit_thread()
	{
		std::thread t([this]() mutable { internal_call_doit("call_doit_thread"); });
		t.join();
	}
private:
	ListenerBase& _base;
	void internal_call_doit(std::string calledFrom)
	{
		{
			std::cout << calledFrom << "[just before calling]" << std::endl;
			_base.doit(calledFrom);
			std::cout << calledFrom << "[just after calling]" << std::endl;
		}
	}
};

class PyListenerBase : public ListenerBase
{
public:
	/* Inherit the constructors */
	using ListenerBase::ListenerBase;

	/* Trampoline (need one for each virtual function) */
	void doit(std::string caller)
	{
		//		PYBIND11_OVERLOAD_PURE(
		//				void,           /* Return type */
		//				ListenerBase,   /* Parent class */
		//				doit,           /* Name of function */
		//				caller          /* Argument(s) */
		//		);
		// Expands to:

	     pybind11::gil_scoped_acquire gil;
	     pybind11::function overload = pybind11::get_overload(this, "doit");
	     if (overload)
	    	 return overload.call(caller).template cast<void>();
	    pybind11::pybind11_fail("Tried to call pure virtual function \"doit\"");
	}
};

PYBIND11_PLUGIN(Sandbox)
{
	py::init_threading();

	py::module sandbox("Sandbox","Sandbox suite");

	py::class_<Controller>(sandbox,"Controller")
		.def(py::init<ListenerBase&>())
		.def("call_doit", &Controller::call_doit)
		.def("call_doit_thread", &Controller::call_doit_thread)
		;

	py::class_<PyListenerBase>(sandbox,"ListenerBase")
	   .alias<ListenerBase>()
	   .def(py::init<>())
	   .def("doit", &ListenerBase::doit)
	   ;

	return sandbox.ptr();
}

} /* namespace Sandbox */
```

In Python I can use the module as:
```python
import Sandbox
sb = Sandbox;

class MyPythonListener(sb.ListenerBase):
    def doit(self,caller):
        print 'MyPythonListener called by {0}'.format(caller);

listener = MyPythonListener();
controller = sb.Controller(listener);

print 'calling doit' 
controller.call_doit()

print 'calling doit on thread'
controller.call_doit_thread()
```

which results in:
```
>>> calling doit
>>> call_doit[just before calling]
>>> MyPythonListener called by call_doit
>>> call_doit[just after calling]
>>> calling doit on thread
>>> call_doit_thread[just before calling]
```

**Comment by wjakob** [comment]
You're missing a
```
pybind11::gil_scoped_release gil;
```
in ``call_doit_thread()``. You'll also need the latest version of pybind11, which fixes an issue that caused a crash in your example.

**Comment by ArdKuijpers** [comment]
Thanks for the feedback and the fix. Turns out your latest modification also fixes my orignal code. Keep up the good work!
