### ISSUE TITLE
Unable to compile pybind with nvcc 9

### ISSUE THREAD

**Issue by szsdk** [pybind/pybind11#1653]
## Issue description
I am try to compile pybind11 2.2.4 with nvcc 9. But there is an error,
```
/.../include/python3.7m/pybind11/cast.h(838): error: alias template "pybind11::detail::type_caster_base<type>::cast_op_type" may not be used in the type-id of the alias-declaration
```
But my code works fine with nvcc 10.
## Reproducible example code
```c++
#include <pybind11/pybind11.h>
int main() {}
```
I compile it with
```
nvcc t.cu -I /scratch/loh/szsdk/anaconda_env/kuda01/include/python3.7m
```
where `t.cu` is the file.

**Comment by Satre95** [comment]
Hello @szsdk I am seeing this same issue on a Tegra TX2 with CUDA 9 and GCC 5. Were you able to figure it out? 

I also get this error when I use GCC 6.

**Comment by szsdk** [comment]
@Satre95 No. I guess is nvcc's problem. It always does some thing funny with the template. One work around is adding a new layer to separate the Cuda implementation and the normal cpp interface.

**Comment by Satre95** [comment]
Alrighty, thanks for your response!

**Comment by YannickJadoul** [comment]
Is this (1.5 years later) still an issue? A few things regarding nvcc were fixed, recently.

I'll close this; if the 2.5.0 or the latest master commit still results in issues, please reopen!

**Comment by szsdk** [comment]
I did a quick test. And there is no error in pybind11 2.4.3 with nvcc 9.2 and nvcc 10.1.

**Comment by YannickJadoul** [comment]
Thanks for confirming! :-)
