### ISSUE TITLE
More support for embed: interactive terminal

### ISSUE THREAD

**Issue by zhihaoy** [pybind/pybind11#1655]
## Issue description

Feature request: Please consider provide abstractions for `PyRun_InteractiveLoop` families.

**Comment by madebr** [comment]
This can also be done, and perhaps easier, by using the code module: https://docs.python.org/3/library/code.html

**Comment by YannickJadoul** [comment]
This seems like it would be out of the current scope, and could be done outside of pybind11.
The request is also pretty vague, and no reply to @madebr's suggestion.

Please reopen with more details, or propose a PR.
