### ISSUE TITLE
pybind11::array constructor deprecated

### ISSUE THREAD

**Issue by soulslicer** [pybind/pybind11#1663]
I am currently using the Type Caster API.

I have a constructor as follows:

```
        bool load(handle src, bool imp)
        {
            array b(src, true);
```

It works, but I get a warning saying: 

```
/home/user/pybind/python/test/_test.cpp:230: warning: ‘pybind11::array::array(pybind11::handle, bool)’ is deprecated: Use reinterpret_borrow<array>() or reinterpret_steal<array>() [-Wdeprecated-declarations]
             array b(src, true);
                              ^
```

I'm not clear how to use reinterpret_borrow etc. Can I get an example?

**Comment by bstaletic** [comment]
It's simple. `array b = reinterpret_borrow<array>(src);` or `array b = renterpret_steal<array>(src);`, depending on if you want to "borrow" or "steal" the reference.

I also can't find a `pybind11::array::array(pybind11::hand, boold)` in `pybind11/numpy.h`, so I'm not sure what that constructor is supposed to do.

**Comment by soulslicer** [comment]
what is the meaning of borrow and steal? What is my old command doing by default?

**Comment by bstaletic** [comment]
Like I said,  don't know what that constructor does.

Stealing and borrowing has everything to do with reference counting. I might be wrong, so I advise you to double check everything I say from this point onward. Stealing a reference doesn't bump the reference count and the original "reference" (actually a `PyObject*`) should no longer be used. Borrowing on the other hand does increment the reference count and leaves the earlier reference usable.
They are somewhat analogous with C++ copy/move assignments/constructors (there are differences that I don't remember).
