### ISSUE TITLE
Create sequences using initializer list

### ISSUE THREAD

**Issue by cowo78** [pybind/pybind11#1669]
## Issue description
To me it would be useful to be able to construct a few containers (i.e. tuple, list) using initializer lists. I would supply a patch.

## Reproducible example code
Something like this:

    pybind11::tuple create_tuple(std::initializer_list<pybind11::object> l)
    {
        pybind11::tuple retval {l.size()};
        size_t index {0};
        for (const pybind11::object& item : l)
            retval[index++] = item;
        return retval;
    }

**Comment by YannickJadoul** [comment]
Sure, if you want to submit a PR, we can happily look at it and consider including it. If it doesn't blow up the binary size, there's a good chance it can be included.

I'm going to close this issue, now, though, in case you wouldn't be interested anymore. Feel free to reopen (or just open a PR).
