### ISSUE TITLE
Minimal working example: Call local python script from cxx

### ISSUE THREAD

**Issue by a-jp** [pybind/pybind11#1673]
Hi,
Very new to pybind11.  I would like to call a python script from my cxx code, passing in some arguments to a function within the script and have the script effect the state of the passed arguments that originate as variables within my cxx code.  Could I ask, on this page:
[pybind11-Importing modules](https://pybind11.readthedocs.io/en/stable/advanced/embedding.html)
there is an example about half way down in the Importing modules section that refers to a calc.py script being called from cxx code: the add function within the script.  This shows what I'd like to do as noted above with the addition that I'd like to change the state of the passed in variables.  Could I ask for a full working example of that approach? At present only a sub is currently shown?  That is, what should I include? Do I need py::scoped_interpreter guard{} at the top as shown in examples further up, how to I clean up etc? I'm building my cxx with cmake, what do I need to do in this specific case to make that work? Sorry to ask, but very new the repo.  A full working example for this approach would be appreciated.  If this is shown elsewhere in full please just point me towards that.
Thanks again,
Andy

**Comment by Dekken** [comment]
the simplest approach would be to use ```"system("python3 script.py arg1 arg2");```

but this is not generally encouraged

Boost provides a cross platform processor launcher, and I've written one myself if you're interested

**Comment by a-jp** [comment]
To reformulate the question.  [Here](https://pybind11.readthedocs.io/en/master/advanced/embedding.html) the follow code stub is posted:
`
"""calc.py located in the working directory"""

def add(i, j):
    return i + j

py::module calc = py::module::import("calc");
py::object result = calc.attr("add")(1, 2);
int n = result.cast<int>();
assert(n == 3);
`

Could someone expand this out into a minimum working example: so a simple "int main" example with the required includes etc.  I'd ideally like to be able to modify the variables passed from cxx from within the python script?  If you would be will to provide an example for that also that would be brilliant.
Thanks,
Andy

**Comment by aoloe** [comment]
@a-jp in the past i've been creating a set of minimal examples that build upon each other:

https://github.com/aoloe/cpp-pybind11-playground#sample-projects

during the last week i've been going through it and i did some clean up.
it might or not be helpful to you.
tickets, comments and pull requests are welcome.

**Comment by YannickJadoul** [comment]
This isn't really an issue. If you have questions like this, please come to [Gitter](https://gitter.im/pybind/Lobby).

> This shows what I'd like to do as noted above with the addition that I'd like to change the state of the passed in variables.

This might not work, since Python doesn't always allow you to do so (e.g., you can't pass an `int` "by value" in Python either).

> At present only a sub is currently shown? That is, what should I include? Do I need py::scoped_interpreter guard{} at the top as shown in examples further up, how to I clean up etc?

This is explained in the sections before. Play around a bit and try out something.
