### ISSUE TITLE
Use Python Frame Work Include Path by Default on OSX

### ISSUE THREAD

**Issue by mfisher31** [pybind/pybind11#1677]
Wondering if it would be possible to add something like this to the code so that Apple's python framework headers are used by default.

**pybind11/detail/common.h**
```
....
#if defined (__APPLE__)
#  include <Python/Python.h>
#  include <Python/frameobject.h>
#  include <Python/pythread.h>
#else
#  include <Python.h>
#  include <frameobject.h>
#  include <pythread.h>
#endif
```
....

Without this I either need to have a lengthy include path pointing to Xcode.app internal contents, or use a third party python build like homebrew.  I realize that another macro (or something) would be needed so that apple headers are optional.

**Comment by bstaletic** [comment]
Doesn't specifying `python-config --cflags` return the needed flags that you ca just plug into your already existing flags and make `#include <Python.h>` work?

**Comment by mfisher31** [comment]
@bstaletic yep, you're absolutely correct!  I didn't realize OSX also includes python-config.  Should have tried that first.  My mistake.
