### ISSUE TITLE
External call function is much more time consuming than internal function execution

### ISSUE THREAD

**Issue by artiit** [pybind/pybind11#1679]
## Issue description

External call function is much more time consuming than internal function execution

## Reproducible example code

Hi everone, I use pybind11 to wrapper my cpp function like,

`Status GetResult(Request* req, Response* res)
{...}
`
the wrapper file like,
```
m.def("get_result", [] (Request* req, Response*  res) {
  Status s = GetResult(req, res);
  return s;
});
```
and the python code is:
a.py
```
def foo(data):
  start = time.time()
  Request req
  Response res
  make_req(req, data)
  s = GetResult(req, res)
  ret = deal_res(res)
  end = time.time()
  print(end-start) #20ms
  return ret
```
b.py
```
start = time.time()
ret = foo(data)
end = time.time()
print(end-start) #30ms
```
when b.py call a.py foo(), it seems that b.py cost 10ms more than a.py foo function internal actually cost. I am confused what lambda bind function did and why there are 10 more ms cost. 

Any suggestions will be appreciate.

Thanks.

**Comment by bstaletic** [comment]
The only difference in the two use cases is that `b.py` needs to import `foo` and needs to call `foo` (you didn't tell us how you measured the difference). Python imports have been known to be slow, so maybe that can explain it. If that's the case and imports are really a bottleneck, you're using the wrong tool (language) for the job.

**Comment by artiit** [comment]
Thanks @bstaletic , I have updated the example code. I just put `a.py` and `b.py` in one py file, but it still has 10ms gap. I guess after call `foo`, python maybe call destructor of cpp class and that may be time consuming, but 10ms is too much.

**Comment by artiit** [comment]
I found that the `res` destruction is the key reason. I declared `res` on the python side, and cpp `GetResult` function will fill some result in `res`.   The `Response` wrapper like:
```
py::class_<Response>(m, "Response")
    .def(py::init())
```
I think that python will call `Response` destructor when exit `foo` function, but why the destruction of `res` is so long?

**Comment by artiit** [comment]
Now I found that the cpp destruction of `Response` is time consuming, not pybind11 or python.
