### ISSUE TITLE
new make_iterator issue?

### ISSUE THREAD

**Issue by rhl-** [pybind/pybind11#168]
I am not sure if I am misusing the new make_iterator feature you added. Looking for some help.

I've added code like this following example6

in this case, I have an object which wraps an STL vector< int> and provides a begin() and end() function which return iterators. This object is called a "simplex" and it has type 's'. 

     .def("__iter__", [](py::object obj) {
        const s &smplx = obj.cast<const s&>();
       return py::make_iterator(smplx.begin(), smplx.end(), obj); // <- obj for reference counting 
    })

I have the following error when I try to compile with this added definition: 
```

In file included from /Users/rhl/code/ctl/python/ctl.cpp:2:
In file included from /Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/pybind11.h:30:
/Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/attr.h:291:93: error: cannot initialize a parameter of type 'pybind11::detail::type_record *' with an lvalue of type
      'pybind11::detail::function_record *'
        int unused[] = { 0, (process_attribute<typename std::decay<Args>::type>::init(args, r), 0) ... };
                                                                                            ^
/Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/pybind11.h:156:47: note: in instantiation of member function 'pybind11::detail::process_attributes<pybind11::name, pybind11::sibling,
      pybind11::is_method, pybind11::return_value_policy, pybind11::object>::init' requested here
        detail::process_attributes<Extra...>::init(extra..., rec);
                                              ^
/Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/pybind11.h:92:9: note: in instantiation of function template specialization 'pybind11::cpp_function::initialize<(lambda at
      /Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/pybind11.h:1006:30), const unsigned long &, pybind11::detail::iterator_state<std::__1::__wrap_iter<const unsigned long *> > &, pybind11::name,
      pybind11::sibling, pybind11::is_method, pybind11::return_value_policy, pybind11::object>' requested here
        initialize(std::forward<Func>(f),
        ^
/Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/pybind11.h:760:22: note: in instantiation of function template specialization 'pybind11::cpp_function::cpp_function<(lambda at
      /Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/pybind11.h:1006:30), pybind11::name, pybind11::sibling, pybind11::is_method, pybind11::return_value_policy, pybind11::object>' requested here
        cpp_function cf(std::forward<Func>(f), name(name_),
                     ^
/Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/pybind11.h:1006:14: note: in instantiation of function template specialization
      'pybind11::class_<pybind11::detail::iterator_state<std::__1::__wrap_iter<const unsigned long *> >, std::__1::unique_ptr<pybind11::detail::iterator_state<std::__1::__wrap_iter<const unsigned long *> >,
      std::__1::default_delete<pybind11::detail::iterator_state<std::__1::__wrap_iter<const unsigned long *> > > > >::def<(lambda at
      /Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/pybind11.h:1006:30), pybind11::return_value_policy, pybind11::object>' requested here
            .def("__next__", [](state &s) -> decltype(*std::declval<Iterator>()) & {
             ^
/Users/rhl/code/ctl/python/wrap_simplex.hpp:20:13: note: in instantiation of function template specialization 'pybind11::make_iterator<std::__1::__wrap_iter<const unsigned long *>, pybind11::object &>'
      requested here
        return py::make_iterator(smplx.begin(), smplx.end(), obj); // <- obj for reference counting 
                   ^
/Users/rhl/code/ctl/dependencies/pybind11/include/pybind11/attr.h:260:52: note: passing argument to parameter 'r' here
    static void init(const handle &h, type_record *r) { r->base_handle = h; }
                                                   ^
```

**Comment by wjakob** [comment]
Hi Ryan,

looks like you're not using the latest iteration of the ``make_iterator`` design. Can you try with ``HEAD`` and use the syntax shown in the included example?

Wenzel

**Comment by rhl-** [comment]
Odd, it seems that this is the commit I am using: 

commit b2b44a9af81b591b273fa98fa0780237c66a3a7d
Date:   Fri Apr 15 17:50:40 2016 +0200

    fix for virtual dispatch on newly created threads

Which appears to be the latest.

**Comment by wjakob** [comment]
Refer to the ``make_iterator`` syntax here: https://github.com/pybind/pybind11/blob/master/example/example6.cpp

For instance, there is no parameter to pass in to keep a reference. Instead, this is now handled using call policies.

**Comment by rhl-** [comment]
Ah, that does resolve this. While I have you, two more questions:

1) Is it possible to define ranges which take as input a parameter? In C++ I am using begin( Simplex s) end( Simplex s)? I could update my design to use ranges I suppose..
2) In the above example I want to expose a function to python whose input in C++ is another type (which I have exported). Is there a way to accept the python equivalent of object as a parameter?

e.g. export ``class Foo`` to python, export a function of signature ``R bar( Foo f)``

**Comment by wjakob** [comment]
For 1, I assume this entails writing only
``
return py::make_iterator(smplex); 
``
?

I don't understand your second point -- isn't this something trivial that many of the examples do?

**Comment by rhl-** [comment]
For (1) an example is:
``s = [1,2,3]
for (auto itr = boundary.begin(s); boundary.end(s); ++itr){
 print *itr;
}``
might print:
``+[2,3]  -[1,3] + [1,2]``

So, begin and end are parameterized..

For (2), I am not seeing an example of this, can you please point at one?

**Comment by wjakob** [comment]
For (1), what syntax did you use in Boost.Python?

For (2), I'll turn this around and ask if you can provide a more explicit example? I am not quite sure what you're getting at.

**Comment by rhl-** [comment]
(1) I never used boost.python for this. I couldn't get that far :)

(2) I think this should be easy, but, not seeing it for some reason.

I export a type ctl::Simplex to a python type ctl.Simplex
then I wish to export a container for example, ctl::Cell_Complex< Simplex> -> ctl.Cell_complex
In C++ I have a strongly typed function:

ctl::Cell_complex< Simplex>::insert( Simplex& s){...}

I wish to export this, and ideally I would like python binding to accept whatever type, but, if it is not a Simplex to try and coerce it into one? Or something? At least accepting just the python version of the C++ type i exported...

**Comment by wjakob** [comment]
Regarding 1, what's wrong with
``
.def("__iter__", [](const Simplex &s, const std::vector<int> &list) { return py::make_iterator(s.begin(list), s.end(list)); }, py::keep_alive<0, 1>())
``

**Comment by wjakob** [comment]
regarding 2: looks like you want implicit type conversions here. See the advanced section of the docs for that, as well as example 8.

**Comment by rhl-** [comment]
These are fine answers let me try them out.
