### ISSUE TITLE
Make a new release with (at least) bugfixes of 5c8746ff135abb390bf95944be593e895a586a50

### ISSUE THREAD

**Issue by johnmarkwayve** [pybind/pybind11#1680]
## Issue description

I just spent two days tracking down a bug in a large codebase that turned out to be caused by a pybind bug. This bug does not seem to be in master but is in the latest release (2.2.4). Since many users will assume that a release version is more stable than non-release master commits, it would be very helpful to make a new release to avoid others potentially having similar problems.

## Description of my specific bug (for posterity)

We have a python module compiled with pybind11, for which we had our build system download version 2.2.4, as the latest release version. We also use pytorch, which itself uses pybind11.

We were getting very bizarre hangs (process doesn't respond to interrupt signal and must be killed) in bizarre places in our pybind11 module. I wasn't able to identify exactly where it happened, but my best guess was it was the destructor of a `std::shared_future` (that object itself provided from another 3rd party library). Weird.

Eventually, I work out that if the python code that calls our module doesn't `import torch` (torch wasn't actually being used in this code, it was just getting imported as a result of transitive python imports), the hangs stop. None of this code (either in our pybind11 module, or the python code calling it) used pytorch at all, it simply happened to be imported.

To cut a long debugging story short, I eventually notice that 1) pytorch uses pybind11 and 2) it uses a commit of pybind11 beyond the most recent release (5c8746f). When I point our build system at the same pybind11 commit, the problem disappeared.

This was not a problem of pytorch being built with the wrong version of pybind11 either, the builds are totally separate and isolated from one another. It was simply using two pybind11 modules, one built at release and one built at 5c8746f.

**Comment by bmerry** [comment]
I haven't looked at the specific changes between 2.2.4 and that commit, but what might be happening is that pybind11 changes the internal layout of its shared data structure from time to time. To avoid conflicts it creates a separate copy of the internals for each distinct pybind version, but it only gets bumped at numbered releases. So it might think that pytorch and your module have the compatible internals when in fact they don't.

If that's a case, I would consider that a bug in PyTorch. If they're using a vendored pybind11 with unreleases changes, they should change the internals version code to something that won't conflict.

**Comment by tadeu** [comment]
What is needed for a new pybind11 release? I'm willing to help.

cc @wjakob

**Comment by nicoddemus** [comment]
Any updates? Just a reply with a rough planning on when the next release is due would be OK.

**Comment by wjakob** [comment]
I've put together a new minor-version release that I'll push out shortly :). Apologies that it took really long, life as a prof is pretty busy some times.
