### ISSUE TITLE
Autogenerating Doc/API?

### ISSUE THREAD

**Issue by soulslicer** [pybind/pybind11#1684]
Does Pybind11 provide some method that allows you to add some documentation to your APIs? Or is there a way in which a user using the generated .so, can determine what functions and classes are available, and what those functions do?

**Comment by bstaletic** [comment]
Read this: https://pybind11.readthedocs.io/en/stable/basics.html#creating-bindings-for-a-simple-function

**Comment by EricCousineau-TRI** [comment]
`pybind11` also briefly mentions `binder` as a project that can help auto-generate bindings:
https://pybind11.readthedocs.io/en/stable/compiling.html#generating-binding-code-automatically

In general, there will be many solutions that are tailored for specific use cases. To illustrate, there's also Google CLIF, SWIG, and a suite of Cython generators out there (e.g. look at `gtsam`).

**Comment by bstaletic** [comment]
Considering that there was no further discussion here, I'll close this.

**Comment by romanwerpachowski** [comment]
> Read this: https://pybind11.readthedocs.io/en/stable/basics.html#creating-bindings-for-a-simple-function

It would be super useful if one could easily extract the documentation generated in this way to an HTML format, a'la sphinx.

**Comment by virtuald** [comment]
As long as you can import the module, and you set up the docstrings in pybind11, you can use sphinx to do this. For example, this RTD site is sphinx documentation of several pybind11 modules:

https://robotpy.readthedocs.io/projects/wpilib/en/stable/wpilib.geometry/Pose2d.html#wpilib.geometry.Pose2d

There's also https://github.com/sizmailov/pybind11-stubgen which can dynamically inspect your module and generate typestubs from it.

**Comment by romanwerpachowski** [comment]
Great, thanks!

**Comment by romanwerpachowski** [comment]
I tried that, but it only generates the documentation for the top-level module, without recursion:

Config: https://github.com/romanwerpachowski/ML/tree/master/docs/sphinx

Travis-generated result: https://romanwerpachowski.github.io/ML/cppyml/html/index.html

(There seems to be a problem with missing theme files, but that's a secondary issue.)

**Comment by YannickJadoul** [comment]
@romanwerpachowski I think that's standard `sphinx-autodoc` behavior, no?

Can you just try with a pure-Python project and sphinx + autodoc? I'm reasonably sure it will demonstrate that this is not a pybind11 issue, but just the way autodoc behaves.

**Comment by romanwerpachowski** [comment]
Thanks, it works better now: https://romanwerpachowski.github.io/ML/cppyml/html/index.html

**Comment by connorjak** [comment]
https://github.com/sizmailov/pybind11-stubgen
