### ISSUE TITLE
Member raw pointer assignment

### ISSUE THREAD

**Issue by drodri** [pybind/pybind11#169]
I am trying (as an example) to build a wrapper for Zlib, which has the following (simplified) structure:

```cpp
struct ZStream{
    char* input;
};

namespace py = pybind11;
PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");
     
    py::class_<ZStream>(m, "ZStream")
        .def(py::init<>())
        .def_readwrite("input", &ZStream::input);
```

This fails with message: 
```bash
include\pybind11\cast.h(581): error C2664: 'void pybind11::class_< ZStream,std::unique_ptr<type,std::default_delete<_Ty>>>::def_readwrite::<lambda_0efac106066633b4fb2e3c6d9eedfded>::operator ()(C &,const D &) const': cannot convert argument
2 from 'char' to 'char *const &' [C:\Users\drodri\workspace\accu\accu\5pybind11\build\example.vcxproj]
          with
          [
              type=ZStream,
              _Ty=ZStream,
              C=ZStream,
              D=char *
          ]
  c:\users\drodri\.conan\data\pybind11\1.4\memsharded\stable\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\pybind11\cast.h(581): note: Reason: cannot convert from
  'char' to 'char *const '
```

I have tried casting "input", but without success.
It builds if I use ``def_readonly``, but then fails at run time, as the field is not-assignable (which makes sense I guess).

I am able to do it with ctypes, this works for my use case:

```python
class _z_stream(ctypes.Structure):
    _fields_ = [
        ("next_in", ctypes.POINTER(ctypes.c_ubyte)),
        ... 
    ]

def compress(input, level=6):
    st = _z_stream()
    ...
    st.next_in   = ctypes.cast(ctypes.c_char_p(input), ctypes.POINTER(ctypes.c_ubyte))
```

I cannot find in the docs or examples how to handle this. Is it possible to manage such low level pointer assignment? I am not willing to modify the original source code to add setters/getters, as it the ZLib, would like to keep it as-is.
Thanks very much.

**Comment by wjakob** [comment]
I just committed a change with theoretically allows your code to compile -- however, note that this is not the way to do it.
Please use the ``def_property`` syntax (see docs for information) and provide a setter and getter manually. Importantly, for the setter, you'll need to ``strdup()`` the string received as an argument.

**Comment by memsharded** [comment]
Great, thanks for this. Yes, you are right, this was not the way to do it, just figuring out things, comparing with ctypes, etc. Keep the good job.

**Comment by drodri** [comment]
Great, thanks for this. You are right, this was not the right way to do it. I was just figuring out things, comparing with raw ctypes, etc. Keep the good job.
