### ISSUE TITLE
initialize_generic should use repr rather than attr("__repr__")

### ISSUE THREAD

**Issue by asadchev** [pybind/pybind11#1691]
in pybind11.h, in `initialize_generic` the relevant line should be 
`a.descr = strdup(repr(a.value).cast<std::string>().c_str());`
otherwise error is thrown with for example type objects
`ImportError: TypeError: descriptor '__repr__' of 'float' object needs an argument`

**Comment by bstaletic** [comment]
This is a duplicate of #2028

**Comment by YannickJadoul** [comment]
This one was first, though, so thanks for reporting, @asadchev! :-)
