### ISSUE TITLE
Rvalue reference parameters work in constructors, but not in other functions

### ISSUE THREAD

**Issue by Boris-Rasin** [pybind/pybind11#1694]
```cpp
struct example {
    example(std::string&&) {}
    void name(std::string&&) {}
};

pybind11::class_<example>(m, "example")
    .def(pybind11::init<std::string&&>()) // this works
    .def<void(example::*)(std::string&&)>("name", &example::name) // this doesn't
;
```
Error message:

/usr/local/include/pybind11/pybind11.h:72:74: error: rvalue reference to type 'basic_string<...>' cannot bind to lvalue of type 'basic_string<...>'
        initialize([f](Class *c, Arg... args) -> Return { return (c->*f)(args...); },

**Comment by e00E** [comment]
Here is another example:
```c++
#include <pybind11/pybind11.h>

namespace py = pybind11;

class C {
public:
  C() = default;
  void f(std::string &&) {}
};

PYBIND11_MODULE(frame_comparer, m) {
  py::class_<C>(m, "C")
    .def(py::init<>())
    .def("f", &C::f);
}
```
Maybe a good way to solve this is to allow syntax along the lines of:
```c++
...
.def_with_this("f", [](C* this_, std::string argument) { return this_->f(std::move(argument)); });
```
where the first argument is always the this pointer. This is terser than the workaround of defining a whole wrapper class and cleaner than the other workaround of making a non member wrappper.

**Comment by amrit-poudel** [comment]
What exactly is the solution to this issue (identified by the op)? I am also encountering similar error.
Does anyone have a working solution that they could share here?I'd appreciate it.
Thanks.

**Comment by Boris-Rasin** [comment]
This pull request seems to fix the problem, but for some reason it hasn't been merged:
https://github.com/pybind/pybind11/pull/2048

**Comment by amrit-poudel** [comment]
Thanks for that note. A bit off topic, but I was wondering if you know how I can expose operator() from a c++ class to python.  I tried:

.def(“__call__”, &SomeClass::operator(), py::arg(“e”)=nullptr, py::is_operator()); 

This does not quite work.

**Comment by mattgodbolt** [comment]
I'm not sure the constructor works either: I think behind the scenes the compiler's using the copy constructor. In my tests with move-only types, a constructor taking a rvalue reference to an uncopyable type causes:

```
env/include/pybind11/detail/init.h:173:66: note:   conversion of argument 2 would be ill-formed:
In file included from env/include/pybind11/attr.h:13:0,
                 from env/include/pybind11/pybind11.h:44,
                 from ../src/python/pywave.cpp:5:
env/include/pybind11/cast.h:1982:37: error: cannot bind rvalue reference of type 'wave::TypeRegistry&&' to lvalue of type 'wave::TypeRegistry'
         return std::forward<Func>(f)(cast_op<Args>(std::move(std::get<Is>(argcasters)))...);
```
