### ISSUE TITLE
coupling c++ and python api from Cantera 

### ISSUE THREAD

**Issue by a-jp** [pybind/pybind11#1695]
Hi,

I would like to use the Cantera library's c++ and python api together to allow faster work flow.  I'd ideally like my c++ code to hold the cantera object, but have it setup via a python script, to allow for faster development: pybind11 seemed the correct way to do this. So far I have in c++:

```c++
#include <pybind11/embed.h> // everything needed for embedding
namespace py = pybind11;
#include "cantera/thermo.h"
using namespace Cantera;
#include <iostream>

int main()
{
    py::scoped_interpreter guard{}; // start the interpreter and keep it alive
    py::module calc = py::module::import("setup");
    py::object result = calc.attr("example")();
    auto* gas = result.cast<ThermoPhase*>();
    std::cout << gas->report() << std::endl;
}
```

In a python file in the same directory I have:

```python
import cantera as ct

def example():
    gas1 = ct.ThermoPhase('gri30.xml')
    gas1()
    return gas1
```

The second last line prints to the screen as expected and the python file is called as expected, but returning the object, the part I need to achieve, fails in the cast on the c++ side:

```terminal
libc++abi.dylib: terminating with uncaught exception of type pybind11::cast_error: Unable to cast Python instance of type <class 'cantera._cantera.ThermoPhase'> to C++ type 'Cantera::ThermoPhase'
```

This is a minimal working example so specific knowledge of Cantera is not really required. Cantera is written in c++ but has a python api provided by cython.  I had therefore naively assumed this would all "just work".  Any help would be really appreciated.
Thanks,
Andy

**Comment by YannickJadoul** [comment]
If Cantera's own bindings are written with Cython, pybind11 won't be able to automatically convert. This is the uncaught exception that crashes your program (you could catch it, and it would already not crash anymore).

I'd suggest looking into [custom casters](https://pybind11.readthedocs.io/en/stable/advanced/cast/custom.html) to see how you could teach pybind11 how to convert a Cantera C++ object into a Python object and vice versa.
