### ISSUE TITLE
Seems there isn't a caster between std::vec to py::list - is it correct?

### ISSUE THREAD

**Issue by gmolkho** [pybind/pybind11#1698]
Hi,

Please refer to Q &first answer at [https://stackoverflow.com/questions/53724225/pybind11-convert-stdvector-to-pylist/54774353#54774353](url)

Is there a built-in ready made manner?

Thanks!

**Comment by gmolkho** [comment]
was answered at:[https://stackoverflow.com/questions/53724225/pybind11-convert-stdvector-to-pylist/54774353#54774353](url)

**Comment by wjakob** [comment]
The answer on SO is incorrect. You simply need to include ``pybind11/stl.h``.

**Comment by gmolkho** [comment]
Thanks, I removed it
