### ISSUE TITLE
implicitly_convertible

### ISSUE THREAD

**Issue by rhl-** [pybind/pybind11#170]
Hi,

Not really an issue, but, you don't have another place to have these conversations.

This is a really useful feature. I was thinking of the following scenario not necessarily captured.

Imagine you have a C++ object with an iterator range constructor 

``Foo::Foo( Iterator begin, Iterator end) { ..}``

Now whenever you have a type that is also a range over ``Iterator::value_type`` you can offer a conversion from that type to Foo.

I suppose this can also be solved by offering an explicit Range constructor for Foo, e.g.

```
template< typename Range>
Foo( const Range & r){ ... }
```

Then you can always implicitly convert? 

However, is it certainly seems possible to codify ``implicit_range_convert<A,B>(){}`` which glues conversion code in to the iterator range constructor.

This would have the value that you could imagine ``implementing implicit_range_covert<B>() {}`` which then automatically glues all known valid range types..

Thoughts?

**Comment by wjakob** [comment]
Not sure I fully understand.. so the main problem is that you have a constructor with two arguments instead of one (in which case ``implicitly_convertible`` would work just fine?)

**Comment by rhl-** [comment]
Ok, i guess that above would be a feature request. Looking at this code more closely, it appears that this doesn't work correctly.

In particular, you need the constructor of B to actually *exist* at run time for this to work. Which means that the exact example I suggested above (or any constructor with a template) causes a problem for conversion.

For example, if you write:
``
class Foo {
 Foo( list< int> & x){};
}; 

py::implicitly_convert< list<int>, Foo>(); 
``
then you should be able to get away with:

`` >> Foo = new Foo([1,2,3])``

But, if you do:
class Foo {
 template< typename Range>
 Foo(Range & x){};
}; 

then nothing in 
`` py::implicitly_convert< A, B>(); ``

actually instantiates the constructor for B.

Do you see what i mean?

I think you need something like:

``declval`` or ``std::result_type()`` in that function to guarantee that the compiler actually produces the constructors you care about..

Let me see if I can produce an example from this.

**Comment by wjakob** [comment]
Yes, a concrete example would be helpful.

**Comment by wjakob** [comment]
Any updates here?

**Comment by rhl-** [comment]
Apologies I am busy with some other things. I haven't had time to make a
minimal test case

**Comment by rhl-** [comment]
```
#include <pybind11/pybind11.h>
#include <vector>
#include <list>

namespace py = pybind11;

struct Foo {
        Foo(): x(){}
        template< typename Range>
        Foo( const Range& r): x(std::begin(r), std::end(r)){}
        std::vector< int> x;
};

//## Define the module
//This is where we actually define the `ctl` module. We'll also have a `phat` module that's written
PYBIND11_PLUGIN(example) {
  //Create the module object. First arg is the name, second is the module docstring.
  py::module m("example", "Minimal Example.");

  py::class_<Foo>(m, std::string("Foo").c_str())
    //Default no-args constructor
    .def(py::init());
  //Foo provides a 
  py::implicitly_convertible< std::list<int>, Foo>();
  return m.ptr();

}
```

But nothing about `py::implicitly_convertible< std::list<int>, Foo>();` requests to instantiate:
```Foo::Foo( std::list<int>& r){..}```

```
 In [2]: example.Foo([1,2,3])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-d769230f00ee> in <module>()
----> 1 example.Foo([1,2,3])

TypeError: Incompatible function arguments. The following argument types are supported:
    1. (example.Foo) -> NoneType
```

**Comment by rhl-** [comment]
I realize this is a banal example as you can just instantiate the constructor, here is perhaps slightly more interesting:
```

//Required header for using pybind11
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <vector>
#include <list>


namespace py = pybind11;

struct Foo {
	Foo(): x(){}
	template< typename Range>
	Foo( const Range& r): x(std::begin(r), std::end(r)){}
	std::vector< int> x;
};

struct Bar {
	Bar(): x(){}
	Bar( const std::list<int>& r): x(std::begin(r), std::end(r)){}
	std::vector< int> x;
	typedef typename std::vector< int>::const_iterator iterator;
	iterator begin(){ return x.begin(); }
	iterator end(){ return x.end(); }
};




//## Define the module
//This is where we actually define the `ctl` module. We'll also have a `phat` module that's written
PYBIND11_PLUGIN(example) {
  //Create the module object. First arg is the name, second is the module docstring.
  py::module m("example", "Minimal Example.");
  
  py::class_<Foo>(m, std::string("Foo").c_str())
    //Default no-args constructor
    .def(py::init());

  py::class_<Bar>(m, std::string("Bar").c_str())
    //Default no-args constructor
    .def(py::init<std::list<int>&>())
    .def(py::init());
 

  py::implicitly_convertible< std::list<int>, Foo>();
  py::implicitly_convertible< Bar, Foo>();
  
  //We're done!
  return m.ptr();

}
```


```
In [2]: example.Foo([1,2,3])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-d769230f00ee> in <module>()
----> 1 example.Foo([1,2,3])

TypeError: Incompatible function arguments. The following argument types are supported:
    1. (example.Foo) -> NoneType

In [3]: example.Foo(example.Bar([1,2,3]))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-9d8649408e2d> in <module>()
----> 1 example.Foo(example.Bar([1,2,3]))
```

**Comment by wjakob** [comment]
The trouble with this sort of thing is templates need to be explicitly instantiated for them to make sense to pybind11 (i.e. your ``template <typename Range>`` constructor is not usable).

The only thing you *could* do is to characterize the concept of iterable types on the Python side:
```
  py::class_<Foo>(m, std::string("Foo").c_str())
    //Default no-args constructor
    .def(py::init())
    .def("__init__", [](Foo &f, py::iterable it){
        std::vector<int> data(py::len(it));
        int idx = 0;
        for (py::handle el : it)
            data[idx++] = el.cast<int>();
        new (&f) Foo(data);
    });
  py::class_<Bar>(m, std::string("Bar").c_str())
    //Default no-args constructor
    .def(py::init<std::list<int>&>())
    .def("__iter__", [](const Bar &b) { return py::make_iterator(b.begin(), b.end()); }, py::keep_alive<0, 1>())
    .def(py::init());
```
To use the ``iterable`` concept, you'll need to use the latest commit (7ca275588073428bff4d8b980c31b69087750410). Not sure if that gets you where you wanted to go, but that's the limits of what this library can do.

**Comment by wjakob** [comment]
(With this, you can cast both from a list, and from your ``Bar`` type.)

**Comment by rhl-** [comment]
Right. That's what I was saying earlier.. You could imagine that the
function itself returns a function which somehow instantiates the B( A()) .
You can do this without explicit instances via decltype and declval. This
might force the compiler to provide the instantiation in the source file.

**Comment by wjakob** [comment]
Feel free to submit a PR if you have any concrete suggestions on how to implement such a feature.

**Comment by rhl-** [comment]
I had tried to mock it up two days ago, but, too much going on. I'm really
enjoying the library thus far. Is there a way I can email or IRC so I don't
spam the issues thread?

**Comment by wjakob** [comment]
I like to have all messages related to the project here. Please note that my resources for discussing this project (and extensions thereof) are extremely limited. I'll close this ticket for now as what you're proposing sounds more like a substantial extension that you should probably condense into a PR and submit when it's ready.
