### ISSUE TITLE
cast from std::string to py::str failed

### ISSUE THREAD

**Issue by bwlee** [pybind/pybind11#1700]
I failed to convert std::string with encoding UTF8 to py:str, code like below:

the input string has ASCII character and multi-bytes character mixed.  like "XXX中文"。

```
.def_property("some_utf8_string",
                    [](const Order& self) {
                      py::str py_s(self.some_utf8_string);
                      return py_s;
                    },
```

also tried:

```
   ...
                    py::bytes py_b = py::bytes(self.some_utf8_string);
                      return py::str(py_b);
```

but got a RuntimeError: "Could not allocate string object!"

BTW, this is a work around to such definition:

```
  def_readwrite("some_utf8_string", &Cls::some_utf8_string)
```
which caused segment fault. 

Any Suggestions?  

Thanks!

**Comment by leonardochung** [comment]
check the pybind11 here: https://pybind11.readthedocs.io/en/master/advanced/cast/strings.html#explicit-conversions

**Comment by bstaletic** [comment]
We have tests for this and I can't repro. The "could not allocate" could mean that you really have ran out of memory or that the input string is invalid, so `len()` returns garbage. Closing as there isn't enough here to debug further.

@bwlee If you still have troubles, feel free to reopen.
