### ISSUE TITLE
Interoperability with legacy SWIG bindings

### ISSUE THREAD

**Issue by kurt-skewton** [pybind/pybind11#1706]
Hi,

not an issue per se, but a question. 

What are the possibilities for having two sets of bindings based on pybind11 and SWIG interoperate? I have a use for a library with existing SWIG bindings, which I would like to extend preferably with pybind11 bindings. I would thus like to be able to pass around SWIG and pybind11 objects both ways. 

Is there any scope at all for doing this or this is a deal breaker and a total migration towards pybind11 is required? 

Thanks, 
Kurt

**Comment by eacousineau** [comment]
It depends on what CPython internals SWIG is able to expose.

As an example, you can look at projects that have interop with other bindings, like VTK and its Python binding layer (using its rich object model to handle stuff):
https://stackoverflow.com/questions/54871216/pybind11-return-c-class-with-an-existing-python-binding-to-python

Specifically, you'd need something like these type casters:
https://github.com/EricCousineau-TRI/repro/blob/b9e02d6d5a71f6315b80759ba1628b4bb383c0b8/python/vtk_pybind/vtk_pybind.h#L20

Another example are OpenCV + pybind interop. Some examples / discussions:
https://github.com/pybind/pybind11/issues/538
https://github.com/edmBernard/pybind11_opencv_numpy

**Comment by bstaletic** [comment]
Considering there was no follow up, I'm closing this. Reopen if necessary.
