### ISSUE TITLE
[HELP] Adding a custom method to the embedded interpreter.

### ISSUE THREAD

**Issue by kotbegemot** [pybind/pybind11#1707]
I use embedding of the interpreter and modules.
How to throw a C ++ method from a class (it can be private)?

```C++
class a {
public:
	auto read() -> std::string {
		return std::string("qwerty");	
	}
};


PYBIND11_EMBEDDED_MODULE(magic, m) {
            m.def(
                    "read",
                    []() -> std::string  {
                        /// How to get an instance of an object created in advance (from C ++)?
                    }
            );
}
```
How to get an instance of an object created in advance (from C ++)?
How to correctly forward objects created from C ++ to python (not requiring a python)?
```python3
from magic import read

def main():
	data = read()
	print(data)

if __name__ == "__main__":
    main()

```

**Comment by aoloe** [comment]
i'm not an expert, but i think you should provide a longer / better example.

from the code you're showing, it's not clear from where you want to get the instance of `a`... since you have none...

**Comment by kotbegemot** [comment]
Class a instance is created on the C++ runtime side and not on the python runtime.

**Comment by aoloe** [comment]
of course. but you must pass it over somehow... as an example by putting it in the locals...

**Comment by kotbegemot** [comment]
![111111](https://user-images.githubusercontent.com/958279/53329959-6c387a00-38fe-11e9-912f-a334b215f8f2.png)
@aoloe

**Comment by aoloe** [comment]
your shared state is in no thread, but as far as i know, your memory must be "owned" by the c++ or python thread.

you can try this: https://pybind11.readthedocs.io/en/stable/advanced/embedding.html#executing-python-code

**Comment by kotbegemot** [comment]
Read the [documentation](https://pybind11.readthedocs.io/en/stable/advanced/embedding.html#executing-python-code). 

Why can't you put an object between C++ and python and make it current to read ?

**Comment by aoloe** [comment]
in the documentation i've linked above, variables are passed to python through the `locals` c++ variable.

here you have an example i've created some time ago:

https://github.com/aoloe/cpp-pybind11-playground/tree/master/eval-set-object-module

it might or not help you with your work. it's hard for me to understand what exactly you're up to.

**Comment by kotbegemot** [comment]
Why is there such a limitation on the life cycle of an object ?

**Comment by kotbegemot** [comment]
@aoloe 
Maybe my approach? :
https://github.com/aoloe/cpp-pybind11-playground/blob/352de41fca7115e0e64ac04b71ad2120d9ed1776/eval-file/src/main.cpp#L17

**Comment by aoloe** [comment]
@kotbegemot that would share a c++ variable with python.

it might or not be the solution of your problem. it much depends on what you're up to...

**Comment by kotbegemot** [comment]
here's my integration prototype:

https://github.com/kotbegemot/smart-connect/blob/master/python_vm.cpp

https://github.com/kotbegemot/smart-connect/blob/master/read.py

@aoloe

**Comment by aoloe** [comment]
and, does it do what you need?

**Comment by kotbegemot** [comment]
I need to stretch one pointer into several interpreters.

**Comment by kotbegemot** [comment]
@aoloe

**Comment by aoloe** [comment]
sorry, i really don't know what your skills are.

i'm only a average skilled c++ and python programmer, not much more...

to me there are two possible case:

- you're an expert and i don't know what you are talking about.
- you're starting with c++ and you don't understand how memory allocation works.

with the information you gave in this ticket, i cannot really help you further. sorry.
