### ISSUE TITLE
arm cross compilation issue when need to compile to different python

### ISSUE THREAD

**Issue by lironmo** [pybind/pybind11#1718]
hellos,
i need to compile my app to different architecture and SBCs (like raspberry pi pi / banana pi /rock64/ etc)
and i see that even if i defined the python arm libs the code: find_package(PythonLibsNew ${PYBIND11_PYTHON_VERSION} REQUIRED) ignore my flags and try to detect the interpreter by it's own and failed.

**Comment by YannickJadoul** [comment]
This will probably get fixed by PR #2370 (in progress)? If not, please reopen.

**Comment by henryiii** [comment]
Let's let #2370 close it. I'm happy to add to the list the get closed. ;)

When #2370 goes in, just use either the new Python support by finding Python yourself (using the new FindPython package in CMake) or use `PYTHON_NOPYTHON=ON` to disable the integration with Python entirely, which allows you to handle Python yourself.
