### ISSUE TITLE
Using python code which is not at working directory

### ISSUE THREAD

**Issue by gmolkho** [pybind/pybind11#1719]
How can I import python script to pybind11 embedding code, from a directory which is not working directory?

The embedding examples and doc use the same folder:
"""py_module.py located in the working directory"""

**Comment by eacousineau** [comment]
I think this will generally work the same as normal Python:
Just ensure that you update `${PYTHONPATH}` or `sys.path` to capture the directory of your module, then you should be able to import it using `py::module::import`.

Another alternative is to use `execfile` (py2) or its equivalent for py3:
https://github.com/RobotLocomotion/drake/blob/a7700d3/bindings/pydrake/__init__.py#L56
However, this is more likely to have weird nuances that you won't want to deal with.

---

Meta: You may want to check out the Gitter chat room (or StackOverflow) for application or tutorial-like questions that aren't necessarily bugs / feature requests for `pybind11` code:
https://gitter.im/pybind/Lobby
https://stackoverflow.com/questions/tagged/pybind11

**Comment by necroen** [comment]
put the py_module.py into sys.path folder
