### ISSUE TITLE
Bindings for base class member functions without binding the base class

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#172]
Hi! I noticed that attempts to call bind'ed base class functions without binding the base class lead to an error. Its looks like Python expecting the base-type object instead of descendent one (see error log below). I guess this could be 'fixed' by binding lambda functions for such cases but it would be nice if that would not be necessary.

Thanks,

```C++
#include <pybind11/pybind11.h>

class Base
{
public:
	void foo_base() {}
};

class C : public Base
{
public:
	void foo_c() {}
};
namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

	pybind11::class_<C> cl(m, "C");
	cl.def(pybind11::init<>());

	cl.def("foo_c", &C::foo_c); // calling this works fine!
	cl.def("foo_base", &C::foo_base);  // calling this lead to an error!

    return m.ptr();
}
```

ipython log:
```
In [1]: c = C()
In [2]: c.foo_base()

TypeError                                 Traceback (most recent call last)
<ipython-input-2-9bea0f40fb1f> in <module>()
----> 1 c.foo_base()

TypeError: Incompatible function arguments. The following argument types are supported:
    1. (Base) -> NoneType
```

**Comment by mdcb** [comment]
The user-guide suggests:
```
py::class<Base> ...

py::class_<C> cl(m, "C", py::base<Base>());
```

**Comment by wjakob** [comment]
The type of the function ``function_base`` references a (mysterious?) type "Base" that pybind11 has never seen before. There is no automatic reflection in C++ (as of C++17) that would let the library know that one derives from the other, and in what way.

You really don't need to specify a lot, but something of the following form is mandatory:
``
pybind11::class_<Base> cl(m, "Base");
pybind11::class_<C> cl(m, "C", py::base<Base>());
``
At some point, the library may support multi-inheritance, in which case the ``py::base`` provides even more information that is really essential.

**Comment by lyskov** [comment]
I see... - thank you for explanation! And i guess in case of chain inheritance (i.e. C : public Base, Base: public BaseBase) i will need to daisy-chain all bases, right?

Out of curiosity: how expensive such 'forward' class declaration (i.e. `pybind11::class_<Base> cl(m, "Base");` with no member bind'ed? How much memory it will take? Like less then hundreds bytes on a heap or something? (i am trying to figure out if using lambda functions instead might yield some benefits etc)

Thanks!

**Comment by wjakob** [comment]
Hi Sergey,

yes, you'll need to daisy chain those definitions for a chain of derived classes. Note that multiple inheritance is currently not supported, but it does not sound like you were using that in any case.

It's hard to for me to judge the memory overhead--probably it's best to benchmark on your end. I'd say probably not more than a few hundred bytes per class (if that class doesn't have any function definition on its own).

Best,
Wenzel
