### ISSUE TITLE
doc: Make Gitter + StackOverflow links more prominent?

### ISSUE THREAD

**Issue by eacousineau** [pybind/pybind11#1724]
I've seen quite a few issues that aren't really bug reports or feature requests; the issues templates does direct people to use Gitter, but it seems that there are still quite a few issues that get by.

Would it help to make a "Getting Help" section in the RTD docs, perhaps right under "About this project", to point to Gitter / StackOverflow?

(I'm posting this assuming that this is not a huge issue, but perhaps could still be optimized. If this is a complete non-issue, feel free to close this!)

**Comment by eacousineau** [comment]
Will try to incorporate a quick link to Gitter chat + StackOverflow in issue template; that (I think) would resolve this bit.

**Comment by YannickJadoul** [comment]
I think we can close this now, especially after @henryiii's #2377, no? If not, please reopen, @eacousineau/@EricCousineau-TRI :-)

**Comment by EricCousineau-TRI** [comment]
Yup, looks better - thanks!
