### ISSUE TITLE
Incorrect version displayed on Anaconda website

### ISSUE THREAD

**Issue by wjakob** [pybind/pybind11#173]
Hi Sylvain,

when visiting the repository at https://anaconda.org/pybind/pybind11, the current version of pybind11 is listed as "v1.3", whereas 1.5 is uploaded now. I'm wondering if there is perhaps an issue with the deployment scripts that strip the "v" in the label? Or perhaps something else?

Thanks,
Wenzel

cc @SylvainCorlay

**Comment by wjakob** [comment]
@SylvainCorlay: any thoughts from your end? I was hoping that you might happen to know :)

**Comment by SylvainCorlay** [comment]
Hum, we could probably remove the conda recipe from the main repo and rely on conda-forge from now-on. It seems to be gaining traction...

**Comment by wjakob** [comment]
Sounds fine with me -- the process was a bit tedious. What's the process to keep conda-forge up-to-date with respect to the latest stable release?

**Comment by SylvainCorlay** [comment]
We change the version number in `meta.yml` and the checksum to match the one computed by pypi.

**Comment by SylvainCorlay** [comment]
cf https://twitter.com/minrk/status/729226098765107200

**Comment by wjakob** [comment]
great! see https://github.com/pybind/pybind11/commit/ace7b4386eebb3470df932ad3367d0d708d98133.
I guess I'll delete the anaconda cloud repository once the next release goes out to avoid any confusion, ok?

**Comment by SylvainCorlay** [comment]
Makes sense.
