### ISSUE TITLE
std::vector< std::shared_ptr< Eigen::ArrayXd> > to python error

### ISSUE THREAD

**Issue by XWarin** [pybind/pybind11#1730]
Hi

First thank you for the library which is very promissing. I try to get rid of boost::python and i run into some problems.
There is perhaps a bug in the following generated code.

#include <Eigen/Dense>
#include <iostream>
#include <memory>
#include <vector>
#include <pybind11/pybind11.h>
#include <pybind11/eigen.h>
#include <pybind11/stl_bind.h>
#include <pybind11/stl.h>

class toto
{
public:
    toto(){}

    std::vector< std::shared_ptr< Eigen::ArrayXd > > ret() const {
        return std::vector< std::shared_ptr< Eigen::ArrayXd> >();
    }
};

PYBIND11_MODULE(StOptRegPyBind, m) {
    pybind11::class_< toto >(m,"toto")
      .def(pybind11::init<>())
      .def("ret", &toto::ret)
      ;
}

compilation with clang gives an error.
This error disappears when removing #include <pybind11/stl.h> but then of course

>>> import StOptRegPyBind
>>> a =StOptRegPyBind.toto()
>>> b = a.ret()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unable to convert function return value to a Python type! The signature was
	(self: StOptRegPyBind.toto) -> std::vector<std::shared_ptr<Eigen::Array<double, -1, 1, 0, -1, 1> >, std::allocator<std::shared_ptr<Eigen::Array<double, -1, 1, 0, -1, 1> > > >

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,

Can you tell me if it really a bug or a problem from my soft.
Best regards

Xavier

**Comment by bstaletic** [comment]
This can easily be reproduced without Eigen:
```c++
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
struct Foo {
	Foo(){}
	std::vector< std::shared_ptr< int > > ret() const { return {}; }
};
PYBIND11_MODULE(foo, m) {
	pybind11::class_< Foo, std::shared_ptr< Foo > >(m,"Foo").def(pybind11::init<>())
		// Uncomment to reproduce the error.
		//.def("ret", &Foo::ret);
		;
}
```

**Comment by XWarin** [comment]
One way consists in using lambda functions. Here is an example using  a ret function with an argument:

#include <Eigen/Dense>
#include <iostream>
#include <memory>
#include <vector>
#include <pybind11/pybind11.h>
#include <pybind11/eigen.h>
#include <pybind11/stl_bind.h>
#include <pybind11/stl.h>

class toto
{
public:
    toto(){}
  std::vector<  std::shared_ptr< Eigen::ArrayXd > >  ret(  int i)
  {
    return std::vector<  std::shared_ptr< Eigen::ArrayXd > >();
  }
};


PYBIND11_MODULE(PyBindTest, m) {
  
  pybind11::class_< toto >(m,"toto")
    .def(pybind11::init<>())
    .def("ret", [ ] ( toto & p_x, int i )
	 {
	   auto ret = p_x.ret(i);
	   std::vector< Eigen::ArrayXd > result;
	   for(auto& array : ret)
	     result.push_back(*array);
	   return result;
	 }
	 )
    ;
}
