### ISSUE TITLE
Cannot catch C++ exception in Python

### ISSUE THREAD

**Issue by langep** [pybind/pybind11#1737]
## Issue description

I am trying to follow the docs for catching C++ exceptions on the python side but I am having troubles even when using the pybind11 tutorial or test code.

## Reproducible example code

```
git clone https://github.com/pybind/python_example.git
cd python_example
curl https://gist.githubusercontent.com/langep/2420a5ee6377eab38ff9e1849c3c8cd1/raw/bd0112dec6478b35fb4524badd8293f00af6f144/patch.diff > patch.diff
patch -p1 < patch.diff
pip install .
```

``` 
import python_example
python_example.add(1, 1) # works correctly
try:
    python_example.throw1()
except RuntimeError:
    print("we dead")
```

I except this code above to print "we dead" but I get
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  This exception was intentionally thrown.
Abort trap: 6
```

**Comment by eacousineau** [comment]
Hm... What platform are you on? The above code works perfectly for me. Expanding on your repro:

```
$ {insert your setup here, not including `pip`}
$ python3 -m virtualenv -p python3 venv
$ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l
$ ./venv/bin/python --version
Python 3.6.7
$ ./venv/bin/pip install .
$ ./venv/bin/python - <<EOF
import python_example
python_example.add(1, 1) # works correctly
try:
    python_example.throw1()
except RuntimeError:
    print("we dead")
EOF

# Output: "we dead"
```

**Comment by langep** [comment]
I am on macOS. I installed pybind with `pip install pybind11`.

```
gcc -v
>> Apple LLVM version 10.0.0 (clang-1000.11.45.5)
```
```
python --version
>> Python 3.6.1 :: Anaconda 4.4.0 (x86_64)
```

**Comment by langep** [comment]
I was able to solve the problem. It seems that compiling with clang produced some issues. If I install with the following command all is fine:

```bash
CXX=/usr/local/bin/gcc-8 pip install .
```
It would probably be good to mention this in the sample project if other people can reproduce the issue.

**Comment by eacousineau** [comment]
Huh... That's very odd to see `clang` do worse than GCC :P (Mayhaps there was an inadvertent mixture of GCC + Clang somewhere along the build?)

Thanks for following up!
