### ISSUE TITLE
Casting help / documentation

### ISSUE THREAD

**Issue by wichert** [pybind/pybind11#174]
I am trying to write some custom casters for things like Glib::ustring and boost::uuids::uuid. I can't find any documentation for type casters, so I am trying to do this by looking at `cast.h`. My current code looks like this:

```c++
template <> class type_caster<boost::uuids::uuid> {
public:
    bool load(handle src, bool) {
        object temp;
        handle load_src = src;
        if (load_src.ptr()==Py_None) {
            value=nil_gen();
            return true;
        }
        if (PyUnicode_Check(load_src.ptr())) {
            temp = object(PyUnicode_AsASCIIString(load_src.ptr()), false);
            if (!temp) { PyErr_Clear(); return false; }  // UnicodeEncodeError
            load_src = temp;
        }
        char *buffer;
        ssize_t length;
        int err = PYBIND11_BYTES_AS_STRING_AND_SIZE(load_src.ptr(), &buffer, &length);
        if (err == -1) {
            PyErr_Clear();
            return false;
        }  // TypeError
        try {
            value=parse_uuid(buffer);
            success=true;
        } catch (const std::runtime_error &e) {
            return false;
        }
        return true;
    }

    static handle cast(const boost::uuids::uuid &src, return_value_policy /* policy */, handle /* parent */) {
        if (src.is_nil())
            return handle(Py_None).inc_ref();
        std::string s(boost::uuids::to_string(src));
        return PyUnicode_FromStringAndSize(s.c_str(), static_cast<Py_ssize_t>(s.length()));
    }

    PYBIND11_TYPE_CASTER(boost::uuids::uuid, _(PYBIND11_STRING_NAME));
protected:
    bool success = false;
};
```

But that is not quite perfect: when trying to assign an invalid uuid to a boost::uuids::uuid property the error message is not very helpful:

```
>>> a.uuid = uuid.uuid4()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (stylist.Article, str) -> NoneType
```

Is there a good way to generate a better error message here?

I am also wondering if there is a convenient way to allow any input that can be coerced to a string; i.e. automatically attempt to call src.__str__ if it exists?

**Comment by wjakob** [comment]
I don't think there is much that can be done for the error message. You could change "_(PYBIND11_STRING_NAME)" to make it more clear that an UUID is expected.

For the coercion, refer to the section on implicit casting in the manual. You might need to add a new type "stringable" (terrible name, I know) analogous to iterable (pytypes.h in the latest repository version).
