### ISSUE TITLE
Add more attribute getters like object_api<>::doc()?

### ISSUE THREAD

**Issue by ultrasilicon** [pybind/pybind11#1745]
## Issue description
I was looking for a way to set `__version__` property for my module, but I didn't find a direct way of doing this in the docs. I worked around by doing: 
``` c++
PYBIND11_MODULE(MyModule, m)
{
    m.doc() = "My Module";
    m.attr("__version__") = "1.1.0";
    ...
}
```

Will it be better if we can do:
``` c++
PYBIND11_MODULE(MyModule, m)
{
    m.doc() = "My Module";
    m.version() = "1.1.0";
    m.author() = "Sponge Bob";
    ...
}
```

**Comment by YannickJadoul** [comment]
#1746 was closed with an explanation on why this wasn't included into pybind11.
