### ISSUE TITLE
Building & linking python for "relocatable" executable (Linux)

### ISSUE THREAD

**Issue by helmesjo** [pybind/pybind11#1750]
## Issue description

My case is rather simple: I've written a small C++ application which invokes a few functions from a python script. It all works fine an dandy, but the issues begin when I relocate this executable to another computer (which in turn manages python environments using anaconda).

First issue is the linking of python. Running `ldd ./my_executable` shows this line:
`libpython3.7m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0`
which won't necessarily be correct on the other computer (especially not when using conda). 
Just for test, I tried [`patchelf`](https://unix.stackexchange.com/a/479471/273609) to manually specify the python3.7 path I wanted (provided by conda). This "works" (it executes), ~but now I'm met with errors regarding "modules not found". I tried setting `PYTHONPATH=<python-dir>` and it got me somewhat closer.
It now for example finds module `queue`, but inside `queue` it fails to find `_queue`.~
_Edit: issues with finding queue module etc was because of broken environment. Starting fresh solved that_

Internet is only semi-helpful, and the conclusion is that linking python is a mess.

I've looked over the docs but haven't found anything specific to my problem.

So, my (two) question... 
1. If I use cmake to build a C++ application which in turn links pybind11, what is the correct way to manage linking python? 
2. How do I get it to work so that I just execute my application inside a conda environment at _it just works_ (the py script I execute internally runs inside this environment)?

## Reproducible example code

```
#include <pybind11/embed.h>
namespace py = pybind11;

int main(int argc, char *argv[])
{
    py::scoped_interpreter interpreter;

    // myModule imports all sorts of python libs (that are available in the conda environment)
    // It works if run from command line inside same conda environment that executable is run in.

    auto module = py::module::import("myModule");
    auto myFunc = os.attr("myFunc");
    auto res = myFunc();

    return 0;
}
```

**Comment by helmesjo** [comment]
So, to summarize, I do the following to make the executable link (and run) properly inside the conda environment:
```
#set_python_path.sh
PY_LIB_PATH="${1}"
patchelf --remove-needed libpython3.7m.so.1.0 marker_identifier
patchelf --add-needed $PY_LIB_PATH marker_identifier
```

I call it like this (in the same folder as the executable):
`./set_python_path.sh "path/to/specific/python/libpython3.7m.so.1.0`

Obviously this is a pretty ugly workaround. What is the "correct" way to do it, so that at run-time it finds the correct python lib (for the current conda environment) itself?

**Comment by skoslowski** [comment]
Hey, without a CMakeLists it's kind of hard to exactly reproduce something and from your description this seems not really pybind11 related. Nevertheless maybe these are of help:
* checkout relative RPATHs to replace that script (CMake has support for that)
* conda itself appears statically link libpython for its python binary (on Linux)
* shouldn't conda packaging guidelines cover how this is supposed to be handled

**Comment by helmesjo** [comment]
Yes indeed, this is not an issue caused by `pybind11`, just a bi-effect really. 
Just figured there must have been a few people with similar requirements, and your info is appreciated!

I'll have a look at it and see what I can figure out. Thank you!
