### ISSUE TITLE
Read/write dynamic attributes from C++

### ISSUE THREAD

**Issue by ahgamut** [pybind/pybind11#1751]
## Description

From the [documentation](https://pybind11.readthedocs.io/en/stable/classes.html#dynamic-attributes), I can use `pybind11` to access dynamic attributes in python.

Now, can I do the same from within C++?
(i.e. read/write `self.__dict__['age']` or `self.attr('age')` )?

## Example Code

For example, is it possible to do:

``` c++
// relevant includes

struct Pet {
    Pet(const std::string &name, unsigned int age){
    this->name = name;
    this->setattr("age") = age; //something like this
 }
    unsigned int age_calc(){
    unsigned int x = this->getattr("age");  // or like this
    // do some calculations with x
    return x+1;
}
    std::string name;
};

PYBIND11_MODULE(example, m)
{
py::class_<Pet>(m, "Pet", py::dynamic_attr())
    .def(py::init<>())
    .def("age_calc", &Pet::age_calc)
    .def_readwrite("name", &Pet::name);
}

```

```python
z = example.Pet("Molly1", 32)
z.__dict__
# {'age' : 32}
z.age_calc()
# 33
z.age = 45 # or z.__dict__["age"] = 45
z.age_calc()
# 46
```

**Comment by eacousineau** [comment]
Er, why do you want to access dynamic attributes from the C++ class itself?
If your interface is heavily Pythonic, why not just implement the core of it in Python?

You can always do weird things to permit the C++ object to get a hold of its `pybind`-registered instance, but that's a bit weird unless your are writing for virtual inheritance (in which case, I'm still not sure how to access the object efficiently).

If you're OK with overt inefficiency, and assuming the C++ object always lives in `pybind11`:
```
py::object sefl = py::cast(this, py_reference);
self.attr("yadda_yadda")
```

**Comment by ahgamut** [comment]
> Er, why do you want to access dynamic attributes from the C++ class itself?
> If your interface is heavily Pythonic, why not just implement the core of it in Python?

Yeah, I ended up keeping only the faster stuff  in C++, and writing the rest in a Python subclass.
(I wanted to have a dynamic attribute `numpy.ndarray` which could change sizes through the lifetime of the object.)

> If you're OK with overt inefficiency, and assuming the C++ object always lives in `pybind11`:
> 
> ```
> py::object sefl = py::cast(this, py_reference);
> self.attr("yadda_yadda")
> ```

Thanks for this, I'll try it out and see if the efficiency loss turns out to be an issue.
