### ISSUE TITLE
Where to put the .pys for embedding of a Python repo?

### ISSUE THREAD

**Issue by Spixmaster** [pybind/pybind11#1754]
How can I embed this [repo ](https://github.com/LevPasha/Instagram-API-python)with pybind11 in C++?

# My Visual Studio project setup:
1. Python header and library files (libs) are stated in "properties > VC++ Directories"
2. /Lib from Python installation folder is put in folder with the .vcxproj
3. .py is  in release folder which contains the .exe

# example
`#include <iostream>
#include <pybind11/embed.h>

namespace py = pybind11;

int main()
{
	py::scoped_interpreter guard{}; // start the interpreter and keep it alive

	py::print("Hello, World!"); // use the Python API

	int i;
	std::cin >> i;
	return 0;
}`

This code runs so far so I guess that so far I did everything right.

# Embedding
I have tested embedding which also works.

## calc.py
`def add(a, b):
    return a+b`

## Location I put the file
I put calc.py in the release folder with the .exe and the following program ran:
`#include <iostream>
#include <pybind11/embed.h>

namespace py = pybind11;

int main()
{
	py::scoped_interpreter guard{}; // start the interpreter and keep it alive

	py::module calc = py::module::import("calc");
	py::object result = calc.attr("add")(1, 2);
	int n = result.cast<int>();
	
	std::cout << "The result: " << n << std::endl;

	int i;
	std::cin >> i;
	return 0;
}`

# My question
I want to embed this app: https://github.com/LevPasha/Instagram-API-python
What do I need to do to call the constructor from this file: https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI/InstagramAPI.py

I already have installed the repository with pip and I know that I find its installations folder with `pip show InstagramAPI`. Do I need to put the files in the release folder of the Visual Studio project again?

These are the dependencies of the Instagram Api: 

> Requires: requests, requests-toolbelt, moviepy
Do I need to consider them anyhow?

I am desperate as I am trying it for days now. Please help me.

**Comment by YannickJadoul** [comment]
Python looks as `sys.path` to look for imports. Same goes here, probably: your files/packages need to be in a folder on `sys.path`.

You can change this with pybind11 with `py::cast<py::list>(py::module::import("sys").attr("path")).append(...)`.
