### ISSUE TITLE
Automatically export enum values (inspired by magic_enum)

### ISSUE THREAD

**Issue by jeanga** [pybind/pybind11#1759]
Hi,

I recently came accross https://github.com/Neargye/magic_enum which enables a number of scenarios like enum values conversion to strings (and vice versa) using nice c++17 tricks.

I was wondering if this library could be used (or inspire) similar work in pybind11 to automatically export C++ enums to python...

Thank you for the great pybind11, I've been using for some time now and it really does wonders!
Jean

**Comment by bstaletic** [comment]
magic_enum relies on compiler implementation details. For that reason, I don't want to include similar stuff into pybind11. Let's hope C++23 actually gives us reflections.

**Comment by YannickJadoul** [comment]
There's probably a way to use magic_enum on top of pybind11 though, and basically call the `enum_::value`?

**Comment by YannickJadoul** [comment]
Something like this? (warning: untested code)

```C++
template <typename E, typename... Extra>
py::enum_<E> export_enum(const handle &scope, Extra&&... extra) {
    py::enum_<E> enum_type(scope, magic_enum::enum_type_name<E>(), std::forward<Extra>(extra)...);
    for (const auto &[value, name] : magic_enum::enum_entries<E>()) {
        enum_type.value(name, value);
    }
    return enum_type;
}
```

**Comment by bstaletic** [comment]
Two mistakes in @YannickJadoul's snippet:

1. `enum_type_name` returns a `string_view`, so you need its `data()`.
2. `enum_entries` also returns `name` as `string_view`, so again you need its `data()`.

**Comment by YannickJadoul** [comment]
Ha, only two? ;-) Didn't know about the actual types, since I just glanced at the README and it said `auto`.

> (warning: untested code)

Anyway, yes, the main purpose was to demonstrate it's perfectly possible to use without core pybind11 support for it ;-)
