### ISSUE TITLE
Request for new return value policy

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#176]
The ``return_value_policy::reference_internal`` does two things:

- it says that the new object is not "owned", so it should not be deleted when its Python reference count goes to zero;
- it increments the Python reference count of the parent, so it will not be deleted while there are children.

There are however situations where you want only the latter to happen.
Case in point, a container returning an iterator object. The container should be kept alive as long as there are iterators around, but the container should not be responsible for keeping track of, and ultimately destroying, all its iterators.

I would like to request a new return value policy which only does the latter.

**Comment by wjakob** [comment]
You're looking for the ``keep_alive`` call policy, which can do this sort of thing (and much more). See the advanced section of the docs for details.

**Comment by wjakob** [comment]
It's not restricted to return values, hence the name "call policy"

**Comment by pschella** [comment]
Thank you. That seems to work. I was just expecting it to be a return value policy. Perhaps add it as an alias? With the first parameter always set to 0?

**Comment by wjakob** [comment]
I rewrote the return value policy parts of the docs and added a more explicit reference to call policies, so hopefully it's more clear now.
