### ISSUE TITLE
access self  or this from lambda wrapper of class member functions

### ISSUE THREAD

**Issue by yuewu001** [pybind/pybind11#1763]
I have a class whose member function accepts a dictionary of parameters.

```c++
class A {
public:
    void Func(const vector<pair<string, string>> & params);
};
```
To expose this func, I use a lambda wrapper:

```c++
py::class_<A>(m, "A")
    .def("Func", [](py::kwargs kwargs) {
             // convert kwargs to vector<pair<string, string>>
             // call A->Func
          });
```

Anyone knows how to call A->Func?

**Comment by antonmilev** [comment]
Yue Wu - Did you get answer?

**Comment by rear1019** [comment]
This should work:
```cpp
.def("Func", [] (A &self, py::kwargs kwargs) { self.Func(converted_kwargs); });
```

The documentation has an example where ``self`` is passed to a lambda [1]. However, it’s not that clear and obvious that you can pass ``self`` this way.

[1] https://pybind11.readthedocs.io/en/stable/classes.html#binding-lambda-functions

**Comment by YannickJadoul** [comment]
Thanks for answering, @rear1019!

> The documentation has an example where `self` is passed to a lambda [1]. However, it’s not that clear and obvious that you can pass `self` this way.
> 
> [1] https://pybind11.readthedocs.io/en/stable/classes.html#binding-lambda-functions

The examples do show it, here. And it is consistent with Python that you need to explicitly accept `self` as first argument.

**Comment by tkkcc** [comment]
@YannickJadoul No. It works just like python class method.

```c++
PYBIND11_MODULE(pybind, m)
{
  NDArrayConverter::init_numpy();
  py::class_<DenseInverseSearch>(m, "DenseInverseSearch")
      .def("calc", [](DenseInverseSearch& algorithm, cv::Mat& I0, cv::Mat& I1, cv::Mat& flow) {
        return 0;
      })
      .def(py::init());
}
```
Right way to call it:
```py
algorithm=DenseInverseSearch()
algorithm.calc(I0,I1,flow);
```
Raise error:
```py
algorithm=DenseInverseSearch()
algorithm.calc(algorithm,I0,I1,flow);
```

**Comment by YannickJadoul** [comment]
@tkkcc 

No, I'm right. I said

> explicitly accept `self` as first argument.

I didn't say "explicitly pass `self` as first argument.

Your `[](DenseInverseSearch& algorithm, cv::Mat& I0, cv::Mat& I1, cv::Mat& flow)` is doing exactly what I said, "accepting the object as first argument, like `self` in Python".

**Comment by tkkcc** [comment]
@YannickJadoul Sorry, my mistake. (o_ _)ﾉ

**Comment by YannickJadoul** [comment]
@tkkcc, no worries! (But I knew I was right ;-) )
