### ISSUE TITLE
question on returning values and memory management

### ISSUE THREAD

**Issue by rhl-** [pybind/pybind11#177]
Hi,

Suppose I have wrapped a container class `class Foo`

and then I wrap a function:

`Foo construct_foo( ... parameters ...)`

When I call `construct_foo` on the python side, there is a memory management issue. I'm not clear from the examples and documentation on what the appropriate way to return the object. In particular, I want to  avoid copies of `Foo` instances will generically be massive..

**Comment by wjakob** [comment]
When you return by value, a copy will have to be made. Return a Foo pointer and use the automatic return value policy.

**Comment by rhl-** [comment]
when it returns by value, and the value is movable, does it end up performing a move? its odd that you need to return a pointer, because how does pybind know how to delete the object? who said it was allocated via new? 

Its safer to return by value, and then have pybind move (which will be free for well designed objects, which reference heap memory..)

**Comment by wjakob** [comment]
Feel free to run some experiments on things like this yourself before posting questions ;). I would like to keep this issue tracker for actual issues.

**Comment by rhl-** [comment]
@wjakob thats why I asked for another place to ask these questions. You previously said you wanted all questions on this issue tracker. Although, point taken. But, for things like this I think it is quite unreasonable to ask people to figure them out on there own. You should document this stuff. And if it isn't right that provides people a place to jump in and help. Comments in code help too, especially when 99% of your library is meta code.

**Comment by wjakob** [comment]
Realistically, I think the documentation for this project is already fairly extensive and it's not going to get much bigger. This is an open source project, so feel free to jump in. 

When submitting issues, I really prefer to have an actual example that I can work with (see also https://github.com/pybind/pybind11/blob/master/CONTRIBUTING.md). In this case, it could have been a piece of code with actual output: copy constructor called, wanted output: move constructor called.

**Comment by rhl-** [comment]
Well if it won't get bigger than I guess I shouldn't help because you are happy with it how it is.. Clearly I'm the only person who is confused or concerned about these issues.

**Comment by wjakob** [comment]
Not necessarily -- just keep in mind that this is a 1-person hobby project, so any steps you can do on your end to reduce effort on my end is appreciated, e.g. by putting together a self-contained and minimal example that illustrates your issue or question. (And please, realize that I simply don't have time to write vast amounts of additional documentation myself, though I welcome PRs with clarifications)

I eventually realized what issue you refer to above, and that was indeed a good point. It is fixed in
https://github.com/pybind/pybind11/commit/f7b5874ca34634ed281b32f8013f5afdde808f50

**Comment by rhl-** [comment]
thanks.. I appreciate the effort your putting in :) If I could send you tenure points, I would.

**Comment by JendaPlhak** [comment]
We all do. I would even send some donations, if you would have an account and could make some good use of the money for purposes of further development of this project.

**Comment by esoha-nvidia** [comment]
The "automatic" mode is described here: https://pybind11.readthedocs.io/en/stable/advanced/functions.html?highlight=automatic%20return%20value#return-value-policies
