### ISSUE TITLE
Segmentation fault (core dumped) when run in python

### ISSUE THREAD

**Issue by PistonY** [pybind/pybind11#1770]
My code could run in C++ correctly.
And I use pybind11 generate .so file. Then I use python run the code the same as C++ but got `Segmentation fault (core dumped).`
Could you please give me some advice to solve this?

**Comment by eacousineau** [comment]
Per the issue template, can you post a minimal reproduction recipe that is specific to `pybind11`? (e.g. please make a single program, strip out the minimal set of code that reproduces the segfault, ensure that it doesn't need to link to all your C++ code, and post it here)

https://github.com/pybind/pybind11/blob/master/ISSUE_TEMPLATE.md
