### ISSUE TITLE
Returning new instances of a derived type via a virtual factory function fails to keep the derived type alive

### ISSUE THREAD

**Issue by yeswalrus** [pybind/pybind11#1774]
Given a virtual function meant to return new instances of a type via a pointer to a base class, and a derived type declared in python, the return value cast won't keep the python object alive, resulting in a failure when attempting to call the virtual method on the new instance via the pointer. Because this function is called from c++, the return value policy has no effect.

## Reproducible example code
https://github.com/yeswalrus/pybind11/tree/virtual-vector-return

**Comment by eacousineau** [comment]
I believe this may be the 5th issue that tracks this problem :P
Ultimately, it's [Object Slicing](https://en.wikipedia.org/wiki/Object_slicing).

Related issues:
- #1145 (mine, but using company acct)
- #1333
- #1389
- #1546

I've worked around this in [our fork](https://github.com/RobotLocomotion/pybind11/tree/drake) of `pybind11`, but have not yet figured out a good way to make it useful for mainstream consumption. (The [`py::wrapper`](https://github.com/RobotLocomotion/pybind11/blob/f2bd883d3f2f47d7b3049af6fbe48585b6417204/include/pybind11/pytypes.h#L1350) class it introduces is... well... a lot of blech.)

While my patch above works and is conservative for object lifetime, it may be costly (in object code and possibly runtime performance).

Simpler workarounds, suggested in the aforementioned issues, point towards making something like `keep_alive_forever`, which could be done by stashing `py::object` inside the Python trampoline class. In this fashion, Python may never delete until the interpreter shuts down, but it could be "deletable" by C++.

As far as issue tracking goes, I'll try to see which thread has the best recommendations, and see if we can consolidate the current duplicates.

**Comment by yeswalrus** [comment]
Ahh, sorry about the duplicate. Yeah, I dug into it in a debugger over the weekend a little bit - I was thinking something along the lines of making the trampoline class store a handle to the underlying python object would be a necessity.

**Comment by mmodenesi** [comment]
> ## Reproducible example code
> 
> https://github.com/yeswalrus/pybind11/tree/virtual-vector-return

@yeswalrus what is the reproducible example, exactly? Thanks!

**Comment by EricCousineau-TRI** [comment]
Closing this in lieu of #1333 for tracking.
