### ISSUE TITLE
Does there exists alternative for opaque pointer compared with boost python?

### ISSUE THREAD

**Issue by daleydeng** [pybind/pybind11#1778]
opaque pointer occured frequently in thirdparty library,  can this be done?

https://stackoverflow.com/questions/50641461/dealing-with-opaque-pointers-in-pybind11

**Comment by eacousineau** [comment]
Just responded there: https://stackoverflow.com/a/55991847/170413

**Comment by YannickJadoul** [comment]
Answered by @eacousineau on SO:

> If your goal is to simply permit passing pointers of a C++ object to Python without exposing information, you should just be able to register the class:
> 
> ```
> PYBIND_MODULE(mymodule, m) {
>  py::class_<mystruct>(m, "mystruct");
>  m.def("f1", &myfunction1);
>  m.def("f2", &myfunction2);
>}
>```
>
> If you wish to avoid conflict with other pybind11 modules that might declare types on this third-party type, consider using `py::module_local()`:
>
> https://pybind11.readthedocs.io/en/stable/advanced/classes.html#module-local-class-bindings

Thanks, @eacousineau!

**Comment by nonatomiclabs** [comment]
Hi @eacousineau , @YannickJadoul 

I have the same issue the OP talked about and can't seem to make it work, even using the solution provided on StackOverflow.

I have the following files:

~~~cpp
// File "header.h"
typedef struct mystruct* mystruct_t;
void myfunction1(mystruct_t x);
mystruct_t myfunction2();
~~~

~~~cpp
// File playground.cpp
#include <pybind11/pybind11.h>
#include "header.h"

namespace py = pybind11;

PYBIND11_MODULE(mymodule, m) {
  py::class_<mystruct>(m, "mystruct");
  m.def("f1", &myfunction1);
  m.def("f2", &myfunction2);
}
~~~

I compile them with the following `CMakeLists.txt`:

~~~cmake
project(PLAYGROUND)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

add_subdirectory(../submodules/pybind11 build_pybind11)

pybind11_add_module(xhe_aac_encoder_lib_wrapper
    playground.cpp
)
~~~

When I compile this, I get few errors, all along the lines of `error: 'typeid' of incomplete type`.

Is there anything I missed in my example to make it work?

**Comment by YannickJadoul** [comment]
@nonatomiclabs, apologies for the late reply. What you're missing is a non-forward declaration of the type. I don't see your full error, but pybind11 seems to be taking the `typeid` of the `mystruct` type, and it cannot do that without a definition of the class.

**Comment by shakfu** [comment]
> @nonatomiclabs, apologies for the late reply. What you're missing is a non-forward declaration of the type. I don't see your full error, but pybind11 seems to be taking the `typeid` of the `mystruct` type, and it cannot do that without a definition of the class.

@YannickJadoul I have exactly the same issue as @nonatomiclabs 

Can you please expand on this your given advice "it cannot do that with a definition of a class"? What if you don't have access to the definition of the class because the `mystruct` is opaque?

Does one have to write a wrapper class and treat the mistruct pointer as a member, and then wrap the wrapper class?
