### ISSUE TITLE
Error scope constructor causes access violation in ~error_already_set()

### ISSUE THREAD

**Issue by AndreasSchoenle** [pybind/pybind11#1779]
When using error_already_set() in code that is called from a C++ program, the error_scope constructor crashes due to non-existent thread state. The C++ Code acquires the thread state through PyGILState_Ensure(), when throwing the error_already_set() PyGILState_Release() is called during thread exit. 

It seems to me that when the destructor is called, the crash occurs because the current thread does not hold the GIL. 

About the destructor:
https://github.com/pybind/pybind11/blob/e2b884c33bcde70b2ea562ffa52dd7ebee276d50/include/pybind11/pybind11.h#L1991

Could it be that the two calls:
```
error_scope scope;
gil_scoped_acquire gil;
```
have to be reversed? Also, why is error_scope needed - as I understand we just need the GIL to decrease the ref count on the held error objects?

**Comment by eacousineau** [comment]
Hm... Seems like it might be that. Any chance you have a simple minimal reproduction, where you can toggle the ordering / remove `error_scope` to see if that fixes it?

**Comment by wjakob** [comment]
I've just run into this myself, and the fix that you suggested looks good to me.
The `error_scope` is needed for module initialization, see https://github.com/pybind/pybind11/pull/1362.
