### ISSUE TITLE
Exposing type as class attribute

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#178]
For a class:

    class A {
    public:
        typedef B value_type;
    ...

for some other pybind11 wrapped type `B` is it possible to expose
`value_type` as a class attribute (of `A`) tied to the class type object for `B` in Python?

**Comment by rhl-** [comment]
Adapted from here:  http://pybind11.readthedocs.org/en/latest/advanced.html
`m.attr("value_type") = py::cast(decltype(A::value_type));`
but this is not associated to A. not sure if attr() works on py::class

Python doesn't have types, so its not clear what you would want to do with this..

Perhaps you could create a member function ``value_type`` which returns an instance of ``value_type``?

**Comment by pschella** [comment]
It should be a class attribute that holds a reference to the class object B, not an instance of B.
The equivalent in Python would be:

    class B:
        pass

    class A:
        value_type = B

**Comment by wjakob** [comment]
If "B" is another type that was registered, there will be a ``class_`` object somewhere. Can't you do
```
A.attr("B") = B_class;
```
or
```
A.attr("B") = m.attr("B");
```
where ``m`` is the module.

**Comment by pschella** [comment]
This works, but unfortunately not across different modules (defined in different translation units).
In my case `A` is in `moda` (`libmoda.so`) and `B` in `modb` (`libmodb.so`).

**Comment by wjakob** [comment]
Then how about ``py::import("modb").attr("B")``?

**Comment by pschella** [comment]
Thanks! `py::module::import("modb").attr("B")` works.

**Comment by wjakob** [comment]
Import was described in the documentation, btw.
