### ISSUE TITLE
Convenience functions for casting between PyObject and underlying smart pointer

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#179]
When integrating pybind11 with other Python wrapper tools it is often necessary to extract smart pointers from pybind11 wrapped objects or conversely construct a `pybind11::object` from a smart pointer. For instance the following swig typemaps will allow swig wrapped functions to accept and return pybind11 wrapped `MyType` objects (backed by a `shared_ptr`).

    %typemap(out) std::shared_ptr<MyType> {
        /* Use a pybind11 typecaster to create a PyObject from a shared_ptr<MyType> */
        pybind11::detail::type_caster<std::shared_ptr<MyType>> caster;
        pybind11::handle out = caster.cast($1, pybind11::return_value_policy::take_ownership, pybind11::handle());
        $result = out.ptr();
    }

    %typemap(in) std::shared_ptr<MyType> {
        /* First make a pybind11 object handler around the PyObject *
         * Then, cast it to a shared_ptr<MyType> using the pybind11 caster. */
        pybind11::object p{$input, true};
        try {
            std::shared_ptr<MyType> ptr(p.cast<std::shared_ptr<MyType>>());
            $1 = ptr;
        } catch(...) {
            PyErr_SetString(PyExc_RuntimeError, "could not cast to shared_ptr<MyType>");
            return nullptr;
        }
    }

But this exposes quite a bit of the internals of pybind11 (namely the typecaster). It would be nice if pybind11 included a few convenience functions to do this.

**Comment by rhl-** [comment]
Have you read: http://pybind11.readthedocs.org/en/latest/advanced.html#unique-pointers
and the next one on smart pointers?

Can you comment on how your use case differs from those documented or in the examples?

**Comment by wjakob** [comment]
To add to rhl-'s comment, I am also very confused by the combination of SWIG and pybind11. Why would one combine two different binding toolkits?

**Comment by pschella** [comment]
Because we have a very large existing codebase which is wrapped with SWIG. If we choose to adopt pybind11 instead, a gradual transition is necessary. So the two toolkits will need to coexist for a time.

**Comment by wjakob** [comment]
@pschella: So is there an actual issue here? Can you clarify how your use case is not covered by the section on smart pointers in the documentation?

**Comment by pschella** [comment]
It isn't so much an issue as it is a feature request. When integrating with different wrapping tools you often have functions that take a `PyObject*` argument (to a pybind11 wrapped type). What is needed is a convenient way of extracting the `shared_ptr<MyType>` from it. And, in the other direction, to create a `pybind11::object` from a `shared_ptr<MyType>` and get a `PyObject*` from it to give back to Python through the other wrapper tool (say when a SWIG function has to return a new instance of a pybind11 wrapped type).

**Comment by wjakob** [comment]
``handle(myPyObject).cast<std::shared_ptr<MyType>>()``

and

``py::object o = py::cast(mySharedPtr)``

**Comment by wjakob** [comment]
(FWIW Both of these are described in the advanced section of the docs)

**Comment by pschella** [comment]
Indeed they are, in "Functions taking Python objects as arguments". Don't know how I overlooked that.
