### ISSUE TITLE
Bind Eigen::Matrix using custom scalar (non-POD) type

### ISSUE THREAD

**Issue by mrspacemankey** [pybind/pybind11#1799]
## Issue description

I have a complex scalar type that I am using with Eigen. I would like to wrap this special Eigen::Matrix<Scalar,...> class with pybind, and it needs to interact with normal Eigen classes (e.g. Eigen::Matrix<double,...>). This complex scalar type is not a POD class, so numpy.h complains it can not define a type caster for it.

There are two ways I see this working.
1. Disable automatic Eigen wrapping code generation for Eigen::Matrix<Scalar,...>. I have to include eigen.h since it has constructors from Eigen::Matrix<double,...>

2. Wrap the complex scalar type to be used with dtype in numpy. Since it is not a POD class, I don't know how to do this (and is probably not what I want).

Option 1 is preferable and hopefully easier to implement. I looked at eigen.h but could not find an straightforward way.

Thank you in advance for you replies.

**Comment by uentity** [comment]
Maybe you can consider third option of making opaque binding your custom Eigen matrix and implementing the buffer protocol as described in https://pybind11.readthedocs.io/en/latest/advanced/pycpp/numpy.html?

**Comment by eacousineau** [comment]
Posted some add'l potential solutions in Gitter as well:
https://gitter.im/pybind/Lobby?at=5cff9bee84c08f5414141da6

To combine with @uentity's answer and address your proposal (1), you could prolly snag the `type_caster<>` resolution with some SFINAE logic, even with including `pybind11/eigen.h`.

For proposal (2), I mentioned in Gitter that there are two ways: (a) binding the class for `dtype=object` (significantly easier, but you can't do `rvp::reference_internal` with those matrices) or (b) do `dtype=user`, but that's way more sketchy. Both things require changes to `pybind11` master to work, though :(

**Comment by mrspacemankey** [comment]
Thank you for you suggestion. I do not wish to expose the Scalar type through the buffer protocol to python, but would rather hide the implementation. The reason is that it is quite complex and not arithmetic type. I attach below a minimum example.

```
#include <pybind11/pybind11.h>
#include <pybind11/operators.h>
//#include <pybind11/eigen.h>
#include <Eigen/Core>

class MyScalar
{
public:
    MyScalar() : value_{ 0.0 } {}
    MyScalar( double value ) : value_{ value } {}
    double value() const { return value_; }
private:
    double value_;
    std::vector< double > gradient_;
};

using EigenVector = Eigen::Matrix< double, Eigen::Dynamic, 1 >;
using MyVector = Eigen::Matrix< MyScalar, Eigen::Dynamic, 1 >;

MyVector create( const EigenVector& vec )
{
    return vec.template cast< MyScalar >();
}

void initVector( pybind11::module& m )
{
    pybind11::class_< MyVector >( m, "MyVector" )
        .def( pybind11::init( []() { EigenVector x( 3 ); x << 1, 2, 3 ; return create( x ); } ) )
        .def( pybind11::init( []( const EigenVector& value ) { return create( value ); } ) );

    m.def( "test", []( const MyVector& vec ) { return vec[0].value(); } );
}
```

This works fine as long as I only use the first constructor. If I want to use the second constructor, which uses an eigen vector as input, I get a runtime error when I want to pass a numpy array (incompatible arguments). If I uncomment the line that includes pybind11/eigen.h, I get a compile error when trying to bind "test" function.
```
/local/scratch/gvarga/godot/pybind/libs/core/autodif/Vector.cpp:47:73:   required from here
/home/orbsw/orb3rd/include/pybind11/numpy.h:1126:5: error: static assertion failed: Attempt to use a non-POD or unimplemented POD type as a numpy dtype
     static_assert(is_pod_struct<T>::value, "Attempt to use a non-POD or unimplemented POD type as a numpy dtype");
```

I do not want to expose 'MyScalar' as a POD type to numpy, as I do not want numpy to take care of that object. I would like to force pybind to provide the wrapper normally for EigenVector, but disable the automatic wrapping for MyVector (at least between numpy and Eigen).

**Comment by mrspacemankey** [comment]
Based on answer from @eacousineau I managed to disable the automatic eigen binding generation and solving the issue using option 1. I attach the small code snippet that worked (together with the previous example).

```
namespace pybind11 {
namespace detail {
    template <>
    class type_caster< MyVector, void > : public type_caster_base< MyVector >
    {
    };
} }
```

One would need to disable the binding for other eigen types using some templates.
