### ISSUE TITLE
git tag v2.3.0 points to version v.2.3.dev0

### ISSUE THREAD

**Issue by skoslowski** [pybind/pybind11#1805]
Thanks for pushing out a new release!

I noticed to commit pointed to by the tag v2.3.0 still has the version v2.3.dev0 specified in the sources. e.g. 
https://github.com/pybind/pybind11/blob/cf36e3d9baa7c771115edae1b16353793eecf1ac/include/pybind11/detail/common.h#L97

I am not sure if this is intended, but since this propagates up to the CMake version I had to go with the branch v2.3 which has the version bumped to v2.3.0

**Comment by wjakob** [comment]
whoops, that's bad! fixed now.
