### ISSUE TITLE
Dependency on PythonX.dll

### ISSUE THREAD

**Issue by dvfdr43** [pybind/pybind11#1808]
I've compiled my application with /MT but it still depends on pythonX.dll

Is it possible to remove the dependency and embed code using pythonX.lib

IDE: VS2017

**Comment by YannickJadoul** [comment]
This is not a pybind11 related question, but something inherent to embedding the CPython interpreter.

See also this SO question and answer: https://stackoverflow.com/questions/3953039/embedding-python-on-windows-why-does-it-have-to-be-a-dll
