### ISSUE TITLE
get c++ pointer from instance initialized at the python side

### ISSUE THREAD

**Issue by fortuneko** [pybind/pybind11#1810]
Hi, i want to get an custom class instance pointer in the c++ side, the custom class instance was initialized at the python side, i want transfer it to other c++ class by call a funcuntion exported python like set_custom_instnace(python_inst)
how can i do to make this work? thanks

**Comment by eacousineau** [comment]
Can you post what you've tried, either as a small snippet (like <30 lines) or a GitHub Gist or something?

**Comment by eacousineau** [comment]
In general, if you're looking at ownership transfer, you should look at return value policies and smart pointers / holders:
https://pybind11.readthedocs.io/en/stable/advanced/functions.html#return-value-policies
https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#std-shared-ptr

**Comment by fortuneko** [comment]
@eacousineau ,thank you for your reply. What i want to do is like this below

```c++
class A{
 ...
}
class B{
  void set_inst(py::class_<A> inst){
       //this is the code where i need to implement
       //A *p_inst_a = inst.get_ptr_xxx()
  }
}
PYBIND11_MODULE(test, m) {
  py::class_<A> a(m, "A");
  py::class_<B> b (m, "B");
  b.def(py::init<>())
          .def("set_inst", &B::set_inst);

}

```

**Comment by bstaletic** [comment]
Wouldn't that `.get_ptr_xxx()` be just `.ptr()`? Also, don't pass `class_` by value. You don't want to copy that thing.

**Comment by YannickJadoul** [comment]
Just accepting `void set_inst(A *inst){` will have pybind11 automatically do the conversion for you, no? Or am I missing something?

Taking away ownership from Python is not possible, though. Python implicitly shares ownership of objects (because of the garbage collector), so if you want the C++ class to share ownership, you have to use a `shared_ptr` holder.

**Comment by YannickJadoul** [comment]
I'll close this. Please reopen (or come to [Gitter](https://gitter.im/pybind/Lobby)) if this is still a problem.
