### ISSUE TITLE
Unable to pass `std::string` as `bytes` from c++ to python

### ISSUE THREAD

**Issue by Notmeor** [pybind/pybind11#1811]
## Issue description

Unable to pass `std::string` as `bytes` from c++ to python

My c++ function is a callback that gets overwritten in python, the problem is that it has an argument that receives `std::string`, which is not valid utf8, and I want the argument passed in as `bytes` in the python context.

How could i achieve this? Failed to figure it out from the docs.

**Comment by sizmailov** [comment]
You can create `py::bytes` from `std::string` and call callback
```c++
py::bytes bytes(std_string.c_str());
callback(bytes);
```

**Comment by Notmeor** [comment]
Very helpful, it works! But I'm still wondering whether this could be done directly in the PYBIND11_MODULE scope.

**Comment by eacousineau** [comment]
Sorry, I'm not sure if I completely understand; can I ask what you mean by `PYBIND11_MODULE` scope in this case?

Is it that you're passing bytes from C++ to Python (via your callback), and you currently have to do your conversion as mentioned above:
```
std::string x(...);
std::function<void (py::bytes)> callback;
callback(py::bytes(x));
```
but instead want to have `string` be readily convertible to bytes in Python?
```
std::string x(...);
std::function<void (std::string)> callback;
callback(x);  // in Python, `x` is of type `bytes`
```

If so, I'm not sure if that's feasible?

From looking at the `type_caster` code for strings, it looks like going from Python to C++ *does* permit converting `py::bytes` to `std::string` if the data are not UTF-N convertible:
https://github.com/pybind/pybind11/blob/a1b71df137e015d44f7e31f7b6d4807253fb7871/include/pybind11/cast.h#L1177-L1180

However, going from C++ to Python, it always attempts to decode as UTF-N (and thus always return a Python 3 `str`):
https://github.com/pybind/pybind11/blob/a1b71df137e015d44f7e31f7b6d4807253fb7871/include/pybind11/cast.h#L1214

**Comment by Notmeor** [comment]
Yeah, that's what I meant. Could I achieve this with my **existing c++ code intact**, by only make some delarations in the 'pybinding' part?

**Comment by bstaletic** [comment]
I've done this once. By creating a custom caster for `std::string` specifically. Two steps:

1. Assuming the python -> C++ direction works for you, inherit the default string caster, so that `load()` is written for you.
2. Override `cast()`, so that, instead of `decode_utfN` it uses something like `PyBytes_FromString()`.

**Comment by YannickJadoul** [comment]
This might be better/easier to continue on [Gitter](https://gitter.im/pybind/Lobby), if this is still an issue.

Or, if it is still an issue, you don't wish to continue on Gitter, and @bstaletic's pointers don't help, do reopen.

**Comment by darkdragon-001** [comment]
@bstaletic Where and how do I perform the steps you are describing?

**Comment by ruiyang00** [comment]
@darkdragon-001 
how do you write the py::class.def("s") if C::s() takes a char* ?
