### ISSUE TITLE
How to overload unary functions

### ISSUE THREAD

**Issue by ianhbell** [pybind/pybind11#1812]
## Issue description

Documentation does not describe how to overload unary operator or pow operator.  

For unary operator, there are no examples in tests/test_operator_overloading.cpp, and for pow overloading, the necessary code seems to be commented out: https://github.com/pybind/pybind11/blob/master/include/pybind11/operators.h#L137 .  Is there a reason for that?  I did a clunky workaround below....

## Reproducible example code

I did this in my code:

``` python

#include "MultiComplex/MultiComplex.hpp"

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/complex.h>
#include <pybind11/operators.h>
#include <pybind11/functional.h>

namespace py = pybind11;

void init_MultiComplex(py::module &m){
    typedef MultiComplex<double> MCD;

    py::class_<MCD>(m, "MultiComplex")
        .def(py::init<const std::complex<double> &>())
        .def(py::init<const std::valarray<double>&>())
        ...
        .def("__pow__", [](MCD& mc, int exponent) { return mc.pow(exponent); })
        .def("__neg__", [](MCD& mc) { return -mc; })
        ...
        ;
}

PYBIND11_MODULE(pymcx, m) {
    m.doc() = " A Python wrapper of C++ library for working with multicomplex mathematics";
    init_MultiComplex(m);
}
```

**Comment by sizmailov** [comment]
Overloading of an operator is not different from defining a regular function. Your implementation is fine. 
The purpose of `operators.h` header is to make the binding of overloaded operators convenient. So instead of 
```C++
        ... 
        .def("__neg__", [](MCD& mc) { return -mc; })
        ... 
```
you can write
```
        ... 
        .def(-py::self)
        ... 
```

which is short and clear.

**Comment by ianhbell** [comment]
... but also not documented or tested :)

**Comment by sizmailov** [comment]
@ianhbell not true

1) https://pybind11.readthedocs.io/en/stable/advanced/classes.html?highlight=conveniently%20exposed#operator-overloading

2) https://github.com/pybind/pybind11/blob/master/tests/test_operator_overloading.cpp#L88-L107

**Comment by ianhbell** [comment]
None of the *unary* operators are tested or documented

**Comment by amrit-poudel** [comment]
How do I overload operator()? I can't seem to find any documentation on this.
I have a C++ class with operator() defined. I simply want to expose it to Python.
 Any help would be appreciated. Thanks.

**Comment by carlsonmark** [comment]
What is the signature of your `SomeClass::operator()`?

**Comment by amrit-poudel** [comment]
double SomeClass::operator(double e){
return e*3 +4/5; // I have Eigen matrices as output in my actual  code, but that should not matter.
}

**Comment by carlsonmark** [comment]
This works for me:
```
class MyClass {
...
   double operator()(double arg){return arg*2.0;}
...
};

...
     .def("__call__", &MyClass::operator())
```

In Python, `myClass(1)` returns `2`

**Comment by amrit-poudel** [comment]
How about for this:

const double& operator()(double arg=nullptr){
}

**Comment by carlsonmark** [comment]
I can't compile a funciton with that signature, even without using pybind11 (using g++9.) I don't think you can assign nullptr as a default value for an argument of type double. I can't even compile `double x=nullptr;` nullptr is not the same as the old NULL macro, and is more type safe.

Funny enough, if you do this, it will still compile, but will give an "incompatible function arguments" error when the operator is called without an argument:
```
class MyClass {
...
   double operator()(double arg){return arg*2.0;}
...
};

...
     .def("__call__", &MyClass::operator(), py::arg("arg")=nullptr)
```

I believe it ends up creating a signature that assigns `None` to the default value of the argument, and None can not be converted to a double the same way that `nullptr` can't really be converted to a double.

**Comment by amrit-poudel** [comment]
I understand that I cannot assign nullptr to double. My point was to show that the above code does compile/run and returns error message as you pointed out, which was a bit surprising. 
One solution is to overload () with and without input and expose them to Python, but I was hoping for a better/shorter  solution.

Thanks for your time.
