### ISSUE TITLE
scoped_interpreter blocks ctrl+c

### ISSUE THREAD

**Issue by luxe** [pybind/pybind11#1813]
When I create a `scoped_interpreter` in my program, like so: 
```
#include <pybind11/embed.h>
int main() {
    pybind11::scoped_interpreter guard{};
    while (true){
        //can't ctrl+C
    }
}
```

I can't ctrl-C out of the program.  Is this expected?  Is there a way to get this functionality back?  Not sure if I should try to write a signal handler or something.  `while(true)` is UB, but this is just an example-- you know what I mean.  

To clarify, I regain the ability to ctrl+c if it goes out of scope.  Example:  
```
#include <pybind11/embed.h>
int main() {
    {
        pybind11::scoped_interpreter guard{};
    }
    while (true){
        //CAN ctrl+C
    }
}
```

**Comment by bjodah** [comment]
Not really addressing your question: but if it's just that you want to stop the program (and not doing anything in particular with SIGINT), you should be able to send a SIGQUIT using `C-\`?

**Comment by luxe** [comment]
> Not really addressing your question: but if it's just that you want to stop the program (and not doing anything in particular with SIGINT), you should be able to send a SIGQUIT using `C-\`?

good tip, that works. I'm still hoping to learn more about why SIGINT doesn't exit as normal with the interpreter in scope.  My solution for the time being is:  

```
#include <pybind11/embed.h>
void signalHandler( int signum ) {
    exit(signum);
}
int main() {
    signal(SIGINT, signalHandler);
    pybind11::scoped_interpreter guard{};
    while (true){
        //can ctrl+c now
    }
}
```

**Comment by YannickJadoul** [comment]
As far as I know, the Python interpreter has a custom signal handler for SIGINT. You can use `PyErr_CheckSignals` duing a long-running piece of C code to check for intercepts: https://docs.python.org/3/c-api/exceptions.html#c.PyErr_CheckSignals. There are a few answers on SO on this: e.g., https://stackoverflow.com/questions/14707049/allowing-ctrl-c-to-interrupt-a-python-c-extension

This is not specific to pybind11, so there's not a lot pybind11 can do about this.
