### ISSUE TITLE
namespace causes segfault

### ISSUE THREAD

**Issue by juliangaal** [pybind/pybind11#1815]
## Issue description
Wrapping my code in a namespace and declaring the function `&namspace::function` in `PYBIND11_MODULE` as mentioned in #968 causes a segmentation fault.

## Reproducible example code
`pybind_demo.hpp`
```cpp

#ifndef PYBIND_DEMO_HPP
#define PYBIND_DEMO_HPP

namespace pybind_demo {

unsigned int ackermann(unsigned int m, unsigned int n);

} // namespace pybind_demo

#endif // PYBIND_DEMO_HPP
```
`bindings.cpp`
```cpp
#include <pybind11/pybind11.h>
#include <pybind_demo/pybind_demo.hpp>

PYBIND11_MODULE(pybind_demo, m) {
    m.doc() = "pybind11 demo";
    m.def("ackermann", &pybind_demo::ackermann, "A function which calculates ackermann number");
}
```
`CMakeLists.txt`
```cmake
...
find_package(PythonLibs 3 REQUIRED)

add_subdirectory(pybind11)
pybind11_add_module(${PROJECT_NAME} src/${PROJECT_NAME}.cpp src/bindings.cpp)
target_include_directories(${PROJECT_NAME} PRIVATE ${PYTHON_INCLUDE_DIRS} include)
...
```
The whole thing without the namespace `pybind_demo` works with no issues. Am I missing something? Is this a bug? Thanks for your help

My setup:
* ubuntu 18.04
* gcc 8.0
* python3.6

**Comment by ShuminKong** [comment]
Same here

**Comment by lvxejay** [comment]
@juliangaal @ShuminKong I'm curious, does GCC 7 work instead? I think I may have run into this with GCC 8 but didn't know what was causing the undefined behavior at the time.

**Comment by ShuminKong** [comment]
Sorry, my GCC is 7.4 instead of 8

**Comment by ShuminKong** [comment]
Nevermind, it turns out that it's because i didn't configure cmake properly and forgor to link a dependency. Thanks.

**Comment by bstaletic** [comment]
This does look like a case of a file not being compiled with the rest of the project, or linking not being set correctly, like @shumink said. I'll close it and if someone still has a problem, come to gitter instead. https://gitter.im/pybind/Lobby
