### ISSUE TITLE
how write class-reference  parameter callback

### ISSUE THREAD

**Issue by fdfhj** [pybind/pybind11#1816]
C++:
class A;
typedef void  Fun(A &a);
class B
{
  B(Fun f){   fun=f;}
  void gt(){    fun(A()); }
public:
Fun fun;
}

python: 
def fun(a):
   ..........

I want to create B object in python  with fun parameter ;

**Comment by bstaletic** [comment]
First of all, that isn't even valid C++. Second, it's not really possible to take `PyObject*` from python and extract a C style function pointer. It's just not how things work. Instead, make an overload with `std::function<void(A&)>`.
