### ISSUE TITLE
CLion: fatal error: pybind11/pybind11.h: No such file or directory #include <pybind11/pybind11.h>

### ISSUE THREAD

**Issue by chakpongchung** [pybind/pybind11#1819]
Issue similar to previous one here: https://github.com/pybind/pybind11/issues/1379

```
Now the cmake project loads correctly (in my CLion IDE), no longer giving the error ...Could not find a package configuration file provided by "pybind11"..., but the line

#include <pybind11/pybind11.h> in my .cpp file now fails to compile with

fatal error: pybind11/pybind11.h: No such file or directory #include <pybind11/pybind11.h>

I can still compile correctly in the command line in my virtual environment with

c++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` Vehicle_pb.cpp util.cpp -o Vehicle`python3-config --extension-suffix`
```

Same issue here, I still cannot resolve the header `pybind11.h` in Clion. Your fix can solve the CMake problem, but not Clion resolving the header.

**Comment by YannickJadoul** [comment]
I'm assuming the the `pybind11` include folder is not in the include path of CLion?

If this is still an issue, please reopen and show us CMake file you're using in CLion or the project setup/layout.
