### ISSUE TITLE
Wrong exception handling

### ISSUE THREAD

**Issue by fteicht** [pybind/pybind11#1829]
Hi,

On C++ side I export to Python a simple class with a function that just throws an exception:

```
struct Foo {
    void bar() {
        // any code here (you can leave it empty for testing purposes)
        throw std::runtime_error("crash");
    }
};

PYBIND11_MODULE(example, m) {
    py::class_<Foo> py_foo(m, "Foo");
         py_foo
             .def(py::init<>())
             .def("bar", &Foo::bar)
          ;
}
```

Then in python I try to catch the exception:

```
try:
    myfoo = Foo()
    myfoo.bar()
except RuntimeError as err:
    print(err)
```

I would expect the program to write "crash" on the terminal but rather I get the following message:
```
TypeError: bar(): incompatible function arguments. The following argument types are supported:
    1. (self: example.Foo) -> None
```

If I don't throw an exception in Foo::bar() then the code runs fine. On a more complex example with many nested exported types (too long to reproduce it) I even get a segmentation fault because of some python object not being correctly freed - I guess because the correct exception is not properly caught by Python. So my question is: *how can I make Python catch the correct RuntimeError exception thrown from C++*?

I tested this example on MacOS with g++-9 installed from brew.

Thanks in advance for your help!
Florent

**Comment by wjakob** [comment]
Works fine here and prints a single line `crash` on my machine (on MacOS, with Python 3.7/Anaconda).

I suspect something fishy is happening on your end—perhaps you linked the extension module to the python library, and you end up having 2 python interpreters in the same process (which tends to produce undefined behavior). As a rule, on MacOS you'll want to link with `-undefined dynamic_lookup` instead of `-lpython3.7m` or something like that.

**Comment by Takishima** [comment]
I have a similar issue on Mac OS 10.15.

Content of `test.cpp`:
```cxx
#include <stdexcept>
#include <pybind11/pybind11.h>

namespace py = pybind11;

struct Foo {
     void bar() {
	  // any code here (you can leave it empty for testing purposes)
	  throw std::runtime_error("crash");
     }
};

PYBIND11_MODULE(test, m) {
     py::class_<Foo> py_foo(m, "Foo");
     py_foo
	  .def(py::init<>())
	  .def("bar", &Foo::bar)
          ;
}
```

Content of `test.py`
```python
from test import Foo

try:
    myfoo = Foo()
    myfoo.bar()
except RuntimeError as err:
    print(err)
```

Compiled using:
```bash
/usr/bin/clang++ \
 -std=c++17 -undefined dynamic_lookup \
`/usr/local/anaconda3/bin/python3 -m pybind11 --includes` \
test.cpp \
-o test`/usr/local/anaconda3/bin/python3-config --extension-suffix`
```

Executed using:
```bash
$ /usr/local/anaconda3/bin/python3 test.py
Segmentation fault: 11
```

The result is the same if I use the Python version I have installed through Homebrew:
```bash
/usr/bin/clang++ \
 -std=c++17 -undefined dynamic_lookup \
`python3 -m pybind11 --includes` \
test.cpp \
-o test`python3-config --extension-suffix`
```

**Comment by Takishima** [comment]
Compiling using GCC-9.2.0 from homebrew gets rid of the segmentation fault and produces code with the expected result.

**Comment by bstaletic** [comment]
No answer after @wjakob's reply. Closing.
