### ISSUE TITLE
tools/clang using relative submodule breaks non-github superprojects

### ISSUE THREAD

**Issue by ransico** [pybind/pybind11#1831]
https://github.com/pybind/pybind11/blob/502ffe50a9f22c04637bbc8ec0019488458ba948/.gitmodules#L3

Using a relative path here breaks cases where pybind11 is itself used as a submodule in another repo _that is not hosted on github_.

The issue is raised when doing a recursive submodule update on the super project, as relative paths are resolved based on the superprojects URL (and there is no way that I know of to exclude a single submodule from the recursive update, since command line options override settings from .gitmodules).

Since you use this as an internal tool (#807), would you consider changing back to an absolute url, such as `git@github.com:wjakob/clang-cindex-python3.git`, or perhaps removing the submodule?

**Comment by wjakob** [comment]
cc @henryiii

**Comment by varunagrawal** [comment]
@ransico @wjakob @henryiii I can submit a PR for this to ease the transition. We are also facing this issue, particularly during Actions post cleanup.
