### ISSUE TITLE
Use C++ object in python with pybind11

### ISSUE THREAD

**Issue by vkresch** [pybind/pybind11#1834]
Hey I would like to use C++ objects in Python. Is it possible? See my question on [stackoverflow](https://stackoverflow.com/questions/56953822/use-c-object-in-python-with-pybind11) thank you. I'm not quite sure how to do it with the embedded module. If someone can provide some minimal code it would be great. 

Is it also possible to pass dynamically changing C++ object on runtime to python?

**Comment by dlong11** [comment]
I would take a look at the the [docs](https://pybind11.readthedocs.io/en/stable/advanced/embedding.html).  It has lots of examples.   Also the the [tests](https://github.com/pybind/pybind11/tree/master/tests/test_embed) can be useful.

**Comment by bstaletic** [comment]
The question has been answered, both, here and on SO.
