### ISSUE TITLE
provide pybind11 function for multiple input type combinations

### ISSUE THREAD

**Issue by nschloe** [pybind/pybind11#1838]
I would like to write a pybind11 interface to a simple adding function that, given a target array `array`, an index array `idx`, and a source array `vals` sums all `vals` at `idx` into `array` (just like `numpy.add.at`). I would also like to support all combinations of reasonable `idx` and `vals` types. The following does the trick, but is _very_ verbose for what I want to achieve
```c++
template <typename I, typename T>
void
add(
    py::array_t<T> array,
    py::array_t<I> idx,
    py::array_t<T> vals
    )
{
   // ... do something smart ...
}

PYBIND11_MODULE(_foobar, m) {
  // int8 idx type
  m.def("_add_at", &add<int8_t, int8_t>);
  m.def("_add_at", &add<int8_t, int16_t>);
  m.def("_add_at", &add<int8_t, int32_t>);
  m.def("_add_at", &add<int8_t, int64_t>);
  m.def("_add_at", &add<int8_t, uint8_t>);
  m.def("_add_at", &add<int8_t, uint16_t>);
  m.def("_add_at", &add<int8_t, uint32_t>);
  m.def("_add_at", &add<int8_t, uint64_t>);
  m.def("_add_at", &add<int8_t, float>);
  m.def("_add_at", &add<int8_t, double>);
  // int16
  // ... same with int16_t
  // int32
  // ...
  // int64
  // ...
  // uint8
  // ...
  // uint16
  // ...
  // uint32
  // ...
  // uint64
  // ...
}
```
How can I avoid listing all those functions individually?

**Comment by wjakob** [comment]
The alternative is to take a `py::array` (without templated type) and do the necessary `dtype()` checking and call logic yourself.

**Comment by nschloe** [comment]
Are there any examples on how to work with `py:array`s? I only ever find `py:array_t`, e.g., [here](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html), where `double` is assumed in
```c++
    double *ptr1 = (double *) buf1.ptr,
           *ptr2 = (double *) buf2.ptr,
           *ptr3 = (double *) buf3.ptr;
```

**Comment by wjakob** [comment]
There should be plenty of examples in the test suite, I would just look at that.

**Comment by nschloe** [comment]
Yup, thank you!
