### ISSUE TITLE
if a class in another class, how can I bind it? (SEAL)

### ISSUE THREAD

**Issue by Huelse** [pybind/pybind11#1839]
This days, I try to use the pybind11 to make the SEAL run on the Python, Like PySEAL.
Differently I want built it on SEAL3.3.
Now, I missed some Problems, I not familiar with C++17.
in context.h there is a important class ContextData whitch is in another class SEALContext.

```
class SEALContext
{
public:
    class ContextData
    {
        friend class SEALContext;
        public:
        ...
    }
....
}
```
from https://github.com/microsoft/SEAL/blob/master/native/src/seal/context.h
I dont't know how to deal with it, and haven't find any similar examples in the doc(maybe I am bind), so I did like this:
```
PYBIND11_MODULE(seal, m) {
    // SEALContext
	py::class_<SEALContext, std::shared_ptr<SEALContext>>(m, "SEALContext")
		.def("Create",
		[](const EncryptionParameters &parms) { return SEALContext::Create(parms); })
		
		.def("key_parms_id", &SEALContext::key_parms_id)
		
		.def("key_context_data", &SEALContext::key_context_data)

		.def("get_context_data",
		(void (SEALContext::*)(parms_id_type)) &SEALContext::get_context_data);

// SEALContext::ContextData
	py::class_<SEALContext::ContextData>(m, "SEALContext::ContextData")
		.def("parms", &SEALContext::ContextData::parms)
		.def("parms_id", &SEALContext::ContextData::parms_id)
		.def("total_coeff_modulus",
		(std::uint64_t (SEALContext::ContextData::*)()) &SEALContext::ContextData::total_coeff_modulus);
}
```
My project: https://github.com/Huelse/pySEAL
in Ununtu18.04, when I run the test.py 
`context.key_context_data()`
`context.key_context_data().parms()`
I got
```
double free or corruption (out)
Aborted (core dumped)
```
I hope someone can help me solve this problem or join my project.
Thanks a million!

**Comment by wjakob** [comment]
The specification looks reasonable. But you should have a good look at the documentation, specifically the portion on return value policies.

**Comment by Huelse** [comment]
> 规范看起来合理。但是你应该好好看看文档，特别是关于返回值政策的部分。

You mean this page?
https://pybind11.readthedocs.io/en/master/advanced/functions.html#return-value-policies
ok, I am trying.

**Comment by Huelse** [comment]
@wjakob 
https://pybind11.readthedocs.io/en/master/advanced/smart_ptrs.html#std-shared-ptr
https://github.com/pybind/pybind11/blob/master/tests/test_smart_ptr.cpp
How can I bind this kind of function?
```
inline auto key_context_data() const
{
    auto data = context_data_map_.find(key_parms_id_);
    return (data != context_data_map_.end()) ?
        data->second : std::shared_ptr<ContextData>{ nullptr };
}
```
I don't want to alter the cpp code

**Comment by Huelse** [comment]
ok, someone helped me, thanks a lot.
