### ISSUE TITLE
Support for similar to boost::python::indexing _suite functionality

### ISSUE THREAD

**Issue by foxtog** [pybind/pybind11#184]
Hello, Wenzel!
Currently, I'm using boost::python to export C++ types to Python. However, I'm planning to move to pybind11 as it seems to be 'lighter' than boost::python, looks elegant and has support for numpy.
However, I have quite a lot of STL(`std::vector, std::map, std::unordered_map`) types exported; and I'm using indexing_suite utilities for doing that. Its major advantage is that it reduces the burden of explicitly defining general container methods such as e.g. `append` (for `std::vector`), etc. The range of such methods is the same for each and every container object of specific type and, in most cases, referring to such objects from python should be analogous to using python dicts and lists. 

Are there any plans to add such functionality?
Would be a PR valuable?

**Comment by wjakob** [comment]
Hi Alexandra,

as it happens, I just committed a fairly big redesign of the way in which *opaque* objects are handled in pybind11. See here for details:  http://pybind11.readthedocs.io/en/latest/advanced.html#treating-stl-data-structures-as-opaque-objects

This change makes it considerably easier to add the ``indexing_suite`` type of utilities to pybind11, and I definitely welcome a PR in this regard. I imagine the resulting code might look something like the following (though you might call the methods differently to make this more pythonic, I guess)

```
template <typename T> void bind_vector_type(const char *name) {
    py::class_<T>(m, name)
        .def(py::init<>())
        .def("pop_back", &T::pop_back)
        .def("__len__", [](const T &v) { return v.size(); })
        .def("__iter__", [](T &v) {
           return py::make_iterator(v.begin(), v.end());
        }, py::keep_alive<0, 1>());        
        /* There are multiple versions of push_back(), etc. Select the right ones. */
        .def("push_back", (void (T::*)(const typename T::value_type &)) &T::push_back)
        .def("back", (typename T::value_type &(T::*)()) &T::back);
       /* To be continued :) */
}
```

Thanks,
Wenzel

**Comment by lyskov** [comment]
Hi Alexandra, 

Great! I was also thinking about suggesting something along these lines and have outline for vector binders implementation. Would be great if we can avoid duplication of effort though..., - have you already started working on this? If not, i would be happy to put PR with what i have so far.

Best,
Sergey.

**Comment by wjakob** [comment]
FYI: this is a link to how boost python implements this feature: http://www.boost.org/doc/libs/1_51_0/libs/python/doc/v2/indexing.html

And here is a basic example from pybind that shows how to provide slicing operations, etc.
https://github.com/pybind/pybind11/blob/master/example/example6.cpp

**Comment by foxtog** [comment]
Hi, Sergey! 
No, I don't yet have a full solution to be proposed as a PR so go ahead and put yours.

Regards, 
Alexandra

**Comment by wjakob** [comment]
Closing this, as the associated PR was merged.
