### ISSUE TITLE
Overriding module name

### ISSUE THREAD

**Issue by jbms** [pybind/pybind11#1843]
I'm creating a Python extension module named `_mypackage` within some python package directory `mypackage`, and then the `mypackage/__init__.py` file imports all of the names from `mypackage._mypackage` into `mypackage`.  I'd like all of the types defined in `mypackage._mypackage` to display with fully-qualified names like `mypackage.MyClass` rather than `mypackage._mypackage.MyClass`.  Is there any way to do that?

**Comment by YannickJadoul** [comment]
You can reassign the `__module__` attribute of a class, just like you would do in Python.

**Comment by wojdyr** [comment]
I asked the same question in https://github.com/wjakob/nanobind/discussions/730 – see Wenzel's answer, it probably can be applied also to pybind11.
