### ISSUE TITLE
Time Conversions - Python datetime.date to C++ system_clock::time_point

### ISSUE THREAD

**Issue by phil-zxx** [pybind/pybind11#1844]
As explained here https://github.com/pybind/pybind11/blob/master/docs/advanced/cast/chrono.rst, there is a conversion option of `datetime.datetime → std::chrono::system_clock::time_point` from `Python` to `C++`.

However, I am wondering whether it is possible to also do the conversion for the simple `date` object, i.e. convert `datetime.date → std::chrono::system_clock::time_point` from `Python` to `C++`?

**Comment by phil-zxx** [comment]
Seems like we just have to add an exra `else if` block in `include\pybind11\chrono.h` as follows (since `PyDate_Check` conveniently exists already):

```cpp
if (PyDateTime_Check(src.ptr())) {
    /* ... */
}
else if (PyDate_Check(src.ptr())) {
    std::tm cal;
    cal.tm_sec   = 0;
    cal.tm_min   = 0;
    cal.tm_hour  = 0;
    cal.tm_mday  = PyDateTime_GET_DAY(src.ptr());
    cal.tm_mon   = PyDateTime_GET_MONTH(src.ptr()) - 1;
    cal.tm_year  = PyDateTime_GET_YEAR(src.ptr()) - 1900;
    cal.tm_isdst = -1;

    value = system_clock::from_time_t(std::mktime(&cal)) + microseconds(PyDateTime_DATE_GET_MICROSECOND(src.ptr()));
    return true;
}
```

**Comment by wjakob** [comment]
feel free to create a PR for this (along with test cases, please.).

**Comment by phil-zxx** [comment]
Where are test cases located? That is, where would I need to add them?

**Comment by phil-zxx** [comment]
Submitted

**Comment by YannickJadoul** [comment]
#1848 was merged
