### ISSUE TITLE
Cannot use Windows.h min/max in same project as pybind11

### ISSUE THREAD

**Issue by n8many** [pybind/pybind11#1846]
# Issue description

When including Windows.h prior to including pybind11, you must define NOMINMAX in order to prevent the min and max macros it creates from interfering with std::min/max and std::numeric_limits::min/max. This issue was presented in issue #291 and a check/error message was put in place.

That solution to the issue prevents you from creating a program that is able to use both std::min/max and the Windows.h macros for min/max. This sometimes is necessary when working on a larger project that requires these macros but also needs to use pybind11. 

An alternate solution to this issue is enclosing the affected functions in parentheses, as noted here: https://github.com/boostorg/stacktrace/issues/37#issuecomment-347997174. This solution protects these functions from being overwritten by the macro while still allowing other parts of the project to use the Windows.h min/max macros.

**Comment by wjakob** [comment]
Closing via #1847.

**Comment by SylvainCorlay** [comment]
Now that all calls to `std::min` are wrapped with parentheses, it could make sense to remove the test that `min` and `max` macros are not defined?

**Comment by n8many** [comment]
@SylvainCorlay I believe that was already done (see https://github.com/pybind/pybind11/commit/9b3fb05326d49bbe2849744d8375dfb2406e8865). 

Is there another instance of this that was missed?

**Comment by SylvainCorlay** [comment]
Indeed, there was a compilation error explicitely triggered, 
```
#if defined(_WIN32) && (defined(min) || defined(max))
#  error Macro clash with min and max -- define NOMINMAX when compiling your program on Windows
#endif
```

but it appears to not be there anymore on the master branch.
