### ISSUE TITLE
doc: Rename example files

### ISSUE THREAD

**Issue by cmpute** [pybind/pybind11#1849]
## Issue description

Some examples are given by example files in current documentation. However, they're now actually test files. Please update those names as mentioned by #577. 

## Reproducible example code

Example: https://pybind11-rtdtest.readthedocs.io/en/stable/advanced.html#binding-sequence-data-types-iterators-the-slicing-protocol-etc

**Comment by bstaletic** [comment]
Wrong link. `pybind11-rtdtest.readthedocs.io` is old and hosted who knows where. Use https://pybind11.readthedocs.io/en/stable/
