### ISSUE TITLE
return custom type from c++ to python

### ISSUE THREAD

**Issue by zhengcharlie8** [pybind/pybind11#1862]
Hi All, I have a question about type conversion. I read about the FAQ it seems like the easiest way is to use primitive type.
```
 class Observation {

 public:
  Weather currWeather;
  vector<vector<Pokemon>> teams;
  vector<vector<Pokemon *>> inBattle;
  vector<Move> chosenMoves;

};
```
Here `Pokemon`, it is another custom class:

```
class Pokemon {
 public:
  std::string species;
  BaseStats baseStats;
}
```

where BaseStats is : 
```
class BaseStats {
 public:
  int hp;
  int atk;
  int def;
  int spa;
  int spd;
  int spe;

}

```
For this kind of nested custom class, what is the best way to return its object to python? I dont find convenient toString() method or json library to return a stringified json that can be read from python.   

Do I have to construct a toString() method such that it will call the nested custom class's toString() method ?

**Comment by bstaletic** [comment]
There's no need to serialize an object. Write bindings for both classes and then just return the instance you want.

```c++
PYBIND11_MODULE(example, m) {
    py::class_<BaseStats>(m, "BaseStats").def_readwrite("hp", &BaseStats::hp); // chain other "stats"
    py::class_<Pokemon>(m, "Pokemon").def_readwrite("species", &Pokemon::species).def_readwrite("BaseStats", &Pokemon::baseStats);
}
```

For questions like these, it's easier to ask in gitter.
