### ISSUE TITLE
Unable to pass Python None to C++ function expecting pointer to basic type

### ISSUE THREAD

**Issue by Nishi311** [pybind/pybind11#1865]
## Issue description

Not entirely sure if this is a bug or if I'm simply being foolish but I'm unable to pass a None type from python to a c++ function expecting a pointer argument. From what I understand, the None type should be automatically converted into a nullptr for use in the c++ function. Instead I encounter an error in the format :
```
pybind_error_test_bindings.test_int_pointer_true(None)
TypeError: test_int_pointer_true(): incompatible function arguments. The following argument types are supported:
1. (test_int_ptr: int) -> None

Invoked with: None
```

I should note that I CAN successfully achieve the desired behavior if passing None to a function expecting a char* but CANNOT achieve this with an int* or double*. 

I'm aware of the documentation ([see section](https://pybind11.readthedocs.io/en/stable/advanced/functions.html#allow-prohibiting-none-arguments)) outlining how this behavior is supposed to be explicitly stated and tried to follow it as best I could, but to no avail. I'm also wondering if this has something to do with the fact that I'm attempting to directly use an immutable object ([see faq](https://pybind11.readthedocs.io/en/stable/faq.html#limitations-involving-reference-arguments)) rather than a c++ type registered with py::class.

Any help would be greatly appreciated! I'm really not sure if I'm simply doing things wrong (VERY possible) or if this is a genuine bug because I can't find much info about this.

Below is my reproducible example, pytest file to test it, and the cmake file I used to build it.

## Reproducible example code

C++ module definition (pybind_error_test_bindings.cpp)
```
#include <pybind11/pybind11.h>
#include <stdio.h>
namespace py = pybind11;

PYBIND11_MODULE(pybind_error_test_bindings, module) {
  //Test for char*. SHOULD allow Python None to be passed and converted to nullptr
  module.def("test_char_pointer_true", [](char *test_char_ptr) -> void {
    if (test_char_ptr){
      printf("%p", test_char_ptr);
    } else {
      printf("test_char_ptr is false");
    }
  }, py::arg("test_char_pointer").none(true));

  //Test for char*. Should NOT allow Python None to be passed and converted to nullptr
  module.def("test_char_pointer_true", [](char *test_char_ptr) -> void {
    if (test_char_ptr){
      printf("%p", test_char_ptr);
    } else {
      printf("test_char_ptr is false");
    }
  }, py::arg("test_char_pointer").none(false));
  
  //Test for int*. SHOULD allow Python None to be passed and converted to nullptr
  module.def("test_int_pointer_true", [](int *test_int_ptr) -> void {
  if (test_int_ptr){
    printf("%p", test_int_ptr);
  } else {
    printf("test_int_ptr is false");
  }
  }, py::arg("test_int_ptr").none(true));
  
  //Test for int*. Should NOT allow Python None to be passed and converted to nullptr
  module.def("test_int_pointer_false", [](int *test_int_ptr) -> void {
  if (test_int_ptr){
    printf("%p", test_int_ptr);
  } else {
    printf("test_int_ptr is false");
  }
  }, py::arg("test_int_ptr").none(false));
}

```

python pytest code (pybind_testing.py)

```
from lib import pybind_error_test_bindings

# Expected to succeed and does succeed
def test_char_ptr_none_true():
    pybind_error_test_bindings.test_char_pointer_true(None)

# Expected to fail and does fail.
def test_char_ptr_none_false():
    pybind_error_test_bindings.test_char_pointer_false(None)

# Expected to succeed but fails.
def test_int_ptr_none_true():
    pybind_error_test_bindings.test_int_pointer_true(None)

# Expected to fail and does fail.
def test_int_ptr_none_false():
    pybind_error_test_bindings.test_int_pointer_false(None)
```

CMake used to build 

```
cmake_minimum_required(VERSION 3.7.2)
project (pybind_error_test)

find_package(pybind11 REQUIRED)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/lib)

# Python bindings for basic_io
pybind11_add_module(pybind_error_test_bindings
    ${CMAKE_CURRENT_LIST_DIR}/pybind_error_test_bindings.cpp
    )

set_target_properties(pybind_error_test_bindings PROPERTIES
    CXX_STANDARD 11
    CXX_STANDARD_REQUIRED YES
    CMAKE_CXX_EXTENSIONS OFF
    )
```

**Comment by chohner** [comment]
I think the issue here is exactly the first paragraph of https://pybind11.readthedocs.io/en/stable/advanced/functions.html#allow-prohibiting-none-arguments

> When a C++ type registered with py::class_ is passed as an argument to a function taking the instance as pointer or shared holder (e.g. shared_ptr or a custom, copyable holder as described in Custom smart pointers), pybind allows None to be passed from Python which results in calling the C++ function with nullptr (or an empty holder) for the argument.

`int *` is neither of those

**Comment by sizmailov** [comment]
I think the same issue described here:

https://github.com/pybind/pybind11/pull/1760

Seems like the note from referred PR is not yet deployed to readthedocs

пн, 19 авг. 2019 г., 16:37 chris <notifications@github.com>:

**Comment by Nishi311** [comment]
Ah, I see, sorry for the double post then, must have missed that one. Appreciate the help!
