### ISSUE TITLE
Singleton and functional: process gets stuck when keeping reference to function

### ISSUE THREAD

**Issue by bdelhaisse** [pybind/pybind11#1866]
Hi, 

I am wrapping a class from a library that uses a singleton (using `static`) and `std::function`s together, and after playing a bit with the code, I understood that I have to set the reference to the given input function to `nullptr` otherwise the process will get stuck on the Python side. My question is mostly why? If I don't use a singleton but a simple constructor, I don't have that problem, I assume it has to do with the `static` keyword, but I would like to understand better. In order to illustrate my point, here is an example that shows the problem. Note that I simplified the code to make it easier to read.

- the minimal class `A.hpp` (which is in the `include` folder) that I would like to wrap:
```
#ifndef MYCLASS_HPP
#define MYCLASS_HPP

class A {
  public:
   static A *get() {
       static A singleton;
       return &singleton;
   }
   using callback_fct = std::function<void()>;
   void set_function(callback_fct callback) { callback_ = callback; }
   void call() { callback_(); }
   void close() { callback_ = nullptr; }  // this needs to be called otherwise the process will get stuck.
  private:
    ~A() { callback_ = nullptr ; }  // setting callback_ to null here doesn't terminate the program.
    callback_fct callback_ = nullptr;
};

#endif
```

- the wrapper `wrap.cpp` using pybind11
```
#include <pybind11/pybind11.h>
#include <pybind11/functional.h> 
#include "A.hpp"

namespace py = pybind11;

PYBIND11_MODULE(lib, m) {
    py::class_<A, std::unique_ptr<A, py::nodelete>>(m, "A")
        .def("get", &A::get)
	.def("set_function", &A::set_function)
	.def("call", &A::call)
        .def("close", &A::close);
}
```

- the `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 2.8.9)
project(test)

find_package(pybind11 REQUIRED)

include_directories(include)
pybind11_add_module(lib wrap.cpp)
```

- the Python test file `test.py`:
```python
import lib

def hello():
    print('hello')

a = lib.A.get()
a.set_function(hello)
a.call()
a.close()      # if you don't set callback_ to nullptr in the C++ code, the following 'end'
print('end')   # will be printed but the process will be stuck afterwards... and it can not be done in the destructor...
```

Note that I had to manually add the `close` function in the `A` class (this is not present in the library that I am wrapping). Is there a better way to do it, without having me to modify the library's code? I also tried to replace the `def` with `def_static` in the `wrap.cpp` but that didn't change anything. And finally, I was also wondering why it doesn't work when setting the `callback_` to `nullptr` in the destructor?

**Comment by sizmailov** [comment]
Related issue: https://github.com/pybind/pybind11/issues/749

Stored python function outlives interpreter and it cannot be properly destroyed, resulting to a deadlock. To avoid this you need to destroy the function before interpreter dies. One option is to limit stored function life to life of module. A cleanup function of `py::capsule` will be called at the module end of life. 

Do you really need a singleton on python side? You can replace it with free functions/static methods of dummy class without exposing underlying singleton object. 

Suggested code change: 

```C++
PYBIND11_MODULE(lib, m) {

    m.def("set_function", [](A::callback_fct& f) { A::get()->set_function(f); });
    m.def("call", []() { A::get()->call(); });

    m.add_object("__cleanup_A", py::capsule([]() { A::get()->set_function(nullptr); }));
}
```

**Comment by YannickJadoul** [comment]
Thanks for answering, @sizmailov!
