### ISSUE TITLE
Enum without identifier

### ISSUE THREAD

**Issue by bdelhaisse** [pybind/pybind11#1868]
Hi,

This might be a dumb question but I would like to know how do you define an `enum` which doesn't have an identifier or variable name? I am wrapping a part of a library that defines such 
enumeration.

Small example:
```cpp
namespace abc {
    enum {  // no identifier / variable name
        a=1,
        b,
    };
}
```

```cpp
py::enum_<abc>(m)  // this doesn't work
   .value("a", abc::a)
   .value("b", abc::b);
```

What should I do?

**Comment by sizmailov** [comment]
Pybind requires enumeration to have name, even if it's C++ counterpart doesn't have one, here is an example: 
https://github.com/pybind/pybind11/blob/5b4751af269afab9a2e40a92b486bd29214f352b/tests/test_enum.cpp#L14-L21

**Comment by bstaletic** [comment]
You can't completely omit the name. C API just doesn't allow that. You can use an empty string if you so desire.
