### ISSUE TITLE
How to define global variables with pybind11

### ISSUE THREAD

**Issue by bdelhaisse** [pybind/pybind11#1869]
Hi,

I am wrapping a part of a library and at one point, they define (static) global variables inside a namespace, like this:
```cpp
namespace library {
    namespace abc {
        static bool a = true;
        static bool b = false;
    }
}
```

How can I define such thing with pybind11? I tried:
```cpp
py::module abc = m.def_submodule("abc");
abc.attr("a") = true;
abc.attr("b") = false;
// abc.def_readwrite("a", &abc::a);  // this doesn't work, it requires a class.
// abc.def_readwrite_static("a", &abc::a);  // this doesn't work, it requires a class.
```

but the problem with the above approach is that it is not linked to the C++ variables, and in Python I can set `a` and `b` to anything, it doesn't have to be a boolean...

I also tried the following:
```cpp
class abc {}; // dummy class

PYBIND11_MODULE(lib, m) {
    py::class_<abc>(m, "abc")
        .def_property("a",
            []() { return library::abc::a; }, 
            [](bool a) { library::abc::a = a; });
}
```
but that doesn't work neither...

**Comment by bdelhaisse** [comment]
Ok, I managed to make it work using `def_property_static`. I tried that one before but I forgot to give it `py::object`. So now, it works with:

```cpp
class abc {};  // dummy class

PYBIND11_MODULE(lib, m) {
    py::class_<abc>(m, "abc")
        .def_property_static("a",
            [](py::object) { return library::abc::a; }, 
            [](py::object, bool a) { library::abc::a = a; });
}
```

However, I think it would make more sense to have something along these lines:
```
py::module abc = m.def_submodule("abc"); // create namespace
abc.def_readwrite_static("a", &abc::a);
```

**Comment by molpopgen** [comment]
Have you tried something like [this](https://github.com/molpopgen/fwdpy11/blob/52e806852a31eb5e02ebfab25be2ccd641e416d4/fwdpy11/src/fwdpp_types/NULL_NODE.cc)

The type being wrapped is `constexpr`, but the overall goal is the same. ([original type](https://github.com/molpopgen/fwdpp/blob/19c5b806d466b1e648aa1f4865bb5d55ab90e912/fwdpp/ts/definitions.hpp))

**Comment by bstaletic** [comment]
The following works:

```c++
namespace library {
	namespace abc {
		static bool a = true;
	} // namespace abc
} // namespace library
PYBIND11_MODULE(xxx, m) {
	py::module abc = m.def_submodule("abc"); // create namespace
	abc.attr("a")= &library::abc::a;

}
```

I believe this is good enough.

**Comment by YannickJadoul** [comment]
Actually, this doesn't work for me. The `&library::abc::a` will be casted away, so changes do not get reflected back into C++.

I might be wrong, but I don't think there's a way to have a "property at module level" this in Python; the closest is perhaps https://www.python.org/dev/peps/pep-0562/, from Python 3.7 onwards, but that still doesn't have a `__setattr__`.

**Comment by YannickJadoul** [comment]
Coming back to this, I don't immediately see a solution, due to the way Python works and doesn't have something like module-properties. There's not a lot we can do, as this seems not fixable with the raw Python C API, either?

All I can suggest is to either implement a getter/setter on the Python side (or some object with a getter and setter), or on the C++ side. Or the hacky solution where the submodule is actually a class.

**Comment by YannickJadoul** [comment]
Oh, another solution: you could probably subclass Python's `module` type and override `__getattribute__` and `__setattribute__`, perhaps?
