### ISSUE TITLE
Binding std::future (for async function call) via Pybind11 - Python application hangs in 'future.get()' on second loop iteration

### ISSUE THREAD

**Issue by hfassold** [pybind/pybind11#1870]
See https://stackoverflow.com/questions/57372902/binding-stdfuture-for-async-function-call-via-pybind11-python-application

**Comment by YannickJadoul** [comment]
Can't reproduce with pybind11 2.5.0 on Linux. Please reopen if this is still an issue.

And please post a fully compiling example (i.e., without typos and with the necessary includes) in the issue next time. Makes it easier to try reproducing.
