### ISSUE TITLE
Throwing a c++ exception in a rvalue causes an abort

### ISSUE THREAD

**Issue by madebr** [pybind/pybind11#1878]
## Issue description

When throwing a c++ exception inside a method of an object that is an rvalue (=has no name associated) AND printing in the destructor, then the program aborts.

## Reproducible example code

pybind11 c++ python module definition:
```
#include <pybind11/pybind11.h>
#include <exception>
#include <iostream>

namespace py = pybind11;

class callback {
public:
    callback() {}
    ~callback() {
        std::cout << "c++: callback::~callback()" << std::endl;
        py::print("Here does the crash happen");
   
    }

    void on_fatal() {
        std::cout << "c++: callback::on_fatal" << std::endl;
        throw std::runtime_error("whatever");
    }
};

PYBIND11_MODULE(pymodule, m) {
    py::class_<callback> class_callback(m, "Callback");
    class_callback
        .def(py::init<>())
        .def("on_fatal", &callback::on_fatal);
}
```

When using the python module as follows, the python interpreter aborts:
```
import pymodule
pymodule.Callback().on_fatal()
```

The output is:
```
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  SystemError: <built-in method join of str object at 0x7fbe724d4bf0> returned a result with an error set
Aborted (core dumped)
```

By assigning the just created object to a variable, the abort disappears:
```
import pymodule
cb = pymodule.Callback()
cb.on_fatal()
```

**Comment by arpit15** [comment]
https://github.com/pybind/pybind11/blob/master/include/pybind11/pybind11.h#L1831 comment might be useful.

**Comment by madebr** [comment]
Thanks for the pointer. The error happens here: https://github.com/pybind/pybind11/blob/c9d32a81f40ad540015814edf13b29980c63e39c/include/pybind11/pybind11.h#L1822

**Comment by YannickJadoul** [comment]
Confirmed to still be an issue in 2.5.0. The issue is that somehow, a Python error is already set, yet the `Callback` object is collected and accesses Python again (without throwing an error, this time), confusing Python/pybind11.
