### ISSUE TITLE
Unwrapping C++ functions

### ISSUE THREAD

**Issue by mrzv** [pybind/pybind11#188]
Suppose I expose a C++ function to Python, either implicitly, by returning it from another function, or just declare it as a module member.

Now suppose I have a function that takes a Python object and calls it to get its return value. Is it possible to recognize when this object is a wrapper of a C++ function, unwrap it, and call it directly, bypassing the Python interpreter?

**Comment by wjakob** [comment]
This is a similar issue as converting ``std::vector<>`` to ``list`` versus treating it as an opaque object that behaves right under duck typing. There is some discussion of a potential solution via "opaque types" in the manual.

**Comment by mrzv** [comment]
I see. So the idea is to make `std::function<...>` opaque, manually expose it to Python, adding `__call__` method that would do the right thing?

**Comment by wjakob** [comment]
Yes, exactly.

**Comment by wjakob** [comment]
You'd of course have to do this for every kind of ``std::function<Return(Args...)>`` signature

**Comment by mrzv** [comment]
Yeah, I think I get how to do it explicitly for any given type. Is there no way to do this generically? To somehow recognize `cpp_function` and cast it to a particular `std::function<...>`?

**Comment by wjakob** [comment]
Oh boy, I suppose that would be possible. It is stored in ``detail::function_record`` in pybind11.h, line 122. To get access to that, you'll have to mess with capsules and Python API.

```
#if PY_MAJOR_VERSION < 3
if (func && PyMethod_Check(func.ptr()))
    func = PyMethod_GET_FUNCTION(func.ptr());
#endif

std::function<Return(Args..)> *myFunc;

if (func && PyCFunction_Check(func.ptr())) {
    py::capsule rec_capsule(PyCFunction_GetSelf(func.ptr()), true);
    auto chain = (py::detail::function_record *) rec_capsule;
    myFunc = chain->data;
}
```

YMMV.

**Comment by wjakob** [comment]
(Obviously, all of this is completely unsupported)

**Comment by mrzv** [comment]
Hm, my mileage does vary, but that's probably because I don't really understand it. Here's what I did:
```
#include <iostream>

#include <pybind11/pybind11.h>
#include <pybind11/functional.h>

namespace py = pybind11;

PYBIND11_PLUGIN(mymod)
{
    py::module m("mymod", "mymod bindings");

    m.def("f", [](int x) { return x + 5; });

    m.def("g", [](py::object func)
               {
                  //std::cout << py::cast<int>(func.call(4)) << std::endl;

                  #if PY_MAJOR_VERSION < 3
                  if (func && PyMethod_Check(func.ptr()))
                      func = py::object(PyMethod_GET_FUNCTION(func.ptr()), true);
                  #endif

                  using Function = std::function<int(int)>;

                  Function* myFunc = nullptr;

                  if (func && PyCFunction_Check(func.ptr())) {
                      py::capsule rec_capsule(PyCFunction_GetSelf(func.ptr()), true);
                      auto chain = (py::detail::function_record *) rec_capsule;
                      myFunc = static_cast<Function*>(chain->data);
                  }

                  if (myFunc)
                      std::cout << (*myFunc)(4) << std::endl;
                  else
                      std::cout << "Conversion failed" << std::endl;
               });

    return m.ptr();
}
```

Then `python -c "import mymod; mymod.g(mymod.f)"` gives me a segfault.

**Comment by wjakob** [comment]
Can you change your 'f' so that it returns a std::function and then call python -c "import mymod; mymod.g(mymod.f**()**)"?

**Comment by wjakob** [comment]
Alternatively, write:
```
std::function<int(int)> f = [](int x) { return x + 5; };
m.def("f", f);
```

Plain function pointers and fancy function containers are handled differently.

**Comment by mrzv** [comment]
Ah, brilliant. That works (the first version, but I'm sure so would the second version). So. When you say that it's unsupported, how likely is it to break in the future?

**Comment by wjakob** [comment]
As long as you get the ``data`` member via ``py::detail::function_record``, I think it's fairly safe to ABI changes. Closing this ticket.

**Comment by mrzv** [comment]
Perfect. Thanks!
