### ISSUE TITLE
Native conversion support of nlohmann::json to py::object

### ISSUE THREAD

**Issue by phil-zxx** [pybind/pybind11#1881]
This is more a question to the `pybind11` maintainers. As discussed here https://github.com/pybind/pybind11/issues/1627, does it make sense to add conversion support from `nlohmann::json` to `py::object` into `pybind11` natively?

This repo https://github.com/martinRenou/pybind_json already contains the code required to make this work.

I realise having an explicit dependency on  `nlohmann::json` might be annoying. But I still think it'd be great if we could combine the efforts of two amazing projects. So maybe one could add a code snippet like this to `pybind11`:

```cpp
#ifdef INCLUDE_NLOHMANN_JSON_HPP_
  /*
  Paste relevant code from 
  https://github.com/martinRenou/pybind_json/blob/master/include/pybind_json/pybind_json.hpp
  here
  */
#endif
```

That way, the code only gets used if `nlohmann::json` has been included prior to including `pybind11`.

Thoughts?

**Comment by wjakob** [comment]
Sorry, that's not going to happen -- STL containers, sure. But this is just way too specific to include in pybind11. What I could offer is to include a note in the documentation somewhere -- please create a PR with a suggested addition in this case.

**Comment by jdumas** [comment]
Pybind does support binding Eigen data structures though, which are not STL.
