### ISSUE TITLE
No debug symbols in RelWithDebInfo mode under Linux

### ISSUE THREAD

**Issue by Nekrolm** [pybind/pybind11#1891]
I try to build module using pybind11 extension for CMake.
And there are no debug symbols in produced binaries in RelWithDebInfo CMake configuration.

I suppose,a problem in this part of the [script](https://github.com/pybind/pybind11/blob/master/tools/pybind11Tools.cmake). `strip` is disabled only in Debug mode.  
 
![image](https://user-images.githubusercontent.com/11522531/63597982-4e0ab880-c5c7-11e9-851a-bbf28f7789c2.png)

**Comment by wjakob** [comment]
What happens if you replace `Debug` by `(Debug|RelWithDebInfo)`? If that fixes it, could you submit a PR?

**Comment by Nekrolm** [comment]
Yes. It solves problem.
https://github.com/pybind/pybind11/pull/1892
