### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by r-barnes** [pybind/pybind11#1898]
## Issue description

Can the license text or repo properties be altered so that Github's License Parser automatically detects it as BSD-3 [directions here](https://help.github.com/en/articles/licensing-a-repository))? 

This would make it easier to immediately recognize the open source nature and legal restrictions on PyBind11.

**Comment by wjakob** [comment]
This topic has been discussed before (you can look back in the issue tracker), and the decision was made to put it down in this form.
