### ISSUE TITLE
Segfault with py::int_()

### ISSUE THREAD

**Issue by kbu9299** [pybind/pybind11#1899]
## Issue description
`py::int_` produces the segfault.

Working Environment:
* Pop OS! 18.04
* gcc 7.4.0
* pybind11: v.2.3.0

## Reproducible example code

```
    {
        py::object py_int = py::int_(3);
        std::cout << "py_int = " << py_int.ref_count() << std::endl;
        std::cout << "py_int = " << py_int.ptr() << std::endl;
    }
```
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

However, it is okay with `py::bool_, py::float_, py::str`.

**Comment by bstaletic** [comment]
In the block above, I don't see the interpreter initialized. Make sure you do that and that you're holding the GIL.

**Comment by kbu9299** [comment]
Sorry, my previous posting is unclear. The code has an interpreter initialization. With the same structure, only `py::int_()` has a problem. For example, the following has no problem as the are supposed to be:
```
    {
        py::object obj = py::float_(3.0); 
        std::cout << "obj = " << obj.ref_count() << std::endl;
        std::cout << "obj = " << obj.ptr() << std::endl;
    }

    {
        py::object obj = py::str("Hello");  // OK
        std::cout << "obj = " << obj.ref_count() << std::endl;
        std::cout << "obj = " << obj.ptr() << std::endl;
    }

    {
        py::object obj = py::bool_(true);  // OK
        std::cout << "obj = " << obj.ref_count() << std::endl;
        std::cout << "obj = " << obj.ptr() << std::endl;
    }
```

**Comment by bstaletic** [comment]
You're still not initializing the interpreter. Read https://pybind11.readthedocs.io/en/stable/advanced/embedding.html

If you have initialized the interpreter, reopen the issue.
