### ISSUE TITLE
How to use CALLBACK?

### ISSUE THREAD

**Issue by Chise1** [pybind/pybind11#1900]
My c++ is bad,and I don't now how to translate this:
`typedef void (CALLBACK *fLoginResultCallBack) (LONG lUserID, DWORD dwResult, LPNET_DVR_DEVICEINFO_V30 lpDeviceInfo , void* pUser);
`
Please...

**Comment by bstaletic** [comment]
That's just a function pointer. I'm guessing that `CALLBACK` is a marcro that expands to nothing, in which case an appropriate binding would be `m.def("fLoginResultCallBack", fLoginResultCallBack);`.

If you still have questions, come to gitter and ask there.
