### ISSUE TITLE
Supporting overload for properties

### ISSUE THREAD

**Issue by sgranjoux** [pybind/pybind11#191]
It seems that it's not possible to associate several set C++ functions to one Python property. By example

```
class COverload
 {
 public:
	void setn(int n) {fprintf(stdout, "set n\n"); value = n;}
	void sets(std::string s) {fprintf(stdout, "set s\n"); value = atoi(s.c_str());}
	int get(void) {return value;}
 private:
	int value;
 };

...

	py::class_<COverload>(m, "Overload")
		.def(py::init<>())
		.def("set", &COverload::setn)
		.def("set", &COverload::sets)
		.def_property("attr", &COverload::get, &COverload::setn)
		.def_property("attr", &COverload::get, &COverload::sets);
```

In this case, the last property definition overwrite the previous one. So in Python, we can assign value using the set function with an integer or a string but only with a string when using the property attr.

I think it would be useful to allow several functions for setting a property because it's possible in Python to assign a property with different type of value. Is it possible to implement that?

**Comment by wjakob** [comment]
You can have a single setter/getter that accepts or returns a ``py::object``. Then, in the body, use the cast function (see the advanced docs on that).

**Comment by franzpoeschel** [comment]
If anyone finds this in 2024: A much more comfortable solution is by using pybind11's support for `std::variant`:
```cpp
        .def_property(
            "my_property",
            [](MyClass &self) -> std::variant<double, std::vector<double>> {
                // ...
            },
            [](MyClass &self, std::variant<double, std::vector<double>> arg) {
                return std::visit(
                    [&](auto &&arg_resolved) {
                        // ...
                    },
                    arg);
            },
```
