### ISSUE TITLE
Map std::nested_exceptions to Python equivalent

### ISSUE THREAD

**Issue by ingomueller-net** [pybind/pybind11#1913]
I want to collect ideas whether and how one could map [`std::nested_exception`s](https://en.cppreference.com/w/cpp/error/nested_exception) to Python's chained exceptions from a [`raise ... from`](https://www.python.org/dev/peps/pep-3134/) clause and vice versa. These seem to be the corresponding language features in the two languages, and hence could be an interesting addition to pybind. My expectation is that this would provide more information in case of exceptions that cross language barriers.

I have done only very initial research, but if there is interest from the side of this project, I might be able to invest some more time, potentially with ideas and help from others.

**Comment by nedrebo** [comment]
This would be really valuable for us as well since our library relies heavily on nested exceptions. An exception hierarchy in C++ typically looks like:
```
Higher-level context-aware message
  + Inner error with root cause details
    + More inner with gorry details
      + Even more inner
        + ...
```

Unfortunately, [our wrapper](https://github.com/zivid/zivid-python) raises a plan exceptions with only `Higher-level context-aware message` message string. This makes it hard for end-user to root cause some types of problems.

**Comment by Skylion007** [comment]
We now support raise_from with PyBind11 so we really should revisit this.

**Comment by Skylion007** [comment]
@nedrebo @ingomueller-net Would either of you be interested in working on this? It should be doable without too much effort with using ```std::rethrow_if_nested``` and https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html#chaining-exceptions-raise-from .

**Comment by Skylion007** [comment]
@ingomueller-net @nedrebo Just opened a PR #3608 to add support for this issue.
