### ISSUE TITLE
What is the best way to compare equality to types

### ISSUE THREAD

**Issue by timkpaine** [pybind/pybind11#1914]
Apologies if this is answered somewhere else in the documentation, I looked around as much as I could but could not find anything.

I'm expecting to receive a dictionary of types as input, e.g. ```{"a": int, "b": float}```, and in C++ need to map the type to something. Right now I convert the type to its string representation and then switch on that:
https://github.com/finos/perspective/blob/python/python/table/perspective/src/python.cpp#L186

This looks like:
```
    auto value = py::str(val.attr("__name__")).cast<std::string>();
    if(value == 'int'){
```

Which is quite ugly. I've tried things like:

```
    if(value == py::int_){
```

```
    if(value == PyLong_Type){
```

```
    if(value.is(py::cast(PyLong_Type))){
```

and several other variants, but can't seem to get it right. What is the best way of doing this? the limitation of my current method is that if something inherits from `datetime.datetime`, but uses a different name, I will have to handle it explicitly rather than allowing subtypes.

Related:
https://github.com/pybind/pybind11/issues/1692

**Comment by sizmailov** [comment]
>     if(value == py::int_){
>     if(value == PyLong_Type){
>     if(value.is(py::cast(PyLong_Type))){

In C++ you need an object to compare. You cannot compare classes. Learn the difference between `int_` class and `int_` class instance. 

Everything _in python_ is an object. Same rule apply to types as well. Get the object which represents the type and compare to it. 

<details>

<summary>Example</summary>

C++:
```C++

PYBIND11_MODULE(dev_pybind, m) {

    py::module builtins = py::module::import("__builtin__");
    py::object py_int = builtins.attr("int");

    py::module datetime = py::module::import("datetime");
    py::object datetime_datetime = datetime.attr("datetime");

    m.def("f", [=](py::object& type) {
          if (type.is(py_int)) {
              std::cout << "int" << std::endl;
          }
          else if (type.is(datetime_datetime)) {
              std::cout << "datetime.datetime" << std::endl;
          }
          else {
              std::cout << "Unknown" << std::endl;
          }
        }
    );
}
```
Python:
```python
import dev_pybind
import datetime

dev_pybind.f(int)
dev_pybind.f(datetime.datetime)
dev_pybind.f(None)
dev_pybind.f(3)
```

Output:
```
int
datetime.datetime
Unknown
Unknown
```

</details>


Please use SO or/and [gitter](https://gitter.im/pybind/Lobby) for "I need help" questions. Well-formulated questions usually gets quick answers there.

**Comment by timkpaine** [comment]
Ah grabbing int out of builtins is the key, thanks!

**Comment by arthurp** [comment]
Just in case someone like me is confused about how to get the type objects for python builtin types. The code has changed a little. On Python 3 and the current Pybind11, the code is:

```python
    py::module_ builtins = py::module_::import("builtins");
    py::object py_int = builtins.attr("int");
```

I was confused because the following does *not* work: `py::type::of<py::int_>()`
