### ISSUE TITLE
Python libraries that use sys.argv give an error "cannot import"  

### ISSUE THREAD

**Issue by rachelglenn** [pybind/pybind11#1918]
Hi. I saw there was an issue with pybind11 using argv. I think that this is a different error. When the python libraries I use try to use argv, such as...

from sys import argv

I get the error:

ImportError: Cannot import name 'argv'

I am able to use sys.argv in python directly with no issue. I used python2 to build pybind11 and I am using python36 in my python libraries. 

Thank you in advance

**Comment by YannickJadoul** [comment]
Though this issue was reported before, it's now been discussed (together with solutions) in #2061.
