### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by jmabille** [pybind/pybind11#192]
Hi Wenzel,

When compiling the examples with VS2015, I have the following error:

pybind11/numpy.h(152): error C2133: ' ?? ?? :: ?? ::values': unknown size

due to the following declaration:

```cpp
    constexpr static const int values[] = {
        array::API::NPY_BYTE_, array::API::NPY_UBYTE_, array::API::NPY_SHORT_,    array::API::NPY_USHORT_,
        array::API::NPY_INT_,  array::API::NPY_UINT_,  array::API::NPY_LONGLONG_, array::API::NPY_ULONGLONG_ };
```

**Comment by wjakob** [comment]
The AppVeyor continuous integration bot (which uses MSVC2015) can compile the examples without problems. Do you know why it might be behaving different on your platform?

**Comment by jmabille** [comment]
Not sure about it, but it seems the /Za option (C ANSI) is set somewhere and that prevents declaration of C array member without a size.

But I don't understand why I have this option set, since I use the vcproj files generated by cmake.
