### ISSUE TITLE
Question/Feature request: Call code when module is unloaded

### ISSUE THREAD

**Issue by gillesdegottex** [pybind/pybind11#1925]
Hi,

First thanks for this great work!

My question/feature request:

The function `PYBIND11_MODULE` also allows, if need be, to initialize external libraries that needs it.
Though, when the module is unloaded, it would be convenient to uninitialize/free those same libraries.

Is there any way to do this?
(really sorry if I overlooked the documentation and missed it)

Cheers,

**Comment by wjakob** [comment]
pybind11 modules can never be unloaded, it's not supported for native libraries in python.
