### ISSUE TITLE
Read the docs not updating

### ISSUE THREAD

**Issue by henryiii** [pybind/pybind11#1926]
Version 2.4.0 came out, but master on read the docs still shows an old version of the changelog (not even including 2.3.0), and stable on read the docs is even older. Seems like it is no longer updating.

**Comment by henryiii** [comment]
FYI, `overload_cast_impl` in C++11 is great, but it is listed twice in the release notes for 2.4.0.

**Comment by wjakob** [comment]
Both fixed now, the webhook seems to have broken.
