### ISSUE TITLE
Windows 10 pybind11 embed, Fatal Python error: initfsencoding: unable to load the file system codec

### ISSUE THREAD

**Issue by sejabs** [pybind/pybind11#1930]
When I use PyBind11 to embed Python interpereter, I faced the error:
`initfsencoding: unable to load the file system codec`. 

The details:
OS: Windows 10 1903 18362.356
Python 3.7.4 & Packages: Miniconda installed at `C:\Users\My\Miniconda3\envs\sci_dev`
MSVS: 2019 community 16.2.5
PyBind11: compiled with VS 2019 from git source with Boost, Eigen and Catch. Installed to `C:\Users\My\Miniconda3\envs\sci_dev` with only `include` and `share`

CMakeLists.txt

    cmake_minimum_required( VERSION 3.15 )

    project( "PyBind11_Test" )
    enable_language(C)
    enable_language(CXX)

    find_package(pybind11 CONFIG REQUIRED PATHS 
        "C:/Users/My/Miniconda3/envs/sci_dev/share/cmake")`
    include_directories( "C:/Users/My/Miniconda3/envs/sci_dev/include/pybind11" )
    MESSAGE( [Main] " pybind11_INCLUDE_DIRS = ${pybind11_INCLUDE_DIRS}" )
    MESSAGE( [Main] " pybind11_LIBRARIES = ${pybind11_LIBRARIES}" )

    add_executable(PyBind11_Test main.cpp)
 
    target_include_directories( PyBind11_Test PRIVATE "C:/Users/My/Miniconda3/envs/sci_dev/include   
            /pybind11" )                                                                    

    target_link_libraries(PyBind11_Test PRIVATE pybind11::embed)

and main.cpp

    #include <pybind11/embed.h>
    #include <iostream>
    namespace py = pybind11;
    int main() {
	    py::scoped_interpreter guard{};
	    /*
	    import sys
	    print sys.path
	    print "Hello,World!"
	    */
	    auto sys = py::module::import("sys");
	    // sys.attr("path").attr("insert")(1, "C:/Users/My/Miniconda3/envs/sci_dev/Lib/site-packages");
	    py::print(sys.attr("path"));
	    py::print("Hello, World!"); // use the Python API
	
	    //auto math = py::module::import("math");
	    //double root_two = math.attr("sqrt")(2.0).cast<double>();

	    //std::cout << "The square root of 2 is: " << root_two << "\n";

}

When VS configure is Release X64, running the build exe file in the cmd, it will report error:
> Fatal Python error: initfsencoding: unable to load the file system codec
> ModuleNotFoundError: No module named 'encodings'

> Current thread 0x00001628 (most recent call first):

**Comment by sejabs** [comment]
I searched online and found a similar error occurred : [Py_Initialize fails - unable to load the file system codec](https://stackoverflow.com/questions/5694706/py-initialize-fails-unable-to-load-the-file-system-codec), so according to the method I resolved the error by adding an environment variable "PYTHONPATH" and "PATHONHOME " which point to the installation location of Python

`PATHONPATH="C:\Users\My\Miniconda3\envs\sci_dev\DLLs;C:\Users\My\Miniconda3\envs\sci_dev\Li 
     b;C:\Users\My\Miniconda3\envs\sci_dev\Lib\site-packages"`
`PATHONHOME="C:\Users\CRRCHZ\Miniconda3\envs\sci_dev"`

Finally the .exe output expect result!

**Comment by helmesjo** [comment]
Setting the path manually is not really a valid solution, especially not when working with conda (changing environment will now have no effect, and changing environments is the whole point of conda).

What's the root cause here? Anyone got complete solution?

**Comment by LeslieGerman** [comment]
@helmesjo , I run basically the same issue, but in different context, some time ago. Then I debugged inside CPython and found somehow that it relies on PYTHONPATH, when it tries to locate its own DLLs - AFAI remember.

I'm not aware of any easy solution/workaround, but I would be glad to see such...

**Comment by wolfleyb** [comment]
> @helmesjo , I run basically the same issue, but in different context, some time ago. Then I debugged inside CPython and found somehow that it relies on PYTHONPATH, when it tries to locate its own DLLs - AFAI remember.
> 
> I'm not aware of any easy solution/workaround, but I would be glad to see such...

@LeslieGerman You you have the exact location where CPython was relying on PYTHONPATH?

**Comment by helmesjo** [comment]
@wolfleyb Unfortunately not, this was a while ago... But I remember that setting the path before executing the exe worked!

**Comment by YannickJadoul** [comment]
@wolfleyb @helmesjo, quoting https://github.com/pybind/pybind11/issues/2369#issuecomment-671275029 (maybe we ought to continue the discussion there?):

> Does this also happen with a Python.org Python installation? If not, we might need to blame Anaconda, rather than pybind11?

**Comment by wolfleyb** [comment]
@YannickJadoul I started a new issue because this one was marked "closed". I feel like it is still an open issue.

**Comment by YannickJadoul** [comment]
@wolfleyb, yes, but @sejabs closed it himself almost a year ago. It seems easier to continue in #2369 and cross link here, then, no?
