### ISSUE TITLE
Converting C++ time_point into Python datetime

### ISSUE THREAD

**Issue by hjk41** [pybind/pybind11#1935]
I have a time_point in C++ and I want to use it in Python as datetime. How do I do that?

More specifically, I have a function that returns pybind11::object. I want it to return pybind11::int_ and datetime depending on some runtime information. Current the code looks like this:
```C++
pybind11::object Foo(int x) {
    if(x) 
        return pybind11::int_(x);
    else
        return time_point();
}
```

But the code won't compile, saying there is no conversion from time_point to pybind11::object. What should I do to make it work?

**Comment by molpopgen** [comment]
Are you including the [right headers](https://pybind11.readthedocs.io/en/stable/advanced/cast/chrono.html)??

**Comment by hjk41** [comment]
I included both pybind11.h and chrono.h. Here is the code:
```C++
#include <iostream>
#include <functional>
#include <string>
#include <type_traits>
using namespace std;

#include <pybind11/pybind11.h>
#include <pybind11/chrono.h>

pybind11::object Foo(int x) {
    if (x) return pybind11::int_(x);
    else return pybind11::object(std::chrono::system_clock::time_point());
}

int main(int, char**) {
    auto f = Foo(10);
    return 0;
}
```

**Comment by molpopgen** [comment]
Give this a try:

```cpp
pybind11::object
Foo(int x)
{
    if (x) {return pybind11::int_(x);}
    else
    {
        auto y = std::chrono::system_clock::time_point();
        auto o = pybind11::cast(y);
        return o;
    }
}
```

**Comment by hjk41** [comment]
This one works like a charm. Thanks @molpopgen 

Another question, how do I check if a pybind11::object is a datetime or not? I need something like:
```C++
if (pybind11::isinstance<pybind11::str>(o)) {
        return Any(o.cast<std::string>());
}
else if (pybind11::isinstance<pybind11::int_>(o)) {
        return Any(o.cast<int64_t>());
}
// else if o is datetime, cast it to time_point
// {
//    don't know how to write this part
// }
else {
        ERR() << "unsupported python type";
}
```

**Comment by molpopgen** [comment]
Not sure about the reverse cast.  You may have to have it be the final else and re-throw any exception raised when trying to cast.
