### ISSUE TITLE
[Question] Dependency of two interfaces to create binding

### ISSUE THREAD

**Issue by marcelotrevisani** [pybind/pybind11#1942]
Hi folks,

I have a question which I can't find in the documentation the explanation.

I have two C interfaces on different projects. 

Let's say

- Project1/interface1.h
- Project2/interface2.h

I was creating some bindings for the ``interface1.h``, but I realize that there are some ``structs`` there which have the type defined in the ``interface2.h``.

There is an example here:

``interface1.h``
```c
typedef struct _type_def_interface2 *pointer_type2;

pointer_type2 func_1(error_code *errcode, void *opac);
````

``interface2.h``
```c
struct _type_def_interface2 {
  size_t size_1;
  size_t size_2;
  std::shared_ptr<foo_namespace::foo_class> _shr_ptr_; 
}
```

PS: I am creating the bindings for both interface, but I don't know how to link them because of that dependency

**Comment by sizmailov** [comment]
I guess the question is "How to express modules dependency in pybind11?"  ? 

Generic advise: you should look at `PYBIND11_MODULE` macro content as a regular python module with a C++ syntax. Just do what you were going to do in python, but follow C++ and pybind11 rules. 

Here is minimal snippet to illustrate the idea: [gist](https://gist.github.com/sizmailov/987dfdd2874514414317262b061f2890)

**Comment by marcelotrevisani** [comment]
> I guess the question is "How to express modules dependency in pybind11?" ?
> 
> Generic advise: you should look at `PYBIND11_MODULE` macro content as a regular python module with a C++ syntax. Just do what you were going to do in python, but follow C++ and pybind11 rules.
> 
> Here is minimal snippet to illustrate the idea: [gist](https://gist.github.com/sizmailov/987dfdd2874514414317262b061f2890)

Thank you very much @sizmailov !
I am going to close it then!
