### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by dibya001** [pybind/pybind11#1943]
Entire Python community is moving towards python 3. When is the plan for pybind11 to drop python 2 support entirely.

**Comment by wjakob** [comment]
There are loads of projects that will depend on python 2.x for many years to come (research code, legacy projects, etc.), and there is little to no cost to keeping support for legacy Python alive for that time. Removing Python 2.x from pybind11 would actually be quite a bit of work: to strip out ifdefs, adopt testcases, CI, etc.

What you suggest is a very hostile move, and it's not going to happen on my watch. Period.

**Comment by kalvdans** [comment]
Dropping python2 would help going forward with the `bytearray` support, issue https://github.com/pybind/pybind11/issues/2523.

**Comment by YannickJadoul** [comment]
@kalvdans, pybind11 is near at the bottom of the hierarchy, being depended on not only by libraries, but also aiming to support PyPy (which isn't immediately dropping Python 2 support).
As @wjakob clearly stated, there's currently no plan to drop Python 2 support (even thought the focus lies on Python 3, most of the time).

#2523 is not blocked by Python 2 (I could envisage the addition of `bytearray` for Python 3-only, given good arguments; or maybe there are other solutions), but by the lack of reaction to a simple question: https://github.com/pybind/pybind11/issues/2523#issuecomment-696976298
