### ISSUE TITLE
Potential bug in passing mutable object by reference

### ISSUE THREAD

**Issue by bpatzak** [pybind/pybind11#1947]
I believe I have identified a potential bug in passing mutable object by reference. The problem is best illustrated on attached simple example. 
I would expect that as the Value instance is passed by reference, one should obtain "11" as a result. However, when Python derived class is passed to test function, wrong result (10) is obtained. The mutable object is passed by reference, but its state is not changed, however the state has been modified, but probably on its copy.
Any help would be appreciated.  
[demo.zip](https://github.com/pybind/pybind11/files/3693221/demo.zip)

**Comment by molpopgen** [comment]
I took a quick look, and I think you need some extra "glue" to get this working.  [This](https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python) section of the manual is likely helpful?

**Comment by bpatzak** [comment]
I am aware of what you recommended and followed exactly this pattern by defining appropriate trampoline class. The Python method overriding the C++ one is correctly called. However, the modification of mutable argument passed by reference to this method is not observable on the caller level (looks like the method receives copy and not true reference).

**Comment by molpopgen** [comment]
Your trampoline override isn't quite right.  Try this:

```cpp
  // trampoline (need one for each virtual method)
  void f (Value& a) override {
    PYBIND11_OVERLOAD (void, A, f, std::ref(a));
  }
```

**Comment by molpopgen** [comment]
This is hard to catch b/c of the macro.  The usual compiler flags to warn about changing a virtual function signature cannot work.

**Comment by bpatzak** [comment]
Thank you a lot, it works. Perhaps this could be considered as potential improvement of the documentation.
