### ISSUE TITLE
Invoking Python (using sklearn) from C++ in a thread different from the interpreter yields a deadlock

### ISSUE THREAD

**Issue by k-b-1** [pybind/pybind11#1952]
I instantiate the interpreter and a module in one thread 
```
_guard = std::make_unique<py::scoped_interpreter>();`
_moduleInst = std::make_unique<py::module>();
*_moduleInst = py::module::import('someModule');

```
and invoke python functions in another thread:
```
...
_module->attr("someFunction")(someParameter)

```
This works fine so far with python functions working with numpy and pandas.

However, when I try to work with sklearn the fit function will not return:
```
from sklearn.tree import DecisionTreeClassifier
df = pd.read_csv('someFile.csv', dtype={"y":np.str})
clf = DecisionTreeClassifier(random_state=0, max_depth=3)
clf.fit(df[['x']], df['y'])

```

The fit function returns when I call the function from the same thread I used to instantiate the interpreter and the module. Pandas and numpy seem to work in all cases.

Any ideas?
Thanks.

**Comment by bstaletic** [comment]
> and invoke python functions in another thread:

Before you can do that, you have to release the GIL in the main thread and acquire it in that other thread. The GIL will be released at the end of the scope of the spawned thread, at which point the main thread needs to reacquire the GIL.

> This works fine so far with python functions working with numpy and pandas.

You basically got lucky.
