### ISSUE TITLE
Questions about __init__, construction, undefined behaviour and exception safety

### ISSUE THREAD

**Issue by bluescarni** [pybind/pybind11#196]
I am struggling to understand exactly what is going on in snippets of code like this (taken from the documentation):

```c++
py::class_<Example>(m, "Example")
    .def("__init__",
        [](Example &instance, int arg) {
            new (&instance) Example(arg);
        }
    );
```

I understand that the intent here is to call placement new into the memory area of ``instance`` to construct the ``Example`` object with the provided argument ``arg``. My first question is: how is the reference ``Example &instance`` obtained? I am familiar with the use of, e.g., aligned storage + placement new on a ``void *`` after a couple of ``static_cast``s, but I am wondering how it has been implemented in pybind11 since it is using reference semantics.

Secondly, what happens if the constructor throws? Imagine something like this:

```c++
py::class_<Example>(m, "Example")
    .def("__init__",
        [](Example &instance, int arg) {
            new (&instance) Example(arg);
            throw std::runtime_error("");
        }
    );
```

Or imagine even that the ``throw`` is placed before the placement new call. What is it going to happen in that case? Is pybind11 going to call the destructor of ``Example``? Can it detect if the C++ constructor has been called or not?

This seems to be a worse issue in the pickling support:

```c++
    .def("__setstate__", [](Pickleable &p, py::tuple t) {
        if (t.size() != 2)
            throw std::runtime_error("Invalid state!");

        /* Invoke the in-place constructor. Note that this is needed even
           when the object just has a trivial default constructor */
        new (&p) Pickleable(t[0].cast<std::string>());

        /* Assign any additional state */
        p.setExtra(t[1].cast<int>());
    });
```

Here the C++ constructor of ``Pickleable`` may or may not be called depending on the content of ``t``.

Am I missing something obvious?

**Comment by wjakob** [comment]
Feel free to peek under the hood, the code is fairly compact. In the case of ``__init__``, the instance is only marked as initialized if the constructor returns without throwing. In the case of ``__setstate__``, I must admit that I am not sure.

**Comment by bluescarni** [comment]
Thanks for the reply! So in both this case

```c++
py::class_<Example>(m, "Example")
    .def("__init__",
        [](Example &instance, int arg) {
            new (&instance) Example(arg);
            throw std::runtime_error("");
        }
    );
```

and in this one

```c++
py::class_<Example>(m, "Example")
    .def("__init__",
        [](Example &instance, int arg) {
            throw std::runtime_error("");
            new (&instance) Example(arg);
        }
    );
```

is the destructor of ``Example`` called or not?

**Comment by wjakob** [comment]
Don't take my word for it -- why don't you try this out yourself by compiling some examples with prints in the constructor?

**Comment by bluescarni** [comment]
So I made a couple of experiments. The C++ class is:

```c++
struct foobar
{
    foobar()
    {
        std::cout << "foobar ctor\n";
    }
    ~foobar()
    {
        std::cout << "foobar dtor\n";
    }
};
```

Take 1:

```c++
    py::class_<foobar> f_class(m,"foobar");
    f_class.def("__init__",[](foobar &instance) {
            new (&instance) foobar();
        }
    );
```
```ipython
In [2]: f = foobar()
foobar ctor

In [3]: 
Do you really want to exit ([y]/n)? 
foobar dtor
```

Constructor called, destructor called. Take 2:

```c++
    py::class_<foobar> f_class(m,"foobar");
    f_class.def("__init__",[](foobar &instance) {
            throw std::runtime_error("");
            new (&instance) foobar();
        }
    );
```
```ipython
In [2]: f = _core.foobar()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-c2813e8e0ee9> in <module>()
----> 1 f = _core.foobar()

RuntimeError: 

In [3]: 
Do you really want to exit ([y]/n)?
```

No constructor called, no destructor called. Take 3:

```c++
    py::class_<foobar> f_class(m,"foobar");
    f_class.def("__init__",[](foobar &instance) {
            new (&instance) foobar();
            throw std::runtime_error("");
        }
    );
```
```ipython
In [2]: f = _core.foobar()
foobar ctor
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-c2813e8e0ee9> in <module>()
----> 1 f = _core.foobar()

RuntimeError: 

In [3]: 
Do you really want to exit ([y]/n)?
```

Here the constructor is called, but the destructor never called.

**Comment by wjakob** [comment]
Use case 3 is really something that cannot be handled in pybind11. It cannot peek inside and thus only considers the __init__ function as a whole. For the latter case, you might need some logic which calls the destructor if an exception is detected in the lines following the placement new call.

**Comment by bluescarni** [comment]
Ok thanks for the reply, it was not clear from the documentation whether the object is considered as constructed or not in face of an excpetion in an init (or init-like) method.

**Comment by wjakob** [comment]
One thing I'm wondering (a bit worriedly): is the destructor ever called for unserialized objects?

**Comment by bluescarni** [comment]
What do you mean by unserialized object?

**Comment by wjakob** [comment]
Something that is un-pickled and initialized by ``__setstate__``. I am not sure if I ever tested the destruction of those objects.

**Comment by bluescarni** [comment]
Is ``__setstate__`` handled specially? I am afraid I don't know enough about the internals of Python serialization to know for sure... I mean, is one supposed to be able to call ``__setstate__`` on an already-constructed object? Because in that case it would seem like the object is re-constructed with placement new in the examples above.

**Comment by wjakob** [comment]
The un-pickling process calls the proper incantations of __new__ and __setstate__, and that the latter basically takes the place of the constructor. I'm just wondering if pybind11 considers the resulting object  as successfully constructed..

**Comment by bluescarni** [comment]
Thanks for the explanation!

If I am reading correctly, you are afraid that the "special" type of initialisation performed by the unpickling process does not correctly set a "constructed" flag in the pybind object?

**Comment by wjakob** [comment]
yes -- since you mentioned being interested in serialization, I thought that you could quickly check this while coding up your serialization code. If not, never mind.

**Comment by bluescarni** [comment]
I just checked. I hope I did not make any mistake in the serialisation code (I was just starting working on it tonight), but it looks like indeed the dtor is not called:

```ipython
In [1]: from pickle import loads, dumps

In [2]: from pygmo import _core

In [3]: rb = _core.rosenbrock(100)
rosen ctor

In [4]: s = dumps(rb)

In [5]: del rb
rosen dtor

In [6]: foo = loads(s)
rosen ctor

In [7]: del foo

In [8]:
```

**Comment by bluescarni** [comment]
(also, closing the python session does not call the destructor as well)

**Comment by wjakob** [comment]
I pushed a fix -- can you commit whether that works for you?

**Comment by bluescarni** [comment]
Thanks, it looks like the issue is fixed :)

**Comment by wjakob** [comment]
great, thanks for checking.
