### ISSUE TITLE
Using a memoryview object as a function parameter

### ISSUE THREAD

**Issue by rschutt** [pybind/pybind11#1964]
Using a memoryview object as a function parameter causes compiler errors.

```
#include <pybind11/pybind11.h>

namespace py = pybind11;

PYBIND11_MODULE(test, m){
    m.def("test_func", [](const py::memoryview & memoryview){
    });
}
```

Adding a default constructor to the py::memoryview class seems to fix the issue:
```
class memoryview : public object {
public:
    memoryview() : object() {}
...
```

**Comment by sighingnow** [comment]
For whom who still stucks on this issue, that a C++ parameter of type `py::buffer` can directly accept a Python object of type `memoryview` as argument.

This issue can be closed as resolved.
