### ISSUE TITLE
Use Tbb malloc instead of native ntdll.dll

### ISSUE THREAD

**Issue by akhaled86** [pybind/pybind11#1973]
I had a c++ code that uses tbbmalloc_proxy and this improved the performance alot on Windows 10
I wrapped the code using pybind11 but it seems that pybind ignores tbb and just uses the malloc implmenetation from ntddll.dll
Any ideas how to overcome this issue ?

**Comment by bstaletic** [comment]
Pybind *has to* use pymalloc when it calls python's C API. There's no way around that. However you can do things like `PYTHONMALLOC=malloc` and force pymalloc to actually be malloc. THen everything would be overrideable.

Apart from that, see https://docs.python.org/3/c-api/memory.html

For more questions, either reopen the issue or visit us on gitter.

**Comment by 1003581** [comment]
> I had a c++ code that uses tbbmalloc_proxy and this improved the performance alot on Windows 10 I wrapped the code using pybind11 but it seems that pybind ignores tbb and just uses the malloc implmenetation from ntddll.dll Any ideas how to overcome this issue ?

Hello, have you overcome this issue yet? I had the sample issue with SWIG.
