### ISSUE TITLE
CXX flags passed to nvcc using CMake make compilation fail

### ISSUE THREAD

**Issue by f-marelli** [pybind/pybind11#1991]
## Issue description

Compilation fails when using CMake and pybind11_add_module for project containing CUDA code. The -flto flag is passed to NVCC and causes the following output:
`nvcc fatal   : Unknown option 'flto'`

## Reproducible example code
In CMakeLists.txt:

cmake_minimum_required(VERSION 3.14)
project(projectname LANGUAGES CXX CUDA)
find_package(pybind11 REQUIRED)

pybind11_add_module(modulename src/cpp_source.cpp src/cuda_source.cu)

## Possible solution

In `pybind11/tools/pybind11Tools.cmake`, line [104](https://github.com/pybind/pybind11/blob/bd24155b8bf798f9f7022b39acd6d92e52d642d6/tools/pybind11Tools.cmake#L104):
-use `$<$<COMPILE_LANGUAGE:CXX>:` to set the flag only for GCC
-pass it to nvcc as `-Xcompiler=-flto`

**Comment by YannickJadoul** [comment]
It might be even better to add this as a case to this if-block? https://github.com/pybind/pybind11/blob/bd24155b8bf798f9f7022b39acd6d92e52d642d6/tools/pybind11Tools.cmake#L62

Feel free to submit a PR. Otherwise, we'll put it on the backlog of "things to get to at some point".

**Comment by bstaletic** [comment]
Nvidia's docs have this section that might be interesting.

https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-guiding-compiler-driver-forward-host-compiler
