### ISSUE TITLE
Better support for const buffers

### ISSUE THREAD

**Issue by nedrebo** [pybind/pybind11#1993]
The `buffer_info` class takes a `void *`. I propose to support `const void *`.

* Removes need for `const_cast` when you have a `const T *` (only possible if you know memory is mutable)
* Read only access of mutable memory will be supported by using `std::as_const` or a safe "to const" `const_cast`.

**Comment by nedrebo** [comment]
Related PR: https://github.com/pybind/pybind11/pull/1466

I think a const "overload" is better. With two parameters you need to keep them in sync, that is a source of errors. Also the `buffer_info` signature does not guarantee that memory will not be mutated even when you pass in a `readonly=true`. Passing in const memory after `const_cast` it is still scary with `readonly=true`.

**Comment by wjakob** [comment]
PR #1466 was just merged.

**Comment by nedrebo** [comment]
Fixed in #1466 by adding this constructor.

https://github.com/pybind/pybind11/blob/dc65d661718ed10a9d212f1949813f7a7acf9437/include/pybind11/buffer_info.h#L50-L52
