### ISSUE TITLE
Update to Python 3.8

### ISSUE THREAD

**Issue by tim-hilt** [pybind/pybind11#1994]
Installed from Github, host is Arch Linux. Arch uses Python 3.8 already, so when compiling the example from [the docs](https://pybind11.readthedocs.io/en/stable/basics.html), with

```
$ c++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` example.cpp -o example`python3-config --extension-suffix`
```

It searches the module in:

```
In [1]: import sys

In [2]: sys.path
Out[2]:
['/usr/bin',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '',
 '/usr/lib/python3.8/site-packages',
 '/usr/lib/python3.8/site-packages/IPython/extensions',
 '/home/tim/.ipython']
```

But the module doesn't seam to be there.

**Comment by wjakob** [comment]
Are you saying that python 3.8 doesn't search for modules in the local folder anymore?

**Comment by tim-hilt** [comment]
I actually messed this up myself somehow. I didn't install the python-package, only compiled the sources and thought that would suffice.
