### ISSUE TITLE
std::complex<T> not resolved correctly

### ISSUE THREAD

**Issue by nils-werner** [pybind/pybind11#200]
Consider the following example

    import numpy
    import ctest

    print ctest.square(numpy.arange(3, dtype=float))
    print ctest.square(numpy.arange(3, dtype=float) * 1j)

    print ctest.square(9.0)
    print ctest.square(9.0 * 1j)

where `ctest` is my pybind11 module

    #include <pybind11/pybind11.h>
    #include <pybind11/numpy.h>
    #include <pybind11/complex.h>

    namespace py = pybind11;

    template <typename T>
    T square(T x) {
        return x * x;
    }

    void pyexport(py::module& m) {
        m.def("square", py::vectorize(square<std::complex<double>>));
        m.def("square", py::vectorize(square<std::complex<float>>));
        m.def("square", py::vectorize(square<float>));
        m.def("square", py::vectorize(square<double>));
    }

The problem is that my functions are always resolved to the `std::complex` type, the above Python code returning

    [ 0.+0.j  1.+0.j  4.+0.j]
    [ 0.+0.j -1.+0.j -4.+0.j]
    (81+0j)
    (-81+0j)

 1. should be real valued
 2. is OK
 3. should be real valued
 4. is OK

If I now reorder my `def`s like

    void pyexport(py::module& m) {
        m.def("square", py::vectorize(square<float>));
        m.def("square", py::vectorize(square<double>));
        m.def("square", py::vectorize(square<std::complex<double>>));
        m.def("square", py::vectorize(square<std::complex<float>>));
    }

the `std::complex` type is never resolved:

    [ 0.  1.  4.]
    test.py:8: ComplexWarning: Casting complex values to real discards the imaginary part
      print ctest.square(numpy.arange(3, dtype=float) * 1j)
    [ 0.  0.  0.]
    81.0
    Traceback (most recent call last):
      File "test.py", line 11, in <module>
        print ctest.square(9.0 * 1j)
    TypeError: Incompatible function arguments. The following argument types are supported:
        1. (array[float]) -> object
        2. (array[float]) -> object
        3. (array[complex]) -> object
        4. (array[complex]) -> object

 1. is OK
 2. is implicitly cast back to real valued number (not OK)
 3. is Ok
 4. fails to resolve

**Comment by wjakob** [comment]
First of all: there is no way to distinguish between float and single precision in Python. The first overload that you specify will always be used.

**Comment by nils-werner** [comment]
I also noticed that

    print type(ctest.square(9))
    print type(ctest.square(9.0))

and

    void pyexport(py::module& m) {
        m.def("square", py::vectorize(square<int>));
        m.def("square", py::vectorize(square<float>));
        m.def("square", py::vectorize(square<double>));
    }

will always yield `long`.

Did I miss that overloading `m.def()`s are not possible?

**Comment by wjakob** [comment]
Overloading is fine, problems appear when one type is implicitly convertible to another type. Since your use case is fairly advanced, I fear that you are on your own -- you'll have to create a single overload which takes a py::object and then write the code yourself that invokes the various specializations after inspecting the contents using the Python C API.

**Comment by wjakob** [comment]
You could also accept a py::buffer and then inspect the buffer's "format" flag -- maybe that is the easiest. Afterwards, you could simply call py::vectorize(square<int>)(array_t<int>(object_arg)) if it's an int, etc.

**Comment by nils-werner** [comment]
Implicit conversion makes sense, that still doesn't explain why in some cases the correct type cannot be resolved at all.

**Comment by wjakob** [comment]
After thinking a bit more about it, I suppose that these sorts of overloads would be useful to have without the forceful casts. This commit should address your problems: https://github.com/pybind/pybind11/commit/b47a9de03542df3743f252b935c52e0d8582a77c -- see the selective_func examples. You will then have to call py::vectorize from that.

**Comment by wjakob** [comment]
(All of this was related to the forcecast argument that was provided to NumPy by deafult. Can you confirm that it works for you with this change?)

**Comment by nils-werner** [comment]
Not yet, I am still struggling with [making it compile when `pip install -e` installing pybind](https://github.com/pypa/pip/issues/3696). :-)

**Comment by nils-werner** [comment]
Yes, that indeed fixes it. Order of definition still matters though.

**Comment by wjakob** [comment]
Yes, that always matters in pybind11. It tries one overload after the other until one works.

**Comment by nils-werner** [comment]
For future reference

    import cppimport
    cppimport.set_quiet(False)

    import numpy
    import ctest

    # builtin types
    for v in [
        9,
        9 * 1j,
        9.0,
        9.0 * 1j,
    ]:
        print type(v), type(ctest.square(v))

    # numpy types
    for v in [
        numpy.arange(3),
        numpy.arange(3, dtype=float),
        numpy.arange(3) * 1j,
        numpy.arange(3, dtype=float) * 1j,
    ]:
        print v.dtype, ctest.square(v).dtype

and

    #include <pybind11/pybind11.h>
    #include <pybind11/numpy.h>
    #include <pybind11/complex.h>

    namespace py = pybind11;

    template <typename T>
    T square(T x) {
        return x * x;
    }

    void pyexport(py::module& m) {
        m.def("square", square<long>);
        m.def("square", square<double>);
        m.def("square", [](py::array_t<long, py::array::c_style> x) { return py::vectorize(square<long>)(x); });
        m.def("square", [](py::array_t<double, py::array::c_style> x) { return py::vectorize(square<double>)(x); });
        m.def("square", [](py::array_t<std::complex<double>, py::array::c_style> x) { return py::vectorize(square<std::complex<double>>)(x); });
    }

now yield

    <type 'int'> <type 'long'>
    <type 'complex'> <type 'complex'>
    <type 'float'> <type 'float'>
    <type 'complex'> <type 'complex'>
    int64 int64
    float64 float64
    complex128 complex128
    complex128 complex128

**Comment by aldanor** [comment]
@wjakob Would you consider reverting the `forcecast` default (or changing it to `c_style`)? This is an "implicit versus explicit" kind of issue -- if your function accepts arrays of ints, it probably wants just that. If it expects a structured type and you give it a bunch of ints, it's likely a user error and you don't want those values to be copied over all fields. Also, (as with the example in this issue) the overloads may not work as you would expect them to unless you disable the forcecast; I believe it's quite counter-intuitive from C++ point of view.

It gets even more weird once you start working with structured arrays. NumPy will happily cast anything to anything according to a set of strange conventions. Chances are, you'll *never* want to see any of this happen accidentally. Just a few examples:

```python
# cast ints to structs
>>> a = np.array([1, 2, 3], dtype='u2')
>>> a.astype([('a', 'u4'), ('b', 'u1')], casting='unsafe')
array([(1, 1), (2, 2), (3, 3)], 
      dtype=[('a', '<u4'), ('b', 'u1')])

# happily cast integer structs to floats, discarding half of the data
>>> np.rec.fromarrays([[1, 2, 3], [4, 5, 6]]).astype('f4', casting='unsafe')
rec.array([ 1.,  2.,  3.], 
          dtype=float32)

# strings to bools, no problem
>>> np.array(['-1', '0', '1']).astype('bool', casting='unsafe')
array([ True, False,  True], dtype=bool)
```

**Comment by wjakob** [comment]
Yes, I am open to this. It will go into the next major version.

**Comment by wjakob** [comment]
Actually, let me take a step back before committing to this yet. The only reason why the forcecast convention was there is that NumPy will by default not convert a list like [0, 0, 1] to a 3D float vector. Do you see any way to accomplish this while avoiding over-eager casts?

**Comment by aldanor** [comment]
Could you be more specific about "NumPy will by default not convert a list like [0, 0, 1] to a 3D float vector", an example?

**Comment by aldanor** [comment]
Do you mean `PyArray_FromAny`?

**Comment by wjakob** [comment]
See the following diff which applies to HEAD and basically implements your suggestion
[diff.txt](https://github.com/pybind/pybind11/files/337133/diff.txt)
This fails the test suite because int vectors are not automatically cast to float vectors anymore. 

Maybe it's just pybind11's fault for not accessing NumPy through the right set of API calls. For instance, it seems to treat arithmetic involving integer and floating point types more leniently:
```
>>> np.array([1,2,3]) * np.array([1,2,3], dtype=np.float32)
array([ 1.,  4.,  9.])
```

**Comment by aldanor** [comment]
I see -- I was thinking about this too recently -- I was trying to make pybind11 disambiguate between overloads on `array_t<SimpleStruct>` and `array_t<PackedStruct>` and it seemed impossible with the current machinery (it would always call the first one defined no matter what, with forcecast off). This is pretty bad since sometimes you want to be sure the data is *not* copied if the function's objective is to mutate it. The only way to achieve that would be through a `NPY_NO_CASTING` check. Also, I don't think  `forcecast` is a proper solution for this at all.

What we can do, I think, is expose casting rules:

```rst
.. c:type:: NPY_CASTING

    .. versionadded:: 1.6

    An enumeration type indicating how permissive data conversions should
    be. This is used by the iterator added in NumPy 1.6, and is intended
    to be used more broadly in a future version.

    .. c:var:: NPY_NO_CASTING

        Only allow identical types.

    .. c:var:: NPY_EQUIV_CASTING

       Allow identical and casts involving byte swapping.

    .. c:var:: NPY_SAFE_CASTING

       Only allow casts which will not cause values to be rounded,
       truncated, or otherwise changed.

    .. c:var:: NPY_SAME_KIND_CASTING

       Allow any safe casts, and casts between types of the same kind.
       For example, float64 -> float32 is permitted with this rule.

    .. c:var:: NPY_UNSAFE_CASTING

       Allow any cast, no matter what kind of data loss may occur.
```

So, in `array_t::ensure` we could first check if what we're receiving as an argument is a NumPy array, if it is, we can first do a cast check according to a casting rule (`PyArray_CanCastTypeTo`).

This could be set to safe casting by default, which would rule out casting from structs to scalars or floats to ints and the like.

One more point -- the `NPY_NO_CASTING` flag only makes sense, I think, if the input object is already an ndarray (and not a Python list or whatnot). Setting this flag plus the `NPY_CONTIGUOUS` would pretty much ensure you're not getting a copy of the array and you can mutate the original.

**Comment by wjakob** [comment]
Exposing the casting flags in some way from within pybind11 sounds like a reasonable way to go. There will be an upcoming 2.0 release fairly soon where it would be acceptable to break API compatibility in ``numpy.h``. It would be fine to give up the current way of passing these via template parameters if the alternative is superior.

As you are clearly more experienced with the NumPy API and interested in this, would you be willing to take the initiative on this?

**Comment by aldanor** [comment]
@wjakob Yea, I sort of have a free week on my hand so I could take a shot at this, I'm very interested personally about getting this right :)

To be able to hack on this though, I have to finish the structured/record array branch first -- would appreciate if you replied on the other thread about it.
