### ISSUE TITLE
Feature request: support of array_t<object>

### ISSUE THREAD

**Issue by HDembinski** [pybind/pybind11#2001]
Currently, pybind11 does not offer a nice API for working with numpy arrays with dtype O. It would be great if `array_t<object>` would act as a wrapper for this exotic array type.

There is a use-case for this: a sequence of Python strings with high redundancy is well represented by `array_t<object>`, because each location in the array then takes only 8 bytes. Similarly, it is a good fit when strings are to be processed that vary greatly in length.

**Comment by wjakob** [comment]
This would indeed be a useful feature but likely quite challenging to implement with the existing functionality in `numpy.h`. I'll close this ticket since it is out of scope for a feature request. If you do get around working on this, please feel free to open a pull request.

**Comment by HDembinski** [comment]
Thank you for agreeing that it would be a nice feature, but could you please share some insights why it is difficult?
According to this (which I haven't tried myself yet)
https://stackoverflow.com/questions/45124695/pybind11-return-numpy-array-of-objects
It is already possible to wrap an existing array of PyObject*.
