### ISSUE TITLE
Very generic operator overload causes ambigous overload resolution

### ISSUE THREAD

**Issue by SylvainCorlay** [pybind/pybind11#2002]
Pull request #1511 by @wjakob (commit 067100201fbeefc4e4bcc041c7e3a36a28e4c7f7) introduced a number of operator overloads for the base `object` class:

```
    object operator-() const;
    object operator~() const;
    object operator+(object_api const &other) const;
    object operator+=(object_api const &other) const;
    object operator-(object_api const &other) const;
    object operator-=(object_api const &other) const;
    object operator*(object_api const &other) const;
    object operator*=(object_api const &other) const;
    object operator/(object_api const &other) const;
    object operator/=(object_api const &other) const;
    object operator|(object_api const &other) const;
    object operator|=(object_api const &other) const;
    object operator&(object_api const &other) const;
    object operator&=(object_api const &other) const;
    object operator^(object_api const &other) const;
    object operator^=(object_api const &other) const;
    object operator<<(object_api const &other) const;
    object operator<<=(object_api const &other) const;
    object operator>>(object_api const &other) const;
    object operator>>=(object_api const &other) const;
```

which is causing some issues in our downstream projects, where we had also overloaded these operators for our more specific (base) types. Since our overload is also for a base class, the compiler fails to determine which overload to use. Cf https://github.com/xtensor-stack/xtensor-python/issues/203

Would it be possible to make these overloads more specific in pybind11? I presume this is not necessarily meant for any `object`?

**Comment by wjakob** [comment]
Hi Sylvain,

this commit was really intended to be this generic. These types of operations are possible with arbitrary Python objects, and the pybind11 API simply maps these basic protocols onto the C++ side.

While the operators in pybind11 are very generic, you should be able to reimplement the xtensor operators so that they are more specific to resolve issues with ambiguity. When deciding on an appropriate overload, C++'s type resolution walks down a partial order with regards to type
specificity and only complains when it's not clear which overload is more specific. I think that is what is happening here.

Best,
Wenzel

**Comment by SylvainCorlay** [comment]
> this commit was really intended to be this generic. These types of operations are possible with arbitrary Python objects, and the pybind11 API simply maps these basic protocols onto the C++ side.

Thanks, this was surprising to me since this is really a catch-all type of overload.

> While the operators in pybind11 are very generic, you should be able to reimplement the xtensor operators so that they are more specific to resolve issues with ambiguity. When deciding on an appropriate overload, C++'s type resolution walks down a partial order with regards to type
specificity and only complains when it's not clear which overload is more specific. I think that is what is happening here.

Since our overloads are also in CRTP base classes, it cannot be disambiguated. We will need to add some `using our_base::operator+=` in the first class that inherits from our base and `object`.

**Comment by wjakob** [comment]
I think you can *always* have a more specific top level overload:

```
template <typename A, typename B, std::enable_if_t<is_xtensor_v<A> || is_xtensor_v<B>, int> = 0> auto operator+(const A &a, const B &b) {
 ...
}
```
(assuming the existence of some kind of type trait `is_xtensor_v` that can identify the types used by your framework.)

**Comment by SylvainCorlay** [comment]
Yes, I am simply adding a `using` statement.

https://github.com/xtensor-stack/xtensor-python/pull/220

**Comment by SylvainCorlay** [comment]
We ended up deleting the pybind11 overloads in our base class so that it is not picked up by the overload resolution. See https://github.com/xtensor-stack/xtensor-python/pull/220.

**Comment by YannickJadoul** [comment]
I take it this can be considered as "resolved", then?
