### ISSUE TITLE
Import pybind11 module that is linked but not in python path

### ISSUE THREAD

**Issue by kenoslund-google** [pybind/pybind11#2003]
## Issue description

I want to define a class in C++ and create python bindings for it in the usual way. However, I need to create a custom type_caster for it, which will utilize the default version (ie, type_caster_base) but also add some additional logic on top of it.

Of course, if I want to use type_caster_base, the module defining my bindings must have been imported, or else my types will not have been registered and it will give an error. Therefore I want to import my pybind11 module from C++ code, probably directly from my custom caster.

I know that pybind11 provides pybind11::module::import(), but that takes the standard python import string and therefore requires the module be in the python path. But I just built that module (it's a pybind11 module, so it's C++ code) and linked it to my binary... it is *not* anywhere in my python path and so I don't think that I can use pybind11::module::import().

What alternative to pybind11::module::import() can I use in this case?

## Reproducible example code

My bindings:

```c++
struct MyType { void my_function() {} };
PYBIND11_MODULE(my_module, m) {
    py::class_<MyType>(m, "MyType").def("my_function", &MyType::my_function);
}
```

I know that `PYBIND11_MODULE` defines a function called `PyInit_NAME` where NAME is the first macro argument (so `PyInit_my_module` in this example).

My caster:

```c++
namespace pybind11 { namespace detail {
    template <> struct type_caster<MyType> {
    public:
        PYBIND11_TYPE_CASTER(MyType, _("MyType"));
        static handle cast(MyType src, return_value_policy policy, handle parent) {
            // Somehow import my_module. How? it's not in the python path so I
            // can't use module::import, and calling PyInit_my_module() did not work.

            // ... Some custom logic here ...

            // The next line will fail unless my_module was imported.
            return type_caster_base<MyType>::cast(src, policy, parent);
        }
    };
```

Calling `PyInit_my_module()` gives this error:

```
RuntimeError: MyType: PyType_Ready failed (SystemError: <built-in method mro of pybind11_type object at 0x7f2bf613018> returned a result with an error set)!
```

Thanks.

**Comment by YannickJadoul** [comment]
I'm not getting this. Is the custom caster defined and used in another extension module? Otherwise, I don't fully understand why you'd need to import this module into itself.

Since it's been over half a year since you asked this  - apologies, we just started reviving the project and cleaning up stuff - I'll close this. If you have more information and this is still an issue, please do reopen!
