### ISSUE TITLE
License category?

### ISSUE THREAD

**Issue by ChaiBapchya** [pybind/pybind11#2008]
What kind of license is this?
https://github.com/pybind/pybind11/blob/a1041190c8b8ff0cd9e2f0752248ad5e3789ea0c/LICENSE

MIT/Apache/Unlicense?

**Comment by pavelschon** [comment]
According to https://github.com/pybind/pybind11#license it's a BSD-style license.

**Comment by bstaletic** [comment]
It's called "3-clause BSD license".
