### ISSUE TITLE
Trouble finding pybind11.h

### ISSUE THREAD

**Issue by chadgh** [pybind/pybind11#201]
I'm trying to use [cppimport](https://github.com/tbenthompson/cppimport/) and when I pip install it and try to run it's example in a new virtualenv (Python 3.5.1) it can't compile my C++ code because it can't find `pybind11/pybind11.h`.

I've posted this [issue](https://github.com/tbenthompson/cppimport/issues/2) to the cppimport project and it looks like there is a problem with pybind11 not finding where it has been installed correctly.

I'm using pyenv and virtualenvs with Python 3.5.1, if that helps.

**Comment by wjakob** [comment]
I'll further defer and say that this is a pip issue and not related to pybind11. Pybind11 is asking pip for the include path, and it returns an incorrect result in your case. Maybe related to this issue: https://github.com/pypa/pip/issues/3696
