### ISSUE TITLE
GCC-4.8 compatibility issue of numpy.h

### ISSUE THREAD

**Issue by chaekwan** [pybind/pybind11#2011]
Make sure you've completed the following steps before submitting your issue -- thank you!

1. Check if your question has already been answered in the [FAQ](http://pybind11.readthedocs.io/en/latest/faq.html) section.
2. Make sure you've read the [documentation](http://pybind11.readthedocs.io/en/latest/). Your issue may be addressed there.
3. If those resources didn't help and you only have a short question (not a bug report), consider asking in the [Gitter chat room](https://gitter.im/pybind/Lobby).
4. If you have a genuine bug report or a more complex question which is not answered in the previous items (or not suitable for chat), please fill in the details below.
5. Include a self-contained and minimal piece of code that reproduces the problem. If that's not possible, try to make the description as clear as possible.

*After reading, remove this checklist and the template text in parentheses below.*

## Issue description

(Provide a short description, state the expected behavior and what actually happens.)

## Reproducible example code

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete C++ and Python snippets that can be easily compiled and run to diagnose the issue.)

**Comment by chaekwan** [comment]
When I tried to compile pybind11 with gcc-4.8.3 with -D_GLIBCXX_USE_CXX11_ABI == 0, #include <pybind11/numpy.h> causes the compile error for pybind11 2.4.3 versin.

I have checked the code, and it seems that the issue is at that code only checks defined(_GLIBCXX_USE_CXX11_ABI) at line 314.

Can you please change it to the following code?
(defined(_GLIBCXX_USE_CXX11_ABI) && (_GLIBCXX_USE_CXX11_ABI == 1))

Because I'm integrating the pybind11 to the tool, and the tool uses -D_GLIBCXX_USE_CXX11_ABI == 0 to make sure the gcc ABI compability. The thing is that I can't remove it from the tool.

Thanks,
Cahekwan

**Comment by wjakob** [comment]
Done.

**Comment by wjakob** [comment]
Sorry, no-go:  this  change broke the continuous integration, so I've had to roll it back. Please create a PR on your own with a proposed fix.

**Comment by chaekwan** [comment]
Great!

Thanks,
Chaekwan

**Comment by chaekwan** [comment]
Hi Wenzel,

Thanks for clarification!
I understand the situation.
Let me keep it as my local fix to workaround the tool.

Regards,
Chaekwan

**Comment by YannickJadoul** [comment]
> Let me keep it as my local fix to workaround the tool.

I'm assuming this means this can be closed?
