### ISSUE TITLE
 No rule to make target 'check'.  Stop.

### ISSUE THREAD

**Issue by dickreuter** [pybind/pybind11#2014]
I've followed the instructions to compbile pybind11 on windows but I get the below error:

C:\Users\dickr\git\pybind11\build>cmake --build . --config Release --target check
make: *** No rule to make target 'check'.  Stop.

**Comment by YannickJadoul** [comment]
We need more information than this. What did you run before, how does your environment look (you're on Windows, but working with make?), ...

Same as #2015: reopen if necessary.
