### ISSUE TITLE
Running the tests requires pytest

### ISSUE THREAD

**Issue by dickreuter** [pybind/pybind11#2015]
I'm getting the below error even though pytest has been installed
```

PS C:\Users\dickr\git\pybind11\build> cmake ..
-- Building tests WITHOUT Eigen
-- Boost version: 1.66.0
CMake Error at tests/CMakeLists.txt:217 (message):
  Running the tests requires pytest.  Please install it manually (try:
  /usr/bin/python3.6 -m pip install pytest)
```

**Comment by YannickJadoul** [comment]
We need more information than this. What Python version is detected by CMake? Judging by the output, it has already run before, so some things are cached? Did you try removing everything from this `build` folder and running `cmake` again?

I'm assuming you might have found a workaround, after 6 months, so I'm closing this for now. If this is still an issue, please reopen!
