### ISSUE TITLE
default arguments / function overloads

### ISSUE THREAD

**Issue by rhaschke** [pybind/pybind11#2029]
In pybind11 one can specify default function arguments in the wrapper definition
([tutorial](https://pybind11.readthedocs.io/en/stable/basics.html#default-arguments)) - independent of the corresponding defaults of the C++ function. On the one hand, this is a nice feature, on the other hand, this requires code duplication and thus makes it more difficult to maintain consistency on changes.
Is there also a mechanism available to define function overloads based on C++ defaults - like in boost::python?

**Comment by rhaschke** [comment]
For class constructors I found an answer [here](https://github.com/pybind/pybind11/issues/957#issuecomment-418488219):
Just specify your optional arguments via `py::optional` like this:
```c++
py::class_<Foo>(m, "Foo")
  .def(py::init<float, py::optional<int, double>>());
```
which makes the first `float` argument required, while `int` and `double` are optional.

**Comment by bstaletic** [comment]
We have no idea how boost achieves this. Mind helping us figure this out? I guess the key is in [this macro](https://github.com/boostorg/python/blob/ac62db1cf17c0af44dc2b2117f9ddeee327e5e7c/include/boost/python/detail/defaults_gen.hpp#L367).

**Comment by YannickJadoul** [comment]
This seems to still duplicate the default arguments between the C/C++ definition and the header, though?
https://www.boost.org/doc/libs/1_73_0/libs/python/doc/html/tutorial/tutorial/functions.html#tutorial.functions.default_arguments

I'm closing as we're cleaning up issues, but please reopen if we got this wrong or overlooked something! I agree it would be cool if we could do this, but until we have reflection (C++23?), I don't see how we could achieve this.

**Comment by YannickJadoul** [comment]
Whoops, sorry. @bstaletic just made me realize I am indeed wrong.

The disadvantage is that the generated docstrings won't contain the default arguments, but the actual values are not repeated, indeed.
So I suppose it is possible, even without (too many) dirty macros, but I'm not sure whether we should?

**Comment by rhaschke** [comment]
Meanwhile, I adapted to the pybind11 syntax and I like it very much, because - as you said - it adds to the doc strings and it allows to define other defaults as in C++. Boost's overload macros were kind of clumsy to use as well.

**Comment by YannickJadoul** [comment]
@rhaschke OK, great :-) Do you still wish to pursue this further (I think it should be possible to do something with templates to achieve the same thing as boost), or can we close this?

**Comment by rhaschke** [comment]
I cannot put effort into this and it's not that important for me. So, I'm fine to close this. Thanks for asking.
