### ISSUE TITLE
pybind11::error_already_set at memory location   (Exception)

### ISSUE THREAD

**Issue by zirid** [pybind/pybind11#2041]
Make sure you've completed the following steps before submitting your issue -- thank you!

1. Check if your question has already been answered in the [FAQ](http://pybind11.readthedocs.io/en/latest/faq.html) section.
2. Make sure you've read the [documentation](http://pybind11.readthedocs.io/en/latest/). Your issue may be addressed there.
3. If those resources didn't help and you only have a short question (not a bug report), consider asking in the [Gitter chat room](https://gitter.im/pybind/Lobby).
4. If you have a genuine bug report or a more complex question which is not answered in the previous items (or not suitable for chat), please fill in the details below.
5. Include a self-contained and minimal piece of code that reproduces the problem. If that's not possible, try to make the description as clear as possible.

*After reading, remove this checklist and the template text in parentheses below.*

## Issue description

I am trying to Call a python function from C++   VS 2017 but I am getting an exception .
![Capture](https://user-images.githubusercontent.com/31682698/71505701-85fd7180-28c1-11ea-9c44-acd75863af46.JPG)

 ( I used Cmake to compile pybind11 in VS2017 . I included the headers but  I had to link python  separately)
![Capture2](https://user-images.githubusercontent.com/31682698/71506380-07560380-28c4-11ea-9506-e76949d1f4c6.JPG)

(Provide a short description, state the expected behavior and what actually happens.)

## Reproducible example code 
Python function :
`
from scipy.optimize import minimize, rosen, rosen_der
 def min_rosen(x0):
        res = minimize(rosen, x0)
        return res`

I used pyInstaller to create  .exe file `pyinstaller --onefile     min_rosen.py`

C++ call : 

	`py::scoped_interpreter guard{}; 
	py::function min_rosen =
	py::reinterpret_borrow<py::function>(py::module::import("min_rosen.exe").attr("min_rosen");`

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete C++ and Python snippets that can be easily compiled and run to diagnose the issue.)

**Comment by YannickJadoul** [comment]
Why are you calling `py::reinterpret_borrow` instead of just `py::cast<py::function>(...)` or `py::function(...)` ?

**Comment by bstaletic** [comment]
No answer, closing. @zirid If there are any more questions, feel free to come to gitter.
