### ISSUE TITLE
matplotlib.pyplot interference with std::stod

### ISSUE THREAD

**Issue by stefoss23** [pybind/pybind11#2042]
## Issue description
This is an issue with Python 3.6, and not with Python 2. 
Issue: when matplotlib pyplot is imported, it changes the behaviour any Python functions created by pybind11 that uses std::stod. Please view c++ code below. The code produces a Python module named 'example'. It as one function: 'convert_str' that takes a string argument and converts it to a double. This works fine, unless matplotlib.pyplot is imported. Here is a printout from the terminal:

Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
>>> example.convert_str("2.2")
2.2
>>> example.convert_str("3.9")
3.9
>>> import matplotlib.pyplot
>>> example.convert_str("2.2")
2.0
>>> example.convert_str("3.9")
3.0
>>> exit()

## Reproducible example code
This is the cpp code for creating a module named example:
```c++
#include <pybind11/pybind11.h>
#include <string>

namespace py = pybind11;

double convert_str(const std::string& value_str) {
    return std::stod(value_str);
}

PYBIND11_MODULE(example, m) {
    m.def("convert_str", &convert_str);
}
```
A more comprehensive detail of the c++ can be see at: https://github.com/stefoss23/matplotlib_pyplot_pybind_problem.

**Comment by wjakob** [comment]
Shouldn't this be a matplotlib issue then? It sounds like it makes some changes to the C locale.

**Comment by stefoss23** [comment]
Thank for the reply! 
It might be a matplotlib issue. I am not sure. I am currently trying to reproduce this without pybind11.

**Comment by stefoss23** [comment]
This is a decimal point/comma problem. When using matplotlib.pyplot, the conversion functionality of std::stod reverts to the nationality setting. It is a bad feature, but possible to override.
