### ISSUE TITLE
Question about argument order for PYBIND11_OVERLOAD_NAME

### ISSUE THREAD

**Issue by jonchammer** [pybind/pybind11#2051]
## Issue description

There seems to be a discrepancy in the documentation with regards to the `PYBIND11_OVERLOAD_NAME` macro. In this [this](https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python) section, the documentation says:

> There are also two alternate macros PYBIND11_OVERLOAD_PURE_NAME and PYBIND11_OVERLOAD_NAME which take a string-valued name argument between the Parent class and Name of the function slots, which defines the name of function in Python.

However, the reference for that macro (and indeed the actual source code) implies that the C name comes before the Python name (rather than the other way around).

Based on my own testing, it seems like the quoted advice is correct and that the python name should come first, but I'd like to verify to clean up any potential confusion. This is a basic example, where the function `bar()` in C++ would be mapped to the function `python_bar()` in Python:

## Example
```C++
struct Foo
{
    virtual void bar() {}
};

// Trampoline class for Foo
struct PyFoo : public Foo
{
    void bar() override
    {
        // Compiles
        PYBIND11_OVERLOAD_NAME(
            void, Foo, "python_bar", bar,
        );

        // Does not compile
        // PYBIND11_OVERLOAD_NAME(
        //     void, Foo, bar, "python_bar",
        // );
    }
};

// ...
py::class_<Foo, PyFoo>(m, "Foo")
        .def(py::init<>())
        .def("python_bar", &Foo::bar);
```

Thanks for all the work that goes into this project! It's appreciated.

**Comment by methylDragon** [comment]
I know this is a bit late, but I had the same issue.

You are absolutely correct! I've sent a relevant PR here: https://github.com/pybind/pybind11/pull/2254

**Comment by YannickJadoul** [comment]
Resolve by that PR, then! Thanks for reporting, @jonchammer, and for fixing, @methylDragon!
