### ISSUE TITLE
How to embedding Python in C++ with PyBind and make instead of CMake?

### ISSUE THREAD

**Issue by cuinjune** [pybind/pybind11#2054]
I am trying to embed some Python code in C++ with PyBind. Most of documentation is on extending Python with C++, but I am interested in embedding:

On http://pybind11.readthedocs.io/en/stable/advanced/embedding.html there is a simple example with cmake. However for my project I have to extend a makefile.

Is it possible to change this example

    cmake_minimum_required(VERSION 3.0)
    project(example)
    
    find_package(pybind11 REQUIRED)  # or `add_subdirectory(pybind11)`
    
    add_executable(example main.cpp)
    target_link_libraries(example PRIVATE pybind11::embed)

with this c++ file

    #include <pybind11/embed.h> // everything needed for embedding
    namespace py = pybind11;
    
    int main() {
        py::scoped_interpreter guard{}; // start the interpreter and keep it alive
    
        py::print("Hello, World!"); // use the Python API
    }

to a version with a makefile?

**Comment by YannickJadoul** [comment]
Sure, have a look at https://docs.python.org/3/extending/embedding.html, which shows you the more low-level things that need to happen (such as linking to `libpythonX.Y`, etc).

Alternatively, run a CMake build with environment variable `VERBOSE=1` set. CMake ought to print the actual compilation and linking commands it's running, and you can distill those into a makefile.

Hope that works for you? If not, do reopen the issue. And if you get it working and think it should be in the documentation, feel free to submit a PR! :-)
