### ISSUE TITLE
enhance numpy capabilities?

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#208]
New to pybind11, I've used ndarray
https://github.com/ndarray/ndarray
for a long time.

I'm excited that pybind11 has numpy capability.  Unfortunately, support for operations in c++ on these objects seems very limited.  At the least, it would be good to support indexing operations such as slicing.  A convenient way to do arithmetic would be useful.

**Comment by wjakob** [comment]
My resources here are very limited to respond to feature requests -- I'll close this since it is not a defect of the software. PRs to implement better NumPy support (especially compact ones!) are welcomed.
