### ISSUE TITLE
Named arguments in callback from C++ to python

### ISSUE THREAD

**Issue by shooshx** [pybind/pybind11#2084]
I have a C++ function I'm defining like this:

void the_func(const std::string& arg1, const std::function<void(const std::string& cbarg1, const std::string& cbarg2)>& callback_result)
m.def("the_func", &the_func, R"doc" , py::arg("arg1"), py::arg("callback_result"));

python is calling the_func() into C++ and then C++ is calling callback_result() into python.
Now when the callback arrives in python, I'd like it to be called with kwargs rather than positional args, or atleast have a way to know the name of the argument via inspect.
Is that possible?

**Comment by YannickJadoul** [comment]
C++ doesn't really have the concept of keyword-arguments, so you're not going to be able to do that with `std::function`.

There's a bunch of interesting stuff you can do if you accept a `py::function', though. See https://github.com/pybind/pybind11/blob/f980d76d38dda8e9ce78e68e27b4c2026681bf51/tests/test_callbacks.cpp#L30-L58
