### ISSUE TITLE
Create Bindings For Maps

### ISSUE THREAD

**Issue by leimao** [pybind/pybind11#2086]
## Issue description

How to create Python bindings for C++ methods which take an instance of `std::unordered_map<std::string, T>` as input. `T` is some custom C++ data structure, `std::pair`, `std::vector`, or `void *`. I could hardly find examples of these cases.

**Comment by carlsonmark** [comment]
I use the std::map bindings, but I have never used `std::unordered_map`. Unless I am not understanding what you are asking, you only have to `#include <pybind/stl.h>` and bindings for `std::unordered_map` should work for the examples you have listed above (except maybe `void *`?)

Check out the unit tests for advanced usage of `std::unordered_map` bindings:
https://github.com/pybind/pybind11/blob/master/tests/test_stl.cpp

**Comment by bstaletic** [comment]
`void*` will be converted to `py::capsule`. Alternative to `stl.h` is `stl_bind.h` and `py::bind_map`.
