### ISSUE TITLE
Segfault related to __init__() when overriding virtual C++ functions

### ISSUE THREAD

**Issue by ryan-maus** [pybind/pybind11#209]
Following the example code here: http://pybind11.readthedocs.io/en/latest/advanced.html#overriding-virtual-functions-in-python

I am getting a segmentation fault when adding an __init__(...) function to a Python class inheriting from a 'trampoline' C++ class.  Am I simply missing some part of the binding, or is this potentially a bug?

Thanks,
REM

**example.cpp:**
```c++
#include <pybind11/pybind11.h>
#include <string>

class ExampleListener {
public:
    virtual ~ExampleListener() {}
    virtual void OnEvent(std::string const& s) = 0;
};

class PyExampleListener : public ExampleListener {
    using ExampleListener::ExampleListener;

    virtual void OnEvent(std::string const& s) {
        PYBIND11_OVERLOAD_PURE(void, ExampleListener, OnEvent, s);
    }
};

void call_listener(ExampleListener * listener) {
    listener->OnEvent("TestString");
}

namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

    py::class_<PyExampleListener>(m, "ExampleListener")
        .alias<ExampleListener>()
        .def(py::init<>())
        .def("OnEvent", &ExampleListener::OnEvent);

    m.def("call_listener", &call_listener);

    return m.ptr();
}
```
**example.py**
```python
from example import *

# Works as expected:
class Test(ExampleListener):
    def OnEvent(self, s):
        print s


t = Test()
call_listener(t)

# Segmentation fault:
class TestWithInit(ExampleListener):
    def __init__(self, a, b, c):
        self.a = a;
        self.b = b;
        self.c = c;

    def OnEvent(self, s):
        print s, self.a, self.b, self.c

twi = TestWithInit(1, 2, 3)
call_listener(twi
```

**Compile & Link:**
```bash
c++ -O3 -fPIC -shared -std=c++11 -I ./include `python-config --cflags --ldflags --libs` example.cpp -o example.s
```

**Output**
```bash
$ python example.py
TestString
[2]    25735 segmentation fault (core dumped)  python example.p
```

**Comment by wjakob** [comment]
You need to call the constructor in your ExampleListener __init__ function.

**Comment by wjakob** [comment]
I'll close this for now -- feel free to reopen/comment if this did not address your issue.

**Comment by ryan-maus** [comment]
Yes, I believe I got it sorted out. Thanks!

**Comment by AJ92** [comment]
Basically i think i have the exact same problem, would be nice one of oyu guys could provide specific code to solve this. I am not that good in python yet... last time i used it was 5 years ago :(

Would be super cool if you could tell me how to call the constructor of the parent class in python.
(already banging my head around this topic for 2 days...)

thx in advance

**Comment by jagerman** [comment]
> Would be super cool if you could tell me how to call the constructor of the parent class in python.

```Python
class DerivedClass(BaseClass):
    def __init__(self):
        BaseClass.__init__(self)
```

You can, of course, take extra arguments in `__init__` and pass them on as needed to the BaseClass constructor.

**Comment by AJ92** [comment]
THX, awesome it works now :)
the self was missing in the __init__
