### ISSUE TITLE
pickling of inner classes fails

### ISSUE THREAD

**Issue by jkhoogland** [pybind/pybind11#210]
Hi 

I have an example of a type with an inner type,
for which I tried to add pickling code. 

The failing code is attached: [innerclasspickle.zip](https://github.com/pybind/pybind11/files/277842/innerclasspickle.zip).
It is example15 with an inner class `Inner` added to `Pickeable`.

On running it fails with what seems to be an incorrect lookup:

```
$  /usr/bin/python2.7 example15.py
test_value 15 48
test_value 15 48
12
Traceback (most recent call last):
  File "example15.py", line 27, in <module>
    data1 = pickle.dumps(i,2)
cPickle.PicklingError: Can't pickle <class 'example.Inner'>: attribute lookup example.Inner failed
```

This should read example.Pickleable.Inner I would expect.

I tried to find the relevant code to fix in pybind11 but couldn't find the right spot.
So if you can point me to it, I can have a look at a possible fix.

This is run on OSX Yosemite 10.10.5 using pybind11 release 1.7

**Comment by wjakob** [comment]
To pickle nested classes, pickle has to be made aware of __qualname__. This only happens for newer pickle protocols -- try replacing 2 by -1 in the example you sent.

**Comment by jkhoogland** [comment]
Switching to -1 doesn't fix the issue.

```
$  /usr/bin/python2.7 --version
Python 2.7.10
$  /usr/bin/python2.7 example15.py
test_value 15 48
test_value 15 48
12
Traceback (most recent call last):
  File "example15.py", line 27, in <module>
    data1 = pickle.dumps(i,-1)
cPickle.PicklingError: Can't pickle <class 'example.Inner'>: attribute lookup example.Inner failed
```

**Comment by wjakob** [comment]
You need to make the change in two places -- also, where the pickle is created

**Comment by jkhoogland** [comment]
I'm probably missing something,
but the line where it fails it the first call to serialize/pickle the instance.

**Comment by wjakob** [comment]
Aha, sorry -- I didn't see all of the information in your previous post. You are still using Python 2.7.

Pickling of inner classes is actually something that cannot be done (even within Python) on version 2.7. The __qualname__ attribute was specifically added in Python 3 to address these sorts of issues. It works with pickle protocol -1 on Python 3.x

**Comment by jkhoogland** [comment]
got it, thanks for the clarification
