### ISSUE TITLE
Error returning vector of complex numbers

### ISSUE THREAD

**Issue by SanPen** [pybind/pybind11#2108]
Hi, 

I am writing a library and wrapping it with pybind11.

In simple terms, I have a class like this:

```
// declare a vector of complex numbers
typedef Eigen::Matrix<std::complex<double>, Eigen::Dynamic, 1> CxVec;

class NumericalCircuitSnapshot{

public:
Circuit *circuit;  // this is another object of my library

CxVec Sbus;

NumericalCircuitSnapshot(Circuit &circuit_) {
    circuit = &circuit_;
}


const CxVec get_Sbus(){return Sbus;}
};
```
And I wrap it like this:

```
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/complex.h>
#include <pybind11/functional.h>
#include <pybind11/chrono.h>
py::class_<gridcal::NumericalCircuitSnapshot>(m, "NumericalCircuitSnapshot")
            .def(py::init<gridcal::Circuit&>(),  py::arg("circuit"))
            .def("get_Sbus", &gridcal::NumericalCircuitSnapshot::get_Sbus, py::return_value_policy::reference_internal)
            ;

```
This is not the whole code, but I believe it is enough to illustrate the conflicting part.

When I call the `get_Sbus` function from Python I get this message:

> TypeError: Unable to convert function return value to a Python type! The signature was
> 	(self: GridCalNative.NumericalCircuitSnapshot) -> Eigen::Matrix<std::complex<double>, -1, 1, 0, -1, 1>
> 
> Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
> <pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
> conversions are optional and require extra headers to be included
> when compiling your pybind11 module.

My aim is to pass a vector of complex numbers from C++ to Python by <read-only> reference.

**Comment by carlsonmark** [comment]
I don't use Eigen, but I do recall seeing this in the documentation:

> To enable the built-in Eigen support you must include the optional header file pybind11/eigen.h.

Did you try adding `#include <pybind11/eigen.h>`?

**Comment by SanPen** [comment]
Silly me, I didn't include it! 
After including `eigen.h` I don't get the reported error anymore. But I get some other error:

```
Error evaluating: thread_id: pid_14048_id_139667920178760
frame_id: 139667393820648
scope: FRAME
attrs: __py_debug_temp_var_1355622253
Traceback (most recent call last):
  File "/home/santi/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/193.5662.61/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 285, in resolve_compound_variable_fields
    return _typeName, resolver.get_dictionary(VariableWithOffset(var, offset) if offset else var)
  File "/home/santi/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/193.5662.61/plugins/python-ce/helpers/pydev/pydevd_plugins/extensions/types/pydevd_plugin_numpy_types.py", line 91, in get_dictionary
    ret['min'] = obj.min()
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by carlsonmark** [comment]
From the snipped you have above, that is probably correct, since `Sbus` does not have anything in it.

**Comment by YannickJadoul** [comment]
> `ValueError: zero-size array to reduction operation minimum which has no identity`

That's a numpy error, unrelated to pybind11:

```
>>> import numpy as np
>>> np.array([]).min()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yannick/.local/lib/python3.6/site-packages/numpy/core/_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```

As @carlsonmark said, your returned array is empty so you can't take the minimum. (Thanks, @carlsonmark!)
