### ISSUE TITLE
Missing symbols after linking on Linux

### ISSUE THREAD

**Issue by coreyjadams** [pybind/pybind11#2113]
I could not find a good answer for this in the FAQ.  I don't have enough knowledge of linkers and CMake to solve it myself, so I hope to get some help here.

## Issue description

I have a software library (https://github.com/DeepLearnPhysics/larcv3/tree/pybind11) that is essentially an IO library for sparse data, written in C++, which is exposed to python.  Originally it was exposed with Swig which worked ok, but wasn't perfect - and took forever to compile.  I want more control over the bindings and want to have better interface to numpy, so I am trying with pybind11.  The interface is very nice compared to swig, and it's one less dependency.

The library has a numpy of classes that I want exposed into the same python library, `larcv`.  The build system is with CMake, which works great for the C++ side as well as pulling together all of the needed tools like HDF5, MPI, OpenMP, and swig/pybind11.  I am using pybind11 as a submodule.

Each class in a `.cxx` file has it's pybind11 code in the same file, and each folder in the project (for example, `base` or `dataformat`) has a header and cxx file for pybind11.  One master file, `larcv.cxx`, is used as the source file for pybind11.  It looks like this:

```
#include "larcv3/core/base/base.h"
#include "larcv3/core/dataformat/dataformat.h"
#include "larcv3/core/processor/processor.h"
#include "larcv3/app/queueio/queueio.h"

PYBIND11_MODULE(pylarcv, m) {
  init_base(m);
  init_dataformat(m);
  init_processor(m);
  init_queueio(m);
}
```

Each of these functions, `init_base(pybind11::module m)` is defined in the header file `base.h`  The implementation is in `base.cxx`.

Here is where things go awry, I think.  Every .cxx file except `larcv.cxx` is compile as an object file, and then linked into a shared library `liblarcv.so`.  The pybind11 module `pylarcv` is instead built with CMake like this:

```

if(CMAKE_PYTHON_BINDINGS)
    pybind11_add_module(pylarcv SHARED larcv.cxx)

    # Add a shared library
    set_target_properties(pylarcv PROPERTIES SKIP_BUILD_RPATH FALSE)

    # If building with setuptools, CMake will not be performing the install
    set_target_properties(pylarcv PROPERTIES BUILD_WITH_INSTALL_RPATH TRUE)

    target_link_libraries(pylarcv PRIVATE larcv3)

    if(UNIX AND NOT APPLE)
        set_target_properties(pylarcv PROPERTIES INSTALL_RPATH "$ORIGIN/lib/")
    elseif(APPLE)
        set_target_properties(pylarcv PROPERTIES INSTALL_RPATH "@loader_path/lib/")
    endif()

    set_target_properties(pylarcv PROPERTIES INSTALL_RPATH_USE_LINK_PATH TRUE)

endif(CMAKE_PYTHON_BINDINGS)
```

This library pylarcv links properly to liblarcv.so on mac (and all tests pass), but it doesn't work on linux.  

It is hard to make a very simple example of this full library, so I stripped it down to one C++ class, no HDF5/numpy/MPI/OpenMP, and created a simple example repo:

https://github.com/coreyjadams/larcv3-pybind11-example/tree/master

On mac osx, the example repo works.  On linux, it fails when trying to import the module `pylarcv` with the following error:
```
ImportError: /home/cadams/.local/lib/python3.7/site-packages/pybind11_test_symbols-1.0.0-py3.7-linux-x86_64.egg/larcv/pylarcv.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z9init_baseN8pybind116moduleE
```

When I look at the linking of the pylarcv library, it indicates it linked successfully to the main shared library for the project:
```bash
ldd /home/cadams/.local/lib/python3.7/site-packages/pybind11_test_symbols-1.0.0-py3.7-linux-x86_64.egg/larcv/pylarcv.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffc3b9d8000)
	liblarcv3.so => /home/cadams/.local/lib/python3.7/site-packages/pybind11_test_symbols-1.0.0-py3.7-linux-x86_64.egg/larcv/lib/liblarcv3.so (0x00007f4e229c2000)
	libpython3.7m.so.1.0 => /lus/theta-fs0/projects/datascience/cadams/software/cooley/miniconda/lib/libpython3.7m.so.1.0 (0x00007f4e2265b000)
	libstdc++.so.6 => /soft/compilers/gcc/8.2.0/lib64/libstdc++.so.6 (0x00007f4e222d7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4e21fd5000)
	libgcc_s.so.1 => /soft/compilers/gcc/8.2.0/lib64/libgcc_s.so.1 (0x00007f4e21dbd000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4e219ef000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4e217eb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4e230e0000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4e215cf000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f4e213cc000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f4e211c4000)
```

Further, I see that the symbols it is looking for are defined in the main shared library:
```
nm /home/cadams/.local/lib/python3.7/site-packages/pybind11_test_symbols-1.0.0-py3.7-linux-x86_64.egg/larcv/lib/liblarcv3.so | grep init_base
00000000000052d0 t _Z9init_baseN8pybind116moduleE
0000000000005060 t _Z9init_baseN8pybind116moduleE.cold.0
```

I see slightly different results on mac:
```
 nm /Users/corey.adams/Library/Python/3.6/lib/python/site-packages/pybind11_test_symbols-1.0.0-py3.6-macosx-10.9-x86_64.egg/larcv/lib/liblarcv3.dylib  | grep init_base
00000000000022c0 T __Z9init_baseN8pybind116moduleE
```

My issue, then, is why can pybind11 generate a file that succeeds on mac, but fails to find the symbols in the successfully linked library on linux?

**Comment by aostruszka** [comment]
Corey

Have you managed to figure out how to link with pybind11?  I'm asking since I'm new to pybind11 and it seems that I've hit very similar issue (missing symbols from lib when importing module).

With regards
Andrzej

**Comment by jcberthon** [comment]
Did you found a solution?

**Comment by coreyjadams** [comment]
Yes, it works now.  

Are you asking for the solution?  I don't remember off the top of my head ... it has been 6 months.

**Comment by YannickJadoul** [comment]
> Yes, it works now.

**Comment by jcberthon** [comment]
> 
> 
> Yes, it works now.
> 
> Are you asking for the solution? I don't remember off the top of my head ... it has been 6 months.

Yes if you still can remember the solution, even vaguely, I would be interested :-)

**Comment by YannickJadoul** [comment]
@jcberthon You can come to [Gitter](https://gitter.im/pybind/Lobby) if you want to show and explain your specific use case and problem. There will be some people there happy to help :-)

**Comment by coreyjadams** [comment]
@jcberthon I agree, I don't have an answer to what the fix was.  You can look here:

https://github.com/DeepLearnPhysics/larcv3

For a repo that works, but I didn't have the time to really get in to chasing my own git history.  I'm sorry.
