### ISSUE TITLE
overload_cast for virtual function

### ISSUE THREAD

**Issue by Kevin-Lee921** [pybind/pybind11#2118]
I want to expose two virtual functions with the same function name to Python. I tried to use py::overload_cast and it failed. I am using VS 2019 with C++ standard set to (std:c++latest). The example codes are listed below. 
P.s. The example also failed with std:c++ 14 and 17.

```
#include <boost/date_time/gregorian/gregorian.hpp>
class ICreditCurve {
 public:
  virtual ~ICreditCurve() = default;

  virtual double GetSurvivalProbability(
      const boost::gregorian::date& query_date) const = 0;
  virtual double GetSurvivalProbability(double query_time) const = 0;
};
```

```
#include <ICreditCurve.h>
#include <pybind11/pybind11.h>

namespace py = pybind11;

PYBIND11_MODULE(example, m) {
  py::class_<ICreditCurve>(m, "ICreditCurve")
  .def("GetSurvivalProbability",py::overload_cast<double>(&ICreditCurve::GetSurvivalProbability));
}
```

**Comment by bstaletic** [comment]
What are you exactly trying to achieve here? You ca neither instantiate `ICreditCurve` nor call `GetSurvivalProbability()`.

**Comment by YannickJadoul** [comment]
No answer, two weeks later. I'm closing this for now.

Please reopen if necessary, and tell us which error you get and what you want to do.
