### ISSUE TITLE
Build module with different compilation flags

### ISSUE THREAD

**Issue by MonkeyBreaker** [pybind/pybind11#2131]
## Issue description

I have a project which defines types depending on compilation defines.
We would like to have only one `bindings.cpp` file with only one module.

Then with cmake, we'll generate 2 different modules with the same code, but with different compilation flags.

The current problem I'm encountering which is an expected behaviour is `ImportError: dynamic module does not define module export function `, because in `bindings.cpp` my module is name `example_module` and in order to generate 2 different modules in cmake, I need to provide 2 different names to the modules, which produce the previous error.

One fix I can think about is to copy/paste `example_module`, and rename copied module to `example_module_different_compilation_flags`, and then it will work as expected. But I would like to know if there's a better solution for this case.

## Reproducible example code

`bindings.cpp`
```cpp
// PYBIND11
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

PYBIND11_MODULE(example_module, m) {
    /* Unbelievable smart code */
}
```

`CmakeLists.txt`
```cmake
pybind11_add_module(example_module "bindings.cpp") # module generated works fine
target_compile_definitions(example_module PRIVATE USE_SET_1)

pybind11_add_module(example_module_different_compilation_flags "bindings.cpp") # Error describe earlier happens when importing module
target_compile_definitions(example_module_different_compilation_flags PRIVATE USE_SET_2)
```

### Possible solution

`bindings.cpp`
```cpp
// PYBIND11
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

PYBIND11_MODULE(example_module, m) {
    /* Unbelievable smart code */
}

PYBIND11_MODULE(example_module_different_compilation_flags, m) {
    /* Unbelievable smart code, but exactly the same as in example_module */
}
```

`CmakeLists.txt`
```cmake
pybind11_add_module(example_module "bindings.cpp") # module generated works fine
target_compile_definitions(example_module PRIVATE USE_SET_1)

pybind11_add_module(example_module_different_compilation_flags "bindings.cpp") # Error describe earlier happens when importing module
target_compile_definitions(example_module_different_compilation_flags PRIVATE USE_SET_2)
```

Thank you for your help

**Comment by bstaletic** [comment]
Make the module name a macro.

```c++
#ifdef MODULE_A
#define MODULE_NAME A
#else 
#define MODULE_NAME B
#endif 

PYBIND11_MODULE(MODULE_NAME, m) {}
```

With simple questions like this one, it's better to ask for help on [gitter](https://gitter.im/pybind/Lobby).
