### ISSUE TITLE
py::format_descriptor does not work for enum types

### ISSUE THREAD

**Issue by lahwaacz** [pybind/pybind11#2135]
## Issue description

According to this code it seems like `py::format_descriptor` should work for enum types, but it does not.

https://github.com/pybind/pybind11/blob/a60648223d409c51804be63a097eeaae383e8a7c/include/pybind11/numpy.h#L948-L968
 
## Reproducible example code

```cpp
#include <pybind11/pybind11.h>
namespace py = pybind11;

enum MyEnum { foo, bar };

int main()
{
    const std::string desc = py::format_descriptor<MyEnum>::format();
}
```

Compiler output (GCC 9.2.1):
```
$ g++ -std=c++14 pybind11_test.cpp -I ~/.local/include/ -I /usr/include/python3.8/
pybind11_test.cpp: In function ‘int main()’:
pybind11_test.cpp:8:61: error: ‘format’ is not a member of ‘pybind11::format_descriptor<MyEnum>’
    8 |     const std::string desc = py::format_descriptor<MyEnum>::format();
      |                                                             ^~~
```

**Comment by YannickJadoul** [comment]
Wow, this has had me fooled for at least 15 minutes.

Your problem is that you are not including `numpy.h`, i.e., the header where these specializations are added. The  non-specialized template declaration is in `common.h` (since it's also used in other header files of pybind11).

**Comment by lahwaacz** [comment]
Wow indeed... :angel:  Thanks for looking into it.
