### ISSUE TITLE
Expose C-Style Array Member of a structure

### ISSUE THREAD

**Issue by lanphon** [pybind/pybind11#2149]
For historical reason, I have to use a C-style array inner the class(structure) designed. And Now I'm trying to expose it to python environment with the help of pybind11. Since it's a C-style array, the stl.h would be of no help. i also found the buffer protocol samples, but it seems to define the whole calss as a buffer object, instead of a member one. So I wonder if there is elegant way to achieve the target, to expose the C-style array, with the python read/write the array(python do not need to reshape the array in any case).

For example, 

```cpp
struct a_t
{
    int b[10];
};
```

and I'd like to manipulate it like this:

```python
obj = a_t()
obj.b[0] = 10
obj.b[9] = 7
print(obj.b)
```

I've found a sample to return a `pybind11::array_t` object. To retrieve the array, it must invoke the `()` operation to get a `numpy` object, before using `[]`.

what's the elegant way to achieve this???

**Comment by carlsonmark** [comment]
Does this look like it might work?
From: https://github.com/pybind/pybind11/blob/master/tests/test_numpy_array.cpp
```
    // test_numpy_view
    struct ArrayClass {
        int data[2] = { 1, 2 };
        ArrayClass() { py::print("ArrayClass()"); }
        ~ArrayClass() { py::print("~ArrayClass()"); }
    };
    py::class_<ArrayClass>(sm, "ArrayClass")
        .def(py::init<>())
        .def("numpy_view", [](py::object &obj) {
            py::print("ArrayClass::numpy_view()");
            ArrayClass &a = obj.cast<ArrayClass&>();
            return py::array_t<int>({2}, {4}, a.data, obj);
        }
    );
```

Usage example here: https://github.com/pybind/pybind11/blob/master/tests/test_numpy_array.py
```
def test_numpy_view(capture):
    with capture:
        ac = m.ArrayClass()
        ac_view_1 = ac.numpy_view()
        ac_view_2 = ac.numpy_view()
        assert np.all(ac_view_1 == np.array([1, 2], dtype=np.int32))
        del ac
        pytest.gc_collect()
    assert capture == """
        ArrayClass()
        ArrayClass::numpy_view()
        ArrayClass::numpy_view()
    """
    ac_view_1[0] = 4
    ac_view_1[1] = 3
    assert ac_view_2[0] == 4
    assert ac_view_2[1] == 3
    with capture:
        del ac_view_1
        del ac_view_2
        pytest.gc_collect()
        pytest.gc_collect()
    assert capture == """
        ~ArrayClass()
    """
```

**Comment by lanphon** [comment]
> Does this look like it might work?
> From: https://github.com/pybind/pybind11/blob/master/tests/test_numpy_array.cpp
> 
> ```
>     // test_numpy_view
>     struct ArrayClass {
>         int data[2] = { 1, 2 };
>         ArrayClass() { py::print("ArrayClass()"); }
>         ~ArrayClass() { py::print("~ArrayClass()"); }
>     };
>     py::class_<ArrayClass>(sm, "ArrayClass")
>         .def(py::init<>())
>         .def("numpy_view", [](py::object &obj) {
>             py::print("ArrayClass::numpy_view()");
>             ArrayClass &a = obj.cast<ArrayClass&>();
>             return py::array_t<int>({2}, {4}, a.data, obj);
>         }
>     );
> ```
> 
> Usage example here: https://github.com/pybind/pybind11/blob/master/tests/test_numpy_array.py
> 
> ```
> def test_numpy_view(capture):
>     with capture:
>         ac = m.ArrayClass()
>         ac_view_1 = ac.numpy_view()
>         ac_view_2 = ac.numpy_view()
>         assert np.all(ac_view_1 == np.array([1, 2], dtype=np.int32))
>         del ac
>         pytest.gc_collect()
>     assert capture == """
>         ArrayClass()
>         ArrayClass::numpy_view()
>         ArrayClass::numpy_view()
>     """
>     ac_view_1[0] = 4
>     ac_view_1[1] = 3
>     assert ac_view_2[0] == 4
>     assert ac_view_2[1] == 3
>     with capture:
>         del ac_view_1
>         del ac_view_2
>         pytest.gc_collect()
>         pytest.gc_collect()
>     assert capture == """
>         ~ArrayClass()
>     """
> ```

This is the way i've found. The related python code here should be:
```python
obj = a_t()
obj.b()[0] = 0
obj.b()[1] = 9
```
Seems not intuitive. Thank you for you reply. If there is no other way, I may use this one.

**Comment by lanphon** [comment]
this code finally work:

```cpp
py::class_<a_t>(m, "a_t")
.def(py_init<>())
.def_property_readonly("b", [](py::object& obj) {
a_t& o = obj.cast<a_t>();
return py::array{10, o.b, obj}; 
}
)
;
```

By define a property and provide a getter function, now the python could use the `a_t.b` just as an array.

Many thanks.

**Comment by jnulzl** [comment]
> this code finally work:
> 
> ```c++
> py::class_<a_t>(m, "a_t")
> .def(py_init<>())
> .def_property_readonly("b", [](py::object& obj) {
> a_t& o = obj.cast<a_t>();
> return py::array{10, o.b, obj}; 
> }
> )
> ;
> ```
> 
> By define a property and provide a getter function, now the python could use the `a_t.b` just as an array.
> 
> Many thanks.

In lastest version, your examples should be:

```c++
struct a_t
{
    int b[10];
};

py::class_<a_t>(m, "a_t")
        .def(py::init())
        .def_property_readonly("b", [](py::object& obj) {
               a_t& o = obj.cast<a_t&>(); # must be**cast<a_t&>**
               return py::array{10, o.b, obj};
           }
        );
```

```python
obj = a_t()
obj.b[0] = 0
obj.b[1] = 9
....
```

**Comment by zeroxer** [comment]
How could I define c style array with non-POD memeber?
```cpp
struct Student
{
	int id;
	std::string name;
};

struct ClassRoom
{
	Student students[10];
};
```
I want to use in this  way.
```python
class_room = pytest.ClassRoom()
class_room.students[2].name = "Tom"
```
