### ISSUE TITLE
Split class implementation code + Pybind11

### ISSUE THREAD

**Issue by nyckmaia** [pybind/pybind11#2157]
I have a working Pybind11 module called `maialib`.
Inside this module I have C++ class called `MusicXML`.
This class is composed by:
 - `musicxml.h`
- `musicxml.cpp` 

Until now, all MusicXML class methods implementations was written inside the `musicxml.cpp`and **it works good!**

Now, I would like to **split** some `MusicXML` methods into a **different** `*.cpp` files to get a better source-code organization.

To to that, I created a new `*.cpp` file called `orq_functions.cpp` and put only one `MusicXML` method inside of it called `my_method()` just to test.

But when I tried to compile **I got this linker error below:**

```
Scanning dependencies of target maialib
[ 16%] Building CXX object CMakeFiles/maialib.dir/src/maialib.cpp.o
[ 33%] Building CXX object CMakeFiles/maialib.dir/src/pugixml.cpp.o
[ 50%] Building CXX object CMakeFiles/maialib.dir/src/functions.cpp.o
[ 66%] Building CXX object CMakeFiles/maialib.dir/src/orq_functions.cpp.o
[ 83%] Building CXX object CMakeFiles/maialib.dir/src/musicxml.cpp.o
[100%] Linking CXX shared module maialib.cpython-37m-darwin.so
duplicate symbol 'MusicXMLClass(pybind11::module&)' in:
    CMakeFiles/maialib.dir/src/orq_functions.cpp.o
    CMakeFiles/maialib.dir/src/musicxml.cpp.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [maialib.cpython-37m-darwin.so] Error 1
make[1]: *** [CMakeFiles/maialib.dir/all] Error 2
make: *** [all] Error 2
```

I known that **is not** a C++ code or a CMake problem because I can compile this library as a C++ static library with CMake and **I got no errors.**

**To confirm that,** I just croped back the `my_method()` implementation to the original `musicxml.cpp` file and **all works good again!**

**So, how can I use Pybind11 in this case?**

Header
-------
Here is the `MusicXML` class inside the `musicxml.h`:
```
#ifndef MUSICXML_H
#define MUSICXML_H

class MusicXML
{
private:
    // private members...

public:
    MusicXML(const std::string fileName);

    // Another methods declarations

    const nlohmann::json my_method(nlohmann::json& config) const;
};

// ===== PYBIND11 ===== //

void MusicXMLClass(py::module &m) {

    m.doc() = "MusicXML class binding";

    // bindings to MusicXML class
    py::class_<MusicXML> cls(m, "MusicXML");

    cls.def("my_method", 
        [](MusicXML &self, py::object& pyConfig)
        {
            nlohmann::json config = py::object(pyConfig);
            return py::object(self.my_method(config));
        });
}
#endif
```
Implementation file 1
------------------
Here is the `musicxml.cpp`
```
#include "musicxml.h"

MusicXML::MusicXML(const std::string fileName)
{
    // Constructor implementation
}

// Another MusicXML methods implementations
```
Implementation file 2
----------------------
Here is the `my_method()` implementation inside the new `orq_functions.cpp` file:
```
#include "musicxml.h"

const nlohmann::json MusicXML::my_method(nlohmann::json& config) const
{
    // Here is the code...
}
```
CMake script
--------------
Here is just the Pybind11 part of my `CMakeLists.txt` file
```
find_package(PythonLibs)
include_directories(${PYTHON_INCLUDE_DIRS})

add_subdirectory(pybind11)

pybind11_add_module(maialib src/maialib.cpp src/orq_functions.cpp src/musicxml.cpp)

target_include_directories(maialib PUBLIC include)
```
**Any ideas? Could you help me please?**

**Comment by carlsonmark** [comment]
I think I have encountered a problem like this before.

Even though you have nice include guards (`#ifndef MUSICXML_H`), you would think that means that everything in them is only done once, right?

Well.... it is, but it is done once per compilation unit.

So if two .cpp files include musicxml.h, they don't know that each other included it, and both create `void MusicXMLClass(py::module &m)`.

Then, when it is time to link, the linker says: "I don't know which one to use!"

There are a few solutions to this problem, and I do not know which is the "correct" one. Here are two solutions I have used in the past.

Solution 1: **(not recommended!)** In musicxml.h, change it to:
```
inline void MusicXMLClass(py::module &m) { ... }
```

Solution 2: In musicxml.h, put:
```
void MusicXMLClass(py::module &m);
```
Then put this in **one** .cpp file somewhere:
```
void MusicXMLClass(py::module &m) { ... }
``

**Comment by nyckmaia** [comment]
**Thank you @carlsonmark ....it works!**

So, now my file structure is composed by 3 files:

1- Header: musicxml.h
----------------------
It's a normal C++ header. No Pybind11 elements....just pure C++.

2- Implementation files "n"
--------------------------
I can split the C++ class implementation on "n" different files....as usual....without any restrictions.
Again, no Pybind11 elements....just pure C++.

3- Pybind11 file
----------------
So I have a third file only to do the Pybind11 stuffs.
I called it `py_musicxml.cpp`. That means that this `*cpp` file will be responsable to bind all things of the `musicxml.cpp`.

```
#include "musicxml.h"

#ifdef PYBIND // My custom pre-processor macro

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/iostream.h>
#include "pybind11_json/pybind11_json.hpp"
namespace py = pybind11;

void MusicXMLClass(py::module &m) {

    m.doc() = "MusicXML class binding";
    py::class_<MusicXML> cls(m, "MusicXML");

   // Bind all class methods...
} 

#endif
```

**Thank you again and all the best!!**
