### ISSUE TITLE
How to expose pybind11::object in C?

### ISSUE THREAD

**Issue by Coderx7** [pybind/pybind11#2162]
## Issue description
This is not a pybind11 issue, however, I'm stuck because I dont know how to go about this using pybind's way of doing things. 
Basically I have a function in Python that accepts callbacks, and reurns an opencv image. 
I can create and send callbacks from C++ as well, using `py::object` directly or use `py::array_t` and it works well. 
```cpp
void default_callback(bool status, std::string id, py::array_t<uint8_t>& img)
{
	auto rows = img.shape(0);
	auto cols = img.shape(1);
	auto type = CV_8UC3;
	cv::Mat img1(rows, cols, type, img.mutable_data());

	cv::imshow("from callback", img1);
	auto timenow = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
	std::cout << "\narg1: " << status << " arg2: " << id << " arg3: " << typeid(img).name() << " " << ctime(&timenow) << std::endl;
}
```

However, I now decided to expose this in `C` so I can be able to call my dll from other languages such as C#, etc. 
I tried to use `void*`, 
```cpp
void default_callback(bool status, char* id, void* img)
{
	//cv::Mat img1(rows, cols, type, img.mutable_data());
	// cv::imshow("from callback", img1);
	auto timenow = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
	std::cout << "\narg1: " << status << " arg2: " << id << " arg3: " << typeid(img).name() << " " << ctime(&timenow) << std::endl;
}
```
but on python part it results in an exception like this : 
```Traceback (most recent call last):
  File "C:\Users\Master\Anaconda3\Lib\site-packages\SNR\utils.py", line 257, in start
    self._main_loop()
  File "C:\Users\Master\Anaconda3\Lib\site-packages\SNR\utils.py", line 301, in _main_loop
    self._execute_callbacks(is_valid, name, frame)
  File "C:\Users\Master\Anaconda3\Lib\site-packages\SNR\utils.py", line 142, in _execute_callbacks
    callback(*args)
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool, arg1: str, arg2: capsule) -> None

Invoked with: True, '5', array([[[193, 217, 241],
        [193, 217, 241],
        [192, 216, 239],
        ...,
        [152, 154, 181],
        [153, 156, 182],
        [158, 160, 187]],

       [[193, 217, 241],
        [193, 217, 241],
        [192, 216, 239],
        ...,
        [149, 152, 178],
        [151, 153, 180],
        [153, 156, 182]],

       [[196, 215, 241],
        [196, 215, 241],
        [195, 214, 239],
        ...,
        [145, 146, 173],
        [148, 148, 175],
        [149, 149, 176]],

       ...,

       [[137, 139, 154],
        [120, 122, 137],
        [122, 117, 135],
        ...,
        [100, 109, 142],
        [100, 109, 142],
        [100, 109, 142]],

       [[136, 145, 158],
        [118, 128, 140],
        [115, 115, 131],
        ...,
        [ 99, 108, 141],
        [ 99, 110, 142],
        [ 99, 110, 142]],

       [[133, 143, 155],
        [123, 133, 145],
        [115, 115, 131],
        ...,
        [ 98, 106, 140],
        [ 99, 110, 142],
        [ 99, 110, 142]]], dtype=uint8)

```

I assumed since we are dealing with `PyObject `at the very least, void* should work! and I should be able to get the pointer and cast it and thus carry on what I am supposed to. but it seems wrong. 

Would greatly appreciate any kind of hint/solutions in this regard 

## Reproducible example code
Here is a Visual Studio project file to reproduce the issue .
[github_pybind Minimal_test.zip](https://github.com/pybind/pybind11/files/4468117/github_pybind.Minimal_test.zip)

When the app crashes, a log file (which is also accessible from solution explorer) shows what happened in the python part. 
I commented out all opencv related codes, if you have it on your system you can enable them as well, but regardless of them, you can reproduce the issue. 

## Source files : 
Here are the files for those who dont want to download the vs project file.
GitHub wouldn't allow me to upload the actual source files, so I added a `.txt` extension after all of them.

[Core.h.txt](https://github.com/pybind/pybind11/files/4469967/Core.h.txt)
[Core.cpp.txt](https://github.com/pybind/pybind11/files/4469966/Core.cpp.txt)
[service_utils.py.txt](https://github.com/pybind/pybind11/files/4469968/service_utils.py.txt)
[test.cpp.txt](https://github.com/pybind/pybind11/files/4469969/test.cpp.txt)

**Comment by molpopgen** [comment]
Not sure if this helps, but the `ptr` function of a `handle` yields the `PyObject *`

https://pybind11.readthedocs.io/en/stable/advanced/cast/custom.html#custom-type-casters

**Comment by Coderx7** [comment]
Thanks a lot, really appreciate it, but no. my problem is I cant seem to find a way so that a callback arguments can be anythinng other than Pybind11 objects. since I'm exposing my C++ class in C
to be used by other clients such as C#, etc. 
using for example PyObject* on the callback results in the same error just like previous ones above.   
This shouldnt be this hard I guess, but I'm stuck in this for the past couple of days!
 
```
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool, arg1: str, arg2: _object) -> None

Invoked with: True, '5', array([[[193, 218, 237],
        [193, 218, 237],
        [192, 217, 235],
        ...,
        [210, 244, 255],
        [210, 244, 255],
        [210, 244, 255]],

       [[193, 218, 237],
        [193, 218, 237],
        [192, 217, 235],
        ...,
        [210, 244, 255],
        [210, 244, 255],
        [210, 244, 255]],

       [[193, 218, 237],
        [193, 218, 237],
        [192, 217, 235],
        ...,
        [210, 244, 255],
        [210, 244, 255],
        [210, 244, 255]],

       ...,

       [[121, 129, 138],
        [108, 116, 125],
        [114, 122, 133],
        ...,
        [154, 119, 142],
        [152, 117, 140],
        [150, 114, 138]],

       [[121, 136, 142],
        [106, 121, 127],
        [102, 119, 127],
        ...,
        [154, 116, 138],
        [151, 114, 138],
        [149, 111, 135]],

       [[121, 136, 142],
        [109, 124, 131],
        [102, 119, 127],
        ...,
        [153, 115, 137],
        [149, 111, 135],
        [148, 110, 134]]], dtype=uint8)

```

**Comment by Coderx7** [comment]
I guess this might be a bug in cpp_function as well. as I wrap my callbacks in a cpp_function. and cpp_function does the argument conversion by itself. void* and the likes are valid c++ types as well, so maybe someone with more Pybind11 knowledge than me can shed more light on this?
would greatly appreciate it

**Comment by molpopgen** [comment]
You may need to show a complete MRE in order to get help.  You've only shown a callback, but not something minimal that demonstrates an issue.

**Comment by Coderx7** [comment]
@molpopgen I added a minimal example to the issue . here it is again 👍 
Here is a Visual Studio project file to reproduce the issue .
[github_pybind Minimal_test.zip](https://github.com/pybind/pybind11/files/4468117/github_pybind.Minimal_test.zip)

Thanks a lot in advance

**Comment by molpopgen** [comment]
Seems like this is what you uploaded to a different issue?  Could you provide plain c++ files instead? Many people will not want to open random zip archives.  Also, many people who could help you do not us VS, and only the raw files are useful.

**Comment by Coderx7** [comment]
I uploaded two different projects for the two different issues. though this one is more complete than the previous one. 
Anyway sure thing, I thought it would be easier to have everything ready : 
anyway here are the files : 
[Core.h.txt](https://github.com/pybind/pybind11/files/4469967/Core.h.txt)
[Core.cpp.txt](https://github.com/pybind/pybind11/files/4469966/Core.cpp.txt)
[service_utils.py.txt](https://github.com/pybind/pybind11/files/4469968/service_utils.py.txt)
[test.cpp.txt](https://github.com/pybind/pybind11/files/4469969/test.cpp.txt)

github wouldn't allow me to upload the actual source file, so I added a .txt extension after all of them.

**Comment by molpopgen** [comment]
Sorry to be pedantic, but we're still pretty far from a minimal example.  There is a bunch of "Core" logic that should be removed.  Can you generate a single source file that generates the issue you are describing?  If there is an issue here, you should be able to isolate it (almost) entirely from the stuff in the Core files.

**Comment by Coderx7** [comment]
@molpopgen Here is the single cpp file , removed all opencv related file in the cpp as well (were commented before) 
The core file didnt have anything special, they just used pybind to get a module and run a method. nothing else. anyway here is the single source file + the sample module : 

[test.cpp.txt](https://github.com/pybind/pybind11/files/4473043/test.cpp.txt)
[service_utils.py.txt](https://github.com/pybind/pybind11/files/4473044/service_utils.py.txt)

**Comment by molpopgen** [comment]
All of Core is still in there. Sorry, but I can't spend any more time on this.

**Comment by Coderx7** [comment]
@molpopgen Does this do it ? :
```cpp
#include <iostream>
#include <functional>
#include <exception>

#include <pybind11/pybind11.h>
#include <pybind11/embed.h>
#include <pybind11/numpy.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>

namespace py = pybind11;
using namespace py::literals;

typedef void(*CallbackFn)(bool, std::string, py::array_t<uint8_t>&);
typedef std::function<void(std::string)> LogFunction;

typedef void(*CCallbackFn)(bool, char*, void*);
typedef void(*CLogFunction)(char* string);


void default_c_callback_temporary(bool status, char* message, void* ptr)
{
	std::cout << "status is: " << status << " id/name: " << message << " ptr:" << typeid(ptr).name() << std::endl;
}


// Note when  the app crashes (it may hang indefinitely and you need to stop the debugging in visual studio
// check out the exceptions-servicecore.log which contains the exception that happened on the python side 
//you can access this file in the solution explorer, next to other source files
int main()
{
	bool showFeed = false;
	py::scoped_interpreter guard{};

	try
	{
		std::cout << "Initialization started..." << std::endl;

		auto cls = py::module::import("service_utils").attr("ServiceCore");
		auto logInfo = [](std::string strInput) {std::cout << strInput; };

		py::dict kwargs = py::dict("loginfo_fn"_a = py::cpp_function(logInfo),
			"logwarning_fn"_a = py::none(),
			"logdebug_fn"_a = py::none(),
			"callback_list"_a = py::none(),
			"debug_show_feed"_a = (py::bool_)(showFeed));

		auto obj = cls(**kwargs);

		std::cout << "\Initialization is done!\n";

		obj.attr("add_c_callback")(py::cpp_function(default_c_callback_temporary));

		obj.attr("start");

		std::cout << "\nGet C Callbacks:\n";
		py::print(obj.attr("get_c_callbacks")());
		obj.attr("stop");

	}
	catch (std::exception ex)
	{
		std::cout << ex.what() << std::endl;
	}

	std::cout << "\nEverything done. press Enter to Exit";
	std::getchar();
	return 0;
}
[service_utils.py.txt](https://github.com/pybind/pybind11/files/4473356/service_utils.py.txt)

```
[test.cpp.txt](https://github.com/pybind/pybind11/files/4473354/test.cpp.txt)
[service_utils.py.txt](https://github.com/pybind/pybind11/files/4473356/service_utils.py.txt)
Thanks a lot in advance

**Comment by Coderx7** [comment]
manged to solve this through delegate callbacks
