### ISSUE TITLE
gil_scoped_release causes segmentation fault when used in a pure C++ context

### ISSUE THREAD

**Issue by luator** [pybind/pybind11#2177]
## Issue description

Using `pybind11::gil_scoped_release` causes a segmentation fault when calling the function in C++ directly.

I have a a C++ class which has Python bindings but should also be usable directly in C++.  In our setup, it is necessary that this class releases the GIL in the destructor to avoid a dead lock in some specific situations. Since I did not find another way, I added 

    pybind11::gil_scoped_release release;

In the destructor of the C++ class.  This works well when using it from Python but when using this class from C++ directly, it results in a segmentation fault.

I would expect that `gil_scoped_release` simply does nothing in case there is no Python interpreter running.

Is this a bug or intended behaviour?  In the latter case, is there another way to release the GIL in the destructor such that the class can still be used in C++ directly?

## Reproducible example code

Full reproducible example: https://github.com/luator/pybind11_segfault_example

The example class.  For the `hello` method the issue is avoided by using a `call_guard` but I did not find a non-intrusive solution for the destructor.
```c++
class Foobar {
public:
    ~Foobar() {
        pybind11::gil_scoped_release release;  // <-- problematic line
    }

    void hello() {
        std::cout << "Hello World" << std::endl;
    }
};

PYBIND11_MODULE(py_foobar, m) {
    pybind11::class_<Foobar>(m, "Foobar")
        .def(pybind11::init<>())
        .def("hello",
             &Foobar::hello,
             pybind11::call_guard<pybind11::gil_scoped_release>());
}
```
Causes a segfault on destruction when used directly in C++ like this:
```c++
int main()
{
    Foobar foo;
    foo.hello();
}
```

**Comment by felfert** [comment]
There is a simple solution for that: Use a wrapper class for the binding and place the pybind11-related stuff **there** instead of the base class:

E.g.:
```C++
class PyFoobar public Foobar {
public:
    PyFoobar() : Foobar() { }
    ~PyFoobar() {
        pybind11::gil_scoped_release release;
    }
};

PYBIND11_MODULE(py_foobar, m) {
    py::class_<Foobar> cl(m, "FoobarBase");
    pybind11::class_<PyFoobar, Foobar>(m, "Foobar")
        .def(pybind11::init<>())
        .def("hello",
             &Foobar::hello,
             pybind11::call_guard<pybind11::gil_scoped_release>());
}
```
Of course, PyFoobar should never be used directly from within C++

**Comment by luator** [comment]
@felfert This might work for this example, however, in my actual application, there are more things happening in the destructor (the things that in some cases need the GIL to be released).  With your wrapper, the GIL would only be released for the duration of `~PyFoobar` but not in `~Foobar` (where I actually need it).  Am I missing something here?

I could probably work around this by adding a `template<bool RELEASE_GIL = false>` to `Foobar` and set it to `true` for the bindings.  But this still does not feel like a proper solution.  To me this feels like a bug in `pybind11::gil_scoped_release`.  Shouldn't it be possible to detect if no Python interpreter is running and simply not do anything if not?

**Comment by luator** [comment]
I just realised that there is a much simpler workaround, I can simply use `Py_IsInitialized()` to check if Python is running or not, i.e.

```c++
if (Py_IsInitialized()) {
    pybind11::gil_scoped_release release;
    do_cleanup();
} else {
    do_cleanup();
}
```

**Comment by luator** [comment]
It seems that the same issue exists with `gil_scoped_acquire`.
I'm not familiar with the internals of pybind11, would it be possible to simply check `Py_IsInitialized()` internally in `gil_scoped_*` to avoid this or are there possible cases where this would fail?

**Comment by bstaletic** [comment]
> I can simply use `Py_IsInitialized()` to check if Python is running or not

The correct thing to do is call [`PyGILState_Check()`](https://docs.python.org/3/c-api/init.html#c.PyGILState_Check).

**Comment by luator** [comment]
Note for future readers: `PyGILState_Check()` was only added in Python 3.4, so it is not available in earlier versions.

**Comment by YannickJadoul** [comment]
@luator, https://stackoverflow.com/a/25666624 seems to have the answer for < 3.4
