### ISSUE TITLE
Cast chrono time_point to numpy datetime64

### ISSUE THREAD

**Issue by m4ce** [pybind/pybind11#2178]
I have a numpy structured array that needs returning from C++ to python. As part of the struct, there's a time field which is a system_clock::time_point.

I am unable to cast a time_point to numpy datetime64. The only way I have is to change the field to an int64 and store the timestamp in there. However, if I then want to cast it to datetime64 in python, a copy is made. I'd like to avoid any copy if possible.

I was looking through the source code and I see NPY_DATETIME is not handled. My understanding is that support could be added to pybind11 given a time_point holds a duration? 

Error:
```
ImportError: NumPy type info missing for NSt3__16chrono10time_pointINS0_12system_clockENS0_8durationIxNS_5ratioILl1ELl1000000EEEEEEE
```

**Comment by m4ce** [comment]
As I am trying to understand how things work internally, I am first trying to convert a custom type I defined to numpy datetime64.

I have added NPY_DATETIME to npy_api in numpy.h. I understand I need to specialize npy_format_descriptor and type_caster for the custom type I have.

Say I have defined a custom type called `Time`:

```c++
struct Time {
    std::int64_t ts;
};```

```c++
namespace pybind11 {
namespace detail {
template <>
struct npy_format_descriptor<Time> {
  static pybind11::dtype dtype() {
    handle ptr = npy_api::get().PyArray_DescrFromType_(npy_api::NPY_DATETIME);
    return reinterpret_borrow<pybind11::dtype>(ptr);
  }

  static std::string format() {
    // what exactly do I need to return here?
  }

  static constexpr auto name() {
    return _("datetime64");
  }
};
```

I am having a hard time in understanding what format() needs to return? I would appreciate if anyone can give me some directions here..

**Comment by YannickJadoul** [comment]
It's the "type string" from the numpy dtype. See https://numpy.org/doc/stable/reference/arrays.dtypes.html#specifying-and-constructing-data-types. I believe it's also related to [PEP 3118](https://www.python.org/dev/peps/pep-3118/).

So in this case, it should be `"M"`, if I'm not mistaken?
