### ISSUE TITLE
recursive implicit conversion fails, although boost::python work at this situation

### ISSUE THREAD

**Issue by hzhangxyz** [pybind/pybind11#2182]
## Issue description

recursive implicit conversion fails.

## Reproducible example code

M.cpp:
```
#include <pybind11/pybind11.h>

struct S {
   S(int) {}
};

struct E {
   E(S) {}
};

struct T {
   T(E) {}
};

namespace py = pybind11;

PYBIND11_MODULE(M, m) {
   py::class_<S>(m, "S").def(py::init<int>());
   py::implicitly_convertible<int, S>();
   py::class_<E>(m, "E").def(py::init<S>());
   py::implicitly_convertible<S, E>();
   py::class_<T>(m, "T").def(py::init<E>());
}
```

main.py
```
from M import *
print("int -> S -> E -> T")
T(E(S(2333)))
print("int -> E -> T")
T(E(2333))
print("int -> S -> T")
T(S(2333))
print("int -> T")
T(2333)
```

## what happen
the above three construction success but `T(2333)` fail. It say
```
int -> S -> E -> T
int -> E -> T
int -> S -> T
int -> T
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    T(2333)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. M.T(arg0: M.E)

Invoked with: 2333
```

## environment
arch linux
gcc 9.3.0
python 3.8.2
pybind11 2.5.0

## what else
BTW boost::python works well at this situation

M.cpp
```
#include <boost/python.hpp>

struct S {
   S(int) {}
};

struct E {
   E(S) {}
};

struct T {
   T(E) {}
};

namespace py = boost::python;

BOOST_PYTHON_MODULE(M) {
   py::class_<S>("S", py::no_init).def(py::init<int>());
   py::implicitly_convertible<int, S>();
   py::class_<E>("E", py::no_init).def(py::init<S>());
   py::implicitly_convertible<S, E>();
   py::class_<T>("T", py::no_init).def(py::init<E>());
}
```

**Comment by bstaletic** [comment]
I don't think an implicit conversion like this should work. Note that even in pure C++ you can't construct a `T` from an `int`. What you can do is provide additional constructors that take those parameters you want and do the right thing explicitly.

**Comment by YannickJadoul** [comment]
I'm quite curious how Bboost.Python does this, then? Seems very costly to explore a whole graph of implicit conversions?

**Comment by YannickJadoul** [comment]
> I'm quite curious how Boost.Python does this, then? Seems very costly to explore a whole graph of implicit conversions?

**Comment by hzhangxyz** [comment]
@bstaletic 

this is my situation, it works well

```
struct S {
      S(int) {}
};

struct E {
      E(S) {}
};

struct T {
      T(E) {}
};

int main() {
   auto a = T{{1}};
}
```

**Comment by bstaletic** [comment]
That `T{{1}}` still isn't implicit. You can't do `T{1}`. What you've written in your `main` is exactly equivalent to python's `T(E(1))`, which already works.

**Comment by hzhangxyz** [comment]
Since `E` is just a helper type here, I don't think writing its name explicitly in python is a good choice.
Or what is the good python API design for my situation?
A example of my c++ API is something like this: `T{ {1, 2, 3} }`
Should I write it as `T(E([1,2,3]))` or `T([S(1), S(2), S(3)])` in python? It is not simple.
Currently I just manually write a converter from `int` to `E` to solve this problem

**Comment by bstaletic** [comment]
> Currently I just manually write a converter from int to E to solve this problem

I don't see anything wrong with that. That's even what I suggested in my first comment.

**Comment by YannickJadoul** [comment]
What about adding an overload `T(S)` or `T(int)`?

**Comment by hzhangxyz** [comment]
This works but what I want is to generate constructor like boost python
automatically

Yannick Jadoul <notifications@github.com> 于2020年7月10日周五 下午8:37写道：

**Comment by YannickJadoul** [comment]
> This works but what I want is to generate constructor like boost python automatically

I don't really understand what you mean by that. Can you explain?

**Comment by YannickJadoul** [comment]
Actually, would just `py::implicitly_convertible<int, E>();` work?

**Comment by hzhangxyz** [comment]
Currently I just write some py::implicitly_convertible in fact. It works
but I don't want to write it because boost python does not require it. I
hope it will search which small constructor(int->S, S->E, E->T) can be used
and find out the correct constructor(int->T) recursively.

Yannick Jadoul <notifications@github.com> 于2020年7月11日周六 下午10:31写道：

**Comment by YannickJadoul** [comment]
> Currently I just write some py::implicitly_convertible in fact. It works but I don't want to write it because boost python does not require it. I hope it will search which small constructor(int->S, S->E, E->T) can be used and find out the correct constructor(int->T) 

If we do that, everything will become a lot slower, actually, because Boost.Python will actually do a whole recursive depth-first graph search, I believe. See Boost.Python's [`implicit.hpp`](https://github.com/boostorg/python/blob/102acf1d34ff91e67fe9aae401edc6edd68be89e/include/boost/python/converter/implicit.hpp) and [`implicit_rvalue_convertible_from_python`](https://github.com/boostorg/python/blob/102acf1d34ff91e67fe9aae401edc6edd68be89e/src/converter/from_python.cpp#L173).

I don't see a way to do this efficiently without making a whole bunch of existing pybind11 code slower, ánd there is a workaround. And pybind11 is not Boost.Python.

You could probably write your own custom caster setup to do anything you want, but I don't think this should be implemented in pybind11 by default.
