### ISSUE TITLE
return-local-addr warning in GCC 5.3.1

### ISSUE THREAD

**Issue by abergmeier** [pybind/pybind11#219]
When compiling my current bindings I get the following warning from GCC.

    In file included from ../pybind/include/pybind11/attr.h:13:0,
                     from ../pybind/include/pybind11/pybind11.h:32,
                     from ../src/bindings/render.cpp:6:
    ../pybind/include/pybind11/cast.h: In function ‘T pybind11::cast(pybind11::handle) [with T = unsigned int&]’:
    ../pybind/include/pybind11/cast.h:812:73: warning: function may return address of local variable [-Wreturn-local-addr]
         return conv.operator typename type_caster::template cast_op_type<T>();
                                                                             ^
    ../pybind/include/pybind11/cast.h:809:17: note: declared here
     type_caster conv;

**Comment by wjakob** [comment]
Hard to say much with this message. What is calling ``py::cast()``, and what are the template arguments?

**Comment by abergmeier** [comment]
I happens when doing e.g.:

    pythonTuple[0].cast<decltype(member[0])>(); // decltype(member[0]) is unsigned int&

IMO it would be best to `static_assert` if the destination type in cast is a reference!?

**Comment by wjakob** [comment]
Well, casting class instances to reference is perfectly fine. So some more differentiation would be needed -- feel free to submit a PR if this is important to you.

**Comment by wjakob** [comment]
Closing this ticket since there was no obvious solution and due to lack of activity.
