### ISSUE TITLE
pybind11 incompatible function arguments. The following argument types are supported: 1. (arg0: _GstPadProbeInfo) -> capsule

### ISSUE THREAD

**Issue by charmed12** [pybind/pybind11#2192]
i want to call a c++ function via python using pybind11, the c ++ function declaration is like billow :

void *getimage ( GstPadProbeInfo * info)
In python i called it using :

image=example.getimage(info)
info python type is gi.repository.GstPadProbeInfo when i run the code i get

incompatible function arguments. The following argument types are supported: 1. (arg0: _GstPadProbeInfo) -> capsule

how i can resolve this issues , please help me

**Comment by bstaletic** [comment]
For this to work, you need to have bindings for `GstPadProbeInfo`. Also, `image=example.getimage(info)` doesn't tell us what is `info`.

**Comment by YannickJadoul** [comment]
Closing this. If this is still an issue, please reopen it with more information on your bindings (and please use ``` to put your code/output in markdown; that makes things a lot more clear to read).
