### ISSUE TITLE
function argument by reference for changing array size 

### ISSUE THREAD

**Issue by lovecoffeeandmilk** [pybind/pybind11#2193]
if I write a function  void foo(std::vector<int> & array) { array.resize(100); }
In Python, I run it like this 
array = []
foo(array)
print(len(array))

since array is mutable, why the output is still 0, rather than 100 ?

**Comment by YannickJadoul** [comment]
Have a look at the docs: https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#automatic-conversion and https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#making-opaque-types
