### ISSUE TITLE
NAMESPACE_BEGIN macro redefinition

### ISSUE THREAD

**Issue by Trigve** [pybind/pybind11#2199]
## Issue description

The NAMESPACE_BEGIN is very generic name and therefor there could be the name clash (for instance CryptoPP does use the NAMESPACE_BEGIN also).

It could be fixed renaming the NAMESPACE_BEGIN -> PYBIND11_NAMESPACE_BEGIN. I think this is the only macro that hasn't the PYBIND11 prefix.

**Comment by michaeldkroener** [comment]
Encountered this problem had to pretty much #undef NAMESPACE_BEGIN #undef NAMSPACE_END
before including pybind11

**Comment by wjakob** [comment]
This change would be fine with me. Do you want to make a PR? FWIW, CryptoPP should probably also change its macro :-P

**Comment by YannickJadoul** [comment]
Funnily enough, pybind11 behaves quite polite here, checking if no one else already defined it:

```
#if !defined(NAMESPACE_BEGIN)
#  define NAMESPACE_BEGIN(name) namespace name {
#endif
#if !defined(NAMESPACE_END)
#  define NAMESPACE_END(name) }
#endif
```

**Comment by YannickJadoul** [comment]
But, see #2283.
