### ISSUE TITLE
what is the proper way to install pybind?

### ISSUE THREAD

**Issue by roeey777** [pybind/pybind11#2202]
Hi
I have a question about pybind11 installation process, I've looked at the way this package is installed with `conda-forge` and it got me thinking: why in they install pybind11 via `cmake` **and** `setuptools`?
both of them installs the same headers to different locations
- `cmake` installs the headers to `/include` and the `*Config.cmake` files to `/share/cmake/pybind11`
- `python setuptools` install the headers to `/include/python<major.minor>/site-packages/pybind11/include/pybind11`

Why both of them are needed? Can I use only one of `cmake` or `setuptools` without using the other?
- If I choose to build using`cmake` then I will surly use `find_package(Python REQUIRED)` and then I will have all the headers located within `python` include directory (because of the setuptools installation) which makes the pure `cmake` installation redundant (there is no need to `find_package(pybind11 REQUIRED)`).
- If I choose to build using `setuptools` then I surely don't need any of the `*Config.cmake` files.

`python` is obviously installed when working with `pybind11` so is there any reason to prefer `cmake` build over `setuptools`?

**Comment by YannickJadoul** [comment]
> Why both of them are needed? Can I use only one of `cmake` or `setuptools` without using the other?

They aren't. Yes.

pybind11 is a header-only library, so you really only need this during compilation, and anywhere where the include path can be found by your compiler should be fine.

If you then choose to use CMake to build your library, there's some extra CMake configuration provided by pybind11, but it again doesn't really matter where on your system that exists, as long as CMake can find it.

Have a look at the example configurations: https://github.com/pybind/python_example and https://github.com/pybind/cmake_example
