### ISSUE TITLE
Return array of struct variables from C++ function

### ISSUE THREAD

**Issue by sharod** [pybind/pybind11#2204]
I am trying to return an array of struct variables from a function in C++. But I am unable to find a way to do that. Please help me with this. I am providing a sample of the c++ code describing what I am trying to do:

`#include <pybind11/pybind11.h>
#include <stdlib.h>
#include <stdio.h>
#include <pybind11/stl.h>

namespace py = pybind11;

struct sample{
  int a;
};

std::array<sample,2> test(int i, int j) {
    sample p;
    p.a=i;
    sample q;
    q.a=j;
    std::array<sample,2> arr={p,q};
    return arr;
}

PYBIND11_MODULE(example, m) {
    m.doc() = "pybind11 example plugin"; 
    m.def("test", &test, "A function to return array of structs");
}`

**Comment by YannickJadoul** [comment]
It's in the docs: https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#structured-types
