### ISSUE TITLE
example/ directory missing or read the docs and PDF needs updating

### ISSUE THREAD

**Issue by prniii** [pybind/pybind11#2205]
## Issue description
PDF references examples in example/ directory that's not in the repository.  All of the ones called out below are referenced on the Advanced topics page 
https://pybind11-rtdtest.readthedocs.io/en/stable/advanced.html

PDF document calls out example/example2.cpp as example for stl data types.  Should that be instead test/test_stl.cpp ?
Similarly PDF calls out example/example6.cpp for binding sequence type and slicing protocol.  is that test/test_sequences_and_iterators.cpp

example/example3.cpp overloaded operators...
example/example5.cpp callbacks and anonymous functions
example/example7.cpp demonstrate using buffer protocol
example/example8.cpp custom reference-counting holder types...
example/example10.cpp demonstrate using vectorize()
example/example11.cpp usage of args and kwargs
example/example12.cpp override virtual functions...
example/example13.cpp keep_alive protocol...
example/example14.cpp create and expose opaque types
example/example15.cpp how to pickle and unpickle types
example/eigen.cpp how to pass Eigen sparse and dense data types

## Reproducible example code

Documentation inconsistency or missing examples/ directory from repository.

**Comment by prniii** [comment]
Looks like example/ is missing, I located a older copy on https://gitlab.unistra.fr/benzerara/pybind11 
which does have an examples/ folder, and they are examples rather than test code.

**Comment by bstaletic** [comment]
Historically, examples were turned into tests. The docs need to be updated to reflect that, I guess.

**Comment by YannickJadoul** [comment]
https://pybind11-rtdtest.readthedocs.io/ rather than https://pybind11.readthedocs.io/

These are some old docs, seemingly from the time the project was added to readthedocs? At any rate, the official docs that are linked from everywhere have long been updated: for example: https://pybind11.readthedocs.io/en/stable/advanced/functions.html#call-guard
