### ISSUE TITLE
Dangling references with reference data members

### ISSUE THREAD

**Issue by orgarten** [pybind/pybind11#2206]
Hi,

I have some issues with dangling references which I was not able to solve.

## Issue description

Using a wrapped class, which holds a reference type data member, results in a dangling reference. In the example code below, this happens when I want to use the function ```print_first_3_elements```. Apparently, the reference is not valid anymore. The same happens if I use pointers instead of references. Printing the values of the ```std::vector``` within the constructor seems to be working just fine.

A workaround is to copy the data, however, my data could be quite big, therefore I would like to avoid copying if possible.

### Unsuccessful attempts to solve the issue:
* disabling the garbage collector in python
* using pointers instead of references

Maybe anybody has an idea how to mitigate this issue. Thanks in advance!

## Reproducible example code
main.cpp
```cpp
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
namespace py = pybind11;

class A {
private:
	const std::vector<double>& data;
public:
	explicit A(const std::vector<double>& data_) : data(data_) {
		std::cout << data[0] << " -> ";
		std::cout << data[1] << " -> ";
		std::cout << data[2] << "\n";
	}

	void
	print_first_3_elements() const {
		std::cout << data[0] << " -> ";
		std::cout << data[1] << " -> ";
		std::cout << data[2] << "\n";
	}
};

PYBIND11_MODULE(pybind_test_mod, m) {
	py::class_<A> cls(m, "A");

	cls.def(py::init<const std::vector<double>&>(), py::keep_alive<1,2>());
	cls.def("print_first_3_elements", &A::print_first_3_elements);
}
```
When using the module in Python as follows, I get a segfault for the second function call.
```py
data = np.array([1., 2., 3., 4., 5., 6., 7.], dtype=np.float64)
a = pybind_test_mod.A(data)  # this works
a.print_first_3_elements() # this segfaults
```
Desired output:
```
1 -> 2 -> 3
1 -> 2 -> 3
```
Output from example above:
```
1 -> 2 -> 3
[1]    5345 segmentation fault (core dumped)  python simple_test.py
```

**Comment by darwin** [comment]
It looks to me that even if this approach worked you would end up with full data copy because the automatic python-to-stl conversion does a full copy before it calls your constructor. 

It probably does not work because you store a referece/pointer to temprorary STL vector which is not kept around by pybind (after you return from your constructor).

https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#automatic-conversion

**Comment by orgarten** [comment]
Ok, now I see where the problem arises which wasn't quite clear for me before.

The tips in your link work pretty much the way I want them to work, it's just a little bit more boilerplate code for the python user:

```c++
#include <pybind11/stl_bind.h>
...
PYBIND11_MAKE_OPAQUE(std::vector<double>);
...
py::bind_vector<std::vector<double>>(m, "vector");
```
```py
data = np.array([1., 2., 3., 4., 5., 6., 7.], dtype=np.float64)
data_vector = pybind_test_mod.vector(data)
a = pybind_test_mod.A(data_vector)
a.print_first_3_elements()
```
