### ISSUE TITLE
scoped_estream_redirect does not capture FILE* stderr

### ISSUE THREAD

**Issue by Getshi** [pybind/pybind11#2209]
The error stream redirection functionality provided by pybind11 does not work for the FILE* stderr, but only captures std::cerr.

```
m.def("printerr",
 []() {
   std::cerr << "This error is printed in the ipynb.\n";
   std::string str = "This error is printed in the console\n";
   fprintf(stderr, str.c_str());
 },
 py::call_guard<py::scoped_ostream_redirect,
 py::scoped_estream_redirect>());
```
For me, this is mainly a minor hickup in coding logging functionality, where instead of `vfprintf(stderr,...)` I have to first write to a `char*` buffer with `vsnprintf(buf, ...)` and then do `std::cerr << buf;`.
If there is an easy fix on pybind's side for capturing both, that would be nice, otherwise mentioning this in the documentation could help.

**Comment by YannickJadoul** [comment]
`FILE*` is C and `stderr` and `stdout` are not part of `iostream` and are a lot harder to capture (as far as I know, solutions are not very portable and would involve POSIX-specific functionality).

At any rate, `fprintf`ing to `stdout` or `stderr` completely bypasses `std::cout` and `std::cerr`, so this is not really in the scope of `py::scoped_ostream_redirect` or `py::scoped_estream_redirect`. So no, there's not a lot we can do there, I'm afraid. It would be nice to have, but unless there's a clean solution, "avoid `printf` like the plague" is the way to go.
