### ISSUE TITLE
Symbol not found for ncurses _COLORS, pybind11/pybind11.h not found

### ISSUE THREAD

**Issue by tony** [pybind/pybind11#221]
Thank you for your project.

Green with C++., sorry if I'm getting basic things wrong.

OS X Darwin, python 3.5

https://github.com/tony/kakoune/tree/pybind11 - branch
https://github.com/tony/kakoune/blob/pybind11/CMakeLists.txt - cmakelists

[cmake --system-information output](https://github.com/pybind/pybind11/files/294779/sysinfo.txt)

```
❯ which python3.5
/usr/local/bin/python3.5

❯ python3.5 -c 'import kakoune'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/me/study/c++/kakoune/build/kakoune.cpython-35m-darwin.so, 2): Symbol not found: _COLORS
  Referenced from: /Users/me/study/c++/kakoune/build/kakoune.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Users/me/study/c++/kakoune/build/kakoune.cpython-35m-darwin.so
```

```
~/study/c++/kakoune pybind11* 6m 28s
❯ ag COLORS
src/ncurses_ui.cc
139:    else if (can_change_color() and COLORS > 16)
142:        if (m_next_color > COLORS)
156:        for (int i = 0; i < std::min(256, COLORS); ++i)
```

I read https://github.com/pybind/pybind11/blob/master/docs/faq.rst.

Second question: is ``pybind::module`` a requirement? In a project like this, where would you keep them?

If I put a 

```c++
#include <pybind11/pybind11.h>
namespace py = pybind11;

int add(int i, int j) {
    return i + j;
}

PYBIND11_PLUGIN(cmake_example) {
    py::module m("cmake_example");
```

into the bottom of any ``.cc`` file, I get this:

```
../src/main.cc:872:10: fatal error: 'pybind11/pybind11.h' file not found
#include <pybind11/pybind11.h>
         ^
48 warnings and 1 error generated.
[2/4] Building CXX object CMakeFiles/kakoune.dir/src/main.cc.o
FAILED: CMakeFiles/kakoune.dir/src/main.cc.o
```

But I'm following the [instructions for cmake](http://pybind11.readthedocs.io/en/latest/compiling.html#building-with-cmake) in my [CMakeLists.txt](https://github.com/tony/kakoune/blob/pybind11/CMakeLists.txt), am I doing it wrong?

**Comment by dean0x7d** [comment]
As far as I can see, you are making both an executable and an extension module. The first error is because the module is not linked with the dependencies. Add this line to resolve it:
```cmake
target_link_libraries(kakoune PRIVATE ${Boost_LIBRARIES} ${CURSES_LIBRARY})
```

The second error is because the executable should not contain `PYBIND11_PLUGIN`, only the module should. Make a new .cc file (e.g. `src_module/main.cc`) and place `PYBIND11_PLUGIN` in there. The CMake config should look something like this:
```cmake
add_executable(kak ${kakoune_SOURCES})
file(module_SOURCES src_module/main.cc)
pybind11_add_module(kakoune ${kakoune_SOURCES} ${module_SOURCES})
```

**Comment by tony** [comment]
[cmake --system-information output](https://github.com/pybind/pybind11/files/295747/sysinfo.txt)

https://github.com/tony/kakoune/tree/pybind11 - branch
https://github.com/tony/kakoune/blob/pybind11/CMakeLists.txt - cmakelists
https://github.com/tony/kakoune/blob/pybind11/src_module/main.cc - src_module/main.cc

```
❯ python3.5 -c 'import kakoune'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/me/study/c++/kakoune/build/kakoune.cpython-35m-darwin.so, 2): Symbol not found: _COLORS
  Referenced from: /Users/me/study/c++/kakoune/build/kakoune.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Users/me/study/c++/kakoune/build/kakoune.cpython-35m-darwin.so
```

There is no ``_COLORS`` in the codebase, but I assume its related to ``COLORS`` from [curses.h](http://pubs.opengroup.org/onlinepubs/7908799/xcurses/curses.h.html) in https://github.com/tony/kakoune/blob/pybind11/src/ncurses_ui.cc.

> The <curses.h> header provides a declaration for COLOR_PAIRS, COLORS, COLS, curscr, LINES and stdscr.

So far I haven't found an example that deals with a case of satisfying an external lib dependency like that.  Do I end up having to add a plugin to satisfy the ncurses dependency?

**Comment by wjakob** [comment]
See the answer by dean0x7d, who mentions ``target_link_library``.

**Comment by wjakob** [comment]
This is not a pybind11 issue, so I'm closing this ticket.

**Comment by tony** [comment]
Thank you @dean0x7d, up and running with https://github.com/tony/kakoune/blob/25d4b98b2d7c25cdfe057646155ab8a8b77a53ac/src_module/main.cc.

Thanks for your work on the project @wjakob
