### ISSUE TITLE
python3 docstring --> memory errors

### ISSUE THREAD

**Issue by looooo** [pybind/pybind11#222]
Compiling my code for python3.5 gave me memory errors at the end of a python session. Removing all the docstrings in the readwrite, readonly ... functions solved this.
Here is a minimal example:

https://github.com/looooo/py_bind_11_tests/blob/master/pybi_memory_problems.cpp#L14

thanks, Lorenz

**Comment by wjakob** [comment]
What kind of memory errors were these -- can you be more specific? What's your platform, python distribution (e.g. OS-bundled, compiled yourself), etc..

**Comment by looooo** [comment]
``` python
IPython 3.5.1+ (default, Mar 30 2016, 22:46:26) 
.
.
.

In [1]: import pybi_memory_problems

In [2]: 
Do you really want to exit ([y]/n)? y
*** Error in `python3': munmap_chunk(): invalid pointer: 0x00007f6ea0669bc8 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7f6ea56f1725]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7f6ea56fdc18]
/home/lo/projects/py_bind_11_tests/build/pybi_memory_problems.so(_ZN8pybind1112cpp_function8destructEPNS_6detail15function_recordE+0x73)[0x7f6ea065e42c]
/home/lo/projects/py_bind_11_tests/build/pybi_memory_problems.so(_ZZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infoiENKUlP7_objectE_clESC_+0x29)[0x7f6ea065d18f]
/home/lo/projects/py_bind_11_tests/build/pybi_memory_problems.so(_ZZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infoiENUlP7_objectE_4_FUNESC_+0x1d)[0x7f6ea065d1af]
```
System: ubuntu 16.04
ipython from apt, but also happens with std python3.5.1 version.

Is the minimal example working for you?

**Comment by looooo** [comment]
I didn't want to close this issue, sry

**Comment by wjakob** [comment]
I almost could not believe it, that's a nasty bug you found! Thanks for reporting it.

**Comment by looooo** [comment]
wow, that was fast, thanks a lot!
