### ISSUE TITLE
bind_vector only works for unsigned int, not work for int, not work for other native types either

### ISSUE THREAD

**Issue by frank-xlj** [pybind/pybind11#2222]
Make sure you've completed the following steps before submitting your issue -- thank you!

1. Check if your question has already been answered in the [FAQ](http://pybind11.readthedocs.io/en/latest/faq.html) section.
2. Make sure you've read the [documentation](http://pybind11.readthedocs.io/en/latest/). Your issue may be addressed there.
3. If those resources didn't help and you only have a short question (not a bug report), consider asking in the [Gitter chat room](https://gitter.im/pybind/Lobby).
4. If you have a genuine bug report or a more complex question which is not answered in the previous items (or not suitable for chat), please fill in the details below.
5. Include a self-contained and minimal piece of code that reproduces the problem. If that's not possible, try to make the description as clear as possible.

*After reading, remove this checklist and the template text in parentheses below.*

## Issue description
I am using VS2017 15.9.19. Python3.6.4-64bit.
py::bind_vector<std::vector<int>>(m, "VectorInt", py::buffer_protocol()); 

python:
v_int = m.VectorInt([0, 0])
assert len(v_int) == 2

It throws 'access violation' error when running the test. But it works fine if using 'unsigned int'.

## Reproducible example code

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete C++ and Python snippets that can be easily compiled and run to diagnose the issue.)

**Comment by bstaletic** [comment]
```
>>> import xxx
>>> v_int = xxx.V([1,1])
>>> v_int
V[1, 1]
>>> assert len(v_int)
>>> assert len(v_int) == 2
```

>     py::bind_vector<std::vector>(m, "VectorInt", py::buffer_protocol());

This should be `py::bind_vector<std::vector<int>>( ... );`
