### ISSUE TITLE
Pybind11 doesn't compile with CPython 3.9b1

### ISSUE THREAD

**Issue by bstaletic** [pybind/pybind11#2224]
CPython recently released version 3.9.0b1. As is the wonderful custom, it comes with breaking changes.

> > Is pybind affected by python 3.9 breaking changes?
> 
> [Yes](https://github.com/pybind/pybind11/blob/master/include/pybind11/detail/internals.h#L276) and [yes](https://github.com/pybind/pybind11/blob/master/include/pybind11/pybind11.h#L1971)

> Useful links:
> 
> - https://docs.python.org/3.9/whatsnew/3.9.html#deprecated
> - https://docs.python.org/3.9/whatsnew/3.9.html#removed
> - https://bugs.python.org/issue37878
> - https://github.com/python/cpython/pull/15315
> - https://github.com/python/cpython/pull/18892
> - https://bugs.python.org/issue39877

`PyEval_InitThreads()` is deprecated and now does exactly nothing.
`PyThreadState_DeleteCurrent()` is "removed", or rather renamed to `_PyThreadState_DeleteCurrent()`. This one was never documented and the reason for the rename is "why would anyone ever use this function?"

**Comment by henryiii** [comment]
The fix for `PyEval_InitThreads()` looks easy: https://sourceware.org/pipermail/gdb-patches/2020-April/167630.html

A simple `#if` should fix it.

**Comment by henryiii** [comment]
The PyThreadState_DeleteCurrent() was supposed to be restored, per @wjakob's request: https://github.com/pybind/pybind11/issues/1932 and https://bugs.python.org/issue38266 - there was a brief mention of adding an underscore, but it was not supposed to be added.

**Comment by bstaletic** [comment]
> The fix for `PyEval_InitThreads()` looks easy: https://sourceware.org/pipermail/gdb-patches/2020-April/167630.html

Are we sure it is that easy in Pybind11, considering the ability to transfer GIL from one thread to another?

> The `PyThreadState_DeleteCurrent()` was supposed to be restored

It was removed in https://github.com/python/cpython/pull/15315.
Then the change was reverted in https://github.com/python/cpython/pull/16558
The CPython docs haven't been updated and still claim that the function was removed (12th bulletpoint): https://docs.python.org/3.9/whatsnew/3.9.html#removed

**Comment by henryiii** [comment]
Docs are being fixed: https://github.com/python/cpython/pull/20489#pullrequestreview-420220906

**Comment by bstaletic** [comment]
python/cpython#20489 is merged. This only leaves `PyEval_InitThreads()`.

Ping @wjakob

**Comment by bstaletic** [comment]
This can be closed.
