### ISSUE TITLE
Is a python installation needed on the client's computer when running the resulting exe with pybind11 embedded?

### ISSUE THREAD

**Issue by NewAndConfused** [pybind/pybind11#2227]
I embedded pybind11 into my C++ project using CMake with the instructions found here: https://pybind11.readthedocs.io/en/stable/advanced/embedding.html

Everything works fine and the exe compiles and runs, but I found that the exe will not run on any computer that does not already have python installed. Does that mean I did something incorrectly with my embedding? Or is that expected behavior?

**Comment by bstaletic** [comment]
When embedding, you should be able to statically link `libpython`.

**Comment by YannickJadoul** [comment]
> When embedding, you should be able to statically link `libpython`.

See also #2232, for example.

I don't know how Windows works, though. Does it by default link to a dll? I'd expect that if that's the case, you could also ship the `libpython` DLL instead of statically linking?

Closing the issue. If this is not a solution, do please reopen.
