### ISSUE TITLE
Unknown CMake command "pybind11_add_module"

### ISSUE THREAD

**Issue by Zach0806** [pybind/pybind11#2229]
Hallo,

When I run CMake, I get this error: 

CMake Error at python/openpose/CMakeLists.txt:6 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

Is there anyone who knows how to solve this problem?

Thank you

**Comment by gargarchit** [comment]
Hello @Zach0806, Have you added pybind11 as sub directory or package before this command?

**Comment by YannickJadoul** [comment]
As @gargarchit says (thanks, @gargarchit!), you should indeed `add_subdirectory(pybind11)` or something similar. See basic examples in the documentation.

If that doesn't work, please reopen this issue and show us how your `CMakeLists.txt` looks, please.

**Comment by YunchuZhang** [comment]
Hi YannickJadoul, could you give a more detailed solution? I am not so familiar with cmake stuff, how could I add_subdirectory?where should I put this stuff?


Thanks

**Comment by YannickJadoul** [comment]
@YunchuZhang The documentation has some good explanation on how to build and what different build systems you can use: https://pybind11.readthedocs.io/en/stable/basics.html & https://pybind11.readthedocs.io/en/stable/compiling.html

**Comment by YunchuZhang** [comment]
thanks

**Comment by Hemanthkumar2112** [comment]
i should create a sub folder? @YunchuZhang

**Comment by YunchuZhang** [comment]
> should i need to create a sub folder pyblind11? @YunchuZhang

no, i think it could make that

**Comment by ABHINAV0307** [comment]
I am getting this error 
Is there any solution to it?

  
does not contain a CMakeLists.txt file.


CMake Error at python/openpose/CMakeLists.txt:6 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

**Comment by guynich** [comment]
DId you try `sudo apt install python3-pybind11` ?

**Comment by serser** [comment]
`pip install pybind11` will make CMake understand it.
