### ISSUE TITLE
Cannot add a new item to a std::map in the pybind-ed C++ class.

### ISSUE THREAD

**Issue by KohMat** [pybind/pybind11#2231]
## Issue description

Cannot add a new item to a std::map which is the member variable in the pybind-ed C++ class in Python.

## Reproducible example code

There is the "A" class.

```c++
#include <map>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

class A {
 public:
    std::map<std::string, double> container;
};

namespace py = pybind11;

PYBIND11_MODULE(python_example, m) {
    py::class_<A>(m, "A")
        .def(py::init<>())
        .def_readwrite("container", &A::container);
}
```

Call the A class in Python and tried adding a new item in the `container` member but it's empty.

```python
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_example
>>> a = python_example.A()
>>> a.container
{}
>>> a.container["aaa"] = 1.0
>>> a.container
{}
>>> 
```

**Comment by YannickJadoul** [comment]
This is expected, since `std::map` is copied into a Python `dict`. See https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#automatic-conversion for details and possible solutions.

**Comment by bstaletic** [comment]
Another thing to look at is `py::bind_map` and `stl_bind.h`.

**Comment by KohMat** [comment]
Understood. I thought I had read the document, but it seems I didn't. Thank you very much.
