### ISSUE TITLE
Linker errors: undefined reference to Py_GetVersion

### ISSUE THREAD

**Issue by pavelschon** [pybind/pybind11#2232]
I'm getting linker errors like below. Obviously when I add `-lpython27 ` erros are gone, but isn't pybind11 _header-only, no linkage_ ? Could you please clarify?
```
undefined reference to `Py_GetVersion'
undefined reference to `PyExc_ImportError'
undefined reference to `PyErr_Format'
undefined reference to `PyExc_ImportError'
undefined reference to `PyErr_SetString'
undefined reference to `PyExc_ImportError'
undefined reference to `PyErr_SetString'
```

**Comment by carlsonmark** [comment]
pybind11 is header-only, yes. But it is a header-only solution for using libpython. So if you are using Python2.7, you will still need to link to libpython27.

**Comment by pavelschon** [comment]
Thanks, I do embedding. The documentation should clarify that the linkage is needed in this case.

**Comment by YannickJadoul** [comment]
The docs @carlsonmark linked to show `target_link_libraries(example PRIVATE pybind11::embed)`. It is also explained in the Python docs themselves: https://docs.python.org/3/extending/embedding.html

Feel free to submit a PR, but I don't see this as particularly unclear.

**Comment by pavelschon** [comment]
Unfortunately we don't use CMake hooks provided by PyBind11, so we need do everything "manually".
From docs unclear what _pybind11::embed_ does behind scenes.

**Comment by YannickJadoul** [comment]
>  From docs unclear what _pybind11::embed_ does behind scenes.

Sure, but it ís clear you need to link against something, if it says `target_link_libraries`?
And if you look it up, It's in the CMake files of pybind11, btw: https://github.com/pybind/pybind11/blob/0d70f0e18eec60786499faba53de4d72583ba2f7/tools/pybind11Config.cmake.in#L86-L88

**Comment by pavelschon** [comment]
Good enough - thanks for pointing me to the code.

However, [goodies](https://pybind11.readthedocs.io/en/stable/intro.html#goodies) says:
_Everything is contained in just a few header files; there is no need to link against any additional libraries._

It should mention something like:
_except when embedding the interpreter in your executable, then linkage with libpython is needed._

**Comment by YannickJadoul** [comment]
Myeah, maybe, but pybind11 is not adding anything on top of CPython itself; that's what that part of the readme means.

Partially, this is probably a historical artifact, since the non-embedding side of pybind11 is much more widely used, and embedding was probably added later.
