### ISSUE TITLE
How to return a string containing null characters to Python

### ISSUE THREAD

**Issue by LeoHsiao1** [pybind/pybind11#2239]
## Issue description
I want to know how to return a string containing null characters to Python.

## Reproducible example code
```cpp
PYBIND11_MODULE(example, m)
{
    m.def("return_bytes",
          []() {
              return py::bytes("Hello\x00\x00World");
              // return py::str("Hello\x00\x00World");
              // return std::string("Hello\x00\x00World");
          });
}
```
```python
>>> import example
>>> example.return_bytes()
b'Hello'
```
As you can see, the string returned by pybind11 is truncated by `\x00`.  And I want to get the full string:`Hello\x00\x00World`
Looking forward to your guidance.

I found a relevant [tutorial](https://pybind11.readthedocs.io/en/master/advanced/cast/strings.html#returning-c-strings-to-python), and a relevant [Issue](https://github.com/pybind/pybind11/pull/48#issue-54584365), but they did not solve my problem.

By the way, I already know a way to pass a string containing null characters to C++:
```cpp
PYBIND11_MODULE(example, m)
{
    m.def("input_bytes",
          [](const char *data, long size) {
              char *buffer = (char *)calloc(size, sizeof(data));
              if(buffer)
                memcpy(buffer, data, size);
          });
}
```

**Comment by carlsonmark** [comment]
Are you sure that `std::string("Hello\x00\x00World")` creates a `std::string` with nul characters in it?
I believe in all three cases below, you need to use the constructor that specifies the length of the string. 

```
              return py::bytes("Hello\x00\x00World");
              // return py::str("Hello\x00\x00World");
              // return std::string("Hello\x00\x00World");
```

See "Notes", here: https://en.cppreference.com/w/cpp/string/basic_string/basic_string

**Comment by carlsonmark** [comment]
Also, if you are using C++14, you can use a std::string literal:
```
#include <string>

using namespace std::string_literals;

int main()
{
    return std::string("123\x00\x00\x00"s).size(); // Note: Trailing s after the closing double-quote
}
```
In this example, the size is 6.

**Comment by LeoHsiao1** [comment]
Thank you for your guidance. I found a useful [example](https://github.com/pybind/pybind11/blob/534b756cb3244aca959359c07d44e4fed3498ba8/tests/test_constants_and_functions.cpp#L31).
