### ISSUE TITLE
unresolved external symbol for method bindings only with multiple projects

### ISSUE THREAD

**Issue by ktnr** [pybind/pybind11#2255]
## Issue description

In the solution there two projects:
- CppSource (contains a normal C++ project for which I want to create python bindings)
- CppSource.Bindings (imports the required .h files from CppSource and creates the bindings)

Creating the bindings for classes and their public members works fine. Methods also work, but only methods that are not inherited from base classes. For base class methods I get a compilation error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: void __cdecl ICoordinate::SetPosition(int,int,int)" (?SetPosition@ICoordinate@@QEAAXHHH@Z)	ContainerPacking.Bindings
`

The error only occurs when the bindings are created in a separate project. When put into the same project there is no error.

I'd like to keep the projects separate. But I'm happy to be convinced that doing so is a bad idea.

## Reproducible example code

CppSource 
Container.h
```
struct ICoordinate
{
  public:
    int X = 0;
    int Y = 0;
    int Z = 0;

    void SetPosition(int x, int y, int z);

  protected:
    ICoordinate() = default;
    ICoordinate(int x, int y, int z) : X(x), Y(y), Z(z) {}
};

class Box : public ICoordinate
{
  public:
    void Translate(int dx, int dy, int dz)
    {
        X += dx;
        Y += dy;
        Z += dz;
    }
};
```

CppSource.Bindings 
.cpp file
```
#include "../ContainerPacking/src/Container.h"

#include <pybind11/pybind11.h>
namespace py = pybind11;

PYBIND11_MODULE(containerpacking, m)
{
    py::class_<Box>(m, "Box")
        .def(py::init())
        .def("translate", &Box::Translate)
        ////.def("setPosition", &Box::SetPosition) // error when uncommented
        .def_readwrite("X", &Box::X)
        .def_readwrite("Y", &Box::Y)
        .def_readwrite("Z", &Box::Z);
}
```

**Comment by bstaletic** [comment]
This sounds like you either haven't compiled `Container.cpp` or you didn't link `Bindings` with `Container`.

**Comment by YannickJadoul** [comment]
Indeed. If things work in a single project, you probably need to link the `CppSource` project into the `CppSource.Bindings` project.

Let's close this, as it doesn't seem related to pybind11. If there are more complications related to pybind11, feel free to reopen!
