### ISSUE TITLE
problem translate main from C++ to python

### ISSUE THREAD

**Issue by HiLiHeYi** [pybind/pybind11#2272]
```
int main(int argc, char *argv[]) {

    std::cout << "hello from app" << std::endl;
    return 0;
}

namespace py = pybind11;

PYBIND11_MODULE(cmake_example, m) {
    
    m.def("main", &main);
}
```
```
note: in instantiation of function template specialization 'pybind11::module::def<int (*)(int, char **), char [86]>' requested here
      m.def("main", &main);

        ^
```
Hey, 
I started to use pybind11 last week and it worked for some simple functions like ``` int add( int a , int b ) ```.  But for some reasons, it doesn't work for the main func. Someone maybe knows a solution ?

**Comment by bstaletic** [comment]
The solution is "don't use `main`". Your python interpreter already has one and you're just asking for trouble. Not to mention that recursively calling `main` is undefined behaviour.

**Comment by YannickJadoul** [comment]
What @bstaletic said. With the right visibility, `main` might be hidden and not conflict with the actual `main`, though? Anyway, it smells like a problem waiting to happen, indeed.

Furthermore, pybind11 doesn't do `char **` or `char *[]` so to bind such a signature, wrap it in a lambda/function that accepts `std::vector<std::string>` and copy/convert it to a `char**` yourself before passing it on.
