### ISSUE TITLE
Derived class (in Python) cannot access Base class (in Python) methods

### ISSUE THREAD

**Issue by colombojrj** [pybind/pybind11#2276]
Hello, I have studied the documentation (very good by the way) and the issues section on github. But I did not find the solution. If this is not an issue then I am sorry.

It is worth noting that the [Classes - Combining virtual functions and inheritance](https://pybind11.readthedocs.io/en/master/advanced/classes.html#combining-virtual-functions-and-inheritance) is not what I want to do.

## Issue description

My case of use is the following: I have a c++ class that makes things very fast. But I want to use that class from Python because Python is so nice and easy. So far, I also want to add more nice features by creating derived (python) classes.

## Reproducible example code

```
#include <iostream>
#include <pybind11/pybind11.h>

class Base {
public:
	Base() {};
	~Base() {};
	void my_method_cpp() { std::cout << "My method" << std::endl; }
};

namespace py = pybind11;

PYBIND11_MODULE(file, m) {
	py::class_<Base> base(m, "Base");

	base.def(py::init());

	base.def("my_method_cpp", &Base::my_method_cpp);
}
```

Then I compiled it with:

c++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` file.cpp -o file`python3-config --extension-suffix`

And I test it with the following test.py:

```
from file import *

class Derived(Base):
	def __init__(self):
		Base().__init__(self)

	def my_method_python(self):
		my_method_cpp()

if __name__ == '__main__':

	base = Base()
	base.my_method_cpp()

	derived = Derived()
	derived.my_method_python()
```

### Obtained result:

```
python3 test.py 
My method
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    derived.my_method_python()
  File "test.py", line 8, in my_method_python
    my_method_cpp()
NameError: name 'my_method_cpp' is not defined
```

### Expected result:

My method
My method

### Workaround to get the expected result:

```
from file import *

class Derived(Base):
	def __init__(self):
		super().__init__()

	def my_method_python(self):
		super().my_method_cpp()

if __name__ == '__main__':

	base = Base()
	base.my_method_cpp()

	derived = Derived()
	derived.my_method_python()
```

Thanks in advance. And again, if this problem was previously solved, then I am sorry.

**Comment by YannickJadoul** [comment]
This is not a problem with pybind11, but a small Python mistake:

```
class Derived(Base):
    # ...
    def my_method_python(self):
        my_method_cpp()
```

This is incorrect. The correct way to call a method from another method is `self.my_method_cpp()`. This should work, just as well as `derived.my_method_cpp()` in your test script should work.

It's doing something different than `super().my_method_cpp()`, since `self.my_method_cpp()` will first try to call `Derived.my_method_cpp` and only then find `Base.my_method_cpp()`.

PS: These kinds of questions that aren't pybind11 issues, you can also quickly ask on [Gitter](https://gitter.im/pybind/Lobby).
