### ISSUE TITLE
Type wrapped in a module is not visible in a separate embedded module on Windows

### ISSUE THREAD

**Issue by dchapp** [pybind/pybind11#2279]
## Issue description

Hello, I have a project that consists of the following components:

1. A C++ struct `my_struct`
2. A pybind11 module containing bindings for `my_struct`
3. A C++ application that:
  1. Contains a pybind11 embedded module that contains bindings for a different struct `my_wrapper_struct` that has an instance of `my_struct` as a member
  2. Embeds an interpreter via pybind11's `scoped_interpreter`

I want (and on Linux, I am able) to run the following python code in the embedded interpreter:
```
py::exec(R"(
    import my_module
    import embedded_module
    ws = embedded_module.wrapper_struct()
    print(ws.my_struct) # Should print <my_module.my_struct object at some address>
    )");
```
However, on Windows (specifically, Windows version 10.0.18363 and Visual Studio 2019 version 16.5.1), I get the following error:
```
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: embedded_module.wrapper_struct) -> my_struct
At:
  <string>(6): <module>
```

One additional note--the codebase that this example is based on manages dependencies via conan and as such is using PyBind11 2.5.0, specifically as available here https://conan.io/center/pybind11/2.5.0/?user=_&channel=_

I have included code below that, to the best of my knowledge, constitutes a minimal reproducible example of this behavior on Windows. Any assistance or pointers to relevant documentation would be greatly appreciated. 

### Definition of `my_struct` (my_struct.h)
```
#include <pybind11/pybind11.h>
struct PYBIND11_EXPORT my_struct {
  int attr{1234};
};
```

### Bindings for `my_struct` (my_module.cpp)
```
#include "my_struct.h"
#include <pybind11/pybind11.h>
namespace py = pybind11;
PYBIND11_MODULE(my_module, m) {
py::class_<my_struct, std::shared_ptr<my_struct>>(m, "my_struct")
.def(py::init<>())
.def_readwrite("attr", &my_struct::attr);
}
```

### Main executable containing embedded module and interpreter (main.cpp)
```
#include "my_struct.h"

#include <pybind11/embed.h>
#include <pybind11/pybind11.h>

#include <iostream>
#include <memory>

namespace py = pybind11;

struct PYBIND11_EXPORT wrapper_struct {
  std::shared_ptr<my_struct> my_struct_ptr{std::make_shared<my_struct>()};
};

PYBIND11_EMBEDDED_MODULE(embedded_module, m) {
  py::class_<wrapper_struct>(m, "wrapper_struct")
    .def(py::init<>())
    .def_readwrite("my_struct_ptr", &wrapper_struct::my_struct_ptr);
}

int main() {
  py::scoped_interpreter guard{};
  try {
    py::exec(R"(
    import my_module
    import embedded_module
    ws = embedded_module.wrapper_struct()
    print(ws.my_struct_ptr) 
    )");
  }
  catch (const py::error_already_set& e) {
    std::cerr << e.what() << std::endl;
  }
  return 0;
}
```

Working example also available at https://github.com/dchapp/pybind11_example

**Comment by ixje** [comment]
I can't seem to reproduce your issue
![image](https://user-images.githubusercontent.com/6625537/87118092-c1b6c200-c27a-11ea-91bb-79d629da0a0e.png)

Note there are 2 differences from your example repo
1. I don't use conan, but a standard Python from Python.org
2. I use Python `3.7.8` not `3.6.9`

**Comment by mguidry-glodon** [comment]
@ixje Note that the example does use a standard Python install and the only thing coming from conan is pybind11 itself. May I ask that you describe the procedure you took to build the example? I would hope just a standard import into VS and then build, along with the conan install.

Context: I am part of the team where we are experiencing this issue.

**Comment by bstaletic** [comment]
Make sure both modules are compiled with the same version of pybind11. If the versions are different, ABI may have been broken and instead of silently being wrong, pybind11 instead doesn't want to cooperate with modules with different ABI.

**Comment by ixje** [comment]
@mguidry-glodon see my diff below. In summary
- I commented out all conan related code
- added `FetchContent` for downloading `pybind11` and commented out `find_package(pybind11)` because I'm not installing it
- updated PYBIND11_PYTHON_VERSION from `3.6.9` to my `3.7.8`
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a2917c6..aa00b7f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -4,13 +4,22 @@ project(minrep_app)
 set(CMAKE_CXX_STANDARD 17)
 set(CMAKE_POSITION_INDEPENDENT_CODE ON)

-include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
-conan_basic_setup()
+#include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
+#conan_basic_setup()

 find_package(Python COMPONENTS Interpreter Development)

-set(PYBIND11_PYTHON_VERSION 3.6.9)
-find_package(pybind11 REQUIRED)
+
+include(FetchContent)
+FetchContent_Declare(
+       pybind11
+       GIT_REPOSITORY https://github.com/pybind/pybind11.git
+       GIT_TAG v2.5.0
+       )
+FetchContent_MakeAvailable(pybind11)
+
+set(PYBIND11_PYTHON_VERSION 3.7.8)
+#find_package(pybind11 REQUIRED)

 # Prevent linker errors caused by the dependencies of PyBind's interface library target                                 set(LIBS "${Python_LIBRARIES}")
@@ -18,7 +27,7 @@ list(REMOVE_ITEM LIBS "optimized")
 list(REMOVE_ITEM LIBS "debug")

 pybind11_add_module(my_module my_module.cpp)
-target_link_libraries(my_module PRIVATE ${CONAN_LIBS})
+#target_link_libraries(my_module PRIVATE ${CONAN_LIBS})

 add_executable(main)
 target_sources(main PUBLIC main.cpp)
```

>  I would hope just a standard import into VS and then build, along with the conan install.

Yes I'm building from VS. Mostly because for some weird Windows reason I don't understand (not a regular Windows user) it didn't seem to pickup `pybind11` via CMake eventhough it should have been made available via `FetchContent_MakeAvailable`. So opened VS, did some overkill solution by adding the headers to the global includes (Solution -> Properties -> VC++ Directories -> include directories). Then build and debug from there

![image](https://user-images.githubusercontent.com/6625537/87156070-5b529380-c2bc-11ea-9522-3bf609f3be08.png)
![image](https://user-images.githubusercontent.com/6625537/87156265-b3899580-c2bc-11ea-8eb8-83c954453a58.png)

**Comment by dchapp** [comment]
@bstaletic Thanks--we have verified that both modules are compiled with the same pybind11 version.

**Comment by dchapp** [comment]
Turns out this was not strictly a pybind11 issue, but instead related to how we were acquiring pybind11 via conan. In my `setup.py` (available at https://github.com/dchapp/pybind11_example/blob/master/setup.py) I invoke `conan install` but do not specify a build type (e.g., Debug, Release). This meant that sometimes the pybind11 module was being built in one mode, whereas the application that was running an embedded interpreter that would import that module was built in a different mode. When these modes did not match, we could reproduce this issue. When they did match, we could not. Interestingly enough this did not seem to be an issue on Ubuntu 18.04.
