### ISSUE TITLE
Is there any way to manipulate python dict in-place in c++

### ISSUE THREAD

**Issue by chenbohua3** [pybind/pybind11#2288]
As described [here](https://pybind11.readthedocs.io/en/latest/faq.html#limitations-involving-reference-arguments), immutable objects can not be manipulated by sending reference argument. However, dict is mutable. So Is there any way to manipulate python dict in-place in c++ by sending reference?

```
void f(std::unordered_map<int*, int*>& data) {
  data[1] = 1;
}
```
with:
```
.def("f", &f)
```

so we will get:
```
data = {}
f(data)
# data = {1: 1} now
```

I have tried codes above and found it does not work. Do i miss something or this goal is just unattainable.

**Comment by bstaletic** [comment]
`stl.h` header *copies* things back and forward. You want `py::bind_map` from `stl_bind.h` header.

**Comment by chenbohua3** [comment]
@bstaletic do you mean that i should replace `std::unordered_map` with `py::bind_map`?

**Comment by bstaletic** [comment]
No. I'm talking about your bindings. https://pybind11.readthedocs.io/en/latest/advanced/cast/stl.html

https://pybind11.readthedocs.io/en/latest/advanced/cast/stl.html#making-opaque-types

https://pybind11.readthedocs.io/en/latest/advanced/cast/stl.html#binding-stl-containers

**Comment by YannickJadoul** [comment]
Or accept a `py::dict` and work on that Python object, ofc.

**Comment by YannickJadoul** [comment]
> Or accept a `py::dict` and work on that Python object, ofc.

https://pybind11.readthedocs.io/en/stable/advanced/pycpp/object.html

**Comment by chenbohua3** [comment]
@bstaletic that's exactly what i want, thank you:)

**Comment by chenbohua3** [comment]
@YannickJadoul I will try, thank you:)
