### ISSUE TITLE
Auto-wrapping enumerations

### ISSUE THREAD

**Issue by ianhbell** [pybind/pybind11#229]
Is there a means of automatically wrapping all entries in an enumeration?  I have an enumeration with about 100 parameters and I *really* don't want to have to parse the definition of the enumeration myself as a pre-processing step.

**Comment by wjakob** [comment]
Sadly C++ (not even C++17 AFAIK) does not have reflection support, so the answer is no.

**Comment by ianhbell** [comment]
:(
