### ISSUE TITLE
Remove stale readthedocs website https://pybind11-rtdtest.readthedocs.io/

### ISSUE THREAD

**Issue by YannickJadoul** [pybind/pybind11#2296]
Hi @dean0x7d, it seems you own this old (test version?) of the docs. Is that correct?
I presume it would not serve any purpose anymore, and some users get confused, looking at an old version of the docs.

Is it possible to remove it?

**Comment by dean0x7d** [comment]
Yes, indeed. I forgot about it after testing some docs changes a long time ago. I've removed it now.

**Comment by YannickJadoul** [comment]
Great, thanks! :-)
