### ISSUE TITLE
Error "already registered!" for module_local

### ISSUE THREAD

**Issue by fnrizzi** [pybind/pybind11#2300]
## Issue description

Hello! I am trying to use the `module_local` to create bindings for the same class under two different modules. But I keep getting a "already registered!" error. Not sure if what I am using is the best way to do this. But the doc seems to suggest so. 

## Reproducible example code

```c++
template <typename T> 
struct MyFoo{
  T a_={};
  MyFoo(T b) : a_(b){}
  T get() const{ return a_; }
};

PYBIND11_MODULE(mymod, mParent)
{
  pybind11::module m1 = mParent.def_submodule("M1");
  pybind11::class_<MyFoo<int>>(m1, "MyFoo", pybind11::module_local())
    .def(pybind11::init<int>());

  pybind11::module m2 = mParent.def_submodule("M2");
  pybind11::class_<MyFoo<int>>(m2, "MyFoo", pybind11::module_local())
    .def(pybind11::init<int>());
}
```
this gives me this error: `E   ImportError: generic_type: type "MyFoo" is already registered!`
I am using pybind11 v2.5 and gcc8.4.0 on macOS. Any help would be much appreciated! thanks

**Comment by YannickJadoul** [comment]
What you show are submodules in the a single (pybind11) module. Since they are in the same compiled library, and will share types. `module_local` helps with not sharing between two different pybind11 modules.

I this case, you can probably just say `m2.attr("MyFoo") = m1.attr("MyFoo");` (or name the `class_` object and assign that).

**Comment by fnrizzi** [comment]
thanks for the reply! Is there a way to make bindings local to submodules?

**Comment by YannickJadoul** [comment]
How exactly do you need them to be "local"?

**Comment by fnrizzi** [comment]
Basically, even if the underlaying c++ objects are the same, I would like (if possible) to treat them as distinct objects in the two different submodules. Does that make sense? Not sure if possible but was wondering. 

Btw, your solution above `m2.attr("MyFoo") = m1.attr("MyFoo");` does not work, I still get the same error, even after removing the `module_local'.

**Comment by YannickJadoul** [comment]
> Basically, even if the underlaying c++ objects are the same, I would like (if possible) to treat them as distinct objects in the two different submodules. Does that make sense? Not sure if possible but was wondering.

The issue then is: if you return a `MyFoo<int>` object from a function, should pybind11 translate it to `m1.MyFoo` or `m2.MyFoo`?

The best way to go would probably be to create two "dummy" classes that contain a `MyFoo` or so (and maybe a custom caster). Something like `template <typename T, int N> struct MyFooWrapper { MyFoo<T> myFoo; }`?

> Btw, your solution above `m2.attr("MyFoo") = m1.attr("MyFoo");` does not work, I still get the same error, even after removing the `module_local'.

No, that solution would only register the class once, and just copy the definition of one submodule to the other submodule (without using `class` a second time). But it wouldn't be considered as 2 separate types.

**Comment by fnrizzi** [comment]
> The issue then is: if you return a `MyFoo<int>` object from a function, should pybind11 translate it to `m1.MyFoo` or `m2.MyFoo`?

yes that makes sense, I see your point!

> The best way to go would probably be to create two "dummy" classes that contain a `MyFoo` or so (and maybe a custom caster). Something like `template <typename T, int N> struct MyFooWrapper { MyFoo<T> myFoo; }`?

ok, I will look into it!

> No, that solution would only register the class once, and just copy the definition of one submodule to the other submodule (without using `class` a second time). But it wouldn't be considered as 2 separate types.

Oh, i see, I don't need to create the second one. I just need to copy it, right? I will try that.

**Comment by YannickJadoul** [comment]
Alright.

By the way: you often get quicker answers to a short question on [Gitter](https://gitter.im/pybind/Lobby).
