### ISSUE TITLE
pybind11 'callable' always returns 'True'

### ISSUE THREAD

**Issue by hassan-aman** [pybind/pybind11#2302]
I have a python script (simple.py) with this:
```
class Component:
    name = 'Tagged'
    speed = 23
    rotSpeed = 0.1
```
And in my C++ code:
```
pybind11::object component = pybind11::globals()["Component"]();
pybind11::object callable = pybind11::module::import("builtins").attr("callable");

if (callable(component.attr("rotSpeed")))
    std::cout << "Property is callable" << std::endl; // <-- It always prints this!
```

How can I determine through C++ if a property is a function or not?

**Comment by bstaletic** [comment]
I can't reproduce.

```c++
#include <pybind11/embed.h>
#include <pybind11/eval.h>
#include <pybind11/pybind11.h>

int main(void)
{
	namespace py = pybind11;
	py::scoped_interpreter g;
	py::eval_file("test.py");
	auto callable = py::module::import("builtins").attr("callable");
	py::print(callable(py::globals()["i"]));
	py::print(callable(py::globals()["Component"]));
	py::print(callable(py::globals()["Component"].attr("rotSpeed")));
	return 0;
}
```

How are you getting `Component` into the `globals` dictionary?

**Comment by hassan-aman** [comment]
@bstaletic Actually, nevermind, I got it working. It was a Python mistake (I am a bit new to this language, I shouldn't have treated it like C++).

**Comment by bstaletic** [comment]
For the record, this was my `test.py`

```python
i = 3
class Component:
  rotSpeed = 0.1
```

**Comment by YannickJadoul** [comment]
It's probably not a Python mistake. `handle::operator bool()` just returns whether it contains a valid Python object, as specified in the C++ docs: https://pybind11.readthedocs.io/en/stable/reference.html#_CPPv4NK6handlecvbEv. `py::cast<bool>(...)` (or `py::cast<bool>(py::bool_(...))` does what you want it to do, probably.
