### ISSUE TITLE
Import modules in embedded Python (with C++)

### ISSUE THREAD

**Issue by hassan-aman** [pybind/pybind11#2304]
(My apologies for asking questions again and again)

I have two files:
_mts.py:_

```
def add(a, b):
    return a + b
```

and _main.py_
```
print('Hello, world!')
```

And I have my C++ code
```
py::initialize_interpreter(); // I am purposely not using eval_file because in the future I might not be using files, but strings instead.
py::exec(readFile("mts.py"));
py::exec(readFile("main.py"));
py::finalize_interpreter();
```

My question is, how can I import 'mts.py' in 'main.py'? i.e. How can I call 'add' in 'main.py'?

**Comment by bstaletic** [comment]
There's `auto mts = py::module::import("mts");`

Also `auto main_add = py::module::import("main").attr("add");`

FOr questions like these, it's better to ask on gitter.
