### ISSUE TITLE
Reducing compile time memory consumption strategies

### ISSUE THREAD

**Issue by atom-moyer** [pybind/pybind11#2306]
Hi all,

I have a project that wraps a C++ template class (map) into many precompiled forms to work with most combinations of numpy datatypes. However this takes a lot of memory during compilations to compile all of these combinations into one module.

Is there a simple way to break up compilation of all these template instances and keep them in one module, or do I need to make several dummy modules and keep track of which module each class is compiled to in python?

I tried to naive approach which is just splitting up the module into multiple C++ files (this reduced memory consumption), but creating the same module in the different files could not be handled during linking I believe.

Here is a link to the repo: https://github.com/atom-moyer/getpy

Thanks,
Adam

**Comment by YannickJadoul** [comment]
Did you see [this](https://pybind11.readthedocs.io/en/stable/faq.html#how-can-i-reduce-the-build-time) and [this](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#partitioning-code-over-multiple-extension-modules) in the docs? I believe that's what you're looking for, or not?

I suppose linking to shared libraries or dynamic linking could also work (I don't see why it wouldn't), but it'll probably make distributing the library harder.

Also, you can try asking questions on [Gitter](https://gitter.im/pybind/Lobby), before making an issue.
