### ISSUE TITLE
how to pass numpy array to c++ by value

### ISSUE THREAD

**Issue by xdaniel9** [pybind/pybind11#2308]
here is my function signature
```
auto fun(py::array_t<double, py::array::c_style | py::array::forcecast> x)
```
My question is that how to pass x to this function by value, currently, if I pass x with dtype `np.float64`, then x is passed by reference.

**Comment by YannickJadoul** [comment]
`py::array` is a Python type, so this is passed in as similar way as in Python (i.e., basically a shared pointer that is passed by value).
If you don't want to change the original, you'll have to make a copy. You can check `base()` or `owndata()` to see when you should copy or when you are the only owner.

Also, for short questions like this, that aren't really issues, there's [Gitter](https://gitter.im/pybind/Lobby), where you'll often get a faster answer than here.
