### ISSUE TITLE
equivalent of boost::python::make_constructor?

### ISSUE THREAD

**Issue by mhochsteger** [pybind/pybind11#231]
Suppose you want to provide a Python binding to an abstract C++ class without exposing all subclasses. Using make_constructor it is possible to provide the abstract base class with a 'pseudo constructor' returning one of its derived classes, depending on the input, like this:

```cpp
BaseClass * CreateInstance( int type ) {
  if (type==0) return new ClassA();
  if (type==1) return new ClassB();
  ...
}

bp::class_<BaseClass>( "BaseClass")
    .def("__init__", bp::make_constructor(CreateInstance))
    ;
```

For custom constructors Pybind11 handles memory allocation, which makes it impossible to use the placement new operator of a derived class.

```cpp

pybind11::class_<BaseClass>("BaseClass")
    .def("__init__", [] ( BaseClass * ptr, int type ) {
        // Fails if sizeof(ClassA) > sizeof(BaseClass)
        if (type==0) new (ptr) ClassA();
        if (type==1) new (ptr) ClassB();
    });
```

Is there any solution to this problem?

Thanks!

BTW: Great library! Can't wait to get rid of the boost dependency of our project :)

**Comment by wjakob** [comment]
This is is not possible with pybind11. The library assumes that the object being constructed is what you actually said it would be. You should probably be using inheritance.
