### ISSUE TITLE
split abstract and derived classes in multiple compilation units

### ISSUE THREAD

**Issue by DerThorsten** [pybind/pybind11#232]
Hi, 

I have a base class with pure virtual functions, and many many derived classes.
Is There a way to have each of the derived classes in a single translation/compilation unit.

I am using code as in the following example.
```
    py::class_<Animal> animal(m, "Animal");
    animal
        .def("go", &Animal::go);

    py::class_<Dog>(m, "Dog", animal)
        .def(py::init<>());

    m.def("call_go", &call_go);
```

The problem is, the derived class "Dog"  takes "animal" as argument.  If i want to put  "Dog" in a single header, how can i get  the "animal" instance.

Greetings Thorsten

**Comment by wjakob** [comment]
Please take another look at the docs, it shows how to do this with py::base
