### ISSUE TITLE
register a function in PYBIND11_MODULE(my_module, m) to by called during import my_module

### ISSUE THREAD

**Issue by xunleiwu** [pybind/pybind11#2329]
## How to register/export a function in PYBIND11_MODULE(my_module, m) so that in Python, import my_module will invoke such function?

include <pybind11/pybind11.h>
int checkLicense(...) { 
... 
}

int add(int i, int j) {
return i + j;
}

PYBIND11_MODULE(my_module, m) {
m.doc() = "pybind11 my_module plugin"; // optional module docstring
m.def("add", &add, "A function which adds two numbers");
}

I have asked the question in https://gitter.im/pybind/Lobby#. I have not got a working answer. I wonder whether I have to inherit py::module and customize a constructor in the derived class calling checkLicense(). If so, would you please provide an example? Thank you all very much.

**Comment by wjakob** [comment]
These kinds of very basic questions shouldn't be handled on the issue tracker, closing..

**Comment by wjakob** [comment]
(And I believe @bstaletic gave you the answer you needed on the Gitter chat. Just look carefully through the conversation..)
