### ISSUE TITLE
ModuleNotFoundError: import of builtins halted; None in sys.modules

### ISSUE THREAD

**Issue by tlsdmstn56-2** [pybind/pybind11#2331]
## Issue description

Error occur at the end of python script

```
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  ModuleNotFoundError: import of builtins halted; None in sys.modules
Aborted (core dumped)
```

## Reproducible example code

I made modifications on [pybind/cmake_example](https://github.com/pybind/cmake_example).

Therefore if you update `main.cpp` to the following code, you can easily compile and test it.

```cpp
// use pybind version: v.2.5.0
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <pybind11/iostream.h>
#include <pybind11/stl.h>

#include <vector>
#include <iostream>

namespace py = pybind11;

template <typename T>
py::array_t<T> to_numpy(std::vector<T> &&v)
{
    auto new_vec = new std::vector<T>(std::move(v));
    py::capsule clear = py::capsule((void *)new_vec, [](void *vec) {
        py::scoped_ostream_redirect output;
        std::cout << "delete vector\n";
        delete reinterpret_cast<std::vector<T> *>(vec);
    });
    return py::array_t<T>({new_vec->size()}, {sizeof(T)}, new_vec->data(), clear);
}

PYBIND11_MODULE(cmake_example, m)
{
    m.def(
        "get_vector", []() {
            return to_numpy<int>(std::vector<int>(10000, 0));
        },
        "");
}

```

This is the used python script

```python
import cmake_example as ce

if __name__ == "__main__":
    for _ in range(10):
        vec = ce.get_vector()
    # del vec
```
And stdout of the script is:
```
$ python3 test.py
delete vector
delete vector
delete vector
delete vector
delete vector
delete vector
delete vector
delete vector
delete vector
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  ModuleNotFoundError: import of builtins halted; None in sys.modules
Aborted (core dumped)
```

However when I add `del vec` (removing `#` from the python code above), this issue disappeared.

Is there someone who has the same issue?

**Comment by bstaletic** [comment]
I can easily reproduce the problem, but I'm not sure what's going on. Here's what causes the error in pure python:

```
>>> import sys
>>> sys.modules['test'] = None
>>> import test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: import of test halted; None in sys.modules
```

https://github.com/python/cpython/blob/6daa37fd42c5d5300172728e8b4de74fe0b319fc/Lib/importlib/_bootstrap.py#L1009

Interestingly, it doesn't happen when embeding interpreter. Even more interestingly, the error doesn't happen on python2.

**Comment by YannickJadoul** [comment]
Extra data point: I can reproduce, and running from the Python 3.8 shell, I get the following (on exit!):

```pycon
>>> # <ctrl-D>
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by YannickJadoul** [comment]
Oh, there you go! If I comment out `py::scoped_ostream_redirect output;`, everything works as expected.

So, my conclusion/guess is: the destruction order of Python is unpredictable, and some system modules are already garbage collected before `vector` gets garbage collected and the `capsule`'s callback gets called. This also explains why adding `del vector` solves things: this way, `vector` gets garbage collected before the internal modules get garbage collected.

Solution: don't access Python anymore from the `capsule`'s deleter callback.
If you really can't do that, make sure the callback keeps some kind of a reference to the necessary Python internals (mainly the `sys` module, in this case, I believe; but hey, not sure; to be tested), such that the garbage collector would first collect your variable before the internal modules. I would believe/hope that keeps things more sane, but it's still risky behavior, I'd say.

At any rate, this is not something pybind11 can fix, I'm afraid. So I'll close this issue. Feel free to still reply or reopen (or even better: come to [Gitter](https://gitter.im/pybind/Lobby)) if you need more clarification.
