### ISSUE TITLE
make test works, but unable to run tests individually

### ISSUE THREAD

**Issue by skebanga** [pybind/pybind11#234]
`make test` passes all tests, but attempting to run them individually fails.

This could well just be a documentation issue - as in, the documentation doesn't have details on how to run individual tests from the command line.

How do I run the tests, individually, from the command line?

**Running the tests automatically via makefiles:**

On linux:
  
    $ cmake .
    $ make -j8
    $ make test

> `100% tests passed, 0 tests failed out of 18`

**Attempting to run a test individually:**

    $ ./example/example1.py
  
> ```
Traceback (most recent call last):
  File "./example/example1.py", line 6, in <module>
    from example import Example1
ImportError: No module named example
```

**Attempting to run from within the example directory:**

    $ cd example
    $ ./example1.py

> ```
Traceback (most recent call last):
  File "./example1.py", line 6, in <module>
    from example import Example1
ImportError: No module named example
```

**Attempt to find the shared library created during the build process:**

    $ find . -name '*.so'
    ./example/example.cpython-34m.so

**Attempt to link `example.cpython-34m.so` to `example.so`:**

    $ ln -s example/example.cpython-34m.so example.so
    $ ./example/example1.py

> ```
Traceback (most recent call last):
  File "./example/example1.py", line 6, in <module>
    from example import Example1
ImportError: ./example.so: undefined symbol: PyInstanceMethod_Type
```

**Attempt to link `example.cpython-34m.so` to `example.so` inside example directory:**

    $ cd example
    $ ln -s example.cpython-34m.so example.so
    $ ./example1.py

>```
Traceback (most recent call last):
  File "./example1.py", line 6, in <module>
    from example import Example1
ImportError: /home/steve/src/3rd-party/pybind11/example/example.so: undefined symbol: PyInstanceMethod_Type
```

**Show no unresolved dependencies:**

```
$ ldd example.so
	linux-vdso.so.1 =>  (0x00007ffdfa7e8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa6d632c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa6d6115000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa6d5d4f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa6d5a49000)
	/lib64/ld-linux-x86-64.so.2 (0x0000563626045000)
```

**Attempting to run `run_test.py`:**

    $ ./run_test.py 
    ( just hangs indefinitely... )

**Attempting to run `run_test.py` through python:** (note: might be nice to add a hash-bang to `run_test.py`)

    $ python ./run_test.py 
    Syntax: run_test.py [--relaxed] <test name>

**Attempt to run `example1.py` through `run_test.py`:** 

    $ python ./run_test.py ./example1.py

>```
Traceback (most recent call last):
  File "./run_test.py", line 58, in <module>
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', './example1.py.py']' returned non-zero exit status 2
```

**Attempt to run `example1` through `run_test.py`:** 

    $ python ./run_test.py ./example1

>```
Traceback (most recent call last):
  File "./run_test.py", line 58, in <module>
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', './example1.py']' returned non-zero exit status 2
```

So this begs the question - how do I run the tests, individually, from the command line?

**Comment by wjakob** [comment]
I think it goes like that:
```
python example/run_test.py example1
```

**Comment by skebanga** [comment]
$ python example/run_test.py example1

>```
Traceback (most recent call last):
  File "example/run_test.py", line 58, in <module>
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'example1.py']' returned non-zero exit status 1
```

**Comment by dean0x7d** [comment]
Module was compiled with python3 but you're running it from python2.

**Comment by wjakob** [comment]
Maybe the issue is that the extension module does not get written to your 'example' directory? It should be compiled by the cmake build system and placed in that directory.

**Comment by wjakob** [comment]
Or that! (@dean0x7d)

**Comment by skebanga** [comment]
Aaargh - @dean0x7d - you are correct - ugh! :(

**Comment by wjakob** [comment]
(See the FAQ)

**Comment by wjakob** [comment]
Ha, github has some concurrency issues -- closed by two people :)

**Comment by skebanga** [comment]
So - **definitely** closed! :)
