### ISSUE TITLE
how can I convert a python int which is longer than 64 bit to c++

### ISSUE THREAD

**Issue by leafwaltz** [pybind/pybind11#2354]
how can I convert a python int which is longer than 64 bit to c++?
For example:
in python:  a_long_int(0b1111...(512bits)...1111)
in c++: a_long_int(some_type value);

a c++ int param not takes effect

**Comment by bstaletic** [comment]
What do you expect to get on the C++ side, regarding representation? If you want a lossless conversion, you'll have to resort to a 3rd party arbitrary precision integer library. Or maybe some 128bit variable? Then you'll also need a custom caster to convert to the C++ type.

Alternatively, take `py::int_` and use that throughout your code.

**Comment by leafwaltz** [comment]
> What do you expect to get on the C++ side, regarding representation? If you want a lossless conversion, you'll have to resort to a 3rd party arbitrary precision integer library. Or maybe some 128bit variable? Then you'll also need a custom caster to convert to the C++ type.
> 
> Alternatively, take `py::int_` and use that throughout your code.



> What do you expect to get on the C++ side, regarding representation? If you want a lossless conversion, you'll have to resort to a 3rd party arbitrary precision integer library. Or maybe some 128bit variable? Then you'll also need a custom caster to convert to the C++ type.
> 
> Alternatively, take `py::int_` and use that throughout your code.

I just want to construct my c++ object by an int variable but it not work when the input value is longer than 64bits

**Comment by bstaletic** [comment]
Then just take an `int` parameter and pybind will raise an error when the object can't fit.
