### ISSUE TITLE
Clearer install instructions needed

### ISSUE THREAD

**Issue by SourceCodeDeleted** [pybind/pybind11#2356]
I like this project and I like that they are code examples which appear to make this project seem simple to use and install. However, there aren't install instructions in the README.md .

I was reading the documentation and while code examples are good, I think the install instructions there are leaving some to be desired.

```
#include <pybind11/pybind11.h>

int add(int i, int j) {
    return i + j;
}

PYBIND11_MODULE(example, m) {
    m.doc() = "pybind11 example plugin"; // optional module docstring

    m.def("add", &add, "A function which adds two numbers");
}
```

```
c++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` pybindtest.cpp -o pybindtest `python3-config --extension-suffix`
c++: error: .cpython-36m-x86_64-linux-gnu.so: No such file or directory
```

To me it looks like it is looking in the incorrect directory for the Python dev package. Or I need to builld something additionally which I cannot figure out at this time. 

What am I missing in the install of this?

**Comment by YannickJadoul** [comment]
Nope. You're not following the docs correctly: 
```
c++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` pybindtest.cpp -o pybindtest`python3-config --extension-suffix`
```

should do the trick. Interpret what this line is doing and mind the whitespace.
