### ISSUE TITLE
Minor release 1.7.1?

### ISSUE THREAD

**Issue by SylvainCorlay** [pybind/pybind11#239]
It would be convenient to have a minor release including #194. Although the current master branch has some backward incompatible changes such as the removal of `class_.alias`... Is the current branch supposed to become a 2.0?

**Comment by wjakob** [comment]
I'll probably make a new major release 1.8 from the current master (which also includes a bunch of other desirable improvements). If all goes well, the main new change for 2.0 will be support for C++ multiple inheritance which Boris Schäling is working on.

I might have to ping you for details on how to trigger the build for the new conda build system.

**Comment by SylvainCorlay** [comment]
ok thanks, would be great to follow semver for API breakage!

**Comment by wjakob** [comment]
Hmm, I would consider it. So semver would entail pushing out the list of non-breaking change as 1.8, and 2.0 would be 1.8 plus the breaking change?

**Comment by SylvainCorlay** [comment]
So semver is `Major.minor.patch`

 - Major: potentially backward incompatible
 - minor: new feature, backward compatible
 - patch: minor bug fixes.

Exceptions to this which will not concern you

 - Before `Major` is 1, that is in `0.m.p` version, any change in `m` can be backward incompatible
 - Before the very first minor is 1, that is `0.0.p`, any change in `p` can be backward incompatible (pure develop mode)

In python, version requirement operators are specified here:
    https://www.python.org/dev/peps/pep-0440/

In node, it is here
    https://github.com/npm/node-semver

**Comment by SylvainCorlay** [comment]
> So semver would entail pushing out the list of non-breaking change as 1.8, and 2.0 would be 1.8 plus the breaking change?

Yes, I guess so. If you want to make frequent breaking changes, it would have been more convenient to not release 1.0, so that any 0.x could be breaking.

Besides, having a three-numbers version number M.m.p is sort of becoming the norm.

**Comment by wjakob** [comment]
Good point about 0.x, but it's too late for that now :)

So it would probably make sense to have a "future 2.0" branch which will accumulate the breaking changes for an eventual 2.0 release.

One thing I'm wondering then is how to organize the git branches for a 1.8 release. For instance, the current master branch has a bunch of non-breaking changes and one incompatible one (but in no particular order). I could rewrite history now to move the incompatibility-introducing commit to a different branch, but I suppose that is generally loathed upon.  Making separate "future 1.8" and "future 2.0" branches that cherry-pick from master is perhaps problematic as well.

Thoughts?

**Comment by SylvainCorlay** [comment]
I think that it would be fine to make a 1.8 release from master try to follow semver after that.

**Comment by dean0x7d** [comment]
Please don't rewrite git history, you'll bring the wrath of the internet down upon you :)
I think it would be best to leave the current master as the 2.0 branch, unchanged. For 1.8, branch from master, then `git revert` the breaking commits and fix any revert conflicts. IMHO this should be even simpler and less error-prone than rewriting history.

BTW For the breaking release, please consider also removing the deprecated [call function](https://github.com/pybind/pybind11/blob/b4dcb8f200895e4c2158cd0d06781488609dd9f4/include/pybind11/pytypes.h#L43-L44). In `-std=c++11` mode, it yields a warning even if it isn't used.

**Comment by wjakob** [comment]
ok, sounds good to me.

**Comment by SylvainCorlay** [comment]
>  For 1.8, branch from master, then git revert the breaking commits and fix any revert conflicts. IMHO this should be even simpler and less error-prone than rewriting history.

No need for that, just branch from before the first breaking commit, and backport later changes we may want in 1.8.

**Comment by wjakob** [comment]
I think it might actually be easier to revert that commit -- I don't expect any conflicts (a number of cherry-picks would be necessary in the other case)

**Comment by SylvainCorlay** [comment]
I guess, if it is the only backward incompatible change!

**Comment by wjakob** [comment]
Ok, done. I updated the feedstock repository as well.
