### ISSUE TITLE
[BUG] CMP0069

### ISSUE THREAD

**Issue by rongrong1314** [pybind/pybind11#2406]
Hi, when I using the latest pybind11 master commit in one of my projects, I get the following error:

**CMake Error at /opt/cmake-3.10.3-Linux-x86_64/share/cmake-3.10/Modules/CheckIPOSupported.cmake:138 (message):
  Policy CMP0069 is not set
Call Stack (most recent call first):
  /usr/local/share/cmake/pybind11/pybind11Tools.cmake:189 (check_ipo_supported)
  CMakeLists.txt:34 (pybind11_add_module)**

My camke version is  3.10, python is 3.8.
I tried to upgrade cmake , but it didn't work.

**Comment by henryiii** [comment]
Being fixed in #2370.

**Comment by henryiii** [comment]
By the way, if you increase you CMake polices, this will work without the fix:

```cmake
cmake_minimum_required(VERSION 3.4...3.18)
```
