### ISSUE TITLE
fail to include boost 

### ISSUE THREAD

**Issue by HiLiHeYi** [pybind/pybind11#2415]
I have boost installed in my system but pybind shows me every time file not found. ` #include <boost/progress.hpp>` this is how I include the file. Do I have to do some extra steps to include boost ?

**Comment by YannickJadoul** [comment]
As far as I know, Boost is only needed for running the tests (do update to the latest `master` commit (or the v2.5.0 release), please; an issue concerning the test configuration when using pybind11 as subproject fixed yesterday). So are you trying to do that, or do you just want to use pybind11?

Boost is detected by CMake using `FindBoost: https://cmake.org/cmake/help/latest/module/FindBoost.html, so I'd look into that, and maybe add your own call to that.

Apart from that, it's hard to say anything useful, without a more detailed description of your setup. How does your project look like? What's in `CMakeLists.txt`?

**Comment by HiLiHeYi** [comment]
I use pybind11 to translate a c++ project to a python api and I started using pybind11 couple days ago.
I include those boost bibs in my header file `config.h`
`#include <boost/progress.hpp>
#include <boost/filesystem.hpp>
`

my `CMakeLists.txt is` has the following sctrucutre 
`cmake_minimum_required(VERSION 2.8.12)
project(cmake_example)
add_subdirectory(pybind11)
find_package(Boost REQUIRED)
pybind11_add_module(cmake_example src/topk.cpp  src/graph.h src/config.h src/mylib.h  src/query.h )
`


I get the error  `fatal error: 'boost' file not found
  #include<boost/progress.hpp>,` although I installed boost and it works for a normal c++ project with boost without pybind11.

**Comment by YannickJadoul** [comment]
That's probably because you haven't added the Boost include directories to the CMake target. See here: https://cmake.org/cmake/help/latest/module/FindBoost.html

Closing, as this is not a pybind11 error. Feel free to ask more questions if the above doesn't work, though.
