### ISSUE TITLE
[FEAT] PYBIND11_EMBEDDED_MODULE declaration

### ISSUE THREAD

**Issue by codeschlosser** [pybind/pybind11#2416]
Consider a case (tested with Visual C++ @ Windows 10 x64):
StaticLibrary.lib:
someclass.h - C++ class
expose.cpp - contains PYBIND11_EMBEDDED_MODULE(exposed, m) { exposing the class to module

Binary (statically links StaticLibrary.lib):
main.cpp - main() which calls py::module::import("exposed")

Such layout results in ModuleNotFound, but if I write a declaration 
<pre>extern pybind11::detail::embedded_module pybind11_module_exposed;</pre>
and minimally refer it
<pre>if (&pybind11_module_exposed == nullptr) return 0;</pre>
then import works

AFAIK it's because C++ is allowed to exclude objects that are not referenced.

Is there a way to declare and refer to PYBIND11_EMBEDDED_MODULE from the box without intruding `detail` namespace?

**Comment by bstaletic** [comment]
For starters, try turning LTO off.

**Comment by codefables** [comment]
Yes, turning off optimizations helps, but the question is if there is way to handle such cases in general

**Comment by YannickJadoul** [comment]
Wait, even if the constructor has side-effects, C++ is allowed to omit it? That seems ... weird?

**Comment by bstaletic** [comment]
If by sideeffects you mean `malloc` and `free`, sure.

**Comment by arsdever** [comment]
Just stumbled across the same issue. I want to have my `c++` interface exposed in a single compile unit, but import and use the module in another unit, but this doesn't work. 

> `extern pybind11::detail::embedded_module pybind11_module_exposed;`
> and minimally refer it
> 
> `if (&pybind11_module_exposed == nullptr) return 0;`
> then import works

This also didn't work. Even tried to assign it to a variable.

Any other solution found so far?
