### ISSUE TITLE
Named parameters for callbacks

### ISSUE THREAD

**Issue by bradharmon** [pybind/pybind11#242]
Pybind11 has worked wonders for a project I'm working on.  Thanks for the hard work!

I have been unable to determine if it is possible to have named parameters for callbacks whose implementation is in C++.  For example, `example5.py` does the following at the very end:

```
f = test_callback4()
print("func(43) = %i" % f(43))
```

Is there any way to implement named parameters on the C++ side like the following:
```
f = test_callback4()
print("func(43) = %i" % f(number=43))
```

**Comment by wjakob** [comment]
You will have to create a ``py::cpp_function`` in your test callback and return it. The arguments to ``cpp_function`` are exactly the same as ``class_::def``, so you can use ``py::arg``, etc.

**Comment by bradharmon** [comment]
Awesome.  I figured it had to do something with `py::cpp_function`, but I wasn't quite sure about how to use it.  Mind if I submit a PR to update examples and docs with this info?

**Comment by wjakob** [comment]
That would be super-nice of you!

**Comment by bradharmon** [comment]
As soon as I get it working myself I'll write it up.  Thanks again.
