### ISSUE TITLE
Loading .pyd file created with pybind11

### ISSUE THREAD

**Issue by NashPant** [pybind/pybind11#2443]
Hi there,
i'm struggling a bit to understand what i'm i missing.
1) i've started a standardalone pybind11 visual studio c++17 project to export the toy functions that are there and it works fine. I can do "import *.pyd" and i can see the functions
2) then i link it against my project (which is a standard dll project) and it links fine and it creates the *.pyd file again. However when i try to load from python the *.pyd file i get 
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

I've checked dependencies and it can see the link to my library(which is using quite a bit of boost ).
Any pointers please where to look and any tips how to resolve would be greatly appreciated.

Regards
Nash

**Comment by YannickJadoul** [comment]
[Dependency Walker](http://www.dependencywalker.com/) is normally pretty good to figure out what DLLs are not resolved?

Apart from that, there's not a lot we can say about this without more details. I don't think any current maintainer is a very regular Windows user.
Given that this isn't really a pybind11-specific question (you mention that a simple pybind11 library does work, right), I'd expect this might get more and better replies on e.g. StackOverflow than here between the pybind11 issues.

**Comment by NashPant** [comment]
Thank you for your suggestion.
I thought i'll post it here in case that is a standard issue when linking pybind11 to other libraries.

**Comment by NashPant** [comment]
I've found the issue at the end and thought to share it just in case someone else is experiencing similar problem.
It was an ill-formed std::regex defined in a cpp file. Although never used and never called anywhere (that's why it compiled and linked) somehow when importing the resulting *pyd file that was produced with pybind11 every cpp source code was checked and prevented the dll to be loaded. Strange one! Was relatively painless, only a couple of days of sleepless nights

**Comment by YannickJadoul** [comment]
Seems rather weird that that was/solved the issue, but good that it worked. Thanks for reporting how you solved it.

I'll close this now.
