### ISSUE TITLE
[QUESTION] Can pybind11 be used with JIT compilation ?

### ISSUE THREAD

**Issue by pfeatherstone** [pybind/pybind11#2444]
Can pybind11 be used with JIT compilation?
[Pytorch](https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.load) does this, but is there a way of doing this without the pytorch tools?

**Comment by YannickJadoul** [comment]
If you write a function that calls a compiler or `setuptools`, sure.

As you can see in the docs, pybind11 currently just provides the headers (and CMake/setuptools to do this), without any additional tools.

**Comment by pfeatherstone** [comment]
Just noticed cppimport. That pretty much what I'm looking for. I apologize for not reading the docs carefully enough.

**Comment by YannickJadoul** [comment]
Oh, I'd forgotten about that page with external tools, as well, indeed!
Also, @henryiii is creating some IPython magic, I believe.

**Comment by henryiii** [comment]
After #2433, I have a branch ready building on that to add an IPython magic, yes, nearly identical to `%%cython` but for pybind11. I just started looking at cppimport's implementation this morning, and might add further updates to `setup_helpers` in the future inspired by that.
