### ISSUE TITLE
Print / repr: Call C++ Method

### ISSUE THREAD

**Issue by nyckmaia** [pybind/pybind11#2447]
I found this example below in the Pybin11 documentation.

```
py::class_<Pet>(m, "Pet")
    .def(py::init<const std::string &>())
    .def("getName", &Pet::getName)
    .def("__repr__",
        [](const Pet &a) {
            return "<example.Pet named '" + a.name + "'>";
        }
    );
```

I would like to call a C++ method inside the lambda function.
Something like that:
```
py::class_<Pet>(m, "Pet")
    .def(py::init<const std::string &>())
    .def("getName", &Pet::getName)
    .def("__repr__",
        [](const Pet &a) {
            return a.getName();
        }
    );
```
But I got this compile time error:
```
error: passing ‘const Pet’ as ‘this’ argument discards qualifiers [-fpermissive]
```
**How can I fix it?**

**Comment by bstaletic** [comment]
By being const-correct with respect to member function qqualifiers.
https://en.cppreference.com/w/cpp/language/member_functions#const-_and_volatile-qualified_member_functions
