### ISSUE TITLE
[QUESTION] Scipy sparse matrix, EIGEN sparse and vector of vectors

### ISSUE THREAD

**Issue by MonkeyBreaker** [pybind/pybind11#2450]
Hello pybind11 community !

I'm encountering a behaviour that I'm not pretty sure it expected or if there's an easy workaround.

Let's take this simple example:

```cpp
#include <pybind11/eigen.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

using Sparse_matrix = Eigen::SparseMatrix<float>;
using Distance_matrix = std::vector<std::vector<float>>;

PYBIND11_MODULE(example, m) {
    m.def("test", [](Sparse_matrix& sparse) { std::cout << "sparse\n"; });
    m.def("test", [](Distance_matrix& dm) { std::cout << "dense\n"; });
}
```

Then, from python, testing this:

```python
import numpy as np
import scipy as sp
from example import test

X = sp.sparse.coo_matrix(([1., 1., 1., 1., 2., 2.], ([0, 1, 2, 3, 0, 1], [1, 2, 3, 0, 2, 3])))
test(X) # prints: sparse
test(X.toarray()) # prints: sparse
```

What I don't know is if it's expected behavior that when converting X from COO format to array format (array of array), it's not the function taking the `Distance_matrix` that should be call but the one with `Sparse_matrix` input ?

Please, let me know if I'm totally wrong in my assumptions and if there's a way with pybind11 to differentiate a sparse matrix format from `scipy` and a vector of vector. 

Thank you soo much for the amazing work :),
Julián

**Comment by bstaletic** [comment]
Hi. I have zero clue about scipy, but I think I know what's going on. Try reversing the order of overloads and test again. If I'm right, it will print `dense\n` both times.

**Comment by MonkeyBreaker** [comment]
I would have expect as you @bstaletic, but it's interesting, if I reverse the declaration order in the bindings I get the following results:

```bash
sparse
dense
```

Seems like an inconsistency or maybe the `sparse` input is more permissive on the data types.

**Comment by bstaletic** [comment]
> or maybe the sparse input is more permissive on the data types.

This is my guess. Basically, pybind isn't too smart about runtime overload resolution. It will pick the first mentioned overload that happens to work. In your case, seems like `Eigen::SparseMatrix` can be constructed from `coo_matrix().to_array()`. You might want to look into `stl_bind.h` and `py::bind_vector()`.

**Comment by MonkeyBreaker** [comment]
Sorry for not giving any answer, I was quite busy last week.

I tried to understand and look better about `stl_bind.h` and `py::bind_vector()`, but I'm not sure what I should have found.
Another idea I got was to try doing a sort of intermediate opaque class for the sparse input, without any success.

At the moment, what we have done is to name the functions differently depending on the input type.

What I would like to have, is the same function name for the different input types. But if in this case, it's not possible to obtain this behaviour, I can live with the current solution and we can close this issue.

PS: `coo_matrix().to_array()` in our case produces `[[],[],[], etc.]`
PSS: [scipy.issparse](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.issparse.html) is a python function that we use to differentiate  between a sparse input and an array of array input. I don't know if this could help for the runtime overload resolution ?

**Comment by bstaletic** [comment]
`stl_bind.h` and `bind_vector` allow you to create bindings for list-like types, but no `py::list`, because these have special types, just like anything that uses `py::class_`. That could disambiguate the overloads further. However, I don't know how well it works with 2D vectors. Also, reordering overloaded bindings so that the most specialized is first would be a good idea anyway.

You can also have a single overload and manually cast and dispatch.

**Comment by MonkeyBreaker** [comment]
I tried playing with bindings like I found in the [documentation](https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#stl-bind) without much success, I dunno if you have maybe other examples ? (I could of course have made a mistake)

However reordering the bindings works like a charm, but after discussing internally, this option is a no-no for us (for others it could be enough).

The single overload and manually dispatching could be a good option, I'll try to have a look on it but I don't know if I will spend more time on the issue.

Thank you for the help :), I think that the issue can be closed, I'll let you decide

**Comment by bstaletic** [comment]
> I tried playing with bindings like I found in the documentation without much success, I dunno if you have maybe other examples ? (I could of course have made a mistake)

Here's what works for 2D vector:

```c++
void f(std::vector<std::vector<int>>){}
PYBIND11_MODULE(foo, m) {
	pybind11::bind_vector<std::vector<int>>(m, "IntVector");
	pybind11::bind_vector<std::vector<std::vector<int>>>(m, "VVectorInt");
	m.def("f", f);
}
```

```
>>> import foo
>>> matrix = foo.VVectorInt()
>>> vi = foo.IntVector()
>>> vi.append(1)
>>> matrix.append(vi)
>>> foo.f(ma
>>> foo.f(matrix)
```
