### ISSUE TITLE
[QUESTION] There is a error when push back a py::buffer_info object to vector. How to deal with it?

### ISSUE THREAD

**Issue by Liu-SD** [pybind/pybind11#2453]
My test code is like that:
```
void buffer_info_demo(py::buffer_info bi) {
    std::vector<py::buffer_info> vec;
    vec.push_back(bi);
}
```

Error message says:

> In file included from /usr/include/x86_64-linux-gnu/c++/7/bits/c++allocator.h:33:0,
>                  from /usr/include/c++/7/bits/allocator.h:46,
>                  from /usr/include/c++/7/bits/forward_list.h:40,
>                  from /usr/include/c++/7/forward_list:38,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/detail/common.h:143,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pytypes.h:12,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/cast.h:13,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/attr.h:13,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pybind11.h:44,
>                  from src/pybind.cpp:1:
> /usr/include/c++/7/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = pybind11::buffer_info; _Args = {const pybind11::buffer_info&}; _Tp = pybind11::buffer_info]’:
> /usr/include/c++/7/bits/alloc_traits.h:475:4:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = pybind11::buffer_info; _Args = {const pybind11::buffer_info&}; _Tp = pybind11::buffer_info; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<pybind11::buffer_info>]’
> /usr/include/c++/7/bits/stl_vector.h:943:30:   required from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = pybind11::buffer_info; _Alloc = std::allocator<pybind11::buffer_info>; std::vector<_Tp, _Alloc>::value_type = pybind11::buffer_info]’
> src/pybind.cpp:10:21:   required from here
> /usr/include/c++/7/ext/new_allocator.h:136:4: error: use of deleted function ‘pybind11::buffer_info::buffer_info(const pybind11::buffer_info&)’
>   { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pytypes.h:13:0,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/cast.h:13,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/attr.h:13,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pybind11.h:44,
>                  from src/pybind.cpp:1:
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/buffer_info.h:61:5: note: declared here
>      buffer_info(const buffer_info &) = delete;
>      ^~~~~~~~~~~
> In file included from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/attr.h:13:0,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pybind11.h:44,
>                  from src/pybind.cpp:1:
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/cast.h: In instantiation of ‘Return pybind11::detail::argument_loader<Args>::call_impl(Func&&, std::index_sequence<Is ...>, Guard&&) && [with Return = void; Func = void (*&)(pybind11::buffer_info); long unsigned int ...Is = {0}; Guard = pybind11::detail::void_type; Args = {pybind11::buffer_info}; std::index_sequence<Is ...> = std::integer_sequence<long unsigned int, 0>]’:
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/cast.h:1959:9:   required from ‘std::enable_if_t<std::is_void<_Yp>::value, pybind11::detail::void_type> pybind11::detail::argument_loader<Args>::call(Func&&) && [with Return = void; Guard = pybind11::detail::void_type; Func = void (*&)(pybind11::buffer_info); Args = {pybind11::buffer_info}; std::enable_if_t<std::is_void<_Yp>::value, pybind11::detail::void_type> = pybind11::detail::void_type]’
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pybind11.h:159:43:   required from ‘pybind11::cpp_function::initialize(Func&&, Return (*)(Args ...), const Extra& ...)::<lambda(pybind11::detail::function_call&)> [with Func = void (*&)(pybind11::buffer_info); Return = void; Args = {pybind11::buffer_info}; Extra = {pybind11::name, pybind11::scope, pybind11::sibling}]’
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pybind11.h:137:22:   required from ‘struct pybind11::cpp_function::initialize(Func&&, Return (*)(Args ...), const Extra& ...) [with Func = void (*&)(pybind11::buffer_info); Return = void; Args = {pybind11::buffer_info}; Extra = {pybind11::name, pybind11::scope, pybind11::sibling}]::<lambda(struct pybind11::detail::function_call&)>’
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pybind11.h:137:19:   required from ‘void pybind11::cpp_function::initialize(Func&&, Return (*)(Args ...), const Extra& ...) [with Func = void (*&)(pybind11::buffer_info); Return = void; Args = {pybind11::buffer_info}; Extra = {pybind11::name, pybind11::scope, pybind11::sibling}]’
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pybind11.h:64:9:   required from ‘pybind11::cpp_function::cpp_function(Return (*)(Args ...), const Extra& ...) [with Return = void; Args = {pybind11::buffer_info}; Extra = {pybind11::name, pybind11::scope, pybind11::sibling}]’
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pybind11.h:819:22:   required from ‘pybind11::module& pybind11::module::def(const char*, Func&&, const Extra& ...) [with Func = void (*)(pybind11::buffer_info); Extra = {}]’
> src/pybind.cpp:17:48:   required from here
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/cast.h:1982:37: error: use of deleted function ‘pybind11::buffer_info::buffer_info(const pybind11::buffer_info&)’
>          return std::forward<Func>(f)(cast_op<Args>(std::move(std::get<Is>(argcasters)))...);
>                 ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pytypes.h:13:0,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/cast.h:13,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/attr.h:13,
>                  from /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/pybind11.h:44,
>                  from src/pybind.cpp:1:
> /home/liu/rl-arch/.eggs/pybind11-2.5.0-py3.7.egg/pybind11/include/pybind11/buffer_info.h:61:5: note: declared here
>      buffer_info(const buffer_info &) = delete;
>      ^~~~~~~~~~~
> error: command 'gcc' failed with exit status 1

**Comment by bstaletic** [comment]
Buffer info isn't copyable. Try moving bi instead.

**Comment by Liu-SD** [comment]
Solved, thank!
