### ISSUE TITLE
[BUG] std::function return types aren't distinguished when used as binding input arguments

### ISSUE THREAD

**Issue by jacobkahn** [pybind/pybind11#2457]
It looks like overload resolution for bindings taking `std::function<T...>` as an argument doesn't distinguish return type.

### Setup

Define a few functions that differ only in return types:
```c++
void myFunc1(int i) {
  std::cout << i << std::endl; // do anything really
}

int myFunc2(int i) {
  return i + 1;
}
```

Bind them [minimally]:
```c++
...
m.def("myFunc1", myFunc1);
m.def("myFunc2", myFunc2);
...
```

Create a binding which has overloads for different `std::function`s and call them. The functions
they accept have different output types:
```c++
// elsewhere
...
m.def("some_func_operation", 
  [](const std::function<void(int)>& func, int i) -> void { func(i); } );
m.def("some_func_operation",
  [](const std::function<int(int)>& func, int i) -> int { func(i); } );
...
```

### Problem -
In Python, if I call:
```python
m.some_func_operation(m.myFunc1, 43)
```
(or with `m.myFunc2`), either both `some_func_operation` bindings will be called, or the first binding will called regardless of the order in which the bindings are defined (which is how overload resolution in pybind would proceed) — usually, both overloads are called.

This also repros when moving the lambdas used above into standalone functions and using those in the binding, even with `py::overload_cast` to distinguish between them, i.e:
```c++
myVoidReturner(const std::function<void(int)>& func, int i) {
  func(i);
}

myIntReturner(const std::function<int(int)>& func, int i) {
  func(i);
}

m.def("some_func_operation", py::overload_cast<const std::function<void(int)>& func, int i, >(&myVoidReturner));
m.def("some_func_operation", py::overload_cast<const std::function<int(int)>& func, int i>(&myIntReturner));
```

Which makes me think something is wrong with return type deduction here. Is overloading with the return type of bound `std::function` arguments supposed to be valid? `std::function<T...>` should be a complete type.

**Comment by bstaletic** [comment]
> either both some_func_operation bindings will be called, or the first binding will called regardless of the order in which the bindings are defined

This makes zero sense. For starters, pybind version 2.5.0 works for me with the following code:

```c++
#include <functional>
#include <iostream>
#include <pybind11/pybind11.h>
#include <pybind11/functional.h>
void myFunc1(int i) {
  std::cout << i << std::endl; // do anything really
}

int myFunc2(int i) {
  return i + 1;
}

PYBIND11_MODULE(foo,m) {
        m.def("myFunc1", myFunc1);
m.def("myFunc2", myFunc2);
m.def("some_func_operation",
  [](const std::function<void(int)>& func, int i) -> void { func(i); } );
m.def("some_func_operation",
  [](const std::function<int(int)>& func, int i) -> int { return func(i); } );
}
```

So please provide the exact steps to reproduce, including the compilable version of your code and the version/commit of pybind you are using.

**Comment by YannickJadoul** [comment]
Python, being dynamically typed, doesn't have return types or argument types. There's absolutely no way of taking an arbitrary Python function and knowing what it will return without calling it (or looking at the code, ofc).

So no, pybind11 provides a nice, convenient conversion from a Python function to `std::function`, but these types are not and cannot be checked, because of the difference in language between C++ and Python. I'm not sure, but I expect a runtime error to be thrown if the Python function passed as argument e.g. returns a `str` instead of `int`.

**Comment by jacobkahn** [comment]
@bstaletic — sorry about that - here are exact repro details.

> commit

This repros on 2.5.0 and master.

> exact steps

Here's a reliable repro (this is on macOS with Python 3.8.5 and Apple clang version 11.0.3):

C++:
```c++
#include <pybind11/functional.h>
#include <pybind11/pybind11.h>
#include <functional>
#include <iostream>

namespace py = pybind11;

void myFunc1(int i) {
  std::cout << i << std::endl; // do anything really
}

int myFunc2(int i) {
  return i + 1;
}

PYBIND11_MODULE(cmake_example, m) {
  m.def("myFunc1", myFunc1);
  m.def("myFunc2", myFunc2);
  m.def(
      "some_func_operation",
      [](const std::function<void(int)>& func, int i) -> void {
        std::cout << "void return overload" << std::endl;
        func(i);
      });
  m.def(
      "some_func_operation",
      [](const std::function<int(int)>& func, int i) -> int {
        std::cout << "int return overload" << std::endl;
        return func(i);
      });

#ifdef VERSION_INFO
  m.attr("__version__") = VERSION_INFO;
#else
  m.attr("__version__") = "dev";
#endif
}
```

Python:
```python
import cmake_example as m

# Verify everything works
m.myFunc1(4)
print(m.myFunc2(5))

# works fine
print("some_func_operation with myFunc1")
m.some_func_operation(m.myFunc1, 1)

# hangs - you can see that it also calls the wrong overload
# (it prints "void return overload")
print("some_func_operation with myFunc2")
m.some_func_operation(m.myFunc2, 2)
```

I created a tiny repro using the [Pybind CMake example](https://github.com/pybind/cmake_example). The C++ above goes into `main.cpp` and the Python above goes into `tests/test.py`. This is after:
```shell
git clone --recursive https://github.com/pybind/cmake_example.git
pip install ./cmake_example
```
as described in the `cmake_example` docs.

To repro, running:
```shell
python tests/test.py
```
Gives the following output:
```
4
6
some_func_operation with myFunc1
void return overload
1
some_func_operation with myFunc2
void return overload
```
before hanging and needing to be killed.

Calling `m.some_func_operation(m.myFunc2, 2)` should obviously resolve to the second overload and print `int return overload`, but that doesn't happen.

**Comment by jacobkahn** [comment]
@YannickJadoul — that's a good point, although my impression was based on the `callback_test` ([C++](https://github.com/pybind/pybind11/blob/master/tests/test_callbacks.cpp), [Python](https://github.com/pybind/pybind11/blob/master/tests/test_callbacks.py)) was that the Python function would resolve to the C++ function pointer - both `myFunc1` and `myFunc2` should do that, so type resolution in the `some_func_operation` bindings should work ok. Maybe that resolution happens in some order which is problematic.

**Comment by bstaletic** [comment]
Thanks for providing a clearer example. @YannickJadoul is right though. Notice that the bindings in those tests aren't creating overloads. Rather they have `test_overload1` through `test_overload5`. Your example would be as if `test_overload1` and `test_overload2` were both called the same, which would break the tests.

**Comment by YannickJadoul** [comment]
Seems @bstaletic is right, there? That's also consistent with what I told. I think you might want to consider a slight redesign of this Python interface, then. Again, we have no way of determining the return value of any function.

> before hanging and needing to be killed.

That shouldn't happen, though. That does sound like a bug. I'd like to see some kind of `py::cast_error` getting called or so.

**Comment by bstaletic** [comment]
> hanging

That wasn't observed when I tested the example. It consistently picked the first-registered overload, finished and errored when the overload order got reversed.

@jacobkahn You could take a `py::object` and examine it with `inspect` before dispatching manually. Though that's quite awkward.

**Comment by YannickJadoul** [comment]
> That wasn't observed when I tested the example. It consistently picked the first-registered overload, finished and errored when the overload order got reversed.

OK, weird. Can you figure out why yours doesn't, then, @jacobkahn? Because if we can't reproduce the error, there's nothing to solve, and we can only close this issue, I guess :-/

**Comment by jacobkahn** [comment]
@YannickJadoul — not sure I can provide any additional details on reproduction on macOS that I haven't already, so I suppose I'll close this. Thanks for the clarity on return type resolution/how that can't be done.

A tiny piece of feedback: I suppose it's not clear that this can't be done from any documentation or a demonstrative test (although there isn't really anything to test).

Thanks again for both of your insights.

**Comment by YannickJadoul** [comment]
> A tiny piece of feedback: I suppose it's not clear that this can't be done from any documentation or a demonstrative test (although there isn't really anything to test).

That might be true, yes! We're open for a tiny PR, if you feel like it :-) Otherwise it might just get added next time someone updates that part of the docs.
