### ISSUE TITLE
QString doesn't work in debug mode

### ISSUE THREAD

**Issue by KerimMatlab** [pybind/pybind11#2458]
Hi,
I'm the very beginner. I work on Windows 10 x64 with Qt 5.14.2
I'm trying to bind my simple C++ class in python. 

**pyclass_d.h**
```cpp
#ifndef PYCLASS_D_H
#define PYCLASS_D_H

#include "pyclass_d_global.h"
#include <pybind11/pybind11.h>

#include <QtCore>

class PYCLASS_D_EXPORT Pyclass_d
{
public:
    Pyclass_d(QString name);

    QString getName();
    void setName(QString name);

private:
    QString name;
};

#endif // PYCLASS_D_H
```
__________________________________________________________

**pyclass_d.cpp**
```cpp
#include "pyclass_d.h"


Pyclass_d::Pyclass_d(QString name) :
    name(name)
{
}

QString Pyclass_d::getName(){
    return this->name;
}
void Pyclass_d::setName(QString name){
    this->name = name;
}

namespace py = pybind11;

PYBIND11_MODULE(pyclass_d, m) {
    py::class_<Pyclass_d>(m, "Pyclass_d")
            .def(py::init<QString>())
            .def("setName", &Pyclass_d::setName)
            .def("getName", &Pyclass_d::getName);
}

PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

namespace pybind11
{
namespace detail
{
/* Create a TypeCaster for auto python string <--> QString conversion */
template <> struct type_caster<QString>
{
public:
    /**
* This macro establishes the name 'QString' in
* function signatures and declares a local variable
* 'value' of type QString
*/
    PYBIND11_TYPE_CASTER(QString, _("QString"));

    /**
*  @brief Conversion part 1 (Python->C++): convert a PyObject into a QString
* instance or return false upon failure. The second argument
* indicates whether implicit conversions should be applied.
* @param src
* @return boolean
*/
    bool load(handle src, bool)
    {
        if(!src)
        {
            return false;
        }
        object temp;
        handle load_src = src;
        if(PyUnicode_Check(load_src.ptr()))
        {
            temp = reinterpret_steal<object>(PyUnicode_AsUTF8String(load_src.ptr()));
            if(!temp) /* A UnicodeEncodeError occured */
            {
                PyErr_Clear();
                return false;
            }
            load_src = temp;
        }
        char* buffer = nullptr;
        ssize_t length = 0;
        int err = PYBIND11_BYTES_AS_STRING_AND_SIZE(load_src.ptr(), &buffer, &length);
        if(err == -1) /* A TypeError occured */
        {
            PyErr_Clear();
            return false;
        }
        value = QString::fromUtf8(buffer, static_cast<int>(length));
        return true;
    }

    /**
   * @brief Conversion part 2 (C++ -> Python): convert an QString instance into
   * a Python object. The second and third arguments are used to
   * indicate the return value policy and parent object (for
   * ``return_value_policy::reference_internal``) and are generally
   * ignored by implicit casters.
   *
   * @param src
   * @return
   */
    static handle cast(const QString& src, return_value_policy /* policy */, handle /* parent */)
    {
#if PY_VERSION_HEX >= 0x03030000 // Python 3.3
        assert(sizeof(QChar) == 2);
        return PyUnicode_FromKindAndData(PyUnicode_2BYTE_KIND, src.constData(), src.length());
#else
        QByteArray a = src.toUtf8();
        return PyUnicode_FromStringAndSize(a.data(), (ssize_t)a.length());
#endif
    }
};
}
}

```

In **release mode** this code is working in PyCharm. But when I turn it to **debug mode** I get the error:
_____________________________________________________
```py
 In[1] import pyclass_d as pb
Traceback (most recent call last):
  File "C:\Anaconda3\envs\MyEnv38\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-f81e1297da4f>", line 1, in <module>
    import pyclass_d as pb
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed while importing pyclass_d: Module not found.
```
_________________________________________________________________________________

By the way if I replace **QSting** to a **std::string** then the built .dll library normally works in PyCharm

P.S.: TypeCaster from QString I found here: [TypeCaster for auto python string <--> QString conversion](https://gist.github.com/imikejackson/d13a00a639271eb99379ebcc95d12424#file-gistfile1-cpp-L37)

**Comment by YannickJadoul** [comment]
We probably need to see your build script for that, and what files it creates and links to. If this code works, then it's the build process that's going to be important.

@bstaletic did reply this to you on Gitter: https://gitter.im/pybind/Lobby?at=5f5100fa49a1df0a12c72647
Did you see/read that?

**Comment by KerimMatlab** [comment]
@YannickJadoul Yes I saw answer of @bstaletic . Earlier I explicitly included **<Python.h>** but if I leave only these three lines:
```cpp
#include "pyclass_d_global.h"
#include <pybind11/pybind11.h>

#include <QtCore>  // include QtCore after <pybind11/pybind11.h>
```
then I can compile **.dll** library and by simply renaming it to **.pyd** I can run this library in PyCharm with following settings:

- if the mode is release then library can be used in PyCharm with any **QString** or **std::string**
- if the mode is debug then library can be used in PyCharm only with **std::string**

I tried to include the lines from the link in header file:
```cpp
#if defined(_MSC_VER)
#  if (PY_MAJOR_VERSION == 3 && PY_MINOR_VERSION < 4)
#    define HAVE_ROUND 1
#  endif
#  pragma warning(push)
#  pragma warning(disable: 4510 4610 4512 4005)
#  if defined(_DEBUG) && !defined(Py_DEBUG)
#    define PYBIND11_DEBUG_MARKER
#    undef _DEBUG
#  endif
#endif
```
but it doesn't change anything

My QMake (.pro file) is look like:
```
QT -= gui

TEMPLATE = lib
DEFINES += PYCLASS_D_LIBRARY

CONFIG += c++1z

DEFINES += QT_DEPRECATED_WARNINGS

TARGET = pyclass_d
win32:CONFIG(release, debug|release): DESTDIR = $$PWD/release
else:CONFIG(debug, debug|release): DESTDIR = $$PWD/debug

LIBS += C:\Anaconda3\envs\MyEnv38\libs\python38.lib

INCLUDEPATH += C:\apps\MSVC_apps_release\pybind11\include \
    C:\Anaconda3\envs\MyEnv38\include

DEPENDPATH += C:\apps\MSVC_apps_release\pybind11\include \
    C:\Anaconda3\envs\MyEnv38\include

HEADERS += \
    pyclass_d_global.h \
    pyclass_d.h

SOURCES += \
    pyclass_d.cpp
```
![image](https://user-images.githubusercontent.com/43808863/92180888-bd5cee80-ee50-11ea-88b2-0e90a8344d18.png)

**Comment by KerimMatlab** [comment]
@YannickJadoul here is zipped archive with my Qt project: 
[pyclass_d.zip](https://github.com/pybind/pybind11/files/5171768/pyclass_d.zip)

**Comment by YannickJadoul** [comment]
@KerimMatlab I don't see what's happening, from here. I'm not too familiar with qmake, either but the copying of a `dll` to `pyd` file feels a bit fishy. But maybe you're forgetting to copy another dependency along, if you're copying the resulting file?

Since you're on Windows, maybe have a look with [Dependency Walker](https://www.dependencywalker.com/) to check what dependencies you're missing in the resulting `pyd` file?

**Comment by KerimMatlab** [comment]
@YannickJadoul thank very much!
With dependency walker I've found out that I'm missing `Qt5Cored.dll`. I added it from my Qt dir/bin to Python prj folder and that is.
As I understood Python 3 doesn't look in `PATH` dir on Windows.

This was the first time when dependency walker helped me :) 
Earlier I couldn't understand how to use it in a way that it should be used...

**Comment by YannickJadoul** [comment]
Hmmm, but then Python needs specific filenames as well, sometimes, like `.cp38-win_amd64.pyd` for Python 3.8 on 64-bit Windows. QMake still doesn't seem the perfect way to do this; our CMake examples do take care of this. Up to you though, but at least you know.

At any rate, issue is resolved. So let's close it.

**Comment by Simran-B** [comment]
> As I understood Python 3 doesn't look in `PATH` dir on Windows.

Actually, it does until [Python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-the-python-api). From 3.8 on, it no longer searches the current working directory nor the paths in the PATH environment variable. Instead, you need to use `os.add_dll_directory()` in a Python script.
