### ISSUE TITLE
Feature request for exception translators

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#246]
Pybind11 nicely converts exceptions derived from `std::exception` into corresponding Python exceptions. However it does not currently seem to support custom exceptions. In Boost Python this functionality is provided by exception translators (http://www.boost.org/doc/libs/1_61_0/libs/python/doc/html/reference/high_level_components/boost_python_exception_translato.html).
What are your thoughts about adding equivalent functionality to pybind11?

**Comment by wjakob** [comment]
Hi,
I'm open to external contributions with this functionality (but it's not enough of a priority that I would go and implement it myself).
Thanks,
Wenzel

**Comment by pschella** [comment]
Hi Wenzel,

I understand. We do need this functionality and are willing to implement it.
In fact a first design is already available at https://github.com/lsst-dm/pybind11-1/tree/tickets/DM-6591-alternative
I would appreciate your feedback at this point although we will probably want to test it internally for a few weeks (possibly modifying it) before we submit a PR.

Regards,

Pim

**Comment by wjakob** [comment]
Dear Pim,

I just took a look and added one super-minor comment. This implementation looks very thoughtful (much nicer design than what I would have done), and I'd be happy to merge it into master when you think it's ready to go.

Best,
Wenzel

**Comment by pschella** [comment]
Dear Wenzel,

thank you for your comments. I have made the requested change and intend to submit a pull request after we verified it internally for our use case. I thus expect to submit it within the next few weeks.

Regards,

Pim Schellart

**Comment by wjakob** [comment]
Excellent, thank you -- I look forward to having this feature :)

**Comment by wjakob** [comment]
Hello Pim,

just a ping from my end -- is this sufficiently tested / ready to be merged?

Thanks,
Wenzel

**Comment by pschella** [comment]
Hi Wenzel,

yes I guess it is. We have been using it internally for a few things and it seems to hold up. I'll send an official pull request later today.

You might also be interested in https://github.com/lsst-dm/pybind11-1/pull/3/files. This is a proposed extension to allow exceptions to derive from Python's Exception type. Which allows them to be raised and caught with the standard `except Exception as e` syntax from Python.
This extension is still a bit rough around the edges and we have opted not to use it for LSST yet, instead relying on a workaround solution that calls back to Python with the C++ wrapped exception type to generate an equivalent Python exception which forwards to the embedded C++ type. This workaround, although less elegant, was chosen because the exceptions are nested in different trees on the C++ and Python side which would also necessitate multiple inheritance in pybind11 which I believe isn't supported.

But it might still be very relevant for other users. The main drawback in the current extension design is that it increases the size of every object by three pointers. These are strictly speaking only required for casting of exceptions but there is no good way to distinguish between object types and only insert them when needed. I tried using `enable_if` in `instance_essentials` but that creates troubles with weakrefs.
I might think about a better way to fix this if I have time, but don't expect anything there soon since it is not high priority for us.

Cheers,

Pim

**Comment by wjakob** [comment]
Regarding the other patch: adding three new PyObjects to instance_essentials (i.e. every object) to support exceptions indeed seems a bit excessive to me. You are right that multiple inheritance is not currently supported (though a patch with multiple inheritance support is currently in the works).
