### ISSUE TITLE
[QUESTION] How to make class hierarchy pickleable?

### ISSUE THREAD

**Issue by Time0o** [pybind/pybind11#2474]
I'm trying to implement `__getstate__` and `__setstate__` via `py::pickle` for a number of classes which share an abstract base class. This does however not seem to be possible the way I envisioned it and since from the documentation (and a quick look at the source code) it is not obvious to me why it shouldn't be, I'll try to present a minimal example showcasing my issue here. Apologies in advance in case I've just made a trvial error somehwere.

I started out with the following class hierarchy defined in `pickleable.hpp`:

```C++
#include <memory>
#include <string>

class PickleableBase
{
public:
  virtual std::string to_string() const = 0;
  static std::shared_ptr<PickleableBase> from_string(std::string const &str);
};

class PickleableImpl1 : public PickleableBase
{
public:
  std::string to_string() const override { return "1"; }
};

class PickleableImpl2 : public PickleableBase
{
public:
  std::string to_string() const override { return "2"; }
};

inline std::shared_ptr<PickleableBase> PickleableBase::from_string(std::string const &str)
{
  if (str == "1")
    return std::make_shared<PickleableImpl1>();
  else if (str == "2")
    return std::make_shared<PickleableImpl2>();
  else
    throw std::runtime_error("invalid argument");
}
```
and then added bindings in `pickleable.cpp`:

```C++
#include <memory>
#include <stdexcept>
#include <string>

#include <pybind11/pybind11.h>

#include "pickleable.hpp"

namespace py = pybind11;

PYBIND11_MODULE(pickleable, m)
{
  py::class_<PickleableBase,
             std::shared_ptr<PickleableBase>>(m, "PickleableBase")
      .def("to_string", &PickleableBase::to_string)
      .def_static("from_string", &PickleableBase::from_string)
      .def(py::pickle(
          [](PickleableBase const &self)
          { return self.to_string(); },
          [](std::string const &str)
          { return PickleableBase::from_string(str); }));

  py::class_<PickleableImpl1,
             PickleableBase,
             std::shared_ptr<PickleableImpl1>>(m, "PickleableImpl1")
    .def(py::init<>());

  py::class_<PickleableImpl2,
             PickleableBase,
             std::shared_ptr<PickleableImpl2>>(m, "PickleableImpl2")
    .def(py::init<>());
}
```
I would have expected this to enable me to e.g. do the following in Python:

```Python
import copy
import pickleable

p1 = pickleable.PickleableImpl1()
p1_deepcopy = copy.deepcopy(p1)
```
However, this fails with:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/timo/.pyenv/versions/3.7.0/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/timo/.pyenv/versions/3.7.0/lib/python3.7/copy.py", line 282, in _reconstruct
    y.__setstate__(state)
TypeError: __init__(self, ...) called with invalid `self` argument
```
i.e. somehow it is not possible to call `p1.__setstate__`. Is this expected behaviour? If so, is there another way I can make all classes inheriting from `PickleableBase` pickleable?

**Comment by EricCousineau-TRI** [comment]
As you prolly came across from the docs / source code:
https://pybind11.readthedocs.io/en/stable/advanced/classes.html#pickling-support
> ![image](https://user-images.githubusercontent.com/26719449/92812778-e66c0a80-f38d-11ea-801b-da91d4ef5d46.png)
Following that:
https://pybind11.readthedocs.io/en/stable/advanced/classes.html#custom-constructors

And basically, the code that gets invoked ends up here:
https://github.com/pybind/pybind11/blob/b47efd35fb436abe5c93db36b4ff5a1b5fdf593f/include/pybind11/pybind11.h#L1238-L1241
and uses `*this` to resolve `Class` to your immediate class, which is your base type:
https://github.com/pybind/pybind11/blob/b47efd35fb436abe5c93db36b4ff5a1b5fdf593f/include/pybind11/detail/init.h#L317-L331

So the static typing in this case (`PickleableBase`) is most likely defeating you.

Can you try repeating your `.def(py::pickle(...))` stanzas for your subclasses, and actually use the concrete subclass type (and put it in a function)? I'd assume that would work with the effective static type checks in place:

```cc
template <typename PyClass>
void PicklePlz(PyClass& cls) {
  using Class = typename PyClass::type;
  using Base = PickelableBase;
  static_assert(std::is_base_of_v<Class, Base>, "Boo");
  cls.def(py::pickle(
          [](Class const &self)  self.to_string(); },
          [](std::string const &str) {
            auto base = Base::from_string(str);
            auto downcast = std::dynamic_pointer_cast<Class>(base);
            return downcast;
          }));
}
...
py::class_<PickleableImpl1...> cls_1(m, "PickleableImpl1");
cls_1.def(py::init<>());
PicklePlz(cls_1);
```

**Comment by Time0o** [comment]
@EricCousineau-TRI  Thank you, that works. I was hoping to avoid the code duplication but it does make sense to me now that it would only work this way.

**Comment by YannickJadoul** [comment]
Thanks, @EricCousineau-TRI! Closing, as this seems solved.
