### ISSUE TITLE
How to bind lambda to def_property_readonly_static

### ISSUE THREAD

**Issue by abergmeier** [pybind/pybind11#248]
I have a lambda 

    .def_property_readonly_static("foo", []() {
        return Foo();
    })

When I try to access `foo` from Python, it complains that it wants to pass bindings class for `Foo` to the lambda. When I actually add it via:

    .def_property_readonly_static("foo", [](py::class_<Foo> const&) {
        return Foo();
    })

I get nasty template errors. Since the examples evade that function my question would be how to use it.

**Comment by aldanor** [comment]
Is this property meant to be bound to the `Foo` class itself? (i.e. `Foo::foo`?)

**Comment by aldanor** [comment]
I think you forgot the first argument (module), this compiles just fine:

```cpp
// m is the module
py::class_<Foo>(m, "Foo")
    .def_property_readonly_static("foo", []() { return Foo(); });
```

**Comment by wjakob** [comment]
I think this makes sense. If a normal property getter receives the instance as the implicit 'self' reference, then it should be the 'type' subclass instance for a static property getter.

If you take a look at the implementation of ``def_readonly_static``, you can see that it actually takes a py::object in the lambda function that acts as the property getter:
```c++
    template <typename D, typename... Extra>
    class_ &def_readonly_static(const char *name, const D *pm, const Extra& ...extra) {
        cpp_function fget([pm](object) -> const D &{ return *pm; }, scope(*this));
        def_property_readonly_static(name, fget, return_value_policy::reference, extra...);
        return *this;
    }
```
This could be a bit more explicit in the documentation though -- I will add a note.

**Comment by wjakob** [comment]
I added some text to the docs -- feel free to submit a PR for the tests if this is a priority for you.
