### ISSUE TITLE
Pybind11/CMake in a structured Project

### ISSUE THREAD

**Issue by johnathanchiu** [pybind/pybind11#2483]
Hello, I am not an expert in CMake and only understand the basics. I have been able to successfully compile the example in the docs but this is a simple CMake compilation.

I am trying to compile my code in another project using pybind11 but it keeps returning:

```
/ilqgames/exec/skeleton_example/main.cpp:63:10: fatal error: 'pybind11/pybind.h' file not found
#include <pybind11/pybind.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [exec/CMakeFiles/skeleton_example.dir/skeleton_example.dir/main.cpp.o] Error 1
make[1]: *** [exec/CMakeFiles/skeleton_example.dir/all] Error 2
make: *** [all] Error 2
```

The project in which I am trying to implement pybind into is: https://github.com/HJReachability/ilqgames. In specific, I have rewritten code in `exec/skeleton_example/main.cpp` (locally on my computer) to encapsulate python bindings. I copied the exact structure in the CMake file from the example into `exec/CMakeLists.txt` but this causes compile time errors. How should I modify the file(s) in `CMakeLists.txt` & `exec/CMakeLists.txt`?

**Comment by bstaletic** [comment]
Please don't delete the issue template instead of filling it in.

I don't see any mention of pybind11 in your cmake files. Also, you didn't specify which version of pybind are you trying to use. There have been a ton of differences between master and previous versions.

**Comment by johnathanchiu** [comment]
Not sure what you mean by issue template but let me know if what I updated on the original issue fixes that.

Anyways, all mentions of pybind are in my local repository and not pushed to the GitHub repo yet. I think my question is that given `ilqgames/CMakeLists.txt` & `ilqgames/exec/CMakeLists.txt` how can I modify them such that it'll allow me to compile `ilqgames/exec/skeleton_example/main.cpp` successfully. 

To specify, the version of pybind11 I am using is whatever is on the master branch, I cloned onto my computer 2 days ago into my root directory (same as where `ilqgames` is contained).

I also attached my modified `ilqgames/exec/CMakeLists.txt`. I made no changes to `ilqgames/CMakeLists.txt`
[CMakeLists.txt](https://github.com/pybind/pybind11/files/5220262/CMakeLists.txt)

**Comment by YannickJadoul** [comment]
> Not sure what you mean by issue template but let me know if what I updated on the original issue fixes that.

When you clicked "New issue" on GitHub, the issue was pre-filled with information to read and instructions on what information we're expecting.

**Comment by johnathanchiu** [comment]
I believe it says "after reading remove this checklist". Let me know if I did something wrong...

**Comment by bstaletic** [comment]
Have you read this page?

https://pybind11.readthedocs.io/en/latest/compiling.html#building-with-cmake

**Comment by johnathanchiu** [comment]
Yes I have. Like I said, I am not an expert in CMake. I believe I did it correctly in the CMake file I attached above. Please let me know if otherwise!

**Comment by YannickJadoul** [comment]
> I believe it says "after reading remove this checklist". Let me know if I did something wrong...

That's true. Just trying to say what I think @bstaletic meant, but in case of `[QUESTION]`, we have no real template, it seems...

**Comment by bstaletic** [comment]
One thing we don't know here is whether @johnathanchiu needs an extension module or wants to embed the interpreter. The former is what `pybind11_add_module` is for. For the latter, you want to use `target_link_libraries`.

**Comment by johnathanchiu** [comment]
@bstaletic I am just trying to create a python module from c++ using pybind11. I have been able to compile the example in the docs and import the example as a python module. I am trying to figure out how I can compile pybind11 in a structured project because what I tried compiling with my CMake file (listed above) just gives me that pybind11 header file cannot be found.

**Comment by henryiii** [comment]
It's called `pybind11/pybind11.h`, not `pybind11/pybind.h`.

**Comment by YannickJadoul** [comment]
Wow. OK. How did we ... ?

Thanks, @henryiii! With that said, let's close this.

**Comment by johnathanchiu** [comment]
Thanks for catching that @henryiii but still having file not found error

**Comment by YannickJadoul** [comment]
@johnathanchiu Please then follow exactly the example from the docs, and see where it diverges from your code. It will probably be something similar then. The minimal CMake example from the docs should work.

**Comment by johnathanchiu** [comment]
Sorry for slow response. Finally got a chance to take a look again today. I removed the code and am just trying to first compile the example from the docs inside the `exec` subdirectory (trying to learn a little more about CMake). The code compiles but I run into:

```
  File "test.py", line 1, in <module>
    import example
ImportError: dlopen(***/ilqgames/build/exec/example.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: ***/ilqgames/build/exec/example.so
  Expected in: flat namespace
 in ***/ilqgames/build/exec/example.so
```

Any ideas on this?

Here are my two CMakeLists.txt files. 
The first one is in the root directory of the project:

[CMakeLists.txt](https://github.com/pybind/pybind11/files/5251144/CMakeLists.txt)

 and the second one only has the line:
```
pybind11_add_module(example example.cpp)
```

**Comment by johnathanchiu** [comment]
I figured out that it was compiling the executable in python2.7. Is there a way to change it to python3.8?

**Comment by johnathanchiu** [comment]
Nvm. Resolved. Thanks for your help @henryiii @bstaletic @YannickJadoul!
