### ISSUE TITLE
[BUG] Compilation error on latest Visual Studio 19 because of module keyword

### ISSUE THREAD

**Issue by matthieucoquet** [pybind/pybind11#2488]
## Issue description
Related to https://github.com/pybind/pybind11/pull/1639 that wasn't merged.

Compilation fails because of the `module` keyword. In VS, modules are now activated when using `/std:c++latest`. 

```
1>...\include\pybind11/pybind11.h(837,5): error C2059: syntax error: 'module'
1>...\include\pybind11/pybind11.h(837,71): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>...\include\pybind11/pybind11.h(837,5): error C7586: a 'module' directive must end with a ';' on the same line
```

This compilation error currently happens only with the preview version of Visual Studio (VS 19 16.8.0 Preview 3.0).

[This blog post](https://devblogs.microsoft.com/cppblog/standard-c20-modules-support-with-msvc-in-visual-studio-2019-version-16-8/) talks about the recent update in Visual Studio.

VS compiler consider module as a keyword [only is it's at the beginning of the line](https://docs.microsoft.com/en-us/cpp/cpp/import-export-module?view=vs-2019#remarks). 
However, in the module class in pybind.h, there is one line with module at the beginning of the line:
```
module def_submodule(const char *name, const char *doc = nullptr)
{ ... }
```
My dirty fix to make it compile is just to add [[nodiscard]] to this function:
```
[[nodiscard]] module def_submodule(const char *name, const char *doc = nullptr)
```
Maybe a safer fix is to rename the class.

## Reproducible example code
Just including pybind11.h fails.
```
#include <pybind11/pybind11.h>
int main() { return 0; }
```

**Comment by bstaletic** [comment]
Does it help if you qualify `module` on that line? Change it to this:

    pybind11::module def_submodule(const char *name, const char *doc = nullptr)

If not, try *fully* qualifying it too.

    ::pybind11::module def_submodule(const char *name, const char *doc = nullptr)

**Comment by matthieucoquet** [comment]
Yes, both of these solutions work. Probably better than [[nodiscard]].

**Comment by bstaletic** [comment]
I don't have MSVC to test, so before I make a pull request, can you check the other places where `module` appears at the start of the line?

Here's the list of all hits:

```
bstaletic@Gallifrey pybind11  (git)-[overload_cast]-% rg '^\s*module\b' include tests --vimgrep
tests/test_embed/test_interpreter.cpp:281:1:    module.reload();
include/pybind11/embed.h:36:1:    module (without quotes). The second parameter is the variable which will
include/pybind11/embed.h:112:1:    module::import("sys").attr("path").cast<list>().append(".");
include/pybind11/numpy.h:225:1:        module m = module::import("numpy.core.multiarray");
include/pybind11/pybind11.h:884:1:    module &def(const char *name_, Func &&f, const Extra& ... extra) {
include/pybind11/pybind11.h:903:1:    module def_submodule(const char *name, const char *doc = nullptr) {
include/pybind11/detail/class.h:573:1:            module = rec.scope.attr("__module__");
include/pybind11/detail/class.h:575:1:            module = rec.scope.attr("__name__");
include/pybind11/detail/class.h:580:1:        module ? str(module).cast<std::string>() + "." + rec.name :
```

**Comment by matthieucoquet** [comment]
I compiled the `test_embed` project with `/std:c++latest` (to check test_interpreter.cpp), and include all the headers you mentions.

Only these two lines produce compilation errors:
```
include/pybind11/numpy.h:225:1:        module m = module::import("numpy.core.multiarray");
include/pybind11/pybind11.h:903:1:    module def_submodule(const char *name, const char *doc = nullptr) {
```
It works fine with `pybind11::module`.

**Comment by bstaletic** [comment]
I've submitted #2489. Feel free to join the discussion.

**Comment by SergeyJames** [comment]
The solution for me was to change my old CMake generator, which was - **"Visual Studio 14 2015 Win64"** to new - **"Visual Studio 15 2017 Win64"**.

```sh
cmake -G "Visual Studio 15 2017 Win64" ../
```
