### ISSUE TITLE
failed to cast std::array to py::array

### ISSUE THREAD

**Issue by timbad** [pybind/pybind11#249]
I want to cast std::array of strings to py::array or list and set it as an attribute of module. How can i do that?

I tried it the following way, but casting failed:
```C++
void init_some_info(py::module &main)
{
    auto m = main.def_submodule("arrays_info");
    std::array<std::string, ARR_TOTAL_NUM> array_names;
    std::copy(std::begin(c_array_names), std::end(c_array_names), std::begin(array_names));
    m.attr("d_pool_names") = py::cast(array_names);
}
```

And tried to define method that returns std::array:
```C++
void init_some_info(py::module &main)
{
    auto m = main.def_submodule("arrays_info");
    m.def("get_i_pool_names", [=]() {
        std::array<std::string, ARR_TOTAL_NUM> array_names;
        std::copy(std::begin(c_array_names), std::end(c_array_names), std::begin(array_names));
        return array_names;
      });
}
```
I expected automatic conversion as in example2, but pybind11 failed to convert std::array automatically.

Is there anything I missed or it is a bug in pybind11?

**Comment by wjakob** [comment]
Perhaps you did not include ``pybind11/stl.h``?

**Comment by timbad** [comment]
Yeah, I definitely forgot to include stl header. Thanks, that fixed my problem.

**Comment by wjakob** [comment]
Consider taking a look at the documentation next time ;)
