### ISSUE TITLE
Attempt to overload C++ functions that take parameters by reference lead to extra copy-constructor call's

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#250]
Hi Wenzel, I noticed that if i try to overload virtual functions that take parameter by-reference it does not work as expected: instead of receiving original parameters (the one that C++ function was called with) the Python version will receive copy of parameter instead. Curiously this does not happened when overloading function accepting parameter by-pointer. Such copy behavior is problematic in two ways: 

1. Copy operation could be expensive and 
2. It makes impossible for overloading function to modify supplied value (because it only can modify copy of it)

Is this something that could be fixed or current design does not permit it? If later: i found a workaround for this issue: during the Py-call-back definition we can just call macro and supply referenced parameter converted to pointer with `&` (see implementation of `test_ref_workaround` below). So perhaps it will be a good idea to mention this in the docs if there is no way to fix this?

Thank you,

Sergey.

```C++
#include <pybind11/pybind11.h>
#include <iostream>
#include <vector>

PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

class Value
{
public:
	Value(std::string s="unknown") { s_=s; }
	Value( Value const & src ) { std::cout << "Value Copy constructor! ["<< src.s_ << "]" << std::endl; }

	~Value() { std::cout << "Value destructor!  ["<< s_ << "]" << std::endl; }

	std::string s_;

	Value &operator=(const Value &v) {
		std::cout << "Value operator assign! ["<< v.s_ << "]" << std::endl;
		s_ = v.s_;
		return *this;
	}
};


class OverloadTest
{
public:
	Value value_;

	void self_test_ref() {
		std::cout << "Calling test_ref(Value &v)..." << std::endl;
		test_ref(value_);
		std::cout << "Calling test_ref(Value &v)... Done!" << std::endl;
	}

	void self_test_p() {
		std::cout << "Calling test_p(Value *v)..." << std::endl;
		test_p(&value_);
		std::cout << "Calling test_p(Value *v)... Done!" << std::endl;
	}

	void self_test_ref_workaround() {
		std::cout << "Calling test_ref_workaround(Value &v)..." << std::endl;
		test_ref_workaround(value_);
		std::cout << "Calling test_ref_workaround(Value &v)... Done!" << std::endl;
	}

	virtual void test_p(Value *v) {}
	virtual void test_ref(Value &v) {}
	virtual void test_ref_workaround(Value &v) {}
};


struct PyCallBack_OverloadTest : public OverloadTest {
	using OverloadTest::OverloadTest;

	using _binder_base_ = OverloadTest;

	void test_ref(class Value & a0) override { PYBIND11_OVERLOAD_NAME(void, _binder_base_, "test_ref", OverloadTest::test_ref, a0 ); }

	// Workaround: pretend that we getting pointer instead of reference, note that we pass '&a0' to macro...
	void test_ref_workaround(class Value & a0) override {
		PYBIND11_OVERLOAD_INT(void, "test_ref_workaround", &a0)
		return _binder_base_::OverloadTest::test_ref_workaround(a0);
	}

	void test_p(class Value * a0) override { PYBIND11_OVERLOAD_NAME(void, _binder_base_, "test_p", OverloadTest::test_p, a0); }
};


namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

	{
		pybind11::class_<Value> cl(m, "Value");
		pybind11::handle cl_type = cl;

		cl.def("__init__", [](Value *self_) { new (self_) Value(); });
		cl.def(pybind11::init<class std::basic_string<char>>(), pybind11::arg("s"));

		cl.def(pybind11::init<const class Value &>(), pybind11::arg("src"));

		cl.def_readwrite("s_", &Value::s_);
		cl.def("assign", &Value::operator=);
	}

	{
		pybind11::class_<OverloadTest, std::shared_ptr<OverloadTest>, PyCallBack_OverloadTest> cl(m, "OverloadTest");
		pybind11::handle cl_type = cl;

		cl.def(pybind11::init<>());
		cl.def(pybind11::init<PyCallBack_OverloadTest const &>());

		cl.def_readwrite("value_", &OverloadTest::value_);

		cl.def("self_test_p",              &OverloadTest::self_test_p);
		cl.def("self_test_ref",            &OverloadTest::self_test_ref);
		cl.def("self_test_ref_workaround", &OverloadTest::self_test_ref_workaround);

		cl.def("test_ref", &OverloadTest::test_ref);
		cl.def("test_p",   &OverloadTest::test_p);
	}

    return m.ptr();
}
```

```python
from __future__ import print_function

from example import *

class PyOverloadTest(OverloadTest):
    def __init__(self):
        OverloadTest.__init__(self)
        self.value_.s_ = '_py_'

    def test_p(self, v): print('PyOverloadTest.test_p({})'.format(v.s_))
    def test_ref(self, v): print('PyOverloadTest.test_ref({})'.format(v.s_))
    def test_ref_workaround(self, v): print('PyOverloadTest.test_ref_workaround({})'.format(v.s_))


print('OverloadTest Test -----------------------')
ot = OverloadTest()
ot.self_test_p()
ot.self_test_ref()

print('PyOverloadTest Test -----------------------------------------')

pot = PyOverloadTest()
print()
pot.self_test_p()
print()
pot.self_test_ref()
print()
pot.self_test_ref_workaround()
print()
```

And output (notice the extra `Value Copy constructor!` and destructor messages for _ref calls):
```
OverloadTest Test -----------------------
Calling test_p(Value *v)...
Calling test_p(Value *v)... Done!
Calling test_ref(Value &v)...
Calling test_ref(Value &v)... Done!

PyOverloadTest Test -----------------------------------------

Calling test_p(Value *v)...
PyOverloadTest.test_p(_py_)
Calling test_p(Value *v)... Done!

Calling test_ref(Value &v)...
Value Copy constructor! [_py_]
PyOverloadTest.test_ref()
Value destructor!  []
Calling test_ref(Value &v)... Done!

Calling test_ref_workaround(Value &v)...
PyOverloadTest.test_ref_workaround(_py_)
Calling test_ref_workaround(Value &v)... Done!

Value destructor!  [_py_]
Value destructor!  [unknown]
```

**Comment by wjakob** [comment]
The trouble with making this a general policy is that it's hard to say what is done with the parameters passed to a Python function called via handle::operator() (which is what is called by PYBIND11_OVERLOAD_NAME etc.). Maybe the Python function will store the value somewhere. If it's a C++ reference that goes out of scope when handle::operator() returns, the object will be deallocated and Python will reference an invalid instance.

Basically you need to tell pybind11 that you know what you're doing, and that the function arguments should only be referenced. This goes a bit beyond what the existing PYBIND11_OVERLOAD_* macros can do, so you'll have to instantiate the corresponding trampoline code yourself (and you'll need this latest commit: https://github.com/pybind/pybind11/commit/37e1f61f541681d755e3d3c81a3b3e6585a8aa23)

```cpp
py::gil_scoped_acquire gil;
pybind11::function overload = py::get_overload(this, "myFunction");
if (overload)
  return overload.operator()<py::return_value_policy::reference>(param1, param2, ...).cast<MyReturnType>();
  /* otherwise fail for pure virtual call or call c++ base class function */
}
```

**Comment by lyskov** [comment]
Great, thank you Wenzel! I agree that a more elaborate approach to reach 'unsafe' behavior probably a good thing here.

What about case of function arguments passed by-pointer and was not copied by default? Would not this surprise the user? (i.e. because it is different behavior from argument passed by-reference) I just checked the latests master and unless i missed something it looks like this still the case...

**Comment by wjakob** [comment]
Local variables that live in the current stack frame will be passed by reference when supplied to handle::call(). Since these expire immediately after the parent function returns, pybind11 would really set things up for a catastrophe if the default policy was to always reference things (even for lvalue references).

On the other hand, in many C++ codebases, pointers in function arguments are used to refer to things that are located on the heap, so the assumption is that the user is at least in some way aware of lifetime issues and will override the reference policy to something else if that is not intended.

There is no default policy that will make everyone happy (hence the ability to override things everywhere). This one is just my very subjective choice for what happens to work 99% in my own codebases ;)

**Comment by lyskov** [comment]
Re Local variables that live in the current stack frame will be passed by reference when supplied to handle::call()...: - not sure i a follow this: are you saying that code is detecting if variable variable is allocated on a heap vs. on-stack? If so, how? (thought there was no standard way to do so...)

**Comment by wjakob** [comment]
You encountered the issue that prompted this ticket via PYBIND11_OVERLOAD_*. But it really boils down to handle::operator() that occurs within this macro. The following situation in particular is scary:
```
{
   MyInstance inst = ...;
   py::handle a_python_function = ...;
   a_python_function(inst);
} /* Oops, 'inst' just disappeared. */
```

Of course the same can happen for function calls:
```
void myFunction(MyInstance inst) {
   py::handle a_python_function = ...;
   a_python_function(inst);
} /* Oops, 'inst' just disappeared. */
```

**Comment by lyskov** [comment]
Ah, i see what you mean, thank you for explaining this!

Re by-pointer: ok, so in that case, - can i count that in the future variables passed by-pointers will always be treated with py::return_value_policy::reference policy? I am asking because that way i can just use standard macros instead of generating the concrete code. Rational is that if pybind11 changes something in macro implementation my code will be ok, but if i generate my own version of code it will require an update etc.

**Comment by wjakob** [comment]
I guess that would work (passing via pointer) -- but doesn't this mean that you will need to change all virtual function calls in your existing codebase to take pointer arguments?

**Comment by lyskov** [comment]
No, not really: see the code in test_ref_workaround callback that i posted: it just added an `&` to argument to trick it to be a pointer - and no function signature changes require. (notice that test_ref_workaround have exactly the same signature in base class as test_ref :)

**Comment by wjakob** [comment]
Ah neat, via PYBIND11_OVERLOAD_INT. Yes that works. But be careful not to do that to an argument that's already a pointer.
Shall I close this ticket then?

**Comment by lyskov** [comment]
Yes, certainly! And thank you for all your help!

**Comment by garth-wells** [comment]
I can get this workaround to work for non-pure virtual functions, but not for pure virtual functions (missing symbol errors at runtime). Is there something else that needs to be added for pure virtual functions?

**Comment by lyskov** [comment]
@garth-wells here is the snippets from some of the self-test code that i use which might be helpful:

Say we need to bind code:
```C++
struct BBB {};

struct AAA
{
	virtual void foo(BBB &) {}
	virtual void pv_foo(BBB &) =0;
};
```

then bindings for call-back-structure will be:

```C++
struct PyCallBack_AAA : public utility::AAA {
	using utility::AAA::AAA;

	void foo(struct utility::BBB & a0) override { 
		pybind11::gil_scoped_acquire gil;
		pybind11::function overload = pybind11::get_overload(static_cast<const utility::AAA *>(this), "foo");
		if (overload) {
			auto o = overload.operator()<pybind11::return_value_policy::reference>(a0);
			if (pybind11::detail::cast_is_temporary_value_reference<void>::value) {
				static pybind11::detail::overload_caster_t<void> caster;
				return pybind11::detail::cast_ref<void>(std::move(o), caster);
			}
			else return pybind11::detail::cast_safe<void>(std::move(o));
		}
		return AAA::foo(a0);
	}
	void pv_foo(struct utility::BBB & a0) override { 
		pybind11::gil_scoped_acquire gil;
		pybind11::function overload = pybind11::get_overload(static_cast<const utility::AAA *>(this), "pv_foo");
		if (overload) {
			auto o = overload.operator()<pybind11::return_value_policy::reference>(a0);
			if (pybind11::detail::cast_is_temporary_value_reference<void>::value) {
				static pybind11::detail::overload_caster_t<void> caster;
				return pybind11::detail::cast_ref<void>(std::move(o), caster);
			}
			else return pybind11::detail::cast_safe<void>(std::move(o));
		}
		pybind11::pybind11_fail("Tried to call pure virtual function \"AAA::pv_foo\"");
	}
};
``` 
(this is all generated by https://github.com/RosettaCommons/binder so it a bit more verbose that written by human)
