### ISSUE TITLE
Patch that fixed #218 disallow forward declaration of types

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#251]
Hi Wenzel, 

I noticed that recent patch that addressed #218 is leading to a behavior when type can no longer be forward-declared. Is there is a way to forward declaring a type (and supply a full bindings at some point later) that does not trigger issues described in #218?

Thanks,

Sergey.

**Comment by wjakob** [comment]
Hi Sergey,

when you want to add extra methods, etc., can't you just do this?

```cpp
class_<MyClass, ...> c(m.attr("MyClass"))
   .def(...);
```
?

In any case, that's way to do it even before #218.

**Comment by lyskov** [comment]
Ah, i see - good idea! I will try that, - thank you!

**Comment by wjakob** [comment]
Can this be closed?

**Comment by lyskov** [comment]
Oh, sorry - i should closed that 3 days ago!

**Comment by MartinBubel** [comment]
> 

Sorry for commenting on this old issue but I came across this and failed to apply it to my problem.

Consider I have a code in a header file
`
class A;

class B {
private:
    A* a;
public:
    A* getA() { return this->a; }
}
`

I would assume the binding for class B would look something similar to
`
py::class_<B>(m, "B")
        .def("get_a", &B::getA, "get a pointer");
`
This howevers gives me compiler errors which also blame it to forward declaration. How would the fixes mentioned above look like?

**Comment by MartinBubel** [comment]
Sorry for commenting on this old issue but I came across this and failed to apply it to my problem.

Consider I have a code in a header file
```
class A;

class B {
private:
A* a;
public:
A* getA() { return this->a; }
}
```

I would assume the binding for class B would look something similar to
```
py::class_<B>(m, "B") .def("get_a", &B::getA, "get a pointer");
```
This howevers gives me compiler errors which also blame it to forward declaration. How would the fixes mentioned above look like?

**Comment by UnidayStudio** [comment]
> Sorry for commenting on this old issue but I came across this and failed to apply it to my problem.
> 
> Consider I have a code in a header file
> 
> ```
> class A;
> 
> class B {
> private:
> A* a;
> public:
> A* getA() { return this->a; }
> }
> ```
> 
> I would assume the binding for class B would look something similar to
> 
> ```
> py::class_<B>(m, "B") .def("get_a", &B::getA, "get a pointer");
> ```
> 
> This howevers gives me compiler errors which also blame it to forward declaration. How would the fixes mentioned above look like?

I'm having this same issue... Did you managed to fix it? @MartinBubel

**Comment by MartinBubel** [comment]
> > Sorry for commenting on this old issue but I came across this and failed to apply it to my problem.
> > Consider I have a code in a header file
> > ```
> > class A;
> > 
> > class B {
> > private:
> > A* a;
> > public:
> > A* getA() { return this->a; }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would assume the binding for class B would look something similar to
> > ```
> > py::class_<B>(m, "B") .def("get_a", &B::getA, "get a pointer");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This howevers gives me compiler errors which also blame it to forward declaration. How would the fixes mentioned above look like?
> 
> I'm having this same issue... Did you managed to fix it? @MartinBubel

Not really, at least not using pybind. I fixed it by using ctypes instead of pybind for the bindings as they enable forward declaration.
