### ISSUE TITLE
[QUESTION] unable to reload a python module that is build with pybind11?

### ISSUE THREAD

**Issue by shelper** [pybind/pybind11#2511]
I am using the first step example in pybind11's documentation
``` 
#include <pybind11/pybind11.h>
int add(int i, int j)
{
    return i + j;
}
PYBIND11_MODULE(example, m)
{
    m.doc() = "pybind11 example plugin"; // optional module docstring
    m.def("add", &add, "A function which adds two numbers");
}
```
 everything works fine, i can use it in python shell:
``` 
import  example
example.add(2, 3) #returns 5
```
Now i made a simple change to use float instead of int for input for add(), everything compiles. and i want to reload the module example so i can test the new float based add(). However, i can not figure out a way to reload the example module. `importlib.reload` does not work,  `%autorelaod 2` in `IPython` does not work either. 
both approach tested to work with pure python based  modules, but not the c++ and pybind11 based modules.

Did I miss anything here? or it ought to be like this?

**Comment by bstaletic** [comment]
> `importlib.reload` does not work

What do you mean by "does not work"? Does it produce an error?

**Comment by shelper** [comment]
it does not reload the new .so file, it just is still the old example module, with the old add function that only takes int , when i use float, it gives type error

**Comment by shelper** [comment]
I believe this is related to https://stackoverflow.com/questions/8295555/how-to-reload-a-python3-c-extension-module

> Python's import mechanism will never dlclose() a shared library. Once loaded, the library will stay until the process terminates.

pybind11 module and ctypes module seems to share the same traits here regarding how the module is loaded/imported

**Comment by bstaletic** [comment]
Right, python is just not made to reload modules. To be honest, it's surprising that things don't blow up worse when you attempt something like this.

**Comment by YannickJadoul** [comment]
As you found yourself, this is really nothing pybind11 can do anything about. The way C extensions are loaded by Python does not allow them to be reloaded (in contract to Python modules, where the Python code can just be reloaded and doesn't refer to a dynamically loaded library).

I'm afraid the only way to reload a C extensino module (as far as I know, at least) is to also restart the interpreter process.
