### ISSUE TITLE
[BUG] Building CLion project with MVSC on Windows 10 fails since sep 5, 2020

### ISSUE THREAD

**Issue by rhjdjong** [pybind/pybind11#2515]
## Issue description

Building a CLion project with pybind11 on Windows 10 with the MVSC toolchain fails since sep 5.
Instead of succesfullly building a debug and release Python module, both build types now fail.
The release build fails with:
```
[100%] Linking CXX shared module spam
LINK: command "C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\spam.dir\objects1.rsp /out:spam /implib:spam.lib /pdb:D:\GitHub\pybind11-issue\cmake-build-release\spam.pdb /dll /version:0.0 -LTCG /machine:x64 /INCREMENTAL:NO spamlib.lib C:\Users\Ruud\AppData\Local\Programs\Python\Python38\libs\python38.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:spam.manifest" failed (exit code 1120) with the following output:
   Creating library spam.lib and object spam.exp
spam.cpp.obj : error LNK2001: unresolved external symbol __imp__Py_NegativeRefcount
spam.cpp.obj : error LNK2001: unresolved external symbol __imp__Py_RefTotal
spam : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: 'C:\Users\Ruud\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\202.7319.72\bin\cmake\win\bin\cmake.exe' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
```

The debug build fails with:
```
[ 75%] Linking CXX shared module spam
LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\spam.dir\objects1.rsp /out:spam /implib:spam.lib /pdb:D:\GitHub\pybind11-issue\cmake-build-debug\spam.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL spamlib.lib C:\Users\Ruud\AppData\Local\Programs\Python\Python38\libs\python38.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\spam.dir/intermediate.manifest CMakeFiles\spam.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'python38_d.lib'
NMAKE : fatal error U1077: 'C:\Users\Ruud\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\202.7319.72\bin\cmake\win\bin\cmake.exe' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

```

## Reproducible example code
A minimal example of the project is provided in https://github.com/rhjdjong/pybind11-issue.
The environment used for this project is CLion 2020.2 with the following toolchain:
* MVSC 2019 BuildTools Version 16.0, Architecture amd64
* CMake (bundled with CLion) version 3.17.3
* Python 3.8.0 64-bit standard window install
* Pybind11 cloned into a neighbouring directory.

By resetting  the head of my local installed pybind11 repo, I discovered that this problem started with revision ce1a07ef45d204e6e72d7039ca6764cac90b026e. By looking at the changes and some experimenting, I found that lines 74-76 in tools/pybind11NewTools.cmake triggered these errors. This revision changed that line from
```
execute_process(COMMAND ${_Python}::Python -c "import sys; print(hasattr(sys, 'gettotalrefcount'))"
                OUTPUT_VARIABLE PYTHON_IS_DEBUG)
```
into
```
execute_process(
  COMMAND "${${_Python}_EXECUTABLE}" "-c" "import sys; sys.exit(hasattr(sys, 'gettotalrefcount'))"
  RESULT_VARIABLE PYTHON_IS_DEBUG)
```
I verified that changing this back to the original line makes the builds succeed again, also with the current pybind11 master HEAD (revision 5e6ec496522b313e34af3de91f6c0565f68e3552).

**Comment by YannickJadoul** [comment]
Thanks for the clear and extensive description! Let's see if @henryiii, who's been reworking CMake, know what went wrong.

**Comment by ruuddejong-altran** [comment]
I was too quick in assuming that reverting the `gettotalrefcount` line fixed the entire problem. The builds do indeed succeed, but no `.pyd` file is created. Hence importing the module in Python does not work. This may be caused by the other changes in the file `pybind11NewTools.cmake`

**Comment by rhjdjong** [comment]
I was too quick in assuming that reverting the `gettotalrefcount `line fixed the entire problem. The builds do indeed succeed, but no `.pyd` file is created. Hence importing the module in Python does not work. This may be caused by the other changes in the file `pybind11NewTools`.cmake

**Comment by henryiii** [comment]
Will investigate tomorrow! Moving and don't have access to my computer currently.

**Comment by henryiii** [comment]
Okay; to look into this further I may need to set up a windows box, but I can do a little now, and provide some insight.

First, `COMMAND ${_Python}::Python` was replaced by `COMMAND "${${_Python}_EXECUTABLE}"` because the first one didn't actual do what I thought it did, it returned an error code instead of running Python. We didn't check the error code, so it was impossible to set a debug Python. When I added the extension discovery, I detected the error (since extensions weren't being discovered), and corrected the debug discovery too. So `Py_DEBUG` is being defined now for debug builds, while before it was not.

After you've done such a fantastic job of investigation and reporting, I rather hate to ask, but can you try one-two debugging ideas?

* Try printing out the values of `${${_Python}_EXECUTABLE}`, `$PYTHON_IS_DEBUG`, and `$PYTHON_MODULE_EXTENSION`
* Try with Python 3.7. Debug builds changed pretty drastically in 3.8, and we don't have CI testing 3.8 on Windows yet (due to extension lookup changes that killed our test suite). And we don't really test against a debug Python build (it looks like Windows may include both?
* Can you try with `-DPYBIND11_NEWPYTHON=OFF` just to see what the behavior of the old one is? 

The idea you get both a debug build and a regular build of Python is rather new to me, especially linking the release build against the release Python, and the debug Python against the debug Python. I'll have to try it before fixing it, I think.

**Comment by rhjdjong** [comment]
OK. I found the issue. Basically a collision of unspoken assumptions. Until now, I had no need to actually use the Python interpreter in my CMakeLists.txt files, so I only searched for the development artifacts
```
find_package(Python3 COMPONENTS Development)
```
This does not set the `Python3_EXECUTABLE` variable, but all other relevant variables (`Python3_INCLUDE_DIRS`, `Python3_LIBRARIES`, `Python3_VERSION`) were set. And that worked fine.
But now Pybind11 assumes the value in `Python3_EXECUTABLE` is set, and since that is not set, weird things happen.
So I changed my cmake line into
```
find_package(Python3 COMPONENTS Interpreter Development)
```
and everything works again.

So I think the only thing that needs to be done for this issue is to make it clear in the documentation that when the `find_package(Python3)` command is used, it *MUST* include the `Interpreter` component.

---

And just to clear up any confusion: I was/am linking both the release and the debug build of my C++ library to the release Python build -- after all, I don't want to debug the Python interpreter. That is, as far as I know, common procedure. But for MVSC builds that means that `_DEBUG` must be unset when including `Python.h` (and reset to its original value afterwards), otherwise (in `pyconfig.h`) it will force linking to `python38_d.lib` -- which does not exist on my system, nor on most Windows systems.
SWIG uses the `SWIG_PYTHON_INTERPRETER_NO_DEBUG` define for this purpose, and for pybind11, I noticed that detail/common.h has a similar mechanism that is triggered except when in CMake PYTHON_IS_DEBUG is set. And since I don't set that anywhere, I was really at a loss why it would suddenly try to link to the debug Python interpreter.

Anyway, changing my CMakeLists.txt file as indicated apparently makes everything work correctly again.

**Comment by henryiii** [comment]
There is a note in the CMake documentation:

> If the component `Development` is requested, it is *strongly* recommended to also include the component `Interpreter` to get expected result.

(under the venv section)

I think we should throw an error if `${${_Python}_EXECUTABLE}` is not set. It should already error with a fairly reasonable error if `Development` is not set (due to missing targets).

**Comment by henryiii** [comment]
Can you try removing the Interpreter component with the latest master and see if the error message is better? You are not allowed to "re-search", but this is still much better than a mysterious failure.

**Comment by rhjdjong** [comment]
Works Fine. When I remove the `Interpreter` component, I get the message:
```
CMake Error at D:/GitHub/pybind11/tools/pybind11NewTools.cmake:77 (message):
  Python3 was found without the Interpreter component.  Pybind11 requires
  this component.
Call Stack (most recent call first):
  D:/GitHub/pybind11/tools/pybind11Common.cmake:190 (include)
  D:/GitHub/pybind11/CMakeLists.txt:162 (include)
```

Thanks for addressing this.
