### ISSUE TITLE
Is there any suitable auto generator for large existing project?

### ISSUE THREAD

**Issue by daleydeng** [pybind/pybind11#252]
Hi, currently I'm using Boost.Python + pyplusplus  to deal with large existing C/C++ project by auto generation, Is it possible to migrate pyplusplus to pybind11?

**Comment by wjakob** [comment]
There is an unmaintained project here that may be a good start:

https://github.com/ISoirar/pypp11

See also the issues, which have some further pointers.

**Comment by daleydeng** [comment]
Thanks~

**Comment by daleydeng** [comment]
I found pyplusplus is messy and I'm working on a new one based on clang, whoosh and jinja2

**Comment by wjakob** [comment]
That sounds like a great idea. You can also take a look at the mkdoc.py that ships with pybind11. That uses libclang to dump all the documentation headers from a C++ codebase so that they can be used as docstrings. Example usage here: https://github.com/wjakob/nanogui/tree/master/python

**Comment by daleydeng** [comment]
Allright, thanks~~

**Comment by daleydeng** [comment]
All right thanks, now I'm refering  seasnake for clang code converter~~ https://github.com/pybee/seasnake, When I'm done, I'll post it up~

**Comment by wjakob** [comment]
Cool, I'd definitely be interested if you have something to share at some point. By the way, what is whoosh good for (Jinja makes sense to me, but Whoosh seems to be an indexing library, which is a bit unusual in this context)

**Comment by daleydeng** [comment]
Since there need some query operation in extracted AST for classes/methods to export, usually u dont want to export all classes/methods which is overhead for large projects (OpenSceneGraph for example). For example in  pyplusplus/gccxml, there is module.classes,  cls.mem_funs and etc for this job to specifiy some params for generation on needed items(class, member functions and etc,)  I'll finish it soon

**Comment by daleydeng** [comment]
Currently, The skeleton of  parser(clang), Indexer(whoosh) and Convertor(Jinjia2) are done and now im finishing the main specification of pybind11 by refering the documentation.
