### ISSUE TITLE
Access to cpp byte string with def_readonly and get UnicodeDecodeError error  

### ISSUE THREAD

**Issue by zhangguanheng66** [pybind/pybind11#2524]
I'm using pybind11 to pass a cpp byte string (a class parameter) to python via `def_readonly`. When calling the class parameter on python side, I got `UnicodeDecodeError`. Actually, I want to keep the byte parameter without decoding. Any ideas are appreciated.

**Comment by YannickJadoul** [comment]
Can you give a bit more explanation and include the relevant parts of the code?

**Comment by zhangguanheng66** [comment]
I saw some discussions to use ` py::bytes` to return cpp strings without conversion. How can I use it with `def_readonly`?

**Comment by YannickJadoul** [comment]
> I saw some discussions to use ` py::bytes` to return cpp strings without conversion.

Where? How's that related to a `UnicodeDecodeError`?

> How can I use it with `def_readonly`?

`def_readonly` is very similar to `def`, so there shouldn't be anything special about it.

**Comment by zhangguanheng66** [comment]
In pybind release document 2.5.0 release section 11.2.2

**Comment by YannickJadoul** [comment]
> See [here](https://github.com/pybind/pybind11/issues/2524#issuecomment-697043184).

Something went wrong there: this is a link to your own comment

> `content_` in cpp is a "byte" string in "SentencePiece" class, and I want to return it to python without conversion (a.k.a. still "byte"). I saw I can use `py::bytes` to force the returned string in "byte". But just don't know how to use it together with `def_readonly`.

Then just bind a lambda `[] (const SentencePiece &self) { ... }` where you turn `content_` into a `py::bytes`, then, instead of `&SentencePiece::content_`?

**Comment by zhangguanheng66** [comment]
Thanks. I add a lambda func to `.def` and it works.
