### ISSUE TITLE
How to call super-class setattr using C++ Python API

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#2525]
In Python it is customary to call e.g. `object.__setattr__(self, name, value)` to assign to an instance attribute from within a custom `__setattr__`.  But how can one do this from C++ (e.g. from `cls.def("__setattr__", ...)`?
I tried just assigning to the instance `__dict__` but that messes with the behavior of any properties also defined in C++ on that class.
What is the recommended way to do this?

**Comment by YannickJadoul** [comment]
@pschella, would `py::module::import("builtins").attr("object").attr("__setattr__")(...)` work, or is that too slow? You can probably also immediately access some C API, I'd guess.

**Comment by bstaletic** [comment]
[`PyObject_SetAttrString(o, "name", val);`](https://docs.python.org/3.8/c-api/object.html#c.PyObject_SetAttrString)

**Comment by YannickJadoul** [comment]
> [`PyObject_SetAttrString(o, "name", val);`](https://docs.python.org/3.8/c-api/object.html#c.PyObject_SetAttrString)

I'm not sure if this is the same or will recurse and do the lookup of `__setattr__` again? (I suspect the latter.) But worth a try.

No further comments, so let's close this. Please reopen if necessary.

**Comment by flooklab** [comment]
Hey, as I had the same/similar problem but this issue didn't really mention a proven solution:
I could make it work using this:
```
cls.def("__setattr__",
        [](Class& instance, const std::string_view name, py::object value) -> void
        {
            // do custom stuff ...

            // fall back on parent class's __setattr__ ...
            py::type selfType = py::type::of<Class>();
            py::object selfObj = py::cast(instance);
            py::module::import("builtins").attr("super")(selfType, selfObj).attr("__setattr__")(name, value);
        }
);
```
