### ISSUE TITLE
Iterate over enums

### ISSUE THREAD

**Issue by romainthomas** [pybind/pybind11#253]
Actually we can't iterate over a enum. It could be nice to enable this kind of code:

``` python
for e in myEnum:
    print e
```

**Comment by wjakob** [comment]
Are you proposing to implement such a feature?

**Comment by aldanor** [comment]
A side thought, would it make sense to consider using standard library's `enum` inside of rolling our own? (only in Python 3, but there's an official backport to Python 2)

https://docs.python.org/3/library/enum.html

**Comment by wjakob** [comment]
It sounds tricky -- ``Enum`` is a kind of magic class in Python3, and it requires installing an extra library on python2. I think duck typing is the way to go here.

**Comment by romainthomas** [comment]
> Are you proposing to implement such a feature? A PR with a custom __iter__ handler would be welcomed.

@wjakob I will try.

Actually I use this trick:
```python
import re
def enum_to_dict(enum):
    return {k: v for k, v in enum.__dict__.iteritems() if not re.match("__(.*)__", str(k))}
```

**Comment by wjakob** [comment]
I'll close this ticket since there isn't an issue with pybind11 -- if you'd like to contribute this as a feature, please open a pull request.

Thanks,
Wenzel
