### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Tuareg0xFFFF** [pybind/pybind11#2535]
## Issue description

`py::module::def_submodule()` does not work in python 2 (2.7.17) and renders its parent module unusable.

Consider the following binding:
```
...
PYBIND11_MODULE(geo, m) {
    m.attr("__name__") = "ns.geo";
    auto cm = m.def_submodule("clustering");
    cm.def("foo", &foo, ...);
...
```

In python 3, `ns.geo.clustering.foo()` is accessible from python and works as expected.

However, python 2 is different: 

```
Python 2.7.17 (default, Jul 20 2020, 15:37:01) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ns.geo.clustering
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: basic_string::_M_construct null not valid
``` 

Couple more observations:
- If I bind `foo()` to original module, and remove submodule, all is well
- If I bind `foo()` to original module, and leave unused submodule in, problem is still there

**Comment by Tuareg0xFFFF** [comment]
pybind version is 2.5.0

**Comment by YannickJadoul** [comment]
@Tuareg0xFFFF Do you have a full, minimal example that shows the failure on Python 2, please? Then I can test out a few things locally.

**Comment by Tuareg0xFFFF** [comment]
I found the issue. It is not pybind's fault. Closing....
