### ISSUE TITLE
[BUG] ImportError: ImportError: __import__ not found Python 3.7

### ISSUE THREAD

**Issue by ObjatieGroba** [pybind/pybind11#2557]
I used python_example (https://github.com/pybind/python_example) to create new package.
After installation I have

```
>>> import mymodule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ImportError: __import__ not found

At:
  <string>(3): <module>
  <frozen importlib._bootstrap>(222): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(914): create_module
  <frozen importlib._bootstrap>(577): module_from_spec
  <frozen importlib._bootstrap>(666): _load_unlocked
  <frozen importlib._bootstrap>(958): _find_and_load_unlocked
  <frozen importlib._bootstrap>(969): _find_and_load
  <stdin>(1): <module>
```

On python3.8 works perfectly

## Reproducible example code

Debian10. Python 3.7

Clone and install python_example

Add this code to main.cpp

```
auto global = m.attr("__dict__");
py::exec(R"(
    import contextlib
)", global);
```

EDIT (@YannickJadoul): "*After reading, remove this checklist and the template text in parentheses below.*"

**Comment by henryiii** [comment]
Why is this installing an egg? You should be using wheels. `pip install .`, never `python setup.py install` or family - installing with `python setup.py install` is deprecated and discouraged heavily by the Python Packaging Authority. If you run setup.py and never import setuptools, you get a pure distutils build, which is likely broken. And if you don't run it with pip, pip can't insert shims needed for building.

Python devs pretty much will not touch distutils, even to fix it, and [is considering getting rid of it entirely](https://www.python.org/dev/peps/pep-0632). Setuptools now vendors distutils.

**Comment by ObjatieGroba** [comment]
> Why is this installing an egg? You should be using wheels. `pip install .`, never `python setup.py install` or family - installing with `python setup.py install` is deprecated and discouraged heavily by the Python Packaging Authority. If you run setup.py and never import setuptools, you get a pure distutils build, which is likely broken. And if you don't run it with pip, pip can't insert shims needed for building.
> 
> Python devs pretty much will not touch distutils, even to fix it, and [are considering getting rid of it entirely](https://www.python.org/dev/peps/pep-0632). Setuptools now vendors distutils.

Hi, thank you.

`pip install .` leads to the same error.

cmake_example uses `setuptoools`

What should I do to install it?

**Comment by ObjatieGroba** [comment]
I found it.

```
auto global = m.attr("__dict__");
py::exec(R"(
    import contextlib
)", global);
```

This code does not working on Python 3.7 and earlier

**Comment by henryiii** [comment]
This code is not part of pybind11 or the examples, as far as I can tell?

**Comment by henryiii** [comment]
I don't think that's the right way to import something. You should do `py::module::import("contextlib")`. Certainly, it's not valid to put a module's `__dict__` in as a replacement for the global context.
