### ISSUE TITLE
support for None type

### ISSUE THREAD

**Issue by HDembinski** [pybind/pybind11#256]
Hi,

I am long time-user of boost.python, and I just started using pybind11. I am already amazed how familiar, yet more comfortable it is. Great work!

The only thing I am missing so far, is support for the None type on the C++ side. In boost.python, it is represented by a default constructed boost::python::object. It is useful to have as a default for a function argument. When I try to use a pybind11::object() as the default argument for a pybind11::arg in this way, I get an error message.

ImportError: arg(): could not convert default keyword argument into a Python object (type not registered yet?). Compile in debug mode for more information.

**Comment by HDembinski** [comment]
After browsing the source code, I found py::none, which is what I needed. I would still suggest to automatically convert pybind11::object() to Py_None if it is used as a default argument, and I suggest to add this to the documentation. py::none is not listed here:
http://pybind11.readthedocs.io/en/latest/reference.html#convenience-classes-for-arbitrary-python-types

**Comment by wjakob** [comment]
The object() conversion can't be introduced since it would cause breakage throughout the library. Improvements to the documentation are welcomed if you want to contribute this.

**Comment by HDembinski** [comment]
I like your solution better, anyway, having a dedicated type pybind11::none is more explicit than using a default constructed pybind11::object to represent none. This is one of the problems with boost.python that you seem to address with pybind11, in boost.python many rules are implicit.

However, I am still a bit confused after reading the code. In cast.h, it looks like you convert nullptr into Py_None. A default constructed pybind11::object is initialized to hold a nullptr. So why can't you define a rule to cast a pybind11::object that holds a nullptr into a Py_None?

**Comment by HDembinski** [comment]
PS: If I find the time, I would be interested to help with the documentation.

**Comment by HDembinski** [comment]
I tried to use nullptr as the default argument in a function. I think that nullptr is a perfect candidate for an automatic cast into a Py_None. However, I get this error:

_likelihood.cpp:393:75: error: use of overloaded operator '=' is ambiguous (with operand types 'py::arg' and 'nullptr_t')
        .def("flux", &LELikelihood::flux, py::arg("prim"), py::arg("par") = nullptr)
                                                           ~~~~~~~~~~~~~~ ^ ~~~~~~~
/Users/hdembinski/Library/Python/2.7/include/python2.7/pybind11/attr.h:20:8: note: candidate is the implicit move assignment operator
struct arg {
       ^
/Users/hdembinski/Library/Python/2.7/include/python2.7/pybind11/attr.h:20:8: note: candidate is the implicit copy assignment operator
/Users/hdembinski/Library/Python/2.7/include/python2.7/pybind11/attr.h:24:24: note: candidate function [with T = nullptr_t]
    constexpr arg_t<T> operator=(const T &value) const { return {name, value}; }
                       ^
1 error generated.

**Comment by wjakob** [comment]
I cannot reproduce your issue, both with Clang and GCC. For instance, the following compiles for me just fine
```
m.def("kw_func", [](const char *) { }, py::arg("data") = nullptr);
```
Perhaps your compiler is a bit outdated? Generally, please try to provide minimal and self-contained examples that trigger an issue, otherwise it's impossible to reproduce on my end.

**Comment by HDembinski** [comment]
**My compiler version:**
Apple LLVM version 7.3.0 (clang-703.0.31)

**Test code:**
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>

namespace py = pybind11;

PYBIND11_PLUGIN(_test_bug) {
    py::module m("_test_bug");

    m.def("func", [](double a) {}, py::arg("a") = nullptr);

    return m.ptr();
}

**Error message:**
./test_bug.cpp:9:49: error: use of overloaded operator '=' is ambiguous (with operand types 'py::arg' and
      'nullptr_t')
    m.def("func", [](double a) {}, py::arg("a") = nullptr);
                                   ~~~~~~~~~~~~ ^ ~~~~~~~
/Users/hdembinski/Library/Python/2.7/include/python2.7/pybind11/attr.h:20:8: note: candidate is the implicit
      move assignment operator
struct arg {
       ^
/Users/hdembinski/Library/Python/2.7/include/python2.7/pybind11/attr.h:20:8: note: candidate is the implicit
      copy assignment operator
/Users/hdembinski/Library/Python/2.7/include/python2.7/pybind11/attr.h:24:24: note: candidate function
      [with T = nullptr_t]
    constexpr arg_t<T> operator=(const T &value) const { return {name, value}; }
                       ^
1 error generated.

**Comment by wjakob** [comment]
It works with the 'master' branch on github (tested with Xcode clang).

Aside: did you really mean to pass a None pointer to a C++ double? That makes no sense to me -- what, in your opinion, should pybind11 issue to the function when it is called?

**Comment by HDembinski** [comment]
On 6/30/16 10:41 AM, Wenzel Jakob wrote:
>
> It works with the 'master' branch on github (tested with Xcode clang).
>
> Aside: did you really mean to pass a None pointer to a C++ double? 
> That makes no sense to me -- what, in your opinion, should pybind11 
> issue to the function when it is called?
>
You asked me for a simple test code. Of course it doesn't make sense, it 
just served to illustrate the bug.

-- 
Hans Dembinski
https://github.com/HDembinski

Proposed for Boost: histogram
https://github.com/HDembinski/histogram

Automatic one-dimensional unfolding of data distributions
https://github.com/HDembinski/aru-unfolding

**Comment by twoone-3** [comment]
Hi
I ran into a similar problem
```cpp
m.def("setCommandDescription",
	[](const string& cmd, const string& des, py::function cb) {
		g_commands.insert({ cmd, { des, cb } });
	}, "cmd"_a, "des"_a, "callback"_a = py::function());
```
I want to make the third parameter py::function optional
But in this example, it reported an error
> ImportError: arg(): could not convert default argument into a Python object (type not registered yet?). Compile in debug mode for more information.

When I change "callback"_a = py::function() to "callback"_a = py::none() or nullptr
> TypeError: setCommandDescription(): incompatible function arguments. The following argument types are supported:
    1. (cmd: str, des: str, callback: function = None) -> None

I don't know what i should do
