### ISSUE TITLE
pybind fails when cross compiling due to using the wrong python include directory 

### ISSUE THREAD

**Issue by asobhy-qnx** [pybind/pybind11#2567]
the way that pybind finds python library, headers and SOABI will fail with any cross compilation method as it relies on running commands on the native system to detect python libraries and other parameters which will be different on the target platform.

Here is a snippet of code that causes the issue:
https://github.com/pybind/pybind11/blob/3b1dbebabc801c9cf6f0953a4c20b904d444f879/tools/FindPythonLibsNew.cmake#L77-L119

There is a way to bypass this issue by manually setting those values in the toolchain file as well as setting PYTHONLIBS_FOUND and PYTHON_MODULE_EXTENSION

**Comment by henryiii** [comment]
I would use FindPython by adding `set(PYBIND11_FINDPYTHON ON)` or `find_package(Python COMPONENTS Development Interpreter)` in your CMakeLists before finding / adding pybind11. Then you'll only run two commands - a check for debug symbols, and so discovery. You can further avoid extension discovery by setting `WITH_SOABI` or `WITHOUT_SOABI`. Or you can turn off Python discovery entirely by setting `PYBIND11_NOPYTHON`.

**Comment by henryiii** [comment]
It might be better if the two values were cached, and only run if not already in the cache?

**Comment by asobhy-qnx** [comment]
> It might be better if the two values were cached, and only run if not already in the cache?

you mean PYTHONLIBS_FOUND and PYTHON_MODULE_EXTENSION?

**Comment by asobhy-qnx** [comment]
Here is part of my toolchain file that I set python variables in:

`set(PYTHON_SOABI cpython-38)
find_package(PythonInterp 3.8 REQUIRED)
set(PYTHON_INCLUDE_DIR ${QNX_TARGET}/${CPUVARDIR}/usr/include/python3.8;${QNX_TARGET}/usr/include/python3.8;${QNX_STAGE}/${CPUVARDIR}/usr/lib/python3.8/site-packages/numpy/core/include)
set(PYTHON_LIBRARY ${QNX_TARGET}/${CPUVARDIR}/usr/lib/libpython3.8.so)
set(PYTHON_INCLUDE_DIRS ${QNX_TARGET}/${CPUVARDIR}/usr/include/python3.8;${QNX_TARGET}/usr/include/python3.8;${QNX_STAGE}/${CPUVARDIR}/usr/lib/python3.8/site-packages/numpy/core/include)
set(PYTHON_LIBRARIES ${QNX_TARGET}/${CPUVARDIR}/usr/lib)
set(PYTHONLIBS_FOUND)
set(PYTHON_MODULE_EXTENSION .cpython-38.so)
`
I override the variables after find_package(PythonInterp 3.8 REQUIRED) to use the libraries and headers in the system root for the target.

**Comment by henryiii** [comment]
I mean for the FindPython tools (new in 2.6), the only two calls that are made (by us) are for PYTHON_IS_DEBUG and PYTHON_EXTENSION. See my PR.

**Comment by asobhy-qnx** [comment]
Thank you

**Comment by YannickJadoul** [comment]
Did #2570 solve this, or should this issue stay open?
