### ISSUE TITLE
Richer interface for array_t

### ISSUE THREAD

**Issue by HDembinski** [pybind/pybind11#257]
It would be nice if the array_t type in numpy.h would get a richer interface, perhaps mimicking boost.multi_array or Eigen::Array. It would be nice if the following things could be done:

void func(pybind11::array_t<double> arr) {
   if (arr.ndim() != 1)
     throw std::invalid_argument("wrong dimension");
   for (unsigned i = 0, n = arr.shape[0]; i < n; ++i) {
      const double value = arr(i);
      // do something with value ...
   }
}

All this is currently possible, but one has to request the buffer, get the data pointer etc. etc., which is repetitive.

**Comment by wjakob** [comment]
A fancy interface would be desirable, but I don't have the manpower here to drive such a project (which could become very complex, as the two projects you mention clearly show). I think it would be better to do this externally by forking pybind11 or developing it as another header file library that is included in addition to pybind11.

**Comment by HDembinski** [comment]
I take that as an offer that you would accept such a pull request, if I found the time to work on it.

I don't see that it has to be that involved, but perhaps I made myself not clear. I am not thinking of a building a complete matrix library on top of arrar_t, just a bit more interface to make array_t behave more like dict or tuple, which mirror the behavior of their respective python interfaces.

Shouldn't you keep an issue open that you in principle agree with, as a reminder for yourself and/or people who might like to make a pull request about it?

**Comment by wjakob** [comment]
There are many users who request features but aren't willing to do the work themselves. As this is only a hobby project, I generally don't have the time for them either, and the issue tracker would just get swamped. Thus I try to use the issue tracker for actual issues (i.e. target issues == 0) and PR tracker for contributions or partial ones that need further discussion.

Regarding this specific ticket: I would be willing to accept improvements to array_t, but I think it's best to develop those separately (e.g. using a fork of pybind11). 
Right now the array class provides a reasonable bare-bones interface. When it's clear that a good solution has been found, this could be merged into pybind11.

**Comment by wjakob** [comment]
FYI: #125 is potentially useful to look at, @jmabille has done some work in this direction (which I rejected at the time because I considered it too complex for pybind11)

**Comment by HDembinski** [comment]
Ok, thank you for explaining your use of issue tracker and PR tracker, that is fine then. It makes sense that you want to focus on the core library, and as a fellow hobby developer, I understand that you have limited time.

I think that pybind11 has a large potential for numerical applications. I am a physicist, Python and C++ are very popular languages among my peers. When you develop an analysis, it is often useful to start out in Python and then move the computational part to C++ as needed. pybind11 seems like an ideal bridge for this task. You already provide some integration with Eigen and numpy. I think that it would benefit many people if this integration would be extended. I am interested in giving it a short and if I find the time, I would be happy to make a PR. I hope I can discuss interface details with you, when the time comes.

I will have a look at #125, thanks!

**Comment by wjakob** [comment]
All agreed with the above. If/once your plans turns into a more concrete project, it would be fine to create an a longer-term ticket to discuss the architecture with me and other users.
