### ISSUE TITLE
[CI] Add valgrind run to CI test suite

### ISSUE THREAD

**Issue by YannickJadoul** [pybind/pybind11#2578]
Reminder to work on adding a (or multiple?) valgrind run to the CI, to catch memory issues sooner. Potentially, we could think about some sanitizers as well?

**Comment by bstaletic** [comment]
`python -c 'import pybind11_tests'` leaks this thing: https://github.com/pybind/pybind11/blob/master/include/pybind11/pybind11.h#L1320
