### ISSUE TITLE
C++ function with existing python datatype

### ISSUE THREAD

**Issue by nalyat** [pybind/pybind11#258]
Hi,

I want to handle a generic python datatype from C++, but unfortunately couldn't find a way to receive PyObject* arguments, or wrap the existing object using a pybind11::object. Any help appreciated.

When I use PyObject* as function, I get this error:
```
Incompatible function arguments. The following argument types are supported:
    1. (_object) -> NoneType
```

T./

**Comment by wjakob** [comment]
You'll have to dig further into the library yourself to see how to use pybind11::object directly -- due to time constraints, this is sadly something for which I cannot provide support here.

**Comment by TD22057** [comment]
@nalyat In case you still care, I had the same problem and was able to get it to work using lambdas:

Function accepting a PyObject*
```
   c.def_static( "fromArray", []( py::handle obj ) {
         PyObject* a = obj.ptr();
         return Dbl3Vec::fromArray( a );
      } );
```

Function returning a PyObject*
```
   c.def( "toArray", []( const Dbl3Vec& self ) {
         PyObject* r = self.toArray();
         return py::handle( r );
      } );
```
