### ISSUE TITLE
[BUG] Warnings on windows when using `pybind11_add_module` and build type `RelWithDebInfo`

### ISSUE THREAD

**Issue by ivanpauno** [pybind/pybind11#2587]
## Issue description

When using `-DCMAKE_BUILD_TYPE=RelWithDebInfo` on Windows, I see some warnings being logged.

<details>
<summary>Example error output</summary>

```
14:39:25   Building Custom Rule C:/ci/ws/src/ros2/rosbag2/rosbag2_py/CMakeLists.txt

14:39:25   _reader.cpp

14:39:25 LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification [C:\ci\ws\build\rosbag2_py\_reader.vcxproj]

14:39:25      Creating library C:/ci/ws/build/rosbag2_py/RelWithDebInfo/_reader.lib and object C:/ci/ws/build/rosbag2_py/RelWithDebInfo/_reader.exp
```
</details>

Other relevant details:
- I checked what are the default link flags that cmake uses on Windows when build type is `RelWithDebInfo`, `/INCREMENTAL` is one of the flags (see [here](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.18.4/Modules/Platform/Windows-MSVC.cmake#L273)).
- `/LTCG` prevents windows `/INCREMENTAL` linkage, thus the warning ([incremental docs](https://docs.microsoft.com/en-us/cpp/build/reference/incremental-link-incrementally?view=vs-2019), [ltcg docs](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=vs-2019)).
- `/LTCG` is implied by `/GL` compile flag ([ltcg docs](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=vs-2019)), so `/GL` shouldn't be passed either.

Based on that, it seems that the generator expressions [here](https://github.com/paamand/pybind11/blob/9513b0daeff546568a4143d3c78563be84063528/tools/pybind11Tools.cmake#L103-L108) should be extended so that `LTO` flags are ignored when build type is `RelWithDebInfo` (at least on Windows, it wasn't a problem in other platforms).

## Reproducible example code

I have tried this in an example with many dependencies (code [here](https://github.com/ros2/rosbag2/tree/master/rosbag2_py)), but it should be reproducible in any pybind11 example using cmake and `-DCMAKE_BUILD_TYPE=RelWithDebInfo`.
If you need a confirmation with a simpler example (e.g. https://github.com/pybind/cmake_example/), please let me know and I will add steps on how to reproduce the issue.

cmake version: 3.18.4 (but I think it shouldn't matter)

**Comment by henryiii** [comment]
Just curious, does CMake do it correctly if you add `set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)` near the top, do you still get the warning? (master or 2.6.0rc1).

**Comment by henryiii** [comment]
Also, you will need to set `cmake_minimum_required(VERSION 3.5...3.18)` (or, really, just make sure you have either a lower or upper limit above 3.9) for `CMAKE_INTERPROCEDURAL_OPTIMIZATION` to work.

**Comment by henryiii** [comment]
Looks like they disable it:

https://gitlab.kitware.com/cmake/cmake/-/blob/f1547694395298ab77c5342d4f596e7800dc9b39/Modules/Platform/Windows-MSVC.cmake#L358-359

Of course, you could set something like `CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE`, which we don't check for.

**Comment by ivanpauno** [comment]
> Just curious, does CMake do it correctly if you add set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE) near the top, do you still get the warning? (master or 2.6.0rc1).

I tested with `2.6.0rc1` and `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`, in that case there's no warning.

**Comment by ivanpauno** [comment]
Thanks for the fix @henryiii !!
