### ISSUE TITLE
implicitly_convertible doesn't allow specification of implicit conversion to basic data types

### ISSUE THREAD

**Issue by jagerman** [pybind/pybind11#259]
I have a a C++ class structure like this:

```
class A {
    ...
    void method(uint64_t val) { ... }
}
class B {
    ...
    uint64_t id() { ... } // returns unique identifier
    operator uint64_t() { return id(); }
}
```

i.e. where B is implicitly convertible to a uint64_t, with the intended usage to allow methods that only need the unique identifier to be called as:

`a_instance.method(b_instance);`

as a shortcut for:

`a_instance.method(b_instance.id());`

I tried to register this conversion using `pybind11::implicitly_convertible<B, uint64_t>()`, but the resulting module fails to import with:

`ImportError: implicitly_convertible: Unable to find type unsigned long`

Given that uint64_t is listed in the documentation's out-of-the-box "Supported data types" I rather expected this to work, but it does not.

I can work around this by defining two methods--one that takes B instances, and one that takes uint64_t values--but that seems a bit messy and inefficient for something that seems like it should work: i.e. my B instances *are* implicitly convertible to uin64_t, but I don't seem to be able to tell pybind11 about it.

(I did a quick test with std::vector and got the same error, so this doesn't appear to be something that only applies to primitive types.)

**Comment by wjakob** [comment]
Implicitly conversions only work for custom types that were registered by the user. The is a limitation of how the feature is implemented in pybind11. I'll add a note to the docs.

**Comment by jagerman** [comment]
> Implicitly conversions only work for custom types that were registered by the user. The is a limitation of how the feature is implemented in pybind11. I'll add a note to the docs.

Yes--but of course every bug is a limitation of the current implementation.  Is there a fundamental reason that this couldn't/shouldn't be implemented?

**Comment by wjakob** [comment]
It could definitely be implemented but involve quite a few changes (if it was straightforward to do, the old implementation would have already supported it). Are you offering to do it?

**Comment by jagerman** [comment]
Yes.  But it may be a while before I can get around to looking at it.
