### ISSUE TITLE
[QUESTION] Consequences of not explicitly constructing a holder with __init__

### ISSUE THREAD

**Issue by topiolli** [pybind/pybind11#2592]
Recently, `pybind11_meta_call` was added a run-time check that ensures that the `__init__` function of a base type defined in C++ is explicitly called in Python code. I can see the rationale, but it breaks things for me. Or maybe I was broken already, I don't know.

I was aware of the requirement of an explicit `__init__` call to the  base class. Since this is not a requirement for normal Python classes, I didn't want to expose the limitation to my users. I carefully designed my base classes so that they have no data members. Thus, undefined content is not a problem. The member functions of the base class use the address of the wrapped C++ object to look up class members in external storage. 

This _seemed_ to work, but the newly added safety feature breaks my code and obsoletes the whole design.

My questions:

- Was it safe in the first place? I mean, does it make any difference from pybind11's perspective whether the base class has data members or not?
- If it is safe, is there a way to make `pybind_meta_call` believe `__init__` was called?

**Comment by bstaletic** [comment]
As far as I can tell, what you've been doing is undefined behaviour. If you didn't call the constructor, there is no object at that memory address. Therefore, you can't treat that memory location as if there were an object.

**Comment by topiolli** [comment]
Thanks for the reply. I understand that _accessing_ the object would be undefined behavior, but I'm not doing that. To me, it doesn't matter that there is no object at the address as far as there is a unique address. I didn't dig into the code deep enough to understand what pybind11 actually does when constructing a holder. If it preallocates memory for the held type and uses placement new, I should be safe. If it uses regular new and the holder's pointer to the class instance without an `__init__` call is uninitialized, I'm screwed.

Maybe the question could be rephrased: is an explicit call to base `__init__` required to initialize the held pointer to the C++ type to a unique value?

Anyhow, I already made my mind. My use case isn't likely to be supported (I wouldn't, the current behavior is sane), and hacking around the check would mean more maintenance burden. That and potentially undefined behavior outweigh my user's convenience. Documenting the slightly annoying restriction seems to be the least bad solution.
