### ISSUE TITLE
[BUG] Windows PyPy2 (32 bit) support

### ISSUE THREAD

**Issue by henryiii** [pybind/pybind11#2596]
## Issue description

There are infinite hangs and/or popups about memory corruption on pypy (2) on Windows (32 bit only currently). 

## Reproducible example code

Activate the `- pypy2` job on Windows in CI, or build locally.

**Comment by henryiii** [comment]
Ahah! It's not 3.9, it's the start of the 32 bit wheels! We are broken on 32 bit windows.

**Comment by bstaletic** [comment]
Isn't this resolved by #2599?

**Comment by henryiii** [comment]
No, 32 bit pypy2 Windows builds, but hangs the test suite on CI or pops up error messages (windows version of segfault, I think) when run locally. The PR resolved build errors, and pypy3 passes the test suite happily.

**Comment by mattip** [comment]
I think this can be closed as a won't-fix. PyPy has dropped support for 32-bit windows, and anyone using pypy + pybind11 + windows32-bit + python2 should speak up and request support.

**Comment by henryiii** [comment]
We won't even be keeping Python 2 support around that much more (less than two months), so sounds fine to me.
