### ISSUE TITLE
[BUG] CMake: add_library cannot create ALIAS target "Boost::headers" [...]

### ISSUE THREAD

**Issue by EricCousineau-TRI** [pybind/pybind11#2607]
## Issue description

On my system, on 0b9acc40, I get this error:
```
  add_library cannot create ALIAS target "Boost::headers" because target
  "Boost::boost" is IMPORTED.
```

## Reproducible example code

~Not sure if this is fully reproducible, but this is what I have on Ubuntu 18.04:~

Here's the workflow from scratch using `ubuntu:18.04` in docker:

```
$ docker image ls ubuntu:18.04 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              18.04               56def654ec22        3 weeks ago         63.2MB
$ docker run -it --rm ubuntu:18.04
# apt update
# apt install -y build-essential cmake git libboost1.65-dev python3-dev python3-pytest
# git clone https://github.com/pybind/pybind11
# cd pybind11/
# git log -n 1 --oneline --no-decorate
0b9acc40 fix: chapters in PDF again (#2606)
# mkdir build && cd build
# cmake ..
-- The CXX compiler identification is GNU 7.5.0
...
-- pybind11 v2.6.0 
-- CMake 3.10.2
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
...
-- Boost version: 1.65.1
CMake Error at tests/CMakeLists.txt:231 (add_library):
  add_library cannot create ALIAS target "Boost::headers" because target
  "Boost::boost" is IMPORTED.
```

If I disable this branch (e.g. `if(FALSE)` instead), then it at least configures well:
https://github.com/pybind/pybind11/blob/0b9acc4009afdda427b5f151a67d500216707dc1/tests/CMakeLists.txt#L229

**Comment by henryiii** [comment]
Yuck, old CMake. 3.11 got _much_ better with `IMPORTED INTERFACE` targets, and started allowing this (not sure why this was ever disallowed...). But you are on 3.10. Good catch.

**Comment by henryiii** [comment]
See the first entry here: https://cmake.org/cmake/help/latest/release/3.11.html#other

:/
