### ISSUE TITLE
Receiving a non-copyable object in a Python callback

### ISSUE THREAD

**Issue by empyrical** [pybind/pybind11#261]
Hey!

The docs say for receiving a class in Python that has a deleted/private copy constructor you need to set a proper return value policy - I can see how to do this when `.def()`ining a function and its return value, but I am not sure how to do this when receiving an instance of a non-copyable object as an argument in a Python callback. Unfortunately for now, trying to receive the object causes a segfault.

**Comment by wjakob** [comment]
It's useful to be conscientious about lifetimes and potential issues where one side deletes an object that is still used by the other side.
What you mention sounds like a potential use case for ``keep_alive``, but it's hard to say more without seeing a minimal example here which reproduces the issue.

**Comment by empyrical** [comment]
Sorry, should have done that from the get-go!

I'm trying to put a callback into the Qt function [`qInstallMessageHandler`](https://github.com/qt/qtbase/blob/5.7/src/corelib/global/qlogging.h#L191), here's a link to the class definition:

https://github.com/qt/qtbase/blob/5.7/src/corelib/global/qlogging.h#L62

And here's what the `Q_DISABLE_COPY` macro expands to:

```c++
#define Q_DISABLE_COPY(Class) \
    Class(const Class &) Q_DECL_EQ_DELETE;\
    Class &operator=(const Class &) Q_DECL_EQ_DELETE;
```

I know it's just this class causing a problem, because it works fine if I try making a callback with just the message text and the enum arguments.

**Comment by wjakob** [comment]
Can you create a small self-contained example (e.g. a dummy class whose constructor has the same signature) that compiles without the Qt dependency? You can take a look at some closed issues to get an idea of what I mean.

**Comment by empyrical** [comment]
Something weird must be happening in Qt internals because in this tiny example, the missing copy constructor gets caught at compile time rather than causing a crash at run time:

```c++
#include <functional>

#include <pybind11/pybind11.h>
#include <pybind11/functional.h>

namespace py = pybind11;

class UncopyableClass {
    UncopyableClass(const UncopyableClass &);
    UncopyableClass &operator=(const UncopyableClass &);
public:
    UncopyableClass() {}
};

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 bug exaple");

    // Uncopyable class can still be instantiated from python
    py::class_<UncopyableClass> UncopyableClass_class(m, "UncopyableClass");
    UncopyableClass_class.def(py::init<>());

    // This will fail on compile
    m.def("send_uncopyable", [](std::function<void(UncopyableClass)> cb) {
        UncopyableClass uncopyable;
        cb(uncopyable);
    });

    return m.ptr();
}
```

Will also work fine if I pass through an `UncopyableClass *` instead! So perhaps there may be something I can do to get this to work.

**Comment by wjakob** [comment]
I think you are missing the ``= delete``, no?

**Comment by empyrical** [comment]
Forgot those. Edited them in; it still fails unfortunately.

**Comment by wjakob** [comment]
Ok, upon second look I think I spot the issue. When you bind pybind functions involving non-reference/pointer arguments, a copy of the argument made internally for tricky implementation reasons. Your class doesn't allow this, thus the compilation error. Use pass-by-reference or pointer semantics to avoid this.

**Comment by empyrical** [comment]
Yeah I just managed to get this working! Made my callback take a pointer and it worked great. Thank you!

**Comment by ikolev21** [comment]
I just noticed that passing by non-const reference also won't work, probably because of that internal copy. A non-const pointer does work.

**Comment by ikolev21** [comment]
By "not working" I meant that the callback cannot modify the original value, even though it is passed by non-const reference. Access to the original value only works when it's passed by non-const pointer.
