### ISSUE TITLE
[QUESTION] How to write the binding code for a c++ function that takes char * and return a std::string

### ISSUE THREAD

**Issue by ruiyang00** [pybind/pybind11#2615]
![rc4-2](https://user-images.githubusercontent.com/37881189/96821704-4c13d380-13dd-11eb-9b85-28f807da2db3.png)
![rc4-1](https://user-images.githubusercontent.com/37881189/96821777-782f5480-13dd-11eb-9a10-a26cf1d1600a.png)
Hello All, I have a cipher function inside the RC4 class that takes char* and returns std::string. I am wondering how should I write 

the binding code. Thank you!!! I am trying return the string to python code. I have searched the Issues, I do not see any solution to my situation!!!

**Comment by bstaletic** [comment]
Pybind doesn't support pointers-as-arrays in bindings. Wrap that function call in a lambda that:

- takes a `py::str` or `py::bytes`
- extracts the `char*` with C API
- calls `cipher`

**Comment by YannickJadoul** [comment]
@bstaletic I thought there was an exception for `char *` and `const char *` conversions from `str` (and maybe `bytes`)?

What's the error you get?

**Comment by ruiyang00** [comment]
Below is my c++ code:
```  
class RC4{
          
           char* cipher(char *text) {
                int i = 0;
                int j = 0;
                 char* ciphertext = new char[strlen(text)];
 
                for(size_t n = 0, len = strlen(text); n < len; n++) {
                     i = (i + 1) % N;
                     j = (j + S[i]) % N;

                     swap(&S[i], &S[j]);

                     int rnd = S[(S[i] + S[j]) % N];
               
                     std::cout<<"This is rnd: "<< rnd<< "\n";
            
                     ciphertext[n] = rnd ^ text[n];    

                  }
                  return ciphertext;
            }

}
```

below is my binding code:

```
PYBIND11_MODULE(example, m) {
py::class_<RC4>(m, "RC4")
        .def(py::init<>())
        .def("cipher", [](RC4 &self) -> py::bytes{
            return py::bytes(self.cipher())
        }); 
}
```

I am getting an error 

![rc4-3](https://user-images.githubusercontent.com/37881189/96929129-84afbd80-146e-11eb-9583-480a30533050.png)

**Comment by YannickJadoul** [comment]
@ruiyang00, well, if you read the error, it says you need to pass an argument to the `RC4::cipher` function. And you need a semicolon. These are plain C++ errors, unrelated to pybind11.

**Comment by ruiyang00** [comment]
@YannickJadoul @rolandd @Dekken 
 Really appreciate your guys time!
I am very new to pybind11. I do not know how to intercept the args passed from python to C++.
in python
```
r = RC4();
r.cipher("hello");
```
In pybind11:
How should I get the hello in pybind11 binding and pass "hello" string to my C++ cipher()?
becuase there was a issue with the utf-8 encoding between C++ and python. I read the pybind11 documentation, but there isn't much info that fit my situation.

**Comment by YannickJadoul** [comment]
> I read the pybind11 documentation, but there isn't much info that fit my situation.

https://pybind11.readthedocs.io/en/stable/basics.html#creating-bindings-for-a-simple-function

> all details regarding the function’s parameters and return value were automatically inferred using template metaprogramming.

I.e., make sure the function (in the form of a lambda, in your case) you're binding takes a parameter of the right type.

pybind11 automatically converts these types for you: https://pybind11.readthedocs.io/en/stable/advanced/cast/strings.html

**Comment by ruiyang00** [comment]
@YannickJadoul thank you! I think we can close this Issue!

**Comment by YannickJadoul** [comment]
Thanks for letting me know, @ruiyang00! :-)
