### ISSUE TITLE
Dealing with list of unique_ptr

### ISSUE THREAD

**Issue by romainthomas** [pybind/pybind11#263]
I have the following method:

```cpp
std::list<std::unique_ptr<foo>> bar(const std::string& filename) {
...

return std::move(result);
}
```

I tried to bind it as follow:
```cpp
void init(py::module& m) {
  m.def("bar", &bar, py::return_value_policy::move);
}
```
But ``pybind11`` failed...

**Comment by wjakob** [comment]
This boils down to a C++ misunderstanding: you should never try to move the (local) result of a function. Return value optimization does this for you, and even more efficiently.  The move return value policy is for other cases.

**Comment by romainthomas** [comment]
Actually this code is perfectly right:
```cpp
std::list<std::unique_ptr<Binary>> parse(const std::string& filename) {
    std::list<std::unique_ptr<Binary>> binaries_parsed = Binary::parse(filename).get_build();
    return std::move(binaries_parsed);
}
```

**Comment by wjakob** [comment]
http://stackoverflow.com/questions/14856344/when-should-stdmove-be-used-on-a-function-return-value

**Comment by romainthomas** [comment]
Thanks :+1:

**Comment by wjakob** [comment]
This is also helpful: http://stackoverflow.com/questions/11817873/using-stdmove-when-returning-a-value-from-a-function-to-avoid-to-copy

**Comment by romainthomas** [comment]
I removed the ``std::move`` from my method but I still have the problem with ``std::list<std::unique_ptr<T>>``

**Comment by wjakob** [comment]
The usual rules apply -- if you'd somebody to take a serious look, please post a minimal self-contained example which triggers the issue. Other resolved tickets on the tracker can serve as a reference.

**Comment by romainthomas** [comment]
This is the following example:
```cpp
#include <iostream>
#include <string>
#include <list>
#include <memory>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

std::list<std::unique_ptr<int>> foo(void) {
    std::list<std::unique_ptr<int>> a;
    for (uint32_t i = 0; i < 32; ++i) {
        a.emplace_back(new int(i));
    }
    return a;
}

void init_module(pybind11::module &m) {

  m.def("foo", &foo);
}

PYBIND11_PLUGIN(myModule) {

  pybind11::module myModule("myModule");

  init_module(myModule);

  return myModule.ptr();
}


int main()
{
  std::list<std::unique_ptr<int>> bar = foo();
  for (const auto& i : bar) {
      std::cout << std::to_string(*i) << std::endl;
  }
}
```

**Comment by wjakob** [comment]
Great -- one more detail: what's the expected output and failure case on your machine? (e.g. crash?)

**Comment by romainthomas** [comment]
I updated my issue with the error. And I expected to have a Python ``list`` of  ``int`` *reference*

**Comment by wjakob** [comment]
Ok, I understand your issue here now (and I can reproduce it).

I fear the problem is really a design decision of pybind11: the default STL bindings make copies whenever creating a return value or parameter, so it's fundamentally incompatible with the idea of passing around unique pointers.

There is one alternative, which is to mark ``std::list<std::unique_ptr<int>>`` as *opaque* and create your own bindings for that. You can read all about it in the docs.

**Comment by romainthomas** [comment]
Ok thanks for your answer.
