### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [pybind/pybind11#2630]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: http://graylab.jhu.edu/RosettaCon2016/PyRosetta-4.pdf

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by henryiii** [comment]
I'm not sure where that file can be found now, I've asked around, and I've given the repo above a star. :)

**Comment by bstaletic** [comment]
Web archive has a few snapshots: https://web.archive.org/web/20200414114038/https://graylab.jhu.edu/RosettaCon2016/PyRosetta-4.pdf

**Comment by Kristine1975** [comment]
Looks like it's here now: https://graylab.jhu.edu/Sergey/2016.RosettaCon/PyRosetta-4.pdf

**Comment by henryiii** [comment]
Thanks! Fixed.
