### ISSUE TITLE
[BUG] Cannot import members of submodules defined with .def_submodule

### ISSUE THREAD

**Issue by SvenMarcus** [pybind/pybind11#2639]
## Issue description

I'm using pybind11 with scikit-build and CMake. I am trying to implement a Python module with submodules.
When I try to import members from the submodules I get a `ModuleNotFoundError`. However, I can use the members of submodules when I access them using the entire path (see example for a better idea of what I mean).

## Reproducible example code

To rule out any major mistakes on my end I have extended the scikit-build example from https://github.com/pybind/scikit_build_example (most of the code omitted for readability)

The module definition:
```cpp
#include <pybind11/pybind11.h>
#include <iostream>

namespace py = pybind11;

PYBIND11_MODULE(_core, m)
{ 
    py::module_ submodule = m.def_submodule("my_submodule");
    submodule.def("hello_submodule", []()
    { std::cout << "Hello from submodule" << std::endl; });
}

```

The package's `__init__.py`:
```python
from ._core import __doc__, __version__, add, subtract, my_submodule
```

### Working examples
Now from Python I can do the following:
```
import scikit_build_example
scikit_build_example.my_submodule.hello_submodule()
# hello from submodule
```

or
```python
import scikit_build_example
from scikit_build_example import my_submodule
my_submodule.hello_submodule()
# hello from submodule
```

### Not working
(Updated, because my initial example was wrong)

```python
import scikit_build_example
import scikit_build_example.my_submodule
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ModuleNotFoundError: No module named 'scikit_build_example.my_submodule'
```

or

```python
import scikit_build_example
from scikit_build_example.my_submodule import hello_submodule
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ModuleNotFoundError: No module named 'scikit_build_example.my_submodule'
```

## Additional information

Python version: 3.8
Pybind11 version: 2.6

**Comment by YannickJadoul** [comment]
@SvenMarcus As far as I know, this wouldn't work in pure Python either (but please give it a try if you want to know for sure; I might be wrong).

The correct way to write this should be `from scikit_build_example.my_submodule import hello_submodule`, I would think?

**Comment by YannickJadoul** [comment]
E.g., see this:

```
>>> from scipy import signal
>>> dir(signal)
[<...>, 'chirp', <...>]
>>> from signal import chirp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'chirp'
>>> from scipy.signal import chirp
>>> 
```

**Comment by SvenMarcus** [comment]
You're right the example I provided doesn't work.
However `from scikit_build_example.my_submodule import hello_submodule` produces the same error.

**Comment by YannickJadoul** [comment]
Oh, it does? Let me try, then!

**Comment by YannickJadoul** [comment]
Right, I can reproduce, but this does work:

```
from scikit_build_example._core.my_submodule import hello_submodule
```

I guess Python first goes looking for the submodule, without loading the main module? So it doesn't really know about `scikit_build_example` having this submodule? I'm sure this import behavior should be documented somewhere, but ... ([this](https://docs.python.org/3/reference/import.html) might be a good start?). At any rate, you're wrapping extension modules with pure Python, so it's maybe not unexpected that there's a slight disconnect?

I would suggest adding a `scikit_build_example/my_submodule/__init__.py` where you could do the same as in `scikit_build_example/__init__.py`; i.e., `from ._core.my_submodule import *`? This should work, as you then have a full Python wrapper around the native C extension.

**Comment by SvenMarcus** [comment]
I have tried what you suggested, that seems to produce even more errors:
```
 import scikit_build_example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcus/Documents/Projects/scikit_build_example/Python/venv/lib/python3.8/site-packages/scikit_build_example-0.0.1-py3.8-macosx-10.15-x86_64.egg/scikit_build_example/__init__.py", line 2, in <module>
    from ._core import *
ImportError: ModuleNotFoundError: No module named 'scikit_build_example.my_submodule._core'

At:
  /Users/marcus/Documents/Projects/scikit_build_example/Python/venv/lib/python3.8/site-packages/scikit_build_example-0.0.1-py3.8-macosx-10.15-x86_64.egg/scikit_build_example/my_submodule/__init__.py(1): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(783): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap>(961): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1101): create_module
  <frozen importlib._bootstrap>(556): module_from_spec
  <frozen importlib._bootstrap>(657): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  /Users/marcus/Documents/Projects/scikit_build_example/Python/venv/lib/python3.8/site-packages/scikit_build_example-0.0.1-py3.8-macosx-10.15-x86_64.egg/scikit_build_example/__init__.py(2): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(783): exec_module
  <frozen importlib._bootstrap>(671): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  <stdin>(1): <module>
```

I have also tried inside the submodule's `__init__`
```python
from . import hello_submodule
```

That results in a circular import:
```
import scikit_build_example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcus/Documents/Projects/scikit_build_example/Python/venv/lib/python3.8/site-packages/scikit_build_example-0.0.1-py3.8-macosx-10.15-x86_64.egg/scikit_build_example/__init__.py", line 2, in <module>
    from ._core import *
ImportError: ImportError: cannot import name 'hello_submodule' from partially initialized module 'scikit_build_example.my_submodule' (most likely due to a circular import) (/Users/marcus/Documents/Projects/scikit_build_example/Python/venv/lib/python3.8/site-packages/scikit_build_example-0.0.1-py3.8-macosx-10.15-x86_64.egg/scikit_build_example/my_submodule/__init__.py)

At:
  /Users/marcus/Documents/Projects/scikit_build_example/Python/venv/lib/python3.8/site-packages/scikit_build_example-0.0.1-py3.8-macosx-10.15-x86_64.egg/scikit_build_example/my_submodule/__init__.py(1): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(783): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap>(961): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1101): create_module
  <frozen importlib._bootstrap>(556): module_from_spec
  <frozen importlib._bootstrap>(657): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  /Users/marcus/Documents/Projects/scikit_build_example/Python/venv/lib/python3.8/site-packages/scikit_build_example-0.0.1-py3.8-macosx-10.15-x86_64.egg/scikit_build_example/__init__.py(2): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(783): exec_module
  <frozen importlib._bootstrap>(671): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  <stdin>(1): <module>

```

**Comment by YannickJadoul** [comment]
Right, sorry, I should have actually tested that, instead of just assuming that would work!

Putting
```
from .._core.my_submodule import *
```
in `src/scikit_build_example/my_submodule/__init__.py` does work for me, though.

That's getting ugly very fast (you need 3 dots for a submodule of a submodule, etc), but I'm not sure if there's a better way. Maybe @henryiii would know or have experience with this?

**Comment by henryiii** [comment]
I don't think there's a better way. Submodules in an extension are not looked up if you write `import a.b.c` - this is a promise in Python that there really is a `a/b/c.{pyc?,so}` on disk. You can't write an extension module (in pybind11 or pure C) that only provides `a.so` or `a/b.so` and satisfies the above statement.

The "correct" way to do this is to split up your extension module the same way as the import statement on disk. The common workaround is to do what was suggested, and add python files that mimic the structure and import from the extension.

**Comment by YannickJadoul** [comment]
> Submodules in an extension are not looked up if you write `import a.b.c`

They are, though. I can write `from parselmouth.praat import call` in my project, and this does load (and execute) the full `parselmouth` module but will also give you `call`.
It's also shown here, since `from scikit_build_example._core.my_submodule import hello_submodule` worked.

I think the issue here is mixing the Python modules (where I *think*, only the submodule's `__init__.py` or `submodule.py` is loaded/executed) and C extension modules (where in the original use case, you'd need to load the `__init__.py` of the main module to know there's a submodule).

**Comment by SvenMarcus** [comment]
Could this be a setuptools/scikit-build problem? Before I followed the pybind11 scikit-build example I omitted the `packages`, `package_dir` and `cmake_install_dir` arguments in `setup.py` and I could install just fine with `python setup.py install`.
Importing with `from module.submodule import thing" worked fine then. But without these arguments when I built a wheel package instead of installing directly and then installing the wheel it would be installed to the top level directory of my virtualenv instead of the site-packages folder resulting in Python not being able to find the library.

So I guess @YannickJadoul is probably right about it being something weird with the Python/Extension module interaction, because setuptools tries to wrap everything in a Python module.

Are there other/better possibilities to create a distributable Python package that also requires building the library with CMake?

**Comment by YannickJadoul** [comment]
> Could this be a setuptools/scikit-build problem?

No, I don't really think so. There's just a difference between a folder with `__init__.py` and just the `.so`/`.pyd` file: if you didn't wrap it in a pure-Python package, that compiled `.so` file is just the module, so it's at the top-level. Just like if you would use `setuptools` to install a single `.py` file, I think.

> Are there other/better possibilities to create a distributable Python package that also requires building the library with CMake?

I don't think that's going to solve anything. Again, it's about the structure of the packages and how Python looks for submodules, I believe. Not sure how another build tool would solve this.

**Comment by YannickJadoul** [comment]
I'm going to assume this was solved. If not, please let us know and reopen!

**Comment by mattip** [comment]
I opened an issue with CPython about [creating submodules](https://bugs.python.org/issue43367). Perhaps worth adding a note in the documentation of [`def_submodule`](https://github.com/pybind/pybind11/blob/c0fbb02c9fc1fe969f2740253469499385e6dc20/include/pybind11/pybind11.h#L972) that its use can be problematic.

**Comment by YannickJadoul** [comment]
@mattip, thanks!

That's kind of funny, because pybind11's way of adding submodules in a purely C extension does work, for me. I can do the following in my project (where the `praat` submodule is created through `def_submodule`):

```pycon
>>> from parselmouth.praat import call
>>> from parselmouth import praat
>>> praat
<module 'parselmouth.praat'>
```

For the record, pybind11 is doing a combination of `PyImport_AddModule(full_name.c_str())` and `PyObject_SetAttrString` in `def_submodule`. Would maybe this full module name be important?

**Comment by mattip** [comment]
In the pytorch issue pytorch/pytorch#38137 they mention `_onnx` as one of the problematic modules. It is added [via `def_submodule`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/onnx/init.cpp#L8), and its attributes cannot be pickled without the `sys.module[s] = module` trick in pytorch/pytorch#53107

**Comment by mattip** [comment]
Can you do `s = pickle.dumps(call)` successfully?

**Comment by YannickJadoul** [comment]
> Can you do `s = pickle.dumps(call)` successfully?

Hmmm, no, because it's complaining that "TypeError: can't pickle PyCapsule objects" (weird thing going on with how `PyCFunction`s are used in pybind11).

I only have functions in that submodule, so I've never tried any pickling.

> For the record, pybind11 is doing a combination of `PyImport_AddModule(full_name.c_str())` and `PyObject_SetAttrString` in `def_submodule`.

If I understand correctly, `PyImport_AddModule` does a [weird'ish thing](https://docs.python.org/3/c-api/import.html#c.PyImport_AddModule), already adding the module in `sys.modules`. But if pytorch uses `def_submodule`, that's most likely irrelevant.

But PyTorch is mixing Python files and the C extension, I assume? That's what this issue was about, showing (C)Python does weird things to resolve submodules, then.

**Comment by mattip** [comment]
OK, maybe there is something else going on. Should I open a new issue?

**Comment by YannickJadoul** [comment]
> OK, maybe there is something else going on. Should I open a new issue?

Possibly, yes. If that's easier to discuss, sure, feel free to open a new one :-)
