### ISSUE TITLE
How to convert pybind11::array to std::string or std::string pointer?

### ISSUE THREAD

**Issue by sun1638650145** [pybind/pybind11#2649]
```c++
void *ptr = const_cast<void *>(y.data(0));
const char *c = static_cast<const char*>(ptr);
std::cout << c << c+4 << c+8 << c+12 << c+16 << std::endl;
```

I can only convert to a char pointer, and it seems that the length of the memory block mapped by the pointer is not correct.

```c++
void *ptr = const_cast<void *>(y.data(0));
const std::string *s = static_cast<const std::string*>(ptr);
```

 Converted to string pointer, the output is blank.

**Comment by YannickJadoul** [comment]
First of all, your issues don't seem to be related to pybind11.

Secondly, this is horribly wrong C++, and full of undefined behavior! You can't just point at some data and say "this is a `std::string`"! `std::string` is a class that needs to be constructed to produce a valid object. Please please please check out basic C++.

Thirdly, there's a template you're asked to fill out.

Fourthly, that template asks/suggests you to pass by Gitter if you have a question that's maybe not really a deep pybind11 issue. Please don't ignore that.
