### ISSUE TITLE
[BUG] `malloc(): unsorted double linked list corrupted` when instantiating a class inside pybind11

### ISSUE THREAD

**Issue by knewter** [pybind/pybind11#2660]
## Issue description

I am writing a small pybind11 wrapper to a proprietary C library (the VisageSDK). When I instantiate a `VisageTracker` (one of its classes), I get `malloc(): unsorted double linked list corrupted`.

I've attached a gist that has all of the information I can provide. I discussed with @bstaletic in gitter and he was very helpful, but ultimately he [counseled me to create a bug report](https://gitter.im/pybind/Lobby?at=5faff24cc10273610a060020).

## Reproducible example code

Because the project cannot be built without the proprietary VisageSDK, I can't exactly give a useful repo to reproduce the error on. In the following gist, I have included all of the relevant files:

https://gist.github.com/knewter/98df1c979e4e5b7b5f08478d3cf86261

**Comment by bstaletic** [comment]
Try the following two things:

1. `python -c '__import__('visage').Tracker()'`
2. If the above still fails, try running `PYTHONMALLOC=malloc python -c '__import__('visage').Tracker()`
3. Finally, `PYTHONMALLOC=malloc python -c '__import__('visage').Tracker()`

**Comment by knewter** [comment]
(1) works, but I don't understand why or how:

```
josh@josh-VirtualBox:~/visage-hls-gaze-detector/src/hello_python/build$ python3 -c "__import__('visage').Tracker()"
/dev.vlc
/home/josh/visage-hls-gaze-detector/samples/FacialFeaturesTrackerHigh.cfg
destroying tracker
josh@josh-VirtualBox:~/visage-hls-gaze-detector/src/hello_python/build$ python3 hello_python.py 
['hello_python.py']
getting tracker
/dev.vlc
/home/josh/visage-hls-gaze-detector/samples/FacialFeaturesTrackerHigh.cfg
malloc(): unsorted double linked list corrupted
Aborted (core dumped)
```

**Comment by knewter** [comment]
ok, if I do not import cv2 then the code works fine. As soon as I import cv2, even though I do not use it, I get this `malloc` error.

**Comment by knewter** [comment]
if I import cv2 but do not call `Tracker()`, it works fine as well. So somehow both importing cv2 and instantiating Tracker causes this

**Comment by bstaletic** [comment]
Here's another idea - let's get pybind11 out of the picture. Try to compile this:

```c++
#include <Python.h>
#include "opencv2/opencv.hpp"
#include "opencv2/videoio/videoio_c.h"
#include <stdio.h>
#include "visageVision.h"

using namespace std;
using namespace cv;
using namespace VisageSDK;

namespace VisageSDK
{
  // all visage|SDK calls must be in visageSDK namespace
  void initializeLicenseManager(const char *licenseKeyFileFolder);
} // namespace VisageSDK

class Foo
{
public:
  Foo()
  {
  }
};

class Tracker
{
public:
  Tracker()
  {
    initializeLicenseManager(getenv("VISAGE_LICENSE_PATH"));
    cout << getenv("VISAGE_LICENSE_PATH") << endl;
    cout << getenv("PYTRACKER_DEFAULT_CONFIGURATION_FILE_PATH") << endl;
    // Instantiating a `Foo` doesn't cause any problems
    // foo = new Foo();
    // But instantiating a `VisageTracker` causes the malloc issue
    tracker = new VisageTracker(getenv("PYTRACKER_DEFAULT_CONFIGURATION_FILE_PATH"));
    // raw_tracker->setTrackerConfiguration(getenv("PYTRACKER_CONFIGURATION_FILE_PATH"));
    // tracker = shared_ptr<VisageTracker>(raw_tracker);
  }
  ~Tracker()
  {
    cout << "destroying tracker" << endl;
  }

private:
  VisageTracker *tracker;
  Foo *foo;
};

typedef struct {
    PyObject_HEAD
    Tracker* tracker;
} PyTracker;

static void
PyTracker_dealloc(PyTracker *self)
{
    self->tracker->~Tracker();
    Py_TYPE(self)->tp_free((PyObject *) self);
}

static PyObject *
PyTracker_new(PyTypeObject *type, PyObject *args, PyObject *kwds)
{
    PyTracker *self = (PyTracker *) type->tp_alloc(type, 0);
    if (self != NULL) self->tracker = new Tracker;
    return (PyObject *) self;
}

static PyTypeObject TrackerType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "visage.Tracker",
    .tp_basicsize = sizeof(PyTracker),
    .tp_itemsize = 0,
    .tp_dealloc = (destructor) PyTracker_dealloc,
    .tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
    .tp_new = PyTracker_new,
};

static PyModuleDef visagemodule = {
    PyModuleDef_HEAD_INIT,
    .m_name = "visage",
    .m_size = -1,
};

PyMODINIT_FUNC
PyInit_visage(void)
{
    PyObject *m;
    if (PyType_Ready(&TrackerType) < 0)
        return NULL;

    m = PyModule_Create(&visagemodule);
    if (m == NULL)
        return NULL;

    Py_INCREF(&TrackerType);
    if (PyModule_AddObject(m, "Tracker", (PyObject *) &TrackerType) < 0) {
        Py_DECREF(&TrackerType);
        Py_DECREF(m);
        return NULL;
    }

    return m;
}
```

**Comment by knewter** [comment]
I tried this but I seem to have done something wrong. When I import the generated .so file, I get the following:

```
ImportError: /home/josh/visage-hls-gaze-detector/src/hello_python_no_pybind11/build/visage.cpython-38-x86_64-linux-gnu.so: invalid ELF header
```

I made a gist of the relevant files here: https://gist.github.com/knewter/76ccf2dbe1eb218dc33c04910c728f2b

**Comment by knewter** [comment]
It compiled fine, but I ended up with an error when I tried to import it in python. This was a clean build; made a new directory, put your c++ file in it and a tiny python file, made the CMakeLists.txt, and compiled it. Compilation worked fine, but importing led to that error. I've never had that happen before when building a c python module :(

**Comment by YannickJadoul** [comment]
@knewter Well, something's definitely going wrong during your build process. "invalid ELF header" is nothing that pybind11 is cause or could cause...

As long as we don't have a reproducing example, there's not a lot more we can do, to be fair.

**Comment by knewter** [comment]
It turns out the `invalid ELF header` was because the library that I built in CMake was not `SHARED`. Once I figured that out from some 2011 StackOverflow post, I was able to build your "no-pybind11" project. It has the same malloc error:

```sh
josh@josh-VirtualBox:~/visage-hls-gaze-detector/src/hello_python_no_pybind11/build$ python3 hello_python_no_pybind11.py 
['hello_python_no_pybind11.py']
getting tracker
<module 'visage' from '/home/josh/visage-hls-gaze-detector/src/hello_python_no_pybind11/build/visage.cpython-38-x86_64-linux-gnu.so'>
/dev.vlc
/home/josh/visage-hls-gaze-detector/samples/FacialFeaturesTrackerHigh.cfg
got tracker
destroying tracker
malloc(): unsorted double linked list corrupted
```

**Comment by bstaletic** [comment]
In that case we can close this. It's clearly not pybind11's fault, as the error happens even without this library. I guess you should open a bug report for visage.

**Comment by YannickJadoul** [comment]
Thanks for figuring out and reporting back on it, @knewter!
