### ISSUE TITLE
[BUG] cmake lead to missng symbols when linking against `pybind11::embed` while preloading python with `find_package(Python3)`

### ISSUE THREAD

**Issue by jbigot** [pybind/pybind11#2664]
Pre-loading python3 in cmake leads to the target not being linked against python library.
```
find_package(Python3 REQUIRED COMPONENTS Interpreter Development)
find_package(pybind11 2.3.0 REQUIRED)
add_library(my_target [...])
target_link_libraries(my_target pybind11::embed)
```

I believe this is due to the following line linking against `Python3::Python3` in that case instead of `Python3::Python`provided by the cmake module
https://github.com/pybind/pybind11/blob/02746cb69f202579efb0004e55ac7984a5c466bb/tools/pybind11NewTools.cmake#L147
https://github.com/pybind/pybind11/blob/02746cb69f202579efb0004e55ac7984a5c466bb/tools/pybind11NewTools.cmake#L151

**Comment by knarfS** [comment]
I just opened PR #2662 which should fix that big.

**Comment by jbigot** [comment]
@knarfS you were faster than me, I opened https://github.com/pybind/pybind11/pull/2665 later than you it seems :smile:
