### ISSUE TITLE
[QUESTION]  how to solve binary type data?

### ISSUE THREAD

**Issue by dockerzhang** [pybind/pybind11#2674]
I have a method defined by CPP, which returns a `char` list with `0/1`  binary data（eg. `0101`）, I can not get the real value after parsed by `pybind11`. I tested the flowing case.

test case which can get  `aa`:
```
data = new char[2 + 1];
data[2] = '\0';
memset(data, 'a', 2);
return data
```

test case which can not get  `11`, same to `0`:
```
data = new char[2 + 1];
data[2] = '\0';
memset(data, 1, 2);
return data
```

**Comment by bstaletic** [comment]
>     data = new char[2 + 1];
>     data[2] = '\0';
>     memset(data, 1, 2);
>     return data

That does correctly write `\x01\x01\x00` into `data`. What you're failing to realize is that you're then printing `\x01` is a character, which is "start of heading", which likely is not printable. If you want to write characters, use `'1'` in your `memset()` call.

If I guessed incorrectly, provide A LOT more information, like how you're consuming the data, how are you using pybind11, what output are you expecting and what output do you actually get. Right now, this issue contains a bit of C code which isn't enough.

Reopen if my initial guess was wrong and provide more data.

**Comment by dockerzhang** [comment]
@bstaletic  thanks for your reply.  

In our case,  the `data_`  returned by `GetData`  binary data (like `101001....`),  the main code snippet following:
``` cpp
const char* Message::GetData() const { return data_; }

void Message::copyData(const char* data, uint32_t datalen) {
  if (data == NULL) {
    data_ = NULL;
    datalen_ = 0;
  } else {
    datalen_ = datalen;
    data_ = new char[datalen];
    memset(data_, 0, datalen);
    memcpy(data_, data, datalen);
  }
}
```

After the `GetData` ( exposed by `pybind11` ) get the binary value,  it will pass the result value to `ParseTDMsg` method (`data` param, and exposed by `pybind11` ),  and `ParseTDMsg` caught type error exception. 

```cpp

bool TDMsg::ParseTDMsg(const char* data, uint32_t data_length) {
....
}

```

It runs correctly if only using CPP, and gets an error after exposed by `pybind11`. I am wondering the returned binary `char* ` value how to pass to another method with `char* ` param correctly in PyBind11?

**Comment by YannickJadoul** [comment]
@dockerzhang We're still going to need a minimal example where you show how you bind this with pybind11, and how you call it from Python, showing that it doesn't work. Please make it something we can easily compile and try out ourselves.

Meanwhile, do take care that pybind11 considers `char*` to be a string. If you're expecting bytes from Python, have a look at e.g. `py::bytes`.

**Comment by dockerzhang** [comment]
@YannickJadoul  After my forward test, I found it's caused by considering `char*` as a string in our case.
but do you know how to configure the defined CPP method to return `bytes` value for `char*`? 
the `py::bytes`  example methods are defined in one pybind11 CPP file.

I want to add some configure in `pybind_test.cpp` for replacing default string to `byte`.
raw `GetData` in users.cpp, which can not change.
``` cpp 
const char* Message::GetData() const { return data_; }
```

exposed `GetData` in pybind_test.cpp, which will be used by python client.
``` cpp 
.def("GetData", &Message::GetData)
```

**Comment by YannickJadoul** [comment]
And as as what type do you want to use that in Python, then?

As I said, have a look at `py::bytes`. It has a straightforward constructor from `const char *`. So if you want to return `bytes`, just wrap your method in a lambda.
