### ISSUE TITLE
[QUESTION] Embed static python 3.9

### ISSUE THREAD

**Issue by prsolucoes** [pybind/pybind11#2678]
Hi,

How can i build an executable with python 3.9 embedded statically without need shared libraries (so, dylib, dll, etc)?

Thanks.

**Comment by YannickJadoul** [comment]
This is reasonably complicated. See e.g., the already existing issue #2542. All in all, as far we could tell there, it's possible, but not trivial (involving a recompilation of Python, it seems).

At any rate, this is not really something pybind11-specific. I'd propose searching further on Google for "static embedding python" or so. See also e.g. https://github.com/bendmorris/static-python.

Also, for questions like this, please consider asking on [Gitter](https://gitter.im/pybind/Lobby) and search the existing issues, as suggested in the issue template.

**Comment by prsolucoes** [comment]
Ok, But how you distribute your application? You need install python 3.9 on every machine?

**Comment by YannickJadoul** [comment]
I don't know. I have not yet distributed an executable that embeds Python.
But please read the issue I linked to! I there suggested:

> Just curious: if Dependency Walker shows a dependency on PythonXY.dll, would you not be able to just ship that DLL along with the program?

(https://github.com/pybind/pybind11/issues/2542#issuecomment-704190791)
