### ISSUE TITLE
[FEAT] Support __cuda_array_interface__

### ISSUE THREAD

**Issue by mikaeltw** [pybind/pybind11#2694]
Trying to send in a CuPy array (https://cupy.dev/), using `array_t<T>`, you will receive incompatible argument type. Digging a bit in the pybind11 source code one finds that, `array_t<T>` relies on the buffer_protocol (https://docs.python.org/dev/c-api/buffer.html#bufferobjects), which for example CuPy do not. CuPy instead relies on the `__cuda_array_interface__` defined by numba (https://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html). 

My question: Is pybind11 interested in supporting the `__cuda_array_interface__`? 

There has been some recent activity on the matter e.g. in tensorflow (https://github.com/tensorflow/tensorflow/issues/29039). Considering that it is not a normal python buffer, there is some extra code to be written. If yes, could you point me to where a good start would be? Create a new .h file like `buffer_info.h` and then add it to `attr.h` and use it as a separate interface or include it alongside already existing interfaces.

**Comment by heyer2** [comment]
The problem is that `__cuda_array_interface__ ` refers to data on the GPU. The only way to convert a GPU array to a standard `array_t` is to copy the data to the CPU - something usually sought to be avoided.

**Comment by YannickJadoul** [comment]
Does NumPy support this? `py::array` is meant to be a NumPy array wrapper.

Apart from that, where do you need pybind11 support? Can't you just implement `__cuda_array_interface__` like any other method?

**Comment by mikaeltw** [comment]
> The problem is that `__cuda_array_interface__ ` refers to data on the GPU. The only way to convert a GPU array to a standard `array_t` is to copy the data to the CPU - something usually sought to be avoided.

Of course, but that is not my suggestion. This feature is provided in CuPy today on the python-side where you can seamlessly transform between numpy-type and and gpu-type, by doing an explicit copy. 


> Does NumPy support this? py::array is meant to be a NumPy array wrapper.

> Apart from that, where do you need pybind11 support? Can't you just implement __cuda_array_interface__ like any other method?

Sorry for being so inexact. Instead of passing around `int_ptr` and extracting the raw data using `getattr`, it would be nice to have a py::device_array_t, which you can extract the info from defined by the __cuda_array_interface__. This is of course just a convenience feature. Since you cannot inherit from `py::array` och `py::array_t` this requires some more work than just a new class. Which is why I wanted opinions and making an interest poll first.

**Comment by YannickJadoul** [comment]
I'm afraid I'm not familiar enough with CUDA/CuPy to know what's necessary, how hard this will be to implement, or how generic and useful for other such an implementation would be.
Do you have some example/documentation/... to look at?

Currently pybind11 doesn't really have anything related (except for common NumPy arrays), so I don't estimate the chances to high that there will be a lot of enthusiasm to include this. An external, plug-in/library for pybind11 (`pybind11_cupy` or so), similar to https://github.com/pybind/pybind11_json or https://github.com/pybind/pybind11_abseil or so, might make more sense, if possible?

**Comment by mikaeltw** [comment]
Since there is currently no C-API definitions for the `__cuda_array_interface__`, I guess that a plug-in, that just implements all needed methods should suffice.

Thanks for the links to the other plug-ins, I might just implement what I need and take it from there.

In RAPIDS (https://rapids.ai/start.html) there might be some interesting examples. 

I CuPy it is just a property of the main class `cupy.ndarray` (https://github.com/cupy/cupy/blob/master/cupy/core/core.pyx). 

Feel free to close the issue.

**Comment by YannickJadoul** [comment]
Thanks, @mikaeltw. Feel free to report back, if you managed to get things working, or if there's maybe something pybind11 could do.
