### ISSUE TITLE
[FEAT] Require runtime-registered type casters to be declared explicitly before use

### ISSUE THREAD

**Issue by jbms** [pybind/pybind11#2695]
Currently, if you don't specialize `type_caster` for a type, pybind11 will use the default implementation based on `type_caster_base`, which handles the default logic for types registered at runtime via `pybind11::class_`.  That works fine assuming you haven't defined a specialization of `type_caster`.

Conversely, if you do specialize `type_caster` for a type `T`, and make sure that specialization is seen by all code that attempts to instantiate `type_caster<T>`, then everything works fine as well.

The problem is that it is very easy to accidentally forget to include the header that defines a necessary specialization of `type_caster` in a single translation unit.  This doesn't get diagnosed by the compiler, but is considered undefined behavior due to violating the "one definition rule".  In practice, depending on the optimization level, and the order in which the object file are specified to the linker, it may either work correctly or fail in a confusing, non-obvious way.

This problem is not limited to pybind11 --- it is an unfortunate problem in C++ generally that occurs any time you specialize a template `X` with a type `T`, where the specialization is not defined in the same header that defines either `X` or `T`.  However, the design of pybind11 makes this bug particularly easy to run into.

One way to prevent this problem would be to eliminate the default `type_caster` definition.  Instead, pybind11 could provide a macro like:

```c++
#define PYBIND11_DECLARE_RUNTIME_TYPE_CASTER(...) \
  namespace pybind11 { \
    namespace detail { \
      template <> struct type_caster<__VA_ARGS__> : type_caster_base<__VA_ARGS__> {}; \
    } \
  }
```

Then users would be required to define a `type_caster` for every type they use, either by using this macro or by explicitly defining a `type_caster` specialization.  Then the guidance would be that if you create a `pybind11::class_` wrapper for a type `MyType` in a source file `my_type.cc`, then create a header `my_type.h` that includes `PYBIND11_DECLARE_RUNTIME_TYPE_CASTER(MyType)`, and include that header from every source file that needs to use conversions to/from `MyType`.

While this would require some work to migrate all existing pybind11 users, I think it is nonetheless worth considering since it would eliminate a significant footgun in pybind11.  A more graceful migration path could be provided by having a macro control whether the existing default definition of `type_caster` is included.  Initially, the default definition could remain but with a deprecation warning.  Or possibly the default definition could remain indefinitely, since potentially the deprecation warning itself would provide a hint that a custom `type_caster` specialization has not been picked up.

**Comment by YannickJadoul** [comment]
I understand your issue, but I'm not ecstatic about a) more macros and b) breaking every pybind11 project that uses `class_` by not making `class_` work as default anymore.

> Then the guidance would be that if you create a `pybind11::class_` wrapper for a type `MyType` in a source file `my_type.cc`, then create a header `my_type.h` that includes `PYBIND11_DECLARE_RUNTIME_TYPE_CASTER(MyType)`, and include that header from every source file that needs to use conversions to/from `MyType`.

My take would be that this is the guidance for the special case where you use custom type_casters, since that tends to be the exception.

The macro might be something interesting, though, as a way to opt-in to this behavior and/or make a diagnostic build.

I guess this is crucial to put in front of @wjakob, though.

**Comment by wjakob** [comment]
Declaring custom type casters is an advanced tool, and as with most advanced tools there are some ways of using them in a dangerous or incorrect way. Inconveniencing the rest of the world to make this feature safer to use is not a path that I would want to follow.
