### ISSUE TITLE
Can't send None to a function accepting std::vector<SomeType>*

### ISSUE THREAD

**Issue by ZoranMilicevic** [pybind/pybind11#2699]
So lets say I have a function:
```
int vectest(std::vector<int>* a){
  int sum = 0;
  if (a == nullptr) return sum;
  for (int elem : *a){
    sum += elem;
  }
  return sum;
}
```

I expose that function
m.def("vectest", &vectest, pybind11::arg("a").none(true));

And in Python when I try to do call the function with None

a = MyModule.vectest(None)

I get

File "test2.py", line 25, in <module>
    a = Cpyth.vectest(None)
TypeError: vectest(): incompatible function arguments. The following argument types are supported:
    1. (a: List[int]) -> int

Is this sending None to a function with such prototype even possible and supported or am I doing something wrong?

**Comment by YannickJadoul** [comment]
The latter. The casters in `stl.h` (currently) don't support null-able pointers. The docs explicitly mention that this only works for custom types: https://pybind11.readthedocs.io/en/stable/advanced/functions.html#allow-prohibiting-none-arguments

The advised way of doing this is using `std::optional` (or adding overload that takes `py::none`).

See also #1760 and #1865.
