### ISSUE TITLE
Dynamic attribute support on class instances

### ISSUE THREAD

**Issue by empyrical** [pybind/pybind11#270]
The feature proposed in PR #180 would be really useful to have (maybe have a way to disable/enable it in the class declaration? I think it has a performance penalty)

Only issue with that is the creator of that PR encountered an incredibly odd bug in Py3.5 that causes some classes (seems to be just the ones with virtual methods in `example12.py`) to sometimes not get picked up by Python's garbage collector -- not sure what's up with that. Just the mere presence of `tp_dictoffset` will break things for some reason.

**Comment by wjakob** [comment]
Sure, it could be an extra flag to py::class_, e.g.

```
py::class_<MyClass>(m, "myClass", py::dynamic_attr)
```

The question is: is there a Python 3 bug? Do you have some kind of a reference to the bug tracker? If not, it should likely be escalated. The other issue is that PR #180 also mentions problems with Python < 3. Do you have an updated version of this PR that addresses these?

**Comment by empyrical** [comment]
> The question is: is there a Python 3 bug? 

Still not sure yet. Gonna make a simple pure python api extension and see if it still happens there.

Weird thing is, if you comment out the instantiation of `ExtendedExample12` in `example12.py`, then `Example12` will destruct fine - it's when that subclass gets instantiated that the destructors will get broken for both.

> The other issue is that PR #180 also mentions problems with Python < 3

It looks like Py2 doesn't have stuff like `PyObject_GenericGetDict` so I'd need to tweak it for that. It actually seemed to work without Getter/Setter funcs and just a dictoffset, but I'm not sure if it's a good idea to do that or not.

**Comment by empyrical** [comment]
Oddly enough, everything seems to work fine if I set `tp_dictoffset` inside of `generic_type::new_instance` rather than `generic_type::initialize`! I still haven't figured out why though, and neither have I been able to recreate the bug using just the CAPI. Quite odd!

**Comment by wjakob** [comment]
hmm, that doesn't seem like the right place to do it :) -- maybe there is some other lingering issue that is really reponsible?

By the way: not setting ``PyObject_GenericGetDict`` etc. may be fine. The ``PyType_Ready`` function configures a lot of sane defaults based on partially specified fields in the type data structure.

**Comment by empyrical** [comment]
Do you have any ideas what parts of pybind11 I could poke around in to find out what's going on with this subclass weirdness? Not even sure where to begin

> By the way: not setting PyObject_GenericGetDict etc. may be fine. The PyType_Ready function configures a lot of sane defaults based on partially specified fields in the type data structure.

Thanks! Had a look at what it does in the Python source.

**Comment by wjakob** [comment]
Just some thought: the calculations involving https://docs.python.org/2/c-api/typeobj.html#c.PyTypeObject.tp_dictoffset are fairly complex. Maybe some other attribute also needs to be set?

Another thought: maybe the dict that goes into that slot actually needs to be created in generic_type::new_instance? (not sure, maybe Python is responsible for this part.)

**Comment by empyrical** [comment]
Tried that as well. Also tried putting it in a custom dict getter function like Boost::Python does and still seems to be weird. I can clean up my code and submit what I've got so far as a PR if you'd like

**Comment by empyrical** [comment]
Put it up - #275

**Comment by wjakob** [comment]
Thanks for the PR. To consider this for merging, the garbage collection issue on Python 3.5 would need to be resolved though.

**Comment by empyrical** [comment]
Figured I'd put it up to possibly make working out a solution easier

**Comment by wjakob** [comment]
Closing this issue, see #275.
