### ISSUE TITLE
[QUESTION] How to overload functions with argument of bool/int

### ISSUE THREAD

**Issue by wyq730** [pybind/pybind11#2706]
How can we overload the two functions like below?

```cpp
void func(int);
void func(bool);
```

Even if we use `overload_cast`, Pybind11 will treat them as the same, so these two functions will not be distinguished in the generated Python interface.

Is there any solution to this problem?

Related discussion: #1625

**Comment by YannickJadoul** [comment]
Please refer to the explanation in the docs. pybind11 does overload resolution if you bind multiple functions to the same name in Python, but this is a distinct concept from `overload_cast`:

- https://pybind11.readthedocs.io/en/stable/classes.html#overloaded-methods
- https://pybind11.readthedocs.io/en/stable/advanced/functions.html#overload-resolution-order

**Comment by wyq730** [comment]
@YannickJadoul 

Thanks for the reply.

Maybe the example was a little confusing, actually the two functions can have different names:

```cpp
void func1(int);
void func2(bool);
```

And if we bind them to the same function name in Python:

```cpp
m.def("func", &func1))
   .def("func", &func2));
```

The overload resolution will not work well. If we call func in Python with a bool argument:

```python
func(False)
```

It will use the `func1` under the hood. Because it doesn't require a conversion from bool to int in Python. But actually I want to use the `func2`.

Does this example make the question clear?

**Comment by YannickJadoul** [comment]
@wyq730 Right, so as I said, it's completely unrelated to `overload_cast` that you mention in the original issue (as explained in the docs).

The issue you yourself linked to does explain that since `issubclass(bool, int)`, the order of overloads is crucial in this case: https://github.com/pybind/pybind11/issues/1625#issuecomment-664016680
