### ISSUE TITLE
[BUG] regression when mixing installed pybind11 with local copy

### ISSUE THREAD

**Issue by henryiii** [pybind/pybind11#2709]
## Issue description

Hi all, since the recent refactor of CMake files (pull request #2370), when setting up include paths, `pybind11_add_module` puts priority on the already installed version of `pybind11 (PYTHON_INCLUDE_DIRS)` instead of the local copy (`pybind11_INCLUDE_DIR`). As an effect, wrong header files are included.

I understand that the documentation of pybind11_add_module says that pybind11 must be properly installed for it to work, but this nevertheless looks like a bug -- why add `pybind11_INCLUDE_DIR` if you expect it to be ignored?

Any idea how to get the old behavior? I found a hacky solution by modifying pybind11_add_module to do

```python
target_link_libraries(${target_name} PRIVATE pybind11::headers pybind11::module)
```
instead of

```python
target_link_libraries(${target_name} PRIVATE pybind11::module)
```

but I hope to find something better. Thanks!

From @ikicic on Gitter.

**Comment by henryiii** [comment]
I probably never thought about this situation, when two copies of pybind11 exist and you want the local one to overide the system one pulled in via the Python directories. The local include property is preceding the target (newer versions of CMake might support this with SYSTEM, but we should fix properly). I believe what we should do here is make a `Python::Headers IMPORTED INTERFACE` target, and stick them on that. Noting this here so I don't forget.

**Comment by ikicic** [comment]
Just to note that my hacky solution may not actually work, as the order of dependencies is not guaranteed (?). For the same reason, would it make sense to simply move `PYTHON_INCLUDE_DIRS` from `pybind11::pybind11` to `pybind11::headers`, to force the order of includes?

**Comment by henryiii** [comment]
The point of `pybind11::headers` is it is _only_ the headers, no `PYTHON_INCLUDE_DIRS`. I think we should make a target `pybind11::python_headers` that has the python includes, and include with that. Targets do respect order, though if you have SYSTEM includes those go to then end but otherwise still respect order (IIRC, and requires your CMake min version to be set above something, I think).

**Comment by henryiii** [comment]
@ikicic Assuming tests pass and I didn't make a mess of it, can you check my branch and see if that fixes it for you? Mismatched installed vs. local pybind11 not something that's very easy to test in CI.
