### ISSUE TITLE
Kernel Restarting: C++ exit error

### ISSUE THREAD

**Issue by nyckmaia** [pybind/pybind11#2712]
I would like to prevent the user of my Python library to access a invalid vector index.
So, here is my simple example:
```
class myClass
{
private:
    std::vector<Note> _note;

public:
    myClass();
    Note& getNote(const size_t noteId);
};
```

```
myClass::myClass()
{
    // Constructor....
    // Allocate _note vector memory...etc...
}

Note& myClass::getNote(const size_t noteId)
{
    if (noteId >= _note.size()) {
        std::cerr << "[ERROR]: Invalid note index" << std::endl;
        exit(0);
    }
    
    return _note[noteId];
}
```
So, I did this test inside the Jupyter notebook:

```
myClass = myLib.MyClass()

// Let's say that _note has only 3 elements inside of it.
// So I will try to access a invalid vector index

x = myClass.getNote(100)
```

When I tried to do that, I got a message saying:
```
=====> Kernel Restarting <=====
The kernel appears to have died. It will restart automatically.
```

**My question is:**
How can I exit this `getNote()` method without the Python kernel restarts.

Thank you,

**My System:**
* Ubuntu 20.10
* Python 3.8

**Comment by YannickJadoul** [comment]
@nyckmaia, you are literally shutting down the interpreter, by calling `exit(0)`. Of course your kernel dies.

Python has exceptions for that, and pybind11 helps you with them: https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html

Also, for questions like this, please consider using [Gitter](https://gitter.im/pybind/Lobby), as suggested by the issue template.
