### ISSUE TITLE
[BUG]throw in def_buffer cause terminate

### ISSUE THREAD

**Issue by caishanli** [pybind/pybind11#2764]
cpp
```
.def_buffer([](Matrix &m) -> py::buffer_info {
    throw std::runtime_error("Incompatible buffer format!");
    return py::buffer_info(
        m.data(),                                /* Pointer to buffer */
        sizeof(Scalar),                          /* Size of one scalar */
        py::format_descriptor<Scalar>::format(), /* Python struct-style format descriptor */
        2,                                       /* Number of dimensions */
        { m.rows(), m.cols() },                  /* Buffer dimensions */
        { sizeof(Scalar) * (rowMajor ? m.cols() : 1),
          sizeof(Scalar) * (rowMajor ? 1 : m.rows()) }
                                                 /* Strides (in bytes) for each index */
    );
 })
```
and in python
```
m = Matrix(3, 2)
np.array(m)
```
cause python terminate, output is
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Incompatible buffer format!
Aborted (core dumped)
```
expected output is runtime error, not terminate
```
RuntimeError: Incompatible buffer format!
```

**Comment by YannickJadoul** [comment]
@caishanli, can you specify why you want to throw from `def_buffer`, though? This should be fixable, but I'd figure out if we should allow this. `"Incompatible buffer format!"` is not up to you to throw; `def_buffer` should specify what's offered and the caller will see if it can handle the buffer format offered.

**Comment by caishanli** [comment]
@YannickJadoul Hi, I use pybind11 to bind [Tencent/ncnn](https://github.com/Tencent/ncnn). And in [ncnn::Mat](https://github.com/Tencent/ncnn/blob/master/python/src/main.cpp#L282), the element size(in byte) can be 1, 2, 3, 4 or any other positive integers, but as my best knowledge, python have no data type of 3 bytes, 5 bytes and so on, so I need to throw a runtime error, and the same as element pack.

**Comment by YannickJadoul** [comment]
@caishanli Ah, I see. And that's only known at runtime? :-(

But OK, then we mainly need a way to indicate failure from a buffer, rather than a "catch all exceptions"? The latter wouldn't be wrong to do either, though.

**Comment by caishanli** [comment]
@YannickJadoul I think just catch all exceptions is ok as we have error message to indicate what's wrong.
