### ISSUE TITLE
[QUESTION] How to add binding for C++ 128bit integer?

### ISSUE THREAD

**Issue by zhqrbitee** [pybind/pybind11#2767]
I'm wondering is there a proper way to convert between Python integer and an C++ 128bit integer (e.g. gcc/clang build-in `__int128`, or `abseil::int128`)?
I did notice there is a project: https://github.com/pybind/pybind11_abseil, but it doesn't seem to include binding for `abseil::int128`.
Any suggestions would be appreciated!

**Comment by henryiii** [comment]
@rwgk might be interested in this? Possibly poking the right pybind11_abseil people? ;)

**Comment by rwgk** [comment]
Hi @zhqrbitee , if you search for `int128` here you will find code that could be adapted for pybind11:

* https://github.com/google/clif/blob/4c5f7c1643e7b31e968a442776a177eb14e327c2/clif/python/types.h
* https://github.com/google/clif/blob/4c5f7c1643e7b31e968a442776a177eb14e327c2/clif/python/types.cc
* https://github.com/google/clif/tree/4c5f7c1643e7b31e968a442776a177eb14e327c2/clif/testing

Background:
* We're actively working on integrating pybind11 into PyCLIF. Eventually all the `Clif_PyObjAs` and `Clif_PyObjFrom` functions will become pybind11 type casters, but at the moment you have to pick them out as needed.
* The github export of pybind11_abseil was bootstrapped only recently and is expected to still have rough edges, but with that caveat, contributions, like fitting in the `int128` type casters, are welcome.

**Comment by EricCousineau-TRI** [comment]
If you want NumPy scalars to specifically bind those types in Python, there's also stuff like #1785. Hopefully, though, that's overkill here!

**Comment by zhqrbitee** [comment]
@EricCousineau-TRI 
If I follow the idea in #1785 to define a type caster for 128-bit int with Python integer, then will it override the default type caster for python integer?  
E.g. when casting Python integer to C++, will it convert to normal C integer or the 128-bit int?

**Comment by rwgk** [comment]
If you have a `type_caster` templated on a specific type, the compiler will pick it as the most specialized, over less-specialized alternatives.
Implementing a `type_caster` is really straightforward for something as simple as `int128`, especially given the PyCLIF code, which you can essentially just copy over into the `load` and `cast` functions, then fix it up to interface with `handle`, like you see in existing casters under include/pybind11, or pybind11_abseil casters.

**Comment by EricCousineau-TRI** [comment]
Yuppers, what Ralf said. In the NumPy variant, the `type_caster` mixes with some of the (odd) NumPy scalar semantics.
That being said, if Python's `int` is all you need for precision, I'd definitely recommend going that route if you can.

Ralf - just to check, this is all predicated on the fact that Python3's `int` object can represent the precision of `int128`?

**Comment by EricCousineau-TRI** [comment]
Ah, yup, seems so! https://stackoverflow.com/a/26121781/7829525

**Comment by zhqrbitee** [comment]
@EricCousineau-TRI  
I care about Python2, so I think. it is clear to me how to implement the conversion. Will close this issue, thanks！
