### ISSUE TITLE
[QUESTION] Why passing a float64 list to c++, c++ get vector<float> but not double?

### ISSUE THREAD

**Issue by liym27** [pybind/pybind11#2775]
<!--

If you have a question, please check the following first:

1. Check if your question has already been answered in the [FAQ][] section.
2. Make sure you've read the [documentation][]. Your issue may be addressed there.
3. If those resources didn't help and you only have a short question (not a bug report), consider asking in the [Gitter chat room][]
4. Search the [issue tracker][], including the closed issues, to see if your question has already been asked/answered. +1 or comment if it has been asked but has no answer.
5. If you have a more complex question which is not answered in the previous items (or not suitable for chat), please fill in the details below.
6. Include a self-contained and minimal piece of code that illustrates your question. If that's not possible, try to make the description as clear as possible.

[FAQ]: http://pybind11.readthedocs.io/en/latest/faq.html
[documentation]: https://pybind11.readthedocs.io
[issue tracker]: https://github.com/pybind/pybind11/issues
[Gitter chat room]: https://gitter.im/pybind/Lobby

*After reading, remove this checklist.*
--!>

I want to pass a float64 list `[2.0**128]` to c++, but c++ only received `vector<float>`, precision is lost. I print the vector<float>, only get 'inf'

**Comment by bstaletic** [comment]
Probably because you're using a vector of floats? Show your code, as we still haven't got our crystal balls to work.

**Comment by liym27** [comment]
For example:

pybind_sum will call `Func(vector<float> nums)` but not `Func(vector<double> nums)`, 
```python
import numpy as np
a = [2.0**129, 2.0**129] # Note float32:[-2^128, 2^128)

out = pybind_func(a)
```

```c++
m.def("pybind_func", Func);

double Func(vector<double> nums){
  // ...
  // do something
  // ...
}

double Func(vector<float> nums){
  
   // Note: nums[0] and nums[1] are 'inf';
  // do something
  // ...
}

```

**Comment by bstaletic** [comment]
>     m.def("pybind_func", Func);

That line wouldn't compile if `Func` is an overload set. So what did you actually do in your code?

**Comment by YannickJadoul** [comment]
Agreeing with @bstaletic. pybind11 doesn't magically call an overload. You specified somewhere that you want to bind the overload with `vector<float>` instead of `vector<double>`.

**Comment by liym27** [comment]
Sorry, the code is as follows:

```python
import numpy as np
a = [2.0**129, 2.0**129] # Note float32:[-2^128, 2^128)

out = pybind_func(a)
```


```c++
m.def("pybind_func", Func);

using num_type = boost::variant<std::vector<float>,std::vector<double>>;

double Func(const num_type& nums){
  // !!! Note: nums[0] and nums[1] are 'inf';
  // do something
  // ...
}

```

**Comment by YannickJadoul** [comment]
Ah, you have a variant?? That was not mentioned anywhere. We can't just randomly guess that.

Casting variants follows the same rules for casting as overloaded functions: order matters; see https://pybind11.readthedocs.io/en/stable/advanced/functions.html#overload-resolution-order. This has also been discussed in e.g. #1625.

**Comment by YannickJadoul** [comment]
In case it was not obvious/documented in other issues, #2784 will document this explicitly.
