### ISSUE TITLE
[QUESTION] Embedding with callbacks

### ISSUE THREAD

**Issue by asmaloney** [pybind/pybind11#2776]
(This feels a bit involved to try to ask it on gitter, but if this is the wrong place for this kind of question please let me know.) 

I have a C++ application and I'm trying to replace a currently embedded ruby/swig interface with an embedded python/pybind11 interface.

I need some high-level guidance on the approach because it feels like I'm "doing it wrong (tm)". I've tried many things and read through the manual, but I still don't have a grasp on it. (_And_ I am a python neophyte.)

1) My C++ application looks in a directory for user scripts.
2) It loads each of them and lets the scripts register callbacks
3) When an event "foo" happens in the C++ code, I want to run the python code (which uses classes exposed from C++)

What I have so far:

1) I initialize and create a scope once:

```cpp
py::initialize_interpreter();
mScope = py::module_::import( "__main__" ).attr( "__dict__" );
```

with destructor:
```cpp
mScope.release();
py::finalize_interpreter();
```

2) My class & functions are registered like this:
```cpp
using calculatorCallback = std::function<void( const someClass * )>;

PYBIND11_EMBEDDED_MODULE( Foo, m )
{
   m.doc() = "Foo plugin";

   py::class_<someClass>( m, "someClass" )
         .def( "id", &someClass::id )
         .def( "name", &someClass::name );
   
   m.def( "registerCalculator", []( const std::string &inMethodName, const calculatorCallback &inCallback ) {
      // store method name and callback for later use
      // assume this is stored somewhere else, not on the stack
      myCalculatorCallback = inCallback;
   } );
}
```

3) For each script I load it and run a specific registration function:
```cpp
py::eval_file( fileName, mScope );
py::exec( "registerInterface()", mScope );
```

4) On the python side, the registration function does something like:
```python
import Foo

def onCalculate(klass: Foo.someClass):
    print("PYTHON: onCalculate" + klass.name())


def registerInterface():
    Foo.registerCalculator("onCalculate", onCalculate)
```

5) When the event happens on the C++ side, I call back to python:
```cpp
myCalculatorCallback( someClassPointer );
```

When I run my more-complete version of this, it hangs and I get this in the console:
```
Warning: Premature drain of QMacAutoReleasePool(0x7ffeeb52d2c8) This can happen if you've allocated the pool on the heap, or as a member of a heap-allocated object. This is not a supported use of QMacAutoReleasePool, and might result in crashes when objects in the pool are deallocated and then used later on under the assumption they will be valid until QMacAutoReleasePool(0x7ffeeb52d2c8) has been drained.	(:0, (null))
```

Questions
--
1) From a high-level perspective, is this a valid approach?
2) If I am loading the files using `eval_file` (in 3 above), do the callbacks I register like this (in 3 & 4 above) stay in scope?
3) What happens if I load two files that have the same function names? Does one override the other?

Thanks for any input!

**Comment by bstaletic** [comment]
In the destructor, you would want to call `mScope.dec_ref().release()`.

> From a high-level perspective, is this a valid approach?

Something like that is what I'd have come up with in your place.

> If I am loading the files using eval_file (in 3 above), do the callbacks I register like this (in 3 & 4 above) stay in scope?

Not sure. I'd make a simple project for testing purposes and see what happens.

> What happens if I load two files that have the same function names? Does one override the other?

I'm pretty sure the answer is "yes". You could store a map of file names to scopes.

**Comment by YannickJadoul** [comment]
> In the destructor, you would want to call `mScope.dec_ref().release()`.

Or have both these as members and allow `py::scoped_interpreter` to do its thing and get destructed after the `py::object` data member? (Mind the order of declaring data members will matter, then!)

**Comment by asmaloney** [comment]
Thanks guys. That helps!

(Found my problem which led to the hanging as well, so progress has been made 👍)

> You could store a map of file names to scopes.

That sounds reasonable. That means `mScope` goes away, and it would basically isolate each file into its own scope, right? 

How do I create a scope per file? I presume I need to create it then use it like this:

```cpp
py::scope fileScope = // somehow create file scope?
mScopeMap[inFileName] = fileScope; // store for other calls into python
py::eval_file( inFileName,  fileScope );
```

The only examples in the docs I see are creating scope based on import like this:
```cpp
py::object scope = py::module_::import("__main__").attr("__dict__");
```

Looking at the code I see `module_::create_extension_module(const char *name, const char *doc, module_def *def)` - is that what I want? What is the `module_def` it wants? ("should point to a statically allocated module_def")

**Comment by bstaletic** [comment]
> That means mScope goes away, and it would basically isolate each file into its own scope, right?

Right.

> How do I create a scope per file? I presume I need to create it then use it like this:

Right, except it's:

```c++
py::dict fileScope;
mScopeMap[inFileName] = fileScope;
py::eval_file( inFileName, py::globals(), fileScope); // scope should be the locals dictionary.
```

Note that `fileScope` is default initialized and that `std::map::operator[]` and `std::unordered_map::operator[]` also default initialize the values if key is not found. That means the second line is completely useless.

    py::eval_file( inFileName, py::globals(), mScopeMap[inFileName] );

> Looking at the code I see module_::create_extension_module(const char *name, const char *doc, module_def *def) - is that what I want?

Nope. That's when you want to make "extension modules" - a completely different use case.

**Comment by asmaloney** [comment]
Thank you @bstaletic.

Looking at the code, it looks like `py::globals()` does the equivalent of what I was doing with `mScope` anyways.

I'm slightly confused by scopes & locals & globals. Is there an explanation of how they work at the API level somewhere?

The closest docs I can find are [here](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/utilities.html#eval) - but it doesn't really talk discuss local & global.

Once I add the file scope as above, it can no longer find my embedded module _Foo_ in `registerInterface()`:

```
NameError: name 'Foo' is not defined
```

I would have thought this would be in the global scope already through `PYBIND11_EMBEDDED_MODULE`? Do I need to add it to the new file scope somehow? (If I remove the file scope it works like it did before.)

**Comment by bstaletic** [comment]
> I'm slightly confused by scopes & locals & globals.

So am I! Python is doing weird things when it comes to globals/locals dictionaries.

> Is there an explanation of how they work at the API level somewhere?

There should be. It's "just" CPython. The `py::eval_file()` call ends up running [`PyRun_FileEx()`](https://docs.python.org/3.8/c-api/veryhigh.html#c.PyRun_FileEx)...

Anyway, I might be remembering the globals/locals things wrong. Try passing `mScopeMap[inFileName]` as the globals dictionary and see if that works.

**Comment by asmaloney** [comment]
Oops. I was chasing my tail a little. Some remnants of my ruby/swig were checking for duplicate method names. Since I'm now passing around function pointers I don't need that.

So I can actually remove both globals _and_ locals and it works!

I took a look at the [Python/C API Reference Manual](https://docs.python.org/3.9/c-api/index.html) and I don't understand globals/locals any better. 😃 🤷

I'm really happy with how much cleaner **pybind11** is so far than what I was doing with ruby/swig.

Thanks a lot for your help @bstaletic - on to console i/o!
