### ISSUE TITLE
[QUESTION] Set python function as callback with noncopyable param via def_readwrite().

### ISSUE THREAD

**Issue by pbalash0v** [pybind/pybind11#2785]
Hi everyone !

I would appreciate some nudge in a direction of grasping what should be done to make the following work.
So question is if Value is noncopyable, but moveable I get a compiler error about Value's deleted copy-ctor.

```c++
#include <pybind11/pybind11.h>
#include <pybind11/functional.h>

struct Value final
{
	Value() = default;
	~Value() = default;
	
	Value(const Value&) = delete;
	Value& operator=(const Value&) = delete;

	Value(Value&&) = default;
	Value& operator=(Value&&) = default;

	int val;
};

using func_type = std::function<void(Value)>;

struct Exposed
{
	func_type f;
};

namespace py = pybind11;

PYBIND11_MODULE(pypg, m)
{
    py::class_<Value>(m, "Value")
		.def(py::init<>())
		.def_readwrite("val", &Value::val);

    py::class_<Exposed>(m, "Exposed")
		.def(py::init<>())
		.def_readwrite("f", &Exposed::f);
}
```

and using like so:

```python
#!/usr/bin/env python3

import pypg

def py_func(value):
	print(value)
	print(value.val)

def main():
	obj = pypg.Exposed()
	obj.f = py_func

if __name__ == '__main__':
	main()
```

Thanks in advance on any input.

**Comment by bstaletic** [comment]
What's the error?

**Comment by YannickJadoul** [comment]
> ```c++
> std::function<void(Value)>
> ```

You're asking for a copy in the signature. pybind11 isn't going to move construct and "steal" the instance from Python.

**Comment by YannickJadoul** [comment]
Change `std::function<void(Value)>` to `std::function<void(Value &)>` or `std::function<void(const Value &)>`, and thing compile and run, for me.

I'll close this. Please reopen if this didn't solve your issue. (Thanks for the clear examples, btw; that does make it easier to test!)
