### ISSUE TITLE
[BUG?] Pickle and joblib in embedded interpreter

### ISSUE THREAD

**Issue by m-drozd** [pybind/pybind11#2788]
I have a piece of code running in embedded interpreter that is called like this:
```
_module = py::module::import(moduleName.c_str());
_module.attr("function")(source, topic, data);
```

The code executes some sklearn and pickle stuff and works fine when executed directly but freezes when running under the embedded interpreter. I've isolated two separate issues. First of all the in this piece of code:
```
    @staticmethod
    def load(filename: str) -> "Model":
        with open(filename, 'rb') as f:
            print("File open")
            return pickle.load(f)
```
The  _File open_ message gets printed but the interpreter gets stuck somewhere in the pickle.load() method and never returns. Any ideas as to why this happens or how to debug this further?

Second issue I've encountered was with joblib usage inside sklearn. The interpreter gets stuck on [this](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/ensemble/_forest.py#L387):
```
            trees = Parallel(n_jobs=self.n_jobs, verbose=self.verbose,
                             **_joblib_parallel_args(prefer='threads'))(
                delayed(_parallel_build_trees)(
                    t, self, X, y, sample_weight, i, len(trees),
                    verbose=self.verbose, class_weight=self.class_weight,
                    n_samples_bootstrap=n_samples_bootstrap)
                for i, t in enumerate(trees))
```
This can be circumvented by changing joblib's backend to _loky_ using [this](https://scikit-learn.org/stable/modules/generated/sklearn.utils.parallel_backend.html), however I'm wondering why that's necessary and if it can be avoided.

Pybind version: 2.6.1
Python version: 3.91
GCC version: 10.2.0

**Comment by m-drozd** [comment]
Both issues seem to be caused initializing the interpreter and calling the function from different threads, which i believe is linked to GIL and expected behaviour. I'm gonna do some more digging before closing this.

**Comment by YannickJadoul** [comment]
Hard to say anything without seeing more code. This doesn't really seem familiar, at least. Though checking you hold the GIL is indeed a good idea.

**Comment by m-drozd** [comment]
I'm gonna post some simplified code for anybody that might find upon this

```
class PythonScriptRunner
{
public:
	PythonScriptRunner()
        {
             	py::module sys = py::module::import("sys");
	        sys.attr("path").attr("insert")(1, "customModulePath");
	        _module = py::module::import("customModuleName");
        }
	void Execute()
        {
            _module.attr("function")();
        }

private:

	pybind11::scoped_interpreter _guard;
	pybind11::module _module;
}




class PythonSubprocess
{
public:
	PythonSubprocess()
        {
            _runner = std::make_unique<PythonScriptRunner>();
        }
	void Run()
        {
	        _runThread = std::thread(&PythonSubprocess::RunFunction, this);
        }
	void Stop()
        {
	        _runThread.join();
        }

private:
	void RunFunction()
        {
            _runner->Execute();
        }


private:
	std::unique_ptr<PythonScriptRunner> _runner;
	std::thread _runThread {};
};

int main()
{
        PythonSubprocess sub;
        sub.Run();
        sub.Stop();
        return 0;
}

```

This seems to hang if I use sklearn or pickle.load() in the python _function_ as I said earlier, however as soon as I move 
` _runner = std::make_unique<PythonScriptRunner>();`
to the _RunFunction_ everything works fine.

**Comment by YannickJadoul** [comment]
It seems like you're calling a Python function without holding the GIL, indeed. If ...

```
	void Execute()
        {
            _module.attr("function")();
        }
```

... is called from a different thread, you'll need to hold the GIL. Meanwhile, in order to acquire the GIL, you also need to release it in the main thread, of course, or you'll have a deadlock.

Does that help? Can you check whether this is enough to close this issue, or not yet?

**Comment by m-drozd** [comment]
Yeah this version works fine, although it feels that there should be a better way to do this. Thanks for help.
```
class PythonScriptRunner
{
public:
	PythonScriptRunner()
        {
             	py::module sys = py::module::import("sys");
	        sys.attr("path").attr("insert")(1, "customModulePath");
	        _module = py::module::import("customModuleName");
        }
	void Execute()
        {
            _module.attr("function")();
        }

private:

	pybind11::scoped_interpreter _guard;
	pybind11::module _module;
}




class PythonSubprocess
{
public:
	PythonSubprocess()
        {
            _runner = std::make_unique<PythonScriptRunner>();
            _gil = std::make_unique<pybind11::gil_scoped_release>();
        }
	void Run()
        {
	        _runThread = std::thread(&PythonSubprocess::RunFunction, this);
        }
	void Stop()
        {
	        _runThread.join();
                _gil.reset();
        }

private:
	void RunFunction()
        {
            pybind11::gil_scoped_acquire acq;
            _runner->Execute();
        }


private:
	std::unique_ptr<PythonScriptRunner> _runner;
	std::thread _runThread {};
	std::unique_ptr<pybind11::gil_scoped_release> _gil;
};

int main()
{
        PythonSubprocess sub;
        sub.Run();
        sub.Stop();
        return 0;
}

```

**Comment by YannickJadoul** [comment]
> Yeah this version works fine, although it feels that there should be a better way to do this.

How do you mean? Python's GIL is quite annoying, but there's not a lot we can do about it.
You could still replace the `unique_ptr` by `optional` to avoid using the heap.

**Comment by m-drozd** [comment]
That's what i meant, using pointers for this seems kind of weird, I might just go with an optional, thanks.

**Comment by YannickJadoul** [comment]
C++ even has `optional<T>::emplace()`, so no need to copy/move assign, even ;-)
