### ISSUE TITLE
numpy.ndarray onwnership management

### ISSUE THREAD

**Issue by foxtog** [pybind/pybind11#279]
Hello, Wenzel!
I have a question on creating numpy.ndarray using existing data buffer pointer.
As the code in numpy.h goes
`      
 if (info.ptr && tmp)
tmp = object(api.PyArray_NewCopy_(tmp.ptr(), -1 /* any order */), false);`
even though we supply pointer to an existing buffer, we create an array and return **a copy** of it thus providing a new ndarray. 
Do we follow this path to ensure proper memory management in terms of array data ownership?(thus ensuring that if data buffer is altered from C++, created ndarray stays intact as there is no way to pass information about such a change to the array)

I can't think of a secure way of passing data pointer to ndarray when we are able to manage the object both from C++ and Python.
My question has been motivated by my attempts to find a way of creating ndarray from existing data with no shared ownership violations.

**Comment by wjakob** [comment]
yes, the reason is indeed to avoid shared ownership issues. NumPy has a way of creating a ND-array which is backed by another instance, but that is not the right thing to do in this case as modifications would be visible in both places. Does this answer your question?

**Comment by foxtog** [comment]
Thanks for a quick reply!
Partly. What do you mean by 'backed by another instance'?

**Comment by wjakob** [comment]
NumPy allows creating an array with a raw pointer to somewhere. To avoid this "somewhere" from disappearing (e.g. by being garbage collected), you also get to provide a ``PyObject *`` pointer whose reference will be increased while the NumPy array is visible.

**Comment by wjakob** [comment]
(Probably it's best if you take a look at the NumPy C++ API for further details)

**Comment by foxtog** [comment]
Thank you. 
I was just interested why no-copy ownership passing is not implemented in libraries(whether it's insecure, etc.)

**Comment by wjakob** [comment]
Ok -- sounds like this is not a pybind11 specific question (which is just a wrapper for NumPy here). I'll close this ticket and suggest you take your question up with the NumPy folks.
