### ISSUE TITLE
Compilation problems with clang

### ISSUE THREAD

**Issue by s-koch** [pybind/pybind11#280]
Hi Wenzel,
we get an error when we try to compile the following function (added to the eigen.cpp example) with clang 3.7, whereas it works with gcc and VS. 

`
m.def("foo", [] (
      const std::vector<Eigen::Quaternion<double> >& v
    )
    {
      return v;
    }, "foo",
    py::arg("v"));
`

Something goes wrong with the parameter casting: 
> errror: no matching function for call to 'conditional_aligned_malloc'
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(IsAligned)

Do you have an idea on how to fix this?

**Comment by wjakob** [comment]
Sorry, not sure. Are you using the ``eigen.h`` header? That one only has bindings for ``Eigen::Matrix`` as of now.

**Comment by s-koch** [comment]
No, the ` eigen.h` header is not used. It"s really just this simple function (which I included as an MWE into your example cmake build for testing purposes as we ran into this problem with libigl).

**Comment by wjakob** [comment]
Did you remember to include "Eigen/Geometry"?

**Comment by s-koch** [comment]
Thanks, that solved the problem. Do you know why G++ doesn't complain?

**Comment by wjakob** [comment]
No, sorry.

**Comment by s-koch** [comment]
Sorry I figured that `Eigen/Geometry` was already included (it compiled because I excluded `pybind11/stl.h` in this case). It must be something else, could you take another look at it?

**Comment by wjakob** [comment]
So how did it solve your issue before?

**Comment by s-koch** [comment]
I accidentally excluded `pybind11/stl.h` while including `Eigen/Geometry` a second time, which resulted in my misinterpretation. Therefore no automatic conversion bindings for the `std::vector<Eigen::Quaternion<double> >` were created and the compilation went smooth even with clang. But that's not the solution I'm looking for as we want to have the automatic bindings (in combination with PYBIND11_MAKE_OPAQUE, but that's not relevant for the MWE). Hope this makes it clear?

**Comment by s-koch** [comment]
The problem occurs for Eigen 3.2.9. as well as 3.3-beta1. Could you reproduce it and/or do you maybe have an idea on how to solve it?

**Comment by wjakob** [comment]
I can try to look at it, but my resources are fairly limited. Could you provide a self-contained minimal example to facilitate this?

**Comment by s-koch** [comment]
That would be great. 9caf70b19a8dc207a64183d181215b43c94a0efa is a self contained example which works if I compile with gcc whereas `cmake -DCMAKE_CXX_COMPILER=clang++-3.7 -DCMAKE_C_COMPILER=clang-3.7 .` fails to compile.

**Comment by wjakob** [comment]
Can't reproduce -- I have no compilation issues with:

```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

and Eigen 3.2.8.

**Comment by s-koch** [comment]
Ok, but thanks a lot for checking. We'll see if a newer clang version solves the problem.
