### ISSUE TITLE
Memory leak when calling embedded module function [BUG] 

### ISSUE THREAD

**Issue by lianera** [pybind/pybind11#2809]
## Issue description

Windows 10  
Visual Studio 2019 x64
Python 3.9.1
Latest master branch (48534089f7f1b0229bc7ae2e4d0f21dc9ad169b5)

It seems like memory leaked when calling `app.attr("test")();`  in the following code. 

## Reproducible example code

```cpp

#define _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h>
#include <iostream>

#include <pybind11/pybind11.h>
#include <pybind11/embed.h>

namespace py = pybind11;

void test()
{
}

PYBIND11_EMBEDDED_MODULE(app, m) {
    m.def("test", &test);
}

void RunPy()
{
    pybind11::scoped_interpreter guard{};
    auto app = py::module_::import("app");
    app.attr("test")();
}

int main()
{
    _CrtMemState s1, s2, s3;
    _CrtMemCheckpoint(&s1);

    RunPy();

    _CrtMemCheckpoint(&s2);

    if (_CrtMemDifference(&s3, &s1, &s2))
    {
        _CrtMemDumpStatistics(&s3);
        std::cout << "********* Memory leak *********" << std::endl;
    }

    return 0;
}


```

**Comment by YannickJadoul** [comment]
- Does this give any output?
- What happens if you don't call `app.attr("test")()`? Is the leak checker happy, then?
- Does the leak not happen with the raw C API?

**Comment by lianera** [comment]
After some study, I found this is caused by python itself. More specifically, Py_Finalize may not free all allocated memory. The python documentation also mentioned [this](https://docs.python.org/3/c-api/init.html#c.Py_FinalizeEx):

> Bugs and caveats: The destruction of modules and objects in modules is done in random order; this may cause destructors (__del__() methods) to fail when they depend on other objects (even functions) or modules. Dynamically loaded extension modules loaded by Python are not unloaded. Small amounts of memory allocated by the Python interpreter may not be freed (if you find a leak, please report it). Memory tied up in circular references between objects is not freed. Some memory allocated by extension modules may not be freed. Some extensions may not work properly if their initialization routine is called more than once; this can happen if an application calls Py_Initialize() and Py_FinalizeEx() more than once.

It seems this pitfall exists for quite a long time and no solution to solve. Which caused inconvenience for memory leak detection. Anyway, I'd close this issue.
