### ISSUE TITLE
[BUG] add_subdirectory no longer works since 2.6.0

### ISSUE THREAD

**Issue by mrexodia** [pybind/pybind11#2817]
## Issue description

The following `CMakeLists.txt` works on 2.5.0 but not on 2.6.1:

```cmake
cmake_minimum_required(VERSION 3.18)

project(pybind11example)

include(FetchContent)
FetchContent_Declare(
    pybind11
    GIT_REPOSITORY https://github.com/pybind/pybind11
    GIT_TAG        v2.6.1
)

FetchContent_GetProperties(pybind11)
if(NOT pybind11_POPULATED)
    FetchContent_Populate(pybind11)
    add_subdirectory(${pybind11_SOURCE_DIR} ${pybind11_BINARY_DIR})
endif()

pybind11_add_module(${PROJECT_NAME} pybind11example.cpp)
```

The error:

```
Unknown CMake command "pybind11_add_module".
```

## Reproducible example code

`pybind11example.cpp` is an empty file.

**Comment by YannickJadoul** [comment]
Why is `add_subdirectory(${pybind11_SOURCE_DIR} ${pybind11_BINARY_DIR})` inside `if(NOT pybind11_POPULATED)`? I'm not sure that makes sense to me.

**Comment by mrexodia** [comment]
> Why is `add_subdirectory(${pybind11_SOURCE_DIR} ${pybind11_BINARY_DIR})` inside `if(NOT pybind11_POPULATED)`? I'm not sure that makes sense to me. You also want to add that subdirectory if pybind11 has already been downloaded, no?

I just copy-pasted from https://cmake.org/cmake/help/latest/module/FetchContent.html. I think the idea is that `FetchContent_Populate` sets `pybind11_POPULATED` so that you don't have to redownload it every time you configure.

In reality I'm using [CPM.cmake](https://github.com/TheLartians/CPM.cmake) (which does all this FetchContent business under the hood) and it looks like this:

```cmake
CPMAddPackage(
    NAME pybind11
    VERSION 2.6.1
    GITHUB_REPOSITORY pybind/pybind11
    OPTIONS
        "PYBIND11_NOPYTHON ON"
        "PYBIND11_FINDPYTHON OFF"
)
```

You can replicate exactly the same behavior if you add a submodule to `pybind11` on the `v2.6.1` tag and call `add_subdirectory` (as recommended in the pybind11 manual).

**Comment by YannickJadoul** [comment]
Hmmm, right, then I must be missing something; sorry to be too hasty to reply!

**Comment by YannickJadoul** [comment]
Let me try out a few things, but also ping @henryiii.

**Comment by YannickJadoul** [comment]
So, I've just tried out the example you described, and things "just work" for me. So something else must be going on.

What CMake version are you on? Do you have the full log of a fresh configure & build run?

**Comment by henryiii** [comment]
```cmake
include(FetchContent)
FetchContent_Declare(
    pybind11
    GIT_REPOSITORY https://github.com/pybind/pybind11
    GIT_TAG        v2.6.1
)
FetchContent_MakeAvailable(pybind11)
```

Is simpler, by the way. I don't see any reason this would fail, I'm suspecting it is a problem somewhere else?

**Comment by mrexodia** [comment]
When I retried after fully clearing the cache I no longer got a fatal error, but a bunch of warnings about the IMPORTED target locations instead (sorry I closed the console already so no logs). I am now upgrading both Visual Studio and CMake (from 3.19.0 to 3.19.2) to see if I can get it to configure without warnings on my machine too.

I set up a simple test repo with AppVeyor to try and replicate my configuration, but everything appears to be working fine there: https://ci.appveyor.com/project/mrexodia/pybind11-example. I'll close the issue for now because it appears to be something in my system configuration.

**Comment by mrexodia** [comment]
Okay I upgraded everything and everything is working great now 🤷🏻‍♂️

**Comment by YannickJadoul** [comment]
Huh, OK. Well yes, as long as the issue doesn't occur again, let's not worry too much, I guess? :-D

If not, do please reopen!

**Comment by henryiii** [comment]
With logs. ;)
