### ISSUE TITLE
[BUG] Abort while printing traceback

### ISSUE THREAD

**Issue by pavelschon** [pybind/pybind11#2825]
## Issue description

Unexpected abort while printing traceback

## Reproducible example code

```c++
/** TestExc.cpp */
#include <pybind11/embed.h>

namespace py = pybind11;

int main( int argc, char** argv )
{
    py::scoped_interpreter guard{};

    try
    {
        py::module::import("foo");
    }
    catch(const py::error_already_set& e)
    {
        py::module::import("traceback").attr("print_exception")(e.type(), e.value(), e.trace());
    }
}
```
### Output
```
$ ./test-exc 
terminate called after throwing an instance of 'pybind11::cast_error'
  what():  make_tuple(): unable to convert argument of type 'object' to Python object
Aborted
```

### This works as expected

The traceback-printing routine normally works. Just create _foo.py_ with the following content:
```python
# foo.py
raise Exception('Hello world')
```
```
$ ./test-exc 
Traceback (most recent call last):
  File "./foo.py", line 1, in <module>
    raise Exception("Hello world")
Exception: Hello world
```

**Comment by bstaletic** [comment]
Looks like that python code doesn't do the same as the C++ code. If we get rid of pybind11, the C code looks like this

```c
#include <Python.h>

int main() {
	Py_Initialize();
	PyObject* foo_unicode = PyUnicode_FromString("foo");
	PyImport_Import(foo_unicode);
	Py_DECREF(foo_unicode);
	assert(PyErr_Occurred());
	PyObject *type, *value, *trace;
	PyErr_Fetch(&type, &value, &trace);
	assert(type);
	Py_XDECREF(type);
	assert(value);
	Py_XDECREF(value);
	assert(trace);
	Py_XDECREF(trace);
	Py_Finalize();
}
```

The `assert(trace)` gets triggered. For some reason, the `trace` is `NULL`. Similarly, in your example, `e.trace().ptr()` is `NULL`. It's not a valid object and thus pybind11 can't cast it.

According to [`PyErr_Fetch()`](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_Fetch):

> The value and traceback object may be NULL even when the type object is not.

So you can't assume that `trace()` is a valid python object.
We can even take a look at what CPython is doing:

- [`PyErr_Fetch()`](https://github.com/python/cpython/blob/fe6e5e7cfd68eeaa69fd1511f354a1b4d8d90990/Python/errors.c#L403-L422) simply gets the thread state and gives you the ownership of `type`, `value` and `trace`.
- [`PyImport_Import()`](https://github.com/python/cpython/blob/4db8988420e0a122d617df741381b0c385af032c/Python/import.c#L1801-L1807) calls `__import__()` and fails.
  - Well, how does it call `__import__()`? See below.

After *a lot* of inlining (and a bit of cheating), the C code looks like this:

```c
#include <Python.h>

int main() {
	Py_Initialize();
	// Get __import__
	PyObject* builtins = PyImport_ImportModule("builtins");
	PyObject* import = PyObject_GetAttrString(builtins, "__import__");

	// Prepare arguments
	assert(!PyErr_Occurred());
	PyObject* args = PyTuple_New(1);
	PyTuple_SetItem(args, 0, PyUnicode_FromString("foo"));

	// Call __import__
	PyObject *result = import->ob_type->tp_call(import, args, NULL);

	// Boom
	assert(PyErr_Occurred());
	//PyErr_Print();
	PyObject *type, *value, *trace;
	PyErr_Fetch(&type, &value, &trace);
	assert(type);
	assert(value);
	assert(trace);

	Py_Finalize();
}
```

A logical next step would be to reproduce this in the python shell.

```
>>> builtins.__import__('foooo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'foooo'
```

Okay, traceback is there. I said I was cheating. The actual arguments to `__import__` are:

```
>>> builtins.__import__('foooo', globals, globals, [], 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'foooo'
```

Ummm... The only possibility that I can see is that the embedded interpreter does not set the initial stack frame. Does that make sense?

___

Anyway, I don't see how this could in any way be pybind11's fault.

**Comment by pavelschon** [comment]
Thanks @bstaletic  you dig deeply into this problem. Actually I discovered varying behaviour, which is quite surprising:

### This works as expected:
```c++
#include <pybind11/embed.h>

namespace py = pybind11;

int main( int argc, char** argv )
{
    py::scoped_interpreter guard{};

    try
    {
        py::exec("1/0");
    }
    catch(const py::error_already_set& e)
    {
        py::module::import("traceback").attr("print_exception")(e.type(), e.value(), e.trace());
    }
}
```

```
$ ./test_exc 
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ZeroDivisionError: integer division or modulo by zero
```

### Here I would expect to see like above but AttributeError:

```c++
#include <pybind11/embed.h>

namespace py = pybind11;

int main( int argc, char** argv )
{
    py::scoped_interpreter guard{};

    try
    {
        py::module::import("os").attr("nonexistent")();
    }
    catch(const py::error_already_set& e)
    {
        py::module::import("traceback").attr("print_exception")(e.type(), e.value(), e.trace());
    }
}
```
```
$ ./test_exc 
terminate called after throwing an instance of 'pybind11::cast_error'
  what():  make_tuple(): unable to convert argument of type 'object' to Python object
Aborted

```

**Comment by YannickJadoul** [comment]
I kind of agree with both. This is quite annoying, but I don't see how pybind11 can do anything about this :-/

To me, this is the key point, as @bstaletic mentioned:

> According to [`PyErr_Fetch()`](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_Fetch):
> 
> > The value and traceback object may be NULL even when the type object is not.

At most, we could document this better, but if Python doesn't give us a stack trace, I don't think we can/should do much more, as it would also incur an overhead.

In principle, the workaround should be simple enough?

```
        py::module::import("traceback").attr("print_exception")(e.type(), e.value() ? e.value() : py::none(), e.trace() ? e.trace() : py::none());
```

**Comment by YannickJadoul** [comment]
> Here I would expect to see like above but AttributeError:

To clarify, there isn't a stack, here. The only frame of the stack trace of your first example would be wrong! You don't have `File "<string>", line 2, in <module>`, because you never passed a string to Python.

**Comment by YannickJadoul** [comment]
Also, to further clarify (@bstaletic did mention this): the issue you're seeing is trying to pass a `py::object()` (wrapping `NULL`!) to that function; pybind11 can't cast a `PyObject *` nullptr to a Python object.

**Comment by pavelschon** [comment]
@YannickJadoul thanks for the workaround. It works, but in the meanwhile, I started using `e.what()` which also carries pretty-printed stack trace and always works.

Since this is a limitation of Python C API, we cannot do much here, thus closing the issue.
