### ISSUE TITLE
[QUESTION] Is make_key_iterator public?

### ISSUE THREAD

**Issue by nsmith-** [pybind/pybind11#2826]
Thanks for this awesome library!
I found `make_key_iterator` which would be nice for exposing map-like classes, but I didn't see it in the API reference document. Is it public? Also, I only find `make_iterator` in an example snippet https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html?highlight=make_iterator#making-opaque-types but not in the reference. Is that expected? Would be nice to have a bit more detail in the API reference.

**Comment by YannickJadoul** [comment]
> I found `make_key_iterator` which would be nice for exposing map-like classes, but I didn't see it in the API reference document.

Weird. In the code, it seems to be documented with Doxygen triple slashes:

```
/// Makes an python iterator over the keys (`.first`) of a iterator over pairs from a
/// first and past-the-end InputIterator.
```

It's not in `detail`, so I think you're free to use it without fear that it will suddenly disappear ;-)

We should fix the docs, though. Why is it not there?

**Comment by YannickJadoul** [comment]
(didn't mean to close this issue)

**Comment by YannickJadoul** [comment]
@henryiii, oh master of the build process, is there any reason you can think of this is not picked up by Doxygen? Is there a point of me looking into this? It feels silly that if someone did at some point bother to write API documentation, that it's not shown?

**Comment by YannickJadoul** [comment]
Added to the docs in #2828 ;-)
