### ISSUE TITLE
[QUESTION] AttributeError: unreadable attribute in python3.8

### ISSUE THREAD

**Issue by wuyifan18** [pybind/pybind11#2829]
struct NodeSource {
  std::string path;
  std::string id_type;
  int32_t     format;
}

  py::class_<io::NodeSource>(m, "NodeSource")
    .def(py::init<>())
    .def_readwrite("path", &io::NodeSource::path)
    .def_readwrite("format", &io::NodeSource::format)
    .def_readwrite("id_type", &io::NodeSource::id_type);

when I run this code below:

```
from pywrap import NodeSource
a = NodeSource()
a.id_type
```

I get 'AttributeError: unreadable attribute'

**Comment by bstaletic** [comment]
I can't repro. What version of pybind11 are you on?

**Comment by wuyifan18** [comment]
> I can't repro. What version of pybind11 are you on?

the version of pybind11 is v2.4. there is no error when I use python 2.7 and python 3.5.

**Comment by bstaletic** [comment]
Try with an updated pybind11, for starters.
