### ISSUE TITLE
[BUG] python interpreter crashed when import scipy

### ISSUE THREAD

**Issue by zszeng** [pybind/pybind11#2830]
## Issue description

I try to access scipy, but python interpreter crashed when I import my module.
I only import scipy and return it.
I ensure scipy is in sys.path and can be import by "import scipy"
The environment is windows 10 , python 3.8 and mingw64.
## Reproducible example code
    m.def(
        "test", []() { return py::module_::import("scipy"); }, R"pbdoc(
        SCIPY TEST.
    )pbdoc");

**Comment by YannickJadoul** [comment]
Sooooooooooooooooooooo?
