### ISSUE TITLE
[BUG] Odd failure started popping up in the CentOS 7 test

### ISSUE THREAD

**Issue by henryiii** [pybind/pybind11#2850]
We are regularly getting a failure with a nan in an array where there wasn't one before. Seems to have just started happening consistently in the CentOS test; seems to be related to an upstream change, perhaps, as it just started happening on all PRs here.

**Comment by bstaletic** [comment]
I compared the last green log with the latest failed log. A newer version of `docker`, a newer docker image, different `dnf` mirrors, newer packages in the system update, including an update to glibc and systemd, but mostly perl packages.

**Comment by henryiii** [comment]
Have you tried reproducing locally? I can try that later, perhaps.

**Comment by bstaletic** [comment]
Trying right now.

**Comment by bstaletic** [comment]
Well that showed exactly nothing. Tests were green in docker. Note that master is green too now.

**Comment by bstaletic** [comment]
Shall we close this? CI is green.

**Comment by YannickJadoul** [comment]
Easy enough to reopen
