### ISSUE TITLE
Exception translators causing segfaults with multiple modules

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#286]
I'm getting segfaults from benign-looking code like this which used to work fine ~40 commits ago:

```cpp
m.def("f", []() { throw std::runtime_error("foo"); })
```

```sh
#12 0x0000000000400add in main (argc=2, argv=0x7fffffffdb58) at ./Programs/python.c:65
(gdb) l
431
432                 auto last_exception = std::current_exception();
433                 auto &registered_exception_translators = pybind11::detail::get_internals().registered_exception_translators;
434                 for (auto& translator : registered_exception_translators) {
435                     try {
436                         translator(last_exception);
437                     } catch (...) {
438                         last_exception = std::current_exception();
439                         continue;
440                     }
(gdb) p translator
$1 = (void (*&)(std::__exception_ptr::exception_ptr)) @0xa: <error reading variable>
(gdb) p registered_exception_translators
$4 = std::forward_list<error reading variable: Cannot access memory at address 0x2>
```

I couldn't produce a full minimal example so far yet though, but one thing to note is that this module imports other pybind11 modules when initializing like so:

```cpp
py::module::import("other.pybind11.module");
```

If I remove a certain import, segfaults go away. However, as I say, it all acts a bit weird so I don't have a full self-sufficient case yet.

**Comment by aldanor** [comment]
Just checked the same code vs a few different commits:

- 4e27f7bb13f041b81ef6b180dcbdd0979c6619ee is working fine 
- 5a7d17ff16a01436f7228a688c62511ab8c3efde (next commit) segfaults

**Comment by aldanor** [comment]
Apologies, my fault, close -- the problem was that I haven't recompiled that offending dependency module so it was built using pre-exception-translator version of pybind11, and it would break whoever imports it in dark and mysterious ways. Might be worth a warning in the release notes or something.

**Comment by wjakob** [comment]
Each new minor version lives in a different namespace so that modules compiled with different versions are actually mutually invisible. Of course you get none of those features when working with master ;)
