### ISSUE TITLE
C++17 support?

### ISSUE THREAD

**Issue by abhi3700** [pybind/pybind11#2869]
Does the existing version support C++17?

**Comment by YannickJadoul** [comment]
Of course. It supports C++11. It's in the name and the basic reason of existence of pybind11.

**Comment by abhi3700** [comment]
Actually, i thought that it supports only upto C++11

**Comment by YannickJadoul** [comment]
C++ standards are (mostly) backwards compatible.

Also: https://stackoverflow.com/questions/63682868/pybind11-for-c14-c17
