### ISSUE TITLE
Suggested reorganizing of examples filenames

### ISSUE THREAD

**Issue by jagerman** [pybind/pybind11#288]
The current sequential numbering of examples makes it a bit of a nuisance to add to in PRs because of example filename conflicts; e.g. multiple PRs adding a new feature each add a new `example20.{cpp,ref,py}`, but that means they can't be merged as is--instead one has to be merged, the other has to be updated to rename the examples, then it can be merged.

(This bit me, twice, in the implicit-cpp-convert PR, which started with example18, but needed to be renamed to example19, then example20 (and might need more renames if some other example-adding PR is accepted in the meantime).  Squashing and rebasing the commits on current master was an even more painful process because every squashed commit to the eventually-renamed example18 resulted in a rebase failure that had to be manually resolved.)

I'd like to propose restructuring the examples with names of what they do, following a `example-some-purpose.{cpp,py,ref}` naming scheme.  **I'm happy to do the work, if you are okay with this, just looking for the go-ahead here.**  In addition to making PR submissions less conflict-prone, this also has two other advantages that I can see:

- Example filenames are self-documenting
- Test failure out is similarly self-documenting as to which feature is failing

It has the disadvantage of reordering the tests; though if some tests should definitely run first, I suppose they could be named something like "example-000-some-test".

I suggest, as a tentative first step, the following renaming:

example1 -> example-methods-and-attributes
example2 -> example-python-types
example3 -> example-operator-overloading
example4 -> example-constants-and-functions
example5 -> (`*` see below)
example6 -> example-sequence-and-iterators
example7 -> example-buffers
example8 -> example-custom-ref-counting
example9 -> example-modules
example10 -> example-numpy-vectorize
example11 -> example-arg-keywords-and-defaults
example12 -> example-virtual-functions
example13 -> example-keep-alive
example14 -> example-opaque-types
example15 -> example-pickling
example16 -> example-upcasting (`*` or example-inheritance, see below)
example17 -> example-stl-binders
example18 -> example-eval
example19 -> example-custom-exceptions

`*` example5 contains three basically unrelated concepts.  The inheritance parts could be moved into example16 (calling it example-inheritance instead of example-upcasting), the callbacks could go into a new example-callbacks, and the gil into example-gil.

**Comment by wjakob** [comment]
+1, what a fantastic idea! Splitting example 5 as you propose sounds good to me. Let's call the "STL binder" example "stl-binder-vector" and "custom-ref-counting" should be "smart-ptr"

**Comment by jagerman** [comment]
Scratch `example-gil`: the header says that it has a gil example, but it doesn't actually have one.

**Comment by wjakob** [comment]
looks like that code is currently not being tested anywhere (other than my nanogui library)

**Comment by wjakob** [comment]
(There is nothing really particular to the order by the way.)
