### ISSUE TITLE
[QUESTION] Using a class as both an exception and a value

### ISSUE THREAD

**Issue by mvoelkle-cern** [pybind/pybind11#2884]
Hello,

I am having trouble using a class as both an exception and a value:

```
struct Error : public std::runtime_error {
    using std::runtime_error::runtime_error;
};

class ErrorHandler {
    virtual void handle(const Error& error) = 0;
};

class Service {
    void doSync() { throw Error(); }
    void doAsync(ErrorHandler& handler) { handler.handle(Error()); }
};

class PyErrorHandler : public ErrorHandler {
    using ErrorHandler::ErrorHandler;
    void handle(const Error& error) override {
        PYBIND11_OVERLOAD_PURE(void, ErrorHandler, handle, error);
    }
};

PYBIND11_MODULE(something, module) {
    py::class_<ErrorHandler, PyErrorHandler>(module, "ErrorHandler");
    py::class_<Service>(module, "Service")
        .def("doSync", &Service::doSync)
        .def("doAsync", &Service::doAsync);
    py::register_exception<Error>(module, "Error");
}
```

```
service = something.Service()
try:
    service.doSync()
except something.Error as error:
    print(error)

class ErrorHandler(something.ErrorHandler):
    def handle(self, error):
        print(error)
service.doAsync(ErrorHandler())
```

Pybind11 fails to call the python handler from c++ with `RuntimeError: make_tuple(): unable to convert arguments to Python object`.

If I use `py::class_<Error>(module, "Error")` instead of `register_exception`, the Error cannot be caught when calling doSync anymore: `TypeError: catching classes that do not inherit from BaseException is not allowed`.

The workaround I had to use was to recreate a python error instance in PyErrorHandler::handle:
`PYBIND11_OVERLOAD_PURE(void, ErrorHandler, handle, py::module_::import("something").attr("Error")(error.what()));`

Is there an other way?

**Comment by YannickJadoul** [comment]
There's a bit of a disconnect between classes and exception types, indeed, so I do wonder if there's much you can do about this.

One solution could be to have a custom caster, which would solve your initial issue (`register_exception` seems to not register the created exception type with pybind11, such that the standard caster doesn't work).

**Comment by marvelous** [comment]
Thanks! The custom caster ended up much more complicated, so I reverted to my initial workaround.

**Comment by mvoelkle-cern** [comment]
Thanks! The custom caster ended up much more complicated, so I reverted to my initial workaround.

**Comment by YannickJadoul** [comment]
> Thanks! The custom caster ended up much more complicated, so I reverted to my initial workaround.

That sounds very possible, yes, so I don't think that's a bad move :-)
