### ISSUE TITLE
[QUESTION] Does pybind11 rely on any environmental variables for C++ embedding?

### ISSUE THREAD

**Issue by dantamont** [pybind/pybind11#2885]
Pretty much the title. I'm wondering if there are any internals that are expecting a PYTHONPATH variable or something similar. I'm making some changes to my CMAKE build, and wanted to make sure that I understand that I'm not missing any dependencies. I ask because I cleared all of my python-related environmental variables, and am now getting the following error when I try to call `py::exec(...)`:

```
ModuleNotFoundError: No module named 'numpy'

At:
  <string>(9): <module>
```

So pybind can no longer find my site packages.

**Comment by dantamont** [comment]
Short answer: yes. I can build using a specific python DLL and include the headers, but that doesn't mean that Python will know where my site packages are. I need to set those in the PYTHONPATH environmental variable.

**Comment by YannickJadoul** [comment]
@dantamont Technically, pybind11 doesn't, but Python (or `libpython`) does have a few of these ~quirks~ features.
At least, pybind11 doesn't add anything, here, and reacts (should react) the same as embedding Python directly through the C API.
