### ISSUE TITLE
[QUESTION] Mixing pybind11 versions including changes that are under development on git

### ISSUE THREAD

**Issue by daltairwalter** [pybind/pybind11#2897]
In using pybind11, there have been a few occasions where modifying the source has been necessary (e.g. shared_ptr, GIL hang issues, python debug builds).  I also know that pybind11 has a number of globals that span across multiple pyds.  Pybind11 has been working very well for us overall and other groups within the company are now also looking at pybind11, which brings questions about pybind11 versioning.

I am under the impression that there is some sort of versioning associated with the globals so that it is possible to have pyds from different versions running in the same python instance and not sharing globals.  Is this correct?

If this is the case, I would like to change the identification on my hacked versions of pybind11 so that they don't interfere with other versions of pybind11.  Where would it be best for me to do this?

**Comment by YannickJadoul** [comment]
@daltairwalter, if I understand correctly, you are correct, yes. If you made important changes to the internals' ABI, these are guarded by the `PYBIND11_INTERNALS_ID` macros in `detail/internals.h`.

**Comment by daltairwalter** [comment]
Yes, this is what I was looking for.  Thank you.
