### ISSUE TITLE
smart_holder: open issues

### ISSUE THREAD

**Issue by rhaschke** [pybind/pybind11#2901]
When using @rwgk's `smart_holder` branch and providing a custom holder type like this:
```cpp
py::class_<MyClass, std::shared_ptr<MyClass>, MyBaseClass>(m, "MyClass")
		.def(py::init<>());
```
I've got a misleading static assert:
```
pybind11/include/pybind11/pybind11.h:1297:13: error: static assertion failed: py::class_ holder vs type_caster mismatch: missing PYBIND11_SMART_POINTER_HOLDER_TYPE_CASTERS(T, std::shared_ptr<T>)?
 1297 |             !(detail::is_instantiation<std::shared_ptr, holder_type>::value
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1298 |               && wrapped_type_uses_smart_holder_type_caster),
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I would assume: 
1. That it is possible to define custom holders
2. If multiple holder types are defined, a more informative assert would be thrown

**Comment by rwgk** [comment]
Hi Robert, are you using `-DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT`?
Or are you using the `PYBIND11_SMART_HOLDER_TYPE_CASTERS(MyClass)`?
If that's not it, could you please share the code that fails building?

**Comment by rhaschke** [comment]
I'm using `-DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT`. I successfully migrated my code to the `smart_holder` branch - at least everything compiles. See [here](https://github.com/ubi-agni/moveit_task_constructor/commit/7d50093a5ecb261bd1619b7576311c0358840deb) for required changes:
- explicitly specifying a custom holder type doesn't work anymore
- (reference) arguments of `std::shared_ptr<T>&` don't work anymore
- `make_iterator` doesn't work for a container (`std::list`) of `std::unique_ptr<T>`

**Comment by rwgk** [comment]
> * explicitly specifying a custom holder type doesn't work anymore

It does :-) I tried to be really careful about. What you need is actually in the `static_cast` message (just with `T` instead of your typename):
```
PYBIND11_SMART_POINTER_HOLDER_TYPE_CASTERS(MyClass, std::shared_ptr<MyClass>)
```
Here are many examples: https://github.com/pybind/pybind11/blob/d6cf6dfed3dda6941f2be4b5bdcc80a2f6e4d8c5/tests/test_smart_ptr.cpp#L277

Maybe I should rename the macro, because it's deceptively similar to PYBIND11_SMART_HOLDER_TYPE_CASTERS?
Maybe it's just too precise for its own good? Does `PYBIND11_CUSTOM_HOLDER_TYPE_CASTERS` look better?

**Comment by rwgk** [comment]
> * (reference) arguments of std::shared_ptr<T>& don't work anymore

Yes, that's on purpose: it could be used to undermine ownership correctness (you could call `.reset(some_other_ptr)`). But `const std::shared_ptr<T>&` should work:
```
git diff smart_holder master tests/test_methods_and_attributes.cpp
```

> * make_iterator doesn't work for a container (std::list) of std::unique_ptr<T>

Do you have a reproducer for this?

**Comment by rhaschke** [comment]
> You need a `PYBIND11_SMART_POINTER_HOLDER_TYPE_CASTERS(T, std::shared_ptr<T>)`

Defining `PYBIND11_SMART_POINTER_HOLDER_TYPE_CASTERS(T, std::shared_ptr<T>)` for all concrete types T works indeed. 

However, this is somewhat laborious and I didn't expect this would be needed. 
So far, there wasn't any need for such a declaration in old pybind11. Only if you wanted to use a custom holder, you had to use `PYBIND11_DECLARE_HOLDER_TYPE(T, custom_holder_type<T>)` _once_ to declare your holder in a templated fashion for any type `T`.

> > * make_iterator doesn't work for a container (std::list) of std::unique_ptr
> 
> Do you have a reproducer for this?

See [here](https://github.com/ubi-agni/moveit_task_constructor/commit/65c404b57b618e6a88dec798c063d919a06d74b1#r48238200). I can prepare a unit test in pybind11 if you like. It's essentially providing an iterator for `std::list<std::unique_ptr<T>>`.

I have some more test issues. Need to inspect them in more detail...

**Comment by rwgk** [comment]
> However, this is somewhat laborious and I didn't expect this would be needed.

Do you have actual custom holders?
The idea is that you can simply remove most or ideally all `std::shared_ptr<T>` holders, because the `smart_holder` also covers the `shared_ptr` handling.
I didn't have an idea for avoiding the need for the macro that would fit into the existing framework. I think it's possible only with intrusive changes to pybind11, maybe, I haven't thought a lot about that direction.

I'll look into the `list` `unique_ptr` issue later. (I want to cleanup #2902 first.)

**Comment by rhaschke** [comment]
True, using the `smart_holder` instead of `std::shared_ptr<T>` avoids the need for the macro. However, requiring the macro breaks existing code and we should find a better solution, I think.
Also, I noticed, using `std::shared_ptr` holders (instead of smart holders), breaks function calls passing the same (shared) argument twice: `f(arg, arg)`.

**Comment by rwgk** [comment]
> However, requiring the macro breaks existing code and we should find a better solution, I think.

Sorry I need to explain this better before announcing the `smart_holder` for wider use: you're basically jumping ahead by using `-DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT` (see comment for the macro). I put being compatible with existing code over ease of using `smart_holder`, given the constraint that either the `smart_holder` (without that define) or `unique_ptr`/`shared_ptr` (with that define) require a macro — unless, maybe, pybind11 is redesigned in a fundamental way, but almost certainly incompatible with existing code.

> Also, I noticed, using std::shared_ptr holders (instead of smart holders), breaks function calls passing the same (shared) argument twice: f(arg, arg).

That's unexpected. If you have `py::class<T, std::shared_ptr<T>>` with the `PYBIND11_SMART_POINTER_HOLDER_TYPE_CASTERS` macro (is that what you have?) I don't expect a behavior change at all, compared to vanilla pybind11 `master`.

**Comment by rhaschke** [comment]
I tried to reproduce this issue in pybind11 with a minimal test case - but I couldn't. I don't yet understand what happens...
The second issue (using `make_iterator` on a container of `std::unique_ptrs`) is reproducable though. See [here](https://github.com/pybind/pybind11/compare/smart_holder...rhaschke:breaking-test) for the tests.

**Comment by rwgk** [comment]
> This issue only shows up when
> - using PYBIND11_USE_SMART_HOLDER_AS_DEFAULT
> - defining a class_ with std::shared_ptr holder in an *external* compilation unit

You need `PYBIND11_SMART_POINTER_HOLDER_TYPE_CASTERS(External, std::shared_ptr<External>)` also in test_class.cpp.

I know this isn't great, but see the rationale from before (compatibility/fitting into exisiting more important than ease of use).

Note that the PyCLIF pybind11 code generator we're working on does NOT use `smart_holder` as the default. It automatically creates a header file for each extension with the `SMART_HOLDER_TYPE_CASTERS` macros, and the existing PyCLIF architecture already enforces that these are included when needed. I.e. it's a non-issue for us.

Moving everybody to smart_holder as the default will come with the advice to remove all `std::shared_ptr holders`. The only situation where macros or maybe alternatively/better `#include`s are needed are for custom smart pointers used as holders. What exactly is still wide open. I'm thinking ideally we'll bake support for custom smart pointers into the `smart_holder` and then remove `type_caster_base` entirely. This will mean though that people with custom smart pointers will have to make changes to switch (changes more involved then adding a one-line macro in the right places). [wires crossing: I wrote this before you just edited your message]

**Comment by rhaschke** [comment]
Thanks for the feedback. I knew migrating away from `std::shared_ptr` holders would resolve the first issue. But, it was driving me crazy that I wasn't able to reproduce the issue in pybind11 unittest. Now, we know that it is related to external compilation units.

**Comment by rwgk** [comment]
Is this the error message for the `IntTypeList` case?

https://github.com/pybind/pybind11/blob/d6cf6dfed3dda6941f2be4b5bdcc80a2f6e4d8c5/include/pybind11/detail/smart_holder_type_casters.h#L414

I need to debug that. If you could create a PR just for that case, with the "Allow edits and access to secrets by maintainers" box checked, that would be a great start for me. `test_class_sh_make_iterator` might be a good name; maybe we want to keep it permanently.

**Comment by rhaschke** [comment]
I'm closing this in favor of #2904. I tracked the issue down to a missing cast implementation.
