### ISSUE TITLE
Potential Windows Issue

### ISSUE THREAD

**Issue by profPlum** [pybind/pybind11#291]
This isn't really a bug but it can happen and I think there should be a warning about it for windows users. One of the windows system headers, "minwindef.h", defines the macros min() and max() which then mess with code in cast.h which uses the std::numeric_limits min() and max() functions. It took me forever to figure out why I got a syntax error when trying to bind a function with integer arguments and couldn't find any help online. I think it would be great if you guys made a check to undefine those macro's if they're there or warn windows users to include the pybind11.h header first.

**Comment by wjakob** [comment]
ok, fair enough.
