### ISSUE TITLE
PYBIND11_OVERLOAD_* with void return type

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#293]
Is it just not meant to work? (in which case the docs should probably mention that...)

Looks like because of code like this

```cpp
return cname::fn(__VA_ARGS__)
```

it would always try to return something, which wouldn't work with `void` return type.

**Comment by wjakob** [comment]
Have you tried this, or just an observation from looking at the code? (I think this construct is allowed.)

**Comment by aldanor** [comment]
Yep (unless I'm missing something):

```sh
pybind11/pybind11.h:1298:33: error: return-statement with a value, in function returning 'void' [-fpermissive]
     return cname::fn(__VA_ARGS__)
```

**Comment by jagerman** [comment]
Are you sure you that whatever cname::fn expands to is actually a void function?  `return f();` should be perfectly fine if `f` is actually void.  (I can also confirm that I have some overloaded void functions without getting this error).

**Comment by aldanor** [comment]
Yeah, my bad, some other error somewhere was causing this obscure error message which led me looking in a wrong place.

Apologies 🐼
