### ISSUE TITLE
[CI] Boost has been removed from GHA

### ISSUE THREAD

**Issue by henryiii** [pybind/pybind11#2946]
Boost has been removed from the GHA images, see https://github.com/actions/virtual-environments/issues/2667. We depended on it for our Boost tests, so we'll need to manually install it, use an image, etc. to do this test. Currently, due to the environment variable setting, it's just doing the same thing as the non-boost tests, I think.

**Comment by philbucher** [comment]
not sure if relevant, but here is a solution of how to make it work in Win: https://github.com/KratosMultiphysics/Kratos/pull/8474
