### ISSUE TITLE
Simplify custom exception handling

### ISSUE THREAD

**Issue by jagerman** [pybind/pybind11#295]
The current custom exception handling (added by @pschella in PR #273) is nice for exposing custom exceptions to Python code, but a little bit cumbersome in declaration.  Unless I'm missing some existing simplification, it requires (copying from `example-custom-exceptions.cpp`):

```C++
    static py::exception<MyCppException> ex(m, "MyPythonException");
    py::register_exception_translator([](std::exception_ptr p) {
        try {
            if (p) std::rethrow_exception(p);
        } catch (const MyCppException &e) {
            PyErr_SetString(ex.ptr(), e.what());
        }
    });
```
This seems needlessly complex in the definition code: basically every definition is going to look exactly the same.  Would it not be possible to expose some other, simplified interface such as:

```C++
py::register_exception<CppException>(m, "PythonExceptionName");
```
that creates the internal static instance and registers the translator?  Even a macro, such as `PYBIND11_CUSTOM_EXCEPTION(CppException, PythonException, m)` would be considerably more convenient.  Of course I could write such a macro for my own code--but right now the custom exception definition seems to require a lot of what feels like implementation detail.

Granted the current code allows you to group multiple exceptions together, but that seems like a very minimal gain for the increased definition complexity.

**Comment by aldanor** [comment]
Agreed. That would be the most common use case, I believe. The `register_` prefix may seem a bit weird since you don't have to `register_class`, but it's not too bad. Is it realistic registering an exception but not providing a translator for it?

Also, in the general case, it would be nice to avoid having to access raw Python API:

```cpp
PyErr_SetString(PyExc_RuntimeError, e.what());
```

Could this be bundled in a method?

**Comment by jagerman** [comment]
See the PR #296: it lets you write just:

```C++
py::register_exception<MyCppException>(m, "MyPythonException");
```
as a shortcut for all the code in the original message. (i.e. it declares the static variable *and* registers the translator that does the try/catch/PyErr_SetString internals).  It's not replacing declaring your own py::exception and using it though: that's still something you might want to do to, for example, extract some extra info from the C++ exception, or catch several different (perhaps related) exceptions in one handler.

Re: the register_ prefix, it does match the "register_exception_translator" naming, but perhaps something like ``py::translate_exception<MyCppException>(m, "MyPythonException");`` would be a better name?

**Comment by pschella** [comment]
I am definitely in favour of adding a convenience method. No preference for the naming. Just please keep in mind that some users (including us) require the ability to register a custom translator that does some more complicated trickery (In our case calling back to Python to get an exception type to set with `PyErr_SetObject`). But as long as the current functionality keeps working I'm happy :) Thanks for the improvement!

P.S. I would suggest to leave the more elaborate example in place in addition to the shortcut so people can see what is possible.

**Comment by jagerman** [comment]
Oh yes, this doesn't remove the existing implementation at all, it just adds a convenience wrapper around it for the common single exception translation case.  I also didn't remove anything from the example file, but just added another example using the helper function.

**Comment by wjakob** [comment]
I agree with @pschella. The ability to do custom stuff in the exception translator is pretty neat.

FYI: I'd like to keep this PR on hold until the possible repercussions of multiple inheritance making it into pybind11 are clear. In particular, the ability to derive from a Python exception type using standard mechanisms (i.e. class_<>) would change things around quite a bit.

None of the exception stuff is official API yet (it's all only in 'master' at this point). I want to make sure that we nail the a API before releasing it as a feature that will need to be supported in the future.

**Comment by wjakob** [comment]
Closing this as PR #296 was merged.
