### ISSUE TITLE
[FEAT] Merge two py::dict

### ISSUE THREAD

**Issue by shelllet** [pybind/pybind11#2976]
dict like a container,   if pybind11 proivde a merege two dict function  is so great.

**Comment by tttapa** [comment]
You can use the `dict::update` function:

```cpp
PYBIND11_MODULE(module, m) {
    m.def("merge_dicts", [](py::dict a, const py::dict b) { a.attr("update")(b); });
}
```
```py
import module as m
a = {1: 'One', 2: 'Two'}
b = {3: 'Three'}
m.merge_dicts(a, b)
print(a)
```
```py
{1: 'One', 2: 'Two', 3: 'Three'}
```

**Comment by shelllet** [comment]
> You can use the `dict::update` function:
> 
> ```c++
> PYBIND11_MODULE(module, m) {
>     m.def("merge_dicts", [](py::dict a, const py::dict b) { a.attr("update")(b); });
> }
> ```
> 
> ```python
> import module as m
> a = {1: 'One', 2: 'Two'}
> b = {3: 'Three'}
> m.merge_dicts(a, b)
> print(a)
> ```
> 
> ```python
> {1: 'One', 2: 'Two', 3: 'Three'}
> ```

thks!
