### ISSUE TITLE
[QUESTION]  Segmentation Fault (core dumped) in array initialization.

### ISSUE THREAD

**Issue by y0ngw00** [pybind/pybind11#2983]
I tried to change Eigen::Vectorxd(like std::vector) to py::array_t

```
namespace py = pybind11;
py::array_t<double> toNumPyArray(const Eigen::VectorXd& vec)
{	
      uint n = vec.rows();

      py::array_t<double> array(n);   // <- This code causes segmentation fault.
  
      py::buffer_info buf = array.request(true);
      
      double* ptr = reinterpret_cast<double*>(buf.ptr);
    
      for(int i =0;i<n;i++)
      {
          ptr[i] = (double)vec(i);
      }

	return array;
}
```

Before access the value of c++ variable, segmentation fault occurs  when initialize py::array_t.
I have no idea what the problem is.
Python version is 3.6.9. and pybind11 version is 2.6.3.

**Comment by y0ngw00** [comment]
I don't know why, but I solve this problem by re-installing pybind11.

**Comment by elSomewhere** [comment]
I am having the exact same issue - re-installing pybind11 did not help however.

**Comment by SmileGoat** [comment]
the same issue, core dump.  
    auto result = py::array_t<double>(num_frames * Dim());
