### ISSUE TITLE
[QUESTION] How to convert python object to None type.

### ISSUE THREAD

**Issue by sirius-william** [pybind/pybind11#2986]
I have following python module:
```cpp
#include <pybind11/pybind11.h>
#include <iostream>
void run(pybind11::object& t){
	t = pybind11::none();
}

PYBIND11_MODULE(PybindTest, m){
	m.def("run", &run);
}
```
In function run(), I would like to convert python list to None, using like this:
```python
import PybindTest as p
a = [1, 2, 3]
p.run(a)
print(a) #a is also [1, 2, 3]
```
The output I expected is 'None', but it didn't work.
Another, other python such as int, str, class and etc. also can not convert to None.
How should I do?
Thanks guys.

**Comment by illumitata** [comment]
Hi @sirius-william,

That should answer your question, citing from docs:

> However, certain basic Python types (like str, int, bool, float, etc.) are immutable. This means that the following attempt to port the function to Python doesn’t have the same effect on the value provided by the caller – in fact, it does nothing at all. 

https://pybind11.readthedocs.io/en/stable/faq.html#limitations-involving-reference-arguments
