### ISSUE TITLE
Cannot expose read-only property using class method

### ISSUE THREAD

**Issue by malagbek** [pybind/pybind11#299]
Hallo,

i wanted to expose method of a class as a read-only property, see below

```
#include <pybind11/pybind11.h>

class A
{
public:
  int x() const
  {
    return 5;
  }
};

namespace py = pybind11;

PYBIND11_PLUGIN(example) {
  py::module m("example", "pybind example plugin");
  py::class_<A>(m, "A")
    .def_readonly("x", &A::x);
  return m.ptr();
}
```
when compiling above with msvc14 update2 i get following error message:

`mod.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xlocale(341): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an.
..\pybind11.git\include\pybind11/pybind11.h(886): warning C4180: Auf Funktionstyp angewendeter Qualifizierer ist ohne Bedeutung; wird ignoriert
mod.cpp(16): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-template "pybind11::class_<A,std::unique_ptr<type,std::default_delete<_Ty>>,type> &pybind11::class_<type,std::unique_ptr<_Ty,std::default_delete<_Ty>>,type>::def_readonly<A,int(void) const,>(const char *,D (__thiscall A::* ))".
        with
        [
            type=A,
            _Ty=A,
            D=int (void) const
        ]
mod.cpp(17): note: Siehe Verweis auf die Instanziierung der gerade kompilierten Funktions-template "pybind11::class_<A,std::unique_ptr<type,std::default_delete<_Ty>>,type> &pybind11::class_<type,std::unique_ptr<_Ty,std::default_delete<_Ty>>,type>::def_readonly<A,int(void) const,>(const char *,D (__thiscall A::* ))".
        with
        [
            type=A,
            _Ty=A,
            D=int (void) const
        ]
..\pybind11.git\include\pybind11/pybind11.h(886): warning C4180: Auf Funktionstyp angewendeter Qualifizierer ist ohne Bedeutung; wird ignoriert
..\pybind11.git\include\pybind11/pybind11.h(886): error C2440: "return": "int (void) const" kann nicht in "int (&)(void) const" konvertiert werden
`

i believe i tried similar thing with def_readwrite it failed too. Is that an expected behavior? Can i only setup properties using internal class fields?

**Comment by jagerman** [comment]
`def_readonly` is for read-only access to member instances, e.g. when you want to provide direct access to `x` in:
```C++
class A {
public:
    int x = 5;
};
```

In your case what you want is the the `def_property_*` methods which take getter/setter member functions, i.e. in your case: `.def_property_readonly("x", &A::x)`.

**Comment by wjakob** [comment]
@jagerman thanks!
