### ISSUE TITLE
How to include opencv? (from a new user with a simple example code)

### ISSUE THREAD

**Issue by placeforyiming** [pybind/pybind11#3003]
This question may be too silly, the code is really simple:

#include <pybind11/pybind11.h>
#include <opencv2/core.hpp>

using namespace std;
namespace py = pybind11;
class Try{
    //default is private
    public:
    float angle_threshold=0.0; 
    int min_number=50;  
    int max_number=20000; 
    //cv::Mat range_img; 
    float data[10] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
    cv::Mat your_matrix = cv::Mat(1, 10, CV_32F, data);
                          
Try(float input_thresh, int input_min, int input_max): angle_threshold ( input_thresh) , min_number (input_min), max_number (input_max) { }
};

PYBIND11_MODULE(example, m) {
    py::class_<Try>(m, "Try")//, py::buffer_protocol())
    	.def(py::init<float, int, int >());
}

Compile:

c++ -O3 -Wall -shared -std=c++11 -fPIC $(python3 -m pybind11 --includes) example.cpp -o example$(python3-config --extension-suffix)

In terminal :

python3
>>> import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /workspace/build/example.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv3Mat10deallocateEv

Anyone can provide a hint? I think it might be something very simple but I just cannot find the solution.

**Comment by sirius-william** [comment]
It seems that your project is running on Linux. Maybe you can try to link the library named 'resolv' when linking  project during compile.

**Comment by placeforyiming** [comment]
> It seems that your project is running on Linux. Maybe you can try to link the library named 'resolv' when linking project during compile.

Do you mean instead of the default simple compile command, using cmake to specify all those linked package and compile it as normal c++ projects? If so, do you know if there any place I can find simple examples to learn how to use cmake to compile the project? Thanks

**Comment by biel-wangdf3** [comment]
> > It seems that your project is running on Linux. Maybe you can try to link the library named 'resolv' when linking project during compile.
> 
> Do you mean instead of the default simple compile command, using cmake to specify all those linked package and compile it as normal c++ projects? If so, do you know if there any place I can find simple examples to learn how to use cmake to compile the project? Thanks

i met the same problem，did you solve it?

**Comment by placeforyiming** [comment]
> > > It seems that your project is running on Linux. Maybe you can try to link the library named 'resolv' when linking project during compile.
> > 
> > 
> > Do you mean instead of the default simple compile command, using cmake to specify all those linked package and compile it as normal c++ projects? If so, do you know if there any place I can find simple examples to learn how to use cmake to compile the project? Thanks
> 
> i met the same problem，did you solve it?

Unfortunately, no. I just need some simple functions, so I wrote that part with native c++ operators. But I will leave this open, hope someone can offer help

**Comment by biel-wangdf3** [comment]
> > > > It seems that your project is running on Linux. Maybe you can try to link the library named 'resolv' when linking project during compile.
> > > 
> > > 
> > > Do you mean instead of the default simple compile command, using cmake to specify all those linked package and compile it as normal c++ projects? If so, do you know if there any place I can find simple examples to learn how to use cmake to compile the project? Thanks
> > 
> > 
> > i met the same problem，did you solve it?
> 
> Unfortunately, no. I just need some simple functions, so I wrote that part with native c++ operators. But I will leave this open, hope someone can offer help
i have solved this problem，there are two method can try：
1. use from setuptools import setup, Extension
ext_modules = [
	Extension(
		'dss_api',
		['./cpp/main.cpp'],
		include_dirs=[
			get_pybind_include(),
			get_pybind_include(user=True),
            "path:/opencv/include",
		],
        libraries=['opencv_core','opencv_highgui','opencv_imgcodecs','opencv_imgproc',],
        library_dirs=[
            'path:/opencv/depend/linux/lib',
        ],
		language='c++'
	),
]
2. use CMake
find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})

add_subdirectory(pybind11)
#source file
SET(SOURCES
        ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/mat_warper.h
        ${CMAKE_CURRENT_SOURCE_DIR}/mat_warper.cpp
        )
pybind11_add_module(test_pybind ${SOURCES})
target_link_libraries(test_pybind PRIVATE ${OpenCV_LIBS})
you can reference: 
https://github.com/pybind/python_example

**Comment by placeforyiming** [comment]
> > > > > It seems that your project is running on Linux. Maybe you can try to link the library named 'resolv' when linking project during compile.
> > > > 
> > > > 
> > > > Do you mean instead of the default simple compile command, using cmake to specify all those linked package and compile it as normal c++ projects? If so, do you know if there any place I can find simple examples to learn how to use cmake to compile the project? Thanks
> > > 
> > > 
> > > i met the same problem，did you solve it?
> > 
> > 
> > Unfortunately, no. I just need some simple functions, so I wrote that part with native c++ operators. But I will leave this open, hope someone can offer help
> > i have solved this problem，there are two method can try：
> 
>     1. use from setuptools import setup, Extension
>        ext_modules = [
>        Extension(
>        'dss_api',
>        ['./cpp/main.cpp'],
>        include_dirs=[
>        get_pybind_include(),
>        get_pybind_include(user=True),
>        "path:/opencv/include",
>        ],
>        libraries=['opencv_core','opencv_highgui','opencv_imgcodecs','opencv_imgproc',],
>        library_dirs=[
>        'path:/opencv/depend/linux/lib',
>        ],
>        language='c++'
>        ),
>        ]
> 
>     2. use CMake
>        find_package(OpenCV REQUIRED)
>        include_directories(${OpenCV_INCLUDE_DIRS})
> 
> 
> add_subdirectory(pybind11)
> #source file
> SET(SOURCES
> ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
> ${CMAKE_CURRENT_SOURCE_DIR}/mat_warper.h
> ${CMAKE_CURRENT_SOURCE_DIR}/mat_warper.cpp
> )
> pybind11_add_module(test_pybind ${SOURCES})
> target_link_libraries(test_pybind PRIVATE ${OpenCV_LIBS})
> you can reference:
> https://github.com/pybind/python_example

Thank you! I will try that
