### ISSUE TITLE
Ref counts differ between Python and C++

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [pybind/pybind11#301]
Having the following Python code:

    foo = Foo()
    print("REFPY %s" % len(gc.get_referrers(foo)))
    bar.swallow(foo)

And C++ code:

    .def( "swallow", [](Bar& bar, py::object& fooObj) {
      auto const refCount = fooObj.ref_count();
      std::cerr << "REFC++ " << refCount << std::endl;

Which prints:

    REFPY 1
    REFC++ 3

I was expecting `REFC++` to be perhaps at max 2 but have no idea where the 3 is coming from.

**Comment by abergmeier-dsfishlabs** [comment]
Strangely if I do:

    print("REFPYSYS %s" % sys.getrefcount(foo))

it prints:

    REFPYSYS 2

I assume it is not subtracting its own ref?

**Comment by aldanor** [comment]
Could you post complete examples? It's hard to judge without the context

**Comment by wjakob** [comment]
There is no formal specification of what reference counts are right and wrong under certain situations, so just getting some unusually high numbers does not constitute a bug.

What *would* be a bug is a leak, i.e. if you can't get an object to be garbage collected despite nobody having a reference to it (or a negative refcount).

**Comment by abergmeier-dsfishlabs** [comment]
@wjakob but wouldn't it preferable to only have the references "shown" to coders?
Personally I would expect:

     .def( "swallow", [](Bar& bar, py::object& fooObj) // Refcount of 1 since the calling code needs to own fooObj anyways

     .def( "swallow", [](Bar& bar, py::object fooObj) // Refcount of 2 since fooObj holds a seperate ref

Any disagreements?
