### ISSUE TITLE
[BUG] strdup symbol unresolved on Windows

### ISSUE THREAD

**Issue by glevner** [pybind/pybind11#3024]
pybind11.h makes calls to `strdup()` which, in Visual Studio, is an alias for `_strdup()`, defined in string.h. But pybind11.h does not include string.h. So when I compile and link on Windows, I get an unresolved symbol error. To work around the issue, I have to either modify pybind11.h or include string.h in my code before including pybind11.h.

**Comment by glevner** [comment]
Actually, after more testing, even including string.h is not enough. But defining a macro if `_MSC_VER` is defined does the trick: `#define strdup _strdup`.

**Comment by Skylion007** [comment]
This should be closed by recent PR and we now do explicitly alias strdup. We do also include string.h now as well.
