### ISSUE TITLE
[BUG] pycharm thinks `def_static` methods take a `self` parameter

### ISSUE THREAD

**Issue by Strilanc** [pybind/pybind11#3029]
## Issue description

I use pybind11 to expose stim to python. One of the recurring problems I run into is that, in pycharm, the autocompletion thinks that static factory methods like `stim.Tableau.from_named_gate(name)` take two parameters (self and name) instead of just one (name).

I also reported this as a pycharm issue ( https://youtrack.jetbrains.com/issue/PY-49144 ), because it's unclear to me whether it's the data in the extension that's wrong about the signature or the interpretation of that data that's wrong.

## Reproducible example code

This happens for any static method I make, so you should be able to reproduce it by making a pybind11 module with a class that has a single static method that takes one parameter, building it, pip installing it into a virtual env, using that virtual env in pycharm, and trying to use the method. Alternatively, you can just `pip install stim` and try calling `stim.Tableau.from_named_gate` in pycharm.

Expected result: pycharm is happy with how you called the method.
Actual result: pycharm highlights the invocation in yellow and complains that `self` is missing:

![image](https://user-images.githubusercontent.com/79941/120898931-04476280-c5e2-11eb-9dce-6d155704f1d5.png)

![image](https://user-images.githubusercontent.com/79941/120898945-132e1500-c5e2-11eb-8928-9e7f7dbcddfc.png)

**Comment by HunterTracer** [comment]
I also find this bug and report this issue in https://youtrack.jetbrains.com/issue/PY-49650. My solution can be also found in https://youtrack.jetbrains.com/issue/PY-49650, simply adding two-line code.

**Comment by HunterTracer** [comment]
I think it's not a bug of pybind11, but a bug of Pycharm.
