### ISSUE TITLE
Constructors: rvaluedness and default args

### ISSUE THREAD

**Issue by mavam** [pybind/pybind11#307]
I was wondering what the semantic of `py::init<Ts...>` are. Say I have a type `T` that takes a constructor argument of type `U` by value. Will this result in a move?

Here's an example from my project. A type `subnet` that takes a type `address` by value. The ctor of `subnet` has the signature `subnet(address, uint8_t)`.

```cpp
    .def("__init__",
         [](subnet& instance, address& addr, uint8_t length) {
           new (&instance) subnet{std::move(addr), length};
         })
```

Is this equivalent to `py::init<address, uint8_t>`? Essentially, I wonder whether you perform a `move` or copy on the call side, and whether I should ensure no extra copying by taking a non-const lvalue for `address` in the lambda above.

Two related questions:
1. How do I specify default arguments in constructors?
2. How do I support move-only types in constructors?

For (2), I have a class `context` that takes a `configuration` object by value in the ctor:

```cpp
  class context {
  public:
    context(configuration = {}); // configuration has no copy constructor
  };

  py::class_<context>(m, "Context")
    //.def(py::init<>()) // compile error: attempts to invoke copy ctor
    .def("__init__",
     [](context& instance, configuration& cfg) { // works, but how to specify a default argument?
       new (&instance) context{std::move(cfg)};
     })
```

(Is there a mailing list or better place for such questions? I couldn't find it in the manual.)

**Comment by wjakob** [comment]
Function arguments (in contrast to return values) will never be moved by pybind11. You'll have to write your own wrappers as you did above to accomplish this.

This *will* create issues with in combination with default arguments -- as in Python (and unlike C++), they are constructed *once* at declaration time. If the function subsequently moves the argument, this will lead to changes that are visible in later function calls.

**Comment by wjakob** [comment]
Closing this issue for now -- feel free to post if you think that it should be reopened.

**Comment by mavam** [comment]
Yeah, you can keep it closed, I think I can answer the questions now. Let me see if I read your answer right:

> I wonder whether you perform a move or copy on the call side [..]

Pybind always performs a copy, for all function arguments (including constructors).

> How do I specify default arguments in constructors?

This doesn't appear to be possible. But it's possible to have multiple definitions of `__init__`/`py::init<>` with different signatures.

> 2. How do I support move-only types in constructors?

By using non-const lvalue reference in the `__init__` lambda. However, this may result in UB when accessing the moved-from objects.

**Comment by EricCousineau-TRI** [comment]
Ran into this for trying to use move-only types as default arguments; it would be nice if it could be re-opened, as I think it could be solved by some things like:

(a) if passing an empty initializer list `{}` (or something else), then mark some flag stating that this value should use a default-constructed type. It does require some level of two-communication, so it may be too expensive.
(b) Permit specifying a default argument factory, which could produce a move-only value to immediately be consumed (assuming the `move` part is acomodated in the code).

Granted, the workaround mentioned above - just using a wrapper - works fine 'n well.

\cc @SeanCurtis-TRI
