### ISSUE TITLE
[QUESTION] How to bind NumPy scalar?

### ISSUE THREAD

**Issue by sun1638650145** [pybind/pybind11#3093]
I hope to implement something like this on the Python side.

```python
>>> import numpy as np
>>> from mymodule import print_type
>>> print_type(np.int32(1))
32-bit
>>> print_type(np.int64(1))
64-bit
```

This way of writing pybind is bound to pure Python int.

```c++
#include <iostream>
#include "pybind11/pybind11.h"


void print_type(const int &num) {
    std::cout << "32-bit" << std::endl;
    // do something ...
}

void print_type(const std::int64_t &num) {
    std::cout << "64-bit" << std::endl;
    // do something ...
}

PYBIND11_MODULE(mymodule, m) {
    m.def("print_type", pybind11::overload_cast<const int &>(&print_type));
    m.def("print_type", pybind11::overload_cast<const std::int64_t &>(&print_type));
}
```

**Comment by jiwaszki** [comment]
Here you go, little tricky but should do the work:
```cpp
#include <iostream>
#include "pybind11/pybind11.h"

void print_type(const pybind11::buffer &num)
{
    auto a = num.request().format;
    if (a == "i")
    {
        std::cout << "32-bit" << std::endl;
        // do something for int...
    }
    else if (a == "l")
    {
        std::cout << "64-bit" << std::endl;
        // do something for std::int64_t...
    }
}

PYBIND11_MODULE(mymodule, m)
{
    m.def("print_type", &print_type);
}
```
Where to get values for each format? Here: https://docs.python.org/3/library/array.html

The `print_type` function can later call other specified functions to work on exact buffer values accordingly to dtype. Treat it like a "dispatcher".

**Comment by sun1638650145** [comment]
Using your method can indeed solve the problem, thanks. Finally, I hope that pybind can develop functions like this. https://github.com/pybind/pybind11/pull/2060#issue-360680968 Although your method solves the problem, the type annotation shows `buffer` instead of `int32` or `int64`.

**Comment by jiwaszki** [comment]
@sun1638650145 would be nice for if that PR was master. Very convenient approach and will resolve your issue with type annotations. Sadly it looks like it is stale or dropped completely...
