### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by RubaiyaLU** [pybind/pybind11#3131]
~/pybind11/pybind11_dev/pybind11/build$ ls -lha
total 88K
drwxr-xr-x 5 wy wy 4,0K juil. 18 03:57 .
drwxr-xr-x 4 wy wy 4,0K juil. 18 04:19 ..
-rw-r--r-- 1 wy wy  21K juil. 18 03:07 CMakeCache.txt
drwxr-xr-x 7 wy wy 4,0K juil. 18 03:57 CMakeFiles
-rw-r--r-- 1 wy wy 3,6K juil. 18 03:07 cmake_install.cmake
-rw-r--r-- 1 wy wy 1,1K juil. 18 03:07 cmake_uninstall.cmake
-rw-r--r-- 1 wy wy 3,1K juil. 18 03:57 install_manifest.txt
-rw-r--r-- 1 wy wy  20K juil. 18 03:57 Makefile
drwxr-xr-x 4 wy wy 4,0K juil. 18 03:13 mock_install
-rw-r--r-- 1 wy wy 7,7K juil. 18 03:07 pybind11Config.cmake
-rw-r--r-- 1 wy wy 2,0K juil. 18 03:07 pybind11ConfigVersion.cmake
drwxr-xr-x 6 wy wy 4,0K juil. 18 03:57 tests

I have followed all the steps but module is missing here. Also facing module_error while import example or any module.
What should I do?Please suggest

**Comment by henryiii** [comment]
Not enough to go on. Please reopen with more information (such as the steps you followed, link to a repo, etc). It looks like you might not have run the build step, but just run the configure step?
