### ISSUE TITLE
[BUG] Incorrect cmake install path in 2.7.0 release?

### ISSUE THREAD

**Issue by stellaraccident** [pybind/pybind11#3136]
I have a local requirements.txt file that just uses the latest pybind11 and when I rebuilt my environment, I got the 2.7.0 release, which looks new. However, CMake is detecting include and lib paths that look suspiciously like they are from the VM that built it, not the actual install location on my machine. Example CMake output:

```
-- found (/home/stella/src/iree-forge/build/iree-forge.venv/lib/python3.8/site-packages/pybind11/share/cmake/pybind11)
-- Found pybind11: /home/runner/work/pybind11/pybind11/pybind11/include (found version "2.7.0" )
-- Found pybind11 v2.7.0: /home/runner/work/pybind11/pybind11/pybind11/include
```

This was found while building the LLVM/MLIR python bindings from head with recommended instructions: https://mlir.llvm.org/docs/Bindings/Python/ (but I imagine there are easier ways to repro). I'm about to push a commit that excludes that version from our dev setup.

**Comment by henryiii** [comment]
Verified, the generated Config file has `set(pybind11_INCLUDE_DIR "/home/runner/work/pybind11/pybind11/pybind11/include")
` instead of a relative path.

**Comment by henryiii** [comment]
This was broken by https://github.com/pybind/pybind11/pull/3005 - `CMAKE_INSTALL_FULL_INCLUDEDIR` is an absolute path so this breaks using this from the Python package.
