### ISSUE TITLE
[QUESTION] [Can't assign value to std::vector by python::list when I use bind_vec]

### ISSUE THREAD

**Issue by MrChengmo** [pybind/pybind11#3140]
I am a beginer of pybind, I try to  bind a Struct to Python, here is my code:

```C++
// struct defination
Stuct Cluster {
std::vector<std::string> worker;
}

//pybind code
PYBIND11_MAKE_OPAQUE(std::vector<std::string>);
py::bind_vector<std::vector<std::string>>(m, "VectorString");

py::class_<Cluster>(m, "Cluster")
    .def(py::init<>())
    .def_readwrite("worker", &Cluster::worker);
```
when i try to use it at python

```python
c = Cluster()
print(c.worker)
# VectorString[]

# it work well when i use append to create new value
c.worker.append("123")
print(c.worker)
# VectorString[123]

# however, I can't assign a value to it with a list
c.worker = ["123"]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: core.Cluster, arg0: core.VectorString) -> None

Invoked with: <core.Cluster object at 0x7f6aef6d7ed8>, ['123']
```

What should I do to use this struct.vector like Python list ？

**Comment by jiwaszki** [comment]
First of you need to understand what are you doing using `PYBIND11_MAKE_OPAQUE ` and `py::bind_vector`. You are creating class across your module that looks at every `std::vector<std::string>` as it is Python Class called `VectorString`. This way you are able to assign new values only if they are matching the type of `worker`, so this is how you assign to it:
```python
c.worker = mymodule.VectorString(["456"])
print(c.worker)
# VectorString[456]
```

To fix your last case you need to override setting property method, something like this should make it work:
```cpp

std::vector<std::string> init_vec(const pybind11::handle &vec)
{
    std::vector<std::string> _vec;

    for (auto s : vec)
    {
        _vec.push_back(pybind11::cast<std::string>(s));
    }

    return _vec;
}

PYBIND11_MODULE(mymodule, m)
{
    pybind11::bind_vector<std::vector<std::string> >(m, "VectorString");

    pybind11::class_<Cluster>(m, "Cluster")
        .def(pybind11::init<>())
        // .def_readwrite("worker", &Cluster::worker);
        .def_property(
            "worker",
            [](const Cluster &self)
            { return self.worker; },
            [](Cluster &self, const pybind11::handle &a)
            {
                self.worker = init_vec(a);
            });
}
```
There is one drawback of this fix, it is breaking `append` method. I was not debugging that issue but maybe you can pick it up from here and with that knowledge handle it :)

**Comment by MrChengmo** [comment]
> First of you need to understand what are you doing using `PYBIND11_MAKE_OPAQUE ` and `py::bind_vector`. You are creating class across your module that looks at every `std::vector<std::string>` as it is Python Class called `VectorString`. This way you are able to assign new values only if they are matching the type of `worker`, so this is how you assign to it:
> 
> ```python
> c.worker = mymodule.VectorString(["456"])
> print(c.worker)
> # VectorString[456]
> ```
> 
> To fix your last case you need to override setting property method, something like this should make it work:
> 
> ```c++
> std::vector<std::string> init_vec(const pybind11::handle &vec)
> {
>     std::vector<std::string> _vec;
> 
>     for (auto s : vec)
>     {
>         _vec.push_back(pybind11::cast<std::string>(s));
>     }
> 
>     return _vec;
> }
> 
> PYBIND11_MODULE(mymodule, m)
> {
>     pybind11::bind_vector<std::vector<std::string> >(m, "VectorString");
> 
>     pybind11::class_<Cluster>(m, "Cluster")
>         .def(pybind11::init<>())
>         // .def_readwrite("worker", &Cluster::worker);
>         .def_property(
>             "worker",
>             [](const Cluster &self)
>             { return self.worker; },
>             [](Cluster &self, const pybind11::handle &a)
>             {
>                 self.worker = init_vec(a);
>             });
> }
> ```
> 
> There is one drawback of this fix, it is breaking `append` method. I was not debugging that issue but maybe you can pick it up from here and with that knowledge handle it :)

Thanks for you help!

I solved the problem yesterday and used this method

```c++
//pybind code
using VectorString = std::vector<std::string>;
PYBIND11_MAKE_OPAQUE(VectorString);
py::bind_vector<VectorString>(m, "VectorString");
py::implicitly_convertible<py::iterable, VectorString>();
```

Use the `py::implicitly_convertible` function, list can be automatically converted to vector

**Comment by jiwaszki** [comment]
@MrChengmo great news! So fix was found, please close the issue to keep it clean here 😄
