### ISSUE TITLE
[QUESTION] Is it possible to define functions in an embedded module with pure Python codes?

### ISSUE THREAD

**Issue by sunyj** [pybind/pybind11#3147]
I know it sounds a bit wierd, why not just define it in Python?  Anyway, this is what I'm trying to work out:

```c++
// Define embedded module in C++
PYBIND11_EMBEDDED_MODULE(mymod, m) {
    m.doc() = "my test module";
    py::eval("def plus1(x): return x + 1");
}
```

```python
# Call it in Python
import mymod
mymod.plus1(1) # ==> 2
```

The code won't work apparently, but is there a way to do that?

**Comment by jiwaszki** [comment]
Hi, I am not quite sure what you are trying to accomplish here. Reading from [here](https://pybind11.readthedocs.io/en/stable/advanced/embedding.html#embedding-the-interpreter):

> While pybind11 is mainly focused on extending Python using C++, it’s also possible to do the reverse: embed the Python interpreter into a C++ program.

But looking at your code you are doing quite opposite - you are importing new interpreter inside existing one. That would not work, probably it will throw an error like `the interpreter has been initialized`.

If you like to bind your code the way you are trying to invoke it, do it like this:
```cpp
PYBIND11_MODULE(mymodule, m)
{
    m.doc() = "my test module";
    m.def("plus1", [](int x)
          { return x + 1; });
}
```
