### ISSUE TITLE
[QUESTION] How to expose a large c style array in C++ to python

### ISSUE THREAD

**Issue by coderev** [pybind/pybind11#3156]
Hi all, I'm new to pybind11. I want to expose a large c style array in C++ to python. 
I checked the manual and Googled the related topics, but cannot find detailed information about how to achieve this goal.
The following is what I tested:
```
typedef struct _tagPixel
{
    float x,y,z;
    int color;
}PIXEL;

class Image
{
private:
    /* data */
public:
    Image(/* args */);
    ~Image();
    PIXEL _data[100];
};

Image::Image(/* args */)
{
}

Image::~Image()
{
}


// pybind11
#include <pybind11/stl.h>
#include <pybind11/pytypes.h>
#include <pybind11/numpy.h>
#include <pybind11/complex.h>
#include <pybind11/functional.h>

namespace py = pybind11;


PYBIND11_MODULE(raw_array, m) {
    PYBIND11_NUMPY_DTYPE(PIXEL, x, y, z, color);
    py::class_<Image>(m, "image", py::buffer_protocol())
    .def_property_readonly("data", [](Image &self) -> py::array {
            auto dtype = py::dtype(py::format_descriptor<PIXEL>::format());
            auto base = py::array(dtype, {100}, {sizeof(PIXEL)});
            return 
                py::array(dtype, {100}, {sizeof(PIXEL)}, self._data, base);
        })


}
```
when in Python, I use this module as following:

```
import numpy as np
import raw_array
p=raw_array.image
n=np.array(p.data)
print(list(n))
```
and the IDE displays:
**_File "/mnt/c/test/build/arr.py", line 5, in <module>
n=np.array(p.data)
TypeError: iteration over a 0-d array_**

I'm not sure if anything I made wrong, I cannot find a standard answer from Google...
Is anyone can kindly show me how to expose the c style array to python?
Thanks in advance.

**Comment by jiwaszki** [comment]
Hello, you need to add `py::init` to your class. I have simplified your example since using custom `PIXEL` as numpy dtype is a different thing:
```cpp
class Image
{
private:
    /* data */
public:
    Image(/* args */);
    ~Image();
    int _data[100];
};

Image::Image(/* args */)
{
}

Image::~Image()
{
}

// pybind11
#include <pybind11/stl.h>
#include <pybind11/pytypes.h>
#include <pybind11/numpy.h>
#include <pybind11/complex.h>
#include <pybind11/functional.h>

namespace py = pybind11;

PYBIND11_MODULE(mymodule, m)
{
    py::class_<Image>(m, "image", py::buffer_protocol())
        .def(pybind11::init<>())
        .def_property_readonly("data", [](Image &self) -> py::array
                               {
                                   auto dtype = py::dtype(py::format_descriptor<int>::format());
                                   auto base = py::array(dtype, {100}, {sizeof(int)});
                                   return py::array(dtype, {100}, {sizeof(int)}, self._data, base);
                               });
}
```

For custom dtype you should switch line responsible for dtype to:
```cpp
auto dtype = py::dtype::of<PIXEL>();
```
Hope that answer your questions!

**Comment by coderev** [comment]
> Hello, you need to add `py::init` to your class. I have simplified your example since using custom `PIXEL` as numpy dtype is a different thing:
> 
> ```c++
> class Image
> {
> private:
>     /* data */
> public:
>     Image(/* args */);
>     ~Image();
>     int _data[100];
> };
> 
> Image::Image(/* args */)
> {
> }
> 
> Image::~Image()
> {
> }
> 
> // pybind11
> #include <pybind11/stl.h>
> #include <pybind11/pytypes.h>
> #include <pybind11/numpy.h>
> #include <pybind11/complex.h>
> #include <pybind11/functional.h>
> 
> namespace py = pybind11;
> 
> PYBIND11_MODULE(mymodule, m)
> {
>     py::class_<Image>(m, "image", py::buffer_protocol())
>         .def(pybind11::init<>())
>         .def_property_readonly("data", [](Image &self) -> py::array
>                                {
>                                    auto dtype = py::dtype(py::format_descriptor<int>::format());
>                                    auto base = py::array(dtype, {100}, {sizeof(int)});
>                                    return py::array(dtype, {100}, {sizeof(int)}, self._data, base);
>                                });
> }
> ```
> 
> For custom dtype you should switch line responsible for dtype to (I would recommend to do it anyway instead of `py::format_descriptor`):
> 
> ```c++
> auto dtype = py::dtype::of<PIXEL>();
> ```
> 
> Hope that answer your questions!

Thanks @jiwaszki for your help , sorry for late reply, the connection to Github is not stable in these days from my location...
I'll try it later, and feedback asap.
:-)

**Comment by coderev** [comment]
Thanks for the help from @jiwaszki !
Basically, the solution works. And I also find a better way which is recommended by pybin11 official documents.
The best practice for exposing c style array to python is to change it from its raw c-style array to a std::array type. Only a minor changes we need to make, but it's quite easy to export them to python, the conversion is implicit and fully automatically!
