### ISSUE TITLE
[BUG]: terminate called after throwing an instance of 'pybind11::error_already_set'

### ISSUE THREAD

**Issue by houyongkuo** [pybind/pybind11#3165]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

Hi, when I reproduce the Teaser++（https://github.com/MIT-SPARK/TEASER-plusplus#readme） library the error occued：
`terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  SystemError: <built-in method __repr__ of PyCapsule object at 0x7f5e01b0b5d0> returned a result with an error set
Aborted (core dumped)
`

**Comment by henryiii** [comment]
Please open an issue with Teaser++. We can't take action until they have at least updated to pybind11 2.7.1, and tried to solve it themselves.
