### ISSUE TITLE
callback function with numpy parameter problem

### ISSUE THREAD

**Issue by Fokatu** [pybind/pybind11#3173]
two problems.

1. what wrong with the following code?  When the function is called, I got an exception 
![image](https://user-images.githubusercontent.com/25919117/128167669-ccf90cf8-a6cb-4441-8361-2df2a5134700.png)

```
void test()
{
	double* data = new double[3 * 5];
	py::array_t<double> arr(3 * 5, data);
	delete[] data;
}
```

2. My need is to create a python callback function with a numpy ndarray parameter. But when I try to pack the data as a py::array_t object in cpp code I got the problem in 1. Is there another way to pass double[] to python callback? 
 
Thanks!

_Originally posted by @Fokatu in https://github.com/pybind/pybind11/discussions/3172_

**Comment by henryiii** [comment]
This is already a discussion, closing here.
