### ISSUE TITLE
[BUG]: Linking against pybind11 in cmake changes build order

### ISSUE THREAD

**Issue by willsimmons1465** [pybind/pybind11#3176]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

When using Catch2 (https://github.com/catchorg/Catch2) for C++ testing with multiple test files, the tests are run by default in the order in which the test files are listed in the CMakeLists file when building the test executable. When I tried to use pybind11::embed to write some tests that used some python libraries, the order of the test files was reversed which causes test failures when the output of tests is dependent on the order (e.g. they use some global data shared between the tests). I narrowed this down to the test shown here. Even though none of the C++ code uses pybind, simply linking against it changes the order of tests.

This was exhibited using the following:
Ubuntu 20.04
gcc 10.3.0
cmake 3.19.6
conan 1.37.2 with catch2/2.13.6 and pybind11/2.6.1

I retried on other systems and this behaviour was observed on our Linux CI server, but not on my MacBook Pro, so this could be some weird system-dependent cmake issue.

I would never claim to be a build systems expert, but having the build order be dependent on the libraries linked after building seems pretty wild to me.

### Reproducible example code

```text
File structure:

.
+-- recipes
|   +-- pybinderr
|   |   +-- test_package
|   |   |   +-- conanfile.py
|   |   +-- conanfile.py
+-- src
|   +-- CMakeLists.txt
|   +-- main.cpp
|   +-- test_file1.cpp
|   +-- test_file2.cpp
```

recipes/pybinderr/test_package/conanfile.py
```
import os
from conans import ConanFile

class PybindErrTestConan(ConanFile):
    keep_imports = True

    def imports(self):
        self.copy("*", src="@bindirs", dst="bin")
        self.copy("*", src="@libdirs", dst="lib")

    def test(self):
        os.chdir("bin")
        self.run(os.path.join(os.curdir, "mytest") + " -l")
```

recipes/pybinderr/conanfile.py
```
from conans import ConanFile, CMake

class PybindErrConan(ConanFile):
    name = "pybinderr"
    version = "0.1"
    generators = ("cmake", "cmake_find_package")
    exports_sources = "../../src/*"
    requires = (
        "catch2/2.13.6",
        "pybind11/2.6.1"
    )

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        executable_filename = "bin/mytest"
        self.copy(executable_filename)
```

src/CMakeLists.txt
```
cmake_minimum_required(VERSION 3.16.0)

project(pybinderr)

find_file(CONANBUILDINFO_FILE conanbuildinfo.cmake HINTS ${CMAKE_BINARY_DIR})
include(${CONANBUILDINFO_FILE})
conan_basic_setup()

find_package(Catch2 REQUIRED)
find_package(pybind11 REQUIRED)

set(TEST_EXE mytest)

set(TEST_SOURCES
    # The ordering here is the order in which catch2 will run the tests
    main.cpp
    test_file1.cpp
    test_file2.cpp
    )

add_executable(${TEST_EXE} ${TEST_SOURCES})

# If we add any pybind11 link option here, the order gets reversed
target_link_libraries(${TEST_EXE} Catch2::Catch2)
# target_link_libraries(${TEST_EXE} Catch2::Catch2 pybind11::headers)
```

src/main.cpp
```
#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>
```

src/test_file1.cpp
```
#include <catch2/catch.hpp>

SCENARIO("Test 1")
{
    REQUIRE(true);
}
```

src/test_file2.cpp
```
#include <catch2/catch.hpp>

SCENARIO("Test 2")
{
    REQUIRE(true);
}
```

Output without linking pybind11::headers
```
All available test cases:
  Scenario: Test 1
  Scenario: Test 2
2 test cases
```

Output with linking pybind11::headers
```
All available test cases:
  Scenario: Test 2
  Scenario: Test 1
2 test cases
```
```

**Comment by henryiii** [comment]
Could you try replacing the pybind11::headers usage with

```cmake
add_library(pybind11_headers INTERFACE)
target_include_directories(
pybind11_headers GLOBAL INTERFACE $<BUILD_INTERFACE:include>
                                $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)

target_compile_features(pybind11_headers INTERFACE cxx_inheriting_constructors cxx_user_literals
                                                     cxx_right_angle_brackets)
```

(Simpler might work too, but trying to include anything that might affect it).

Also, if you throw that in a Gist, it would be easier to quickly test.

**Comment by henryiii** [comment]
Oops, SYSTEM, not GLOBAL, sorry.

**Comment by willsimmons1465** [comment]
Thanks for the quick response! Here's a Gist for the CMakeLists.txt with your suggestion added: https://gist.github.com/willsimmons1465/5bc9e05a1b35e9b6fd62d7b1c8c39fbb
This doesn't quite replace the pybind11::headers usage since it would not allow including any pybind headers in the actual code (adding `#include <pybind11/pybind.h>` to one of the test files fails to compile because it can't find Python.h), and using this alongside pybind11::headers still has the reversed test order.

**Comment by henryiii** [comment]
You can point it at the path, or better yet, just don't import pybind11, as you are looking for the ordering, not pybind11 behavior. I don't see an include for pybind11 in the example files. Can you put the other files into the Gist? That way I could download it and run it.

I'm basically trying to see if we can reproduce the flipped ordering without pybind11 (I would assume so, because we can't touch the source file list from a linked target). If so, it's likely a bug for CMake.

**Comment by henryiii** [comment]
Also, you can build in verbose mode, and you should see the order of the source files flip.  Honestly, I didn't even realize that you could detect source file ordering when you compile - to me it I would think it's something Catch2 decides.

**Comment by henryiii** [comment]
(For linking it can matter, but still not "detectable" by a library, IFAIK)

**Comment by henryiii** [comment]
https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#specify-the-order-test-cases-are-run

It's (linking) implementation dependent. Check to see what the two commands look like when building with `cmake --build build_dir -v`.
