### ISSUE TITLE
Trampoline classes and inheritance

### ISSUE THREAD

**Issue by jagerman** [pybind/pybind11#320]
Not so much an issue as a question about using a trampoline class, and perhaps something worth adding to the documentation.

I'm finding cases in my library where I want to bind both a base class with virtual methods and some derived classes of the base class, to allow the python classes to themselves inherit from either the base or derived classes.  As an illustrative example, consider:

```C++
class A {
public:
    virtual void methodA1();
    virtual void methodA2();
    virtual void methodA3();
    virtual void methodA4();
};
class B : public A {
public:
    virtual void methodA1() override;
    void methodA2() override;
    virtual void methodB1();
};
class C : public B {
public:
    virtual void methodC1();
};

// Trampoline classes
class PyA : public A {
public:
    void methodA1() override { PYBIND11_OVERLOAD(void, A, methodA1); }
    void methodA2() override { PYBIND11_OVERLOAD(void, A, methodA2); }
    void methodA3() override { PYBIND11_OVERLOAD(void, A, methodA3); }
    void methodA4() override { PYBIND11_OVERLOAD(void, A, methodA4); }
};
class PyB : public B {
    void methodA1() override { PYBIND11_OVERLOAD(void, B, methodA1); }
    // B's overridden methodA2() not virtual
    void methodA3() override { PYBIND11_OVERLOAD(void, B, methodA3); }
    void methodA4() override { PYBIND11_OVERLOAD(void, B, methodA4); }
    void methodB1() override { PYBIND11_OVERLOAD(void, B, methodB1); }
};
class PyC : public C {
    void methodA1() override { PYBIND11_OVERLOAD(void, C, methodA1); }
    void methodA3() override { PYBIND11_OVERLOAD(void, C, methodA3); }
    void methodA4() override { PYBIND11_OVERLOAD(void, C, methodA4); }
    void methodB1() override { PYBIND11_OVERLOAD(void, C, methodB1); }
    void methodC1() override { PYBIND11_OVERLOAD(void, C, methodC1); }
};
```

The thing that bothers me here is the duplication of virtual methods in PyB and PyC; this is also a bit error prone as it isn't enough to just look for virtual methods in B and C, I also need to remember to look at their ancestors for any virtual methods (methods 2 and 3, above).

So my question is this: am I missing something here that pybind11 is handling that I'm not aware of?  Is there (or could there be) a nicer way to do this that doesn't require repeating all the virtual methods in each trampoline class for each derived class?

To the latter question, the first thought that occurred to me was that this could be accomplished via multiple inheritance (PyB inherits from both PyA and B), but that introduces diamond inheritance which would need `virtual` inheritance from A in both PyA (fine) and B (not so fine as it requires a C++ API change); I'm also not entirely sure that the method resolution order would be entirely correct.

Another potential solution is to template PyA, along the lines of:
```C++
template <class Base, typename = typename std::enable_if<std::is_base_of<A, Base>::value>::type>
class PyA : public Base {
public:
    virtual void methodA1() override { PYBIND11_OVERLOAD(void, A, methodA1); }
    virtual void methodA2() override { PYBIND11_OVERLOAD(void, A, methodA2); }
    virtual void methodA3() override { PYBIND11_OVERLOAD(void, A, methodA3); }
    virtual void methodA4() override { PYBIND11_OVERLOAD(void, A, methodA4); }
};
template <class Base, typename = typename std::enable_if<std::is_base_of<B, Base>::value>::type>
class PyB : public PyA<Base> {
public:
    virtual void methodA1() override { PYBIND11_OVERLOAD(void, B, methodA1); }
    virtual void methodB1() override { PYBIND11_OVERLOAD(void, B, methodB1); }
};
template <class Base, typename = typename std::enable_if<std::is_base_of<C, Base>::value>::type>
class PyC : public PyB<Base> {
public:
    virtual void methodC1() override { PYBIND11_OVERLOAD(void, C, methodC1); }
};
```
and then using `PyA<A>` for A's trampoline class and `PyB<B>` for B's trampoline class, and `PyC<C>` for C's.  I *think* this would get everything right (as long as all the trampoline methods are themselves virtual), while being both cleaner and far less likely to accidentally miss a base class virtual method.

Does this seem right to you, and if so, is it worth my writing it up as a documentation patch?

**Comment by wjakob** [comment]
Without multiple inheritance, you need to repeat all the trampolines. At its core, this is really a C++ issue. It might be possible to do something more efficient by messing with the virtual call tables, but it would be completely non-portable.

With multiple inheritance, I assume that you would want virtual inheritance so that the contents don't get replicated. Did you try this? It may just work already (even though pybind11 is not aware of multiple inheritance atm)

**Comment by jagerman** [comment]
I'm pretty sure the example I have above is a case that causes some problems with the multiple inheritance approach (even with virtual inheritance).  If PyB doesn't have a methodA2 override (which, naturally, it shouldn't, since B overrides methodA2 non-virtually), it won't compile (gcc gives: `error: no unique final overrider for ‘virtual void A::methodA2()’ in ‘PyB’`).  The only way to get around this is then to add a:
```C++
    virtual void methodA2() { B::methodA2(); }
```
into PyB for each non-virtually overridden virtual method, which is still pretty messy and easy to miss.

Any thoughts on the second, non-MI approach I described above?

**Comment by wjakob** [comment]
Aha, I see. The Curiously Recurring Template approach sounds reasonable to me as well, though it doesn't solve the fundamental problem about code duplication.

**Comment by jagerman** [comment]
Aha, I didn't realize there was an established name for that pattern.  Indeed the duplication is still there, but it's done by the compiler rather than by me, which seems like a beneficial tradeoff.

**Comment by wjakob** [comment]
Actually it's not the CRTP. It would be if your class declaration looked like this: ``class A : public Base<A>.``

**Comment by dean0x7d** [comment]
Slightly off-topic, but: There's actually no such thing as a non-virtual override. In your class `B`, both `methodA1` and `methodA2` are virtual overrides. 

Given:
```c++
struct A {
    virtual void foo();
}
struct B : A {
    // <insert code here>
}
```
there are 4 equivalent ways of writing the override:
```c++
virtual void foo(); // usual C++98 style
void foo(); // not the usual style, but equivalent to the previous line
            // --> the `virtual` keyword is not required in derived classes
virtual void foo() override; // C++11, functionally equivalent but compiler will 
                             // throw an error if the base function is not virtual
void foo() override; // recommended C++11 style, works just like the previous line
```
The only difference between the 4 lines is that `override` will help catch some mistakes at compile time. The last line is the recommended style by the [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final): "Virtual functions should specify exactly one of `virtual`, `override`, or `final`".

**Comment by jagerman** [comment]
Ah, thanks @dean0x7d, I didn't realize that.  I suppose the existence of a `final` method actually breaks *both* approaches (since you can't override to avoid the ambiguity with MI, and the PyA<B> override would be invalid).

**Comment by jagerman** [comment]
Draft of an addition to (or perhaps new section following) the "Overriding virtual functions in Python" documentation--I'll submit this as a PR if it sounds good.

---
When combining virtual methods with inheritance, you need to be sure to provide an override for each method for which you want to allow overrides from derived python classes.  For example, if you have the following class structure:
```C++
class A {
public:
    virtual int m1() { /* ... */ }
};
class B : public class A {
    virtual void m2(int arg) { /* ... */ }
};
```
then the trampoline class for `A` must override `m1()`, while the trampoline class for `B` must override `m2()` *and* the virtual `m1()` method inherited from `A`:
```C++
class PyA : public A {
public:
    int m1() override { PYBIND11_OVERLOAD(int, A, m1); }
};
class PyB : public B {
public:
    void m1() override { PYBIND11_OVERLOAD(int, B, m1); }
    void m2(int arg) override { PYBIND11_OVERLOAD(void, B, m2, arg); }
};
```

There are, however, some techniques you can use to avoid this duplication.  The first technique uses multiple inheritance, but requires changing the inheritance of `A` to be virtual for both `B` and `PyA`:
```C++
// class A: unchanged
class B : public virtual A { /* ... same as above */ };
class PyA : public virtual A { /* ... same as above */ };
class PyB : public PyA, public B {
    // no m1() override needed
    void m2(int arg) override { PYBIND11_OVERLOAD(void, B, m2, arg); }
};
```
Another approach that avoids requiring changing the underlying C++ inheritance to virtual is to use a templated trampoline class such as:
```C++
// class A unchanged
// class B unchanged
template <class Base = A> class PyA : public A {
    int m1() override { PYBIND11_OVERLOAD(int, A, m1, /* no args */); }
};
template <class Base = B> class PyB : public PyA<B> {
    void m2(int arg) override { PYBIND11_OVERLOAD(void, B, m2, arg); }
};
```
defining the classes with pybind11 using:
```C++
    py::class_<A, std::unique_ptr<A>, PyA<>> a(m, "A");
    py::class_<B, std::unique_ptr<B>, PyB<>> b(m, "B");
```

The multiple inheritance approach has the advantage of requiring less code to be generated by the compiler, while the latter approach has the advantage of not needing to change the inheritance of the wrapped class to virtual.

See example-virtual-functions.cpp for complete examples using both approaches.

**Comment by wjakob** [comment]
Sounds perfect to me.  Feel free to submit as a PR. So the multiple inheritance approach indeed works in practice?

**Comment by jagerman** [comment]
Yes, it does work.

It has one substantial messiness, though, for classes with non-default constructors: inheriting constructors doesn't work with virtual inheritance, so each derived class has to have a constructor that initializes all of its virtual base classes (and worse, this requires the same modifications to the C++ code).

**Comment by jagerman** [comment]
I think, given those complications, I'll move the templated approach first, then mention the multiple inheritance approach with the caveats for non-default-constructible classes.

**Comment by dean0x7d** [comment]
The template trampoline is a pretty elegant solution. Being non-intrusive is a big advantage.
BTW in the example above, I think `PyA` should inherit from `Base` and `PyB` from `PyA<Base>`.

**Comment by jagerman** [comment]
Shall I just drop the multiple-inheritance version completely then?  It *does* have the advantage of requiring substantially fewer methods for a deep inheritance tree, but needing virtual inheritance is a pretty big annoyance.

**Comment by jagerman** [comment]
And yes, it should indeed inherit from Base.

**Comment by dean0x7d** [comment]
I think the MI approach works against itself. It'll generate less code for deep hierarchies, but at the same time, the deeper the hierarchy is, the more intrusive it becomes with virtual inheritance and constructor rewriting for more classes. I'm not really sure it's worth the trade-off.

**Comment by jagerman** [comment]
I'll leave it in the example code, then, with some comments about the pitfalls, but take it out of the documentation.
