### ISSUE TITLE
[BUG]: segement fault for template function in multi files

### ISSUE THREAD

**Issue by libratiger** [pybind/pybind11#3208]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

I have three files.

exmple.h
```cpp
#include <pybind11/pybind11.h>


class Cat {
 public:
  Cat() { myname = "cat"; }
  void hello() {printf("hello cat\n");}
  void task_log() {printf("task_log cat\n");}
 private:
  std::string myname;
};

class Dog {
 public:
  Dog() { myname = "dog"; }
  void hello() {printf("hello dog\n");}
  void task_log() {printf("task_log dog\n");}
 private:
  std::string myname;
};


template <typename RunnerType>
class RunnerWrapper {
 public:
  RunnerWrapper() { ; };
  ~RunnerWrapper();
  void hello();
  void task_log();
 private:
  RunnerType *runner;
};



```

exmple.cc
```cpp
#include "example.h"


namespace py = pybind11;


template <typename RunnerType>
void RunnerWrapper<RunnerType>::hello() {
  this->runner->hello();
}


template <typename RunnerType>
void RunnerWrapper<RunnerType>::task_log() {
  this->runner->task_log();
}


template <typename T>
static void export_other1(const std::string &name, py::module_ &m) {
    py::class_<T>(m, "Cat").def(py::init<>())
        .def("hello", &T::hello);
}



template <typename F>
void export_other2(const std::string &name, py::module_ &m);


PYBIND11_MODULE(example, m) {
   export_other1<Cat>("Cat", m);
   export_other2<Dog>("Dog", m);
}

```

example2.cc
```cpp
#include "example.h"
#include <cstring>

namespace py = pybind11;


template <typename F>
void export_other2(const std::string &name, py::module_ &m) {
  py::class_<F>(m, "Dog")
    .def("hello", &F::task_log);
}

```

foo.py

```py
import example as ex
```

on Mac with clang-12.0.5 will report `Expected in: flat namespace`.
on Ubuntu with gcc-9.4.0 will report `11244 segmentation fault (core dumped)`

**Comment by libratiger** [comment]
I build with bazel

**Comment by libratiger** [comment]
I do not know whether the pybind11 does not support this? If I do not with the template, everything is OK.

**Comment by jiwaszki** [comment]
Hi @libratiger , I am not sure how to replicate your build process and dependencies especially with `example2.cc`.

First try adding body to a function in cpp file, even empty one `{ }`. That will resolve flat namespace problem.
```cpp
template <typename F>
void export_other2(const std::string &name, py::module_ &m) { };
```

Second thing - if you try to register a class you would also like to add `py::init` inside `export_other2`.

**Comment by libratiger** [comment]
> Hi @libratiger , I am not sure how to replicate your build process and dependencies especially with `example2.cc`.
> 
> First try adding body to a function in cpp file, even empty one `{ }`. That will resolve flat namespace problem.
> 
> ```c++
> template <typename F>
> void export_other2(const std::string &name, py::module_ &m) { };
> ```
> 
> Second thing - if you try to register a class you would also like to add `py::init` inside `export_other2`.

Add the `{}` can still lead to this, I will create a repo to put my code later.


Yes, there should be `py::init` in the `export_other2`, but since I do not call the `Dog` class, it is OK.

**Comment by libratiger** [comment]
@jiwaszki I just upload the code to repo: https://github.com/libratiger/pybind11examples. 
It is Ok on Mac, but still can lead to segment fault on Ubuntu

**Comment by laramiel** [comment]
This is not a pybind11 bug. This is an issue with your c++ code.

The definition (body) of  export_other2` needs to be visible at the instantiation point in example1.cc.

The other solutions mentioned above hide the actual issue by creating ODR rule violations--they create a new function with a different body and the same name--and don't actually solve it.

The typical solution is to put template functions into the .h file so they are visible where they are instantiated. It's also possible to indicate that the function is extern. Search for `function template instantiation`. 

In this case you might be able to do the following

in example.cc

```
extern template void export_other2<Dog>(const std::string &name, py::module_ &m);

```

in example2.cc

```
template void export_other2<Dog>(const std::string &name, py::module_ &m);
```
