### ISSUE TITLE
[BUG]: string_caster should not use temporary on Python >= 3.3

### ISSUE THREAD

**Issue by jbms** [pybind/pybind11#3252]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

Currently, `string_caster` always creates a temporary PyBytes object by calling `PyUnicode_AsEncodedString`.  However, in the common case of `UTF_N == 8`, on Python >= 3.3 we can instead use `PyUnicode_AsUTF8AndSize`, which manages and caches the UTF-8 encoding internally within the PyUnicode object.  If the UTF-8 representation is cached, then the encoding does not have to be done at all, avoiding an extra copy of the string.

This is particularly advantageous in the `IsView == true` case: users likely expect casting from PyUnicode to `std::string_view` to be low cost, but currently it always involves a copy of the string.  Additionally, it the `IsView == true` case has the additional cost of relying on `loader_life_support::add_patient`, which introduces additional cost and additional memory allocations (e.g. with the change in #3237, an allocation of the unordered_set bucket array on first use of loader_life_support, and an additional allocation of the node).

**Comment by Skylion007** [comment]
@jbms PR on this front is welcome, would you mind submitting one?

**Comment by jbms** [comment]
@Skylion007 Done.
