### ISSUE TITLE
[BUG]: tests fail on Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by brianm-sra** [pybind/pybind11#3258]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

Build failed as follows

```
[100%] Built target pybind11_tests
Scanning dependencies of target pytest
/usr/bin/python3.6: No module named pytest
tests/CMakeFiles/pytest.dir/build.make:59: recipe for target 'tests/CMakeFiles/pytest' failed
make[3]: *** [tests/CMakeFiles/pytest] Error 1
CMakeFiles/Makefile2:242: recipe for target 'tests/CMakeFiles/pytest.dir/all' failed
make[2]: *** [tests/CMakeFiles/pytest.dir/all] Error 2
CMakeFiles/Makefile2:316: recipe for target 'tests/CMakeFiles/check.dir/rule' failed
make[1]: *** [tests/CMakeFiles/check.dir/rule] Error 2
Makefile:242: recipe for target 'check' failed
make: *** [check] Error 2

```

### Reproducible example code

```text
$ git clone https://github.com/pybind/pybind11.git
$ cd pybind11
$ mkdir build
$ cd build
$ cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ cmake ..
$ make check -j 4
```

**Comment by jiwaszki** [comment]
Are you sure that you installed `pytest` in your python3.6?
>Scanning dependencies of target pytest
/usr/bin/python3.6: No module named pytest

**Comment by henryiii** [comment]
Please install pytest.
