### ISSUE TITLE
class member variables returned by value

### ISSUE THREAD

**Issue by foxtog** [pybind/pybind11#326]
If there is a following class
```
class A {
 public:
    std::shared_ptr<B> b;
    std::string str;
};
```
and I'm exporting its member variables via `def_readonly`.
I retrieve the objects in python    
```
 import ext
 a = ext.A()
 b1 = a.b
 b2 = a.b
 s1 = a.str
 s2 = a.str
```
Then, `id(b1) == id(b2)` which is expected as `reference_internal` policy is used for `def_readonly`. 
However, `id(s1) != id(s2)` even though it has also been declared via `def_readonly`. 
Is it because `std::string` is almost a POD type and thus, getter returns a copy ?

**Comment by wjakob** [comment]
Pybind11 internal type converters that convert between native C++ and native Python types *always* create copies of types, with one exception: custom classes (like "B"), in which case it depends on the return value policy. If you only want one string to exist, you'll have to use a native Python type in C++, such as ``py::object`` or ``py::str``
