### ISSUE TITLE
[BUG]: error: invalid conversion from ‘void (*)(int, ...)’ to ‘void (*)(int)’ [-fpermissive]

### ISSUE THREAD

**Issue by flyinskyin2013** [pybind/pybind11#3268]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

1. I have a func:
`void test(int a, ...){}`

2. I try bind the func to the module:
`m.def("test", static_cast<void (*)(int, ...)>(&test), "No notes");`

3. I compile it and get follow error(The sign of 'test' is invalid.):
`error: invalid conversion from ‘void (*)(int, ...)’ to ‘void (*)(int)’ [-fpermissive]`

4. In c++&c, we can convert func-pointer 'test' to type 'void (*)(int, ...)'.I can't bind this kind of func using pybind11.

### Reproducible example code

```text
No
```

**Comment by henryiii** [comment]
I don't even know what this would compile into. Variadic functions are a C feature, and as far as I know, do not play nicely with C++ features, like `std::function` (at least, I couldn't figure out how to do it). *Maybe* you could write a little C++ wrapper, and then use that? You'll take `py::args`, then process it and build, well, I'm not sure how you programmatically call a variadic function in C. You should look at the C docs.

**Comment by flyinskyin2013** [comment]
Yes! you are right. the `std::function` can't support it.

It's a correct solution to wrapper it using `py::args`.

Thanks.
