### ISSUE TITLE
Binding shared_ptr fails

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [pybind/pybind11#331]
I am trying to expose a protobuf instance to Python:

    auto m = py::module("protobuf_utils", "Utils for handling protobuf");

    py::class_< google::protobuf::io::IstreamInputStream, std::shared_ptr<google::protobuf::io::IstreamInputStream> >( m, "IstreamInputStream" )
    ;

    m
        .def("make_stdin_stream", []() {
            return std::make_shared<google::protobuf::io::IstreamInputStream>(&std::cin, 1);
        })
    ;

When I run this I get:

        input = make_stdin_stream()
    TypeError: Unable to convert function return value to a Python type! The signature was
	() -> std::shared_ptr<google::protobuf::io::IstreamInputStream>

I currently have no idea what is going wrong. Isn't the holder working!?

**Comment by wjakob** [comment]
Did you declare shared_ptr as a supported smart pointer to pybind11? See the advanced docs.

**Comment by abergmeier-dsfishlabs** [comment]
Ah, thanks @wjakob. Was under the impression that for `std::shared_ptr` it would not be explicitly necessary.
