### ISSUE TITLE
example-virtual-functions fails to compile, MSVC 2015

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#332]
- Visual Studio 14 2015, MSVC 19.0.23918.0
- Python 3.5.2 x64 via conda
- Latest pybind11 master
- This seems to be the only error, aside from a few xatomic warnings

```
include\pybind11\cast.h(859): error C2280: 
    'NonCopyable::NonCopyable(const NonCopyable &)': 
    attempting to reference a deleted function 
    (compiling source file example\example-virtual-functions.cpp)
example\example-virtual-functions.cpp(74): note: 
    see declaration of 'NonCopyable::NonCopyable' 
    (compiling source file example\example-virtual-functions.cpp)
include\pybind11\cast.h(916): note: 
    see reference to function template instantiation 
    'T pybind11::cast<T>(const pybind11::handle &)' being compiled
          with
          [
              T=NonCopyable
          ] 
    (compiling source file example\example-virtual-functions.cpp)
include\pybind11\cast.h(920): note: 
    see reference to function template instantiation 
    'NonCopyable pybind11::cast<T>(pybind11::object &&)' being compiled
          with
          [
              T=NonCopyable
          ] 
    (compiling source file example\example-virtual-functions.cpp)
example\example-virtual-functions.cpp(110): note: 
    see reference to function template instantiation 
    'T pybind11::object::cast<NonCopyable>(void) &&' being compiled
          with
          [
              T=NonCopyable
          ]
```

**Comment by wjakob** [comment]
Interesting. Is possible that this is a compiler bug that was fixed in a service pack, which is applied on the CI build bots but not your machine?

**Comment by aldanor** [comment]
Indeed. I've installed the latest toolchain update and it compiled.

From the [release notes of VS2015 Update 3](https://www.visualstudio.com/en-us/news/releasenotes/vs2015-update3-vs):

> We now check the access of a deleted trivial copy/move ctor. Without the check, we may incorrectly call the defaulted copy ctor (in which the implementation can be ill-formed) and cause potential runtime bad code generation.

Maybe we should mention that we recommend VS2015 Update 3 on Windows so as to avoid cryptic problems like this.
