### ISSUE TITLE
Error while calling overloaded functions

### ISSUE THREAD

**Issue by k6project** [pybind/pybind11#342]
Hi,

In C++ i have following methods declared in a class:
```
class Binding {
...
IntrusivePtr<BoundResource> getBoundResource();
const IntrusivePtr<BoundResource>& getBoundResource() const;
...
}
```

In python bindings i declare:

```
py::class_<BoundResource,  IntrusivePtr<BoundResource> >(m, "BoundResource", py::base<Resource>());

...  
py::class_<Binding>(m, "Binding").def_property_readonly("bound_resource", 
    static_cast<IntrusivePtr<BoundResource> (Binding::*)()>(&Binding::getBoundResource)
);
...
```

Whenever i try to access "bound_resource" property from python i get:

Unable to convert function return value to a Python type! The signature was
(pbtest bindings.Binding) -> IntrusivePtr<BoundResource>

What might be the issue here? IntrusivePtr works as holder type for other similar cases in my code and produces no errors (the only difference is that there i don't have overloaded getters). The pointer inside IntrusivePtr in this case is not null (checked by accessing specific fields of it via lambda wrappers)

**Comment by wjakob** [comment]
Please provide minimal, reproducible and self-contained example code as per the instructions. (https://github.com/pybind/pybind11/blob/master/CONTRIBUTING.md)
