### ISSUE TITLE
[BUG]: segfault in pybind11:dict constructor

### ISSUE THREAD

**Issue by modkin** [pybind/pybind11#3442]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

We are getting a SEGFAULT when creating a simple dict.

The code is attached bellow. It might be the case that we are just missing something but the fact that this leads to a SEGFAULT makes it pretty hard to debug.

tested with pybind11 2.6 and 2.8 in combination with python 3.8 and 3.9

Thanks in advance

### Reproducible example code

```text
Start with https://github.com/pybind/cmake_example

add src/minimal.cpp:
#include <pybind11/pybind11.h>
using namespace pybind11::literals;

int main(){
   pybind11::dict d("spam"_a=pybind11::none(), "eggs"_a=42);
}

add in CMakeLists.txt:
add_executable(minimal src/minimal.cpp src/minimal.cpp)
target_link_libraries(minimal pybind11::embed)
```

**Comment by skoslowski** [comment]
You need to initialize the interpreter first. See py::scoped_interpreter

**Comment by modkin** [comment]
Thanks for the quick response. Strangely we had cases where it was not necessary to initialize the interpreter. But it works now for sure. Thanks again!
