### ISSUE TITLE
Simpler PYBIND11_PLUGIN

### ISSUE THREAD

**Issue by anntzer** [pybind/pybind11#347]
It should be easy to avoid some boilerplate code by providing a variant of PYBIND11_PLUGIN that would allow something like
```
PYBIND11_PLUGIN2(name, m, [doc]) {
    m.def(...);
}
```
with `m` being directly created with the correct name and `m.ptr()` implicitly returned at the end.

I don't know whether it would also be possible to infer `name` from `__FILE__` with some constexpr tricks as well...

**Comment by wjakob** [comment]
This would add more magic macro stuff, which we generally try to minimize, and the gains are very small (a few lines).
