### ISSUE TITLE
[BUG]: missing version type in release

### ISSUE THREAD

**Issue by sergiud** [pybind/pybind11#3471]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

When consuming pybind11 by means of `find_package`, the following message is generated by CMake:
```console
-- Found pybind11: /home/sergiu/proj/devel/pybind11/install/include (found version "2.8.1" )
                                                                                          ^
```
Note the spurious space before the closing parenthesis. It seems that this is where the version type is supposed to appear:
https://github.com/pybind/pybind11/blob/270b11d50229e67e2d8d63e96464f9bcd12b527c/tools/pybind11Config.cmake.in#L231
For some reason, however, the corresponding CMake variable is empty.

**Comment by Skylion007** [comment]
@henryiii This looks like something wrong with our release version flow using Nox. Also pinging @rwgk since he ran the release script this time.

**Comment by henryiii** [comment]
I could be wrong, but I thought this was supposed to be empty for release versions. The spacing is a problem, but I'm pretty sure it's supposed to be empty for releases.

**Comment by sergiud** [comment]
Thanks for looking into this issue. I observe the same behavior both when I install pybind11 using plain CMake but also in the version packaged for Arch Linux [using `setup.py`](https://github.com/archlinux/svntogit-community/blob/b9262f816baf25a11c34f4a72a42dd4992ebc51f/trunk/PKGBUILD#L42).

**Comment by henryiii** [comment]
I think it's because it's the correct behavior. We just haven't bothered to remove the extra space (though we probably should).

**Comment by sergiud** [comment]
I see. The simplest fix would be to report the version type as part of the version string, e.g., as `2.8.1dev1`. This would be consistent with how versions are generally reported by CMake in terms of `find_package_handle_standard_args` and maybe even use the latter instead (e.g., in `CONFIG` mode).

**Comment by henryiii** [comment]
That is what is done (though it is pulled from the version string, rather than the other way around). But for 2.8.1, there is no version type, since it's a final release. If you use master, it should be reported as dev1, which as far as I can tell, it is.

**Comment by henryiii** [comment]
Oh, I see what you mean, about the fix for the space. Okay, though I think the "." is not included, so you'd still have to add that.

**Comment by sergiud** [comment]
As far as I can see, the version is still reported as `"2.9.0" dev1`. I, however, propose changing it to `"2.9.0dev1"`. Does this make sense?

**Comment by henryiii** [comment]
Sorry, I'm only half here, it seems. :) Yes, that sounds reasonable and should be easy.

**Comment by henryiii** [comment]
Would you like to make the change?

**Comment by sergiud** [comment]
Sure.
