### ISSUE TITLE
VS2022 _invalid_parameter

### ISSUE THREAD

**Issue by gearslogy** [pybind/pybind11#3477]
### Problem description

Not a pybind bug, it should be vs2022 bug 

![image](https://user-images.githubusercontent.com/14259542/142109750-e42400d8-0387-42b5-8510-69cee784faa0.png)

solution:

https://www.reddit.com/r/cpp_questions/comments/qpo93t/error_c2039_invalid_parameter_is_not_a_member_of/

in the pybind11.h , Insert this code after line 22 ,  it can fix the problem
```c
#elif defined(_MSC_VER)
#include <corecrt.h>
```

**Comment by henryiii** [comment]
We can turn on 2022 testing, GHA now has 2022 images.

**Comment by henryiii** [comment]
I think this is a bug in MSVC 2022. You shouldn't have to include a file (like corecrt.h) before accessing stdlib files like `atomic` and `memory`.

**Comment by Boris-Rasin** [comment]
I think this is pybind11 bug, not MSVC 2022 bug.

Problem arises because pybind11 redefines _DEBUG variable in the middle of the build.

**Comment by henryiii** [comment]
If we don't do that, then you have to link to the (often non-existent) debug lib of Python, which is usually not what you want.

**Comment by henryiii** [comment]
We undefine it just for python.h, then redefine it. It shouldn't affect anything in C++, just C via Python.

**Comment by Boris-Rasin** [comment]
These headers (<python.h> and others) include standard C/C++ headers, which leads to this bug. I believe if we include relevant standard C/C++ headers before redefining _DEBUG, it will fix the problem. These standard C/C++ headers will first be processed with correct _DEBUG definition, and will not be processed second time from <python.h> etc. because they all have include guards.

**Comment by henryiii** [comment]
Sorry, I thought I responded here. CPython headers _must_ be included before any system headers get included. This is a requirement from CPython, and it's why we require pybind11 to be the first include too. However, this _might_ not be a requirement for MSVC; I know it breaks things on linux if not first, but not sure that's an issue if you are using GCC.

**Comment by henryiii** [comment]
(See https://docs.python.org/3/c-api/intro.html#include-files - this just says:

> you _must_ include Python.h before any standard headers are included

(no mention of type of system)

**Comment by rwgk** [comment]
> Sorry, I thought I responded here.
I got a bit confused, too.
@gearslogy, I think it would be better to close this with comment: this is being worked on under PR #3477, please continue the discussion there.
