### ISSUE TITLE
Simpler setuptools integration

### ISSUE THREAD

**Issue by anntzer** [pybind/pybind11#348]
`pybind11` could provide a subclass of `setuptools.Extension` with the defaults provided by https://github.com/pybind/python_example/blob/master/setup.py, i.e. that would automatically set `language` to `c++` and append the relevant `include_dirs`.

Extra points if it also allows lets one infer the module name from the path of the first source, similarly to Cython (http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#multiple-cython-files-in-a-package).

The idea would be to let one put the .cpp file in the same folder as where one expects the .so in the python package hierarchy, and write a `setup.py` as simple as
```
from pybind11 import Extension

setup(
    ...,
    ext_modules=[Extension("*", ["path/to/extmodule.cpp"])])
```
(I don't think it is necessary to subclass `build_ext`; instead the new Extension ctor could just extend the `extra_compile_args` as needed.)

**Comment by wjakob** [comment]
A feature request is not so helpful due to a severe lack of resources -- feel free to create a PR if you plan to implement this yourself.
