### ISSUE TITLE
[BUG]: conflict with cmd on windows

### ISSUE THREAD

**Issue by xkungfu** [pybind/pybind11#3489]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

If any other script open a cmd window,  the program would be crashed!

for examples:
1 open cmd console by "AllocConsole()"
or:
2 redis client execute any command.

### Reproducible example code

examples code:
1\ AllocConsole:

```
inline void Console()
{
    AllocConsole();
    FILE *pFileCon = NULL;
    pFileCon = freopen("CONOUT$", "w", stdout);

    COORD coordInfo;
    coordInfo.X = 130;
    coordInfo.Y = 9000;

    SetConsoleScreenBufferSize(GetStdHandle(STD_OUTPUT_HANDLE), coordInfo);
    SetConsoleMode(GetStdHandle(STD_OUTPUT_HANDLE),ENABLE_QUICK_EDIT_MODE| ENABLE_EXTENDED_FLAGS);
}

Console();
```

or
2\ redis client: I use redis-plus-plus

```
Redis m_redis = new Redis("tcp://127.0.0.1:6379");
m_redis->flushdb();
```

**Comment by jagerman** [comment]
Is this filed on the wrong project?  I am not seeing any connection here to pybind11.

**Comment by xkungfu** [comment]
@jagerman 
I think you said I didn't post a whole example...
and I think you haven't use any cmd command in your projects. If you did, you would find the issue.
the problem is : 
It seems that the pybind11 caused the program to be crashed when other script open and execute cmd command.

I will try to create a demo later.

If anyone has the same issue, please tell me how to resovle it?

thank you.

**Comment by xkungfu** [comment]
sorry, can't reproduce this issue now.
maybe the error caused by checking win32.
closed.
