### ISSUE TITLE
cpp_function::initialize_generic function memory leaks!

### ISSUE THREAD

**Issue by Ponus** [pybind/pybind11#349]
Deall all. I found a memory leaks issue today.
Here is my code:
```
struct Viewport {
...
};

py::class_<Viewport>(lMainModule, "Viewport")
        .def(py::init());
```
When I looked into this issue, I found out that
`func->m_ml->ml_doc = strdup(signatures.c_str());` **(file: pybind11.h, line: 324**)
the memory never deallocated.

Could you verify it?

Best Regards,
Bo

**Comment by wjakob** [comment]
This is eventually freed in ``cpp_function::destruct``, which of course only happens when the function is garbage collected. You'll need to provide a complete, self-contained and minimal (no external dependencies) example here, otherwise your issue cannot be reproduced.

I'll close this ticket for now, but it can be reopened if you provide further details.

**Comment by Ponus** [comment]
Hi @wjakob , thanks for your response.
Here is a complete that you can reproduce:
```
#include <iostream>
#include <pybind11/pybind11.h>
#include <pybind11/eval.h>
#include <pybind11/stl.h>

#ifdef _WIN32
#define _CRTDBG_MAP_ALLOC
#include <crtdbg.h>
#endif          // End of _WIN32

struct Viewport
{
    int x;
    int y;
    int width;
    int height;
};

void parseRenderer(void)
{
    namespace py = pybind11;
    using namespace std;

    auto mainModule = py::module::import("__main__");
    py::object mainNamespace = mainModule.attr("__dict__");

    mainNamespace["Viewport"] = py::class_<Viewport>(mainModule, "Viewport")
        .def(py::init())
        .def_readwrite("x", &Viewport::x)
        .def_readwrite("y", &Viewport::y)
        .def_readwrite("width", &Viewport::width)
        .def_readwrite("height", &Viewport::height);

    std::string script = R"(def generator():
    vp = Viewport()
    yield vp
)";

    py::eval<py::eval_statements>(script, mainNamespace);
    py::object lGenFunc = mainNamespace["generator"];
    auto lGenerator = lGenFunc();

    for (auto& viewports : lGenerator)
    {
        auto viewport = viewports.cast<Viewport>();
        std::cout << "width: " << viewport.width << "\theight: " << viewport.height << std::endl;
    }
}

int main(int /*argc*/, char* /*argv*/[])
{
#ifdef _WIN32
    _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
#endif          // End of _WIN32

    Py_Initialize();

   parseRenderer();

    return 0;
}
```

I am using Visual Studio 2015. I turned the CRT memory reports on, so that I am pretty sure there some memory leaks.

**Comment by wjakob** [comment]
Embedding python via ``Py_Initialize`` is not supported here. It's highly likely that you are just missing some extra cleanup steps to bring down the interpreter at the end.

**Comment by Ponus** [comment]
Then how should I embed python so that python scripts can manipulate C++ structures? I didn't find any documents in the readthedocs site.

**Comment by wjakob** [comment]
Embedding itself is just not a supported feature at the moment. You're certainly welcome to submit a PR which turns this into an official feature, which would entail writing C++ abstractions for Python API and debugging everything, including reference counting (nobody else is working on any of these things).

**Comment by Ponus** [comment]
Copy that.

Thank you for the info.

**Comment by Ponus** [comment]
I am thinking about supporting the feature. I will let you know when I get some progress.

Best Regards,
Bo
