### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by EMUNES** [pybind/pybind11#3529]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

Hi, guys. I'm new to pybind11 and I run into problems in the first place. When I install pybind11 using conda-forge on Linux (Zorin OS, based on Ubuntu), I install the dependencies, run the build tests procedure according to First Steps on the documentation page. And the following error message occurred:

![image](https://user-images.githubusercontent.com/53288091/144873737-da368cb6-7c78-41d9-9dce-7de3180ae8ff.png)

![image](https://user-images.githubusercontent.com/53288091/144873785-617df2b0-ab15-4e88-9fac-4449864235f3.png)

I searched similar issues but I find no solution for this problem. And some issues are not quite like the problem I encountered. Any fixes for this? Thanks in advance.

Environment:
anaconda - python 3.10
cmake 3.16.3
python-dev python3-dev pytest  installed
Zorin OS 16

**Comment by henryiii** [comment]
You are using the last released version of pybind11 (2.8.1, I expect) with the master version of the tests. You should either checkout the matching version of the tests, or just not run our tests at all against a separately installed pybind11 instance. The first steps is assuming you _don't_ have it installed beforehand.

**Comment by EMUNES** [comment]
> You are using the last released version of pybind11 (2.8.1, I expect) with the master version of the tests. You should either checkout the matching version of the tests, or just not run our tests at all against a separately installed pybind11 instance. The first steps is assuming you _don't_ have it installed beforehand.

Thanks for your reply, I believe it helps.
