### ISSUE TITLE
[BUG]: Python compilation fails with cmake < 3.15

### ISSUE THREAD

**Issue by aws-taylor** [pybind/pybind11#3538]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

[CMakeLists.txt](https://github.com/pybind/pybind11/blob/master/CMakeLists.txt#L8) reports that the minimum required version as 3.4. The code has various workarounds for bugs up to 3.14, however in the [setup.py](https://github.com/pybind/pybind11/blob/master/setup.py#L151), the `--install` syntax is used when calling cmake. This feature was added in [3.15](https://cmake.org/cmake/help/latest/release/3.15.html).  As such, when running `python setup.py build` with cmake<3.15, compilation fails with `SystemExit: error: package directory 'pybind11/include/pybind11' does not exist` because the installation from cmake never happens.

The fix may be as simple as setting `cmake_minimum_required(VERSION 3.15)`

**Comment by henryiii** [comment]
This _only_ requires a recent version of CMake to build the SDist, which most users should not be doing anyway, and if they do, they will get CMake 3.18+ https://github.com/pybind/pybind11/blob/7516811315c76321e847cf28955937195c577d2f/pyproject.toml#L2

Note, though, you must use `pip` or `build`; `python setup.py sdist` or any other `setup.py` command is [very deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), and some of them have started showing depreciation warnings finally.

If you are using an SDist, wheel, submodule, etc. then 3.4+ works fine (and is tested).
