### ISSUE TITLE
Typed iterators/iterables

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#360]
I was thinking, it would be nice to have typed iterators and iterables (kind of like you can have typed numpy arrays), so you can do things like accept arguments of type `iterable_t<MyObject>` which will provide you with appropriate `.begin()` and `.end()`.

In the example below, this works:

``` python
>>> generate(5)
[Foo(0, 0), Foo(1, 10), Foo(2, 20), Foo(3, 30), Foo(4, 40)]
>>> dump(generate(5))
[ Foo(0, 0) Foo(1, 10) Foo(2, 20) Foo(3, 30) Foo(4, 40) ]
>>> dump(f for f in generate(5) if f.x % 2 == 0)  # pass a lazy iterable
[ Foo(0, 0) Foo(2, 20) Foo(4, 40) ]
```

If this looks good, I could open a PR.

A related improvement would be to relax input object requirements if an input argument of a method is `std::vector<T>`. It should really be a "sized iterable" (aka [Sequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence)) instead of a list which is unnecesarily restrictive.

Here's the C++ code for the example:

``` cpp
#include <iostream>
#include <string>
#include <vector>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

template<typename T> class iterator_t : public py::iterator {
public:
    using iterator::iterator;

    // cheap/lazy way of doing this as it could be done in advance(), 
    // but then py::iterator needs to be changed
    auto operator*() const {
        return this->iterator::operator*().cast<T>();
    }
};

template<typename T> class iterable_t : public py::iterable {
public:
    using iterable::iterable;

    iterator_t<T> begin() { return {PyObject_GetIter(ptr()), false}; }
    iterator_t<T> end() { return {nullptr, false}; }
};

struct Foo {
    int x;
    int y;

    Foo(int x, int y) : x{x}, y{y} {}

    std::string to_string() const {
        return std::string("Foo(") + std::to_string(x) + ", " +
            std::to_string(y) + ")";
    }
};

PYBIND11_PLUGIN(test_iter) {
    py::module m("test_iter");

    py::class_<Foo>(m, "Foo")
        .def(py::init<int, int>())
        .def_property_readonly("x", [](const Foo& v) { return v.x; })
        .def_property_readonly("y", [](const Foo& v) { return v.y; })
        .def("__str__", [](const Foo& v) { return v.to_string(); })
        .def("__repr__", [](const Foo& v) { return v.to_string(); });

    m.def("generate", [](int n) {  // this could actually return an iterator as well
        std::vector<Foo> data;
        for (int i = 0; i < n; i++)
            data.emplace_back(i, i * 10);
        return data;
    });

    m.def("dump", [](iterable_t<Foo> x) {
        std::cout << "[";
        for (auto v : x)
            std::cout << " " << v.to_string();
        std::cout << " ]" << std::endl;
    });

    return m.ptr();
}
```

**Comment by wjakob** [comment]
This addition looks good to me -- I don't think it's nice as-is without changing ``py::iterator``.

**Comment by wjakob** [comment]
Sorry, typo above. I meant to say: I **do** think it's nice as-is without changing ``py::iterator``.

**Comment by aldanor** [comment]
Ok thanks, I was a bit confused there :)

**Comment by wjakob** [comment]
Feel free to turn this into a PR. It would be nice to mention it in the documentation as well.

**Comment by aldanor** [comment]
Yep, will do, I have a local branch hanging somewhere that needs docs/tests etc, just a bit swamped with everything else right now :hammer:

**Comment by wjakob** [comment]
ok, no problem -- take your time.

**Comment by wjakob** [comment]
I'll close this ticket since there is a related PR now (which seems on hold at least for the time bing).
