### ISSUE TITLE
Cannot assign a Python function to a C++ class member of type std::function

### ISSUE THREAD

**Issue by a-tinsmith** [pybind/pybind11#366]
Using release v1.8.1.
I'm trying to assign a Python function to a C++ class member of type `std::function`. Here is the code:

```C++
class Test
{
public:
    void Foo(int param)
    {
        if (callback)
            callback(param);
    }

    std::function<void(int)> callback;
};

// pybind11 binding:
namespace py = pybind11;
using namespace pybind11::literals;

PYBIND11_PLUGIN(PyProject1) {
    py::module m("PyProject1", "PyProject1 example plugin");

    py::class_<Test>(m, "Test")
        .def(py::init<>())
        .def("Foo", &Test::Foo, "param"_a)
        .def_readwrite("callback", &Test::callback)
    ;

    return m.ptr();
}
```

Python test code:
```python
import PyProject1 as pp

t = pp.Test()

def py_callback(a):
    print('param: {0}'.format(a))

t.callback = py_callback   # <--- exception here!
t.Foo(param=42)
```
The code compiles fine. At run time when I'm trying to assign a Python function to the `Test::callback` member I'm getting this exception:
```
Incompatible function arguments. The following argument types are supported:

    1. (PyProject1.Test, std::function<void __cdecl(int)>) -> NoneType

    Invoked with: <PyProject1.Test object at 0x00000150A3EA4CE0>, <function py_callback at 0x00000150A3E48950>
```

How can I assign a Python callback function to a C++ class member of type `std::function`?

**Comment by jagerman** [comment]
You can't directly assign a python callable to a std::function, but you can work around it pretty easily in a couple of ways.

If you don't strictly need an std::function, you can simply change `callback` to a `pybind11::object`—which is callable with the same `()` operator as the std::function.

If you really need an std::function (i.e. because you need to interface with external code that uses one), you could use `def_property` with a py::object variable capture like this:

```C++
.def_property("callback",
        [](Test &t) { return t.callback; },
        [](Test &t, py::object callable) { t.callback = [callable](int param) { callable(param); }; })
```

**Comment by a-tinsmith** [comment]
Thanks for the answer.
Yes, the `Test` class comes for a different library, which I cannot change. The trick with using property works perfectly. Though the call stack looks a bit scary. :)

I was looking at the example5.cpp file where callbacks are demonstrated. There is this function: `void test_callback3(const std::function<int(int)> &func)`, which is used from Python with lambda: `test_callback3(lambda i: i + 1)`. So I was under impression that Python callables are converted to `std::function` types automagically.

**Comment by wjakob** [comment]
> You can't directly assign a python callable to a std::function, but you can work around it pretty easily in a couple of ways.

The ``functional.h`` extension header implements a type converter for exactly this, no?

**Comment by a-tinsmith** [comment]
Good point! After including `<pybind11/functional.h>` the original code works flawlessly without any additional lambdas. I overlooked the fact that `<pybind11/functional.h>` is not included by default and required to make this work.

**Comment by aldanor** [comment]
Yea, it's the same story with stl.h., it wasn't clear to me initially that a few things are opt-in so I surprised a few things didn't work out of the box.

Skimming through the docs right now, at the first glance I can't seem to find where it says that some headers are optional. There're mentions of each specific header, but those are scattered through the docs. Maybe it would make sense to highlight it somewhere at the beginning of the documentation, loud and clear; maybe the README as well (e.g. "note that some functionality is opt-in and is contained in these headers: ..")?

By the way, is there a good reason functional.h/stl.h and all other headers except for numpy.h/eigen.h shouldn't be just included by default (other that compilation time which is negligible)?

**Comment by wjakob** [comment]
@aldanor: There is a summary at the bottom of ``basics.rst``. The reason for this separation is just to not pull in so many header files at the same time (``stl.h`` pulls in a ton of extra stuff -- e.g. all the Red/Black tree crazyness in ``set`` and ``map``), and so that I could write that the core header files (excluding comments) are < 2500 LOC ;) (though I am not so sure if it's still true at this point).
