### ISSUE TITLE
[BUG]: Distutils is going to be deprecated with Python3.12

### ISSUE THREAD

**Issue by Azrael3000** [pybind/pybind11#3677]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

In Python 3.12 distutils is going to be removed and with 3.10 it's marked as deprecated. Currently `tools/FindPythonLibsNew.cmake` is still using

["${PYTHON_EXECUTABLE}" "-c" "from distutils import sysconfig as s;import sys;import struct;](https://github.com/pybind/pybind11/blob/ce18721d830a9deb8cf1883b513bcb8f98090c35/tools/FindPythonLibsNew.cmake#L115)

It might be replaceable by a simple `import sysconfig as s;`

See [[0]](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated) and [[1]](https://docs.python.org/3/library/distutils.html)

Kind regards,
Arno

**Comment by henryiii** [comment]
You can also just use the modern FindPython support, as CMake's FindPythonLibs/FindPythonInterp is also deprecated. ;)

I think the same sort of thing as done in #3663 would be needed here.

**Comment by henryiii** [comment]
```
AttributeError: module 'sysconfig' has no attribute 'get_python_inc'
```

**Comment by henryiii** [comment]
This looks useful: https://github.com/pytorch/pytorch/commit/4b96fc060b0cb810965b5c8c08bc862a69965667
