### ISSUE TITLE
Invalid Argument Counts and Types Cause Crash

### ISSUE THREAD

**Issue by tonybarbieri** [pybind/pybind11#375]
Hello,

I am embedding python into an existing C++ project and I'm running into an issue where passing incorrect argument counts and/or types to wrapped functions causes the interpreter to crash. When calling Py_Finalize I see output that says the crash occured in python's threading.pyc module. An example error:

`0x0000021c81849d00 L"'Incompatible function arguments. The following argument types are supported:\\n    1. (arg0: std::function<void __cdecl(void)>, arg1: float) -> None\\n    Invoked with: <function <lambda> at 0x0000021B...`

Is there a way I can handle these types of errors and avoid the interpreter crashing and becoming unresponsive?

Thank you in advance for any help.

**Comment by wjakob** [comment]
Embedding the interpreter is not a supported feature ATM. If you can get pybind11 to crash in this way while acting as a regular extension module, then please file a complete, self-contained example that triggers this behavior.
