### ISSUE TITLE
ld error for posix under mac

### ISSUE THREAD

**Issue by zaviichen** [pybind/pybind11#382]
Hi, i am trying to use mac 10.10.5 with llvm to compile the demo pybind11 program. But there is a ld error: ld: symbol(s) not found for architecture x86_64. Seems posix lib under mac doesn't support libc++. Can you give some suggestions please? Thanks!

Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -dylib -arch x86_64 -dylib_install_name @rpath/libpybind.dylib -macosx_version_min 10.10.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -o libpybind.dylib -headerpad_max_install_names CMakeFiles/pybind.dir/main.cpp.o -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_PyCFunction_GetSelf", referenced from:
      pybind11::cpp_function::initialize_generic(pybind11::detail::function_record*, char const*, std::type_info const* const*, unsigned long) in main.cpp.o
  "_PyCFunction_NewEx", referenced from:

**Comment by zaviichen** [comment]
python lib is not in the searching path. i need to manually add python lib for the linker.

**Comment by aldanor** [comment]
Try building with `-undefined dynamic_lookup`?

**Comment by wjakob** [comment]
The issue is unrelated to libc++ and just means that you didn't link to Python.

**Comment by jakobjw** [comment]
Maybe it could be helpful for new users to put the info to build with `-undefined dynamic_lookup` into the FAQ?

I just spent a few minutes wondering and experiencing unexpected/unwanted surprises regarding the Python library locations on macOS (with homebrew)... ^^

**Comment by YannickJadoul** [comment]
@jakobjw, the example (I guess you're referring to the [Creating bindings for a simple function](https://pybind11.readthedocs.io/en/stable/basics.html#creating-bindings-for-a-simple-function) section?) says "_On Linux_, the above example can be compiled using the following command:"

Also, manually compiling is really not a great plan with pybind11. There's a whole page about building in the docs with much better solutions: https://pybind11.readthedocs.io/en/stable/compiling.html

Also also, `-undefined dynamic_lookup` is mentioned on the https://pybind11.readthedocs.io/en/stable/compiling.html#building-manually, and that section is linked to from the note in [Creating bindings for a simple function](https://pybind11.readthedocs.io/en/stable/basics.html#creating-bindings-for-a-simple-function).

**Comment by jakobjw** [comment]
@YannickJadoul, ok, thanks for the explanation!
