### ISSUE TITLE
Linking additional libraries in CMake pybind11_add_module()

### ISSUE THREAD

**Issue by lathen** [pybind/pybind11#387]
I'm not very experienced with CMake so I'm sure there's a simple solution to this. I'm adding an issue since it could be useful to add the reply to the docs.

I have additional libraries that I need to link to the target Python module, basically adding elements to the `target_link_libraries` command in `pybind11_add_module()`. I understand that one solution would be to setup everything manually, i.e. replicating the stuff in `pybind11_add_module()` in my project's CMakeLists. But I would rather use the `pybind11_add_module()` function since this makes everything really clean. Is there a way to tell CMake to add additional link libraries or does `pybind11_add_module()` need to be extended with additional arguments?

Ping also the contributor in #207 (@dean0x7d)

**Comment by wjakob** [comment]
``target_link_libraries`` is what you want, you can just specify the target name of the pybind11 module.

**Comment by lathen** [comment]
Ah, I actually tried this orginally but got the message `Plain and keyword target_link_libraries signatures cannot be mixed` and immediately  assumed that you could only use `target_link_libraries` once. But it was the `PRIVATE` keyword that was missing in my additional call to `target_link_libraries`. So now all is fine. Maybe this was a bit too silly to add to the docs, I should have investigated the error message further.. Don't bother - we'll close this!

Thanks btw for an awesome library, I'm also a huge fan of NanoGUI  :thumbsup:

**Comment by mivade** [comment]
On the contrary, I think showing this in the docs would be extremely helpful. I was getting the same CMake error mentioned above and, given my relative inexperience with CMake, had no idea what that was supposed to mean.

**Comment by Abhijit-2592** [comment]
@lathen  did you solve the error?

**Comment by jagerman** [comment]
@Abhijit-2592 - yes, see the second post (about needing the `PRIVATE` keyword).

(Also, for future visitors, note that @wichert 's "still fails" error was unrelated--it was a mismatch between the compiled `.so` filename and the module specified in the `PYBIND11_MODULE` macro; see #1271).

**Comment by GliderGeek** [comment]
I have a similar, but slightly different problem. It would like to link another pybind11 module. 

Am trying to create the following two modules:
- point: can be called directly
- line: can be called directly and also uses point module.

Anyone suggestions on how to fix this? i have described my problem in more detail in [a SO question](https://stackoverflow.com/questions/50257655/how-to-use-pybind11-with-cmake-for-linking-2-modules).

**Comment by jagerman** [comment]
> line: can be called directly and also uses point module.

Try adding a `py::module::import("point");` in the `line` binding code to get Python to load the `point` module before you do anything in `line` that relies on it (i.e. near the beginning of your `PYBIND11_MODULE` code).

**Comment by GliderGeek** [comment]
That doesn't do the trick unfortunately. There were a few other suggestions on the gitter channel which are similar, but didn't work:
```
py::object point = (py::object) py::module::import("point");
```
```
py::module point = py::module::import("point");
```

**Comment by soulslicer** [comment]
I can't get any of my 3rd party libraries to work. I set target_link_libraries, but it still complains of undefined symbols

**Comment by Dariusz1989** [comment]
Same here, I'm trying to add QT library but pybind11 is not allowing. To be honest, seeing that pybind11 is cmake based I though that this will be easy. But yet here I am 3 days alter questioning the universes....

How on earth do we get this stuff to work ?! 

I've got this, 
`target_link_libraries(${PROJECT_NAME} Qt5::Widgets Qt5::Core Qt5::Gui Qt5::Network Qt5::Qml Qt5::Quick Qt5::Multimedia Qt5::MultimediaWidgets Qt5::Concurrent opengl32.lib)
`

How to add pybind11 to this I have no idea ;[

TIA.

**Comment by BIGBALLON** [comment]
@lathen thanks for your answer!! It works well!!!

**Comment by eythimis** [comment]
Thanks @lathen :)

**Comment by SumatPurewal** [comment]
None of this works for me.

`
cmake_minimum_required(VERSION 3.5)
project(test_pybind)

#pybind11
add_subdirectory(pybind11)
pybind11_add_module(test_module test_module.cpp)

#OpenCV
set(OpenCV_DIR C:/Users/xyz/Desktop/opencv/build/install)
find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})

target_link_directories(test_module PRIVATE ${OpenCV_LIBS})
`

Linker still complains about undefined symbols from OpenCV.

What am I doing wrong?

@wjakob

**Comment by nalostta** [comment]
I am facing this same issue and when I tried using target_link_libraries (with PRIVATE keyword), it showed this:

> [{
	"resource": "/e:/sdk/vsio/CMakelists.txt",
	"owner": "cmake-configure-diags",
	"severity": 8,
	"message": "CMake Error at CMakeLists.txt:16 (target_link_libraries):Cannot specify link libraries for target \"pbt\" which is not built by this\nproject.",
	"source": "CMake (target_link_libraries)",
	"startLineNumber": 16,
	"startColumn": 1,
	"endLineNumber": 16,
	"endColumn": 10000
}]

**Comment by qgbcs** [comment]
> `target_link_libraries`是你想要的，你可以只指定 pybind11 模块的目标名称。

-- Found pybind11: /opt/vcpkg/installed/x64-linux/include (found version "2.11.1")
CMake Error at CMakeLists.txt:84 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "cashflow".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * /opt/vcpkg/installed/x64-linux/share/pybind11/pybind11Tools.cmake:179 (target_link_libraries)
   * /opt/vcpkg/installed/x64-linux/share/pybind11/pybind11Tools.cmake:211 (target_link_libraries)
