### ISSUE TITLE
Can't make iterators via make_iterator() with different r/v policies

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#388]
Best illustrated by an example:

```cpp
// default r/v policy = reference_internal 
py::make_iterator(begin, end);

// this one's still using reference_internal due to iterator type caching
py::make_iterator(begin, end, py::return_value_policy::copy);
```

This would be due to handle caster being created just once:  https://github.com/pybind/pybind11/blob/master/include/pybind11/pybind11.h#L1140 -- which makes all subsequent calls effectively ignore the `Extra...` arguments. Doesn't looks like it's by design? I actually have a use case where I need to select between copy/ref versions of iterator at runtime...

// One other very minor thing, it would be a tad nicer to have `class_<state>(handle(), "iterator")` instead of `class_<state>(handle(), "")` since the iterators appear as `< at 0x12312312>` in Python; same with `key_iterator`.

**Comment by aldanor** [comment]
A possible solution, I guess, would be to have iterator state also carry all extra arguments passed.

**Comment by wjakob** [comment]
The solution you suggest sounds reasonable (as does adding "iterator" to the ``class_`` name)

**Comment by aldanor** [comment]
Alright. I'm not closely familiar with this part of the API, are the extra parameters always copyable, how should they be stored in the iterator?

**Comment by wjakob** [comment]
I've pushed a fix, can you please verify that it works?

**Comment by aldanor** [comment]
Hi @wjakob thanks -- haven't checked yet but I don't think this is going to work; example:

```cpp
py::make_iterator(begin, end, py::return_value_policy::reference_internal);
py::make_iterator(begin, end, py::return_value_policy::copy);
```

The `Extra...` in both cases is just `[py::return_value_policy]`, so the types of the iterators are the same. The type info for the first one will be cached and the second will now behave wrong. I think the actual values for `extra` need to be stored somewhere, either in iterator or some kind of closure.

This also kind of calls for a test in the test suite... :)

**Comment by aldanor** [comment]
Should this get reopened?

**Comment by wjakob** [comment]
Right, I realize now that this is more complicated.

**Comment by wjakob** [comment]
See the proposed PR #388.

**Comment by jagerman** [comment]
(or #407) :)

**Comment by wjakob** [comment]
right :)
