### ISSUE TITLE
[BUG]: CMake bigobj option incompatible with nvcc

### ISSUE THREAD

**Issue by LXLWDGY** [pybind/pybind11#3883]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

The cmake compile options for pybind11 currently adds a **/bigobj** option if MSVC is used, as can be seen here:
https://github.com/pybind/pybind11/blob/1c636f4dce8414d458fee3a00df72ed769b7f79a/tools/pybind11Common.cmake#L99

This is problematic if the language is in anything other than C++, which in my case was CUDA. The nvcc compiler does not recognize /bigobj (or at least I think this is what happens) and therefore raises an error:
> [Nvcc fatal : A single input file is required for a non-link phase when an outputfile is specified]

There is a very similar issue raised here, which details a bug concerning **/MP**:
https://github.com/pybind/pybind11/issues/1532#issue-360955054

There are a lot of similar bugs if you care to google, and the consensus (whenever there is one) seems to be that /MP and /bigobj are the culprits. I personally have solved this problem by simply changing the line to, but I'm not certain whether this is the best fix:
`    PROPERTY INTERFACE_COMPILE_OPTIONS $<$<NOT:$<CONFIG:Debug>>:$<$<COMPILE_LANGUAGE:CXX>:/bigobj>>)`

**Comment by Skylion007** [comment]
@henryiii This seems like your domain.

**Comment by henryiii** [comment]
That seems like a reasonable fix.
