### ISSUE TITLE
[BUG]: Compiling in windows after installing with vcpkg

### ISSUE THREAD

**Issue by dvirneuman** [pybind/pybind11#3891]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

after installing version 2.9.2 with vcpkg, I can not compile with cmake.
platform: windows.

the error is:

> CMake Error at C:/ext_libs/vcpkg/installed/x64-windows/share/pybind11/pybind11Tools.cmake:132 (set_property):
Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
"debug". The INTERFACE_LINK_LIBRARIES property may contain
configuration-sensitive generator-expressions which may be used to specify
per-configuration rules.

### Reproducible example code

```text
cmake_minimum_required (VERSION 3.8)
set(CMAKE_TOOLCHAIN_FILE "C:/ext_libs/vcpkg/scripts/buildsystems/vcpkg.cmake")
project ("MyProject")
find_package(pybind11 CONFIG REQUIRED)
```

**Comment by wention** [comment]
same problem

**Comment by esride-jts** [comment]
Ran into the same issue, too. Trying to downgrade from version 2.9.2...

**Comment by wsolichin-sees** [comment]
I found the issue with pybind11 and vcpkg in Windows, it's the same issue mentioned here: https://gitlab.kitware.com/cmake/cmake/-/issues/21637. As vcpkg installs Python libraries in both debug and optimized, we can't use the `INTERFACE_LINK_LIBRARIES`, and instead should use `target_link_libraries`. Should I create a pull request for this fix?

**Comment by henryiii** [comment]
Thanks, that's helpful. That was only added in CMake 3.11, so it will need to be conditional. MSVC users should be using a recent CMake, so I think it's fine.

**Comment by henryiii** [comment]
Can someone verify that #3948 does in fact fix this?

**Comment by jeanga** [comment]
I have just tested the latest from the main branch (containing the referenced commit).
What I get (with MSBuild generator):
```
[build] LINK : fatal error LNK1104: cannot open file 'optimized.lib' 
```
Indeed, the generated vcxproj contains an "optimised.lib" reference (and also a "debug.lib" one):
```
      <AdditionalDependencies>MyLib.lib;optimized.lib;..\..\vcpkg_installed\x64-windows-static\lib\python310.lib;debug.lib;..\..\vcpkg_installed\x64-windows-static\lib\manual-link\python.lib;other libs looking better....</AdditionalDependencies>
```

**Comment by Chaojimengnan** [comment]
Hi, I have the same problem, any solution?

**Comment by JackBoosY** [comment]
@henryiii I confirm that this issue is not fixed, related issue: https://github.com/microsoft/vcpkg/issues/26220
The reason is that keywords including debug/optimization cannot be used in `target_link_libraries`.
See cmake issue: https://gitlab.kitware.com/cmake/cmake/-/issues/18424

**Comment by henryiii** [comment]
Can you test my new PR?

**Comment by JackBoosY** [comment]
@henryiii Thanks for your quickly reply, yes that works!

**Comment by Michaelzhouisnotwhite** [comment]
Well, So , How to fix it ?

**Comment by henryiii** [comment]
I think this just needs a release, which should happen in roughly a week I’m guessing.
