### ISSUE TITLE
Bump stable branch to 2.9.2

### ISSUE THREAD

**Issue by MatthijsBurgh** [pybind/pybind11#3937]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

Please bump the stable branch to 2.9.2. I think this has just slipped with the last release.

**Comment by Skylion007** [comment]
@henryiii

**Comment by henryiii** [comment]
Oops, thanks!
