### ISSUE TITLE
[BUG]: pybind11::slice::compute segfaults on complex number slices

### ISSUE THREAD

**Issue by Strilanc** [pybind/pybind11#3953]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

When you call pybind11::slice::compute on a slice that contains a complex number value, the python interpreter crashes with a segfault.

Note that python does allow slices to contain complex entries.

### Actual Behavior

The python interpreter crashes.

### Expected behavior

The python interpreter does not crash.

An exception bubbles up into the python interpreter (via `compute` returning false causing the `if` block to run `throw pybind11::error_already_set()`). The exception says that the slice is not valid.

### Repro

Create a pybind11 module with a method that runs the `repro` method, compile the module into a wheel, then invoke the method from a python interpreter.

```c
#include <pybind11/pybind11.h>
#include <complex>
#include <pybind11/complex.h>

void repro() {
    pybind11::object obj = pybind11::cast(std::complex<double>{0, 1});
    pybind11::slice slice = pybind11::cast<pybind11::slice>(obj);
    pybind11::ssize_t start = 0;
    pybind11::ssize_t stop = 0;
    pybind11::ssize_t step = 0;
    pybind11::ssize_t slice_length = 0;
    pybind11::ssize_t length = 5;

    // this line triggers a segfault
    auto succeed = slice.compute(length, &start, &stop, &step, &slice_length);

    if (!succeed) {
        throw pybind11::error_already_set();
    }
}
```

**Comment by Skylion007** [comment]
You also need ```#include pybind11/complex.h```, it's not included by default I believe.

**Comment by Strilanc** [comment]
Added that include.

**Comment by Skylion007** [comment]
Did it still segfault?

**Comment by Strilanc** [comment]
Yes, it still segfaults.

Note that it segfaults on the `compute` call, not the cast call. And when I originally ran across this it was in a context where the complex value came from the python interpreter, not from the C++ code.

**Comment by Skylion007** [comment]
@Strilanc I added it as a test to the pytest suite and I can't reproduce the error on master. This seems like you are doing something else wrong like not using a scoped_interpreter etc? See the documentation on embedding the interpreter: https://pybind11.readthedocs.io/en/stable/advanced/embedding.html
```    
def test_complex_slice():
        import pybind11_tests.sequences_and_iterators as m
>       assert not m.complex_slice()
E       TypeError: Object of type 'complex' is not an instance of 'slice'

m          = <module 'pybind11_tests.sequences_and_iterators'>

../../tests/test_sequences_and_iterators.py:247: TypeError
```

**Comment by Strilanc** [comment]
Ah, I've confirmed that it no longer segfaults in the latest version. I was on 2.6.0.
