### ISSUE TITLE
Can't override method returning primitive value references

### ISSUE THREAD

**Issue by jagerman** [pybind/pybind11#397]
With #394 applied, any trampoline class that tries to override a function returning a reference or pointer to a primitive type (essentially any of the type_casters that copy a value, such as numeric, std::string, std::complex if `complex.h` is included, etc., and anything else using PYBIND11_TYPE_CASTER) are going to fail.  Between ed14879a1942fdfa4e4ef053c842841ca9fd6fc4 (PR #297) and #394, it wouldn't compile at all; as of #394, it will work for non-converted types, and gives a static_assert compilation failure for primitive types.

Before ed14879a (including in v1.8.1) it compiled, but it was returning a reference to a temporary, as the following demonstrates:
```C++
#include <pybind11/pybind11.h>
PYBIND11_PLUGIN(t) {
    namespace py = pybind11;
    py::module m("t");
    m.def("foo", [](py::object o) { std::cout << o.cast<std::string &>() << "\n"; });
    return m.ptr();
}
```

```Python
import t
t.foo("asdf" * 10)
```
`python test.py | xxd` shows the obvious problem:
```
00000000: 884b e87d 897f 0000 c07b 7a02 0000 0000  .K.}.....{z.....
00000010: 6173 6466 6173 6466 6173 6466 6173 6466  asdfasdfasdfasdf
00000020: 6173 6466 6173 6466 0a                   asdfasdf.
```
(the same code, but cast to a non-reference `std::string`, works as intended, of course):
```
00000000: 6173 6466 6173 6466 6173 6466 6173 6466  asdfasdfasdfasdf
00000010: 6173 6466 6173 6466 6173 6466 6173 6466  asdfasdfasdfasdf
00000020: 6173 6466 6173 6466 0a                   asdfasdf.
```

The fact that an explicit `obj.cast<int &>()` doesn't compile now is not a big deal, but a bigger implication of this is that we cannot override a method that returns a reference (including a `const Type &`).  This isn't something new: we never *could* do such an override properly, but it did actually compile before and gave the appearance of working--it just returned a reference to already-freed memory.

I think, at the very least, it needs to be documented that this isn't supported, but it would be nicer still if we had a suggested workaround.  I thought something like this might work:

```C++
    class A {
        std::string v = "jkl;";
    public:
        virtual const std::string &value() { return v; }
        void print() { py::print(value()); }
    };
    class PyA : public A {
        std::string _value;
        std::string _value_helper() { PYBIND11_OVERLOAD(std::string, A, value); }
        std::string &value() override { _value = _value_helper(); return _value; }
    };

    py::module m("t");
    py::class_<A, PyA>(m, "A")
        .def(py::init<>())
        .def("value", &A::value)
        .def("print", &A::print);
```

... but it doesn't; I get a segfault instead where the assignment to `_value` happens (because, apparently, the trampoline instance is never actually initialized--which is fine as long as it doesn't have any members).  So:

1. Should we document it as not supported?
2. Should we make the above work, by actually initializing the trampoline instance (and what side effects will that have)?
3. Should we find and document some other workaround?

**Comment by jagerman** [comment]
I experimented with this (see the commit referenced above) by changing pybind to always initialize the holder class.  This passes all the tests except one, and makes the above work.

The one that didn't pass (I removed it as part of the commit) is from test_issues and mentions specifically not initializing the trampoline when not inherited from by a python type.  I'm not sure that this is entirely desirable (nor is it what I expected): there are valid cases for using a trampoline *other* than virtual methods; one I've run into a few times is wanting to expose `protected` methods that I can't access, and occasionally to provide a method or two that wrap the C++ method interface in some more pythonic way.  (As long as the class doesn't have any members, these work: a `type` pointer will be the same as a `type_alias` pointer anyway).

Another use case is to be able to use constructors and destructors to do instance cleanup related to the pybind11 interface layer.  In #327, for instance, where he/she wanted a `__del__`, a less intrusive solution than using the `C` destructor would have been to declare a trampoline class and use its destructor.

So even if it's easily fixable to have alias initialization-when-inherited-from-in-python working again, I think it would be nicer to simply always initialize the alias, allowing the trampoline to do more than it currently can.

Thoughts?

**Comment by wjakob** [comment]
There were performance reasons for the current scheme which only initializes the alias class when needed. In particular, virtual calls never reach the trampolines when instantiating a class without overrides on the Python side, which has significant performance benefits. It looks to me like the current proposed patch breaks this behavior.

**Comment by wjakob** [comment]
cc @lyskov

**Comment by jagerman** [comment]
#399 addresses the segfault in the workaround code I have above: aliases *were* initialized, but the space in which they were being put was too small.

**Comment by jagerman** [comment]
So with that out of the way, I think another set of defines for reference overloads might do this.  Experimenting with it now.

**Comment by jagerman** [comment]
Submitted PR #400 to address this.

**Comment by lyskov** [comment]
+1 on @wjakob point on performance implication for classes that might be overridden in Python. It would *be very desirable* to insure that calling virtual methods that was not overridden in Python does not add any runtime-cost comparing to C++ code. (in other words creation creation of trampoline code during binding phase will not degrade performance if it was not used)

**Comment by jagerman** [comment]
Right, I see that.  I've dropped that line of thought/branch in favour of PRs #399 and #400.

(I have come across cases where I'd find it useful, however, to always have trampoline initialization, but making it an opt-in feature that I don't get unless I explicitly ask for it seems entirely reasonable to me, and I'll submit as a separate issue/PR).

**Comment by lyskov** [comment]
Ah, ok - glad that we on the same page on this!!!

**Comment by wjakob** [comment]
This should be resolved now, feel free to reopen if it isn't.
