### ISSUE TITLE
[BUG]: Complie Error

### ISSUE THREAD

**Issue by peterzpy** [pybind/pybind11#4002]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

When I compile a demo under CentOS7 with GCC8.3.1, the error occurs '/attr.h:647:85: error: incomplete type ‘pybind11::detail::process_attribute<int, void>’ used in nested name specifier'. I also run the similar code on macOS, while it could run with no bugs.

### Reproducible example code

```text
// example.cpp
#include <pybind11/pybind11.h>
#include <iostream>

namespace py=pybind11;

int test() {
    std::cout << "231231231231231231232" << std::endl;
}

PYBIND11_MODULE(dijkstra_example, m) {
    m.doc() = " ";
    m.def("test", &test, 'test');
}

//setup.py
from pybind11.setup_helpers import Pybind11Extension, build_ext
from setuptools import setup

functions_module = Pybind11Extension(
    name='example',
    sources=['example.cpp'],
    extra_compile_args=["-O2","-fPIC"],
    include_dirs=['/data/zhiwu/anaconda3/lib/python3.9/site-packages/pybind11/include'],
)

setup(
    ext_modules=[functions_module],
    cmdclass = {"build_ext": build_ext}
)
```

**Comment by henryiii** [comment]
The code above is not valid C++; `'test'` is not the same as `"test"`. Single quotes are for single chars, not strings. You also aren't returning an int from your function. Otherwise works for me, and we test on CentOS 7 and various versions of GCC.

```bash
docker run --rm -it centos:7 bash
yum install centos-release-scl
yum install devtoolset-8 python3-devel git
source scl_source enable devtoolset-8
git clone https://github.com/pybind/pybind11
cd pybind11/
python3 -m venv .venv
source .venv/bin/activate
pip install -U pip setuptools wheel build
pip install .
mkdir tmp
cd tmp
# Add files above, with fix mentioned
python -m build -n
```
