### ISSUE TITLE
[BUG]:  Release new version for bugs in cmake

### ISSUE THREAD

**Issue by FrankXie05** [pybind/pybind11#4040]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

Hi, I am the maintainer of vcpkg and recently encountered a bug about python compilation.
Sorry, I didn't find a place to submit an issue tagged as `question`, so I can only submit an issue tagged as `Bug`
So far you have solved this problem 🦾👍. But our version has not yet synced with this change.

Version: 2.9.2
Fix PR: https://github.com/pybind/pybind11/pull/3948
Related vcpkg PR: 
https://github.com/microsoft/vcpkg/pull/25377 
https://github.com/microsoft/vcpkg/pull/25467

We have two temporary workarounds:

1. Apply the patch that resolves the PR
2. Update the resolved commit on the master branch

My expectations:
Are you guys going to release a new version in the near future as we prefer to keep the updates in the stable version rather than committing in the master branch.
cc @henryiii 

Thanks,
Frank

**Comment by henryiii** [comment]
Aiming for a release before SciPy 2022, so ~1 week or so. Starting the changelog in #4042.

**Comment by FrankXie05** [comment]
@henryiii Thanks for your reply, I will update the new version as soon as possible. :)

**Comment by henryiii** [comment]
2.10.0 is out!
