### ISSUE TITLE
[BUG]: [CPython 3.11] GC not implemented properly for objects with managed dictionaries

### ISSUE THREAD

**Issue by Fidget-Spinner** [pybind/pybind11#4092]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

Pybind11 originally reported a CPython bug at https://github.com/python/cpython/issues/92678. It was later found that the current solution for `Py_TPFLAGS_MANAGED_DICT` implemented by Pybind11 does not properly support GC for their dictionaries.

Suggestion: used the newly added (3.11b5) unstable functions:
- `_PyObject_VisitManagedDict`
- `_PyObject_ClearManagedDict`

to properly implement `tp_clear` and `tp_traverse` for types with `Py_TPFLAGS_MANAGED_DICT` set.

Functions were added in https://github.com/python/cpython/pull/95256/files.

**Comment by Fidget-Spinner** [comment]
CC @Skylion007 and @henryiii

**Comment by Skylion007** [comment]
Yikes... and this is will be a 3.11 only fix since we want to switch APIs once the stable APIs from 3.12 are added....

**Comment by Fidget-Spinner** [comment]
Not needed anymore. Fixed upstream in CPython.

**Comment by vstinner** [comment]
Follow-up: the `Py_TPFLAGS_MANAGED_DICT` flag is set to late in `make_static_property_type()` causing an assertion error (Python debug build) or crash (Python release build) on Python 3.13: see https://github.com/pybind/pybind11/issues/4970. I proposed a fix.
