### ISSUE TITLE
[BUG]: Python 3.12 support

### ISSUE THREAD

**Issue by henryiii** [pybind/pybind11#4115]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

@tacaswell reported that https://github.com/python/cpython/pull/23205 from Python 3.12 breaks pybind11, which in turn breaks matplotlib. We should probably both fix this and see if we can reenable the `dev` tag for 3.12 testing (Might also be good to start playing with using `PyType_FromMetaclass` too).

**Comment by tacaswell** [comment]
and specifically it breaks https://github.com/contourpy/contourpy which breaks Matplotlib

**Comment by pwuertz** [comment]
Python 3.12 now supports global interpreter locks per interpreter (PEP 684). This, as far as I understand, requires more fine grained control over module initialization & cleanup (PEP 489, #2548).

Is this something pybind is eventually able to do, or is this a topic for a pybind reboot like nanobind?

**Comment by rwgk** [comment]
> Is this something pybind is eventually able to do, or is this a topic for a pybind reboot like nanobind?

I don't think creating more clones of pybind11 is environmentally friendly for the world at large. (Unless we have a clean interop story, to avoid excessive copy-pasting from one namespace to another.)

Upshot: I think it'll be best to fit new features into pybind11, even though it obviously requires more thought than another reboot.
