### ISSUE TITLE
Choosing a bindings filename different from the cmake target name

### ISSUE THREAD

**Issue by patrikhuber** [pybind/pybind11#415]
Hi!

I'd like pybind11 to create a file that has a different filename than the name of the CMake target. The problem is the following: Usually you have a library called "xyz", and that library has a CMake target named "xyz" that creates that library. Now I'd of course also like the generated python bindings file to have the name "xyz.pyd", for which you seem to need to do `pybind11_add_module(xyz create-python-bindings.cpp)`. But that's not possible, because it adds a target "xyz" and that target already exists, because it's the library itself. I couldn't see a workaround of some sorts to this in the docs. Am I missing something? Seems like I can't be the first to run into this :-)

**Comment by wjakob** [comment]
You can use cmake commands to adjust the output filename of the target to anything. They don't necessarily need to be the same. I'll refer you to the cmake documentation on how to do this (don't know by heart)

**Comment by dean0x7d** [comment]
Check out the CMake properties documentation, but this should be all you need:
```cmake
set_target_properties(xyz_target_name PROPERTIES OUTPUT_NAME xyz_file_name)
```

**Comment by patrikhuber** [comment]
Aah, yes, I see! That's a good idea. I just tried it and it works more or less. There's still one small issue though: 

`set_target_properties(xyz-python PROPERTIES OUTPUT_NAME xyz)` now causes a file xyz.lib to be generated, from which then an xyz.py is created. So if the library target itself is called "xyz" too and also creates a "xyz.lib" file, this would collide. In my case it's fine because it's a header only library. But still it would be good if it was possible to be able to specify a name for the generated `.pyd` file, so that the target name can be `xyz-python`, generates a `xyz-python.lib`, and then from that, a `xyz.pyd` is created (which will not conflict with anything).

Maybe it would be possible to add a CMake property for this? I'm not sure how easy that would be, might be too much effort.

**Comment by dean0x7d** [comment]
At that point, you're really just fighting the compiler's default naming scheme -- it's also going to generate debug and other support files with the same name but different extensions. (And the debugger is going to expect to find the files like that, so you'll need to adjust it as well.)

The simplest and best thing you can do is to keep the library and Python module in different subdirectories (or parent + subdir). That's the most natural way to resolve name conflicts and you don't need to micromanage the compiler's intermediate and support files. While the support files are safely separated in subdirectories, you can still chose the output path for the main file (`.pyd`) if it's really needed in a specific place (see `LIBRARY_OUTPUT_DIRECTORY` in CMake docs).

**Comment by patrikhuber** [comment]
I see! I thought maybe it was possible to define a CMake property, let's call it `PYTHON_OUTPUT_NAME`, and to pass that on to the python compiler. And then, basically, if `PYTHON_OUTPUT_NAME` is set, it would override the default (which is that the output name is the same as the input name) - I'm sure the python compiler has means to specify the name of the generated file(s).

In any case, my setup is as you suggested, with the python module in a subdirectory.
