### ISSUE TITLE
get_include() does not return the location of the header files

### ISSUE THREAD

**Issue by drufat** [pybind/pybind11#421]
For comparison, in numpy get_include returns the location of the numpy header files:

```
>>> import numpy as np
>>> np.get_include()
'/usr/local/lib/python3.5/site-packages/numpy/core/include'
```

However, doing the same with pybind11 one gets

```
>>> import pybind11 as py
>>> py.get_include()
'/usr/local/include/python3.5m'
```

and there are no pybind11 header files in that location.

I have installed `pybind11` by doing

```
$ python setup.py install 
```
from its source folder.

**Comment by wjakob** [comment]
Sadly this is something we have no control over. pybind11 asks ``pip`` for the path and simply returns this value -- I suggest escalating this issue to them.
