### ISSUE TITLE
[BUG]: Documentation doesn't explain how to bind C++ classes in namespaces

### ISSUE THREAD

**Issue by yurivict** [pybind/pybind11#4244]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### Problem description

C++ class in the namespace
```
namespace aaa::bbb {
  class C {
    // ... methods
  };
}
```

should be accessible using Python notation mod.aaa.bbb.C.

Documentation [here](https://pybind11.readthedocs.io/en/stable/advanced/classes.html) doesn't explain how to handle such situation.

**Comment by jiwaszki** [comment]
There is an explanation on how to handle such situations:
https://pybind11.readthedocs.io/en/stable/reference.html?highlight=submodule#_CPPv4N7module_13def_submoduleEPKcPKc

You can chain them to achieve `mod.aaa.bbb`. As submodule is created you need to use `def()` on specific submodule to mimic C++ counterpart. Some simple code could look like this:
```cpp
py::module_ top_module("example", "Top-level module");
py::module_ aaa_module = top_module.def_submodule("Represents aaa C++ namespace");
py::module_ bbb_module.def_submodule("bbb", "Represents aaa::bbb namespace");

py::class_<aaa::bbb:::C>(bbb_module, "C class");
```

To be honest this solution is the best possible one. If automatic solution would be preferred, this would result in potential problems when translating C++ library to Python standards. Control of submodules allows to overcome some serious problematic cases, such as:

- C++ namespaces that are keywords (such as `pass` or `import`). Imagine case where `namespace engine::import` exists in the project. In pybind you could change name to be allowed in Python.
- C++ namespaces can be flatten or even cut-off, if some library do not want to expose everything and create minimalistic version of bindings.
