### ISSUE TITLE
Add docs for unscoped enum

### ISSUE THREAD

**Issue by ianhbell** [pybind/pybind11#426]
It took me a long time to realize how to wrap unscoped enums in the main namespace, and a simple example in the main docs would have cleared that right up.  I guess now C++11 makes unscoped enum more or less obsolete, but those of us interfacing with older C++ code are stuck.

**Comment by wjakob** [comment]
External contributions for this sort of thing are welcomed.

**Comment by ianhbell** [comment]
Ok, will do.

**Comment by wjakob** [comment]
(Closing this then)
