### ISSUE TITLE
Create bindings to an existing C++ object

### ISSUE THREAD

**Issue by dov** [pybind/pybind11#428]
In an embedded python application, I would like to create a python binding to interact with a C++ object that was already created (typically a singleton). The scenario is something like follows:

```
struct Dog {
    void bark() { printf("Bark!\n"); }
};

int main()
{
  auto dog = new Dog;
  Py_Initialize();
  initexample();

  // TBD - Add binding  between dog and example.dog .

  PyRun_StringFlags("import example\n"
                               "\n"
                               "example,dog.bark()\n"  // Access the C++ allocated object dog.
                               , Py_file_input, main_dict, main_dict, NULL);
  Py_Finalize();
}
```

For this to work the python object `dog` either needs to be defined as a python module, or as a class with all its members being static. 

One solution would be to define the class `Dog` to be a singleton, and then create it once for C++ and then a second time (which will just return a pointer to the singleton) the python binding. But I wonder if there is any solution without changing the definition of Dog?

**Comment by wjakob** [comment]
Embedding Python itself is not a scenario that we support here at the moment, though external contributions are welcomed.

**Comment by dov** [comment]
Embedding python is actually trivial. Here is an example using your `add.cc` file:

```
#include <Python.h>

// The preprocessor defined initializer for our example module.
extern "C" PyObject *initexample();

int main(int argc, char *argv[])
{
  Py_Initialize();
  PyObject* main_module = PyImport_AddModule("__main__");
  PyObject* main_dict = PyModule_GetDict(main_module);

  // Initialize our external module
  initexample();

  // We can now import our example module just like any other module.
  PyRun_StringFlags("import example\n"
                    "\n"
                    "print example.add(3,2);\n"
                    , Py_file_input, main_dict, main_dict, NULL);

  Py_Finalize();
  exit(0);
}

```

To compile do:
```

g++ -o hello-pybind11.o -c -g -Wall -std=c++14 -I/usr/include/python2.7 -I/usr/local/include hello-pybind11.cc
g++ -o add.o -c -g -Wall -std=c++14 -I/usr/include/python2.7 -I/usr/local/include add.cc
g++ -o hello-pybind11 hello-pybind11.o add.o -lpython2.7

```

But what got me stuck is how to create a binding for a C++ singleton.

**Comment by wjakob** [comment]
The library provides no official API for this. Also, users have reported many issues with reference counting issues specifically in conjunction with pybind11.

I checked again, and the question you ask is not really specific to embedding. You need to bind your class and reference the C++ instance as a Python object. All of this explained extensively in the documentation.

**Comment by dov** [comment]
Ok. Thanks. I'll check the documentation again regarding how to reference a C++ instance as python object. Is there an example of this somewhere? Perhaps in tests?

Regarding the lack of API for python embedding, I don't see why a simple call to `initexample()` function isn't enough? It basically calls `Py_InitModule()`. Quoting https://docs.python.org/2/extending/extending.html :

> When embedding Python, the initspam() function is not called automatically unless there’s an entry in the _PyImport_Inittab table. The easiest way to handle this is to statically initialize your statically-linked modules by directly calling initspam() after the call to Py_Initialize():

...which is exactly what I was doing. In any case, I'll make use of it, even if it isn't officially sanctioned. :-)
