### ISSUE TITLE
Bug: exception in noexcept `what()` when Python exception contains a surrogate character

### ISSUE THREAD

**Issue by Skylion007** [pybind/pybind11#4288]
### Discussed in https://github.com/pybind/pybind11/discussions/4287

<div type='discussions-op-text'>

<sup>Originally posted by **TheShiftedBit** October 26, 2022</sup>
By default, Python produces errors when converting encoding `str`s with utf-8 if the `str` contains surrogate characters. This can be disabled by passing `surrogatepass` as a second argument to `.encode()`. Pybind11 has this same behavior with its `str` -> `std::string` conversion. However, the bug is this: if an exception message contains a surrogate character, calling `.what()` on an `error_already_set` with such an exception causes another exception to be thrown, but since `.what()` is `noexcept`, that exception cannot be caught and the program `std::terminate`s.

I'm not sure what the correct behavior regarding surrogate characters is. Perhaps pybind11 should always use `surrogatepass`, perhaps not. However, even if that's not the right choice, it should probably use it during exception handling, or Python exceptions like this are extremely difficult to diagnose.</div>

**Comment by rwgk** [comment]
Without having looked very closely here, it seems similar to what we were running into with the `absl::Status` type, which also reports error messages. We settled on this:

https://github.com/pybind/pybind11_abseil/blob/ef7a738c6472f661aa3a77c228ff0b456fee3f2f/pybind11_abseil/utils_pybind11_absl.cc

That approach could be adopted in `error_already_set`.

Although that throws `error_already_set`, which we don't want to do when we're already inside `error_already_set` I think. I'm not sure how to best error out if there is really no way to recover the error message (some kind of system error or undefined behavior, presumably).

**Comment by Skylion007** [comment]
On MacOS at least: I'm not getting an exception, I am just junk characters as the output. I suspect this may be an issue on Windows though.
```

    def test_surrogate_exception():
        ucs_surrogates_str = "\udcc3"
>       m.test_surrogate_str(ucs_surrogates_str)
\x1b[1m\x1b[31mE       AttributeError: 'str' object has no attribute '\udcc3'\x1b[0m

ucs_surrogates_str = '\udcc3'
```

**Comment by TheShiftedBit** [comment]
You asked for a reproducer, I posted it on the other issue: https://github.com/pybind/pybind11/discussions/4287#discussioncomment-3995628

I temporarily fixed it by adapting your `what()` implementation. I roughly do this:

```cc
auto value_str = py::reinterpret_steal<py::object>(PyObject_Str(ex.value().ptr()));
py::bytes bytes = value_str.attr("encode").call("utf-8", "backslashreplace");
std::string result = bytes;
```

(This one doesn't have the backtrace, just the message). In my case, I don't care about recovering from an exception, I just want to end the program with as much detail as possible; so using `backslashreplace` is a good choice for me. For a more general implementation, you probably want `surrogatepass` or something.

**Comment by Skylion007** [comment]
@TheShiftedBit Your repro doesn't seem to actually reproduce the issue, :( https://github.com/pybind/pybind11/pull/4295/

**Comment by TheShiftedBit** [comment]
I've attached a zip containing a Dockerfile with the full reproducer. I pinned every relevant version number I could find, including pinning pybind11 to the latest release.

Run with:
```sh
cd <place_with_Dockerfile>
sudo docker build -t repro .
sudo docker run repro
```

[pybind11_repro.zip](https://github.com/pybind/pybind11/files/9894673/pybind11_repro.zip)

**Comment by rwgk** [comment]
This reproduces the error:

```diff
index 70b6ffea..0114bc31 100644
--- a/tests/test_exceptions.py
+++ b/tests/test_exceptions.py
@@ -275,6 +275,11 @@ def test_local_translator(msg):
     assert msg(excinfo.value) == "this mod"


+def test_error_already_set_message_with_unicode_surrogate():
+    # Issue #4288
+    m.error_already_set_what(RuntimeError, "\ud927")
+
+
 class FlakyException(Exception):
     def __init__(self, failure_point):
         if failure_point == "failure_point_init":
```

```
test_exceptions.py::test_error_already_set_message_with_unicode_surrogate terminate called after throwing an instance of 'pybind11::cast_error'
  what():  Unable to cast Python instance of type <class 'str'> to C++ type 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Fatal Python error: Aborted

Current thread 0x00007f15b3d4a740 (most recent call first):
  File "/usr/local/google/home/rwgk/forked/pybind11/tests/test_exceptions.py", line 280 in test_error_already_set_message_with_unicode_surrogate
  File "/usr/local/lib/python3.10/dist-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
```

I think it's an easy fix, but I need to play a bit.

**Comment by rwgk** [comment]
@henryiii This would be a good one to get out ASAP. It's a bit nasty that it dies with `terminate`.
