### ISSUE TITLE
Transparent conversion for glm types

### ISSUE THREAD

**Issue by patrikhuber** [pybind/pybind11#430]
Hi!

I've added a set of transparent conversions for [glm](https://github.com/g-truc/glm)'s matrix and vector types. I know that's probably too specific to include in pybind11, but I wanted to share it nonetheless, since there might be other people looking for something similar.

Here's the file:
https://github.com/patrikhuber/eos/commit/822faa52bc41478fc66903feab6f9501344b5d6e

Any comments welcome.

**Comment by jagerman** [comment]
@wjakob - Perhaps it would be worth adding a "contrib" directory for things like this—code that might be useful in edge cases, but without official support.  Or, alternatively, a separate `pybind11-contrib` repository?  Keeping notes in closed bug reports with links to other repositories seems a bit fragile and hard to find.

**Comment by patrikhuber** [comment]
I agree - "opening" an issue for it was the best (or least bad) idea I could come up with.

What about a GitHub wiki? A section there could be dedicated to these custom type-casters.

**Comment by wjakob** [comment]
Rather than a contrib directly (where lots of commits will eventually be needed to keep the changes in sync with development), a wiki might be a nice alternative. I'll set one up right now!
