### ISSUE TITLE
Question about CMake script

### ISSUE THREAD

**Issue by wjakob** [pybind/pybind11#434]
@dean0x7d : A minor question

The cmake code currently contains the following:

```cmake
macro(pybind11_execute_python)
  execute_process(COMMAND ${PYTHON_EXECUTABLE} -m ${ARGN} OUTPUT_QUIET ERROR_QUIET
                  RESULT_VARIABLE pybind11_execute_python_error)
endmacro()
```

Is there any reason why this is a macro? Looking at it, the code could just be pasted a few lines downwards.

**Comment by dean0x7d** [comment]
There is no reason for it anymore. The macro was necessary with the original implementation (#321) which made multiple calls to `pybind11_execute_python`, but this was later changed (#364) leaving just the one call. It's safe to remove it.

**Comment by wjakob** [comment]
Got it, thanks!
