### ISSUE TITLE
Default return value policy for def_property/def_property_readonly

### ISSUE THREAD

**Issue by dean0x7d** [pybind/pybind11#436]
The [return_value_policy docs](http://pybind11.readthedocs.io/en/latest/advanced.html#return-value-policies) state that `def_property` uses `reference_internal` by default, but the current implementation actually uses the `automatic` policy.

The change seems to have happened in this commit 0b4895885b7f1f7ecad2851196943a12f846bb19, but I'm not sure why.  Is there a special reason to prefer `automatic` for `def_property` but `reference_internal` for `def_readwrite`?

**Comment by wjakob** [comment]
@dean0x7d:

For def_property_readwrite etc., the lambda function returns a field, so the RVP obviously *has* to be ``reference_internal``.

For general ``def_property``, the situation is tricky. The user provides a ``cpp_function`` that will generally already have a RVP attached to it. If we add a default value to the recursive ``def_property_*`` calls, it will override the RVP stored in the ``cpp_function``.

This is really an API issue. Do we want to specify custom RVPs as a variadic template argument to ``def_property``, or do we want to specify it as a variadic template argument to ``cpp_function``? Currently, the documentation says the latter:

```rst
Return value policies can also be applied to properties, in which case the
arguments must be passed through the :class:`cpp_function` constructor:

.. code-block:: cpp

    class_<MyClass>(m, "MyClass")
        def_property("data"
            py::cpp_function(&MyClass::getData, py::return_value_policy::copy),
            py::cpp_function(&MyClass::setData)
        );
```

**Comment by dean0x7d** [comment]
I see. That is tricky, but I think it would be worth trying to resolve. By far the most common getter format in C++ should be `const Bar& Foo::get_bar() const`. It would be nice if the API was optimized for it. Manually adding `py::return_value_policy::reference_internal` for most properties is not fun.

Although not that elegant, adding an additional overload for `def_property` and `def_property_readonly` should resolve any RVP issues:
```c++
// existing function
template <typename... Extra>
class_ &def_property(const char *name, const cpp_function &fget, const cpp_function &fset, const Extra& ...extra) {
    return def_property_static(name, fget, fset, is_method(*this), extra...);
}

// additional overload
template <typename Getter, typename... Extra>
class_ &def_property(const char *name, const Getter &fget, const cpp_function &fset, const Extra& ...extra) {
    return def_property(name, cpp_function(fget), fset, return_value_policy::reference_internal, extra...);
}
```

The first overload is resolved when a `cpp_function` getter is passed and it does not apply any RVP. The second overload is for everything else and it sets `reference_internal` by default. RVP doesn't matter for the setter. I think the resulting binding code would be pretty clean, without the extra `py::cpp_function`. The following would all work:

```c++
// default -- reference_internal
.def_property("bar", &Foo::get_bar, &Foo::set_bar)

// cpp_function -- def_property does not override cpp_function's RVP
.def_property("bar", py::cpp_function(&Foo::get_bar, py::return_value_policy::copy), &Foo::set_bar)

// RVP as direct argument -- only the getter cares about RVPs
.def_property("bar", &Foo::get_bar, &Foo::set_bar, py::return_value_policy::copy)
```

It also seems logical to have RVP as a direct `def_property_*` argument, rather than passing it thought `cpp_function`.

One last thing: Having `reference_internal` by default is potentially unsafe if the getter returns an rvalue instead of a reference: `Bar Foo::get_bar() const`. But I think this could be made automatically safe by overriding the policy for rvalues in `type_caster_base` which already happens  in some cases. Actually, is there any use case for having an RVP other than `move` for rvalues? Making it always `move` would remove any possibility for user error in this regard, unless I'm overlooking something.

**Comment by wjakob** [comment]
Your suggestion for the duplicate overloads sounds reasonable to me. Before submitting a PR, could you please double-check that the ``cpp_function`` and template versions get correctly called when using the corresponding arguments? The overload resolution algorithm in C++ can be surprising some times.

The always-move-rvalues policy sounds good to me, but there are also the usual caveats for types that can't be moved at all.
