### ISSUE TITLE
generc_type xxxx is already registered

### ISSUE THREAD

**Issue by kanaero** [pybind/pybind11#439]
Suppose in test_stl_binders.cpp we have two types mapping back to the same underlying c++ type in this case "unsigned int".

    py::bind_vector<std::vector<unsigned int>>(global, "VectorInt");
    py::bind_vector<std::vector<unsigned int>>(global, "AnotherVectorInt");

When importing the module, the error generic_type: type "AnotherVectorInt" is already registered! arises.

Are we disallowing type alias within python. Can we not refer to the same vector type using multiple python types ?

If we choose to keep the current behaviour of disallowing multiple aliases for the same underlying type we should improve the error message to say "generic_type: type "AnotherVectorInt" has underlying type "unsigned int" that is already registered.

**Comment by wjakob** [comment]
You can use ``global.attr("VectorInt") = global.attr("AnotherVectorInt")`` to create an alias on the Python side. However, you can't register the type two times independently since it would cause various inconsistencies in Python-internal data structures.

**Comment by kliegeois** [comment]
@SanPen I am facing the same issue; how have you resolved this?

**Comment by SanPen** [comment]
Hi! yes I solved it by adding `py::module_local()` to the class definition 

example:

```
py::class_<Zone, Device, std::shared_ptr<Zone>>(m, "Zone", py::module_local())
.def(py::init<std::string,
                           std::string,
                           std::string,
                           uword>(),
                  py::arg("uuid"),
                  py::arg("secondary_id"),
                  py::arg("name"),
                  py::arg("time_steps"))
            .def_property("area", &Zone::getArea, &Zone::setArea, "Area object to which this zone belongs to. It may be null.")
            ;
```

THis is somewhere in the docs and should be in every example!

**Comment by kliegeois** [comment]
Thanks a lot @SanPen !
