### ISSUE TITLE
[BUG]: Fail to serialize eigen arrays when GIL released

### ISSUE THREAD

**Issue by migichen** [pybind/pybind11#4403]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.4

### Problem description

I got segfault when pickling eigen arrays while GIL released. The root cause is when pickling an eigen array, Pybind11 will import numpy.core.multiarray in numpy.h:
```python
static npy_api lookup() {
        module m = module::import("numpy.core.multiarray");
        ...
```
, which calls `PyImport_ImportModule()`, which is known must hold GIL.
 (I have checked the current code (v2.10), this part in numpy.h is not changed)

This behavior is inconsistent against pickling other types, which may not require GIL holding. So I think importing modules during the code path of pickling an eigen array should be avoid.

### Reproducible example code

```python
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/iostream.h>
#include <pybind11/eigen.h>
#include <Eigen/Dense>

typedef Eigen::Array<long double, 2, 1> Point2;
struct Node {
  Point2 minpoint;
  Point2 maxpoint;
};
...
PYBIND11_MODULE(MyModule, m) {
  py::class_<Node>(m, "Node")
    .def(py::pickle(
      [](const Node& node) { // __getstate__
          // Return a tuple that fully encodes the state of the object
          return py::make_tuple(node.minpoint, node.maxpoint);
        },
      [](py::tuple t) { // __setstate__
        // doesn't matter here
    }), py::call_guard<py::gil_scoped_release>());
}
```
Then, try to pickle `Node` in python

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by migichen** [comment]
Thank you for pointing out that py::make_tuple is a python API. So although this way to pickle is suggested in document(https://pybind11.readthedocs.io/en/latest/advanced/classes.html#pickling-support), it should not be used without GIL holding. I wonder does Pybind11 suggest a way to pickle eigen and other C types without holding GIL?

That said, interestingly I only hit segfault when `make_tuple`ing eigen variables. Serializing primative C++ types and STL vectors are pretty ok.

**Comment by Lalaland** [comment]
>  I wonder does Pybind11 suggest a way to pickle eigen and other C types without holding GIL?

Not really. Why do you need to do that? There might be a better overall approach.

**Comment by migichen** [comment]
Yes, I am using [Dask-Distributed](distributed.dask.org) (briefly Dask below) to distribute my C++ computation to several computers. Dask is a Python framework that implements a task manager on each worker (on a distributed computer) that send/recv's computation tasks from a centralized "scheduler" server and launches user's Python computation functions.

Dask uses `cloudpickle` to pass Python objects around as computation parameters. Since my computation tasks are implemented in C++, all the computation parameters are of course in C++ objects.  Therefore I implemented the pickling methods in my project with Pybind11. 

Once done, testing in sequential mode works fine. But when my tasks were run in Dask distributed framework, the worker sometimes got disconnected from the scheduler due to not responding to heartbeat (for connectivity check). This is of course because of my pybind functions holding GIL, and Dask uses multithreading instead of multiprocessing to launch user codes. In other words, while user tasks are running and holding GIL, the communication thread cannot respond to heartbeats anymore. Note: Although disconnection is not an issue to Dask framework because it is built to be fail-safe, frequent dropoffs still impacts overall performance.

I have then modified most of my pybind11 functions to release GIL if possible, except pickling functions.  I thought my pickling functions should not take long in doing the serialization/deserialization. However, I still got disconnection occasionally, indicating that I should also release GIL when pickling, or better all the pybind11 functions. Then it comes to the bug here, that I got segfault pickling `eigen` variables.

This is a little off-topic but my current workaround is, instead of pickling `eigen` variables, I add each of those `eigen` elements in floats to `py::make_tuple()`.  With all the functions GIL-released I do not see Dask complaining non-responding workers anymore.

**Comment by migichen** [comment]
Thank you for your precious insights on Python best practice. Yes we should always keep this in mind while constructing our data. 

And I now even feel converting C++ structs to Python objects so that we can serialized them by Python `pickle`, just for a remote machine to deserialize them back to C++ structs, is insane.  I am looking into pure C++ serialization tools like `boost::serialization` or `cereal` to convert them to byte streams.

Actually when it comes to pickling, instead of using `make_tuple()`, I think a pure C++ serialization tools should be suggested as the first choice. Of course, using `make_tuple()` is simple and intuitive, if performance is not the concern.

**Comment by Lalaland** [comment]
Once you get your code into a struct of arrays format, pickle will actually be extremely low overhead because it will call into numpy's serialization logic, which is very efficient C code.

Pickle only sucks when you have an array of structs data format.

**Comment by migichen** [comment]
I think you are suggesting to keep holding GIL while doing pickle/unpickle, and ensure the serialization overhead is minimized by structuring our code into SoA.  I think this is valid and should work perfectly for most cases. 

My issue is that the data structure is not that simple to convert into SoA. The `Node` objects in my case is actually in a "Tree" structure, and here is the full implementation of `Node`:

```python
struct Node {
  Point2 minpoint;
  Point2 maxpoint;
  std::vector<Node> childnodes;
};
```

Pickling `childnodes` is fine, as long as there is no cycle in the tree (so that it is tree).

It is a little hard to restructure a tree into SoA, especially the number of child nodes is not fixed.

**Comment by Lalaland** [comment]
It's actually relatively straightforward to convert this sort of tree structure into SoA.
```

std::vector<Point2> minpoints; // length N
std::vector<Point2> maxpoints; // length N
std::vector<size_t> child_indices_start; // length N

std::vector<size_t> child_indices; // length M
```

child_indices will contain all the indices of the children. child_indices_start contains the starting index into that array for every Node. The ending index is implicitly either the next index or the end of the array.

Fox example

```
child_indices_start = {0, 1, 4, 4, 4};
child_indices = {1, 2, 3, 4};
```

You have five nodes here from 0 to 4 (inclusive). Node 0 has a single child, 1. Node 1 has 3 children (2, 3, 4). All the other nodes have no children.

**Comment by migichen** [comment]
Hi thank you for all the replies. I have some more interesting findings:

1.
It is simply wrong to use pybind11::make_tuple() in GIL-released code blocks. 
WIll also get SegFault in normal functions other than pickle().

2. 
The simple solution should be to use std::make_tuple(): 
```
std::make_tuple(node.minpoint, node.maxpoint);
```
I guess it is because I am leaving the C-python conversion out of my GIL-released code block.
