### ISSUE TITLE
Is it possible to see C++ subclass info from an object that returns a superclass pointer?

### ISSUE THREAD

**Issue by hersh** [pybind/pybind11#441]
I'm trying to write something that has a narrow interface like a getter that returns a superclass pointer, and I would like to return various subclass instances through that and then have the python code figure out which type the instance is.

I don't see how to do this with pybind11 currently, and I've read the docs through quite a few times.  Is it possible to do what I'm trying?

Thanks for a great product, by the way, I've gotten a lot of great use out of it.

Here is my current attempt.

C++:

```
// compile with:
// g++ -fPIC -shared -std=c++11 -I$HOME/pybind11/include `python-config --cflags --ldflags` subclassinfo.cpp -o subclassinfo.so

#include <pybind11/pybind11.h>

struct Super
{
  int a;
};

struct Sub: public Super
{
  int b;
};

class Source
{
public:
  std::shared_ptr<Super> get()
    {
      Sub* sub = new Sub;
      sub->a = 1;
      sub->b = 2;
      return std::shared_ptr<Super>(sub);
    }
};

namespace py = pybind11;

PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

PYBIND11_PLUGIN(subclassinfo)
{
  py::module m("subclassinfo", "test of subclass info");

  py::class_<Super, std::shared_ptr<Super> > super(m, "Super");
  super.def_readwrite("a", &Super::a);

  py::class_<Sub, std::shared_ptr<Sub> >(m, "Sub", super)
    .def_readwrite("b", &Sub::b);

  py::class_<Source>(m, "Source")
    .def(py::init<>())
    .def("get", &Source::get, py::return_value_policy::reference_internal);

  return m.ptr();
}
```

Python:

```
#!/usr/bin/python

import subclassinfo

source = subclassinfo.Source()
obj = source.get()
print obj.a
print obj.b
```

Python thinks the returned object is a Super, so it fails when I try to print obj.b:

```
hersh@chubs$ python subclassinfo.py
1
Traceback (most recent call last):
  File "subclassinfo.py", line 8, in <module>
    print obj.b
AttributeError: 'subclassinfo.Super' object has no attribute 'b'
```

**Comment by wjakob** [comment]
This sort of thing can only work if your type is polymorphic. Otherwise, pybind11 really has no way of finding out that your ``Super``-typed pointer is really pointing to a ``Sub`` instance. Try adding a virtual destructor (e.g. ``virtual  ~Super() { }``) to the ``Super`` class to force making the class polymorphic.

**Comment by hersh** [comment]
Thanks.  I just tried that and it still fails.

```
struct Super
{
  virtual ~Super(){}
  int a;
};
```

... i.e. I just added the one line you suggested.

**Comment by hersh** [comment]
When a wrapped object is returned from C++ to Python, is there anything dynamic going on with the type, or is it fixed by the wrapper code?

It seems like pybind11 would need to be calling typeid() on the returned object and looking through all the bound types to see if any matched in order for this to work, wouldn't it?

**Comment by hersh** [comment]
I retried my example with plain pointers instead of std::shared_ptr, and it still has the same result.  I added a little check to see that the C++ side knew the run-time type name of the Super* and it showed it as "3Sub".  So it seems the virtual destructor is doing its job of forcing polymorphic behavior.

Looking further at pybind11, I don't see anywhere that typeid() is called on an instance, it is always called with a type.  Therefore I don't see how it could work without changes to pybind11.

**Comment by jagerman** [comment]
Using exactly your code, but with `virtual ~Super() = default;` added to `struct Super`, I get the expected result (1/2).  Are you sure you recompiled properly (and don't have multiple `.so`s with different names/directories or something along those lines) after adding it?

(As for the `typeid()`, the relevant ones that use the instance for polymorphic type detection are in pybind11/cast.h).

**Comment by hersh** [comment]
My apologies, I was not using the latest version of pybind11.  With the latest version and the virtual destructor, it works fine.

Thanks for the help!
