### ISSUE TITLE
[BUG]: id(reference_internal_obj) is not stable under python 3.9+

### ISSUE THREAD

**Issue by district10** [pybind/pybind11#4425]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

not relevant (tested on quite old & new version of pybind11)

### Problem description

id(reference_internal_obj) is not stable under python 3.9+.

### Reproducible example code

(Full code at <https://github.com/district10/cmake_example/commit/9e293fa5ceadb7c7df07466f5a6c6ef2c7db1a21>)

```cpp
struct Beed {};
struct Pod {
    Beed &beed() { return _beed; }
  private:
    Beed _beed;
};

py::class_<Beed>(m, "Beed").def(py::init<>());
py::class_<Pod>(m, "Pod").def(py::init<>()).def("beed", &Pod::beed, rvp::reference_internal);
```

Compile & install:

```bash
conda activate py39 # choose a python
python3 setup.py install
```

test `id(pod.beed())`:

```python
# python3 tests/test_id.py
import cmake_example as m
p = m.Pod()
beeds = set()
for _ in range(5):
    beeds.add(id(p.beed()))
print(beeds)
# python 3.9+ (tested on python 3.9, 3.10)
```

python <= 3.8 output (tested py36, py37, py38): `{140689219312944}` (one id)

python >= 3.9 output (tested py39, py310): `{140689219312944, 140689219312880}` (not just one id)

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by Skylion007** [comment]
@district10 Would you be willing to make a PR that reproduces the issue in our test suite? That would make it easier to work on this issue.

**Comment by district10** [comment]
@Skylion007 python `is` does recognize them as the same object.
![image](https://user-images.githubusercontent.com/5262037/209836186-ecea9738-81a3-4110-b0fd-05cb3dd6605a.png)

It's late here, I'll try adding to test suite later.

**Comment by district10** [comment]
@Skylion007 https://github.com/pybind/pybind11/pull/4433

**Comment by district10** [comment]
It's more like a python GC thing, see https://github.com/pybind/pybind11/pull/4433 for details.
