### ISSUE TITLE
[FEATURE REQUEST]: Improve error logging with new inc_ref() feature

### ISSUE THREAD

**Issue by Lalaland** [pybind/pybind11#4426]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.10.2

### Problem description

In 2.10.2, @rwgk added a really neat feature to detect undefined behavior by double checking the GIL on reference counter calls.

Unfortunately (as experienced by our users, https://github.com/scipy/scipy/issues/17644), the error messages here are really bad, especially on Windows.

We need a better error message strategy here to avoid user confusion.

This is tricky because this feels like a regression to our users when we really want to better inform them about UB in their code.

### Reproducible example code

https://github.com/tylerjereddy/pybind_repro is a really nice Windows example that has terrible error messaging.

### Is this a regression? Put the last known working version here if it is.

2.10.1

**Comment by Lalaland** [comment]
I'll assign myself as I already have pybind_repro set up on Windows so I can easily play with different error reporting strategies.

One key thing is that we must not throw exceptions in the DLL load process. We probably want to do some raw printf calls here.

**Comment by Skylion007** [comment]
Causing issues here as well: https://github.com/pytorch/pytorch/issues/91251
