### ISSUE TITLE
Bizarre Python 3.x failure when creating method aliases

### ISSUE THREAD

**Issue by wjakob** [pybind/pybind11#443]
Consider the following program, which creates an alias of a method. My use case for this kind of design pattern were two different precision implementations of some floating point code (i.e. `computeSingle` and `computeDouble`) as well as an alias for the default compile time precision of the application (i.e. `computeFloat`).

``` cpp
#include <pybind11/pybind11.h>

struct Test { void foo() { printf("foo\n"); } };

namespace py = pybind11;

PYBIND11_PLUGIN(test) {
    py::module m("test");
    py::class_<Test> tclass(m, "Test");

    tclass
        .def(py::init<>())
        .def("foo", &Test::foo);

    tclass.attr("bar") = tclass.attr("foo");

    return m.ptr();
}
```

Calling this from Python 3.x produces the following issue (Python 2.7 works without problems):

``` pycon
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
>>> t = test.Test()
>>> t.foo()
foo
>>> t.bar()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo(): incompatible function arguments. The following argument types are supported:
    1. (self: test.Test) -> None

Invoked with:
```

What specifically happens here is that the implicit `self` argument is dropped, which causes method resolution to fail. The root cause is `PyInstanceMethod_New`, which seems to be really picky about the name of the attribute that does the function call.

So when creating an alias, this means that we would have to un-box the method from it's method wrapper, and re-box it with a different name. It wasn't clear to me how to do that in a transparent way, and whether that's a generally reasonable workaround. What's also weird is that this kind of behavior does not occur in native Python classes, where method aliases can be created without such problems.

**Comment by dean0x7d** [comment]
I'm not sure that the name is the problem. If I try this in Python 3:
```python
>>> class Test:
...     def foo():
...         pass
...
>>> Test.bar = Test.foo
>>> t = Test()
>>> t.foo
<bound method Test.foo of <__main__.Test object at 0x1066025c0>>
>>> t.bar  # still called "foo" internally
<bound method Test.foo of <__main__.Test object at 0x1066025c0>>
```

`t.bar` retains the method name `foo` but it works correctly. On the other hand, with the pybind11 class:

```python
>>> import test
>>> test.Test.baz = test.Test.foo
>>> t = test.Test()
>>> t.foo
<bound method PyCapsule.foo of <_test.Test object at 0x105374538>>
>>> t.bar
<built-in method foo of PyCapsule object at 0x1052ac750>
>>> t.baz
<built-in method foo of PyCapsule object at 0x1052ac750>
# Also
>>> test.Test.foo
<built-in method foo of PyCapsule object at 0x1052ac750>
```

Somewhere along the way it goes from being a `PyInstanceMethod` to a pure `PyCFunction`, but I'm not sure where that happens.

**Comment by jagerman** [comment]
> I'm not sure where that happens.

It happens [here](https://hg.python.org/cpython/file/4243df51fe43/Objects/classobject.c#l642) and [here](https://hg.python.org/cpython/file/4243df51fe43/Objects/classobject.c#l502).  When calling `tclass.attr("foo")` (in C++) or accessing `Test.foo`, PyInstanceMethod itself returns the wrapped PyCFunction rather than itself.

#802 works around it by not giving PyInstanceMethod a chance to return something else.
