### ISSUE TITLE
[BUG]: pybind11::dtype::of<T> segfault

### ISSUE THREAD

**Issue by Char-Aznable** [pybind/pybind11#4448]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

a34596b

### Problem description

The following code triggers a segmentation fault:

```c++
#include <pybind11/numpy.h>

int main(int argc, char *argv[])
{
  auto float32 = pybind11::dtype::of<float>();
}
```

My cmake build is:

```cmake
cmake_minimum_required (VERSION 3.23)

# projectname is the same as the main-executable
project(testPybind11 LANGUAGES CXX)
include(FetchContent)

FetchContent_Declare(
  pybind11
  GIT_REPOSITORY https://github.com/pybind/pybind11.git
  GIT_TAG        origin/master
  GIT_SHALLOW 1
)

set(PYBIND11_FINDPYTHON ON)

FetchContent_MakeAvailable(pybind11)

add_executable(hello hello.cpp)
target_link_libraries(hello PRIVATE pybind11::embed)
```
BTW, what I am trying to do is to convert a c++ type to the corresponding typestr of numpy (as in https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.interface.html#__array_interface__). But I don't know if pybind11::dtype::of<float>().kind() is the way to do it

### Reproducible example code

```text
++
#include <pybind11/numpy.h>

int main(int argc, char *argv[])
{
  auto float32 = pybind11::dtype::of<float>();
}
```

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by Lalaland** [comment]
You generally aren't allowed to call CPython functions outside of the module init.

Is there some reason why you think this should work?

**Comment by Char-Aznable** [comment]
@Lalaland Thank you for your comments. I thought the header-only usage allows me to do that in pure c++.

**Comment by Lalaland** [comment]
@Char-Aznable If you follow the instructions in https://pybind11.readthedocs.io/en/stable/advanced/embedding.html, you should be able to embed the interpreter. Note how Python functions (py::print) can be called after py::scoped_interpreter is initialized.

**Comment by Char-Aznable** [comment]
Putting the `py::scoped_interpreter guard{};` and installing numpy in the environment does solve the problem. I thought the `numpy.h` code is some dedicated c++ code to map type from c++ to python but didn't realize it relies on numpy to work. Thanks @Lalaland for the help!
