### ISSUE TITLE
Multiple inheritance change seems to break holder type test in some cases

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#446]
Or at least it breaks my understanding of it. So perhaps all that is needed is a change to the documentation.

The following wrapper:

```py::class_<Mask<unsigned short>, std::shared_ptr<Mask<unsigned short>>, ImageBase<unsigned short>> cls(mod, "MaskS");```

fails to compile with:

```static_assert failed "Unknown/invalid class_ template parameters provided"
    static_assert(detail::all_of_t<is_valid_class_option, options...>::value,
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
python/lsst/afw/image/mask.cc:37:92: note: in instantiation of template class```

But works once the `PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>)` macro is added at the top.
This did not use to be the case with the old `py::base` syntax. Perhaps this can be clarified in the documentation?
I was wondering also if it is perhaps not possible to somehow eliminate the need to add the macro altogether? Failing to put that in is a frequent source of errors.

**Comment by jagerman** [comment]
The documentation about this macro already reads (and has, since 1.1):

> To enable transparent conversions for functions that take shared pointers as an argument or that return them, a macro invocation similar to the following must be declared at the top level before any binding code:
>
> PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

Think of the new message as being a compile-time check that you actually declared the holder type before attempting to use it.

Would it help to improve the static assert message to something like:

"Unknown/invalid class_ template parameters provided -- perhaps you forgot to declare the holder type, or specified an invalid base or trampoline class?"

**Comment by dean0x7d** [comment]
`std::shared_ptr` is an extremely common holder type. Would there be any downside to adding a `type_caster_holder` specialization directly to the library? It would eliminate the need for `PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>)` in user code, leaving it only for truly custom smart pointers.

**Comment by wjakob** [comment]
This seems fine to me, though it will break a lot of code in going to v2.0.

**Comment by pschella** [comment]
I would be very happy if we follow the suggestion from @dean0x7d and no longer have to use the macro for `std::shared_ptr<T>`.

As for the error message, yes that might help. Although I would only put that in if there are no other likely reasons the assert fails. I read the documentation differently, saying one should only add the macro to get the automatic translation of smart pointer arguments (and return values). My confusion was compounded by the fact that until the change away from `py::base` it would actually compile without the macro.

**Comment by dean0x7d** [comment]
`std::shared_ptr` could be added in a backwards compatible way. It would require SFINAE-ing the holder declaration macro:
```c++
#define PYBIND11_DECLARE_HOLDER_TYPE(type, holder_type) \
    namespace pybind11 { namespace detail { \
    template <typename type> \
    class type_caster<holder_type, enable_if_t<!is_shared_ptr<holder_type>::value>> \
        : public type_caster_holder<type, holder_type> { }; \
    }}
```
It would turn off any existing user-declared `std::shared_ptr` holders (and leave the non-SFINAEd library specialization). The only downside is that it doesn't have a deprecation warning so it would essentially leave a bit of dead code for existing users.

**Comment by wjakob** [comment]
nice! -- short and effective. Let's use that. With this workaround, I see no need to deprecate the macro for ``shared_ptr``.

**Comment by pschella** [comment]
That sounds great!
