### ISSUE TITLE
[BUG]: Wrong argument for gil_scoped_release deleted copy constructor

### ISSUE THREAD

**Issue by AlexanderSerov** [pybind/pybind11#4484]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

master

### Problem description

Is [passing ](https://github.com/pybind/pybind11/blob/master/include/pybind11/gil.h#L155) gil_scoped_acquire as parameter to gil_scoped_release deleted copy constructor expected?
@Skylion007 

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by Skylion007** [comment]
No, that appears to be a bug.
