### ISSUE TITLE
[BUG]: Python C++ interface incorrectly casts a derived class instance when using a base class type for cast

### ISSUE THREAD

**Issue by abulavin** [pybind/pybind11#4507]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.9.2

### Problem description

Consider two classes, `Pet` and `Dog`, where `Dog` is a subclass of `Pet`. `Pet` has a virtual method `bark()` that is not implemented, but is overridden in the `Dog` subclass. Both classes have bindings and are exposed to python.

```cpp
struct Pet {
    Pet(const std::string &name) : name(name) { }
    virtual std::string bark() const {
        throw std::runtime_error("Not implemented");
    }
    std::string name;
};

struct Dog : Pet {
    Dog(const std::string &name) : Pet(name) { }
    std::string bark() const override  { return "woof!"; }
};
```

When using the Python C++ interface to instantiate a `py::object dog` object and then casting `dog` to a C++ type using `Pet dog_cpp = dog.cast<Pet>()`, the casted object appears to not be polymorphic and is instead treated as the base class `Pet`, instead of `Dog`. The expected behaviour is that `casted.bark()` should call `Dog::bark()`, and not `Pet::bark()` because the original object instantiated using the C++ python interface has type `Dog`. The following code below will fail with `RuntimeError: Not Implemented`

```cpp
void reproducer() {
  py::object dog_class = py::module_::import("cmake_example").attr("Dog");

  py::object dog = dog_class("timmy");

  Pet dog_cpp = dog.cast<Pet>();

  dog_cpp.bark();
}
```
I have reproduced this issue using the `cmake_example` repository template here: https://github.com/abulavin/pybind11-reproducer. The C++ code can be found under `src/`, and the python calling code that raises the error is in `test.py`. See section below to run the reproducer.

### Reproducible example code

```text
git clone --recursive https://github.com/abulavin/pybind11-reproducer
cd pybind11-reproducer/
pip install .
python test.py
```

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by zolo2013** [comment]
I think the line in your test should be: 

Pet& dog_cpp = dog.cast<Pet&>();

instead of 

Pet dog_cpp = dog.cast<Pet>();

which is a copy to an Pet object.

**Comment by abulavin** [comment]
Yep, that fixed it 😅. Thanks for the suggestion. For posterity, the fix was changing
```cpp
Pet dog_cpp = dog.cast<Pet>();
```
to use reference types as follows:
```cpp
Pet& dog_cpp = dog.cast<Pet&>();
```
