### ISSUE TITLE
Type casters for NumPy scalars

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#451]
It would be nice to be able to pass structured NumPy scalars back to C++, e.g.:

```c++
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <vector>

struct A { int a; float b; A() = default; A(int a) : a(a), b(a + 1) {} };

PYBIND11_PLUGIN(test_scalars) {
    PYBIND11_NUMPY_DTYPE(A, a, b);
    return pybind11::module("test_scalars")
        .def("f_struct", [](A a) { return (float) a.a + a.b; })
        .def("mk_structs", []() {
                std::vector<A> x {A(1), A(2), A(3)};
                return pybind11::array_t<A>(3, x.data());
            })
        .ptr();
}
```

It would be great to have this work:

```python
>>> from test_scalars import *
>>> f_struct(mk_structs()[1])
```

(it already works with arithmetic NumPy types, but mostly because they inherit from the builtins)

Because structured types are always POD, they're default constructible and don't have a user destructor; so basically all we need to do is a reinterpret cast. Each element  of the structured array is of type `np.void`:

```python
>>>  mk_structs()
array([(1, 2.0), (2, 3.0), (3, 4.0)], dtype=[('a', '<i4'), ('b', '<f4')])
>>> row = mk_structs()[1]; row
(2, 3.0)
>>> type(row).mro()
[numpy.void, numpy.flexible, numpy.generic, object]
>>> row.dtype
dtype([('a', '<i4'), ('b', '<f4')])
>>> row.data.tolist()
[2, 0, 0, 0, 0, 0, 64, 64]
```

@wjakob Any ideas on how this could be best implemented?

**Comment by wjakob** [comment]
The important thing would be to do it without adding undue computation/code bloat to the general case (i.e. types which don't care about being stored in a numpy container).

This feature could potentially be implemented by creating a function that appends a new implicit conversion to the type's ``implicit_conversions`` list. The entries of that list are functions which take a ``py::object`` that can't be handled by the associated invocation of ``type_caster_generic::load()`` and return one that can be handled. All implementations currently involve making a copy, but it would be possible to add conversions that return a different view of the original data.

In this particular case, the implicit conversion should check that the argument is a ``py::array`` with the expected dtype.

Then I guess, you'd do something like
```
object inst(PyType_GenericAlloc(tinfo->type, 0), false);
auto wrapper = (instance<void> *) inst.ptr();
wrapper->value = <pointer to py::array contents>;
wrapper->owned = false;
detail::keep_alive_impl(inst, <py::array instance>);
internals.registered_instances.emplace(wrapper->value, inst.ptr());
return inst.release();
```

where ``tinfo`` is a pointer to pybind11's internal record of the type.

**Comment by wjakob** [comment]
Addendum: whatever this function or method is called (e.g. ``dtype::register_implicit_conversion()``) could be called from ``detail::npy_format_descriptor<Type>::register_dtype()``

**Comment by wjakob** [comment]
This is a nice idea btw.

**Comment by wjakob** [comment]
I guess you really need to know the C++ type to access the pybind11 internal type record, so ``dtype::register_implicit_conversion()`` would need to be a template function that is parameterized by that.

**Comment by aldanor** [comment]
Hmm, yes, I think this would work, but isn't it a *lot* of overhead? I.e., to pass an element of a structured array to a C++ function, it will

- try to cast it to `T`
- fail, check implicit conversions
- get to one that matches
- create python object
- register the object in the hash map
- cast the resulting object to `T` again
- later, dealloc python object and remove from hash map

whereas the hypothetical ideal scenario is just something like 
```cpp
*reinterpret_cast<T*>(PyArray_GET_(obj.ptr(), data))
```

Now, because numpy array's `__getitem__` itself always returns a copy of the element and not a "reference" into the array (which you would get when obtaining a 1-element slice), we can copy it around as well (i.e., you won't be able to mutate original array this way, anyhow). Plus, I don't think you'd want to track those temporary instances anyway?

**Comment by aldanor** [comment]
It's basically a pure rvalue here, so we won't want it to bind to mutable references, etc.

**Comment by wjakob** [comment]
Yes, it would be pretty expensive, and a simple ``PyArray_GET_`` is clearly cheaper. Another way could be to modify the generic type caster and have another ``else`` branch that tries this conversion (perhaps with an extra `` if (std::is_pod<Type>) { }`` to avoid generating useless code for non-POD classes).

The tricky part would be to know when that conversion is applicable. Here is one thought about that: NumPy supports attaching metadata to a type.
```
>>> np.dtype('<i8', metadata={'hello': 'world'}).metadata
mappingproxy({'hello': 'world'})
```
This could be used to cache the ``class_<>`` type object of the underlying POD type. Specifically, ``dtype::of<>`` could call ``detail::get_type_info(const std::type_info &)`` to get the ``class_`` object and stick it into the metadata when creating a new dtype. 

Then in the ``generic_type_caster`` in ``cast.h``, there could be quick to see if the object is a NumPy array. If so, the next test would verify that the dtype metadata matches the caster's type. The last step would run the operation you mention. This scheme obviously requires that types are bound before corresponding dtypes are generated.

However, there is one major catch: What I *really* want to avoid is pulling ``numpy.h`` into the main set of header files. NumPy support is a very useful feature, but it's not needed by many (most?) applications.

So we'd need to find a way to do all of these steps without relying on ``numpy.h``, and without executing any code that would import ``numpy`` on the Python side.

**Comment by aldanor** [comment]
Re: metadata, note that the `class_<>` may not even be defined at all, like in the example above :) (or it may be, but it's completely orthogonal in this case).

Hmm, maybe there could be "pod_casters", kind of like implicit converters, but not requiring type info to exist at all. Pod casters would be triggered if:
1) type is pod
2) either of:
2.1) type info doesn't exist
2.2) type info does exist, casting failed, implicit conversions failed

(then registering a dtype would also register a "pod caster").

It's a bit clunky but then it would be detached from `numpy.h`, I think.

**Comment by aldanor** [comment]
#453 has been merged in, closing.
