### ISSUE TITLE
[BUG]: Binding two maps with two different integer key types failues due to duplicate KeyViews

### ISSUE THREAD

**Issue by gatecat** [pybind/pybind11#4529]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

3cc7e4258c15a6a19ba5e0b62a220b1a6196d4eb

### Problem description

The attached example code binds two map types: `std::map<uint16_t, uint16_t>` and `std::map<uint32_t, uint16_t>`.

With recent pybind11 this fails when importing with:

```
ImportError: generic_type: cannot initialize type "KeysView[int]": an object with that name is already defined
```

Looking at the relevant code: 
https://github.com/pybind/pybind11/blob/3cc7e4258c15a6a19ba5e0b62a220b1a6196d4eb/include/pybind11/stl_bind.h#L733

checks whether a matching key typeid has been wrapped already; but in this case two different typeids have the same string name in pybind11.

This is breaking a project that happens to use this; if there's a workaround other than unifying the map key types that fixes things with recent pybind11 releases that would also be useful to know.

Thanks for your help!

### Reproducible example code

```c++
#include <pybind11/pybind11.h>
#include <pybind11/stl_bind.h>
#include <map>

namespace py = pybind11;

PYBIND11_MODULE(python_example, m) {
    py::bind_map<std::map<uint16_t, uint16_t>>(m, "u16u16map");
    py::bind_map<std::map<uint32_t, uint16_t>>(m, "u32u16map");
}
```

### Is this a regression? Put the last known working version here if it is.

Believe this was broken by 9db988013ceb54ab15fb775b229ac9180fd08fbe.  2.10.0 was known working.

**Comment by lyskov** [comment]
The same issue also appear if one attempts to bind both map to `float` and `double`. Minimal code to replicate:
```C++
#include <map>
#include <pybind11/pybind11.h>
#include <pybind11/stl_bind.h>

PYBIND11_MODULE(example, m)
{
	// leads to ImportError: generic_type: cannot initialize type "ValuesView[float]": an object with that name is already defined
	pybind11::bind_map< std::map<std::string,float> >(m, "map_string_float" );
	pybind11::bind_map< std::map<std::string,double> >(m, "map_string_double" );
}

```

**Comment by mika-fischer** [comment]
I think this was broken by https://github.com/pybind/pybind11/commit/9db988013ceb54ab15fb775b229ac9180fd08fbe first released in [v2.10.2](https://github.com/pybind/pybind11/releases/tag/v2.10.2), from https://github.com/pybind/pybind11/pull/4353

**Comment by mika-fischer** [comment]
And needless to say this also breaks our build, so this is a real issue.

Interrestingly we also run into this:
```
ImportError: generic_type: cannot initialize type "ArrayInt2": an object with that name is already defined
```
ArrayInt2 is a binding for `std::array<int, 2>`. Not entirely sure if it's the same issue, but it also appears with 2.10.2...

Everything works fine in 2.10.1.

**Comment by Tobias-Fischer** [comment]
Are there any updates on this? It also breaks a few of my projects, see https://github.com/conda-forge/pycolmap-feedstock/issues
