### ISSUE TITLE
[BUG]: compile slow even if simply include header

### ISSUE THREAD

**Issue by zingdle** [pybind/pybind11#4558]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.10.3

### Problem description

a simple file that includes pybind11 and does nothing:

```c++
#include "pybind11/pybind11.h"
```

It takes ~2.4s to compile with g++ 9.4.0: `g++ -I <pybind11-include-path> -I <python-include-path> -c demo.cc`

`nm demo.o | wc -l` shows the object has 2956 symbols!

is this the desired behavior? I expect nothing get compiled if no pybind11 struct is used.

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by henryiii** [comment]
This (the 2+ seconds) is heavily due to the C++ stdlib - including it takes an over a second just to parse all the headers. C++20 modules and C++23 stdlib module should help solve this, I think, whenever we can eventually use it.

**Comment by zingdle** [comment]
@henryiii  Thanks for your reply. Looking forward to the module feature.

Just out of curiosity, I write a simple template class with stdlib:

```cpp
#include <iostream>
#include <vector>

template <typename T>
struct A {
    T t = 0;
    int x = 1;

    std::string foo(int y) {
        return std::to_string(t) + std::to_string(y);
    }

    static std::vector<int> bar(int y) {
        return {y * 2};    
    }
};
```

the `nm` only shows limited symbols for stdlib:

```
                 U __cxa_atexit
                 U __dso_handle
                 U _GLOBAL_OFFSET_TABLE_
000000000000004d t _GLOBAL__sub_I_t.cc
0000000000000000 t __static_initialization_and_destruction_0(int, int)
                 U std::ios_base::Init::Init()
                 U std::ios_base::Init::~Init()
0000000000000000 r std::piecewise_construct
0000000000000000 b std::__ioinit
```

after I add:

```cpp
int main() {
  A<int> a;
  a.foo(2);
}
```

then the `nm` shows `struct A` and stdlib related symbols:

```
...
0000000000000068 t __static_initialization_and_destruction_0(int, int)
0000000000000000 W A<int>::foo[abi:cxx11](int)
0000000000000000 W std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned long, char const*, __va_list_tag*), unsigned long, char const*, ...)
0000000000000000 W bool __gnu_cxx::__is_null_pointer<char>(char*)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::capacity() const
...
```

But when `nm` the object file with just `pybind11.h` included, I found lots of things like: 
```
...
0000000000000000 W pybind11::type::handle_of(pybind11::handle)
0000000000000000 W pybind11::tuple::operator=(pybind11::tuple&&)
0000000000000000 W pybind11::tuple::tuple(pybind11::handle, pybind11::object::borrowed_t)
0000000000000000 W pybind11::tuple::tuple<int, 0>(int)
0000000000000000 W pybind11::tuple::tuple<long, 0>(long)
0000000000000000 W pybind11::tuple::tuple<unsigned long, 0>(unsigned long)
0000000000000000 W pybind11::tuple::tuple(pybind11::handle, pybind11::object::borrowed_t)
0000000000000000 W pybind11::tuple::tuple<int, 0>(int)
0000000000000000 W pybind11::tuple::tuple<long, 0>(long)
0000000000000000 W pybind11::tuple::tuple<unsigned long, 0>(unsigned long)
0000000000000000 n pybind11::tuple::tuple(pybind11::handle, pybind11::object::borrowed_t)
0000000000000000 n pybind11::tuple::tuple<int, 0>(int)
0000000000000000 n pybind11::tuple::tuple<long, 0>(long)
0000000000000000 n pybind11::tuple::tuple<unsigned long, 0>(unsigned long)
0000000000000000 W pybind11::tuple::~tuple()
0000000000000000 W pybind11::tuple::~tuple()
0000000000000000 n pybind11::tuple::~tuple()
...
```

Seems that it instantiate the `pybind11::tuple` and generated weak symbols. I presumed a header-only library should only instantiate struct when you acturally used it. Are thoses `pybind11::tuple` symbols related to stdlib thing? Will that slow down the compilation?
