### ISSUE TITLE
Failure calling base class method

### ISSUE THREAD

**Issue by bradharmon** [pybind/pybind11#463]
With v1.8 I am coming across two issues:

- I cannot call a base class method from within a derived class.
- Derived class method is executed exactly 500 times for unknown reasons.

A contrived example follows:

```
#include "example.h"

class Base {
public:
    Base() {}
    virtual void run() { std::cout << "Run Base" << std::endl; }
};

class Example1: public Base {
public:
    Example1() {}
};

void init_ex1(py::module &m) {
    py::class_<Base>(m, "Base")
        .def("run", [](Base &b) {
            std::cout << "Running important code..." << std::endl;
            // Extra code can go here before calling run(), which may be important.
            b.run();
        });

    py::class_<Example1>(m, "Example1", py::base<Base>())
        .def(py::init<>())
        .def("run", [](Example1 &e) {
            std::cout << "Example1 run()" << std::endl;
            py::cast<Base>(e).attr("run").cast<py::object>()(); // <-- Error occurs here
        });
}
```

```
#!/usr/bin/env python
import sys
sys.path.append('.')
from example import Example1

Example1().run()
```

Results when running python script:

```
...
Example1 run() # <-- 500 times!
Example1 run()
Example1 run()
...
Traceback (most recent call last):
  File "example1.py", line 7, in <module>
    Example1().run()
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (example.Example1) -> NoneType
    Invoked with: <example.Example1 object at 0x7f0d156ed3b0>
```

**Comment by wjakob** [comment]
This is just infinite recursion -- your derived method is calling itself. That's really nothing specific to pybind11 and a property of how virtual methods work in C++.

You could call ``e.Base::Run()`` in the second lambda function.

I suggest that you review the pybind11 advanced documentation on virtual function calls and trampolines, since it looks like that functionality may be useful for your project.

**Comment by bradharmon** [comment]
Thanks for the quick response.  Greatly appreciated!

Yes, I could call `e.Base::run()`, however, I am trying to achieve something that calls into the first lambda, not into `Base::run()` directly. The portion where `// Extra code can go here...` is important to me.

**Comment by wjakob** [comment]
The interface is simply not designed to do what you want. You may be able to use trampolines (refer to the docs) to do something similar, but not in this exact way.

**Comment by bradharmon** [comment]
Thanks for the verification. I'll try other workarounds now that I know this isn't directly supported.
