### ISSUE TITLE
Static linking using Cmake

### ISSUE THREAD

**Issue by amitibo** [pybind/pybind11#466]
Hi,

I am trying to (cmake) compile a binding to a library that uses a another library (dlib). This library is compiled for static linking. Is it possible to set pybind11 to use static linking?

Thanks,
Amit

**Comment by wjakob** [comment]
Python extension modules have to be dynamic. However, you can have a dynamic pybind11 module that links to a static library.

Best,
Wenzel

**Comment by amitibo** [comment]
I am linking using CMake, following the docs example:

    ADD_SUBDIRECTORY(pybind11)
    PYBIND11_ADD_MODULE(pyface pyface.cpp dummy.cpp)
    TARGET_LINK_LIBRARIES(pyface dlib ${OpenCV_LIBS})
 
When running make, I get the following error:

    Linking CXX shared module pyface.so
    /usr/bin/ld: dlib_build/libdlib.a(threads_kernel_shared.o): relocation R_X86_64_32 against `_ZN4dlib21threads_kernel_shared14thread_starterEPv' can not be used when making a shared object; recompile with -fPIC
    dlib_build/libdlib.a: could not read symbols: Bad value

If I understand correctly, it tries to do dynamic linking with the dlib library which is compiled for static linking. How can I request static linking with the dlib library when creating the pyface module?

Thanks,
Amit

**Comment by dean0x7d** [comment]
Add the following line to enable `-fPIC` for your dependency:
```cmake
set_target_properties(dlib PROPERTIES POSITION_INDEPENDENT_CODE TRUE)
```

Note that this really isn't specific to pybind11. It's general build system and linking for any dynamic library.

**Comment by surabhi96** [comment]
How to link pybind11 module that links to a static library? I tried TARGET_LINK_LIBRARIES but I seem to be using it wrongly. 
Thanks!

**Comment by Sberm** [comment]
> Add the following line to enable `-fPIC` for your dependency:
> 
> ```cmake
> set_target_properties(dlib PROPERTIES POSITION_INDEPENDENT_CODE TRUE)
> ```
> 
> Note that this really isn't specific to pybind11. It's general build system and linking for any dynamic library.

Thank you so much sir
