### ISSUE TITLE
[BUG]: Undefined Symobl: `pybind11::detail::type_caster<at::Tensor, void>::load(pybind11::handle, bool)`

### ISSUE THREAD

**Issue by FabianSchuetze** [pybind/pybind11#4696]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

cca4c51ca463

### Problem description

Thanks for this wonderful project, it is a pleasure to work with it.

I am trying to build a pybind11 module which uses pytorch. When I try to load
the library in Python, I get the following error:

```
In [1]: import torch_extension
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import torch_extension

ImportError: /workspace/build/torch_extension.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN8pybind116detail11type_casterIN2at6TensorEvE4loadENS_6handleEb
```
The symbol demangles to:
```
pybind11::detail::type_caster<at::Tensor, void>::load(pybind11::handle, bool)
```
The CMakeLists.txt file that I use is:
```
cmake_minimum_required(VERSION 3.15)                                           
project(torch_extension)                                                         
set(SOURCES MySources)
                                                                               
add_subdirectory(submodules/pybind11)                                          
                                                                               
# Set include directories                                                      
find_package(Torch REQUIRED)                                                   
find_package(Python REQUIRED COMPONENTS Interpreter Development)               
include_directories(${TORCH_INCLUDE_DIRS})                                     
include_directories(${PYTHON_INCLUDE_DIRS})                                    
                                                                               
pybind11_add_module(torch_extension MODULE ${SOURCES})                           
set_property(TARGET torch_extension PROPERTY CXX_STANDARD 17)                    
set_property(TARGET torch_extension PROPERTY CUDA_STANDARD 17)                   
set_property(TARGET torch_extension PROPERTY CUDA_ARCHITECTURES native)          
                                                                               
# Set extra link arguments                                                     
target_link_libraries(torch_extension PRIVATE -lcublas_static -lcublasLt_static  
    -lculibos -lcudart -lcudart_static -lrt -lpthread -ldl                     
    -L/usr/lib/x86_64-linux-gnu/ ${TORCH_LIBRARIES} Python::Python             
    pybind11::pybind11)                                                        
                                                                               
# Set extra compile options                                                    
target_compile_options(torch_extension PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--std=c++17;-O3;-U__CUDA_NO_HALF_OPERATORS__;-U__CUDA_NO_HALF_CONVERSIONS__;-U__C    UDA_NO_HALF2_OPERATORS__>)
```

I put all the bindings in the cpp file `bindings.cc` which looks like:
```
#include "include/my_torch_extension_header.h"
#include <pybind11/pybind11.h>                                                                         
#include <torch/extension.h>                                                   
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {   
...
}
```
Based on the [custom-type-caster](https://pybind11.readthedocs.io/en/stable/advanced/cast/custom.html?highlight=detail#custom-type-casters) docs, I presume that I need to define this function myself? Pytorch seem to have a [relevant type caster](https://github.com/pytorch/pytorch/blob/4cfa06f706811e2c3b70289b222461822537bd93/torch/csrc/utils/pybind.h) . I included the header file `#include <torch/csrc/utils/pybind.h>`  in my `bindings.cpp` source file, but to no avail. 

Does somebody have an idea what I need to change to load the module?

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by AkiyamaYummy** [comment]
exactly the same question as mine. did you solve it? :cry:

@FabianSchuetze @rwgk @henryiii

**Comment by haopan27** [comment]
I'd like to propose reproducing this issue as follows:

First clone facebookresearch's repo "[ReBeL](https://github.com/facebookresearch/rebel)" (please be aware, that according to the dev, "The build is only tested on Linux machines")

Then follow the procedure outlined in the "Installation" section of the README. Use [a1b71df](https://github.com/pybind/pybind11/tree/a1b71df137e015d44f7e31f7b6d4807253fb7871) version of pybind11 as seen in the repo. When I first executed "make", I encountered the following message (here's the first few lines of many more):

> CMakeFiles/gen_benchmark.dir/gen_benchmark.cc.o: In function `pybind11_static_get':
/opt/conda/envs/rebel/lib/python3.7/site-packages/torch/include/pybind11/detail/class.h:49: undefined reference to `PyProperty_Type'
CMakeFiles/gen_benchmark.dir/gen_benchmark.cc.o: In function `pybind11_static_set':
/opt/conda/envs/rebel/lib/python3.7/site-packages/torch/include/pybind11/detail/class.h:55: undefined reference to `PyProperty_Type'

So I copied the `pybind11` folder within the `include` folder of the pybind11 repo over here: `/opt/conda/envs/rebel/lib/python3.7/site-packages/torch/include/` (make a copy of the already existing `pybind11` folder if you'd like). Then I was able to complete make without any errors

Now depending on if you have any GPUs, do one of the following commands:
CPU:

> python run.py --adhoc --cfg conf/c02_selfplay/liars_sp.yaml \
>     env.num_dice=1 \
>     env.num_faces=4 \
>     env.subgame_params.use_cfr=true \
>     selfplay.cpu_gen_threads=60

GPU:

> python run.py --adhoc --cfg conf/c02_selfplay/liars_sp.yaml \
>     env.num_dice=1 \
>     env.num_faces=4 \
>     env.subgame_params.use_cfr=true \
>     selfplay.cpu_gen_threads=0  \
>     selfplay.threads_per_gpu=8

And if you are "lucky" as me, you'll see something similar as the following:

> Traceback (most recent call last):
  File "run.py", line 25, in <module>
    import cfvpy.tasks
  File "/home/usrname/rebel-main/cfvpy/tasks.py", line 15, in <module>
    import cfvpy.selfplay
  File "/home/usrname/rebel-main/cfvpy/selfplay.py", line 27, in <module>
    import cfvpy.rela
ImportError: /home/usrname/rebel-main/cfvpy/rela.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN8pybind116detail11type_casterIN2at6TensorEvE4loadENS_6handleEb

Just as [FabianSchuetze](https://github.com/FabianSchuetze), I too wondered if I'd have to define `pybind11::detail::type_caster<at::Tensor, void>::load(pybind11::handle, bool)` myself (or find it somewhere if it's already defined)? I am hoping the reproduction procedure outlined above suffices and we can begin to tag maintainers/devs if so.

**Comment by rwgk** [comment]
This file needs to be compiled & linked:

https://github.com/pytorch/pytorch/blob/main/torch/csrc/utils/pybind.cpp

That's a problem with the build system, definitely outside pybind11, therefore closing this bug.

I think it's pretty unusual to see template specialization code in a .cpp file. That's a choice made by the pytorch team. Please ask there.

**Comment by erwangccc** [comment]
Hi, @rwgk @FabianSchuetze @haopan27 
So the solution is this?

> This file needs to be compiled & linked:
> 
> https://github.com/pytorch/pytorch/blob/main/torch/csrc/utils/pybind.cpp
> 
> That's a problem with the build system, definitely outside pybind11, therefore closing this bug.
> 
> I think it's pretty unusual to see template specialization code in a .cpp file. That's a choice made by the pytorch team. Please ask there.

**Comment by haopan27** [comment]
@erwangccc 
Here's an indirect answer to your question.

The solution I found for my purposes (to be able to run "[ReBeL](https://github.com/facebookresearch/rebel)") was to downgrade PyTorch from 1.13.1 (where the original "Undefined Symbol" issue happened) to 1.4.1 (as required by ReBeL). Yes, it's totally my fault to neglect the version requirement. But with 1.4.1, the "Undefined Symbol" was gone. That's simply what worked for me, inspired by rwgk's comment.

**Comment by rwgk** [comment]
In the interest of the community (I have no stake in this myself): Please file a **pytorch bug report**, as I was suggesting before. I think this is the link: https://github.com/pytorch/pytorch/issues

Maybe look first if there is a related bug report already. If this isn't a known issue already, point them to the two comments here:

* https://github.com/pybind/pybind11/issues/4696#issuecomment-1678574353

* https://github.com/pybind/pybind11/issues/4696#issuecomment-1679013574

**Comment by haopan27** [comment]
As suggested by rwgk, I've submitted a PyTorch bug report:
https://github.com/pytorch/pytorch/issues/108041
