### ISSUE TITLE
Custom type caster question

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#482]
// This is more of a question/exercise than an issue. 

Suppose I want the following to work: for all functions that accept a certain user type in C++, I want them to also accept certain Python types like tuple/None and translate them to this user type according to some rules.  So, in the example below, function `bar()` takes a `const Bar&`, and I'd want it to be possible to pass a tuple `(x, y)` from Python or a `None` so that it understands it. 

However I can't seem to fully work it out through implementing a type caster specialization (I think the cast() function is flaky) and find it quite difficult although I've been digging around pybind11 internals for a good while now... Is this a kind of thing we want to be easy to do? What's a proper "base case" for cast() and load() here? 

Below is a short example (which doesn't really work since any call to `bar` would erroneously print `2/3`; the arguments conversion itself seems to work though), how do I fix it? :)

```cpp
#include <pybind11/pybind11.h>
#include <string>

struct Bar {
    int x = 2; 
    int y = 3;
    Bar() = default;
    Bar(int x, int y) : x(x), y(y) {}
};

namespace pybind11 { namespace detail {
template<> struct type_caster<Bar> {
    static handle cast(const Bar& src, return_value_policy policy, handle parent) {
        return type_caster_base<Bar>::cast(&src, policy, parent);  // (???) hmm....
    }

    bool load(handle src, bool convert) {
        if (!src) 
            return false;
        if (src.is_none()) { 
            value = {}; 
            return true; 
        }
        tuple args(src, true);
        if (args.check()) {
            if (len(args) != 2)
                return false;
            value.x = args[0].cast<int>();
            value.y = args[1].cast<int>();
            return true;
        }
        return caster.load(src, convert); // (???)
    }

    type_caster() = default;
    PYBIND11_TYPE_CASTER(Bar, _("Bar"));
private:
    type_caster_generic caster = typeid(Bar);
};
} }

PYBIND11_PLUGIN(test_conv) {
    namespace py = pybind11;
    py::module m("test_conv");
    py::class_<Bar>(m, "Bar")
        .def(py::init<>())
        .def(py::init<int, int>())
        .def("__repr__", [](const Bar& v) {
            return std::to_string(v.x) + "/" + std::to_string(v.y); });
    m.def("bar", [](const Bar& bar) { py::print(bar); });
    return m.ptr();
}
```

**Comment by wjakob** [comment]
I don't (right away) spot any issue in the code above. In any case, this sort of thing is easiest to do with the implicit conversions feature. You'll want to add a special constructor ``.def("__init__", [](Bar &b, py::tuple t) { new (&b) Bar(t[0].cast<int>(), t[1].cast<int>()); }`` and then add a line like ``py::implicitly_convertible<py::tuple, Bar>();``

**Comment by aldanor** [comment]
I still don't understand why the code above doesn't work :/ In fact, it does correctly reject all arguments that are not either `Bar`, `None` or a tuple of length 2 (as intended), but then `bar()` always prints "2/3" which is a default initialization value (so it must be the `cast()` I guess...).

Re: implicit conversions, yea, I first thought about them too but didn't use them because there was validation of the tuple argument here (length check). I guess I forgot that the exceptions are consumed while the appropriate loader is being selected.

So this actually works as expected:

```cpp
// ...
        .def("__init__", [](Bar &self, py::tuple t) {
            if (py::len(t) != 2)
                throw std::runtime_error("oh no");
            new(&self) Bar(t[0].cast<int>(), t[1].cast<int>());
        })
// ...
    py::implicitly_convertible<py::tuple, Bar>();
```

allowing you to call `bar((10, 20))` from within Python and it works. It also doesn't accept tuples of wrong sizes.

However, this implicit converter doesn't work, which is quite sad: (any ideas why?)

```cpp
// ...
        .def("__init__", [](Bar &self, py::none) {
            new(&self) Bar();
        })
// ...
    py::implicitly_convertible<py::none, Bar>();
```

**Comment by wjakob** [comment]
@aldanor: This is not a bug. None will always convert to a ``nullptr``-valued instance of "Bar" and therefore needs no implicit conversion. However, your ``bar()`` method expects a reference instead of a pointer, and it's impossible to pass ``nullptr``-valued references around in C++. For this reason, pybind11 returns with a type error.
