### ISSUE TITLE
[BUG]: Coverity scan issue: Possible dereferencing iterator pos though it is already past the end of its container.

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [pybind/pybind11#4822]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.10.2

### Problem description

Scan highlights possible issue in function `clear_patients` in "class.h" file:

![image](https://github.com/pybind/pybind11/assets/21087696/44faf463-6f4a-43d0-8491-57919e8a6af2)

I assume the tools expects explicit check before dereferencing:

```c++
if (pos != internals.patients.end()) {
    // Clearing the patients can cause more Python code to run, which
    // can invalidate the iterator. Extract the vector of patients
    // from the unordered_map first.
    auto patients = std::move(pos->second);
    internals.patients.erase(pos);
    instance->has_patients = false;
    for (PyObject *&patient : patients) {
       Py_CLEAR(patient);
    }
} else {
    assert(pos != internals.patients.end());
}
```

If such a change is agreeable, I'd be happy to open a PR.

Feel free to resolve this issue if you are against this change and believe this issue is a false positive in the Coverity scan.

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by rwgk** [comment]
Did you try this with `-UNDEBUG` already?

**Comment by oleksandr-pavlyk** [comment]
Yes, doing `-UNDEBUG` does help.
