### ISSUE TITLE
How to suppress automatic docstring generation

### ISSUE THREAD

**Issue by stukowski** [pybind/pybind11#485]
Is there a way to suppress the automatic generation of docstrings by pybind11?

I am converting my Python binding code from Boost.Python, which provides the [docstring_options](http://www.boost.org/doc/libs/1_61_0/libs/python/doc/html/reference/high_level_components/boost_python_docstring_options_h.html) facility for suppressing the creation of docstrings. I am wondering if something similar exists in the pybind11 framework.

Background: I want only class members to appear in my Sphinx generated documentation for which I explicitly provided a docstring. Members without a docstring should not appear in the documentation, because they are not part of the public API that I want to expose.

**Comment by wjakob** [comment]
Something like this does not yet exist, but you are welcome to contribute it. I'll close this ticket for now since this is a feature request and not a pybind11 issue.
