### ISSUE TITLE
Module required in py::exception and py::register_exception?

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#492]
I wonder why `exception` ctor and `register_exception` take `module&` and not just a scope, like `class_`? Is it only to get a nicely formatted name or are there some other reasons?

Sometimes there's no well-defined module -- e.g. you have an external C++ library that provides a way to register pybind11 translators for its exceptions, but doesn't have any pybind11 modules per se. It would be handy to be able to register exception "inline" (kind of like it's done in the implementation of `py::iterator`, the class is created on the fly with `handle()` as the scope).

// Another minor thing: would probably make sense for `exception` to have an overload of `operator()` also accepting `const std::string&`, it looks a bit inconsistent, e.g. with its ctor.

**Comment by wjakob** [comment]
I think it's an oversight -- changing to a generic ``py::object`` would be perfectly reasonable.
