### ISSUE TITLE
Uses of `size_t` and `ptrdiff_t` without including `cstddef`

### ISSUE THREAD

**Issue by SylvainCorlay** [pybind/pybind11#498]
Many compilers define `size_t` and `ptrdiff_t` but according to the standard these are only guaranteed to be defined in the standard namespace in the `<cstddef>` header.

We came across this issue in xtensor with some flavors of clang.

So the method is to replace all uses of `size_t` and `ptrdiff_t` with std::size_t and `std::ptrdiff_t` and include `cstddef`.

**Comment by jagerman** [comment]
Is there any reason we couldn't simply add `#include <cstddef>` to the list of includes into common.h, and:
```C++
using std::size_t;
```
at the beginning of `common.h`'s pybind11 namespace code?  Otherwise we're talking more than 200 changes, and an ongoing (and easily forgotten) annoyance of having to prefix all `size_t` uses with `std::`.

**Comment by SylvainCorlay** [comment]
Making use of `std::size_t` in a header is probably not good practice.

The standard practice is to have container classes expose some types. (size_type) that are used throughout the methods of the class.

**Comment by wjakob** [comment]
We already have a typedef for ``ssize_t`` to ``Py_ssize_t``, which saves a bunch of typing in many places. I think a similar alias for ``size_t`` would be reasonable. (and regarding the latest message: We definitely don't want to template everything on a generic ``size_type`` if it's not going to be generic after all.)

**Comment by SylvainCorlay** [comment]
(What I meant is that `size_type` is generally a per-allocator thing in the STL.)
A top level typedef like for Py_ssize_t is reasonable to me.

**Comment by SylvainCorlay** [comment]
Python's `Py_ssize_t` is a bit of a mystery to me though. (why a signed integral type of the same length as `size_t` instead of `ptrdiff_t`).
