### ISSUE TITLE
Issue with char* vs char[] in C++14 implementation of descr _()

### ISSUE THREAD

**Issue by patrikhuber** [pybind/pybind11#502]
Hi!

I've got a custom type-caster, modelled after the one in `eigen.h`. Here's the offending code, explanation below:

```
template<typename Type>
struct type_caster<Type>
{
    static constexpr std::size_t num_elements = 2;
protected:
    template <typename T = Type>
    static PYBIND11_DESCR elements() { return _(std::to_string(num_elements).c_str()); }
}
```

Compiling with VS2015 works, but compiling with gcc-5.4 and clang-3.8 fails:

```
/myproj/repro.hpp:44:44: error: no matching function for call to '_'
        static PYBIND11_DESCR elements() { return _(std::to_string(num_elements).c_str()); }
                                                  ^
/myproj/pybind11/include/pybind11/descr.h:66:53: note: candidate template ignored: could not
      match 'const char [Size]' against 'const char *'
template <size_t Size> constexpr descr<Size - 1, 0> _(char const(&text)[Size]) {
                                                    ^
/myproj/pybind11/include/pybind11/descr.h:77:47: note: candidate function template not viable:
      requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, descr<Size1 - 1, 0>> _(char const(&text1)[Size1], char const(&)[Size2]) {
                                              ^
/myproj/pybind11/include/pybind11/descr.h:81:48: note: candidate function template not viable:
      requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, descr<Size2 - 1, 0>> _(char const(&)[Size1], char const(&text2)[Size2]) {
                                               ^
/myproj/pybind11/include/pybind11/descr.h:85:39: note: candidate function template not viable:
      requires 0 arguments, but 1 was provided
template <size_t Size> auto constexpr _() -> decltype(int_to_str<Size / 10, Size % 10>::digits) {
                                      ^
/myproj/pybind11/include/pybind11/descr.h:89:48: note: candidate function template not viable:
      requires 0 arguments, but 1 was provided
template <typename Type> constexpr descr<1, 1> _() {
```

What's happening is that in `descr.h` there are two implementations, one for C++11 (which gets chosen when compiled in VS2015), and one for C++14, which gets chosen when compiling in clang/gcc.

The C++11 codepath seems to accept the `const char*`, while the C++14 implementation doesn't.

My guess is that what I am trying to do is supposed to work, and there's a problem with the C++14 code path, but I'm not 100% sure!

**Comment by wjakob** [comment]
``descr`` is a compile time type, so it can't be combined with runtime heap-allocated types like ``std::string``. To express a number as a ``descr``, use the special ``_<ConstExprNumber>()`` function. (See descr.h and the rest of the codebase for usage)

**Comment by patrikhuber** [comment]
Cool! Yep, `_<ConstExprNumber>()` is indeed the way to go. Compiles fine now on all platforms. This is even used in `eigen.h`! Sorry to have missed that.

(By the way pybind's C++11 code path of `descr` the same technique that I used with `to_string()`:
`return descr(std::to_string(Size).c_str(), types);`
So it seems like I wasn't too far off :-)

Thank you again for your help, awesome!

**Comment by jagerman** [comment]
This difference is exactly what:

> - When supported by the compiler, two new C++14 features (relaxed constexpr and return value deduction) are used to precompute function signatures at compile time, leading to smaller binaries.

is referring to in the README.

**Comment by patrikhuber** [comment]
I see! Makes perfect sense now. Thanks for adding this comment @jagerman.
