### ISSUE TITLE
Optional caster r.v.p. problems

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#509]
Just ran into a peculiar bug, where it looks like the type caster is taking a pointer to a value on the stack. I could reproduce it with `optional<enum>` but it doesn't seem to happen with `optional<int>` for some reason (why?). 

I guess it must do something with dereference operator for optionals and the default return value policy for properties being `reference_internal` since it doesn't happen with `.def()` as can be seen in the example below. Maybe I'm just doing something stupid (but is returning rvalues in property definitions invalid?).

Can't seem to pinpoint the exact cause of the problem though, so any help's much appreciated :)

```cpp
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <cstdint>
#include <experimental/optional>

namespace py = pybind11;
using std::experimental::optional;

enum class Side : int8_t { Left = 1, Right = -1 };

struct Foo {
    optional<Side> side_;
    Foo(Side side) : side_(side) {}
    optional<Side> side() const { return side_; }
};

PYBIND11_PLUGIN(test_optcast) {
    py::module m("test_optcast");
    py::enum_<Side>(m, "Side")
        .value("Left", Side::Left)
        .value("Right", Side::Right);
    py::class_<Foo>(m, "Foo")
        .def(py::init<Side>())
        .def_property_readonly("side", &Foo::side)
        .def("side_method", &Foo::side);
    return m.ptr();
}
```

```python
>>> import cppimport; cppimport.force_rebuild(); m = cppimport.imp('test_optcast')
>>> foo = m.Foo(m.Side.Right)
>>> int(foo.side_method())
-1  # as expected
>>> int(foo.side)
96  # ^__^
```

**Comment by dean0x7d** [comment]
PR #510 should fix this. The difference between `optional<int>` and `optional<enum>` is that the latter uses `type_caster_generic` which is affected. There's more details in the PR, but the basic issue is that `type_caster_generic::cast` uses its `&&` overload to switch to the `move` policy, but `optional_caster::cast` only has a `const&` overload and so the policy change never happens.
