### ISSUE TITLE
Inheritance with static factory member functions breaks return type

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#511]
I encountered the following unexpected behaviour. When having the following inheritance relation `Base <- Derived <- DerivedImpl` and a static factory `std::shared_ptr<Derived> Derived::make() { return make_shared<DerivedImpl>(); };` (`Base` has a similar `make`). When `Base` and `Derived` are wrapped (and `DerivedImpl` is not) all works well if `Derived` is not marked to inherit from `Base`. But if the inheritance relation is added then `Derived.make()` returns `Base` instead of the expected `Derived`.

See the attached patch file (of `test_inheritance`) for an example (remove the inheritance relation to get the expected correct behaviour).

[pimpl_error.txt](https://github.com/pybind/pybind11/files/601562/pimpl_error.txt)

**Comment by jagerman** [comment]
The problem isn't an inheritance one, but rather it appears to be a problem with `def_static`s of the same name across inheritance trees.  I changed your example to this:

```C++
#include <pybind11/pybind11.h>
#include <iostream>

class MyBase {
public:
    static std::unique_ptr<MyBase> make() {
        std::cerr << "MyBase::make()" << std::endl;
        return std::unique_ptr<MyBase>(new MyBase());
    }
    virtual ~MyBase() = default;
};

class MyDerived : public MyBase {
public:
    static std::unique_ptr<MyDerived> make() {
        std::cerr << "MyDerived::make()" << std::endl;
        return std::unique_ptr<MyDerived>(new MyDerived());
    }
};


PYBIND11_PLUGIN(issue511) {
    namespace py = pybind11;
    py::module m("issue511", "Issue 511 test");

    py::class_<MyBase>(m, "MyBase")
        .def_static("make", &MyBase::make);

    py::class_<MyDerived>(m, "MyDerived", py::base<MyBase>())
        .def_static("make", &MyDerived::make)
        .def_static("make2", &MyDerived::make)
        ;

    return m.ptr();
};
```

with Python:
```Python
from issue511 import MyBase, MyDerived

b = MyBase.make()
d1 = MyDerived.make2()
d2 = MyDerived.make()

assert isinstance(b, MyBase)
assert isinstance(d1, MyDerived)
assert isinstance(d2, MyDerived)
```

When I compile that and run it, I get:

```
MyBase::make()
MyDerived::make()
MyBase::make()
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    assert isinstance(d2, MyDerived)
AssertionError
```

Notice the `d1 = ...` is going to the right place (MyDerived), but the `d2 = ...` isn't: it ends up calling `MyBase::make()`.  So the actual inheritance (and recognition of subobjects) is working fine.  The bug, rather, is in how the static method gets set up.  (Suggest re-titling this to something like "static methods on derived classes are ignored in favour of base class static methods with the same name".)

**Comment by jagerman** [comment]
Also note that the above switched back to the deprecated pybind11 base class specification: I wanted to see if it also happened in 1.8.1, and indeed it does.

**Comment by jagerman** [comment]
(And goes all the way back to 1.4; perhaps earlier, but the `unique_ptr` return value support looks like it was added in 1.4).

**Comment by jagerman** [comment]
Aha: here's something demonstrating exactly what the problem is:
```
>>> MyDerived.make(123)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: make(): incompatible function arguments. The following argument types are supported:
    1. () -> issue511.MyBase
    2. () -> issue511.MyDerived
```

**Comment by wjakob** [comment]
Thanks for the report, fix pending..

**Comment by jagerman** [comment]
@wjakob - I think the fix is just a matter of changing pybind11.h line 263 from:

```C++
                if (chain->class_ != rec->class_)
```
to
```C++
                if (chain->class_ != rec->class_ || chain->scope != rec->scope)
```

(without this, the same chain is shared for static method for both the parent and derived classes, since both have `class_` set to null).

**Comment by wjakob** [comment]
Yep, and my patch just has
```
 if (chain->scope != rec->scope)
``

**Comment by wjakob** [comment]
Fix pushed. I also completely got rid of the ``class_`` field in a second patch, since it was quite redundant..

**Comment by pschella** [comment]
Thanks for the quick diagnosis and fix!
