### ISSUE TITLE
LICENSE file is missing in the tarball on https://pypi.python.org/pypi/pybind11

### ISSUE THREAD

**Issue by yurivict** [pybind/pybind11#512]

**Comment by wjakob** [comment]
Can you propose how to change the PyPi scripts here to add a LICENSE file?

**Comment by yurivict** [comment]
I couldn't understand why exactly LICENSE file doesn't get transferred into PyPi. But here is some discussion about the license file: http://stackoverflow.com/questions/9977889/how-to-include-license-file-in-setup-py-script

Also, as an example, py-gitdb package also uses BSD license and it does appear in PyPi: https://pypi.python.org/pypi/gitdb

**Comment by dean0x7d** [comment]
The simplest thing would be to add the following line to `MANIFEST.in`:
```
include LICENSE, README.md, CONTRIBUTING.md
```

**Comment by wjakob** [comment]
The solution from the referenced stackoverflow post says

> There is no direct need to ship a license with your product, you can use the license metadata in distutils to specify this.

(and we're already doing that AFAIK)

**Comment by dean0x7d** [comment]
The license isn't exactly BSD as specified in the metadata (there's a custom appendix).
