### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by SylvainCorlay** [pybind/pybind11#513]
I just wanted to ask about the following coding conventions in pybind

- `#pragma once` : do you experience a significant benefit of this over standard inclusion guards.
- `NAMESPACE_BEGIN(pybind11)`: what is the reason  for wrapping namespace declaration in macros? At first I thought that this was done to enable some renaming to have multiple definitions , but in multiple locations of the library, you can find things like `::pybind11` which shows that it is probably not the intention.

(feel free to close this)

**Comment by wjakob** [comment]
1. #pragma once: shorter, can't have issues with typos/repetitions would break guards, supported by all compilers we care about.

2. NAMESPACE(pybind11): avoids having to type out braces, which can interfere with source code formatting software that then wants to indent the whole file by 4 spaces.

This is also done for consistency with all of my other projects, so I don't really want to change it ;).

**Comment by jagerman** [comment]
NAMESPACE_END(pybind11) also gives a nice self-documenting feature (vs the more traditional `} // end of namespace pybind11`
