### ISSUE TITLE
[BUG]: undefined Boost::headers with Boost::boost found

### ISSUE THREAD

**Issue by Teloze** [pybind/pybind11#5138]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

4d0fced

### Problem description

in the tests/CMakeLists.txt the target Boost::headers is empty if Boost::boost found. I believe the problem is at https://github.com/pybind/pybind11/blob/4d0fcedc266df1f254da832d86698dfef15bfdf6/tests/CMakeLists.txt#L333 where the TARGET should be Boost::headers, instead of Boost::boost.

### Reproducible example code

```text
I use a custom install of Boost 1.71.0 with CMake 3.12.1 on a system (CentOS7) with Boost < 1.51. The custom Boost is found during CMake but the system library is included during make.
```

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by henryiii** [comment]
That is correct, it is supposed to match the line below.
