### ISSUE TITLE
FindPythonLibsNew fails to find library on Travis

### ISSUE THREAD

**Issue by dvirtz** [pybind/pybind11#516]
I'm using pybind11 to embed python in cpp, but the FindPythonLibsNew module set `PYTHON_LIBRARIES` to `python3.5m` instead of the correct `/opt/python/3.5.2/lib/python3.5/config-3.5m/libpython3.5m.a`,
so my test fails to link.

see [failed Travis build](https://travis-ci.org/dvirtz/pybind11-test/jobs/177503907).

**Comment by wjakob** [comment]
I don't think we actually support linking with static python libraries

**Comment by wjakob** [comment]
(and the embedding python in cpp part is not supported here either)

**Comment by dvirtz** [comment]
That's a shame, cause it works great for me locally.
Would you accept a PR if it fixes the issue for me?

**Comment by wjakob** [comment]
It's impossible to promise in advance -- why don't you submit your PR, and then we can take a look?
