### ISSUE TITLE
TypeError to show invoked types if possible

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#517]
It is really frustrating at times that `TypeError` shows the _types_ of the function arguments it accepts but prints the _values_ for the types that it actually got. If the print of the value does not contain the type it is hard to diagnose the exact problem.
If it is in any way possible to print the types of the arguments it got instead, I believe it would be very helpful.

**Comment by jagerman** [comment]
Good idea!  See #518 for a proposed fix (take a look at the diffs for the files in `tests` to see an example of the new output).

**Comment by pschella** [comment]
That looks very nice!
I'm however not entirely sure if the values are actually needed for this error. I guess it depends on which problem you are trying to diagnose. Most of the time in our case that is "which overload have I forgotten to add?" and so the types are all you need, and the values are a potential distraction (that may take up a lot of screen space if their `__str__` spits out lots). But I'm sure that is not the same for everyone.
