### ISSUE TITLE
[BUG]:  token pasting of ',' and __VA_ARGS__ is a GNU extension / pedantic warnings

### ISSUE THREAD

**Issue by N-Wouda** [pybind/pybind11#5310]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.13.3

### Problem description

The most recent release uses `, ##__VA_ARGS__` in `common.h`. This is not technically in the standard (see e.g. [here](https://en.cppreference.com/w/cpp/preprocessor/replace#.23_and_.23.23_operators)), but most compilers support it. Clang, however, complains about its use when setting `-Wpedantic`. I can work around this by either not passing `-Wpedantic`, or passing `-Wno-gnu-zero-variadic-macro-arguments`, but I'd rather not do that if it can at all be avoided.

Consider the attached example, `test.cpp`. Compiling it with 
```shell
clang -Wall -Wextra -Wpedantic -Werror -shared -std=c++20 -fPIC $(python -m pybind11 --includes) test.cpp -o test.so
```
produces the following:
```shell
In file included from test.cpp:1:
In file included from .venv/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:13:
In file included from .venv/lib/python3.11/site-packages/pybind11/include/pybind11/detail/class.h:12:
In file included from .venv/lib/python3.11/site-packages/pybind11/include/pybind11/attr.h:13:
.venv/lib/python3.11/site-packages/pybind11/include/pybind11/detail/common.h:493:57: error: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Werror,-Wgnu-zero-variadic-macro-arguments]
            &PYBIND11_CONCAT(pybind11_module_def_, name),
  \
                                                        ^
1 error generated.
```
It concerns the following code snippet:
https://github.com/pybind/pybind11/blob/fc97cc41d575d44fa425a0e56765380e15474399/include/pybind11/detail/common.h#L493-L494

I am not sure if pybind needs to consider this a bug or even an issue. But the previous versions of pybind (2.12 and below) worked without a hitch when setting the `-Wpedantic` option, so I figured I'd let you know about this here.

### Reproducible example code

```text
#include <pybind11/pybind11.h>

int test()
{
    return 42;
}

PYBIND11_MODULE(module, m)
{
    m.def("test", &test);
}
```

### Is this a regression? Put the last known working version here if it is.

2.12.0

**Comment by henryiii** [comment]
`PYBIND11_MODULE(module, m, py::mod_gil_not_used())` would fix it, I think?

We probably should push and pop this warning, then.

**Comment by henryiii** [comment]
I don't think we can fully hide the warning inside a macro. There are actually three cases, the others have been in the code base forever but are less common. In #5322 I've managed to get it working with the flag for C++20 mode. Before C++20, GCC's warning isn't suppressible, since it's not categorized (it's just `-Werror`), and GCC doesn't seem to be reliable about allowing it to be suppressed as `-Wpedantic`. And Clang can produce another error code here before C++20, which probably isn't in older compilers, so I think supporting C++20 for pedantic is probably fine.

**Comment by N-Wouda** [comment]
Thanks @henryiii! In my use case we compile everything in C++20 mode, so this would solve my particular issue. As you mention it is difficult to backport this to earlier C++ modes, I think supporting 20 and up should suffice for most (new) projects. In any case I'm a big fan of supporting `-Wpedantic` builds 👍.
