### ISSUE TITLE
py::args doesn't work with C++ methods?

### ISSUE THREAD

**Issue by halgari** [pybind/pybind11#535]
I have a class that looks something like this:

```
class Foo {
public:
  void __call__(py::args args);
}
```

From what I can tell the problem is that pybind11 doesn't support positional args in conjunction with `py::args`. However since this is a method it will always have a `self` positional argument before the `py::args`, is it really impossible to use `py::arg` in conjunction with a class method?

**Comment by wjakob** [comment]
This is indeed a limitation. It would be nice if we could support an arbitrary number of positional/keyword args before ``*args, **kwargs`` but this is not the case for now (mostly because I couldn't figure out how to implement it in a way that does not significantly increase complexity or slow down the default case).

**Comment by jagerman** [comment]
Maybe I'm misunderstanding, but as to a method call, isn't `*this` available inside your method?  I.e. you still have the calling (C++) object.

**Comment by wjakob** [comment]
Binding ``__call__`` won't work with the automatic approach since there is an implied ``this`` argument before ``py::args``. It's definitely possible with a lambda function that only takes ``py::args``, from which the lambda function then extracts ``this``, but this is more work and less elegant.

**Comment by halgari** [comment]
Extracting the `this` pointer worked fine for my case. Thanks for answering my questions

**Comment by williamfgc** [comment]
@halgari how do you extract the "this" pointer? I am coming from boost python where I make the member function static and extract the "self" object so the Python user will treat it as any member function acting on the instance. I want to add support for pybind11 to my project and I am stuck here (this works with boost::python::extract) : 
`class Foo {
  public:
      static boost::python::object call( boost::python::tuple args, boost::python::dict kwargs )
      { 
          Foo& self = boost::python::extract<Foo&>( args[0] );
          //do things with the rest of args and kwargs
          return args[0];
      }`

I can't get this to work with pybind11, I get compiler errors with reinterpret_cast or any variant of pybind11 cast. Any options?

**Comment by jagerman** [comment]
The limitation on `py::args`/`py::kwargs` being the only arguments doesn't apply anymore (in current master/the upcoming 2.1 release): they have to be last, but other arguments can come before them.

As for extracting it, `py::cast<Foo &>(args[0])` (or `Foo *` if you prefer a pointer) should work.

**Comment by williamfgc** [comment]
@jagerman Thanks for your quick response.  I still have trouble getting the "this" pointer, from wjakib comment (two entries above my original post): "Binding __call__ won't work with the automatic approach since there is an implied this argument before py::args". My question is to how I get that this pointer, since in pybind11 is before args....in boost::python is args[0]. Thanks in advance!

**Comment by jagerman** [comment]
It's possible I'm not understanding what you're trying to do, but see if this example helps you:

```C++
struct Test {
    Test(int v) : value{v} {}
    int value;
};

PYBIND11_PLUGIN(mytest) {
    py::module m("mytest");

    py::class_<Test>(m, "Test")
        .def(py::init<int>())
        .def_readwrite("value", &Test::value)
        .def_static("static_func_pre21", [](py::args args) {
            Test &object = py::cast<Test &>(args[0]);
            return object.value;
        })
        .def_static("static_func_new", [](Test &object, py::args more) {
            return object.value;
        })
        .def("nonstatic_method", [](Test &self, py::args more) {
            return self.value;
        })
        ;

    return m.ptr();
}
```

Python:
```Python
>>> from mytest import Test
>>> z = Test(34)
>>> z.value
34
>>> Test.static_func_pre21(z)
34
>>> Test.static_func_new(z)
34
>>> z.static_func_pre21(z)
34
>>> z.static_func_new(z)
34
>>> z.nonstatic_method()
34
```

**Comment by jagerman** [comment]
For a pybind11 pre-2.1 workaround, you'd need to use:
```C++
        .def("nonstatic_method_pre21", [](py::args args) {
            Test &self = py::cast<Test &>(args[0]);
            return self.value;
        })
```
but that's arguably a bug (fixed in master/2.1).

**Comment by williamfgc** [comment]
@jagerman thanks for the detailed examples. What I need is described here: http://stackoverflow.com/questions/27488096/boost-python-raw-function-method  In boost python a raw function (any number of arguments) is combined with a static function that carries "self" in args[0], to give the impression in Python that it's a similar call to a "non-static" member function. I tried this below

`struct Test {
    Test(int v) : value{v} {}
    int value;
   **void SetParameters( py::args args, py::dict kargs ){  ///do things with args and kargs }**
};

PYBIND11_PLUGIN(mytest) {
    py::module m("mytest");

    py::class_<Test>(m, "Test")
        .def(py::init<int>())
        .def_readwrite("value", &Test::value)
        .def_static("static_func_pre21", [](py::args args) {
            Test &object = py::cast<Test &>(args[0]);
            return object.value;
        })
        .def_static("static_func_new", [](Test &object, py::args more) {
            return object.value;
        })
        .def("nonstatic_method", [](Test &self, py::args more) {
            return self.value;
        })
        .def("member_function", &SetParameters )
        ;

    return m.ptr();
}

In Python:
>>> from mytest import Test
>>> z = Test(34)
>>> z.SetParameters( '34', param1='value1', param2='value2', param3='value3')
`

**Comment by williamfgc** [comment]
When following your last "member_function" example:
`void SetParameters( Test& test, py::args args, py::dict kargs ){  ///do things with args and kargs }`

I get: `TypeError: SetParameters(): incompatible function arguments. The following argument types are supported:
    1. (self: mytest.Test, arg0: tuple, arg1: dict) -> None
`

**Comment by jagerman** [comment]
Is that with 2.0?  I think you're going to need 2.1 to get `py::args` working reliably with instance methods.  (My workaround above requires a lambda function, specifically; it won't work for a regular instance method reference).

**Comment by williamfgc** [comment]
I see, that explains the issue. I played with master, stable and v2.0 branches with no luck....I appreciate the template-only nature of the library so I can play around easily.  I will try your lambda workaround.

**Comment by jagerman** [comment]
If this is an instance method, why do you need to take the object as the first argument?  Can't you just use `this`?

**Comment by williamfgc** [comment]
I get the same error we trying to use this:
`Test.SetParameters( max_buffer_size = '10000000' )
TypeError: SetParameters(): incompatible function arguments. The following argument types are supported:
    1. (self: mytest.Test, arg0: tuple, arg1: dict) -> None
`

**Comment by jagerman** [comment]
You appear to be calling an instance method on a class rather than an instance.

**Comment by williamfgc** [comment]
The need for taking the object as first argument is coming from the boost python workaround.....raw functions (any number of arguments, not only list and dict but more like variadic templates)  only work with static and regular functions, not with member functions (as you explained it might be the same case with pybind11 as you have a lambda workaround).  I tried both approaches static + instance from arg[0] and member function. Still to try your lambda approach.   I am just trying to mimic a variadic template member function.

**Comment by jagerman** [comment]
On current master, `py::args` and/or `py::kwargs` should work for both regular functions and member functions.  You can also (again requiring current master) specify positional arguments before the `py::args`/`py::kwargs` arguments.

**Comment by williamfgc** [comment]
`namespace py = boost::python;

class MyObject {
public:
    MyObject(){ }
    ....
    static py::object foo(py::tuple args, py::dict kwargs)
    {
        MyObject& self = py::extract<MyObject&>(args[0]);
        // Do stuff with the self object
    }
};

py::class_<MyObject>("MyObject")
    .def("foo", py::raw_function(&MyObject::foo, 1));`

In Python it looks like a regular member function:
`>>> object = MyObject()
>>> object.foo( 'one', 'two', param1='var1', param2='var2')`

**Comment by williamfgc** [comment]
Can you point me to a working example?  I tried with master and I don't know what I am doing wrong

**Comment by jagerman** [comment]
mytest.cpp:
```C++
#include <pybind11/pybind11.h>

namespace py = pybind11;

struct Test {
    Test(int v) : value{v} {}
    int m2(py::args args, py::kwargs kwargs) {
        return 100 * value + 10 * py::cast<int>(args[0]) + py::cast<int>(kwargs["foo"]);
    }
    int value;
};

PYBIND11_PLUGIN(mytest) {
    py::module m("mytest");

    py::class_<Test>(m, "Test")
        .def(py::init<int>())
        .def_readwrite("value", &Test::value)
        // Instance method via lambda function:
        .def("m1", [](Test &self, py::args args, py::kwargs kwargs) {
            return 100 * self.value + 10 * py::cast<int>(args[0]) + py::cast<int>(kwargs["foo"]);
        })
        .def("m2", &Test::m2)
        ;

    return m.ptr();
}
```

Python:
```Python
>>> from mytest import Test
>>> z = Test(1)
>>> z.m1(2, foo=3)
123
>>> z.m2(5, foo=9)
159
```

**Comment by williamfgc** [comment]
OK, I feel really stupid right now. I think the problem is that in boost python args and kwargs are passed as boost::python::list and boost::python::dict.......in pybind11 it's pybind11::args and pybind11:kwargs (not as pybind11::list and pybind11::dict). It worked! Thanks a lot for your help @jagerman.

**Comment by jagerman** [comment]
`args`/`kwargs` *are* tuple/dicts underneath, but they extend those with special args/kwargs argument handling, whereas a plain `tuple`/`dict` would accept a literal tuple and dict argument from python.
