### ISSUE TITLE
Allocating new C++ objects to be returned to Python

### ISSUE THREAD

**Issue by halgari** [pybind/pybind11#536]
I've read the docs from one end to the other, and most of the tests and code, and I can't seem to find the best way to create a new instance of a C++ Object from within C++, if I want that object to be seen as a `py::object`.

```
class Foo {
public:
 Foo() {};
}


py::class_<Foo>(m, "Foo").def(py::init());

// What I want to do:

py::object foo = new Foo();


// What works but seems to be a bit of a hack:

py::class_<Foo>FooObj(m, "Foo");
FooObj.def(py::init())

py::object foo = FooObj();


```

Is this really the correct way to create new instances of a C++ object and convert them to a `py::object`? I wouldn't mind adding some info to the docs of someone can help me figure out the correct answer to this question.

**Comment by jagerman** [comment]
Take a look at the [Casting back and forth](http://pybind11.readthedocs.io/en/latest/advanced/pycpp/object.html#casting-back-and-forth) section.

Where it has `MyClass *cls = ..;` you want the `..` to be `new Foo();`.

**Comment by wjakob** [comment]
Well, the ``py::class_`` definition still has to be run at some point, or pybind11 won't know what to do with a ``Foo*``.

**Comment by tomgwasira** [comment]
@wjakob Given the above example, how would you go about doing it correctly?
