### ISSUE TITLE
how to access C structs from Python?

### ISSUE THREAD

**Issue by FelixSchwarz** [pybind/pybind11#542]
(This is more a support-like question but I did not find a channel which is more appropriate for that. If I missed something please let me know.)

Say I have some lovely C structs in my library.

    typedef struct {
        uint32_t x;
        uint32_t y;
    } SimpleStruct;

Is there a way to map these to a Python object so I can access x and y without creating a custom C++ class and map that one instead?

In my use case the structs are a bit more complicated (they might contain pointers to other structs) so I guess I'll need a C++ class anyway but I wanted to ask before spending too much time going the wrong way.

**Comment by jagerman** [comment]
A struct and class are the same thing in C++, so you should be able to directly bind your structs without needing to add another layer on top of them.

**Comment by jagerman** [comment]
(The only difference is syntactic: `struct`s default to public, while `class` defaults to private. Using the `class` keyword for actually classes is basically just convention)

**Comment by FelixSchwarz** [comment]
Of course your are entirely correct and the documentation also mention this in a way: https://pybind11.readthedocs.io/en/latest/classes.html#creating-bindings-for-a-custom-type

Not sure why I overlooked it.

**Comment by soundarsurya** [comment]
Hi @FelixSchwarz

Have you implemented this case? _In my use case the structs are a bit more complicated (they might contain pointers to other structs) so I guess I'll need a C++ class anyway but I wanted to ask before spending too much time going the wrong way._ 

My case also same...

I want to pass structure pointer
### api.cpp: 
int expose_init**(const input_struct* config_measure)**{
    return operate_nm::init(config_measure);
}

### My header.hpp file
typedef enum {
    E_CALCULATOR = 0,
    E_MEAUREMENTS
} option;

typedef struct {
    float number1;
    float number2;
}values;

typedef struct {
    option *option_enum;
    values *inp_lw;
}input_struct;

### Py_wrapper.cpp
#include <pybind11/pybind11.h>
namespace py = pybind11;
PYBIND11_MODULE(apiWrapper, module){
    module.doc() = "This is py wrapper for exposed APIs";
    py::class_<input_struct>(module, "input_struct")
    .def(py::init())
    _.def("pyValues", &input_struct::values)
    .def("pyOption", &input_struct::option)
    module.def("pyInit", &expose_init, "Init function");_
    module.def("PyOperation", &expose_operation, "Operation function");
}

kindly help to build wrapper for my case

**Comment by FelixSchwarz** [comment]
@soundarsurya Sorry, I worked on this more than 5 years ago and I don't remember anymore what I did exactly. I just know that I was able to solve the issue using pybind11 in the end. Probably it is best if you open a separate issue as the answers here refer to a state in 2016 and the approach might be different in 2022 due to C++/pybind11 changes.

**Comment by soundarsurya** [comment]
Thanks, @FelixSchwarz 

created new thread [https://github.com/pybind/pybind11/discussions/4036](url)
