### ISSUE TITLE
Segfault with shared_ptr holder and def_readwrite

### ISSUE THREAD

**Issue by bennybp** [pybind/pybind11#543]
The following MWE produces a segfault. This isn't compiler or optimization specific. The segfault goes away if the holder type is removed from TestA. Valgrind shows that it is an invalid delete/free.

CPP file:

    #include <pybind11/pybind11.h>
    #include <iostream>
    #include <memory>

    PYBIND11_DECLARE_HOLDER_TYPE(T__,std::shared_ptr<T__>)

    struct TestA{
        TestA() = default;
        int x;
    };

    struct TestB{
        TestB() = default;
        TestA myA;
    };

    PYBIND11_PLUGIN(mwe) {
        pybind11::module m("mwe");

        pybind11::class_<TestA, std::shared_ptr<TestA>>(m,"TestA")
        .def(pybind11::init<>())
        .def_readwrite("x",&TestA::x)
        ;

        pybind11::class_<TestB>(m,"TestB")
        .def(pybind11::init<>())
        .def_readwrite("myA",&TestB::myA);

        return m.ptr();
    }

Python script:

    from mwe import *

    a = TestA()
    a.x = 2
    b = TestB()
    b.myA = a
    print(b.myA)

git bisect shows the error introduced with commit bd560acf401596136b98a4540c2454ad07a99e9e

I'm thinking that when constructing from another holder, it shouldn't be owned by the new object?

**Comment by dean0x7d** [comment]
This should be fixed in PR #533 which is pending a small revision -- I will address this shortly.

**Comment by jagerman** [comment]
(I just verified that it is indeed fixed by #533).

**Comment by bennybp** [comment]
This does seem fixed now that it has been merged. Thanks!
