### ISSUE TITLE
accessing/modifying C++ "arrays" from Python

### ISSUE THREAD

**Issue by FelixSchwarz** [pybind/pybind11#546]
(Again a support-like question which probably roots in my rusty C/C++)

What is the most elegant way to access C-like "arrays" via pybind11?

For example there are two structs:

    typedef struct {
        int x;
        int y;
    } Point;

    typedef struct {
        Point* points;
        unsigned int size;
    } Path;

In C the user might do something like:

    Point points[2];
    Path path;
    path.size = 2;
    path.points = points;

Now I try to come up with an elegant way of wrapping this in pybind without too many custom getter/setter functions.

Ideally I would like a Python API like this:

    path = cmod.Path()
    path.points = [Point(), Point()]
    # maybe also path.size = 2

However a simple 

        .def_readwrite("points", &Path::points)

won't work. Is there a better way than doing the copying myself in a helper function?

**Comment by edmBernard** [comment]
@FelixSchwarz can't you overload = operator ?

**Comment by edmBernard** [comment]
the problem here is from python.
in your case `path.points = [Point(), Point()]` 
the type of `path.points` is unknow
maybe you can overload operator += but you need to initialize path.points in Path type

**Comment by wjakob** [comment]
Pybind11 will help you with standard structures that it understands, like ``std::vector``. For more "manual" C array & size-type data structures, you will have to use one of the ``def_property*`` constructors and implement getters/setters that accept and return a data structure that pybind11 can translate to a ``list``, e.g. ``std::vector<Point>`` (i.e. copying is involved).
