### ISSUE TITLE
Allow proper Cmake installation

### ISSUE THREAD

**Issue by KerstinKeller** [pybind/pybind11#549]
Hi,

I am new to bybind11, it seams great so far! But I have one question about actually installing pybind11 with cmake instead of adding it as a `add_subdirectory(pybind11)`.

The goal for me is to once install pybind11 and then use it from anywhere on my system by simply adding:

    find_package(pybind11 REQUIRED)
    pybind11_add_module(something.cpp)

From reading the CMakeLists.txt file, this is not possible at the moment.
If the option `PYBIND11_INSTALL` is set, then all headers are installed to `include/pybind11`. While this is part of the solution, shouldn't also the functions `pybind11_add_module` and `pybind11_enable_warnings` be installed too?

This would require to move them to a different file (e.g. pybind11Functions.cmake) and also create a bybind11Config.cmake file, which is installed, too. It sets `PYBIND11_INCLUDE_DIR` and includes pybind11Functions.cmake.

What do you think about this issue?

**Comment by dean0x7d** [comment]
Work on this is currently in progress in PR #506. As far as I can see, it covers your proposal, except for `pybind11_enable_warnings` which is not exported. Take a look at that PR and see if it covers your use case.

**Comment by KerstinKeller** [comment]
Ah, yes this is exactly what I had in mind. I only looked at current issues, but not at pull request, so I guess this issue can be closed.
