### ISSUE TITLE
MacOsX - Multiple Modules - Release Build

### ISSUE THREAD

**Issue by sjunges** [pybind/pybind11#550]
Using MacOs with AppleClang, under Release mode, multiple modules do not to work (Type not found errors) when constructed via CMake.
While we have not yet constructed a minimal working example, we could trace it back, and
as far as we can tell, guarding the -fvisibility=hidden statement in CMakeLists.txt (line 111) resolves the issue:

```
if(NOT APPLE)
       # Default symbol visibility
        target_compile_options(${target_name} PRIVATE "-fvisibility=hidden")
endif()
```

I would happily do some additional experiments if that is of any interest.

**Comment by wjakob** [comment]
Hi @sjunges,

keeping the default symbol visibility hidden is important to create extension modules with a small footprint.

The next step then is to set the symbol visibility of types that are shared across modules explicitly using ``__attribute__ ((visibility ("default")))`` on Linux/OSX and ``__declspec(dllexport)`` / ``__declspec(dllimport)`` on Windows. This sort of thing is good practice in any case to get the right symbol behavior across various platforms.

Wenzel
