### ISSUE TITLE
Link to Pybind11 code generator (Binder)

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#553]
Dear Pybind11 developers, 

I wrote binding code generator that uses Pybind11 and we recently released it under MIT license. Will it be possible to link it from Pybind11 docs? 

Thanks,

Sergey.

https://github.com/RosettaCommons/binder 

**Core features**
Automatically determent which types/functions could be bound and generate bindings for the following C++ code:

- functions
- enums
- C++ classes and struct’s, including:
  - read/write access to public data members, including static data members
  - class member functions including static functions
  - class inner enums
  - class operators

- automatically determent which template classes should be instantiated and generate bindings for it
- generate single shared library which on Python-import act as collection of Python modules  
- representing hierarchy of C++ namespaces
- generated bindings for both Python-2.6+ and Python-3+

**Comment by wjakob** [comment]
Hi Sergey,

would you be willing to expand the documentation a bit? I think that the compilation guide is reasonably self-complete, but the example section could be written with a focus on a concrete source code example.

(Right now I would be a big scared to try it without further docs)

Thanks,
Wenzel

**Comment by lyskov** [comment]
Sure! What examples do you have in mind? Examples for code that will be generated (i think self-tests might be helpful: https://github.com/RosettaCommons/binder/tree/master/test) or do you mean examples of general usage? If later: a few of our students working on this right now so i should have something soon...

**Comment by wjakob** [comment]
I guess it could start with something super-basic analogous to the pybind11 add-two-numbers example and then build up some classes. It would also be interesting to explain what code actually gets generated as a result.

**Comment by wjakob** [comment]
I've put a link to binder in the docs and will close the issue. However, I think the ``binder`` documentation still remains a bit sparse given its size (just counting lines of code, it's almost as large as the core parts of pybind11, but the documentation is much much shorter). It would be nice if you could ask your students to provide a few more hands-on examples.

**Comment by lyskov** [comment]
Great, thank you Wenzel! I agree that current `Binder` documentation is lacking and we working on fixing this.
