### ISSUE TITLE
Massive memory increase under Python 3.6

### ISSUE THREAD

**Issue by jagerman** [pybind/pybind11#558]
Compiling current master under python 3.5 gives a reasonable memory use:

```
$ make -j4 && /usr/bin/time -v make pytest
... (regular test output, everything passes) ...
	Command being timed: "make pytest"
	User time (seconds): 1.30
	System time (seconds): 0.04
	Percent of CPU this job got: 117%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.14
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 43220
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 14910
	Voluntary context switches: 45
	Involuntary context switches: 185
	Swaps: 0
	File system inputs: 0
	File system outputs: 272
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

Under python 3.6 rc1, with the same compiler (g++ 6.2.1) memory usage explodes (this is built without numpy/scipy support and thus also skips all the tests, which *are* run above):
```
$ make -j4 && /usr/bin/time -v make pytest
... (regular test output, everything passes or is skipped) ...
	Command being timed: "make pytest"
	User time (seconds): 1.23
	System time (seconds): 1.13
	Percent of CPU this job got: 98%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.41
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 4316736
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 1445509
	Voluntary context switches: 40
	Involuntary context switches: 268
	Swaps: 0
	File system inputs: 0
	File system outputs: 272
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

Note, in particular, that the Maximum RSS has increased from around 43MB to 4.3GB.  If I install numpy/scipy and run those tests, my 16GB of RAM isn't enough to run the tests.

I suspect this is http://bugs.python.org/issue28147.  Worryingly, the last comment in that bug report suggests that this *won't* be fixed for the final python 3.6.0.

**Comment by jagerman** [comment]
With python 3.6 rebuilt with the patch from that bug report applied:

```
	Maximum resident set size (kbytes): 30060
```

@wjakob -- perhaps you could weigh in to that bug to convince them that this is a pretty important fix?  Without it, if we can't figure out some workaround pybind11 is going to be pretty useless under the final 3.6.0 release.

**Comment by wjakob** [comment]
Ok, I just did. Thank you very much for tracking this down @jagerman.

**Comment by jagerman** [comment]
It looks like upstream is going to include this in 3.6.0 (apparently with a 3.6.0 rc2 first) thanks to the report.  We just barely caught that in time.

**Comment by wjakob** [comment]
That's just fantastic -- thank you so much for saving us (and likely many others) from a ton of troubles downstream, Jason.
