### ISSUE TITLE
py::overload_cast causes an ICE on VS2015U3

### ISSUE THREAD

**Issue by patrikhuber** [pybind/pybind11#559]
Hi!

I've got an ICE when using `py::overload_cast` on VS2015 Update 3, even though the pybind11 doc suggests that it's supposed to be working with >=U2.

If I replace [this line](https://github.com/patrikhuber/eos/blob/python-bindings/python/generate-python-bindings.cpp#L229) in my code:

`.def("draw_sample", (cv::Mat (morphablemodel::PcaModel::*)(std::vector<float>) const)&morphablemodel::PcaModel::draw_sample, "Doc.")`

with `.def("draw_sample", py::overload_cast<std::vector<float>>(&morphablemodel::PcaModel::draw_sample), "Doc.")`, it results in an internal compiler error.

I thought it might be because my type is non-trivial but just using the `float` overload of my function (without the `vector`) still produces the ICE.

I'm sorry I currently don't have time to create a MWE (beyond the open-source code of my library above that triggers it) - so feel free to just close this if you can't be bothered. I wanted to report it nonetheless, in case you're interested. I will just go back to using the manual casting, and hope that MS fixed the ICE in VS2017, I'll switch to that as soon as it comes out anyway.

Thanks & cheers :-)

**Comment by wjakob** [comment]
^ @dean0x7d

**Comment by dean0x7d** [comment]
Did you perhaps omit `py::const_`?
```c++
// original: const
(cv::Mat (morphablemodel::PcaModel::*)(std::vector<float>) const) &morphablemodel::PcaModel::draw_sample
// you said: no const
py::overload_cast<std::vector<float>>(&morphablemodel::PcaModel::draw_sample)
// should have py::const_ to match original
py::overload_cast<std::vector<float>>(&morphablemodel::PcaModel::draw_sample, py::const_)
```

This shouldn't be an ICE anyway, but asking just in case. It should yield a regular compiler error just like trying to cast a non-const function to const.

The only other thing I can think of is the namespace. Maybe try fully qualifying the function name.

I tried some things on my end, but it's been pretty well behaved in various configurations.

**Comment by patrikhuber** [comment]
@dean0x7d I did forget `py::const_`!

However, adding it doesn't make the ICE go away (and indeed the `float` overload I also tried wasn't const).

I tried with the full namespace, and also without the doc-string argument, still produces the ICE.

**Comment by dean0x7d** [comment]
I tried a few permutations, but it's not happening for me. In any case, it should be an issue with the compiler. If you have time to reduce it to a minimal example, perhaps we can pinpoint the issue and report it to MS (if it isn't fixed in VS2017 already). But for pybind11 itself, I think the issue should be closed.

**Comment by patrikhuber** [comment]
@dean0x7d Sounds good to me. If I dig into it more (probably either with VS2017RC or when the final comes out) I'll post an update here.

**Comment by wjakob** [comment]
I'll close this for now then.

**Comment by patrikhuber** [comment]
Good news: I can confirm the code works in VS2017RC and doesn't produce ICEs anymore.
(`py::overload_cast<std::vector<float>>(&morphablemodel::PcaModel::draw_sample, py::const_)`)
