### ISSUE TITLE
cannot override abstract / interface classes - v1.8.1

### ISSUE THREAD

**Issue by harryvs** [pybind/pybind11#560]
pybind11 v1.8.1 installed

I cannot get the first example in 
http://pybind11.readthedocs.io/en/latest/advanced/classes.html#overriding-virtual-functions-in-python

to work: 

VS-output:
c:\users\hvstedum\appdata\local\continuum\anaconda2\include\pybind11\pybind11.h(991): error C2259: 'Animal': cannot instantiate abstract class
3>  c:\users\hvstedum\appdata\local\continuum\anaconda2\include\pybind11\pybind11.h(991): note: due to following members:
3>  c:\users\hvstedum\appdata\local\continuum\anaconda2\include\pybind11\pybind11.h(991): note: 'std::string Animal::go(int)': is abstract
3>  D:\boxes\pyBind_sandbox\native\Animal.h(7): note: see declaration of 'Animal::go'

Now, I have a tarball of v1.8.1 somewhere on a local disk, to get to the example code of pybind11; in the last coderules of example-virtual-functions.cpp there's a line: 

py::class_<ExampleVirt, std::unique_ptr<ExampleVirt>, PyExampleVirt>(m, "ExampleVirt")

There's an extra argument, 2nd one, for the macro; when I run a Visual difference on pybind11.h for both the installed one and the one in the tarball-expansion, I see quite a few differences, mainly concerning base- and holder- types.

I tried a clean install of pybind11, and also an upgrade, to no avail; apparently, and confusingly, there are different version of v1.8.1; can anyone shed some light on this?

**Comment by wjakob** [comment]
You are following the tutorial of master (i.e. latest development repository) with an older version of pybind11. Please either follow the stable docs or also use the master version of pybind11.

There is only one version of v1.8.1, which is the one available on PyPi and on the v1.8.1 tag

**Comment by harryvs** [comment]
Thanks for the quick reply,

upon choosing ‘stable’ in the bottom-left ‘Read the Docs’, I get:

http://pybind11.readthedocs.io/en/stable/advanced/classes.html

gives a ‘Sorry, this page does not exist yet’

but, after some poking around, here it is:

https://pybind11.readthedocs.io/en/stable/advanced.html#overriding-virtual-functions-in-python

coded as described there, it builds;

sorry about the noise, keep up the good work!

Harry


ing. Harry van Stedum | Software Engineer | Maritime Simulation & Software Group
MARIN | T +31 317 49 33 11 | H.v.Stedum@marin.nl<mailto:H.v.Stedum@marin.nl> | www.marin.nl<http://www.marin.nl>

[LinkedIn]<https://www.linkedin.com/company/marin> [YouTube] <http://www.youtube.com/marinmultimedia>  [Twitter] <https://twitter.com/MARIN_nieuws>  [Facebook] <https://www.facebook.com/marin.wageningen>
MARIN news: Energy saving by using asymmetric aftbodies for merchant ships – design methodology, numerical simulation and validation<http://www.marin.nl/web/News/News-items/Energy-saving-by-using-asymmetric-aftbodies-for-merchant-ships-design-methodology-numerical-simulation-and-validation-1.htm>
