### ISSUE TITLE
Determining the type of a numpy array

### ISSUE THREAD

**Issue by patrikhuber** [pybind/pybind11#563]
Hi,

This might be pretty basic but I've searched all the docs and issues and tried lots of stuff and couldn't figure it out.

I'm writing a type-caster, and in the `bool load(handle src, bool)` method, I need to find out what the type of the numpy array is that is given (to then create a `pybind::array_t<T>` of that type).

I got pretty close, and arrived at: `const auto data_type = reinterpret_borrow<pybind11::dtype>(detail::array_proxy(src.ptr())->descr).kind();`

However this doesn't work because it returns `'f'` for both float32 as well as float64 numpy arrays, so I can't determine whether to instantiate a `array_t<float>` or `array_t<double>`. 

Any way to determine the type of the numpy array that's passed to this function from python?

Thanks!

**Comment by aldanor** [comment]
Try the `.dtype()` method?

**Comment by aldanor** [comment]
Oh, apologies, you already have a dtype. Then I don't fully understand what is it you want to accomplish :)

**Comment by patrikhuber** [comment]
Thanks for the quick reply!
I'm must trying to find out the scalar type (float, double, whatever else) of the numpy array that is passed as `handle src`?

**Comment by wjakob** [comment]
You can query the 'itemsize' to determine the difference between float and double

**Comment by patrikhuber** [comment]
Ok, so it turns out the whole `kind()` and `itemsize()` stuff is actually not necessary and it's possible to just do:

```
const auto pyarray_dtype = reinterpret_borrow<pybind11::dtype>(detail::array_proxy(src.ptr())->descr);
if (pyarray_dtype == pybind11::dtype::of<float>()) {
	// float (float32) type
} else if (pyarray_dtype == pybind11::dtype::of<double>()) {
	// double-type (float64)
}
```
That's great. It feels however like I'm overlooking something, is there really no easier way to get the dtype than `reinterpret_borrow<pybind11::dtype>(detail::array_proxy(src.ptr())->descr);`? Seems like I need to touch on quite a lot of internals here. I couldn't find a helper method or something like that for it.

Also it looks like only numpy arrays have a `descr` that is convertible to a `dtype` - if I pass a list or something from python, it crashes upon the conversion to `dtype`. How do I figure out whether what's in the `src` handle is a numpy array or not, and if it's not (for example I passed a list from python), what do I do with `descr` to get out the type and all that information I need to create an `array_t` from it?

**Comment by aldanor** [comment]
`reinterpret_borrow<py::array>(ptr)`? And you don't need all this dancing; you should be able to do this without digging in internals too much.

**Comment by patrikhuber** [comment]
@aldanor: Aaaah. I think I'm getting there - the hard way. I didn't figure out the "easy" way so I dug deeper and deeper, unnecessarily. And I got stuck a bit on `py::array_t<T>` as well and didn't use `py::array`. With all this knowledge it turns out the solution is really easy ;-)

There's one last issue, and that one smells a bit like a possible bug: I can test for any type and it works perfectly, but not for `int32` and `uint32`. 

```
auto buf = pybind11::array::ensure(src);
if (!buf) return false;
std::cout << buf.dtype() << std::endl;
if (buf.dtype() == pybind11::dtype::of<std::int32_t>()) {
    // do something...
} else if (...) {
    // another type...
} // ...
```
This works for any type I tried (float, std::uint8_t, etc.) but it just jumps over the `if` for int32/uint32 types. Using just `int` or `unsigned int` also does not work.
For example, calling this function with:
`test(np.array([1, 2, 3], dtype=numpy.int32))`
prints `int32` to the console, which means the dtype is actually int32, but then the comparison in the `if` is false for any integer type that I tried.

This is under VS2015U3, x64, and python-3.5.2 64bit.

**Comment by patrikhuber** [comment]
MWE:

```
#include "pybind11/pybind11.h"
#include "pybind11/numpy.h"
#include "pybind11/stl.h"
#include <iostream>

class Test {};
void test(Test t) {};

NAMESPACE_BEGIN(pybind11)
NAMESPACE_BEGIN(detail)
template<>
struct type_caster<Test>
{
	bool load(handle src, bool)
	{
		auto buf = pybind11::array::ensure(src);
		if (!buf)
			return false;

		std::cout << buf.dtype() << std::endl;
		if (buf.dtype() == pybind11::dtype::of<std::int32_t>())
		{
			std::cout << "Match" << std::endl;
		}
		else {
			std::cout << "No match" << std::endl;
			return false;
		}
		return true;
	};

	static handle cast(const Test& src, return_value_policy /* policy */, handle /* parent */)
	{
		throw std::runtime_error("Not implemented.");
	};

	PYBIND11_TYPE_CASTER(Test, _("Test"));
};
NAMESPACE_END(detail)
NAMESPACE_END(pybind11)

PYBIND11_PLUGIN(eos) {
	pybind11::module m("eos", "Doc");
	m.def("test", &test);
    return m.ptr();
};
```

Calling it from Python:

`eos.test(np.array([1, 2, 3], dtype=np.int32))`

prints `int32` `No match`. Trying it with any other `int` type doesn't match either. Trying it with all other types (e.g. float32, uint8, etc.) works as expected.

**Comment by dean0x7d** [comment]
Try replacing
```c++
buf.dtype() == pybind11::dtype::of<std::int32_t>()
```
with 
```c++
py::isinstance<py::array_t<std::int32_t>>(buf)
```

**Comment by patrikhuber** [comment]
@dean0x7d This works. Do you have an explanation for it? Is the way I was doing it wrong? And why does it only fail for int32?

**Comment by dean0x7d** [comment]
`operator==` for pytypes just compares pointers -- it's equivalent to the `is` operator in Python (e.g. `obj1 is obj2`). But there can be two identical objects at different addresses which would return `false`. On the other hand, `isinstance<py::array_t<T>>` internally uses `PyArray_EquivTypes` which actually checks that the type objects are equivalent.

**Comment by patrikhuber** [comment]
Wow, so it was pure coincidence that it worked in all other cases. Even on different machines. That's kind of terrifying. 
Thank you to all of you for the quick help!

(To all the curious, I was writing a type-caster for [transparent conversions for OpenCV's `cv::Mat`](https://github.com/patrikhuber/eos/blob/devel/python/pybind11_opencv.hpp#L136) type. It works great now, and much simpler than before thanks to @aldanor which got me back on the right track :-))
