### ISSUE TITLE
How to relate a template name associated with class to a kwarg in Python ?

### ISSUE THREAD

**Issue by karandesai-96** [pybind/pybind11#564]
Say I have a class in C++:

```C++
template<typename T>
class Foo() {
public:
    // body
    T var1;
}
```
where T can be possibly about 50 different classes declared elsewhere (named `C1`, C2`, C3` ... `C50`).

Do I have to make 50 different Python classes ? It would be really convenient to have a Python API such as:
```python
foo = Foo(t='c23')   # specifying names as strings
```
Is there a way like this / similar to this ? I cannot afford to make one class for each template type.

**Comment by wjakob** [comment]
Sorry, there is no way to do this. A template does not generate any code by itself -- you explicitly have to instantiate to ensure that the code is there. On the other hand, Python can't go and call the C++ compiler on demand to generate another implementation. That is why you have to call ``class_`` many times (though you can of course use templates on your end as well to facilitate this)

**Comment by karandesai-96** [comment]
@wjakob thanks for the A2A :smile:
