### ISSUE TITLE
cmake policy CMP0048

### ISSUE THREAD

**Issue by rwols** [pybind/pybind11#567]
I have pybind11 included in my cmake project via `add_subdirectory(pybind11)`, which works great. At configure time I get this warning:

```
CMake Warning (dev) at lib/pybind11/CMakeLists.txt:10 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
```

I don't see the `PROJECT_VERSION` and friends variables used anywhere in the CMakeLists file, so a simple fix would be to add the line `cmake_policy(SET CMP0048 NEW)` after the `cmake_minimum_required(...)` line (or, set the minimum cmake version required to be 3).

**Comment by wjakob** [comment]
Hi @rwols,

to clarify: what version of cmake are you using, and on what OS? What generator are you using? (e.g. Visual studio, Ninja, makefiles, etc.). I'd like to be able to reproduce the issue before applying any changes.

Wenzel

**Comment by rwols** [comment]
Hi @wjakob,

My CMake version is 3.5.1 on my Ubuntu machine, and 3.7.0 on my OSX laptop. The warning occurs on both machines, no matter which generator I choose.
I've gathered the steps to reproduce this with a minimal project, here goes:

```
$ mkdir pybind11-test
$ cd pybind11-test
$ git init
$ git submodule add https://github.com/pybind/pybind11.git
```

Make a CMakeLists.txt file with the following contents:
```
cmake_minimum_required(VERSION 3.0)
project(hello VERSION 0.1 LANGUAGES C CXX)
add_subdirectory(pybind11)
```

Then attempting to configure this project I get the warning above.

**Comment by jagerman** [comment]
It seems to be the implicit `CMP0048 = NEW` set by the `cmake_minimum_required(VERSION 3.0)` in the top-level CMakeLists.txt: that then triggers a warning for included project() commands.  #570 fixes it.
