### ISSUE TITLE
Please help, passing STL structures into py::arg.

### ISSUE THREAD

**Issue by neumond** [pybind/pybind11#568]
I have following snippet of code, which successfully compiles, but causes `arg(): could not convert default keyword argument into a Python object (type not registered yet?)`.
```
.def("build", [](Unitset& instance, UnitType type, Pybrood::UniversalPosition target) -> bool {
   return instance.build(type, TilePosition(target[0], target[1]));
}, py::arg("type"), py::arg("target") = py::cast(Pybrood::TilePositions::None))
```
No matter what I try here: `Pybrood::TilePositions::None`, `py::cast(Pybrood::TilePositions::None)`, `std::array<int, 2>(Pybrood::TilePositions::None)`, result is the same: compiles then fails in runtime.

`Pybrood::TilePositions::None` is `std::array<int, 2>` constant derived from another constant, not defined by me. That's why I want to preserve it as is.
```
typedef std::array<int, 2> UniversalPosition;
const UniversalPosition None = convert_position<BWAPI::TilePosition>(BWAPI::TilePositions::None);
```
I'm trying to replace custom position classes with simple std::array to get/pass python tuples "out of the box". I suspect this problem hides in some typeid magic, which doesn't allow typedef'ed things to be considered 'registered' without manual registering from scratch.

Please excuse my very shallow knowledge of C++ :fearful: How better could I deal with this problem?

**Comment by wjakob** [comment]
Did you include the header file ``pybind11/stl.h``?

**Comment by neumond** [comment]
Oh.. I've spent severals hours trying to make this work, it was so easy, just include additional header. Now it can be described as originally intended `py::arg("target") = Pybrood::TilePositions::None`. Thank you!!
