### ISSUE TITLE
Backporting eval

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [pybind/pybind11#569]
I am now facing the problem that I need to create some Python object instances from C++. As such, I could really use `py::eval`.

Now, before I move that into our repo I was wondering whether it would make sense to backport `py::eval` to 1.8 and perhaps then make a 1.8.2 on the long run?

BTW, is there any reason why there hasn't been a release in half a year, while 1.9 seems to get quite huge?

**Comment by wjakob** [comment]
FYI: v2.0.0-rc1 just went out, and v2.0.0 will be released very soon (beginning of January). I'd be happy to entertain a backported py::eval for a potential v1.8.2 but would ask you to do the PR, port the testcases, etc.
