### ISSUE TITLE
Where to get help with pybind11?

### ISSUE THREAD

**Issue by smontanaro** [pybind/pybind11#574]
Wenzel,

I realize you are just a solo person developing and maintaining pybind11. Where should I go for help? I saw nothing in the README or CONTRIBUTING which suggested the correct/best place. I suppose in the absence of any direction I could assume stackoverflow.com, but that's not always the most friendly place for novices. Besides, you know what Uncle Timmy always said:

  * explicit is better than implicit
  * in the face of ambiguity, refuse the temptation to guess

:-)

Caveat: Before you suggest I send usage questions to you or open issues on GitHub, note that I am a Python person, not a C++ person, so there will be some pretty basic stuff which others could just as easily answer as you. If there are plenty of users monitoring GitHub, then that might be fine, but I don't want to rely on you as a very limited resource for help.

**Comment by wjakob** [comment]
Actually lots of bright folks are helping out, I'm just the one who maintains this repo. Regarding more informal communication, see https://gitter.im/pybind/Lobby. Obviously you should still take a good look at the documentation before asking questions. ;)
