### ISSUE TITLE
Converting variant types

### ISSUE THREAD

**Issue by MathMagique** [pybind/pybind11#576]
Hey there! I am in the middle of replacing Boost.Python with pybind11 in my project and stumbled on this situation:

I have a C++ class with an instance field of type `boost::variant<A, B>`, where `A` and `B` are simple types that I have already exposed to python with `pybind11::_class` as `pyA` and `pyB`, respectively. `boost::variant` is basically a safe `union` type, i.e., it represents a single value that is guaranteed to be either `A` or `B`.

My question is: What is the recommended way to convert `boost::variant<A, B>` to `pyA` or `pyB` (as appropriate given the variant's concrete value)? How can I make sure that both `pyA` and `pyB` can be converted to `boost::variant<A, B>`?

The documentation points me towards using a custom `type_caster<boost::variant<A, B>>`, but it seems I would have to decide for _one_ corresponding Python type to translate to/from.

Any help is much appreciated.

**Comment by dean0x7d** [comment]
I've been using the following generic variant caster. I mainly wrote it for my own use with `mapbox::variant`, but the variant type comes in as a template parameter and `boost::variant` has the same interface, so you should be able to use it mostly as is.

```c++
namespace pybind11 { namespace detail {

// Can be replaced by a generic lambda in C++14
struct variant_caster_visitor {
    return_value_policy policy;
    handle parent;

    template<class T>
    handle operator()(T const& src) const {
        return make_caster<T>::cast(src, policy, parent);
    }
};

template<class Variant> struct variant_caster;

template<template<class...> class V, class... Ts>
struct variant_caster<V<Ts...>> {
    using Type = V<Ts...>;

    template<class T>
    bool try_load(handle src, bool convert) {
        auto caster = make_caster<T>();
        if (caster.load(src, convert)) {
            value = cast_op<T>(caster);
            return true;
        }
        return false;
    }

    bool load(handle src, bool convert) {
        auto loaded = {false, try_load<Ts>(src, convert)...};
        return std::any_of(loaded.begin(), loaded.end(), [](bool b) { return b; });
    }

    static handle cast(Type const& src, return_value_policy policy, handle parent) {
        // If you see an error here, add `boost::` qualifier to `apply_visitor`
        return apply_visitor(variant_caster_visitor{policy, parent}, src);
    }

    PYBIND11_TYPE_CASTER(Type, _("Variant"));
};

// Add specialization for concrete variant type
template<class... Args> struct type_caster<boost::variant<Args...>>
    : variant_caster<boost::variant<Args...>> {};

}} // namespace pybind11::detail
```

Some notes:

* This works quite well for me, but it has not been extensively tested.
* Should work with any variant as long as its types are exposed to Python via `py::class_` or have their own type casters. But recursive variants are not covered (`recursive_wrapper<T>`).
* It converts to/from any type on both sides.

**Comment by MathMagique** [comment]
@dean0x7d Thanks a lot for your code snippet! With slight adjustments, it works like a charm. A few notes regarding the usage that may be helpful for other folks trying to migrate their code:

* For the Python -> C++ direction, a member variable `value` is used. It is implicitly created when using the `PYBIND11_TYPE_CASTER` macro. It assumes `Type` to be default-constructible. `boost::variant` is not always default constructible, but it is when its first component type is. I had to add a default constructor to fix this.
* The converter needs to be available in the _compilation unit_ where it would be needed. It is not sufficient to declare it in a separate C++ file, because the function that requires the conversion has no knowledge of this. This is in contrast to `boost::python` where there is a static converter registry. Not a big deal, but something to watch out for.

Thanks again!

**Comment by wjakob** [comment]
I'll close this then.
