### ISSUE TITLE
pybind11/chrono.h not found

### ISSUE THREAD

**Issue by smontanaro** [pybind/pybind11#578]
docs/advanced.rst mentions support for some STL time stuff. In particular, this table:

https://pybind11.readthedocs.io/en/master/advanced/cast/overview.html#conversion-table

refers to a pybind/chrono.h file which I can't find. Figuring that it was perhaps an artifact of the build process, I tried building (cmake 3.5.2, g++ 4.9.2), but got compilation errors.

**Comment by wjakob** [comment]
You're probably using the ``master`` documentation of pybind11, while working with the ``stable`` release.

**Comment by smontanaro** [comment]
Dunno. The zip archive I downloaded from GitHub (instead of cloning the repo) was named "pybind-master.zip". The pybind11.egg-info/PKG-INFO file reads "Version: 1.9.dev0". The Branch pulldown says "master". I do see an include/pybind11/chrono.h file.

**Comment by wjakob** [comment]
Then I don't understand the issue. The web page you linked explicitly refers to ``pybind11/chrono.h``, and the file is present in the file you downloaded.

**Comment by smontanaro** [comment]
I don't understand either. It's clearly there on GitHub, but not in the zip
file I downloaded. Sorry for the noise. I'll start over from scratch.
