### ISSUE TITLE
TypeError: Incompatible function arguments. [question with template class]

### ISSUE THREAD

**Issue by pyjiang** [pybind/pybind11#580]
```ruby

// base.hpp

#include<vector>

template <typename M,
          typename G1>
struct  popb
{
  G1 g1;
  M m;
  popb(const G1 & _g1, const M & _m): g1(_g1), m(_m){}
};

template <typename M,
          typename G1,
          typename G2>
struct pop: public popb<M,G1>
{
  G2 g2;
  pop(const G1 & _g1, const M & _m, const G2 & _g2): popb<M,G1>(_g1,_m ),g2(_g2) {}
};

template <typename M,
          typename G1,
          typename G2,
          typename E>
struct newpop: pop<M,G1,G2>
{
  E e;
  newpop(const G1 & _g1, const M & _m, const G2 & _g2, const E & _e): pop<M,G1,G2>(_g1,_m,_g2), e(_e) {}
};

using newpop_t=newpop<std::vector<int>,std::vector<int>,std::vector<int>,int>;

newpop_t create_pop();



// base.cpp

#include "base.hpp"

newpop_t create_pop()
{
  std::vector<int> m = {7, 5, 16, 8};
  std::vector<int> g1 = {19, 3, 1, 8,5,3,2,1};
  std::vector<int> g2 = {2, 3, 8,30,2,1};
  int e=10;
  newpop_t pop(g1,m,g2,e);
  return pop;
}


// interface.cpp

<%
cfg['compiler_args'] = ['-std=c++11']
cfg['sources'] = ['base.cpp']
setup_pybind11(cfg)
%>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "base.hpp"

namespace py = pybind11;

using namespace pybind11::literals;

PYBIND11_PLUGIN(interface){
  py::module m("interface", "pybind11 interface");

  m.def("create_pop",&create_pop,"create pop");

  py::class_<newpop_t>(m,"newpop_t")
    .def_readwrite("g1",&newpop_t::g1)
    .def_readwrite("g2",&newpop_t::g2);

}


```

I am trying to write an interface for c++ function in python using pybind11 and cppimport. The class in c++ are templated, and derived from parental template class. I want to call create_pop from python and get return object of class newpop_t. 

```
import cppimport
m=cppimport.imp("interface")
x=m.create_pop()
x.g1
```

When I try to access the member g1, I got error message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (popb<std::vector<int, std::allocator<int> >, std::vector<int, std::allocator<int> > >) -> list<int>
    Invoked with: <interface.newpop_t object at 0x7f72d73411b8>

I want to access the member not calling function. I'm not sure how to resolve this. Thanks a lot!!

**Comment by dean0x7d** [comment]
You can work around the issue by also registering all the bases where the data members are originally defined. For example:

```c++
using base_g1 = popb<std::vector<int>,std::vector<int>>;
py::class_<base_g1>(m, "base_g1");

py::class_<newpop_t, base_g1>(m,"newpop_t")
    .def_readwrite("g1", &newpop_t::g1);
```

And similar for `g2` and any other data members defined in base classes.

That should work for you right now, but the underlying issue might need a fix inside pybind11 (the need to also expose bases is a bit bizarre here). The following minimal code demonstrates the core issue:

```c++
#include <pybind11/pybind11.h>
namespace py = pybind11;

struct Base {
    int value = 1;
};

struct Derived : Base {};

PYBIND11_PLUGIN(issue) {
    py::module m("issue");

    py::class_<Derived>(m, "Derived")
        .def(py::init<>())
        .def_readwrite("value", &Derived::value);

    return m.ptr();
}
```

```pycon
>>> x = m.Derived()
>>> x.value
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: Base) -> int

Invoked with: <issue.Derived object at 0x109d04e10>
```

The problem is that the type of `&Derived::value` is `int Base::*` (pointer to a data member in the base) and not `int Derived::*` as might be expected. Because of this `def_readwrite` creates a getter function which expects a `Base` object, but it receives `Derived` instead. This may cause problems if the `Base` class is an implementation detail which should not be exposed in Python.

**Comment by pyjiang** [comment]
Thanks so much!! This method works for me!!
