### ISSUE TITLE
Bound checks in numpy array accessors

### ISSUE THREAD

**Issue by SylvainCorlay** [pybind/pybind11#584]
The current behavior of data access methods in `py::array` and `py::array_t` is to check the dimension bounds every time the accessor is called, via the `check_dimensions` function, event when using it in a loop.

I agree that when exposing a feature to Python, it must be written in such a way that regardless of the values passed to it, it cannot crash the interpreter, but these accessors are not directly exposed to the Python users. Instead, I think that one of the main reasons people would right c++ extensions with pybind is because they want *speed*, and they might be disappointed with this behavior. https://github.com/pybind/pybind11/pull/500 already improved the situation, but as we discussed there, I would prefer to completely remove the bound checking.

**Comment by aldanor** [comment]
Which access methods are you most interested in, do you have a minimal example? In a loop, you have unchecked version of `byte_offset`, plus you can prefetch the data pointer once before the loop starts?

**Comment by SylvainCorlay** [comment]
I think that all the access methods should be like this on the c++ side (except for `at`)  which according to the STL idoms (e.g. std::vector) is checked.

**Comment by wjakob** [comment]
Closing this since unchecked access is now provided.
