### ISSUE TITLE
Test failures on i386

### ISSUE THREAD

**Issue by ghisvail** [pybind/pybind11#586]
I have refreshed the Debian packaging to the latest release (v2.0.0). The build of the packaging succeeds on `amd64`, but fails on `i386` (see build log attached) due to a failure happening whist running the test suite. Looks like something executed in `test_pickling.py` could be the culprit.

[pybind11_2.0.0-1.buildlog.txt](https://github.com/pybind/pybind11/files/684464/pybind11_2.0.0-1.buildlog.txt)

**Comment by wjakob** [comment]
@ghisvail: I pushed out a new v2.0.1 release that addresses this issue.

**Comment by dean0x7d** [comment]
Sorry about that. It was my copy-paste error in the test. Kind of crazy that it worked at all.

**Comment by wjakob** [comment]
@ghisvail: I just wanted to check whether this will still make it into debian stable?

**Comment by ghisvail** [comment]
`2.0.1` is already uploaded, and it should transition to Stretch in a few days.

**Comment by wjakob** [comment]
That's great to hear! I assume all the tests passed now?

**Comment by ghisvail** [comment]
Yep. Thanks for the prompt fix.

**Comment by wjakob** [comment]
Looks like the packages are not in stretch at this point (https://packages.debian.org/search?keywords=pybind11&searchon=names&suite=testing&section=all). Is that normal?

**Comment by jagerman** [comment]
Yup; a new version needs to have been in `sid` for 10 days without attracting a serious bug report before automatically migrating to `testing`.  It should migrate in about 3 days or so.

**Comment by jagerman** [comment]
(It's in stretch as of a couple days ago).

**Comment by jagerman** [comment]
@ghisvail - I didn't notice this until now (which is unfortunate, given the freeze) but it looks to me like the debian package isn't installing the cmake files (which should probably be in pybind11-dev).  I think they might also need some path adjustments; the current package build leaves them in debian/tmp/usr/share/cmake/pybind11, but (at least judging from what Eigen does) I think they should go into `/usr/lib/cmake/pybind11`.

**Comment by jagerman** [comment]
(I can `reportbug` it if you think it would help justify a freeze exception.)

**Comment by ghisvail** [comment]
> it looks to me like the debian package isn't installing the cmake files

Correct. These did not exist back when I started packaging v1.8.1 and I failed to notice the change until you reported it. My bad.

> I think they should go into `/usr/lib/cmake/pybind11`

Not only that, but the CMake package stuff need to be made arch-independent. See this [example](https://bitbucket.org/eigen/eigen/src/4d09e90f07c8ac4a3da31dc0f5a782db18904679/CMakeLists.txt?at=default&fileviewer=file-view-default#CMakeLists.txt-538) in Eigen.

> I can reportbug it if you think it would help justify a freeze exception.

Please do and mark it `severity: important`.

**Comment by jagerman** [comment]
Submitted.

**Comment by jagerman** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854502
