### ISSUE TITLE
Usage of `PYBIND11_OVERLOAD*` is misleading

### ISSUE THREAD

**Issue by myd7349** [pybind/pybind11#593]
In [docs/advanced/classes.rst](https://raw.githubusercontent.com/pybind/pybind11/master/docs/advanced/classes.rst), there is an example code snippet looks like this:
```cpp
    class PyAnimal : public Animal {
    public:
        using Animal::Animal; // Inherit constructors
        std::string go(int n_times) override { PYBIND11_OVERLOAD_PURE(std::string, Animal, go, n_times); }
        std::string name() override { PYBIND11_OVERLOAD(std::string, Animal, name, ); }
    };
    class PyDog : public Dog {
    public:
        using Dog::Dog; // Inherit constructors
        std::string go(int n_times) override { PYBIND11_OVERLOAD_PURE(std::string, Dog, go, n_times); }
        std::string name() override { PYBIND11_OVERLOAD(std::string, Dog, name, ); }
        std::string bark() override { PYBIND11_OVERLOAD(std::string, Dog, bark, ); }
    };
```

Take a look at:
```cpp
PYBIND11_OVERLOAD(std::string, Animal, name, ); // (1)
```
and
```cpp
PYBIND11_OVERLOAD_PURE(std::string, Dog, go, n_times); // (2)
``` 
There is a redundant comma in (1), but not in (2).
But I didn't notice this difference when I typed these code into my IDE, so I also added a trailing comma for (2), which causes confusing compilation errors related to C++ templates.

So, I think the redundant comma in (1) is misleading. Shall we remove it?

References:
[variadic_macro_test.c](https://github.com/myd7349/Ongoing-Study/blob/master/c/C99/variadic_macro_test.c)

**Comment by jagerman** [comment]
If your compiler allows it you can omit the comma.  The issue is that not all compilers do, and so the version in the documentation should work pretty much anywhere, but leaving off the comma will cause problems with some compilers.
