### ISSUE TITLE
Requiring metaclass attribute breaks a lot of code

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#594]
I'm sorry to not have caught this earlier, but I'm really not happy with the change to require `py::metaclass()` whenever a static property is used.
For very large codebases like ours, where many many classes have static properties this causes unnecessary breakage. Is there any way this can be avoided now or in the future?

**Comment by wjakob** [comment]
No, sorry -- v2.0.0 is out, and it's too late to complain ;).

We need to break compatibility occasionally (with a corresponding increase of the major number according to semver). In this case it was necessary to do so for compatibility with PyPy.

You could implement an alternative ``py::class_<>`` wrapper that *always* passes ``py::metaclass``, though this means that some memory will be wasted.
