### ISSUE TITLE
Broken mro when using multiple inheritance with py::metaclass

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#597]
When a derived class `MroDerived` needs to expose a static attribute (which necessitates using `py::metaclass`), but also inherits from multiple bases Python raises the following error:

`ImportError: MroDerived: PyType_Ready failed (TypeError: mro() returned base with unsuitable layout ('pybind11_tests.MroBaseB'))!`

For a complete example see https://github.com/lsst-dm/pybind11/tree/broken_mro

**Comment by pschella** [comment]
This is on Python 3.5.2.

**Comment by r-owen** [comment]
I will also say that the need to add `py::metaclass` to all our code is a bit of a nuisance. I wish there was some way to offer backwards compatibility while still giving whatever benefit this adds (such as making that the default and having a way to disable it when needed). Why might one omit it?

**Comment by pschella** [comment]
While I agree with it being a nuisance, this was already ruled upon by the lead developer.
However, adding `py::metaclass` to all classes does not resolve this problem.
