### ISSUE TITLE
issue with unique_ptr ?

### ISSUE THREAD

**Issue by jkhoogland** [pybind/pybind11#608]
Hi,

I came across the following issue today which seems like a bug.

I have a class `Foo` that produces `Bar` and returns a unique_ptr to an instance of `Bar`.

On running a C++11 executable it works fine (little main in the code attached).
On running python, it craps out with 
```
RuntimeError: return_value_policy = move, but the object is neither movable nor copyable!
```
Am I missing something ? The class `Bar` is moveable, and copyable...

Code attached to reproduce.

[pybind11_issue_unique_ptr.zip](https://github.com/pybind/pybind11/files/715271/pybind11_issue_unique_ptr.zip)

**Comment by dean0x7d** [comment]
This should be fixed in PR #607. Fixing this wasn't the goal of that PR, but it does seem to be a lucky side effect.

**Comment by jkhoogland** [comment]
cool, i'll wait for it to hit master
thanks for the quick update

**Comment by jkhoogland** [comment]
Hi,
I created a [branch](https://github.com/jkhoogland/pybind11/tree/2.0.1_unique_ptr_fix) to test your changes, the initial error 
```
RuntimeError: return_value_policy = move, but the object is neither movable nor copyable!
 ```

is gone but I now see a different error popping up:

```
Failed to import pybind11_tests from pytest:
  ImportError: generic_type: cannot initialize type "Foo": an object with that name is already defined
```

I dont think that there is anything wrong in my py module declaration:
```
test_initializer unique_ptr( []( py::module& m ) {

    py::class_<FooI, std::unique_ptr<FooI>> foo( m, "FooI" );
    foo.def( "bar", &FooI::bar );

    py::class_<Foo, std::unique_ptr<Foo>>( m, "Foo", foo )
        .def( py::init<>() );

    py::class_<BarI, std::unique_ptr<BarI>> bar( m, "BarI" );
    foo.def( "bar", &BarI::bla );

    py::class_<Bar, std::unique_ptr<Bar>>( m, "Bar", bar )
        .def( py::init<int>() );

} );
```

Any thoughts ?
Regards
Jiri

**Comment by dean0x7d** [comment]
Based on
```
test_initializer unique_ptr( []( py::module& m ) { ... }
```
I'm guessing you're trying this out alongside the test of the pybind11 tests. But those already have a class called `Foo`, hence the duplicate initialization error.

**Comment by jagerman** [comment]
If that is indeed it, `cmake -DPYBIND_TEST_OVERRIDE=test_mine.cpp` can be helpful for turning off compilation of everything except for one test cpp file.  (I also use it all the time when working on one particular feature to cut down compilation/link times).

**Comment by jkhoogland** [comment]
Right, sorry about that, indeed a stupid mistake.
I also forgot to add the test code i wrote, which I submitted now to my test branch.

Having fixed that though, I do see an issue that I think is a bug:

The two classes `Foo` and `Bar` are as defined above.

Running 
```
from pybind11_tests import (Bar, Foo)

print("dir(Foo):\n",dir(Foo))
print("dir(Bar):\n",dir(Bar))

foo = Foo()
bar = foo.bar()

print(type(foo))
print(type(bar))

print(bar.bla())
```
gives some surprising output: 
```
dir(Foo):
 ['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'bar', 'bla']
dir(Bar):
 ['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
<class 'pybind11_tests.Foo'>
<class 'pybind11_tests.Bar'>
```
and then it barfs since it cannot find the method `bla` on `Bar`.
Looking at the output of `dir(Foo)` it is seen that  `pybind11` has put the method `bla` on `Foo`...

This looks like there is something going wrong in parsing the interface when wrapping the c++ code in pybind11 ?

**Comment by jagerman** [comment]
This looks suspect:
```C++
    py::class_<BarI, std::unique_ptr<BarI>> bar( m, "BarI" );
    foo.def( "bla", &BarI::bla );
```
`bla` is defined as a bound method on `Foo`, but then bound to a function of `BarI`.  Thus when pybind11 tries to dispatch `foo.bla()` it will see that `bla` has one entry with first argument type `BarI`, but you gave it a first argument of type `Foo`, so it won't match.

**Comment by jkhoogland** [comment]
ouch, sorry for that stupidity, yep, problem solved.
Thanks for your help and patience

```
dir(Foo):
 ['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'bar']
dir(Bar):
 ['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'bla']
<class 'pybind11_tests.Foo'>
<class 'pybind11_tests.Bar'>
123
```
