### ISSUE TITLE
PYBIND11_TYPE_CASTER and parameterized constructors

### ISSUE THREAD

**Issue by smontanaro** [pybind/pybind11#618]
It's not at all clear how I would create a type converter for a class which requires parameters in its constructor. I want to convert Python's date and datetime objects into internal date/datetime classes which are for this exercise, immutable. (They have overloaded operators which are meaningless to me.)

Do I have to forego direct usage of PYBIND11_TYPE_CASTER (expand it manually and tweak the result), or is there another macro I can use instead?

**Comment by smontanaro** [comment]
I think I figured this out, though what I have doesn't yet work.

**Comment by jagerman** [comment]
The basic approach I would be to use copy out the PYBIND11_TYPE_CASTER macro yourself, but change the `value` member to a `std::unique_ptr<YourType>`.  Then in `load()` you would do `value.reset(new YourType(...))`.
