### ISSUE TITLE
How to type convert std::vector<> subclass?

### ISSUE THREAD

**Issue by smontanaro** [pybind/pybind11#620]
I have a few classes to write converters for which are subclasses of std::vector<>. They add no data, only methods, so I think converting between them and the relevant Python types should be more-or-less the same. As it stands, the existing std::vector<> type converter isn't invoked, and I get

> TypeError: Unable convert function return value to a Python type! ...

Is there an easy way to defer to the existing STL type converters, maybe with a trivial converter so I don't need to duplicate existing code?

**Comment by jagerman** [comment]
```C++
template <typename Type, typename Alloc> struct type_caster<std::vector<Type, Alloc>>
 : list_caster<std::vector<Type, Alloc>, Type> { };
```

so you should be able to add your own definition like the above, but change the `std::vector<Type, Alloc>` to your own class.

(I should point out in passing that inheriting from stl containers is generally frowned upon, most notably because they don't have virtual destructors).

**Comment by jagerman** [comment]
(There's also a `set_caster`, `map_caster`, and `array_caster` for classes with std::set-like, std::map-like, and std::array-like interfaces).

**Comment by jagerman** [comment]
Also, these sorts of questions would be better put to the [gitter room](https://gitter.im/pybind/Lobby) than as bug reports; we set that up to try to keep this for legitimate bugs.

**Comment by smontanaro** [comment]
On Thu, Jan 26, 2017 at 9:58 AM, Jason Rhinelander <notifications@github.com
> wrote:

> Also, these sorts of questions would be better put to the gitter room
> <https://gitter.im/pybind/Lobby> than as bug reports; we set that up to
> try to keep this for legitimate bugs.
>
Thanks, Jason. I had never heard of (let alone interacted with) gitter
before bumping into pybind11. It will, unfortunately, probably take me a
couple more tries to get that bit of workflow correct. (Your reminder
sparked a memory of a similar reminder from a few weeks ago.)

I will point that that though it is certainly easy to ignore, GitHub
displays a "guidelines for contributing" link to CONTRIBUTING.md when you
start a new issue. I don't see the gitter channel mentioned there. Might be
a worthwhile addition. Unfortunately, my work environment makes it nearly
impossible to submit pull requests, so I can't suggest an obvious change.

And the decision to subclass std::vector<> is well out of my hands. I'm not
really a C++ programmer, and the decision was made long before I was in my
current job. (In their defense, I think they are transitioning from an
older non-STL vector system to std::vector, and our current classes are
transitional, though with a pretty long transition window.)

Skip

**Comment by jagerman** [comment]
The gitter room is new, and somewhat experimental to see if it works, but there have been a few questions/answers in there, so it seems to be working.

As for obvious changes/fixes that you can't submit a PR for, those are perfect uses for issues.

**Comment by dean0x7d** [comment]
I'm guessing that the custom `type_caster` suggestion solved this issue, so I'll close it. Feel free to reopen if there's still a problem.

**Comment by varunagrawal** [comment]
Apologies for commenting on this old thread, but is this not documented? I went to the latest pybind documentation and searched for `list_caster` but got nothing. [Reference](https://pybind11.readthedocs.io/en/stable/search.html?q=list_caster&check_keywords=yes&area=default#)

**Comment by varunagrawal** [comment]
@jagerman came across this again. Hopefully, someone can point me in the right direction.

cc: @wjakob
