### ISSUE TITLE
please consider adding (n,m) constructors

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#622]
I believe a useful enhancement would be constructors of the form:

array_t<double> a (1,2)

to create an empty, 2-d array of dim 1x2

This would make the library interface more like many other array libraries, and ease porting.

Unfortunately, my modern c++ foo is not quite up to this.  The existing array_t has a constructor of the form
array_t<double> a (std::vector<size_t>)
So a simple approach is to transform a variable arg list into a std::vector and use the existing constructor.

BTW, I think it's strange the only constructor (of an empty array) takes a very specific std::vector rather than some more generic sequence, or am I misreading the code?

**Comment by nbecker** [comment]
This code appears to work
```diff
diff --git a/include/pybind11/numpy.h b/include/pybind11/numpy.h
index 6fecf28..c224bd4 100644
--- a/include/pybind11/numpy.h
+++ b/include/pybind11/numpy.h
@@ -591,6 +591,24 @@ public:
     explicit array_t(size_t count, const T *ptr = nullptr, handle base = handle())
         : array(count, ptr, base) { }
 
+    std::vector<size_t> to_vect() {
+        return std::vector<size_t>();
+    }
+
+    template<typename I, typename... Ix> std::vector<size_t> to_vect(I i, Ix... rest) {
+        std::vector<size_t> s = to_vect(rest...);
+        s.push_back (i);
+        return s;
+    }
+
+    template<typename... Ix>  std::vector<size_t> to_vect1(Ix... rest) {
+        std::vector<size_t> s = to_vect(rest...);
+        std::reverse(s.begin(), s.end());
+        return s;
+    }
+
+    template<typename... Ix> explicit array_t(Ix... rest) : array_t (to_vect1 (rest...)) {}
+
     constexpr size_t itemsize() const {
         return sizeof(T);
     }
```

**Comment by jagerman** [comment]
Because it takes a vector, it will also take anything implicitly convertible to a vector, which includes initializer lists.  That means you can do:

```c++
array_t a({1, 2});
```

which is pretty close to what you are looking for.

**Comment by jagerman** [comment]
The version above will cause problems if called with, for example, an `array_t<T>`: it'll match the template and call that instead of calling the proper `array(object &o)` constructor [added by the PYBIND11_OBJECT_CVT macro].

If we want this (I'm fairly neutral on it), this constructor works better: it's simpler in that it just maps array(1,2,3) to array({1,2,3}), but more importantly it won't match constructors called with arguments that aren't implicitly convertible to `size_t`:

```C++
    template <typename... Ix, typename = detail::enable_if_t<detail::all_of<std::is_convertible<Ix, size_t>...>::value>>
    explicit A(Ix... dimensions) : A{{ (size_t) dimensions... }} {}
```

**Comment by dean0x7d** [comment]
The existing syntax pointed out by @jagerman is simple enough. I don't think that `array_t(1, 2, 3)` adds much over the existing `array_t({1, 2, 3})`. The latter has the advantage that it can naturally be extended with more arguments (strides, data) while keeping the same form, which is also consistent with the numpy array creation syntax. 

While possible to implement, the braceless syntax requires adding a completely generic variadic constructor with SFINAE alongside a bunch of existing constructors. This would surely cause more trouble down the line (more SFINAE for other constructors if they are to be made more generic, which was proposed elsewhere).
