### ISSUE TITLE
libpython not added to built modules with CMake when BUILD_SHARED_LIBS is OFF

### ISSUE THREAD

**Issue by jcelerier** [pybind/pybind11#623]
Hello,

When I build my pybind11 modules (with `pybind11_add_module`) and set `BUILD_SHARED_LIBS=OFF`, my link line looks like this : 

    /usr/bin/c++  -fPIC -g  -shared  -o ossia_python.cpython-36m-x86_64-linux-gnu.so CMakeFiles/ossia_python.dir/OSSIA/ossia-python/ossia_python.cpp.o  OSSIA/libossia.a -lpthread -ffunction-sections -fdata-sections -Wl,--gc-sections -fvar-tracking-assignments -Wl,--compress-debug-sections=zlib -Wa,--compress-debug-sections -Wl,--dynamic-list-cpp-new -Wl,--dynamic-list-cpp-typeinfo -Wl,-Bsymbolic-functions -Wl,--gdb-index -gsplit-dwarf -fuse-ld=gold -Wl,-z,defs -Wl,--threads -Wl,--thread-count,8

I have to add ` -lpython3.6m` manually (else I understandably get various undefined references to python functions). Everything works correctly with `BUILD_SHARED_LIBS=ON`.

When calling CMake I get this, which seems correct : 

    -- Found PythonInterp: /usr/bin/python3.6 (found version "3.6") 
    -- Found PythonLibs: /usr/lib64/libpython3.6m.so
    -- pybind11 v2.1.dev0

**Comment by jcelerier** [comment]
I could fix it by addding 

    -Wl,--warn-unresolved-symbols

to my link line.

Maybe this is something that should be added by default for the `UNIX AND NOT APPLE` case in the CMakeLists ?

**Comment by loriab** [comment]
Unless you're embedding python (that is, creating an executable, rather than a shared library), I don't think you _want_ to be linking libpython, as per [this](https://github.com/pybind/pybind11/blob/master/tools/pybind11Tools.cmake#L95-L107), as you get less more flexibility at runtime by leaving those symbols unresolved. The `-undefined dynamic_lookup` on Mac is making Mac emulate the Linux behavior leaving the symbols unresolved.

**Comment by jcelerier** [comment]
Indeed, for the software I develop I default to errors when symbols are missing (with `-Wl,-z,defs`) because it's quite common for instance to forget to export a symbol, and only get an error at runtime. But for a "loadable plug-in" behaviour it makes more sense to have dynamic lookup.
Sorry for the noise.
