### ISSUE TITLE
example of ctor with default args (and docstring)?

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#626]
Is there an example showing the syntax for a constructor taking default args, also with default args + a docstring?

Thanks

**Comment by jagerman** [comment]
It's really no different than any method: you need to tell pybind11 about the defaults using `py::arg("name") = value`. (C++ defaults are really a compile-time thing; at run-time pybind has to know all the arguments).

e.g.

```C++
class A {
public:
    A(int a = 3, int b = 4) : value{a + b} {}
    int value;
}
// ...
py::class_<A>("A").def(py::init<int, int>(), py::arg("a") = 3, py::arg("b") = 4, "docstring");
```
Or you could change the `py::arg("x") = n` to `"x"_a = n` if you have a `using namespace pybind11::literals;`.
