### ISSUE TITLE
can't convert bp::object()

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#628]
In the past (boost::python) I've used bp::object() for defaulted arguments e.g.,

```
    .def ("__call__", &wrapped_pn<int_t>::generate,
          //bp::default_call_policies(),
          py::arg ("size"),
           py::arg ("dtype")=object()
          )
```

But with pybind11 this gives:
```
ImportError: arg(): could not convert default keyword argument 'dtype: boost::python::api::object' in method '<class 'pn2.pn64'>.__call__' into a Python object (type not registered yet?)
```

Is there either a fix for this, or another recommended way to indicate defaulted arguments?

**Comment by nbecker** [comment]
Also tried:
```
...
py::arg("dtype")=py::object()
...
```

that gives:
```
ImportError: arg(): could not convert default keyword argument 'dtype: object' in method '<class 'pn2.pn64'>.__call__' into a Python object (type not registered yet?)
```

**Comment by wjakob** [comment]
With pybind11, you need to register the types that occur in default arguments before you can actually use them. You can only use ``py::object`` as a default argument if that's what your method actually accepts (unlikely if it is a function from an existing codebase)
