### ISSUE TITLE
left shift of int_

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#629]
This code:
```
    max (sizeof(out_type) == sizeof(uint64_t) ?
         py::cast(py::int_(1) << 64) : py::cast(py::int_(1) << 32)),
```
produces this warning:
```
pn2.cc:130:31: warning: left shift count >= width of type [-Wshift-count-overflow]
          py::cast(py::int_(1) << 64) : py::cast(py::int_(1) << 32)),
                       ~~~~~~~~^~~~~
```

Clearly this isn't doing what I expected (and I believe worked under bp::int_).  I expected this to produce a python int object, then use the boost::python object protocol to apply the << operator.  I'm confused.

**Comment by wjakob** [comment]
The pybind11 python object wrappers are extremely light and don't have arithmetic overloads (and many other things..), since they are mostly meant for internal usage. You'll notice that this library has a much more minimalistic design compared to boost.python -- this is intentional.

**Comment by nbecker** [comment]
The objective here is to get a get a python long object = 1 << 64
I'm using this code:
```
    py::object one =  py::object(PyLong_FromLong(1L), false);
    py::object max = one.attr("__lshift__")(64);
```
Is this use of py::object(PyObject*) correct?
