### ISSUE TITLE
Splitting class definitions in separate cpp files

### ISSUE THREAD

**Issue by elypma** [pybind/pybind11#633]
I have a large number of classes to make bindings for and instead of using a single huge module file I'd like to split it in separate cpp files.
I have seen the way this is done in the pybind11_test module that comes together with pybind11 and although this builds, I get spurious errors when trying to import the resulting pythyon module.

One of the classes (InputVariable derived from Variable) is defined like (in a separate cpp file):

```
module_initializer InputVariable([](py::module &m) {

	py::class_<fl::InputVariable, fl::Variable>(m, "InputVariable_class")
		.def("fuzzyInputValue", &fl::InputVariable::fuzzyInputValue)
		.def("type", &fl::InputVariable::type)
		.def("toString", &fl::InputVariable::toString)
		.def("clone", &fl::InputVariable::clone)
		;
	m.def("InputVariable",
		[](const std::string &name, fl::scalar maximum, fl::scalar minimum)
	{ return new fl::InputVariable(name, maximum, minimum); },
		py::return_value_policy::reference);

});
```
When trying to import the module I get:
```
ImportError('generic_type: type "InputVariable_class" referenced unknown base type "fl::Variable"',)
```
Changing the definition like:
```
py::class_<fl::InputVariable>(m, "InputVariable_class")
     .... etc...
```
removes all the base-class functionality and is thus no option.

Am I missing the obvious?

**Comment by dean0x7d** [comment]
This is one area where it would be better not to follow the example of the test module. The `test_initializer` class is convenient, but only useful when there are no dependencies between the different translation units (`cpp` files) as is the case for `pybind11_tests`. Each `test_initializer` is a global variable and C++ does not specify the initialization order of global variables in different translation units (the order is essentially random). So if your base and derived class wrappers are defined separately, there's a 50/50 chance that the derived wrapper will be initialized before the base, resulting in that error.

As a solution, use standard functions instead of the initializers, [as suggested in the docs](http://pybind11.readthedocs.io/en/latest/faq.html#how-can-i-reduce-the-build-time). It's a bit more typing, but it guarantees the initialization order.

**Comment by jagerman** [comment]
What [we used to have](https://github.com/pybind/pybind11/blob/06d8de113a89b660b216600a46e06d52666e318b/tests/pybind11_tests.cpp) is basically what you want.

It switched because, for a test suite, it's very convenient to be able to turn some tests on or off.  Before the commit just after the one I linked to above, disabling tests—for example, to concentrate on just a single test when working on something—meant making changes in three different places.

**Comment by wjakob** [comment]
The documentation now contains a warning about this (see #635)

**Comment by khurramHazen** [comment]
I having a similar issue as @elypma The difference I guess is, @elypma understood the issue he was facing while I am completely out of guesses.

I am following an example from good Nvidia souls about extending TensorRT functionality by implementing own C++/CUDA layers and then binding it with TensorRT engine using Pybind11. As a first, I am trying to run their given example to have some grasp on basic steps. 

Nvidia provided implementation is:
```
#include "FullyConnected.h"
#include "NvInfer.h"
#include "NvCaffeParser.h"
#include <pybind11/pybind11.h>

PYBIND11_MODULE(fcplugin, m)
{
    namespace py = pybind11;

    // This allows us to use the bindings exposed by the tensorrt module.
    py::module::import("tensorrt");

    // Note that we only need to bind the constructors manually. Since all other methods override IPlugin functionality, they will be automatically available in the python bindings.
    // The `std::unique_ptr<FCPlugin, py::nodelete>` specifies that Python is not responsible for destroying the object. This is required because the destructor is private.
    py::class_<FCPlugin, nvinfer1::IPluginExt, std::unique_ptr<FCPlugin, py::nodelete>>(m, "FCPlugin")
        // Bind the normal constructor as well as the one which deserializes the plugin
        .def(py::init<const nvinfer1::Weights*, int>())
        .def(py::init<const void*, size_t>())
    ;

    // Since the createPlugin function overrides IPluginFactory functionality, we do not need to explicitly bind it here.
    // We specify py::multiple_inheritance because we have not explicitly specified nvinfer1::IPluginFactory as a base class.
    py::class_<FCPluginFactory, nvcaffeparser1::IPluginFactoryExt>(m, "FCPluginFactory", py::multiple_inheritance())
        // Bind the default constructor.
        .def(py::init<>())
        // The destroy_plugin function does not override the base class, so we must bind it explicitly.
        .def("destroy_plugin", &FCPluginFactory::destroyPlugin)
    ;
}

```

This example compiles but when I try to import the resultant python module it throws following error at import time
`ImportError: generic_type: type "FCPlugin" referenced unknown base type "nvinfer1::IPluginExt"`

As pointed by @elypma when I remove the `nvinfer1::IPluginExt` and the following items from the first `py::class_` call, the resulting python module gets imported but the required functionality (of extending TensorRT base class) is absent. hence this error 

```
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: nvcaffeparser1::ICaffeParser, arg1: tensorrt.tensorrt.ICaffePluginFactoryExt) -> None
```

So any suggestions?

**Comment by khurramHazen** [comment]
@wjakob @jagerman  Any suggestion/comment on above issue?

**Comment by traveller59** [comment]
@khurramHazen solved by using pybind11 2.2.3:
```git clone -b v2.2.3 https://github.com/pybind/pybind11.git```

**Comment by khurramHazen** [comment]
@traveller59 I tried v2.2.3 but still got the same error.
Following [https://github.com/pybind/pybind11/issues/172] I modified the binding code as follows:
```
#include "FullyConnected.h"
#include "NvInfer.h"
#include "NvCaffeParser.h"
#include <pybind11/pybind11.h>


PYBIND11_MODULE(fcplugin, m)
{
    namespace py = pybind11;

    // This allows us to use the bindings exposed by the tensorrt module.
    py::module::import("tensorrt");

    py::class_<nvinfer1::IPluginExt, std::unique_ptr<nvinfer1::IPluginExt, py::nodelete>>(m, "IPluginExt");  // <-- Addition as per pybind:#172

    // Note that we only need to bind the constructors manually. Since all other methods override IPlugin functionality, they will be automatically available in the python bindings.
    // The `std::unique_ptr<FCPlugin, py::nodelete>` specifies that Python is not responsible for destroying the object. This is required because the destructor is private.
    py::class_<FCPlugin, nvinfer1::IPluginExt, std::unique_ptr<FCPlugin, py::nodelete>>(m, "FCPlugin")
        // Bind the normal constructor as well as the one which deserializes the plugin
        .def(py::init<const nvinfer1::Weights*, int>())
        .def(py::init<const void*, size_t>())
    ;

    py::class_<nvcaffeparser1::IPluginFactoryExt>(m, "IPluginFactoryExt");   // <-- Addition as per pybind:#172
    
    // Since the createPlugin function overrides IPluginFactory functionality, we do not need to explicitly bind it here.
    // We specify py::multiple_inheritance because we have not explicitly specified nvinfer1::IPluginFactory as a base class.
    py::class_<FCPluginFactory, nvcaffeparser1::IPluginFactoryExt>(m, "FCPluginFactory")
        // Bind the default constructor.
        .def(py::init<>())
        // The destroy_plugin function does not override the base class, so we must bind it explicitly.
        .def("destroy_plugin", &FCPluginFactory::destroyPlugin)
    ;
}

```
Now I am able to import the module in Python.

But since things are not *that * simple in life, now I am facing data-type issues. More specifically following error:
```
fc_factory = fcplugin.FCPluginFactory()
parser.plugin_factory_ext = fc_factory
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: nvcaffeparser1::ICaffeParser, arg1: tensorrt.tensorrt.ICaffePluginFactoryExt) -> None

Invoked with: <tensorrt.tensorrt.CaffeParser object at 0x7f95c4037490>, <build.fcplugin.FCPluginFactory object at 0x7f95c40377d8>
```

**Comment by khurramHazen** [comment]
@traveller59 I am able to compile and successfully (finally) run the fcplugin example.
I guess the issue was with my cmake build command, apparently the order in which you specify cmake options on terminal **do** matter.

**Comment by traveller59** [comment]
@khurramHazen Congratulations.
I still can't successfully build that sample code with your cmake command with pybind11-2.3dev0 (generic_type unknown base type error), but 2.2.3 works. 
environment 1: ubuntu 18.04, anaconda-python2.7, cuda 9.0.176, TensorRT 5.0.0.10
environment 2: ubuntu 16.04, python3.5, cuda 9.0.176, TensorRT 5.0.0.10

**Comment by khurramHazen** [comment]
Apologies. I am using pybind11 **v2.2.3**  and it is working. ( ubuntu 16.04, Anaconda Python3.6, Cuda 9.0.176, TensorRT 5.0.0.10 ). I have edited my previous post.
The 2.3.dev0 is another environment.
