### ISSUE TITLE
Documentation: module destructor

### ISSUE THREAD

**Issue by virtuald** [pybind/pybind11#638]
Python supports a module destructor via `tp_dealloc`... I can't seem to figure out how to hook that in pybind11. I tried the most obvious thing I could think of (subclass module), and that doesn't work. I'm sure it's supported, right?

**Comment by virtuald** [comment]
Wasn't able to find anything... it seems like python 3 supports extension destructors, but not python 2. Instead, I went with a weakref-based approach in the PYBIND_PLUGIN initialization:

``` c++
    if (PyWeakref_NewRef(m.ptr(), 
        py::cpp_function([](py::weakref ref){
            // add destructor code here
            Py_DECREF(ref.ptr());
        }).ptr()) == NULL) {
        return NULL;
    }
```

If it seems like this is a good approach, it would be useful to put in the documentation (or perhaps create a wrapper?).

**Comment by jagerman** [comment]
I'm curious what the use case is for this.  Can module destruction happen at any time other than program exit?

**Comment by virtuald** [comment]
If one subclasses py::module, the C++ destructor seems to be called almost immediately as the C++ instance seems to go out of scope after it's passed to Python somewhere.

My use case is that I'm wrapping a C library that has some globally allocated resources that I would like to cleanup before exit.

**Comment by jagerman** [comment]
Here's an alternative that is a little bit simpler (though the _cleanup capsule will be visible to Python code):

```C++
static int unused; // the capsule needs something to reference
py::capsule cleanup(&unused, [](PyObject *) { std::cout << "Cleanup!" << std::endl; });
m.add_object("_cleanup", cleanup);
```

**Comment by virtuald** [comment]
That is a much better alternative I suspect, and it seems to work.

**Comment by jagerman** [comment]
It's better still if you already have a pointer around to stick in the capsule, to be retrieved in the lambda with `[](PyObject *o) { auto *whatever = (WhateverType *) PyCapsule_GetPointer(o, nullptr); /* ... */ });`

Then you can get rid of the useless `unused`.
