### ISSUE TITLE
ImportError: dynamic module does not define init function (initcode)

### ISSUE THREAD

**Issue by jshellen** [pybind/pybind11#644]
Hi,

I have been working for weeks with this project and suddenly started to receive the following behaviour:
**First, I receive this error:** ImportError: dynamic module does not define init function (initcode) when trying to import my module "code" in Python.

**Second,** when I write in the src folder "python setup.py build_ext -i" nothing happens anymore.

What is going on? 

I know that this has been discussed before. However, It is still very unclear to me what I am doing wrong. Here is my code.cpp

       #include "TestCppClient.h"
       #include "EWrapper.h"
       #include "EReaderOSSignal.h"
       #include "EReader.h"
       #include "EReaderSignal.h"
       #include "EClientSocket.h"
       #include "EClient.h"
       #include "ESocket.h"
       #include "EMessage.h"
       #include "DefaultEWrapper.h"
       #include "OrderCondition.h"
       #include "OperatorCondition.h"
       #include "TimeCondition.h"
       #include "ContractCondition.h"
       #include "PriceCondition.h"
       #include "IExternalizable.h"
       #include "MarginCondition.h"
       #include "VolumeCondition.h"
       #include "executioncondition.h"
       #include "PercentChangeCondition.h"
       #include "EMutex.h"
       #include "Contract.h"
       #include <pybind11/pybind11.h>
       #include <pybind11/numpy.h>
       #include <ostream>
       namespace py = pybind11;
       using namespace pybind11::literals;
       PYBIND11_PLUGIN(code)
       {

    py::module m("code", "pybind11 example plugin");

    py::class_<EWrapper>          c_EWrapper(m, "EWrapper");
    py::class_<EClient>           c_EClient(m,  "EClient");
    py::class_<ESocket>           c_ESocket(m,  "ESocket");
    py::class_<EReaderSignal>     c_EReaderSignal(m, "EReaderSignal");

    py::class_<Contract> c_Contract(m, "Contract");

    //! [EClientSocket]
    py::class_<EClientSocket, EClient> c_EClientSocket(m, "EClientSocket");
    c_EClientSocket
            .def(py::init<EWrapper*,EReaderSignal*>());

    //! [EReaderOSSignal]
    py::class_<EReaderOSSignal, EReaderSignal> c_EReader(m, "EReaderOSSignal");
    c_EReader
            .def(py::init<long&>());

    //! [TestCppClient]
    py::class_<TestCppClient,EWrapper> c_client(m, "TestCppClient");
    c_client
            .def(py::init<>())
            .def("connect",     &TestCppClient::connect)
            .def("disconnect",  &TestCppClient::disconnect)
            .def("isConnected", &TestCppClient::isConnected)
            .def("LimitOrder",  &TestCppClient::LimitOrder);

    return m.ptr();
}

**Comment by wjakob** [comment]
Please take a look at the FAQ

**Comment by jshellen** [comment]
Where is it exactly?

**Comment by jagerman** [comment]
http://pybind11.readthedocs.io/en/master/faq.html (the very first question).

**Comment by jshellen** [comment]
But as you can see per above the name of my module is "code" and it is specified inside the parenthesis in PYBIND11_PLUGIN(code) ....

**Comment by jshellen** [comment]
Well, if I write in terminal "python --version" I get the following: Python 2.7.13 :: Anaconda 4.3.0 (x86_64). and when I run the code I use "python test_funcs.py" which invokes python 2. To me this is that my problem does not satisfy item1 or item 2...

**Comment by jagerman** [comment]
Check how you are compiling the .so; it sounds very much as though it's being compiled with python3, but you're trying to load it in python2.

**Comment by jshellen** [comment]
Will do. Thanks! I highly appreciate your patience.

**Comment by jshellen** [comment]
I believe I now know the source of this issue. I had forgotten to include the .cpp file containing pybind11 code into the setup.py source code list.
