### ISSUE TITLE
Howto check if cast will succeed?

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#649]
Is there a way to see if obj.cast<some_type>() will succeed, or just use try/catch?

**Comment by dean0x7d** [comment]
AFAIK `try`/`catch` is the only public API to accomplish that.

Also, prefer using the [Gitter room](https://gitter.im/pybind/Lobby) for quick questions like this to avoid generating lots of issues.

**Comment by nbecker** [comment]
Thanks, I didn't know about the gitter room.
