### ISSUE TITLE
Unsigned function signature

### ISSUE THREAD

**Issue by YannickJadoul** [pybind/pybind11#651]
Very very minor detail, but docstring-signature this is confusing, if I have a function taking an unsigned int:

```test(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int) -> int

Invoked with: -1```

**Comment by wjakob** [comment]
The docstring signature uses Python types, and there is no such distinction within the Python language. I agree that it is unfortunate, but the choice is intentional.
