### ISSUE TITLE
Allow running the test suite against the installed pybind11

### ISSUE THREAD

**Issue by ghisvail** [pybind/pybind11#663]
Now that `pybind11` installs a corresponding CMake package configuration, it would be nice to make the test suite a standalone CMake project, which can be built against either an exported or an imported `pybind11` target. One could then run the following:

```
apt install pybind11-dev
cd $<path-to-test-suite>
mkdir build && cd build
cmake .. && make && make check
```

This would help with CI on Linux distributions (for instance the `debci` infrastructure on Debian), and help catch future integration issues, like the gcc-6 LTO regression experienced in #604, much earlier in the development cycle.

**Comment by jagerman** [comment]
Good idea: #665

**Comment by jagerman** [comment]
Closing; this is supported in master now (and used by one of the travis-ci builds).
