### ISSUE TITLE
numpy reference leaks

### ISSUE THREAD

**Issue by jagerman** [pybind/pybind11#670]
I'm seeing behaviour from `py::array` that I don't understand w.r.t. numpy array reference counts.  Here's the test code:

#### reltest.cpp:
```C++
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>

namespace py = pybind11;

template <int I> class A {};

namespace pybind11 { namespace detail {
template<> class type_caster<A<0>> {
public:
    PYBIND11_TYPE_CASTER(A<0>, _(""));

    bool load(handle, bool) { return true; }

    static handle cast(A<0> src, return_value_policy, handle) {
        py::array_t<double> a({3, 3});
        return a.release();
    }
};
template<> class type_caster<A<1>> {
public:
    PYBIND11_TYPE_CASTER(A<1>, _(""));

    bool load(handle, bool) { return true; }

    static handle cast(A<1> src, return_value_policy, handle) {
        py::dict d;
        return d.release();
    }
};
}}

PYBIND11_PLUGIN(reltest) {
    py::module m("reltest");
    m.def("a0", []() -> A<0> { return A<0>(); });
    m.def("a1", []() -> A<1> { return A<1>(); });
    return m.ptr();
}
```

#### reltest.py
```Python
from reltest import a0, a1
import sys
# Call once to initialize any static refs (numpy, in particular):
a0()
a1()
print(sys.gettotalrefcount())
for i in range(1000):
    a0()
print(sys.gettotalrefcount())
for i in range(1000):
    a0()
print(sys.gettotalrefcount())
for i in range(1000):
    a1()
print(sys.gettotalrefcount())
for i in range(1000):
    a1()
print(sys.gettotalrefcount())
```

(Note that this requires a python debug build for the `gettotalrefcount()`, which in turn also requires a numpy debug build; on Debian/Ubuntu installing the `python3-dbg` and `python3-numpy-dbg` packages should be enough).

I compile and run with:
```
g++ -Os -std=c++14 -Iinclude `python3-dbg-config --includes --ldflags` -shared -fPIC reltest.cpp -o reltest.so
python3-dbg reltest.py
```

I get the following output, which seems to suggest a leak in the `array` returns, but perhaps I'm doing something wrong:
```
250025
251031
252031
252031
252031
```
Note the increase of ~1000 for the first two `py::array` returns, and the lack of increase for the `py::dict` returns.

This doesn't seem to be a numpy leak: I tried the following non-pybind, pure C version:
#### nptest.c
```
#include <Python.h>

#define NPY_NO_DEPRECATED_API NPY_1_12_API_VERSION
#include <numpy/ndarrayobject.h>

static double storage[100] = { 0 };

static PyObject* f(PyObject *unused1, PyObject *unused2) {
    Py_intptr_t shape[2] = {10, 10};
    Py_intptr_t strides[2] = {8, 80};
    PyObject *a = PyArray_NewFromDescr(&PyArray_Type, PyArray_DescrFromType(NPY_DOUBLE),
            2, shape, strides, storage, 0, NULL);
    return a;
}

static struct PyMethodDef meths[] = {
    {"f", f, METH_NOARGS, ""},
    {NULL, NULL, 0, NULL}
};
static struct PyModuleDef mod = {
    PyModuleDef_HEAD_INIT,
    "nptest",
    NULL,
    -1,
    meths
};

PyMODINIT_FUNC PyInit_nptest(void) {

    import_array();
    return PyModule_Create(&mod);
}
```

#### nptest.py:
```Python
import sys
import nptest
print(sys.gettotalrefcount())
for i in range(1000):
    nptest.f()
print(sys.gettotalrefcount())
```

compiled and run with:
```
gcc -Os `python3-dbg-config --cflags` -shared -fPIC nptest.c -o nptest.so
python3-dbg nptest.py
```
which gives non-leaking numbers:
```
249988
249994
```

So this seems to be some problem either with `array`, or with my understanding of how to properly use `array`, but I can't figure it out.

Any ideas?

**Comment by jagerman** [comment]
Aha, found it!  We're not leaking the numpy array itself, we're leaking the dtype (we're passing `descr.release().ptr()` into `PyArray_NewFromDescr`, but it borrows rather than steals).

**Comment by jagerman** [comment]
No, I was wrong, the documentation is pretty clear that it does steal a reference; my "fix" was just breaking something else.

**Comment by dean0x7d** [comment]
I'd guess this is due to numpy, rather than anything that pybind11 is doing. See the same refcount issue in pure Python here: https://github.com/numpy/numpy/issues/8503

**Comment by jagerman** [comment]
Yeah, I'm fairly sure this isn't our fault.  I'll close this.
