### ISSUE TITLE
Question about cast std::wstring with Python3

### ISSUE THREAD

**Issue by czastack** [pybind/pybind11#674]
The document of Python3 says:
wchar_t* PyUnicode_AsWideCharString(PyObject *unicode, Py_ssize_t *size) 
Returns a buffer allocated by PyMem_Alloc() (use PyMem_Free() to free it) on success.

and in cast.h of pybind11:
template <> class type_caster<std::wstring>
```
#if PY_MAJOR_VERSION >= 3
    buffer = PyUnicode_AsWideCharString(load_src.ptr(), &length);
#else
...
#endif
    if (!buffer) { PyErr_Clear(); return false; }
    value = std::wstring(buffer, (size_t) length);
    success = true;
    return true;
```

Why we don't need to call PyMem_Free to free the buffer in this case?

**Comment by jagerman** [comment]
It looks like a bug, but it's no longer used in the pybind11 master branch (as of PR #624, which largely rewrote the unicode support).  We now go via `PyUnicode_AsEncodedString`, and manage the returned reference.

**Comment by wjakob** [comment]
I'll close this for now -- please comment here if you still have problems with the master version.
