### ISSUE TITLE
Add support for std::array

### ISSUE THREAD

**Issue by darkdragon-001** [pybind/pybind11#676]
It would be nice, if std::array could be directly handled without further adaption :)

It could be converted to Python lists. 
Since it has a fixed size, it could be converted to Python tuples.

**Comment by jagerman** [comment]
It is supported (when you `#include <pybind11/stl.h>`).

**Comment by darkdragon-001** [comment]
Thanks! Now it works to pass a Python list to a C++ array. 

Would be nice to mention in the [docs](https://github.com/pybind/pybind11/blob/master/docs/advanced/cast/stl.rst) as well ;)

**Comment by wjakob** [comment]
Goot catch, see baec23c.
