### ISSUE TITLE
Question about opaque types

### ISSUE THREAD

**Issue by psykokwak4** [pybind/pybind11#678]
For the `PYBIND11_MAKE_OPAQUE` macro, is there a way to make it accept template arguments? For example if I want to make a vector of sometype to be opaque could I do something like this?
```cpp
PYBIND11_MAKE_OPAQUE(std::vector<T>);
pybind11::bind_vector<std::vector<T>>(m, "OpaqueVector");
```
thanks so much for your help.

Could I make all vector objects opaque?

**Comment by jagerman** [comment]
No--it needs to have a concrete type.  However, if you don't `#include <pybind11/stl.h>` at all in any of your code then all vectors will be opaque already.
