### ISSUE TITLE
vcpkg integration

### ISSUE THREAD

**Issue by rwebber** [pybind/pybind11#681]
I would love to see pybind11 included in the vcpkg package manager.
This would greatly simplify usage for many developers.
https://github.com/Microsoft/vcpkg

**Comment by wjakob** [comment]
What would this kind of integration entail? Do we have to change the pybind11 repository or register the project in a registry? Are you offering to help? (I am not familiar with this tool)

**Comment by ethanhs** [comment]
Basically one makes a PR with a portfile [like this one](https://github.com/Microsoft/vcpkg/blob/master/ports/jsoncpp/portfile.cmake) and a control file. Then people can install pybind11 via vcpkg. For a cmake based project like this one, it is relatively straight forward.

**Comment by rwebber** [comment]
This is a little beyond my expertise currently. vcpkg support would make using pybind11 much easier for myself and many others I would imagine. Installing / building is the greatest hurdle.

**Comment by wjakob** [comment]
Unfortunately, AFAIK none of us have experience with this tool (I personally mostly develop on MacOS/Linux) -- if it's something you care about, would you be willing to push a portfile for pybind11?

**Comment by ethanhs** [comment]
Unless @rwebber wants to do it, I can probably do that this weekend.

**Comment by perara** [comment]
+1 For this. vcpkg really simplifies automated setups for windows users :) @rwebber  cheers!

**Comment by ethanhs** [comment]
sorry, got busy last week. Ill set myself a reminder to do the portfile this weekend.

**Comment by perara** [comment]
Cheers @ethanhs !

**Comment by ethanhs** [comment]
I will probably work on this tomorrow or Saturday. Ill update when I have a pr to their git repo.

**Comment by rwebber** [comment]
@ethanhs this is much appreciated. I'm not clear how vcpkg works internally (yet) but I do find it very convienient to use.

**Comment by ethanhs** [comment]
Since this project can be built with cmake, it is actually pretty simple. You write a portfile which is basically a cmake file with a few extra wrapping functions. I dont actually know everything about its underlying details. Anyway, I started on it, and should submit a pr later.

**Comment by wjakob** [comment]
Any news here? Can this be closed?

**Comment by ethanhs** [comment]
Sorry, some of the mechanics of how vcpkg portfiles are supposed to be written has changed, I began writing it, but I need to correct some things in how it installs. Im starting spring break so I will definitely have time to work on this, apologies for the delay.

**Comment by ras0219-msft** [comment]
@ethanhs Hi, I'm a dev on Vcpkg. Please feel free to open an issue on our GitHub if you get stuck anywhere -- we're happy to help!

If you get a chance, I'd also really appreciate knowing what you were depending on that broke. While they're sometimes needed, we do take breaking changes seriously! It's no fun at all to lose work.

**Comment by ethanhs** [comment]
Hey @ras0219-msft. Thanks so much for your message. Most of the issues I was having were checks on folder contents that didn't exist when I last wrote a portfile. So more of stricter requirements than breaking changes. I just need to figure out why it is complaining.

**Comment by ethanhs** [comment]
Okay, finally had time to work on this. Figured out how to please vcpkg post-install requirements. The PR is here: https://github.com/Microsoft/vcpkg/pull/857

**Comment by jagerman** [comment]
Cool.  A couple of very minor comments:

- in your PR test "single header library"should be "header-only library"
- I think when you updated to 2.1.0 you didn't update the `SOURCE_PATH` in `portfile.cmake` to pybind11-2.1.0 (the downloaded version is correct, so this is pretty minor).

**Comment by ethanhs** [comment]
Ah, thanks for catching that. And I updated to the more accurate description. I'll push the correction in a second.

**Comment by ethanhs** [comment]
And it is merged! You should be able to close this.

**Comment by wjakob** [comment]
Thanks!

**Comment by hkaiser** [comment]
Are there any plans to update the pybind11 version distributed by vcpkg by default to V2.2?

**Comment by ethanhs** [comment]
@hkaiser if you want to do it yourself, you can simply update the [ref](https://github.com/Microsoft/vcpkg/blob/master/ports/pybind11/portfile.cmake#L6) and the SHA512 hash and update the [CONTROL file](https://github.com/Microsoft/vcpkg/blob/master/ports/pybind11/CONTROL). Unless the build system has changed.
