### ISSUE TITLE
Allow access to static class variables that are defined in the header file

### ISSUE THREAD

**Issue by r-owen** [pybind/pybind11#682]
We have C++ classes with static constants (such as ints) whose value is specified in the header file. When we try to wrap these with pybind11 we find that the code fails at run time with a failure to find the symbol.

Presumably this is because the address cannot be taken of the constant if its value is specified in the header instead of in the implementation file.

I am hoping you might be able to find a way to fix this (e.g. by making a copy?). We have the luxury of modifying most of our C++ code, so it has been primarily a nuisance for us. But I can imagine wanting to wrap C++ code cannot be modified, at which point the problem becomes more difficult.

**Comment by jagerman** [comment]
Can you write up a short, failing example?

**Comment by r-owen** [comment]
The header file:
```
#ifndef TEST_H
#define TEST_H

class Test {
public:
    static const int Num = 5;
};

#endif
```

The wrapper:
```
#include <pybind11/pybind11.h>

#include "test.h"

namespace py = pybind11;
using namespace pybind11::literals;

PYBIND11_PLUGIN(_test) {
    py::module mod("_test");

    py::class_<Test> cls(mod, "Test");

    cls.def_readonly_static("Num", &Test::Num);

    return mod.ptr();
}
```

When build this an try to import this library in Python the import fails with
`Symbol not found: __ZN4Test3NumE` which is, of course, `Test::Num`.

If the value of `Test::Num` is set in an implementation file (which you'd have to add and build) then the problem goes away.

**Comment by jagerman** [comment]
This isn't really a pybind-specific problem: you only have a declaration but not a definition for `Num`.  You'll run into trouble with anything that wants to reference `Num`.

You'll need to add:
```C++
const int Test::Num;
```
somewhere.  If you have another library that the pybind11-built library is itself linking to, it belongs in that library; for a simple test/example as above it could be right in the `test.cpp` file.

**Comment by jagerman** [comment]
The answer to http://stackoverflow.com/questions/1410563/what-is-the-difference-between-a-definition-and-a-declaration is pretty informative on this.

**Comment by r-owen** [comment]
Exactly (and I tried to say that in my original posting). My request is to find a way to use the value instead of a reference to the value.

**Comment by r-owen** [comment]
For the record: `cls.attr("Num") = py::cast(Test::Num);` fails in the same way. I know of no way to get around the issue without modifying the original source code (which is not always possible), or duplicating the value in the wrapper file (which is risky).

**Comment by jagerman** [comment]
Try: `cls.def_property_readonly_static("Num", []() { return Num; });`

**Comment by r-owen** [comment]
For the record, this works: `cls.def_property_readonly_static("Num", [](py::object) { return Test::Num; });`

**Comment by wjakob** [comment]
(Another simple way is to cast the constant to a python object and assign it as an attribute.)

**Comment by r-owen** [comment]
@wjakob if you mean this, it does not work for me: `cls.attr("Num") = py::cast(Test::Num);`. That results in the same failure as the other things I tried (an undefined symbol at import). If it is supposed to work then I suspect there is a bug.

It would be nice to have a way to wrap these attributes without using a lambda. Thus I am somewhat disappointed to see this issue closed without a better resolution. Still, on the whole I have been very impressed with pybind11.

**Comment by jagerman** [comment]
That seems to work for me, with your example above.

**Comment by dean0x7d** [comment]
@r-owen Have you tried `cls.attr("Num") = py::int_(Test::Num)` instead of `py::cast()`? The latter takes its arguments as `const&` which counts as an ODR violation for constants without a definition (sans optimizations, taking a reference is the same as taking the address). On the other hand, `py::int_()` accepts only values and shouldn't run into the same issue.

**Comment by r-owen** [comment]
If `py::cast()` works with the current version of pybind11 then that's reasonable (we're starting to transition, having been stuck at some pre-2.0 version due to the metaclass issue breaking our code). I sure hope that is the case, as having to explicitly specify data types is less than thrilling.

I sure wish `cls.def_property_readonly_static` would work with constants, though. I don't understand why it refuses to copy constants (and instead requires a reference or address). It is fundamentally describing a constant, and if a plain old data type or a short string, it's cheap to copy. Might you consider adding an optional argument that means "Make a copy"?

**Comment by wjakob** [comment]
Actually, I think it would be quite feasible to add an overload that gets triggered for non-function/lanbda-functionpy::cppfunction arguments and sticks a static copy of an enum or other type into the class.
