### ISSUE TITLE
Wrong std::string overload called when given numpy.ndarray argument

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#685]
When an overload is present that takes a `std::string` argument, this overload is also (wrongly) called when given a `numpy.ndarray`.

See attached unit test patch to latest master.
[broken_overload.txt](https://github.com/pybind/pybind11/files/790838/broken_overload.txt)

**Comment by dean0x7d** [comment]
Looks like it only affects Python 2. [PyUnicode_FromObject](https://github.com/pybind/pybind11/blob/11a337f16f9b96a13df971d490c2ceea85d1a309/include/pybind11/cast.h#L655) might be a bit too permissive and accepts `ndarray` via the buffer protocol:

> https://docs.python.org/2.7/c-api/unicode.html#c.PyUnicode_FromObject
> String and other **char buffer compatible objects** are decoded according to the given encoding

@jagerman Perhaps an additional `PyString_Check` is needed for Python 2?

**Comment by pschella** [comment]
Any chance we can get a new point release with the fix for this, #688 and potentially other recent fixes?
