### ISSUE TITLE
std::unique_ptr returned destroys object

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [pybind/pybind11#690]
When I return an object by `unique_ptr`, it calls the destructor.
Like this:

    m.def("foo", []() {
        return std::make_unique<Foo>();
    };

When I change the smart pointer to `shared_ptr` and

    py::class_<Foo, std::shared_ptr<Foo>>(m, "Foo");

it works (does not call the destructor after exiting the lambda).
Am using 2.01.
Tried with a simple Foo and it works - so there seems to be a more complex problem here.

**Comment by dean0x7d** [comment]
Could you try with `master` instead of v2.0.1? Some `std::unique_ptr` issues were fixed recently. If it's still an issue, see if you can post a self-contained code example which reproduces it.

**Comment by dean0x7d** [comment]
@abergmeier-dsfishlabs Any update? Were you able to reproduce this on master or this a v2.0.1 issue?

**Comment by dean0x7d** [comment]
I'll close this due to lack of response. I assume the issue was fixed in v2.1. Feel free to reopen if there is new information.
