### ISSUE TITLE
Crashes when binding none to unsigned*

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [pybind/pybind11#691]
#### Issue description
When binding `none` to a `unsigned*`, it crashes on function (`foo`) call (v2.01).

#### Reproducible example code
Something similar to:

    m.def("foo", [](unsigned const* const) {
    }, py::arg("level") = py::none())

**Comment by dean0x7d** [comment]
I can't reproduce a crash (either on stable or master). But an exception is raised in both cases:
```
TypeError: foo(): incompatible function arguments. The following argument types are supported:
    1. (level: int=None) -> bool

Invoked with:
```

Is that what you're seeing?

**Comment by jagerman** [comment]
No response: I'll close this.  Feel free to reopen if the issue persists.
