### ISSUE TITLE
std::negation requires Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by SylvainCorlay** [pybind/pybind11#706]
As reported [here](https://www.bountysource.com/issues/41112911-error-building-the-python-plugin-with-visual-studio-2015).

**Comment by wjakob** [comment]
I think that we generally require that compiler because earlier versions may ICE when compiling pybind11 code.

**Comment by SylvainCorlay** [comment]
OK, it was just a FYI as I have a build machine that complained about this on the update to Pybind11 2.0.0.

In other places of the code base, you check for the specific msvc version.

**Comment by jagerman** [comment]
We should probably put a cmake fatal error for unsupported compilers. (MSVC before 2015u3, GCC before 4.8, etc.)

**Comment by dean0x7d** [comment]
VS 2015 Update 2 should be able to compile pybind11 with just some minor workarounds, but I think the bigger issue is that it's difficult to test. AFAIK AppVeyor only has a "Visual Studio 2015" option and it's always kept up to date, so there's only Update 3 to test against.

> We should probably put a cmake fatal error for unsupported compilers. (MSVC before 2015u3, GCC before 4.8, etc.)

Make the compiler support explicit sounds good, but I think CMake skimps on the [minor version numbers](
https://cmake.org/cmake/help/v3.7/variable/MSVC_VERSION.html). Perhaps doing the check in `common.h`?

**Comment by jagerman** [comment]
Somewhat related: the latest MSVC 2017 RC also ICEs when building pybind as well.

What a wonderful compiler.

**Comment by jcelerier** [comment]
Another problem with std::negation is that it was introduced in C++17 while pybind11 advertises C++11 compat...

**Comment by jagerman** [comment]
It's only used (along with std::conjunction and std::disjunction) on MSVC, because MSVC has it in the stl (as of 2015u3), and has trouble with some of the template metaprogramming in common.h.

**Comment by jcelerier** [comment]
@jagerman when my compiler is in -std=c++1z mode, it seems that it goes through the `std::negation`code path which isn't implemented yet.
Would a pull request that would put it behind a feature test macro (`__cpp_lib_experimental_logical_traits` and `__cpp_lib_logical_traits`) be accepted ?
