### ISSUE TITLE
File ending of library depends on whether or not one has loaded the pythonLibs before.

### ISSUE THREAD

**Issue by NOhs** [pybind/pybind11#707]
#### Issue description

Using cmake in my project I was confused that I needed to add the target properties `SUFFIX` to get the `*.so` ending of the file. I tried creating a MWE and it seems that searching for the PythonLibs before adding pybind11 as a subdirectory results in the generated libraries not having any file-ending.

#### Reproducible example code

Simply uncommenting the `find_package(PythonLibs...` will result in an `example` output instead of `example.cpython...so`. This was done on Arch-Linux.

```cmake
cmake_minimum_required(VERSION 3.6)
project(test_pybind11 CXX)

find_package(PythonInterp 3.5 REQUIRED)
# find_package(PythonLibs 3.5 REQUIRED) 
  
add_subdirectory(pybind11)
 
include_directories(
    SYSTEM ${CMAKE_CURRENT_SOURCE_DIR}/pybind11/include)
    
pybind11_add_module(example SHARED main.cpp)
```

Here the `main.cpp` simply copied from the tutorial:

```cpp
#include <pybind11/pybind11.h>
    
int add(int i, int j) {
    return i + j;
}
    
namespace py = pybind11;
    
PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

    m.def("add", &add, "A function which adds two numbers");

    return m.ptr();
}
```

**Comment by dean0x7d** [comment]
Pybind11 will run its own (improved) version of `find_package(PythonLibs)` internally (see [here](https://github.com/pybind/pybind11/blob/master/tools/FindPythonLibsNew.cmake)). If `PYTHONLIBS_FOUND` is already true, it will not overwrite an existing configuration. I guess the solution here is to just not use `find_package(PythonLibs)` before `add_subdirectory(pybind11)` or if you must, use pybind11's version:

```cmake
list(APPEND CMAKE_MODULE_PATH "pybind11/tools")  # make FindPythonLibsNew.cmake visible
find_package(PythonLibsNew 3.5 REQUIRED) 
```
