### ISSUE TITLE
Errors with clang-4.0

### ISSUE THREAD

**Issue by jcelerier** [pybind/pybind11#711]
Clang 4.0 seems to introduce a new warning, treated as an error, that breaks pybind11 for me: `-Wunusable-partial-specialization`.

The error can be seen here : https://travis-ci.org/OSSIA/libossia/jobs/209039296#L1914

My whole pybind11 code is here : https://github.com/OSSIA/libossia/blob/master/OSSIA/ossia-python/ossia_python.cpp

**Comment by jagerman** [comment]
This is fixed in current master (PR #677 fixed it).

I'll close this, but of course reopen if you're still getting it on current master.

**Comment by jcelerier** [comment]
nice, thanks, pulling asap!
