### ISSUE TITLE
Static members lead to "undefined symbol"

### ISSUE THREAD

**Issue by NOhs** [pybind/pybind11#718]
Ok. I know when you read the title it appears, I did not read the FAQ, but pybind11 is actually working for me. It is only when I was trying out static members, that errors started to occur.

MWE:

```cpp
#include "pybind11/pybind11.h"

struct myTest
{
    static const int the_number = 12;
};


PYBIND11_PLUGIN(pytest)
{
    namespace py = pybind11;
    py::module test_module(
        "pytest",
        "Module description goes here.");

    auto wrapper =
        py::class_<myTest>(test_module)
            .def_readonly_static("the_number", &myTest::the_number);

    return test_module.ptr();
}
```

If I switch to a non-inline version, python complains:

    ImportError: TypeError: can't set attributes of built-in/extension type 'module'

I also tried to define a `property` via a `get` method. Same issue.

The following non-static case works:
```cpp
#include "pybind11/pybind11.h"

struct myTest
{
    int the_number;
};


PYBIND11_PLUGIN(pytest)
{
    namespace py = pybind11;
    py::module test_module(
        "pytest",
        "Module description goes here.");


    auto wrapper =
        py::class_<myTest>(test_module)
            .def(py::init<>())
            .def_readonly("the_number", &myTest::the_number);

    return test_module.ptr();
}

```

**Comment by jagerman** [comment]
You have the static variable definition but not declaration, and so taking a reference fails.  You need to add: `const int myTest::the_number;` in exactly one cpp file.

See http://stackoverflow.com/questions/11178434/static-variable-in-the-class-declaration-or-definition

**Comment by NOhs** [comment]
Ok, that was a stupid mistake :(
