### ISSUE TITLE
stl_bind.h uses namespace py which is missing

### ISSUE THREAD

**Issue by jcelerier** [pybind/pybind11#736]
I get compilation errors due to the use of `py::` everywhere in that file (in current master).

It works if I add a `namespace py = pybind11` in [stl_bind.h:20](https://github.com/pybind/pybind11/blob/master/include/pybind11/stl_bind.h#L20)

**Comment by wjakob** [comment]
Namespace prefixes are actually completely unnecessary in this file, I've now removed them all. (dfd89a6).

**Comment by jcelerier** [comment]
thanks !
