### ISSUE TITLE
 Cannot call parent method when use multiple inheritance with pybind11::class_

### ISSUE THREAD

**Issue by czastack** [pybind/pybind11#741]
I am using Python 3.5 and VS 2015. The pybind11 is in the master branch.
When I use py::class_ to define multiple inheritance, like this.
```C++
	// namespace py = pybind11;
	
	auto PropertyGrid = py::class_<PyPropertyGrid>(m, "PropertyGrid")
		.def(py::init<py::object>(), "data"_a=None)
		.def("addCategory", &PyPropertyGrid::addCategory, "title"_a);

	auto PropertyGridPage = py::class_<PyPropertyGridPage>(m, "PropertyGridPage", PropertyGrid)
		.def(py::init<py::object>(), "data"_a = py::none());

	auto ListBox = py::class_<PyListBox>(m, "ListBox")
		.def(py::init<>())
		.def(py::init<py::capsule>())
		.def("insertItems", &PyListBox::insertItems)
		.def("setListener", &PyListBox::setListener);

// if delete the line bellow, typeinfo->simple_type become true and work well
	py::class_<PyPropertyGridListPage>(m, "PropertyGridListPage", ListBox, PropertyGridPage)
		.def(py::init<py::object>(), "data"_a = py::none());
```
And I call addCategory in PropertyGridPage instance, I got this:
TypeError: addCategory(): incompatible function arguments. The following argument types are supported:
    1. (self: fefactory_api.PropertyGrid, title: str) -> None

Invoked with: <fefactory_api.PropertyGridPage object at 0x000001EE51163DB0>, 'name'

fefactory_api is my module name, and issubclass(fefactory_api.PropertyGridPage, fefactory_api.PropertyGridPage) is true;

in cpp:
```C++
class PyPropertyGridListPage: public PyListBox, public PyPropertyGridPage
{
public:
	PyPropertyGridListPage(py::object data) : PyPropertyGridPage(data)
	{
		
	}
};
```

I debug and finally find this in cast.h
```C++
/* Case 2: multiple inheritance */
            /* Check if we can safely perform a reinterpret-style cast */
            if (tobj == typeinfo->type) {
                value = reinterpret_cast<instance<void> *>(src.ptr())->value;
                return true;
            }

            /* If this is a python class, also check the parents recursively */
            auto const &type_dict = get_internals().registered_types_py;
            bool new_style_class = PyType_Check((PyObject *) tobj);
            if (type_dict.find(tobj) == type_dict.end() && new_style_class && tobj->tp_bases) {
                auto parents = reinterpret_borrow<tuple>(tobj->tp_bases);
                for (handle parent : parents) {
                    bool result = load(src, convert, (PyTypeObject *) parent.ptr());
                    if (result)
                        return true;
                }
            }
```
After i modifying "type_dict.find(tobj) == type_dict.end()" into "type_dict.find(tobj) != type_dict.end()", it work on.

Is my usage wrong or is this a bug?

**Comment by dean0x7d** [comment]
Try changing
```c++
py::class_<PyPropertyGridListPage>(m, "PropertyGridListPage", ListBox, PropertyGridPage)
```
to
```c++
py::class_<PyPropertyGridListPage, PyListBox, PyPropertyGridPage>(m, "PropertyGridListPage")
```
i.e. specify the classes as template arguments rather than constructor runtime arguments.

I don't think this limitation is documented currently.

**Comment by czastack** [comment]
Thank you, it solve my problem.

**Comment by jagerman** [comment]
After discussion in #742, we *can't* support it; so it's both wrong, but also a bug that we let you do it without raising an error.

**Comment by jagerman** [comment]
This is fixed now: you'll get an informative compilation error rather than runtime failures if trying to specify multiple inheritance that way (since we can't reasonably support it).
