### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by stehol01** [pybind/pybind11#744]
Hi,
I would like to try pybind11 but it seems that i dont know how. I'm unfortunately not very familiar with setting programms up this way. So this the question is probably owed to my lack of knowledge but nevertheless, i stuck at this problem:

I tried to getting started with the python_example and the cmake_example which @dean0x7d mentioned, but somehow i dont get it! :P

Is there a step by step instruction guidline how to set up those examples? Something like a step by step tutorial for very very very beginners? Or a youtube video ...

I've already tried to getting both examples working but somehow i always end up with the following error if type the following words within my spyder IDE:

import python_example
python_example.add(1, 2)

Error:
AttributeError: module 'python_example' has no attribute 'add'

Why is this happening? I'm using python 3.6 and Anaconda. I also use VS2017 or VS2015.

Thank you for your help!

**Comment by jagerman** [comment]
Are you following [this](http://pybind11.readthedocs.io/en/master/basics.html) getting started guide?

**Comment by stehol01** [comment]
No, i followed the instructions posted here (https://github.com/pybind/python_example). I figured out how to run the python_example but the cmake_example (https://github.com/pybind/cmake_example) still doesnt work. If i follow the installation guidelines posted there, end with the following error: 

C:\ProgramData\Anaconda3>pip install .\cmake_example
Processing c:\programdata\anaconda3\cmake_example
    Running setup.py install for cmake-example ... error

Furthermore, i would like to try the test_callbacks.cpp/test_callbacks.py examples from the tests directory. Can you give some additinal advices how to get this things work?

Thank you!

**Comment by wjakob** [comment]
I think that this discussion is better moved to pybind11's gitter channel since this ticket is not about a bug or other kind of issue with pybind11 itself.
