### ISSUE TITLE
pybind11 doesn't seem to honor `operator new()` (e.g. for Eigen aligned allocators)

### ISSUE THREAD

**Issue by phfaist** [pybind/pybind11#754]
#### Issue description

I would like to expose classes in Python which have Eigen matrices as fields. Such classes need to be [allocated aligned to 16 bytes for vectorized operations](https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html). A canonical way of ensuring this is to use Eigen's "operator new" implementation via the macro `EIGEN_MAKE_ALIGNED_OPERATOR_NEW`.

However it seems that pybind11 doesn't honor the alignment-aware `operator new()` when exposing such a class to Python, causing segfaults. Crashes seem to appear only when compiling with vectorized operations enabled.

This may be a feature request if pybind11 currently does not support a custom `operator new()`. In this case, could this be mentioned in the docs and/or a compile-time error be generated? It would be very helpful instead of having to trace the reason of a segfault.

Thanks a lot for your time and for the great tool!

#### Reproducible example code

See attachment [pybind11_eigenaligned.tar.gz](https://github.com/pybind/pybind11/files/856416/pybind11_eigenaligned.tar.gz). I'm assuming the host system has vectorized operations available via `-march=native`. Then, in python:

    >>> import pybind11_eigenaligned
    >>> pybind11_eigenaligned.Data().showB()
    Assertion failed: ((internal::UIntPtr(array) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"), function plain_array, file /usr/local/include/eigen3/Eigen/src/Core/DenseStorage.h, line 128.
    Abort trap: 6

I'm running Mac OS Sierra with Apple's clang and Eigen 3.3.3. The problem occurs both with pybind11 2.0.1 as well as current pybind11 git master.

**Comment by wjakob** [comment]
pybind11 splits memory allocation into an ``operator new`` (https://github.com/pybind/pybind11/blob/master/include/pybind11/class_support.h#L186) and followed by a call to the placement new operator. The former part is non-templated/generic and does not know about alignment, hence the assertion failure you're seeing.

C++17 has a nice alignent-aware ``operator new``, but alas, C++17 is not widely supported.

**Comment by phfaist** [comment]
Ok, thanks for the info. My current workaround is to use dynamic-sized Eigen matrices, which don't require aligned allocation (as they internally take care of allocating the data correctly).

**Comment by jagerman** [comment]
I think we can actually support this fairly easily for a type that provides its own `T::operator new(size_t)` (which is what Eigen does); it's just a matter of storing the allocator (`::operator new` by default, but `T::operator new` if available) in the type record.  I'll submit a PR shortly.

**Comment by wjakob** [comment]
FWIW ``operator delete`` would also be needed. Actually, It's not exactly clear to me what operators should be stored to make this future-proof given the large number of subtly varying operators that are on the horizon: http://en.cppreference.com/w/cpp/memory/new/operator_new

**Comment by dean0x7d** [comment]
@jagerman Seems like we've had the same idea: https://github.com/dean0x7d/pybind11/commit/c14425934b8af603d29340f6fa34b95c9d031ca9

**Comment by jagerman** [comment]
Indeed; you got further than me, so I'll drop mine.

**Comment by dean0x7d** [comment]
The new/delete detection results in an internal compiler error on GCC 4.8, but passes on VS. That's a new one.

**Comment by jagerman** [comment]
Try 2015u2 ;)

**Comment by dean0x7d** [comment]
@wjakob The alignment-aware operators do indeed complicate matters. Fully supporting everything would require also storing the alignment and doubling the number of candidate operators (global and class-specific with alignment).

**Comment by phfaist** [comment]
It works great, thanks!
