### ISSUE TITLE
vectorize() for class member functions?

### ISSUE THREAD

**Issue by mreineck** [pybind/pybind11#761]
Hi,

I'm currently trying to make some improvements to the healpy package (https://github.com/healpy/healpy), and pybind11 seems to be an almost perfect tool for the interfacing between Python and C++ that this package needs.
My first experiments went well, but then I hit the problem that the vectorize() functionality of pybind11 does not appear to support class member functions.

Assuming I have in C++

```
class foo {
  public:
    double bar(double arg);
};
```
I'd like to provide a Python function that takes either a scalar or a numpy array, calls foo::bar for all individual values, and then returns either a scalar or a numpy array. (The class object itself will always be a scalar.)
Is there a way to achieve this with current pybind11 versions? Naive application of vectorize() doesn't seem to work, like so:

```
  py::class_<foo>(m, "foo")
     .def("bar",py::vectorize(&foo::bar))
```

I'd be grateful for any tips!

**Comment by jagerman** [comment]
This is indeed a limitation; I have a working fix that I'll submit shortly.

That won't appear in the stable release until 2.2; in the meantime, you can use the argument exclusion technique [given in the docs](http://pybind11.readthedocs.io/en/master/advanced/pycpp/numpy.html#vectorizing-functions) (look for "Sometimes we might want to explicitly exclude an argument") to bind a method-like lambda that invokes the method via another lambda, like this:

```C++
    .def("bar", [](foo &self, py::array_t<double> arg) {
        auto v = [&self](double arg) { return self.bar(arg); };
        return py::vectorize(v)(arg);
    });
```

**Comment by mreineck** [comment]
Great to hear that direct support is on the way, thanks a lot!
I had played with the lambda approach already, but didn't manage to treat the "self" argument properly. I'll use this variant for now.
