### ISSUE TITLE
Unedfined symbol pybind11::object::borrowed

### ISSUE THREAD

**Issue by uentity** [pybind/pybind11#770]
Hi devs!

Faced topic issue when building modules with Python bindings. Seems that this is related to my custom array class that is inherited from `pybind11::array_t`. It's a templated type that imports (inherits) all constructors from `array_t`, but couple of methods are only declared. Module1 contains explicit specializations of these methods (from my custom array) and have no problems.
Then, I use array in Module2 and it fails to load because of the issue above. I think the same would apply for `pybind11::object::stolen`, but I just didn't use it -- my array code contains `reinterpret_borrow<>`.

Right now I have a situation when release build *does not* have undefined symbol, but debug build *does*. In some other Module3 both release and debug builds have undefined symbol. Tested with gcc 6.3.1 and clang 3.9.1 -- results are the same.

Any ideas how to fix this?

**Comment by jagerman** [comment]
Can you be a bit more specific as to the missing symbols, or a (small) code sample that isn't working (so we can add a test for it)?  It's a bit hard to guess what specifically might be wrong from a general description.

**Comment by jagerman** [comment]
Oh, never mind, I didn't read the issue subject!

**Comment by jagerman** [comment]
Cc @dean0x7d 

I don't see an easy fix to this (aside from changing all `object::borrowed` to `object::borrowed_t{}`): `borrowed`/`stolen` are constexpr declarations without definitions which can (typically when compiling without optimizations and/or in debug mode) trigger a linkage failure.  In C++17 we could add a `inline const object::borrowed_t object::borrowed;` definition, but in earlier C++ standards that's not allowed.  We could add a templated class (with a dummy template parameter) in between `object` and `handle` to allow an inline definition, but that's a bit messy.

**Comment by jagerman** [comment]
@uentity - I can't seem to reproduce this easily (I'd still appreciate some sample test code!), but I think #771 may fix this; can you give it a try?

**Comment by dean0x7d** [comment]
@uentity How did you define the borrow and steal constructors? I'm guessing the definition and declaration are split between header and source files. If that's the case, moving just those constructors into the header should work around the issue. (The underlying issue should still be resolved in pybind11.)

**Comment by uentity** [comment]
@jagerman yes, #771 fixes my undefined symbol issue.
@dean0x7d - I didn't define borrow and steal constructors. I just imported them (inherited) from base `array_t` class with `using base_t::base_t`, where `base_t` is `array_t`.

**Comment by uentity** [comment]
Btw, I've read a little on `constexpr` subject and don't understand why compiler got confused here. Everything seems pretty legit. There is no single place in my code where I mention `object::borrowed` or `object::borrowed_t` explicitly. `pybind11` internals also seems to be fine at a glance - nobody tries to take an address of `borrowed`.

**Comment by jagerman** [comment]
It's more common to see this sort of thing on non-optimizing debug builds.  Compilers don't *have* to replace `constexpr` values with the literal value, but it's an easy optimization to make, so most do.  But under `-O0` (i.e. no optimization), the compiler sometimes references rather than substituting the `constexpr` value.

**Comment by jagerman** [comment]
I updated #771 with an alternate fix that stops using `borrowed` in pybind11, so your inherited constructors will no longer reference it at all.  It could still be a potential issue if you try to use `object::borrowed` directly, but as long as you aren't you should be fine (and you'll get deprecation warnings if you try).

**Comment by uentity** [comment]
@jagerman I already checked out your work. No issues so far.
Great project and great responsiveness, thank you guys!
