### ISSUE TITLE
Negative strides in Python buffer view?

### ISSUE THREAD

**Issue by crisluengo** [pybind/pybind11#776]
I have a C++ image type that allows negative strides. Python numpy arrays do too, so I was hoping I'd be able to convert between the two without data copy. But pybind11's `buffer_info` struct defines the strides with a `std::vector<size_t>`. In the code, Python's stride values are simply cast to unsigned:

    strides[i] = (size_t) view->strides[i];

This is bound to be problematic!

From Python's user manual (https://docs.python.org/3/c-api/buffer.html): 
>> Stride values can be any integer. For regular arrays, strides are usually positive, but a consumer MUST be able to handle the case `strides[n] <= 0`

I didn't have time to comb through the pybind11 code, are there any checks for negative strides?

Would it be OK if I tried to patch pybind11 to use signed strides?

**Comment by jagerman** [comment]
> Would it be OK if I tried to patch pybind11 to use signed strides?

Yes, definitely!  I noticed the same thing recently, but didn't have the time to fix it as I think it needs updating in quite a few places (not just `buffer_info` but also `numpy.h` and `eigen.h`).

**Comment by aldanor** [comment]
Yes indeed, they are `ssize_t` and not `size_t` iirc, certainly calls for a fix.

**Comment by crisluengo** [comment]
Good, in that case I'll try to look for time to fix this.

**Comment by dean0x7d** [comment]
Resolved in #782.
