### ISSUE TITLE
py::print causes bizarre error

### ISSUE THREAD

**Issue by nbecker** [pybind/pybind11#778]
When I add the py::print statement, I get:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-4257bd149e29> in <module>()
----> 1 FHT(np.zeros(16, dtype=complex))

RuntimeError: make_tuple(): unable to convert arguments of types 'std::tuple<int&, ndarray::ArrayRef<std::complex<double>, 1, 1> >' to Python object
```
Without the py::print there is no error.

This is truly bizarre.  py::print shouldn't affect the value returned from the function.

https://gist.github.com/nbecker/f99f32a5e587064b719a212ea8ec16a5

I ran this under valgrind and saw no issue

**Comment by aldanor** [comment]
Sounds like `ndarray` pybind11 bindings are interfering?

**Comment by jagerman** [comment]
The error isn't coming from the return, but from the `py::print` itself: pybind doesn't know how to convert ndarray::ArrayRef to a Python object to be able to pass it to Python's built-in `print`.

The error message there could be more helpful.

**Comment by nbecker** [comment]
Of course, that makes sense!  Sorry for the noise.

**Comment by jagerman** [comment]
As soon as the build tests finish I'll merge that change into `master`: it will improve the error message to

```RuntimeError: make_tuple(): unable to convert argument of type 'ndarray::ArrayRef<std::complex<double>, 1, 1>' to Python object```

**Comment by jagerman** [comment]
(Pushed to master).
