### ISSUE TITLE
Compilation error with mulitple class constructors

### ISSUE THREAD

**Issue by fengwang** [pybind/pybind11#809]
#### Issue description

When working with a multi-ctor class, compilation errors emitted.

> $ g++-6 -O3 -shared -std=c++14  `python3-config --cflags --ldflags` ./test.cc -o test.so                                                                           [0]
> cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
> In file included from ./test.cc:1:0:
> ././include/pybind11/pybind11.h: In instantiation of 'struct pybind11::detail::init<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<test>; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {void}]::<lambda>':
> ././include/pybind11/pybind11.h:1256:9:   required from 'static void pybind11::detail::init<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<test>; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {void}]'
> ././include/pybind11/pybind11.h:991:9:   required from 'pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const pybind11::detail::init<Args ...>&, const Extra& ...) [with Args = {void}; Extra = {}; type_ = test; options = {}]'
> ./test.cc:15:28:   required from here
> ././include/pybind11/pybind11.h:1256:56: error: invalid parameter type 'void'
>          cl.def("__init__", [](Base *self_, Args... args) { new (self_) Base(args...); }, extra...);
>                                                         ^
> ././include/pybind11/pybind11.h:1256:56: error: in declaration 'pybind11::detail::init<Args>::execute(Class&, const Extra& ...)::<lambda(Base*, Args ...)>'
> ././include/pybind11/pybind11.h:960:13: error: 'pybind11::class_<type_, options>& pybind11::class_<type_, options>::def(const char*, Func&&, const Extra& ...) [with Func = pybind11::detail::init<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<test>; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {void}]::<lambda>; Extra = {}; type_ = test; options = {}]', declared using local type 'pybind11::detail::init<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<test>; Extra = {}; typename std::enable_if<(! Class:: has_alias), int>::type <anonymous> = 0; Args = {void}]::<lambda>', is used but never defined [-fpermissive]
>      class_ &def(const char *name_, Func&& f, const Extra&... extra) {

#### Reproducible example code

```
#include "./include/pybind11/pybind11.h"

struct test
{
    test(){}
    test( int*, char, double ){}
};

PYBIND11_PLUGIN( test )
{
    namespace py = pybind11;
    py::module m( "test", " " );
    py::class_<test>( m, "test" )
    .def( py::init<void>() )
    .def( py::init<int*, char, double>() );

    return m.ptr();
}
```

#### Enviroment

mac os x with g++ 6.3.0(brewed) python3.6

**Comment by jagerman** [comment]
This:
```C++
    .def( py::init<void>() )
```
should just be:
```C++
    .def( py::init<>() )
```

**Comment by fengwang** [comment]
@jagerman  Problem solved. Thanks.

**Comment by fengwang** [comment]
@jagerman  Is it possible to add a partial template specialization for `void`?

**Comment by jagerman** [comment]
It's possible, but can I ask why you'd want this?

Also worth pointing out: the template types in py::init<...> are defining arguments to forward to the constructor, not the (C++) constructor signature.  The argument types don't even have to exactly match the invoked constructor as long as the types are implicitly convertible (e.g. `py::init<int>()` will happily invoke a `MyType(long)` constructor).  The only use I can see for supporting `sometype foo(void)` is C compatibility, but that seems meaningless for a constructor definition.

**Comment by wjakob** [comment]
Adding (void) to function signatures strikes me as relic of C that probably has little place in modern C++ code.
