### ISSUE TITLE
variant type

### ISSUE THREAD

**Issue by RedSkotina** [pybind/pybind11#810]
Can you give me advice how handle variant types(std::variant from c++17, mpark/variant for c++14, boost::variant and etc ) with pybind11?

**Comment by dean0x7d** [comment]
See the `type_caster` code and notes in https://github.com/pybind/pybind11/issues/576#issuecomment-269563199. That's using the custom type caster support as explained [here](http://pybind11.readthedocs.io/en/master/advanced/cast/custom.html).

This might actually be a good time to add `std::variant` support to `pybind11/stl.h` alongside `std::optional`. GCC 7, clang 4.0 and VS2017 all have `<variant>`. Users can also easily create specializations for third-party variants. I'll prepare a PR.

**Comment by RedSkotina** [comment]
thanks for explanation and  work on PR.
