### ISSUE TITLE
Bound methods not working correctly as callbacks

### ISSUE THREAD

**Issue by daid** [pybind/pybind11#814]
#### Issue description

When using bound methods of instantiated python objects as std::function callbacks, the "self" parameter is incorrectly set to the first parameter instead of the bound object. Causing exceptions and incorrect behavior when using callbacks with member bound objects.

I'm using:
python 3.4.2
pybind11 git hash deb85f46efcba5fea624ee89daea8144abd77c54
gcc: arm-linux-gnueabihf-gcc ( 4.9.2-10) 4.9.2

It seems like bound functions are getting the same handling as normal functions, and thus do not properly capture "self". In pure python code this happens automatically, I do not know enough about the python C API to guess where this could be going wrong.

#### Reproducible example code

C++ code from example:
```
#include <pybind11/functional.h>

int func_arg(const std::function<int(int)> &f) {
    return f(10);
}

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");
    m.def("func_arg", &func_arg);
    return m.ptr();
}
```

Python code:
```
import example
class Test:
  def boundMemberFunction(self, arg=-1): #default is needed, as pybind11 incorrectly does not fill the argument
    print(self, arg)
    return 1

t = Test()
example.func_arg(t.boundMemberFunction)
```

The boundMemberFunction incorrectly prints "10 -1", while I would expect it to print "<__main__.Test object at 0xa6c98070> 10"

**Comment by jagerman** [comment]
Thanks for the report and nice small reproducible example.  Can you confirm that PR #815 fixes it for you?

**Comment by daid** [comment]
That seems to fix it for the example, my bigger code base has some other problems that makes it hard to verify in in there (messing up object ownership somewhere causing crashes)

Thanks for the quick fix!
