### ISSUE TITLE
Conversion from bytes() to std::string

### ISSUE THREAD

**Issue by daid** [pybind/pybind11#816]
#### Issue description

Conversion from bytes() from python to std::string should be automatic according to the documentation at:
http://pybind11.readthedocs.io/en/master/advanced/cast/strings.html#passing-bytes-to-c

However, when I actually have a function that accepts std::string, passing a bytes object causes a TypeError.

python 3.4.2
pybind11 git hash deb85f4
gcc: arm-linux-gnueabihf-gcc ( 4.9.2-10) 4.9.2

With py::bytes also being available, I'm not sure if this is a bug in the code or an error in the documentation.

#### Reproducible example code

```
#include <pybind11/pybind11.h>

namespace py = pybind11;

void test(const std::string& s) {
}

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");
    m.def("test", &test, "");
    return m.ptr();
}
```

```
import example
example.test('x') # works
example.test(b'x') # TypeError
```

**Comment by jagerman** [comment]
Definitely looks like a bug.  (I also just checked--it doesn't affect Python 2, where it would probably be much more noticeable)
