### ISSUE TITLE
Regression in v2.1.1 returning Eigen Map Type

### ISSUE THREAD

**Issue by daveah** [pybind/pybind11#818]
#### Issue description

A simple test case that returns an Eigen::Map works fine with v2.0.0 but now segfaults with v2.1.1.  The issue appears to have been introduced with a change on 16 Jan 2017: https://github.com/pybind/pybind11/commit/f86dddf7ba45810c97dc2cf8e8cb6ee1e8477307

This is with python 2.7.2 and gcc 4.9.2

#### Reproducible example code
```
// The following test case should run fine on v2.0.0 but segfault on v2.1.1
#include "Eigen/Dense"
#include "pybind11/pybind11.h"
#include "pybind11/eigen.h"

namespace py = pybind11;

static Eigen::Map<Eigen::Matrix3i> return_eigen_map() {
  static int array[9];
  for (int ii = 0; ii < 9; ++ii) {
    array[ii] = ii;
  }
  return Eigen::Map<Eigen::Matrix3i>(array);
}

PYBIND11_PLUGIN(test_eigen_map) {
  py::module mm("test_eigen_map", "Eigen Map Tester");
  mm.def("return_eigen_map", &return_eigen_map)
  return mm.ptr();
}
```

**Comment by jagerman** [comment]
I can't seem to reproduce this.  Does the pybind test suite run successfully for you?

**Comment by jagerman** [comment]
What numpy version are you using?  I could reproduce a segfault by going all the way back to numpy 1.6.0 (which was released around the same time as Python 2.7.2).  Given that you bisected it to that commit, I suspect the issue may be that `SetBaseObject` doesn't exist in ancient numpy.

**Comment by jagerman** [comment]
Indeed: `PyArray_SetBaseObject` was added to numpy's C API in 1.7.

**Comment by daveah** [comment]
Confirmed, I'm on 1.6.1.

**Comment by jagerman** [comment]
Is it feasible for you to upgrade numpy (to at least 1.7.0)?  That change was rather important in keeping all the base references correct when interacting numpy and eigen types.

**Comment by jagerman** [comment]
#818 won't fix the numpy 1.6 support, but will at least give an informative error for requiring 1.7.0 rather than segfaulting.

**Comment by daveah** [comment]
Fully upgrading from 1.6.1 will be rather difficult.  There are some discussions on alternatives to PyArray_SetBaseObject in earlier versions of Numpy: e.g. https://mail.scipy.org/pipermail/numpy-discussion/2015-June/073061.html

**Comment by jagerman** [comment]
The code in 2.0 sets the base directly, but it was broken in that it doesn't follow references (which is a bit tricky).  I.e. if `a` owns its own data, `b` references `a`'s data, and `c` references `b`'s data, the correct base of `c` is `a`, not `b` (that is, `b` can go away without affecting `c`); but `a` also needs to know that it is referenced (which doesn't happen in the 2.0 code).  All of that ends up being quite important for the eigen<->numpy referencing support added in 2.1.

A numpy upgrade ought to be fairly easy without requiring any compilation, at least on a linux system: `python -m pip install --upgrade wheel numpy scipy` (you might need to install the python-pip package first if you don't already have it).

**Comment by jagerman** [comment]
For @daveah and anyone else who strongly needs this, [this patch](https://gist.github.com/jagerman/05f95f79b5a1e26d221de502f456b1d1) backports the numpy SetBaseObject code into pybind 2.1.1 and uses it rather than trying to load the function pointer via the numpy API, which should make pybind work with numpy 1.6.  This is not officially supported, but seems to work fine with the current test suite.

**Comment by daveah** [comment]
Thanks a lot.
