### ISSUE TITLE
Compiler error with return types in PYBIND11_OVERLOAD

### ISSUE THREAD

**Issue by ianhbell** [pybind/pybind11#824]
#### Issue description

When using the ``PYBIND11_OVERLOAD`` macro, the compiler MSVC 14 2015 chokes when the output type is something like ``std::pair<double, double>`` and yields an obscure error about a problem with a "*" symbol.  I suspect the same problem would manifest with most STL types.  A workaround is a typedef which seems to placate the compiler

#### Reproducible example code

**Bad**:
``` C++
class PyVLEIsolineTracer : public VLEIsolineTracer {
public:
    /* Inherit the constructors */
    using VLEIsolineTracer::VLEIsolineTracer;

    std::pair<double, double> get_integration_limits() override {
        // Release the GIL
        py::gil_scoped_release release;
        {
            // Acquire GIL before calling Python code
            py::gil_scoped_acquire acquire;

            // Parameters to macro are: Return type, parent class, name of function in C++, argument(s)
            PYBIND11_OVERLOAD(std::pair<double, double>, 
                              VLEIsolineTracer, 
                              get_integration_limits, 
                              // No arguments
                              );
        }
    }
};
```

**Good**:
``` C++
class PyVLEIsolineTracer : public VLEIsolineTracer {
public:
    /* Inherit the constructors */
    using VLEIsolineTracer::VLEIsolineTracer;

    std::pair<double, double> get_integration_limits() override {
        // Release the GIL
        py::gil_scoped_release release;
        {
            // Acquire GIL before calling Python code
            py::gil_scoped_acquire acquire;

            // Parameters to macro are: Return type, parent class, name of function in C++, argument(s)
            typedef std::pair<double, double> pairdoubledouble;
            PYBIND11_OVERLOAD(pairdoubledouble, 
                              VLEIsolineTracer, 
                              get_integration_limits, 
                              // No arguments
                              );
        }
    }
};
```

**Comment by wjakob** [comment]
See the documentation note about macro usage. The C++ preprocessor can't handle type-related commas in the  PYBIND11_OVERLOAD macro, so you'll need to refer to the type through a ``typedef`` or ``using Type = std::pair<...>`` alias.

**Comment by wjakob** [comment]
(In other words: this is not a pybind11 bug, it's a fundamental limitation of macro usage)

**Comment by ianhbell** [comment]
Can I provide some info to the docs to this effect?  Perhaps a small example?

**Comment by wjakob** [comment]
I think the docs are already plastered with references to the note about macros -- what would you change?

**Comment by jagerman** [comment]
It's already there, with almost exactly this example:

http://pybind11.readthedocs.io/en/master/advanced/misc.html?highlight=comma#general-notes-regarding-convenience-macros

**Comment by ianhbell** [comment]
Exactly my point: *almost* that example.  I’d add a dummy overload with a trampoline where there is a comma in the return type, and show how to overcome the problem with a typedef.  The compiler error is so obscure that an example would be merited IMHO.

**Comment by jagerman** [comment]
Extending it with a short "For example, ..." paragraph seems fine to me.
