### ISSUE TITLE
Documentation should point to latest release

### ISSUE THREAD

**Issue by mivade** [pybind/pybind11#826]
I am using pybind11 as a git submodule and have it checked out at the latest release tag. I was trying to use `py::call_guard` as described in the documentation on releasing the GIL only to get the following error with gcc:

```
error: ‘call_guard’ is not a member of ‘py’
```

After a little investigation, I found that `call_guard` was added more recently than the latest release. It would be helpful if the documentation on readthedocs pointed to the latest stable rather than the master branch to avoid this situation.

**Comment by phaustin** [comment]
thanks for this note -- just ran into this with py::call_guard<py::gil_scoped_release>()

**Comment by dean0x7d** [comment]
I also think this would be a nice change. It's come up as a source of confusion before. @wjakob What do you think about pointing to `stable` by default on RTD?

**Comment by wjakob** [comment]
Done -- good idea.

**Comment by mivade** [comment]
Thanks!
