### ISSUE TITLE
GCC 7.1 (mingw-w64) has broken -flto and hypot

### ISSUE THREAD

**Issue by RedSkotina** [pybind/pybind11#838]
For future:
GCC 7.1 (mingw-w64)
Just examine problem while compiling tests with unreferenced symbols on `Release` and `MinSizeRel` . 
`-flto` have mystic conflicts with -O3 or -Os 
Temp solution while gcc developers not fix bug: 
Disable -flto flag like this:
`cmake ..  -G"Ninja" -DPYBIND11_LTO_CXX_FLAGS=""`

mingw-w64 headers have conflict with python headers: 
`error: '::hypot' has not been declared`
we can fix it with redefining `-D_hypot=hypot`
`cmake ..  -G"Ninja" -DPYBIND11_LTO_CXX_FLAGS="" -DCMAKE_CXX_FLAGS="-D_hypot=hypot"`

**Comment by dean0x7d** [comment]
I assume this is informational since these are bugs related to mingw-w64 and not specifically pybind11. I'll close the issue for bookkeeping, but it will still show up in searches so others will be able to use the workarounds you suggested.
