### ISSUE TITLE
std::reference_wrapper accepts nullptr / None arguments

### ISSUE THREAD

**Issue by YannickJadoul** [pybind/pybind11#848]
Seems I'm able to pass None to a function that accepts an std::reference_wrapper. (While for an ordinary reference, I get the appropriate cast error.)

So I'm assuming this example is not supposed to give this output:

```C++
#include <pybind11/pybind11.h>
#include <iostream>

class A {};

void f(std::reference_wrapper<A> a)
{
	std::cout << "called with &a.get() == " << (void *) &a.get() << std::endl;
}

namespace py = pybind11;

PYBIND11_PLUGIN(test) {
    py::module m("test");

    py::class_<A>(m, "A")
        .def(py::init<>())
    ;

    m.def("f", &f);

    return m.ptr();
}
```

Python output:
```Python
>>> import test
>>> test.f(test.A())
called with &a.get() == 0x28dd7e0
>>> test.f(None)
called with &a.get() == 0
```

**Comment by YannickJadoul** [comment]
Actually, I just tried, and seems that just changing [line 504 in cast.h](https://github.com/pybind/pybind11/blob/master/include/pybind11/cast.h#L504) from
```C++
    operator std::reference_wrapper<type>() { return std::ref(*((type *) this->value)); }
```
to
```C++
    operator std::reference_wrapper<type>() { return std::ref(static_cast<type&>(*this)); }
```
already does the job.

**Comment by jagerman** [comment]
Looking at that code in a little more detail, I think the `reference_wrapper` issues go a little deeper.  I think it should be inheriting from `make_caster<type>`, not `type_caster_base<type>`, and then should be using `cast_op<T>` rather than either the pointer cast or static_cast.

**Comment by jagerman** [comment]
#849 addresses this (and the other issues).

**Comment by YannickJadoul** [comment]
Oh, wow, that's quick. Thanks!

Another related thing, then: Python 3's type hints have the [`Optional[T]`](https://docs.python.org/3/library/typing.html#typing.Optional) type annotation, which equals 'either the type or None' (as you probably know, because std::optional's caster generated that signature).

Would it be possible/interesting to show the difference between `T*` and `T&` in the generated signatures by using respectively `Optional[T]` for `T*`. Right now, looking at the docstrings, it is impossible for the Python user to tell whether he/she can or cannot pass None.

**Comment by wjakob** [comment]
> Would it be possible/interesting to show the difference between T* and T& in the generated signatures by using Optional[T] for T*. 

I'm against that. It would introduce countless ``Optional[]``s in virtually all wrapped C++ code, where that is not actually part of the API semantics.

**Comment by YannickJadoul** [comment]
Fair enough. I had just realized that `isinstance(None, T)` is never True for T != NoneType. But I guess that if anyone would wánt to make this explicit, you can still use `std::optional<T&>`.
