### ISSUE TITLE
buffer::request leaks on failure

### ISSUE THREAD

**Issue by bmerry** [pybind/pybind11#852]
#### Issue description

I haven't actually tested it, but this bit of code in pytypes.h looks a lot like a memory leak:
```c++
Py_buffer *view = new Py_buffer();
if (PyObject_GetBuffer(m_ptr, view, flags) != 0)
    throw error_already_set();
return buffer_info(view);
```
In the success case, the returned buffer_info owns `view`, but in the failure case `view` simply leaks.

**Comment by jagerman** [comment]
Thanks, fixed!
