### ISSUE TITLE
Problems wrapping member function defined in base class

### ISSUE THREAD

**Issue by bmerry** [pybind/pybind11#854]
#### Issue description

If a member function being wrapped by `py::class_::def` is actually implemented in a base class, then calling the member fails.

In the example code, it gives
```
Traceback (most recent call last):
  File "./testit.py", line 6, in <module>
    b.do_nothing()
TypeError: do_nothing(): incompatible function arguments. The following argument types are supported:
    1. (self: A) -> None

Invoked with: <pbtest._pbtest.B object at 0x7f1a691c3810>
```

This is presumably because the type of &B::do_nothing is actually `void (A::*)()` rather than `void (B::*)()`. While it can be fixed by explicitly casting it, it seems like it should be possible for pybind11 to fix this itself, since it knows at compile time which class is being wrapped.

#### Reproducible example code

C++:
```c++
#include <pybind11/pybind11.h>

namespace py = pybind11;

class A
{
public:
    void do_nothing() {}
};

class B : public A
{
public:
    using A::A;
};

PYBIND11_PLUGIN(_pbtest)
{
    py::module m("_pbtest");

    py::class_<B>(m, "B")
        .def(py::init<>())
        .def("do_nothing", &B::do_nothing);

    return m.ptr();
}
```

Python:
```python
from pbtest._pbtest import B

b = B()
b.do_nothing()
```

**Comment by bmerry** [comment]
One fix might to be an overload `py::class_::def` that takes pointers-to-members, then casts them to fix the referring class. One question I don't have a strong opinion on is what should happen if one passes a pointer-to-member of an unrelated class for which there is an implicit conversion: should it be a compile error or should `*this` be converted to the other type before invoking the pointer to member? At the moment the latter seems to happen.

**Comment by bmerry** [comment]
The issue also seem to affect pointers to members defined by `def_readonly` and `def_readwrite`.

**Comment by jagerman** [comment]
#855 should address this.  I didn't do anything about non-base-class member function pointers; I don't see that they hurt anything, even if they are a bit obscure.
