### ISSUE TITLE
Where is "example.pyd" which is supposed to be created in First steps if I am using Visual Studio 2015?

### ISSUE THREAD

**Issue by zhou-heng** [pybind/pybind11#870]
Make sure you've completed the following steps before submitting your issue -- thank you!
You can remove this template text afterward.

1. Check if your question has already been answered in the [FAQ](http://pybind11.readthedocs.io/en/latest/faq.html) section.
2. Make sure you've read the [documentation](http://pybind11.readthedocs.io/en/latest/). Your issue may be addressed there.
3. If those resources didn't help and you only have a short question (not a bug report), consider asking in the [Gitter chat room](https://gitter.im/pybind/Lobby).
4. If you have a genuine bug report or a more complex question which is not answered in the previous items (or not suitable for chat), please fill in the details below.
5. Include a self-contained and minimal piece of code that reproduces the problem. If that's not possible, try to make the description as clear as possible.

#### Issue description

(Provide a short description, state the expected behavior and what actually happens.)
Where is "example.pyd"?

#### Reproducible example code

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete C++ and Python snippets that can be easily compiled and run to diagnose the issue.)

I am trying to follow the Document: First steps->Creating bindings for a simple function. Instead of CMake, I am using Visual Studio 2015 to build the simple addition example. The compile and link both succeeded but when I tried to continue with the document, I am dumbfounded at "(example.pyd on Windows)" -- Where is example.pyd?

This is the config of VS2015:
- I build the sample under x64 configuration
- The output format is set to DLL (In Property page->General->Configuration Type, set "Dynamic Library (.dll)". I changed it to Static Library but there is no example.pyd either.

The output files are ConsoleApplication2.dll (the project name is ConsoleApplication2), ConsoleApplication2.lib, example.obj, ... but I can't find any file named example.pyd, and not surprisingly I got error "No module named example" in python. So what is the example.pyd? where is it? How to generate it in Visual Studio 2015?

I know the Document mentions CMake and perhaps CMake can automatically generate example.pyd, but I am a Windows user and it is a natural choice to use VS to develop on Windows. You can't force your Windows user to stop using Visual Studio, right? So what are the steps for pybind11 to work with VS2015? Thanks.

**Comment by jagerman** [comment]
Try renaming `ConsoleApplication2.dll` to `example.pyd`.

I'm not a VS user, so I have no idea how to set the output filename for compilation within VS.

**Comment by zhou-heng** [comment]
Yes! This is the trick I am looking for. Thank you so much!

To set the output file extension to pyd In VS2015, Property
Pages->General->Target Extension->set to ".pyd".

**Comment by jagerman** [comment]
Happy to help.
