### ISSUE TITLE
Installing resulting module

### ISSUE THREAD

**Issue by mbrucher** [pybind/pybind11#873]
I'm trying to install the resulting module after a call to:

pybind11_add_module(Core ${PYTHON_MODULE_Core_SRC} ${PYTHON_MODULE_Core_HEADERS})

For this, I did:
SET(
    ATK_CORE_PYTHON
    __init__.py Core
)
and then:
INSTALL(FILES ${ATK_CORE_PYTHON}
    DESTINATION ${PYTHON_INSTALL_FOLDER}/site-packages/ATK/Core
    )

Which went fine with SWIG. But now, I get a file in Core/Release named Core (and not Core.pyd on Windows???) and it can't get installed.
What are the proper steps to install a pybind11 module with CMake and what should I check for the file name?

**Comment by mbrucher** [comment]
After calling find_package(PythonLibsNew), I got a Core file that had the proper extension, but the name is not what I expected.
Anyway, installing the file the way I showed beore doesn't work, but I think it should have. Or there is something missing but I can't find anything in the documentation.
The lack of installation capability is quite a big stopper :/

**Comment by jagerman** [comment]
`pybind11_add_module(Core ...)` is going to give you a CMake `Core` target; you'll want to install that by the target name, rather than filename, using `install(TARGETS Core DESTINATION ...)` which should copy the proper .so/.pyd, whatever the actual proper suffixed library name is.

**Comment by mbrucher** [comment]
Thanks, I'll use targets, I didn't know about this one, always used FILES (meaning I have a bunch of things to update to make it proper).
Importing a module with this complex extension is still the same? if the file is named bar.cp36_xxxx.pyd, import bar still works as expected?

**Comment by mbrucher** [comment]
Seems like import bar checks the proper names, so closed now.

Thanks!
