### ISSUE TITLE
Difference in behavior with inheritance across modules between Windows and MacOS/Linux

### ISSUE THREAD

**Issue by mbrucher** [pybind/pybind11#877]
I've encountered another issue while porting Audio ToolKit to pybind11.
There are several modules defined in the library, all driving from a parent class in a module named Core.
On Windows, I defined in the Core bindings the Python declaration fo the base class as such: https://github.com/mbrucher/AudioTK/blob/feature/pybind11/Python/Core/Core.cpp
After, in the EQ module, I declared the inheritance: https://github.com/mbrucher/AudioTK/blob/feature/pybind11/Python/EQ/EQ.cpp and when running tests, Python/pybind11 could find all the links and everything was fine.
On macOS, I got this: ImportError: generic_type: type "FloatSecondOrderBaseCoefficients" referenced unknown base type "ATK::TypedBaseFilter<float, float>"
"ATK::TypedBaseFilter<float, float>" is a type defined in the Core, and strangely, pybind11 couldn't find the definition in its memory, even if I force the import of Core before.

How is inheritance across modules supposed to work? Am I doing something crazy that no one did before?

**Comment by jagerman** [comment]
Inheritance across modules require that you declare the inheritance as a constructor argument, rather than specifying the type as a template argument.  See http://pybind11.readthedocs.io/en/stable/advanced/misc.html#partitioning-code-over-multiple-extension-modules for an example of doing this.

**Comment by mbrucher** [comment]
Excellent, I didn't see that page.
Strange that it does work on Windows and actually Linux, but not macOS.

Thanks a lot for your help today!

**Comment by mbrucher** [comment]
Actually, seems like py::module::import should have worked, but import("..Core") or import ("ATK.Core") don't seem to declare the proper types :/

**Comment by mbrucher** [comment]
Thanks, importing the object itself worked. Probably worth changing the doc, as it says that it should have worked.

**Comment by jagerman** [comment]
The main issue is that `typeid()` and `std::type_index` aren't guaranteed to be the same across different `.so`s.  They could be, which appears to be the case for gcc/MSVC, but don't have to be, which appears to be the case for clang.

I'm not quite sure what the failed import is about; you want something like: `auto other_m = py::module::import("other"); py::class_<Foo>(m, "Foo", other_m.attr("BaseClass"))`
