### ISSUE TITLE
py::eval functioning differently on Windows and Ubuntu

### ISSUE THREAD

**Issue by jmanek** [pybind/pybind11#883]
TL;DR: When accessing and modiyfing a singleton class through python scripts evaluated with py::eval, Ubuntu (14/16) maintains a single object between the C++ and Python layer, while Windows appears to duplicate the object.

I have a singleton class that I have wrapped with pybind.  I am also trying trying to access and modify this class through the pybind interpreter.  Since I want to support arbitrary code execution of scripts and files I am using py::eval.  Say I have modified the singleton class in C++, then later call py::eval on a script that accesses this singleton class. On Ubuntu, the same singleton object is shared between the C++ and Python layer, and changes to the object are shared.  On Windows, no changes persist between the layers.

Given the code below, the output on Ubuntu is:
```
C++: Foo is 2
Python: Foo is 2
Python: Foo is 3
C++: Foo is 3
```
And on Windows 
```
C++: Foo is 2
Python: Foo is 0
Python: Foo is 3
C++: Foo is 2
```

I have tried Python 2.7 and 3.4 on Windows.  And 2.7, 3.4, 3.4, 3.6 on Ubuntu.  For compiling on Windows I have tried MSVC 2015 and 2017.  On Ubuntu I have tried gcc 5.x and 6.x.  The results have been the same.  I am under the assumption this is an issue with how libraries are being loaded, and how that is handled differently between the two operating systems.  However I don't have much more to go on than that.  Is there an obvious mistake being made here?  If not is there a direction I can explore to work on resolving this?

#### Reproducible example code

main.cpp
```
#include <pybind11/embed.h>
#include "Foo.h"
#include <iostream>
namespace py = pybind11;
using namespace std;
int main() {
	py::scoped_interpreter guard{};
	Foo::get().setVal(2);
	cout << "C++: Foo is " << Foo::get().getVal() << endl;
	py::object globals = py::module::import("__main__").attr("__dict__");
	py::object locals = py::dict();
	py::eval<py::eval_statements>(R"(
				import Foo_Py
				print('Python: Foo is ' + str(Foo_Py.Foo.get().getValue()))
				Foo_Py.Foo.get().setValue(3)
				print('Python: Foo is ' + str(Foo_Py.Foo.get().getValue()))

			)", globals, locals);

	cout << "C++: Foo is " << Foo::get().getVal() << endl;
}
```
Foo_Py.cpp
```
#include <pybind11/pybind11.h>
#include "Foo.h"
#include <memory>
using namespace std;
namespace py = pybind11;

PYBIND11_PLUGIN(Foo_Py) {
	py::module m("Foo_Py");
	py::class_<Foo, unique_ptr<Foo, py::nodelete>>(m, "Foo")
		.def_static("get", &Foo::get, py::return_value_policy::reference)
		.def("getValue", &Foo::getVal)
		.def("setValue", &Foo::setVal);

	return m.ptr();
}

```
Foo.h
```
#pragma once
#include <memory>
using namespace std;
class Foo {
public:
	static Foo& get();
	int getVal() const;
	void setVal(int v);
protected:
	Foo();
	~Foo();
private:
	int _val;
};
```
Foo.cpp
```
#pragma once
#include "Foo.h"
using namespace std;

Foo &Foo::get() {
	static Foo _instance;
	return _instance;
}
int Foo::getVal() const { return _val; }
void Foo::setVal(int v) { _val = v; }
Foo::Foo() : _val(0) {}
Foo::~Foo() {}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.5)
project(pybindtests)

# These are specific to my environment and can be ignored
# _________________________________________________________
if(WIN32)
	set(PYTHON_EXECUTABLE "C:\\python34\\python.exe")
else()
	# Was 3.5, but also tried 2.7, 3.4, 3.6
	set(PYTHON_EXECUTABLE "/usr/bin/python3")
endif()
if(WIN32)
	# This issue existed with pybind v2.1.1 and is not specific to the recent interpreter commits
	set(pybind11_DIR "${CMAKE_SOURCE_DIR}\\..\\toolsets\\pybind11\\6d2411f\\Build\\Windows\\x64\\Release\\share\\cmake\\pybind11")
else()
	set(pybind11_DIR "${CMAKE_SOURCE_DIR}/../toolsets/pybind11/6d2411f/Build/Linux/x86_64/mock_install/share/cmake/pybind11")
endif()
# _________________________________________________________

set(CMAKE_POSITION_INDEPENDENT_CODE ON)
find_package(pybind11 REQUIRED)
# Singleton class
add_library(Foo Foo.h Foo.cpp)
# interpreter
add_executable(tests main.cpp)
# bindings
pybind11_add_module(Foo_Py  SHARED Foo_Py.cpp)
target_link_libraries(Foo_Py PRIVATE Foo)
target_link_libraries(tests PRIVATE pybind11::embed Foo_Py Foo)
```

**Comment by jagerman** [comment]
I'm not much of a MSVC programmer, but try adding `__declspec(dllexport)` to the function under MSVC.

[More info here](https://stackoverflow.com/questions/4911994/sharing-a-global-static-variable-between-a-process-and-dll).

**Comment by jagerman** [comment]
See also the section of the docs on [partitioning over multiple modules](http://pybind11.readthedocs.io/en/stable/advanced/misc.html#partitioning-code-over-multiple-extension-modules).  It's not quite what you're doing, but the bits about symbol visibility about halfway down apply to you.

**Comment by jmanek** [comment]
Thanks for the suggestion, adding __declspec(dllexport) to the declaration of Class Foo resolves the issue!

**Comment by jagerman** [comment]
There's also a PYBIND11_EXPORT macro you can use which does the same thing (but instead expands to a default-visibility attribute under gcc/clang, which you probably also want).  It's not explicitly documented, but it's fairly unlikely that it would go away.
