### ISSUE TITLE
py::cast gives exception with -1

### ISSUE THREAD

**Issue by amkigit** [pybind/pybind11#884]
Hello,

in pybind11, version 2.1.0 casting a value of -1 causes an exception, casting -2 works.

        a1 = py::int_(-2);
	o1 = py::object(a1);
	l = o1.cast<long long>();

	a1 = py::int_(-1);
	o1 = py::object(a1);

The error occurs in cast.h line 522:
     if ((py_value == (py_type) -1 && PyErr_Occurred()) || ...

Please find a short example program attached:

[castError.txt](https://github.com/pybind/pybind11/files/1038563/castError.txt)

Alfred

**Comment by jagerman** [comment]
What's the exception that you get?

The attached program, as is, won't work (I'm surprised you get as far as an exception with it rather than a segfault).  If you want to control `main` yourself, you need to [embed the interpreter](http://pybind11.readthedocs.io/en/master/advanced/embedding.html).  If I change your code to use `PYBIND11_MODULE`, I don't get any exception from the cast.  Can you confirm that this example works or fails for you:

```C++
// neg1.cpp
#include <pybind11/pybind11.h>
namespace py = pybind11;

PYBIND11_MODULE(neg1, m) {
    m.def("f", []() {
        py::list ret;
        long l;

        auto a1 = py::int_(1);
        auto o1 = py::object(a1);
        l = o1.cast<long>();
        ret.append(l);

        a1 = py::int_(-2);
        o1 = py::object(a1);
        l = o1.cast<long long>();
        ret.append(l);

        a1 = py::int_(-1);
        o1 = py::object(a1);

        // Exception
        l = o1.cast<long long>();
        ret.append(l);
        return ret;
    });
}
```

```Python
>>> import neg1
>>> neg1.f()
[1, -2, -1]
```

Here's the embedded interpreter version:
```C++
// neg2.cpp
#include <pybind11/pybind11.h>
#include <pybind11/embed.h>

namespace py = pybind11;

int main() {
    py::scoped_interpreter python;

    py::list ret;
    long l;

    auto a1 = py::int_(1);
    auto o1 = py::object(a1);
    l = o1.cast<long>();
    ret.append(l);

    a1 = py::int_(-2);
    o1 = py::object(a1);
    l = o1.cast<long long>();
    ret.append(l);

    a1 = py::int_(-1);
    o1 = py::object(a1);

    // Exception
    l = o1.cast<long long>();
    ret.append(l);

    py::print(ret);
}
```

```bash
$ g++ neg2.cpp -I../include -I/usr/include/python3.5 -lpython3.5m -o neg2
$ ./neg2
[1, -2, -1]
```

**Comment by jagerman** [comment]
Closing due to lack of response.  Feel free to reopen if there is still an issue here.
