### ISSUE TITLE
PyPy, Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by kashirin-alex** [pybind/pybind11#886]
Hello, 
Trying to compile a module to use with PyPy and fail with Fatal Python error: PyThreadState_Get: no current thread. if to compile the same module for Python, it is working.

```
# pypy
Python 2.7.13 (1aa2d8e03cdfab54b7121e93fda7e98ea88a30bf, May 30 2017, 06:06:44)
[PyPy 5.7.1 with GCC 7.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import imp
>>>> imp.load_dynamic('libHyperPyPy','/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPyPy.so')
Fatal Python error: PyThreadState_Get: no current thread
Aborted
```

The source code of the module is:
https://github.com/kashirin-alex/hypertable/blob/master/src/cc/HyperPython/SerializedCells_pyBind11.cc
and It's cmake file is:
https://github.com/kashirin-alex/hypertable/blob/master/src/cc/HyperPython/CMakeLists.txt
The original working boost based release version of the module is at: 
https://github.com/kashirin-alex/hypertable/blob/master/src/cc/HyperPython/SerializedCells.cc

The commands that are issued to compile are:

### [100%] Building CXX object src/cc/HyperPython/CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o

- cd /root/builds/builts/hypertable/src/cc/HyperPython && /usr/bin/c++  -DHyperPyPy_EXPORTS -I/root/builds/sources/hypertable/src/cc -I/root/builds/builts/hypertable/src/cc -I/usr/local/include -I/usr/local/include/thrift -I/usr/local/include/python2.7  -DHAVE_NETINET_IN_H  -Wno-long-long -Wall -Wno-unknown-pragmas -pedantic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -std=c++11 -DTCMALLOC_MINIMAL -DHT_WITH_THRIFT -Wno-variadic-macros -O3 -DNDEBUG -fPIC   -flto -DPYPY_VERSION=5.7.1 -DPYTHON_EXECUTABLE=/opt/pypy2/bin/pypy -o CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o -c /root/builds/sources/hypertable/src/cc/HyperPython/SerializedCells_pyBind11.cc

### [100%] Linking CXX shared module libHyperPyPy.so

- cd /root/builds/builts/hypertable/src/cc/HyperPython && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/HyperPyPy.dir/link.txt --verbose=1
- /usr/bin/c++ -fPIC -DHAVE_NETINET_IN_H  -Wno-long-long -Wall -Wno-unknown-pragmas -pedantic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -std=c++11 -DTCMALLOC_MINIMAL -DHT_WITH_THRIFT -Wno-variadic-macros -O3 -DNDEBUG  -shared  -o libHyperPyPy.so CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o -Wl,-rpath,/root/builds/builts/hypertable/src/cc/ThriftBroker:/root/builds/builts/hypertable/src/cc/Hypertable/Lib:/root/builds/builts/hypertable/src/cc/Hyperspace:/root/builds/builts/hypertable/src/cc/Tools/Lib:/root/builds/builts/hypertable/src/cc/FsBroker/Lib:/root/builds/builts/hypertable/src/cc/AsyncComm:/root/builds/builts/hypertable/src/cc/Common:/root/builds/builts/hypertable/src/cc/ThirdParty: ../ThriftBroker/libHyperThrift.so ../Hypertable/Lib/libHypertable.so -lpython2.7 -lthrift -lthriftnb -levent ../Hyperspace/libHyperspace.so ../Tools/Lib/libHyperTools.so -ledit ../FsBroker/Lib/libHyperFsBroker.so ../AsyncComm/libHyperComm.so ../Common/libHyperCommon.so -lexpat -lsigar-amd64-linux -ldl -lboost_iostreams -lboost_program_options -lboost_filesystem -lboost_thread -lboost_system -lboost_chrono -lboost_python -lpython2.7 -lz -lsnappy -lncurses -lpthread -lre2 -ltcmalloc_minimal -lunwind -lssl -lcrypto ../ThirdParty/libHyperThirdParty.so -lm

## WITH_THREAD: 
follow some facts tried as well with the -DWITH_THREAD (https://github.com/pybind/pybind11/blob/acedd6c70ce192e79047fe5111287fbc14b1eab5/include/pybind11/cast.h#L64)
### [100%] Building CXX object src/cc/HyperPython/CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o

- cd /root/builds/builts/hypertable/src/cc/HyperPython && /usr/bin/c++  -DHyperPyPy_EXPORTS -I/root/builds/sources/hypertable/src/cc -I/root/builds/builts/hypertable/src/cc -I/usr/local/include -I/usr/local/include/thrift -I/usr/local/include/python2.7  -DHAVE_NETINET_IN_H  -Wno-long-long -Wall -Wno-unknown-pragmas -pedantic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -std=c++11 -DTCMALLOC_MINIMAL -DHT_WITH_THRIFT -Wno-variadic-macros -O3 -DNDEBUG -fPIC   -flto -DPYTHON_VERSION=2.7 -DPYPY_VERSION=5.7.1 -DWITH_THREAD -DPYTHON_EXECUTABLE=/opt/pypy2/bin/pypy -o CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o -c /root/builds/sources/hypertable/src/cc/HyperPython/SerializedCells_pyBind11.cc

### [100%] Linking CXX shared module libHyperPyPy.so
- cd /root/builds/builts/hypertable/src/cc/HyperPython && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/HyperPyPy.dir/link.txt --verbose=1
- /usr/bin/c++ -fPIC -DHAVE_NETINET_IN_H  -Wno-long-long -Wall -Wno-unknown-pragmas -pedantic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -std=c++11 -DTCMALLOC_MINIMAL -DHT_WITH_THRIFT -Wno-variadic-macros -O3 -DNDEBUG  -shared  -o libHyperPyPy.so CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o -Wl,-rpath,/root/builds/builts/hypertable/src/cc/ThriftBroker:/root/builds/builts/hypertable/src/cc/Hypertable/Lib:/root/builds/builts/hypertable/src/cc/Hyperspace:/root/builds/builts/hypertable/src/cc/Tools/Lib:/root/builds/builts/hypertable/src/cc/FsBroker/Lib:/root/builds/builts/hypertable/src/cc/AsyncComm:/root/builds/builts/hypertable/src/cc/Common:/root/builds/builts/hypertable/src/cc/ThirdParty: ../ThriftBroker/libHyperThrift.so ../Hypertable/Lib/libHypertable.so -lpython2.7 -lthrift -lthriftnb -levent ../Hyperspace/libHyperspace.so ../Tools/Lib/libHyperTools.so -ledit ../FsBroker/Lib/libHyperFsBroker.so ../AsyncComm/libHyperComm.so ../Common/libHyperCommon.so -lexpat -lsigar-amd64-linux -ldl -lboost_iostreams -lboost_program_options -lboost_filesystem -lboost_thread -lboost_system -lboost_chrono -lboost_python -lpython2.7 -lz -lsnappy -lncurses -lpthread -lre2 -ltcmalloc_minimal -lunwind -lssl -lcrypto ../ThirdParty/libHyperThirdParty.so -lm

#### on Python directly
the load is failing but it is probably of the fact it is built for PyPY
```
# python
Python 2.7.13 (default, May 30 2017, 06:10:15)
[GCC 7.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import imp
>>> imp.load_dynamic('libHyperPython','/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPython.so')
<module 'libHyperPython' from '/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPython.so'>
>>> imp.load_dynamic('libHyperPyPy','/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPyPy.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: NameError: name 'property' is not defined
```
##### While the expected result should be:

- the Boost::python version
```
>>> imp.load_dynamic('libHyperPython','/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPython.so')
<module 'libHyperPython' from '/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPython.so'>
>>> import libHyperPython
>>> print dir(libHyperPython)
['Cell', 'SerializedCellsReader', 'SerializedCellsWriter', '__doc__', '__file__', '__name__', '__package__']
>>>
```
- the PyBind11 version being the without the flag -DPYPY_VERSION=5.7.1 on compile:
```
# python
Python 2.7.13 (default, May 30 2017, 06:10:15)
[GCC 7.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import imp
>>> imp.load_dynamic('libHyperPyPy','/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPyPy.so')
<module 'libHyperPyPy' from '/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPyPy.so'>
>>> import libHyperPyPy
>>> print dir(libHyperPyPy)
['Cell', 'SerializedCellsReader', 'SerializedCellsWriter', '__doc__', '__file__', '__name__', '__package__']
>>>
```

The environment is as at https://github.com/kashirin-alex/environments-builder/blob/master/debian/build-debian-env.sh

Thank You,
Kashirin Alex

**Comment by kashirin-alex** [comment]
a ref to this issue on PyPy board:
https://bitbucket.org/pypy/pypy/issues/2566/importing-shared-library-pypy-fatal-python

**Comment by jagerman** [comment]
The commands used to compile and link look wrong to me:

> `cd /root/builds/builts/hypertable/src/cc/HyperPython && /usr/bin/c++ ... -I/usr/local/include/python2.7 ...`

is caused because you're already called `find_package(Python)` in the root CMakeLists.txt.

You're also trying to *compile* with [various defines](https://github.com/kashirin-alex/hypertable/blob/master/src/cc/HyperPython/CMakeLists.txt#L52), but those are not going to work: `PYTHON_EXECUTABLE` is a CMake variable understood by the pybind11 CMake scripts, *not* a compile options.  Setting `PYPY_VERSION`/`PYTHON_VERSION`/`WITH_THREAD` is never something you should be doing manually: those should come from the Python/PyPy headers themselves.  (In this case, setting `PYPY_VERSION` is probably making pybind think it's compiling for PyPy, even though the available headers in the search path are actually for Python 2.7).

Suggested fix: you can simplify your `CMakeLists.txt` greatly if you take out the `find_package(Python)` from your root `CMakeLists.txt`, and instead use `find_package(pybind11)` coupled with [the provided cmake functions](http://pybind11.readthedocs.io/en/stable/compiling.html#building-with-cmake).  Let pybind11 find Python and extract the required include path from it.

**Comment by kashirin-alex** [comment]
I'll go and try to equalize the lib's cmake to be as the process of http://pybind11.readthedocs.io/en/stable/compiling.html#building-with-cmake

while, I can't see/find any mentions of PyPy on the cmake files, except the https://github.com/pybind/pybind11/blob/6d2411f1ac09b5669ab48834fb38079bb4ca95b9/tests/test_embed/CMakeLists.txt
which would indicate the different headers to use,
on my sys, i can find, two Python.h:
- /opt/pypy2/include/Python.h
- /usr/local/include/python2.7/Python.h

and they are different:
```
root@ns2-2 ~/builds/builts/hypertable # ls -l /usr/local/include/python2.7/Python.h
-rw-r--r-- 1 root root 4329 May 30 06:11 /usr/local/include/python2.7/Python.h
root@ns2-2 ~/builds/builts/hypertable # ls -l /opt/pypy2/include/Python.h
-r--r--r-- 1 root root 3868 May 30 08:06 /opt/pypy2/include/Python.h
```

in base, all of the additional flags are required to compile the lib's dependencies
 -fPIC -DHAVE_NETINET_IN_H -Wno-long-long -Wall -Wno-unknown-pragmas -pedantic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -std=c++11 -DTCMALLOC_MINIMAL -DHT_WITH_THRIFT -Wno-variadic-macros -O3 -DNDEBUG -shared -o libHyperPyPy.so CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o -Wl,-rpath,/root/builds/builts/hypertable/src/cc/ThriftBroker:/root/builds/builts/hypertable/src/cc/Hypertable/Lib:/root/builds/builts/hypertable/src/cc/Hyperspace:/root/builds/builts/hypertable/src/cc/Tools/Lib:/root/builds/builts/hypertable/src/cc/FsBroker/Lib:/root/builds/builts/hypertable/src/cc/AsyncComm:/root/builds/builts/hypertable/src/cc/Common:/root/builds/builts/hypertable/src/cc/ThirdParty: ../ThriftBroker/libHyperThrift.so ../Hypertable/Lib/libHypertable.so -lpython2.7 -lthrift -lthriftnb -levent ../Hyperspace/libHyperspace.so ../Tools/Lib/libHyperTools.so -ledit ../FsBroker/Lib/libHyperFsBroker.so ../AsyncComm/libHyperComm.so ../Common/libHyperCommon.so -lexpat -lsigar-amd64-linux -ldl -lboost_iostreams -lboost_program_options -lboost_filesystem -lboost_thread -lboost_system -lboost_chrono -lboost_python -lpython2.7 -lz -lsnappy -lncurses -lpthread -lre2 -ltcmalloc_minimal -lunwind -lssl -lcrypto ../ThirdParty/libHyperThirdParty.so -lm

**Comment by kashirin-alex** [comment]
sorry, about the PyPy is not mentioned, it is worked by the Python interp

New results: (now it is using the /opt/pypy2/include/Python.h)
attached, is the cmake and cpp , while a symlink to pybind11 root is made in the mod folder
```
# cmake ./ -DPYBIND11_PYTHON_VERSION=2.7  -DPYTHON_EXECUTABLE=/opt/pypy2/bin/pypy
-- The C compiler identification is GNU 7.1.0
-- The CXX compiler identification is GNU 7.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /opt/pypy2/bin/pypy (found suitable version "2.7.13", minimum required is "2.7")
-- Found PythonLibs: python2.7
-- pybind11 v2.2.dev0
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- Performing Test HAS_CPP11_FLAG
-- Performing Test HAS_CPP11_FLAG - Success
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /root/tmpBuilds/pybind11/test
root@ns2-2 ~/tmpBuilds/pybind11/test # make VERBOSE=1
/usr/local/bin/cmake -H/root/tmpBuilds/pybind11/test -B/root/tmpBuilds/pybind11/test --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /root/tmpBuilds/pybind11/test/CMakeFiles /root/tmpBuilds/pybind11/test/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/root/tmpBuilds/pybind11/test'
make -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/depend
make[2]: Entering directory '/root/tmpBuilds/pybind11/test'
cd /root/tmpBuilds/pybind11/test && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /root/tmpBuilds/pybind11/test /root/tmpBuilds/pybind11/test /root/tmpBuilds/pybind11/test /root/tmpBuilds/pybind11/test /root/tmpBuilds/pybind11/test/CMakeFiles/example.dir/DependInfo.cmake --color=
Dependee "/root/tmpBuilds/pybind11/test/CMakeFiles/example.dir/DependInfo.cmake" is newer than depender "/root/tmpBuilds/pybind11/test/CMakeFiles/example.dir/depend.internal".
Dependee "/root/tmpBuilds/pybind11/test/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/root/tmpBuilds/pybind11/test/CMakeFiles/example.dir/depend.internal".
Scanning dependencies of target example
make[2]: Leaving directory '/root/tmpBuilds/pybind11/test'
make -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
make[2]: Entering directory '/root/tmpBuilds/pybind11/test'
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
/usr/bin/c++  -Dexample_EXPORTS -I/root/tmpBuilds/pybind11/test/pybind11/include -I/opt/pypy2/include  -fPIC   -std=c++14 -flto -fno-fat-lto-objects -o CMakeFiles/example.dir/example.cpp.o -c /root/tmpBuilds/pybind11/test/example.cpp
[100%] Linking CXX shared module example.pypy-41.so
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/example.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC   -shared  -o example.pypy-41.so CMakeFiles/example.dir/example.cpp.o -flto
make[2]: Leaving directory '/root/tmpBuilds/pybind11/test'
[100%] Built target example
make[1]: Leaving directory '/root/tmpBuilds/pybind11/test'
/usr/local/bin/cmake -E cmake_progress_start /root/tmpBuilds/pybind11/test/CMakeFiles 0
```

now it is a new error:
```

imp.load_dynamic('example','/root/tmpBuilds/pybind11/test/example.pypy-41.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: function _cffi_pypyinit_example or initexample not found in library /root/tmpBuilds/pybind11/test/example.pypy-41.so
```
missing the:
> PyMODINIT_FUNC #https://docs.python.org/2/extending/extending.html

- -- Should the module example.ccp include anything regarding the function _cffi_pypyinit_example or initexample ?


[example.zip](https://github.com/pybind/pybind11/files/1040325/example.zip)

**Comment by kashirin-alex** [comment]
GOT IT WORKING:
```
# pypy
Python 2.7.13 (1aa2d8e03cdfab54b7121e93fda7e98ea88a30bf, May 30 2017, 06:06:44)
[PyPy 5.7.1 with GCC 7.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import imp
>>>> imp.load_dynamic('libHyperPyPy','/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPyPy.so')
<module 'libHyperPyPy' from '/root/builds/builts/hypertable/src/cc/HyperPython/libHyperPyPy.so'>
>>>> import libHyperPyPy
>>>> print dir(libHyperPyPy)
['Cell', 'SerializedCellsReader', 'SerializedCellsWriter', '__doc__', '__file__', '__name__', '__package__']
>>>>
```

new cmake files organized into:
- https://github.com/kashirin-alex/hypertable/blob/master/cmake/FindPython.cmake
- https://github.com/kashirin-alex/hypertable/blob/master/src/cc/HyperPython/CMakeLists.txt

compiler commands are:
### [100%] Building CXX object src/cc/HyperPython/CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o
- cd /root/builds/builts/hypertable/src/cc/HyperPython &&  /usr/bin/c++  -DHyperPyPy_EXPORTS -I/root/builds/sources/hypertable/src/cc -I/root/builds/builts/hypertable/src/cc -I/usr/local/include -I/usr/local/include/thrift -I/opt/pypy2/include  -DHAVE_NETINET_IN_H  -Wno-long-long -Wall -Wno-unknown-pragmas -pedantic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -std=c++11 -DTCMALLOC_MINIMAL -DHT_WITH_THRIFT -Wno-variadic-macros -O3 -DNDEBUG -fPIC   -flto -DPYTHON_VERSION=2.7 -DPYPY_VERSION=1 -DWITH_THREAD -o CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o -c /root/builds/sources/hypertable/src/cc/HyperPython/SerializedCells_pyBind11.cc

### [100%] Linking CXX shared module libHyperPyPy.so
- cd /root/builds/builts/hypertable/src/cc/HyperPython && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/HyperPyPy.dir/link.txt --verbose=1
- /usr/bin/c++ -fPIC -DHAVE_NETINET_IN_H  -Wno-long-long -Wall -Wno-unknown-pragmas -pedantic -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC -std=c++11 -DTCMALLOC_MINIMAL -DHT_WITH_THRIFT -Wno-variadic-macros -O3 -DNDEBUG  -shared  -o libHyperPyPy.so CMakeFiles/HyperPyPy.dir/SerializedCells_pyBind11.cc.o  -L/opt/pypy2/bin -Wl,-rpath,/root/builds/builts/hypertable/src/cc/ThriftBroker:/root/builds/builts/hypertable/src/cc/Hypertable/Lib:/opt/pypy2/bin:/root/builds/builts/hypertable/src/cc/Hyperspace:/root/builds/builts/hypertable/src/cc/Tools/Lib:/root/builds/builts/hypertable/src/cc/FsBroker/Lib:/root/builds/builts/hypertable/src/cc/AsyncComm:/root/builds/builts/hypertable/src/cc/Common:/root/builds/builts/hypertable/src/cc/ThirdParty: ../ThriftBroker/libHyperThrift.so ../Hypertable/Lib/libHypertable.so -lpypy-c -lthrift -lthriftnb -levent ../Hyperspace/libHyperspace.so ../Tools/Lib/libHyperTools.so -ledit ../FsBroker/Lib/libHyperFsBroker.so ../AsyncComm/libHyperComm.so ../Common/libHyperCommon.so -lexpat -lsigar-amd64-linux -ldl -lboost_iostreams -lboost_program_options -lboost_filesystem -lboost_thread -lboost_system -lboost_chrono -lboost_python -lpython2.7 -lz -lsnappy -lncurses -lpthread -lre2 -ltcmalloc_minimal -lunwind -lssl -lcrypto ../ThirdParty/libHyperThirdParty.so -lm


previously biggest mistake was the pypy lib and headers were missed -I/opt/pypy2/include

**Comment by kashirin-alex** [comment]
Thank You,
Kashirin Alex

**Comment by jagerman** [comment]
> previously biggest mistake was the pypy lib and headers were missed -I/opt/pypy2/include

There are still issues with your compilation; given the frenetic nature of your original post and solution, I'm a bit concerned that you're rushing this through rather than thinking carefully about how you're building things, and I urge you to slow down a little to save yourself time and effort in the future.

Some things to think about:
- it is definitely wrong to set `-DPYTHON_VERSION=2.7 -DPYPY_VERSION=1 -DWITH_THREAD`.  These *must* be set by the appropriate Python headers; if they aren't being set properly, there's something wrong with your include paths that specifying them in the compilation *cannot* fix.  Overriding them like you do *will* break something sooner or later.
- Python 2.7 .so modules in general shouldn't link to libpython2.7, and PyPy .so modules in general shouldn't link to libpypy-c.  PyPy modules *definitely* shouldn't link to *both* libpypy-c *and* libpython2.7.
- You would save yourself a good chunk of cmake code if you used the cmake scripts included and installed with pybind.  Those scripts are designed to get all the linking and flags correct.

**Comment by lironmo** [comment]
i have similar issue when i call from java to c++ and to python.
the c++ part to python work fine, but from java to c++ to python i get the following error:
Fatal Python error: PyThreadState_Get: no current thread

**Comment by kashirin-alex** [comment]
It is probable at include path for Java you need to include the correct Python/PyPy headers, at least that what was the specific error in the issue case

**Comment by lironmo** [comment]
I included them:
    set(PYTHON_INCLUDE_DIR /home/liron/anaconda2/include/python2.7)
    set(PYTHON_LIBRARY /home/liron/anaconda2/lib/python2.7/config/libpython2.7.a)
    set(PYTHON_EXECUTABLE /home/liron/anaconda2/bin/python)

    #find_package(PythonInterp REQUIRED )
    find_package(PythonLibs 2.7 REQUIRED)
    message(STATUS ++++++${PYTHON_INCLUDE_DIRS})
    include_directories(${PYTHON_INCLUDE_DIRS})

i have another c++ project that use the c++ shared object that call to python that work just fine.

the problem is when i call from java via JNI i get this error.

**Comment by lironmo** [comment]
first i tried with /home/liron/anaconda2/lib/libpython2.7.so instead of /home/liron/anaconda2/lib/python2.7/config/libpython2.7.a

and i get the following bug:
https://bugs.python.org/issue4434

**Comment by kashirin-alex** [comment]
if you have on your system a one Py Version, (may the issue is different)
while for Java,
include paths of C/C++ libs need to be set example, https://github.com/hyperic/sigar/blob/master/bindings/java/build.xml#L417
and if there are several Python.h files on your system, java selects first found

**Comment by kashirin-alex** [comment]
you can check on https://github.com/kashirin-alex/hypertable/blob/master/src/py/ht-package/setup.py.in
and try in building against static libraries with the "extra_objects" set .
that is without cmake file

**Comment by lironmo** [comment]
I have two Py versions,
i am a bit new at java - i have a gradle based project not sure where to include it.

and why the jave need this include, my program stack  look like:
Pure java main project load shared library (JNI)
The JNI build using SWIG over C++ header interface file
 The CPP interface implement with several freamworks (caffe/ tiny/ pytorch) - we only talk about the pytorch impl.
the implementation call python function using pybind11 library.

so it's seem to be contained in the shared library and not from the java

**Comment by kashirin-alex** [comment]
Just a check are there any linked libs in the library you build with c++ to
python,  ldd lib-name.so (there might be something else expected for java
to include)

**Comment by lironmo** [comment]
yes, there is .a lib that there i implemented the c++ interface.
but when i linked it to the .so it's supposed to be inside the .so

**Comment by kashirin-alex** [comment]
I can't be sure if that can help , cmake does define flags for static libs,
while you can define and assure with: `-Wl,--whole-archive YourLib.a -Wl,--no-whole-archive`

**Comment by lironmo** [comment]
tried -0 don't work same error
same error:
Fatal Python error: PyThreadState_Get: no current thread

something is not running current in the JNI because from my c++ project it's runs.

**Comment by kashirin-alex** [comment]
if caffe/ tiny/ pytorch surely include a py lib than definitely it should not be included statically in the C++ shared lib.
while have't tried (considering methods will be anyway available) 
if you do `-O3` for your shared lib it might in-line all and the Py methods and won't collide (might)

**Comment by lironmo** [comment]
i not fully follow.

maybe if i will able to add the shared python /home/liron/anaconda2/lib/libpython2.7.so - but i get the following bug :
https://bugs.python.org/issue4434

**Comment by lironmo** [comment]
thanks for pointed this script!
script output :
-lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic

i need to add it to .a lib or to JNI .so?

**Comment by kashirin-alex** [comment]
Was there any difference without using /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 in java 
running with link to a static or shared build ?

**Comment by lironmo** [comment]
yep , some .so like ld and util that were missing.

and i not sure why the satic pythonlib is under confi folder in conda distribution 

i have a workaround - i revert all the changes:
used the following link to debug the liberies loading - https://unix.stackexchange.com/questions/448964/how-do-i-trace-library-loading

i found problem loading the python .so:
/home/liron/anaconda2/lib/libpython2.7.so.1.0: error: symbol lookup error: undefined symbol: JNI_OnLoad (fatal)


and my workaround is to set
LD_PRELOAD=/home/liron/anaconda2/lib/libpython2.7.so

now it's work but i need to figure why the java load different python lib - what do you think?

**Comment by kashirin-alex** [comment]
with java,
it looks for libs in it's classpaths, eg -cp /home/liron/anaconda2/lib;/home/liron/anaconda2/lib/python2.7/dyn-lib  and the rest seperated by semi-colon

**Comment by lironmo** [comment]
this is without the workaround:
         15352:	find library=libpython2.7.so.1.0 [0]; searching
     15352:	 search path=/home/liron/anaconda2/lib/python2.7/lib-dynload/../../tls/x86_64:/home/liron/anaconda2/lib/python2.7/lib-dynload/../../tls:/home/liron/anaconda2/lib/python2.7/lib-dynload/../../x86_64:/home/liron/anaconda2/lib/python2.7/lib-dynload/../..		(RPATH from file /home/liron/anaconda2/lib/python2.7/lib-dynload/_locale.so)
     15352:	  trying file=/home/liron/anaconda2/lib/python2.7/lib-dynload/../../tls/x86_64/libpython2.7.so.1.0
     15352:	  trying file=/home/liron/anaconda2/lib/python2.7/lib-dynload/../../tls/libpython2.7.so.1.0
     15352:	  trying file=/home/liron/anaconda2/lib/python2.7/lib-dynload/../../x86_64/libpython2.7.so.1.0
     15352:	  trying file=/home/liron/anaconda2/lib/python2.7/lib-dynload/../../libpython2.7.so.1.0
     15352:	
     15352:	
     15352:	calling init: /home/liron/anaconda2/lib/python2.7/lib-dynload/../../libpython2.7.so.1.0
     15352:	
     15352:	
     15352:	calling init: /home/liron/anaconda2/lib/python2.7/lib-dynload/_locale.so
     15352:	
Fatal Python error: PyThreadState_Get: no current thread

**Comment by kashirin-alex** [comment]
is the C++ shared or static and was it linked with the same libpy ?
-- the only thing I can consider to check on.
