### ISSUE TITLE
std::variant of nontrivial types

### ISSUE THREAD

**Issue by classner** [pybind/pybind11#903]
Hi!

Thanks for the amazing work with pybind11! It's an incredible package and, having used the already very good boost python, I really appreciate the things you improved from there.

## Issue description

I just ran into a behavior which I'm not sure is intended. When using the std::variant support, it's possible to receive complex types from python or c++ and convert them into/from variant types. From how I read the implementation, it is intended to also be able to receive wrapped complex types from Python.

Whereas the conversion from c++ to Python of, e.g., a wrapped std::vector, works flawlessly, I am not able to push a vector from Python to c++.

## Reproducible example code

I am using mapbox variant implementation [here](https://github.com/mapbox/variant), but as far as I understand this shouldn't matter. The registration code is set up as described in the documentation and the conversion from c++ to Python is working flawlessly.

```
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
namespace py = pybind11;

PYBIND11_MODULE(tm, m) {
    m.def("test", [](const std::variant<std::vector<float>, std::vector<int>> &in) {
        std::cout << "received" << std::endl;
      });
}
```

```
import tm
tm.test([1, 2, 3])  # Fails.
```

**Comment by jagerman** [comment]
What failure are you getting?  I added this to the test suite, and it passes:

```C++
    m.def("vector_variant", [](const std::variant<std::vector<float>, std::vector<int>> &in) {
        if (auto *intv = std::get_if<std::vector<int>>(&in))
            return py::make_tuple("int vector", std::accumulate(intv->begin(), intv->end(), 0));
        auto &floatv = std::get<0>(in);
        return py::make_tuple("float vector", std::accumulate(floatv.begin(), floatv.end(), 0.0f));
    });
```

```Python
    assert vector_variant([1, 2, 3]) == ("int vector", 6)
    assert vector_variant([1.5, 10.0, 0.25, 1.0]) == ("float vector", 12.75)
```

**Comment by classner** [comment]
Thanks for coming back so quickly on this! Adding this again to my project and recompiling, it works. I realize I was getting the following warnings:

```
pybind11-v2.2/include/pybind11/cast.h:789:56: warning: type ‘struct type_caster’ violates the C++ One Definition Rule [-Wodr]
 template <typename type, typename SFINAE = void> class type_caster : public type_caster_base<type> { };

note: a type with the same name but different base type is defined in another translation unit
     struct type_caster<mapbox::util::variant<Ts...>> :

pybind11-v2.2/include/pybind11/stl.h:299:8: note: the incompatible type is defined here
 struct variant_caster<V<Ts...>> {
```

which makes total sense looking at the respective source files. I included my type caster specialization for variants now in all compilation units (independent on whether they use variants or not) and this warning vanishes and things work. I assume that the dual definition problem led to undefined behavior of the linker and I ended up with working or non-working conversions depending on linking order.

I didn't know that it's possible to have partial struct specializations with other base classes, so I learned something new! :-) Now I also understand that this is meant in the manual with "The above should be placed in a header file and included in all translation units where automatic conversion is needed", so, automatic conversion independent of whether variant is present or not. That might be very helpful as an additional hint in the manual.

Apart from that, thanks again, and feel free to close this issue.

**Comment by jagerman** [comment]
> I assume that the dual definition problem led to undefined behavior of the linker and I ended up with working or non-working conversions depending on linking order.

Yup, that's exactly what happened.  Without defining the specialization, if you try to use it it'll end up at the generic type caster, which won't work since that handles types registered with `py::class_`.  So you'd get a runtime failure if you didn't have the ODR problem; with the ODR violation, what you get is officially Undefined.
