### ISSUE TITLE
Feature request: std::string_view support

### ISSUE THREAD

**Issue by dirkvdb** [pybind/pybind11#905]
Any plans on supporting std::string_view as arguments? You already have great c++17 support with things like std::optional. std::string_view seems like a nice addition.

**Comment by jagerman** [comment]
This is a good idea, and should be pretty simple to implement.

**Comment by jagerman** [comment]
Merged.

**Comment by dirkvdb** [comment]
Excellent! Recently switched from boost python to pybind11. Never looking back :-) great job!
