### ISSUE TITLE
pybind11::array constructor does not support shape and strides of std::array

### ISSUE THREAD

**Issue by heavytail** [pybind/pybind11#933]
pybind11::array cannot find constructor for shape and strides of type std::array<std::size_t, 2>
```
include/foo.h:117:22: error: no matching function for call to ‘pybind11::array::array(std::array<long unsigned int, 2>&, std::array<long unsigned int, 2>&, double*)’
         return pybind11::array(shape,strides,source.data()).release();
```
Is it a bug or is it designed as not to accept shape of std::array?

**Comment by jagerman** [comment]
In 2.1.x and earlier, only `std::vector` or an initializer list were accepted.  In current master, any stl-like container should be accepted.

Closing (as something already fixed).  If this is happening for you with current `master`, please reopen.
