### ISSUE TITLE
GNUInstallDirs warning on CMake-3.8.2

### ISSUE THREAD

**Issue by patrikhuber** [pybind/pybind11#939]
I'm getting the following warning from pybind11 when I set a custom `CMAKE_INSTALL_PREFIX`:

```
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.8/Modules/GNUInstallDirs.cmake:246 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "lib" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  3rdparty/pybind11/CMakeLists.txt:67 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

It's coming from pybind11's `include(GNUInstallDirs)`. The offending line in GNUInstallDirs seems to be `elseif(DEFINED __LAST_LIBDIR_DEFAULT`. Not so sure what's going on.

Should I report this to upstream CMake?

**Comment by jagerman** [comment]
It looks like an upstream issue to me, especially since GNUInstallDirs is a core cmake module.

**Comment by patrikhuber** [comment]
Okay, let's close this then.

**Comment by patrikhuber** [comment]
I still got this error on CMake-3.10.0-rc1. It seems I never reported this issue. I did now: https://gitlab.kitware.com/cmake/cmake/issues/17381

Curious that nobody else encountered this yet.
