### ISSUE TITLE
Passing arguments when calling python functions

### ISSUE THREAD

**Issue by tkoch96** [pybind/pybind11#942]
Hello,

This is more of a question rather than an issue, but I am unable to access the Gitter behind a corporate firewall. 

I am trying to call a function I wrote in Python via Pybind. I am trying to pass this function an array of numbers (or some class that can act as one). I would like this array to be 2d, but a flattened 1d version works fine. I would also like to be able to accept return values from this Python function in C++. These return values would also be 1d or 2d arrays of numbers.

I am having trouble with the casting and type-conversion business. For example if data is a 1d array of floats I would like to do 
`py::object my_module = py::module::import("my_module");
py::object f = my_module.attr("my_function");
f(data)`

I have tried data in both the form of a 1d array of floats and a flattened Eigen matrix. I have also tried this with 2d objects. A typical error message I receive is:
'unable to convert arguments to Python object'.

On the other hand, when returning arguments I try the following code:
` py::object f = my_module.attr("give_me_array");
 py::object result = f();
std::vector<int> arr = result.cast<std::vector<int>();`

where the Python code I'm calling looks something like:
`def give_me_array():
return [1,2]`
A typical error message I receive is 'unable to cast Python instance to C++ type.

I have successfully tried the basic examples provided in the documentation such as calling add(1,2) in Python from C++ which produces 3 back in C++.  I don't understand what to do when it comes to anything more than the basic built in types. I am new to C++ so sorry if I am missing a big idea here.

**Comment by jagerman** [comment]
What is the specific type of `data` in your example?

If your C++ side is using Eigen arrays and your Python side is using numpy arrays, all you should need is an `#include <pybind11/eigen.h>` to get transparent conversion between them.  You can even get mutable references both ways (with some caveats--see [the docs on the Eigen support](http://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html)).

Casting to/from stl containers like `std::vector` similarly requires a `#include <pybind11/stl.h>`.

**Comment by tkoch96** [comment]
Thank you! Turns out I was leaving out that pybind11/eigen.h file and the pybind11/stl.h file for my tests. Now the implementation using MatrixXd works.

The type of 'data' above was an c-type array of floats or doubles. When I call f(data), only the first element of the array gets sent through to Python instead of the whole array. I assume this has to do with the fact that data is a pointer to the first element. If you could point out a way to remedy this, I'd appreciate it.

So an update is that using Eigen for my purposes works great, while using the built in C-types does not. Using Eigen is good enough for me though.

**Comment by jagerman** [comment]
Indeed, this is a limitation: C-style arrays are treated like pointers; there is no way to deduce the length of a returned C-style array, and so no way to automatically bind it.  If you need to work with them, you'll have to use wrapper functions that know the size, such as:

```C++
// Returns c-style int[5]:
m.def("func_a", []() { int *ret = func_a(); return std::vector<int>(ret, ret + 5); });
// Takes c-style int[5]:
m.def("func_b", [](std::array<int, 5> a) { return func_b(a.data()); });
```

**Comment by tkoch96** [comment]
Thank you very much.
