### ISSUE TITLE
[regression] calling function with object of derived class: Unable to load a custom holder type from a default-holder instance

### ISSUE THREAD

**Issue by nschloe** [pybind/pybind11#956]
In pybind11 2.0.1, calling a function of a derived class works as expected, e.g.,
```c++
struct Base {};
struct Deriv: Base {};
void show(std::shared_ptr<Base> & b) {return;}

PYBIND11_PLUGIN(foo) {
    py::module m("foo");

    py::class_<Base>(m, "Base")
          .def(py::init<>());
    py::class_<Deriv, Base>(m, "Deriv")
          .def(py::init<>());
    m.def("show", &show);
}
```
```python
import foo
d = foo.Deriv()
foo.show(d)
```
Since pybind11 2.1.0, this gives the Python error
```
RuntimeError: Unable to load a custom holder type from a default-holder instance
```

**Comment by jagerman** [comment]
The error is happening because the default holder for pybind classes is `std::unique_ptr`, which can't be converted to a `shared_ptr`.  2.1 added detection and failure for this; I'm not entirely sure what would have happened in 2.0 (perhaps a double free?).

The easiest fix is to change the holder on the registered types to `shared_ptr` with:

```C++
py::class_<Base, std::shared_ptr<Base>>(...);
py::class_<Derived, Base, std::shared_ptr<Derived>>(...);
```

(On a separate note, you'll want to make sure `Base` has a virtual destructor for anything more than a trivial class.)

**Comment by nschloe** [comment]
Thanks, this fixes it.

**Comment by freakeinstein** [comment]
It worked! hurrey..

**Comment by xealits** [comment]
A comment on this topic, hopefully it will be useful to someone. What if `Base` is an abstract class and you use only its implementations in Python, never the abstract class itself. But some C++ functions accept the abstract class. To keep the binding code at minimum, this just worked for me:

```
class Base {
    virtual void set(int) = 0;
};
class Deriv: Base {
    void set(int foo) {m_foo = foo};
private:
    int m_foo;
};
void show(std::shared_ptr<Base> & b) {return;}

PYBIND11_MODULE(foo, m) {
    py::class_<Base, std::shared_ptr<Base>>(m, "Base") ; // <--- even without the constructor

    py::class_<Deriv, Base, std::shared_ptr<Deriv>>(m, "Deriv")
          .def(py::init<>())
          .def("set", &Deriv::set)
          ;

    m.def("show", &show);
}
```
Quite brilliant! I was expecting to have to override all the virtual methods etc.

One thing to add, it would be nice to mention which class causes the exception in "Unable to load a custom holder type from a default-holder instance". Like when you omit the `shared_ptr` in the `Base` class, the exception states class names explicitly:

```
ImportError: generic_type: type "Deriv" has a non-default holder type while its base "Base" does not
```

(I'll try to send a merge request for this tomorrow.)

**Comment by stellarpower** [comment]
Slightly tangential, but I have encountered some similar difficulties. My solution (so far, I don;t think it'll break, but we will see) is just to proxy to C++ via a value type.

So I export to Pybind a simple value-type that contains one `shared_ptr` to the base class of my tree. I am parsing mathematical expressions, so, I have a lot of base classes form this and covariant return types through smart pointers. The advantage of this is that Pybind never even needs to see this, as it's all hidden through the composition.

By adding this layer of indirection, we can keep all this complexity in the C++ side, and the type exposed to python needs no polymorphism, no factories, no covariant returns, etc. Each method it just delegates out to the implementation, receives a shared pointer of some derived type back, and wraps in a new instance of its own type, so what goes back over the fence is homogeneous.

And pybind/Python can handle this type however it wants. It doesn't really matter if it treats it by value or shares pointers to it. We simply know that the lifetime of this object will correctly control the lifetime of the `shared_ptr` member it contains, and this in turn will properly manage the lifecycle of the implementation - but this second part all staying on the C++ side. 

I may end up having missed something here, but just thought I'd share as a design pattern. We need something up and running quickly, and placing a separation between two separate things (managing the complexities in the C++ code and how memory is managed across to the Python side of things) is helpful for us here, even if a bit more verbose.
