### ISSUE TITLE
PYBIND11_MODULE breaks when including third-party library in Cmake

### ISSUE THREAD

**Issue by ncullen93** [pybind/pybind11#976]
I get an error on the master branch only when I include ITK:

```
cmake_minimum_required(VERSION 3.0)
project(mymodule)

find_package(ITK REQUIRED)
include(${ITK_USE_FILE}) # breaks when I include this 

add_subdirectory(pybind11)

pybind11_add_module(mymodule mymodule.cpp)
target_link_libraries(mymodule PRIVATE ${ITK_LIBRARIES})
```

Gives me the following error:

```
/Users/ncullen/desktop/test/mymodule.cpp:13:17: error: C++ requires a type
      specifier for all declarations
PYBIND11_MODULE(mymodule, m) {
                ^
/Users/ncullen/desktop/test/mymodule.cpp:13:27: error: unknown type name 'm'
PYBIND11_MODULE(mymodule, m) {
...
...
...
/Users/ncullen/desktop/test/mymodule.cpp:15:25: error: use of undeclared
      identifier 'm'
    py::class_<Wrapper>(m, "Wrapper");
```

Includes look like this:

```cpp
#include <iostream>
#include <pybind11/pybind11.h>
#include "itkImage.h"

namespace py = pybind11;
```

Thanks for the help :)

**Comment by garth-wells** [comment]
Try
```
target_link_libraries(mymodule PRIVATE pybind11::module ${ITK_LIBRARIES})
```

**Comment by ncullen93** [comment]
thank you for the response! didn't work unfortunately :( it still fails even if i take out the `target_link_libraries` statement completely and leave in `include(${ITK_USE_FILE})`. It works fine with the old way of PYBIND11_PLUGIN

**Comment by jagerman** [comment]
If `PYBIND11_PLUGIN` works, then it sounds as though the ITK parts are changing the include paths to include something that has an old version of pybind (perhaps installed in a system path).  Does it make any difference if you move the `add_subdirectory(pybind11)` earlier?

**Comment by ncullen93** [comment]
damn yeah i just hit `pip uninstall pybind11` and then it worked. thank you, guru.
