### ISSUE TITLE
Incompatible constructor arguments with std::vector<uint8_t>

### ISSUE THREAD

**Issue by DarkZeros** [pybind/pybind11#993]
Hi,

I am having issues with this data type, am I calling it wrong? Or compiling it wrong? It works fine under my C++ application but not when called in pybind11.

Code:
```
#include <pybind11/pybind11.h>
namespace py = pybind11;
#include "boo.h"
PYBIND11_MODULE(foo, m) {
    m.doc() = "foo library"; // optional module docstring
    py::class_<boo>(m, "boo")
        .def(py::init<uint8_t, std::vector<uint8_t>, uint8_t>())
    ;
}
```

Header:
`    boo(uint8_t, const std::vector<uint8_t> &, uint8_t, const std::vector<uint8_t>& a = std::vector<uint8_t>());`

Compile:
`g++ -fpermissive -O3 -std=c++11 -I ~/dev/pybind11/include/ -I/usr/include/python2.7 boo.cpp -lpython2.7 -shared -fPIC -o foo.so`

Run:
```
>>> import foo
>>> foo.boo(3,[3,3],1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. foo.boo(arg0: int, arg1: std::vector<unsigned char, std::allocator<unsigned char> >, arg2: int)
Invoked with: 3, [3, 3], 1

```

Note: I replaced the original parameters and class names.

**Comment by YannickJadoul** [comment]
Did you include `<pybind11/stl.h>`?

**Comment by DarkZeros** [comment]
No, and .... now my problem is fixed!
Thanks, so easy.
